lib/elixir/lib/enum.ex
It should return {:ok, count} when we can count the number of elements
without traversing the enumerable.
=> Be clearer about Enumerable.count/1 implementations

lib/elixir/lib/regex.ex, lib/elixir/test/elixir/regex_test.exs
This MR adds the [offset option](https://erlang.org/doc/man/re.html#run-3) to be internally used by `:re.run/3` in `Regex.scan/3` and `Regex.run/3` functions. 
The offset option specifies the starting position of the string in which the regex should start matching. It is different from simply slicing the string because of the `^` matcher:
```elixir
str = "foobar"
sliced_str = String.slice(str, 3, 3)
Regex.run(~r{^bar}, sliced_str) == ["bar"]
Regex.run(~r{^bar}, str, offset: 3) == nil
``` 
[(A more detailed example from python re docs, the offset is equivalent to the `pos` parameter there.)](https://docs.python.org/3/library/re.html#re.Pattern.search)
The offset option is somewhat already present in `Regex.scan` and `Regex.run` - it is just always implicitly defaulted to zero.
=> Add offset option to Regex.scan/3 and Regex.run/3

bin/elixir
It conflicted with the erl executable for Korn-derived shells where a function
can be used in `exec command`.
It isn't clear which behavior is expected from reading the POSIX specification
but "Shell Command Language § 2.9.1 Simple Commands" clears the usage of
the term `command` quite well.
And even with excluding functions from the `command` operand of `exec`,
why are aliases accepted? (in most if not all shells)
See: https://bugs.gentoo.org/729964
=> bin/elixir: Rename erl() function to erl_set()

lib/elixir/lib/enum.ex
Mention that when we say that "you can count" is
without traversing the whole collection.
This was left out in 4a1e4481a3714cc48597b6f55242ca6413cade4d
=> Add left out clarification in Enumerable count

lib/elixir/lib/map_set.ex
The v2.0 could be interpreted as if it's referring to the defstruct version, which by the way it is already number 2.
=> Make comment unambiguous

lib/eex/lib/eex/compiler.ex, lib/eex/test/eex/smart_engine_test.exs
This PR adds a new compilation error when EEx encounters a `do` expression without the `<%=` modifier, since this is nearly always unintentional. For example, take this block:
```eex
<% if @password %>
Temporary Password: <%= @password %>
<% else %>
Sign in with your existing password.
<% end %
```
At first glance, all seems well, and in the context of a full application it may take quite some time to work out that nothing is being output because you're missing the `<%=` opening tag. The only case I can think of where a `do` block is valid without the `<%=` opening tag is something like this:
```eex
<% if @condition do %>
<% some_side_effect() %>
<% end %>
```
...but this could trivially be refactored to the (IMO) cleaner:
```eex
<% if @condition do
some_side_effect()
end %>
```
Credit to …
=> generate error for unused "do" expression in EEx

lib/mix/test/mix/cli_test.exs, lib/mix/test/test_helper.exs
I got several tests in `lib/mix/test/mix/cli_text.exs` failed when I had an environment variable named `MIX_TARGET` with a non-empty value (e.g. `rpi3` for Nerves). It's because tmporary directories are created with wrong names like `_build/rpi3_test/lib/` not as `_build/test/lib/.`
```shell
$ bin/elixir lib/mix/test/mix/cli_test.exs
Excluding tags: [windows: true]
.
1) test default task (Mix.CLITest)
lib/mix/test/mix/cli_test.exs:8
Expected truthy, got false
code: assert File.regular?("_build/dev/lib/p/ebin/Elixir.A.beam")
stacktrace:
lib/mix/test/mix/cli_test.exs:18: anonymous fn/0 in Mix.CLITest."test default task"/1
(elixir 1.12.0-dev) lib/file.ex:1554: File.cd!/2
lib/mix/test/test_helper.exs:126: MixTest.Case.in_fixture/3
lib/mix/test/mix/cli_test.exs:9: (test)
2) test new --sup with …
```
=> fix test failures when `MIX_TARGET` is set with a non-empty value

lib/elixir/lib/task.ex
before it read:
> Another consideration to have in mind is that tasks are always linked to their callers
This isn't true for e.g. `Task.start`. However, since it's docs for `await/2`, I guess it is implied that we're talking about tasks started by `async/1`, I thought it might be worth clarifying but maybe it's unnecessary :)
=> Update Task.async docs

lib/elixir/lib/kernel/special_forms.ex
I've stumbled upon this case couple of days ago when I wanted to use multiple match options but for some reason couldn't remember the correct syntax.
My first thought was to inspect documentation for `case` but I didn't find how to write `case` statement in order to support multiple matches in one expression.
I think this case is common enough to consider adding it as part of documentation.
Here is couple of links to support "common enough" statement.
- https://stackoverflow.com/questions/39139814/elixir-how-to-test-multiple-values-in-case-condition, _60 votes_
- https://elixirforum.com/t/pattern-match-with-multiple-match-options/9907/7, _8,4k views_
=> documentation for multiple match options using case statement

lib/elixir/lib/kernel.ex
Hi,
I found using `Keyword` lists to pass grouped parameters is the [preferred choice](https://elixirforum.com/t/passing-in-options-maps-vs-keyword-lists/1963) over `Map` because of keyword list benefits
* keys must be atoms
* keys can be given more than once
* keys are ordered, as specified by the developer
I think new Elixir developers will benefit from extended documentation how to define functions using keyword lists with default attributes.
=> Add documentation for Keyword lists with default arguments

lib/elixir/lib/path.ex, lib/elixir/test/elixir/path_test.exs
Hello, 
Unless my reasoning is wrong, there might be a bug
in `Path.relative_to/2` implementation.
The assumption I'm making is `relative_to` should always
return a path of type `:relative`.
Thus, if `relative_to` argument points at `path`, the
result should be relative.
Currently it's:
iex(1)> Path.relative_to('/foo/bar', '/foo/bar') |> Path.type()
:absolute
This patch fixes it, so it's:
iex(1)> Path.relative_to('/foo/bar', '/foo/bar')
"."
iex(2)> Path.type(v(1))
:relative
Similar code in python:
In [1]: os.path.relpath('/foo/bar', start='/foo/bar')
Out[1]: '.'
And in ruby:
> Pathname.new('/foo/bar').relative_path_from(Pathname.new('/foo/bar')).to_s
=> "."
=> Fix `Path.relative_to/2` when referencing self

lib/elixir/lib/protocol.ex, lib/elixir/test/elixir/protocol_test.exs
Add to the list: defexception/1, defdelegate/2, defguard/1, defguardp/1
=> Extend functions/macros not allowed inside Protocols

lib/elixir/lib/kernel.ex
x is not used anywhere in the specs. Use name of argument instead.
/cc @Eiji7, @v0idpwn
=> Stremaline specs in Kernel.{tap, then}/2

lib/elixir/lib/kernel.ex
Caught this while having a look at the `Kernel.then/1` PR
Thank you for adding it!
=> fix small typo in pipe operator's doc

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
Since [`Macro.decompose_call/1`](https://hexdocs.pm/elixir/Macro.html?#decompose_call/1) is exported and documented, it would make sense to explicitly handle the case of passing quoted regular tuple as an argument, returning `:error` as it does for any other garbage (neither local nor remote call.)
=> Return :error on decomposing regular tuples as calls

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
I found trying to understand `Enum.chunk_while/4` quite confusing, and needed to resort to reading the code to understand how the `after_fun` param semantics are intended to work. Have added my understanding to the docs for it, and made a couple of improvements to code readability, and added a couple of test cases covering extra cases.
- Updated docs to clarify
- add `{:halt, acc}` tuple return doc for `chunk_fun`
- explain `after_fun` semantics in more detail
- format return tuples for `chunk_fun` and `after_fun` as markdown lists
- added note that `acc` in `after_fun` return tuple is ignored
- state `Enum.chunk_while/4` returns a list of *chunks*, not a list of lists (emitted chunks can be anything, not necessarily just lists)
- added example showing `after_fun`'s behaviour more clearly …
=> Improve Enum.chunk_while/4 docs to clarify `after_fun` semantics

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/protocol_test.exs
When defimpl/3 is defined outside a module without a :for option, such as in the code bellow,
it will five a cryptic error.
```elixir
defprotocol A do
def ok(term)
end
defimpl A do
def ok(term), do: {:ok, term}
end
```
BEFORE FIX:
```
19:42:16.595 [error] Task #PID<0.187.0> started from #PID<0.95.0> terminating
** (CaseClauseError) no case clause matching: {:error, :not_a_protocol}
(mix 1.11.2) lib/mix/tasks/compile.protocols.ex:141: Mix.Tasks.Compile.Protocols.consolidate/4
(elixir 1.11.2) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
(elixir 1.11.2) lib/task/supervised.ex:35: Task.Supervised.reply/5
(stdlib 3.13.2) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: #Function<9.81221892/0 in Mix.Tasks.Compile.Protocols.consolidate/6>
Args: []
** (EXIT from #PID<0.95.0>) an …
```
=> Fix cryptic error when defimpl is defined without :for option

lib/elixir/lib/calendar.ex
Make day of month documentation more clear
Show example while removing padding from day
At first glance, I saw the example in the days column as "01, 12" which made more sense as a month.
Also, I thought it would be nice to add an example with the padding removed.
=> Enhance Calendar.strftime docs

lib/elixir/lib/string.ex
For 1000 bytes string, a very simple benchmark on my computer shows that it's ~20% faster.
```
iex> Enum.map(1..5000, fn _ -> :timer.tc(fn -> A.valid?(data) end) |> elem(0) end) |> Enum.sum()
678553
iex> Enum.map(1..5000, fn _ -> :timer.tc(fn -> String.valid?(data) end) |> elem(0) end) |> Enum.sum()
868434
```
=> Optimize String.valid?

lib/elixir/unicode/unicode.ex
Benchmarking against the following script. It seems to be more efficient in memory and speed.
```elixir
inputs =
%{
"Short ASCII" => "abcdefghjklmnopqrstuvwxyz",
"Short UTF-8" => "葡萄美酒夜光杯 欲饮琵琶马上催 醉卧沙场君莫笑 古来征战几人回",
"Long ASCII" => String.duplicate("abcdefghjklmnopqrstuvwxyz", 1000),
"Long UTF-8" => String.duplicate("葡萄美酒夜光杯 欲饮琵琶马上催 醉卧沙场君莫笑 古来征战几人回", 1000),
}
bench_options = [
time: 5,
memory_time: 2,
inputs: inputs
]
Benchee.run(
%{
"String (master)" => fn input -> String.codepoints(input) end,
"String (qcam)" => fn input -> String2.codepoints(input) end
},
bench_options
)
```
```
Operating System: macOS
CPU Information: Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz
Number of Available Cores: 4
Available memory: 16 GB
Elixir 1.10.2
Erlang 23.0.3
Benchmark suite executing with the following …
```
=> Optimize String.codepoints

lib/elixir/lib/registry.ex, lib/elixir/test/elixir/registry_test.exs
The original use case here is enabling a tuning option for Absinthe subscriptions. In testing this can improve memory usage by 3x for workloads where individual users submit a lot of subscriptions and therefore there is a lot of duplicate context content. Chatted w/ Jose about this a month or so ago, finally getting around to messing with it.
=> Support compression on Registry

lib/elixir/lib/regex.ex
#10500 was shared in _Elixir Weekly, issue 232_ on December 24th, so I read the story and looked at the PR more than a month after it was merged! Looking at the diff, I realized the `is_function` guard was now useless because it was transferred to the `precompile_replacement/1` function.
We can get rid of the guard, the function header and the private `do_replace/4` all at ounce.
🎩 to @dsdshcym for encouraging me to push my first (of I hope many) PR to the language!
=> Refactor replace/4 to remove guards on replacement parameter

lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/test/ex_unit/case_test.exs
Hi folks,
Hope you're doing well :D
Yesterday I got bitten by a small "typo" I made Friday and although it didn't take me long to figure out my mistake, I think folks new to Elixir/ExUnits inner working might take longer to figure it out. I hope we can address that by returning a more "friendly" error. Please consider this PR as proposed solution, I'm open to discuss/change it. Also I didn't take the official route by discussing this first on ML, so feel free to close this for whatever reason you see fit 
My example:
```elixir
setup do
user = Thing.AuthFixtures.user_fixture()
[user: user]
end
test "list_invites/0 returns all invites", user: user do
assert ...
end
```
> ## output
> 
> 1) test invites list_invites/0 returns all invites (Thing.AccountsTest)
> test/thing/accounts_test.exs:19 …
=> Prevent using wrong test context

lib/mix/lib/mix/tasks/release.init.ex
Combining dd, od and awk with the common arguments found in busybox and GNU coreutils as well BSD the function rand() can make correct id.
This is based on
https://github.com/erlware/relx/commit/200e12815ef665338cea1280244e9c4f9dfa06b9
and
https://github.com/erlware/relx/pull/828
I ran into this when adding a mix release to a minimal yocto image using https://github.com/meta-erlang/meta-erlang and a busybox with undefined CONFIG_DESKTOP.
=> Make mix.release script rand() work with busybox

lib/mix/test/mix/tasks/deps_test.exs
The warning would be:
hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint:
hint: 	git config --global init.defaultBranch <name>
hint:
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint:
hint: 	git branch -m <name>
=> Remove warnings in test in latest Git version

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel_test.exs
This PR is a proposal for discussion. The original discussion on the mailing list can be found [here](
https://groups.google.com/u/1/g/elixir-lang-core/c/OhtFggrEHfU/m/BO6x5XleDAAJ)
The idea is to make `Kernel.tap/2` and `Kernel.then/2` macros instead of functions, in order to remove the runtime overhead.
This might be an overkill optimization, but since it is in the Kernel I thought it could make sense.
Looking forward to knowing your thoughts!
=> [Proposal] Make tap/2 and then/2 macros

lib/mix/lib/mix.ex, lib/mix/test/mix_test.exs
Proposal: https://groups.google.com/g/elixir-lang-core/c/q0k2dX992HU
=> Add Mix.install/2

lib/mix/test/mix_test.exs
Thanks for the `Mix.install/1`! :raised_hands:
=> Fix typo (`s/InstalTest/InstallTest`)

lib/elixir/lib/gen_server.ex
I guess that the original text was introduced before
`handle_continue/2`, but now the `GenServer` behaviour define 8
callbacks:
* code_change/3
* format_status/2
* handle_call/3
* handle_cast/2
* handle_continue/2
* handle_info/2
* init/1
* terminate/2
=> chore: fix callbacks amount in GenServer docs

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel/impl_test.exs
Fixes #10593
Fixing bug #10593 unveiled another bug, which is that we are not setting the context as the one where `defdelegate/2` is being called from so since the macro is defined in Kernel, this is the module that was being set.
That is fixed, but the commit fixes the initial issue publish, but when using a behaviour instead of a protocol, it will not work.
The best solution which will be more performant is if we can annotate the AST code generated by the `defdelegate/2` macro with the keyword `delegated: true, but updating the meta field in the AST when returning did not work.
=> Fix `@impl` warning when defdelegate is used

lib/ex_unit/lib/ex_unit/assertions.ex, lib/ex_unit/test/ex_unit/assertions_test.exs
This will interpolate the value of module attributes in match assertions
in ExUnit. Basically, the old diff would look like this:
```
1) test assert match with module attribute (ExUnit.AssertionsTest)
test/ex_unit/assertions_test.exs:186
match (=) failed
code:  assert {2, @test_mod_attribute} = Value.tuple()
left:  {2, @test_mod_attribute}
right: {2, 1}
stacktrace:
test/ex_unit/assertions_test.exs:187: (test)
```
And now it will look like this:
```
1) test assert match with module attribute (ExUnit.AssertionsTest)
test/ex_unit/assertions_test.exs:186
match (=) failed
code:  assert {2, @test_mod_attribute} = Value.tuple()
left:  {2, 2}
right: {2, 1}
stacktrace:
test/ex_unit/assertions_test.exs:187: (test)
```
Resolves #10675
=> Interpolate module attributes in match assertions

lib/elixir/lib/calendar/iso.ex
This makes it more clear how we've chosen to support ISO 3601.
Other changes targeted for this PR, per discussion on [the mailing list](https://groups.google.com/g/elixir-lang-core/c/CcXpeMQhsmU/m/o2b2_HM6DwAJ) and predecessor #10687:
=> Improve Calendar.ISO documentation.

lib/elixir/lib/calendar/iso.ex, lib/elixir/test/elixir/calendar/iso_test.exs
The `Calendar.ISO` string parsing function's examples have gotten pretty verbose, and increasingly unit-testy.
This PR uses the improved `Calendar.ISO` moduledocs from #10689 as a place to shift some of those doctests, and places other unit-testier ones into the test suite, making for much easier to read documentation around them.
- Doctests demonstrating how we've chosen to implement ISO 8901 have been moved to the ISO 8901 compliance section of the moduledocs.
- Functions that had doctests oriented around demonstrating our compliance now link back up to the ISO 8901 moduledoc.
- Doctests that flex edge cases or demonstrating failure modes have mostly been moved to the test suite.
- Doctests showing off happy path usage or common typo-caused failure modes remain, and are not lost in …
=> Rework Calendar.ISO parsing function tests and examples

lib/elixir/lib/calendar/iso.ex, lib/elixir/test/elixir/calendar/date_test.exs, lib/elixir/test/elixir/calendar/iso_test.exs, lib/elixir/test/elixir/calendar/naive_datetime_test.exs, lib/elixir/test/elixir/calendar/time_test.exs, lib/elixir/test/elixir/kernel_test.exs
This PR adds support for an optional second parameter to `Calendar.ISO` parsing functions, allowing them to parse the `:basic` format as well as the (default) `:extended`.
=> Support basic datetime format in Calendar.ISO parsing functions

lib/elixir/lib/enum.ex
Hi! This might be a controversial PR, I'm opening it for discussion.
I found out that the use of the identity function as a default param (`fun \\ fn x -> x end`) for functions that are iterating over a collection, especially in the `Enum` module, can be adding quite some overhead in some cases.
For most functions which are building some new data structures, like `Enum.group_by/2`, this overhead is fairly small.
But for functions that are mostly reading, the speedup obtained by declaring different arity functions separately is pretty huge:
- [a dedicated Enum.all?/1 is about 3x faster than the current one](https://github.com/sabiwara/elixir_benches/blob/main/bench/fast_enum_all.results.txt) for lists
- [:lists.max/1 is about 4.5x faster than …
=> Make Enum.any?/1 and Enum.all?/1 faster

lib/elixir/lib/enum.ex
Hi!
This change should yield a ~4.5x speedup for lists according to [this benchmark](https://github.com/sabiwara/elixir_benches/blob/main/bench/enum_max.results.txt).
It is a bit tricky to add clauses to these functions given how the double defaults are set, but I think this change is quite small and optimizes for the more important use cases (non-empty lists, with or without `empty_fallback`).
If we want to optimize other enumerables, it should be possible as well but it would be a bigger change with much duplication (and probably a less noticeable impact).
=> Speedup Enum.min/1 and Enum.max/1 for lists

lib/mix/lib/mix/tasks/test.ex
This does not change the way the `mix help test` or the docs for Mix.Tasks.Test
look in ExDoc or IEx. It just makes the code more readable.
=> Minor fix: remove/add new lines in Mix.Tasks.Test moduledoc

lib/elixir/src/elixir_erl_compiler.erl, lib/elixir/test/elixir/kernel/warning_test.exs
Since https://github.com/erlang/otp/commit/8ecc648df22dbfe9dd68a3e2b968ba2b6a2ca7fe instead of `{eval_failure, Reason}` we'd get `{eval_failure, Call, Reason}`.
=> Update Erlang warnings translation

lib/mix/lib/mix/release.ex, lib/mix/test/mix/release_test.exs
If a non-beam file in the ebin directory had execute permissions set,
those were lost when making a release. This switches the copy function
to `File.cp!/3` to preserve permissions.
Specifically, this affects the use of zigler with Nerves. Zigler
generates NIF shared libaries and stores them in the `ebin` directory.
The shared libraries had their execute mode bit set, but lost it on the
copy to the release. This affected the Nerves post-processing of all
firmware executables since Nerves uses the execute bit to identify
files that should be processed.
This also switches the copy call to the raising version like is done
when writing `.beam` files for consistency.
=> Preserve file mode when copying non-beam ebin files

lib/ex_unit/lib/ex_unit/doc_test.ex
The `either` is left over from a doc refactor. Also reworks the sentence to read a bit smoother.
=> Minor typo fix in ExUnit.DocTest moduledocs

lib/elixir/lib/gen_server.ex
I believe that the last element of the original list didn't fit the description of "if a callback (except `c:init/1`) does one of the following:".
Thank you for reviewing.
=> Fix logic error in docs of GenServer's c:terminate/2

lib/elixir/lib/gen_server.ex
Sorry I had a typo in my prev pull request.
Thank you for reviewing.
=> Fix typo in GenServer docs

lib/mix/lib/mix/compilers/erlang.ex, lib/mix/test/mix/umbrella_test.exs
The compiler previously emitted just `line` and now emits `{line, column}`.
The diagnostic struct accepts as position either:
nil
line
{start_line, start_col, end_line, end_col}
so we could have used the `column` to create the 4-tuple but we don't have enough information to do that correctly, we don't know where the column or line ends.
=> Fix translating erl compiler errors to diagnostics on OTP 24

lib/mix/lib/mix/compilers/erlang.ex, lib/mix/test/mix/tasks/compile.yecc_test.exs
Yecc error message changed so we need to loosen up our assertion:
OTP 23
iex> iex
Erlang/OTP 23 [erts-11.1.7] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Interactive Elixir (1.11.3) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :yecc.file('f.yrl')
f.yrl:1: syntax error before: '.'
:error
OTP 24
iex> iex
Erlang/OTP 24 [DEVELOPMENT] [erts-11.1.7] [source-802d2c5083] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1]
Interactive Elixir (1.12.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :yecc.file('f.yrl')
f.yrl:1:5: syntax error before: .
:error
=> Fix remaining warning translations for OTP 24

lib/elixir/lib/task/supervised.ex
Hi,
I found a memory leak issue when running Task.async_stream/2 with `ordered` options turned off for fetching large external data.
i can replicate with this code:
```
stream = Task.async_stream(
Stream.cycle([1]),
fn _ ->
Enum.map(1..1000, &(&1))
end,
max_concurrency: 10,
ordered: false,
timeout: 60_000
)
Stream.run(stream)
```
below attached memory usage from observer tool.
if my understanding is correct, the `waiting` map that stores the response from task should be cleaned like when `ordered` options turned on in [here](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/task/supervised.ex#L400). Currently, it is not cleaned and leads to the response piling up and causing a memory leak.
These changes clean up the `waiting` map that has been delivered to the reducer …
=> Cleanup waiting map on Task.Supervised.stream/6

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/fixtures/dialyzer/is_struct.ex, lib/elixir/test/elixir/kernel/dialyzer_test.exs, lib/elixir/test/elixir/kernel_test.exs
The macro expansion for `is_struct/2` includes a `case` that checks for whether the second argument (`name`) is an atom, and raises `ArgumentError` if not. This is sometimes, maybe even usually, known at compile time, and the second clause of the generated case is simply dead code. Dialyzer warns about this.
```
The pattern
:variable_
can never match, because previous clauses completely cover the type
MyApp.MyModule.
```
The change is simply to check to see whether "name" is known to be an atom at compile-time, and if so not to generate the case at all but simply perform the map `__struct__` key check.
=> Shorten is_struct/2 Macro Expansion for Atom Literals

README.md, lib/elixir/lib/kernel.ex, lib/elixir/lib/kernel/special_forms.ex, lib/elixir/lib/process.ex, lib/elixir/pages/library-guidelines.md, lib/elixir/pages/syntax-reference.md, lib/mix/lib/mix/tasks/archive.build.ex, lib/mix/lib/mix/tasks/release.ex
It removes the use of indiscriminate title casing :P
Pages titles in Elixir pages are not title cased.
=> Revise use of link titles

lib/elixir/lib/application.ex, lib/elixir/lib/code.ex, lib/elixir/lib/gen_server.ex, lib/elixir/lib/kernel/special_forms.ex, lib/elixir/lib/string_io.ex, lib/elixir/lib/system.ex, lib/elixir/pages/typespecs.md, lib/mix/lib/mix/tasks/profile.fprof.ex, lib/mix/lib/mix/tasks/release.ex, lib/mix/lib/mix/tasks/release.init.ex, man/mix.1
Consistently use https://erlang.org
See also ExDoc PR: https://github.com/elixir-lang/ex_doc/pull/1335
=> Update erlang.org links

lib/elixir/lib/enum.ex
HI!
Similarly to previous PRs on `Enum.max/1` and `Enum.any?/1`, I noticed that `Enum.dedup/1` could also be implemented in a much more efficient way, since `Enum.dedup_by/2` needs to:
- call identities `fun` at every step
- use a tuple as `acc` instead of just a list
My [benchmarks](https://github.com/sabiwara/elixir_benches/blob/main/bench/fast_enum_dedup.results.txt) suggest a significant performance boost disregarding (either if there are duplicates or not), and the boost seems to be even more important [with the JIT](https://github.com/sabiwara/elixir_benches/blob/2f4e6bab25ee4a9ed97b0af108d65190e6ebcaef/bench/fast_enum_dedup.results.txt).
=> Optimize Enum.dedup/1

lib/elixir/lib/kernel/special_forms.ex, lib/elixir/src/elixir_bitstring.erl, lib/elixir/test/elixir/kernel/expansion_test.exs
Ref: https://github.com/erlang/otp/pull/2890
On OTP 24:
iex> <<x::float-16>> = <<60, 0>>
iex> x
1.0
iex> <<x::float-16>>
<<60, 0>>
iex> <<1.0::float-128>>
** (CompileError) iex:1: float requires size*unit to be 16, 32, or 64 (default), got: 128
Before OTP 24:
iex> <<x::float-16>> = <<60, 0>>
** (CompileError) iex:1: float requires size*unit to be 32 or 64 (default), got: 16
iex> <<1.0::float-16>>
** (CompileError) iex:1: float requires size*unit to be 32 or 64 (default), got: 16
=> Support 16bit floats in bitstrings

lib/mix/lib/mix/tasks/compile.erlang.ex, lib/mix/test/mix/tasks/compile.erlang_test.exs
Before OTP 24 when given invalid args, :compile.file/2 would return:
iex(1)> :compile.file('a.erl', [{:d, 'foo', 'bar'}, :report])
{:error, :badarg}
On OTP 24:
iex(1)> :compile.file('a.erl', [{:d, 'foo', 'bar'}, :report])
*** Internal compiler error ***
exception error: bad argument
in function  io_lib:format/2
called as io_lib:format("badly formed '~s'",[{"foo","bar"}])
in call from sys_messages:list_errors/3 (sys_messages.erl, line 53)
in call from lists:foreach/2 (lists.erl, line 1342)
in call from compile:comp_ret_err/1 (compile.erl, line 546)
in call from compile:'-internal_fun/2-anonymous-0-'/2 (compile.erl, line 229)
in call from compile:'-do_compile/2-anonymous-0-'/1 (compile.erl, line 219)
:error
=> Handle :compile.file/2 returning :error on OTP 24

lib/elixir/lib/kernel/special_forms.ex, lib/elixir/src/elixir_bitstring.erl, lib/elixir/src/elixir_erl_compiler.erl, lib/elixir/test/elixir/kernel/expansion_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs, lib/mix/lib/mix/compilers/erlang.ex, lib/mix/lib/mix/tasks/compile.erlang.ex, lib/mix/test/mix/tasks/compile.erlang_test.exs, lib/mix/test/mix/tasks/compile.yecc_test.exs
- Update Erlang warnings translation (#10694)
- Fix translating erl compiler errors to diagnostics on OTP 24 (#10719)
- Fix remaining warning translations for OTP 24 (#10720)
- Support 16bit floats in bitstrings (#10740)
- Handle :compile.file/2 returning :error on OTP 24 (#10742)
=> Backport OTP 24 compatibility patches to v1.11

lib/elixir/lib/enum.ex
Hi!
This PR optimizes `Enum.scan/2` and `Enum.scan/3` for lists.
The speedup seems to be around 1.7x~2x according to [this benchmark](https://github.com/sabiwara/elixir_benches/blob/main/bench/fast_enum_scan.results.txt), but this drops down to ~1.6x [with the JIT](https://github.com/sabiwara/elixir_benches/blob/jit/bench/fast_enum_scan.results.txt) (which is still a nice improvement though I think).
=> Optimize Enum.scan/2 and Enum.scan/3 for lists

lib/elixir/lib/enum.ex
Hi! `Enum.map_intersperse/3` had an optimized version for lists, but `Enum.interspese/2` didn't.
This optimization can speedup by a factor of ~2x according to [this benchmark](https://github.com/sabiwara/elixir_benches/blob/jit/bench/fast_enum_intersperse.results.txt) (JIT).
I also renamed the `element` param to `separator` to be consistent with `map_intersperse` (which is also clearer IMO).
=> Optimize Enum.intersperse/2

lib/elixir/lib/enum.ex
Hi again. I tried to see if `Enum.join` could be improved as well for lists, and it seems that this version can be ~40% faster [with the JIT](https://github.com/sabiwara/elixir_benches/blob/jit/bench/fast_enum_join.results.txt), ~30% [with OTP23](https://github.com/sabiwara/elixir_benches/blob/main/bench/fast_enum_join.results.txt).
Note: I first tried [with body recursion](https://github.com/sabiwara/elixir_benches/commit/ed9c364a5c41a8beed8190898d3a3602c8ab8375), but the result was not so convincing: TCO seems to make a noticeable difference, especially the JIT seems to like it.
=> Optimize Enum.join/3 for lists

lib/elixir/lib/string.ex
Duplicate `n` times might sound unusual to some. This commit changes the docstring for `String.duplicate` to use repeat.
See also https://lodash.com/docs/4.17.15#repeat .
It might be worth renaming / aliasing the method in the future.
=> Refine docstring for String.duplicate

lib/elixir/lib/kernel.ex
Add usage documentation to `Kernel.apply/2` and `Kernel.apply/3` to let developers know to use it only when they don't know the arity of the function or the name of the function. 
Similar to [this erlang documentation](https://erlang.org/doc/man/erlang.html#apply-3). Specifically this line:
> If the number of arguments are known at compile time, the call is better written as Module:Function(Arg1, Arg2, ..., ArgN).
=> Add documentation for `Kernel.apply/x` regarding when not to use it

.cirrus.yml
This should also fix the problems with the Erlang installation that happened on 12.1.
=> CI: Upgrade FreeBSD to 12.2

lib/mix/lib/mix/tasks/compile.protocols.ex
If I'm reading this line of code correctly it's intended to ignore any Erlang paths when looking for protocols and their implementations. However, the call order appears backwards to me.
With [:lists.prefix/2](https://erlang.org/doc/man/lists.html#prefix-2) the prefix is supposed to be the first argument. It's used correctly when [extracting protocols and implementations](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/protocol.ex#L495) down the line.
That check when extracting protocols and implementations rejects any BEAM files in the directories missed by this check, so protocols still consolidate correctly. The `filter_otp/2` function just doesn't do anything as it stands right now.
How that looks on my machine:
```elixir
otp = :code.lib_dir()
#=> …
```
=> Fix prefix check when consolidating protocols

lib/elixir/lib/system.ex
Ref https://github.com/elixir-lang/elixir/issues/10433
`:os.env/0` is available in [OTP 24](https://erlang.org/download/OTP-24.0-rc1.README) as OTP-16793
Note that the CI matrix doesn't include OTP 24 yet.
=> Use :os.env/0 in System.get_env if available

lib/elixir/lib/regex.ex
See:
https://github.com/erlang/otp/pull/4551/files
=> Copy upstream documentation change about regex ascii character class deficiency

lib/mix/lib/mix/rebar.ex, lib/mix/test/mix/rebar_test.exs
Ensures non-semver application versions do not break when no requirement
is specified in the rebar3 dependency.
=> Remove default requirement for rebar3 deps

lib/mix/lib/mix/tasks/test.ex
The --export-coverage option specify the result files. This commit make it clear that it means the name of the file you want to export the result file to.
=> Fix typo in Mix.Tasks.Test module document

lib/elixir/lib/module/parallel_checker.ex
The return type changed in 96661c6963cd75ba83f7c8f4ca01e798b4c6e724
=> Update Module.ParallelChecker.fetch_export/4 spec

lib/elixir/lib/calendar/date.ex
I accidentally passed a `nil` value to `Date.compare/2` and got an UndefinedFunctionError:
```elixir
iex(41)> Date.compare Date.utc_today, nil
** (UndefinedFunctionError) function nil.calendar/0 is undefined. If you are using the dot syntax, such as map.field or module.function(), make sure the left side of the dot is an atom or a map
nil.calendar()
(elixir 1.11.1) lib/calendar/date.ex:504: Date.compare/2
```
I think a FunctionClauseError would be more appropriate (and helpful) as it would provide a nice hint about what went wrong, similar to convert:
```elixir
iex(1)> Date.convert nil, Date.utc_today()
** (FunctionClauseError) no function clause matching in Date.convert/2    
The following arguments were given to Date.convert/2:
nil
~D[2021-03-08]
Attempted function clauses (showing 2 …
```
=> raise FunctionClauseError when passing invalid arguments to Date.compare/2

lib/elixir/pages/typespecs.md
This is a follow up of #10780
As noted by @eksperimental, it would be more readable if `type1` and `type2` would be renamed instead of adding additional comments to clarify their meaning.
Additionally, `nonempty_maybe_improper_list/2` was left untouched in the previous PR.
=> Improve improper lists typespecs readability

lib/mix/test/mix/tasks/test_test.exs
this became outdated with the recent changes to `mix test --failed`
to run all tests when there are no failing tests.
=> update `mix test --failed` test comment

lib/mix/lib/mix/compilers/erlang.ex, lib/mix/lib/mix/shell/process.ex, lib/mix/lib/mix/tasks/compile.erlang.ex, lib/mix/lib/mix/tasks/compile.leex.ex, lib/mix/lib/mix/tasks/compile.yecc.ex
Improves the compilation time of [erlang-jose](https://github.com/potatosalad/erlang-jose) from 3.7s to 1.6s and increases CPU utilization from 125% to 400% on my machine.
Closes #10690.
=> Parallelize compile.erlang

lib/mix/lib/mix/tasks/compile.erlang.ex
It looks like it was missed in https://github.com/elixir-lang/elixir/pull/10789#event-4458704647
=> Add timeout: :infinity and ordered: false in compile.erlang task

lib/elixir/lib/list.ex
I've looked through the Getting Started guide and the List docs but I was unable to find anywhere that makes it clear that this is the syntax to add an element to the head of a list. The closest I could find is later in the same section where speed of prepending vs appending is discussed. However, there and throughout the docs it is only implicitly used.
This PR is just a suggestion for how an explanation of the list prepend syntax could be added.
I was also considering a further sentence stating that the reverse does not work as expected as it will create an improper list.
=> Clarify syntax for prepending an element to a list

lib/elixir/lib/code/formatter.ex, lib/elixir/lib/code/identifier.ex, lib/elixir/lib/enum.ex, lib/elixir/lib/exception.ex, lib/elixir/lib/integer.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/macro.ex, lib/elixir/lib/range.ex, lib/elixir/lib/string.ex, lib/elixir/pages/operators.md, lib/elixir/src/elixir_parser.yrl, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/code_formatter/operators_test.exs, lib/elixir/test/elixir/enum_test.exs, lib/elixir/test/elixir/integer_test.exs, lib/elixir/test/elixir/kernel/parser_test.exs, lib/elixir/test/elixir/kernel_test.exs, lib/elixir/test/elixir/macro_test.exs, lib/elixir/test/elixir/range_test.exs
Proposal: https://gist.github.com/josevalim/da8f1630e5f515dc2b05aefdc5d01af7
Mailing list discussion: https://groups.google.com/g/elixir-lang-core/c/U5EhplEqda4
TODO:
Other notes:
* With this PR, we can now support stepped ranges on `Enum.slice/2` and `String.slice/2`. For example:
```elixir
iex> String.slice("Elixir", 0..-1//2)
"Eii"
```
This is not done in this PR. We could even support slice+reverse by having negative steps, such as:
```elixir
iex> String.slice("Elixir", -1..0//-2)
"rxl"
```
but unfortunately we can't do so right now because 3..-1 has a negative step. Therefore, in order to support slice+reverse, we first need to raise for negative steps on Elixir v2.0 (which is not scheduled nor planned at the moment) and then add this feature later on.
=> Add support for stepped ranges

lib/mix/test/test_helper.exs
The configuration init.defaultBranch is a recent addition to git. When
it's not available the tests will fail because the wrong branch is
created.
=> Fix mix tests on older git versions

lib/elixir/pages/library-guidelines.md
This came up on the Elixir Slack a few days ago. This is a bit of institutional knowledge that is not currently captured in writing
anywhere (as far as I can tell), but it is important guidance for the health of the Elixir ecosystem. cc: @ericmj
Related: https://github.com/hexpm/hexpm/pull/1018
=> Add "namespaces" guidance to library guidelines

lib/elixir/lib/access.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/keyword.ex, lib/elixir/lib/map.ex
In the same fashion of PRs #10228 and #10223
Replaces:
- `get_values` with `current_value`
- `update_value` with `new_value`
- `data` with `new_data` when suitable
Adds nil as an argument term in the function spec.
=> Streamline get_and_update specs for Access for Kernel

lib/elixir/lib/exception.ex, lib/elixir/test/elixir/exception_test.exs
Bug:
iex(1)> raise KeyError, "My message"
** (KeyError) key nil not found
Fix:
iex(1)> raise KeyError, "My message"
** (KeyError) My message
=> Fix KeyError custom message

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
This is a work in progress but I wanted feedback on the approach I took.
~I took heavy inspiration from the way we do reduce / reduce_while in Enum. The way that works is we have `Enumerable.reduce` which acts as a lower level implementation for `Enum.reduce` and `Enum.reduce_while`.
When zipping we also special case the zipping of two lists to provide a faster implementation.~
~So what I did was implement two (awfully named) functions:~
~* `enumerable_zip_reduce_while`. This is analagous to `Enumerable.reduce` but for zipping.~
~* `fast_enumerable_zip_reduce_while`. This is the special cased "zipping two lists" faster implementation, also analagous to `Enumerable.reduce`~
~The questions I have are:~
~1. Do we want either of those to be public functions?~
~2. Should we instead define a …
=> Zip reduce and Zip reduce while

lib/elixir/lib/range.ex
We need to be explicit and define the step field, otherwise IEx and ExDoc will spec it as "term()"
(1)> t Range.t/2
@type t(first, last) :: %Range{first: first, last: last, step: term()
=> Fix t:Range.t/2

lib/elixir/lib/range.ex
Ranges are no longer exclusively a consecutive sequence of integers.
=> Update range definition

lib/elixir/lib/access.ex
By looking at source of `Access.all/0` it seems that returned value by this function is `container()` instead of tuple `{val, container()}`.
=> Set correct value returned by `get_fun/2` callback

lib/elixir/lib/module/types/unify.ex, lib/elixir/test/elixir/module/types/types_test.exs
In the same fashion as generated arguments 30373382ec2183d316f14b6ec6a99225855c6d8d
=> Use one-based var names in Types

lib/elixir/test/elixir/enum_test.exs
Use :exss exclusively since it is the default one in OTP 22+
Related to #10848
=> Replace deprecated random seed algorigthm in tests

lib/elixir/lib/calendar/date.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/range.ex
- Use "with a step of X"
- Replace usage of "start" and "stop" with "first" and "last"
=> Fix grammar in Range docs

lib/elixir/lib/enum.ex, lib/elixir/lib/stream.ex
No longer use :exrop and :exsplus alogrithms in documentation.
=> Update Enum.{random, shuffle}/1 docs to OTP 22

lib/mix/lib/mix/tasks/xref.ex, lib/mix/test/mix/tasks/xref_test.exs
`mix xref` task's module doc lists some arguments that are supposed to affect compilation, but they get stripped off by option parser before passing `args` to `compile` task.
In result, `compile` task is run with default arguments and project compilation is always _attempted_.
The PR fixes this.
=> Pass xref's compile args to compile task

lib/mix/test/test_helper.exs
Includes the fix for Windows by removing redundant quotes.
=> Fix git default branch warnings

Makefile, lib/elixir/docs.exs, lib/mix/docs.exs
Before:
https://hexdocs.pm/elixir/1.12.0-rc.0/changelog.html contains links like:
[`Mix.install/2`](https://hexdocs.pm/mix/Mix.html#install/2)
which currently 404.
After:
https://hexdocs.pm/elixir/1.12.0-rc.0/changelog.html would contain:
[`Mix.install/2`](https://hexdocs.pm/mix/1.12/Mix.html#install/2)
(it requires https://github.com/elixir-lang/elixir/pull/10871 too)
See demo: http://wojtekmach.pl/docs/elixir/1.12/elixir/changelog.html
=> Use docs canonical version in all built-in apps

lib/elixir/lib/task.ex
A common scenario when using tasks is try to trigger the result of the first task to complete, given a list of tasks.
We can accomplish that using Task.async_stream + Stream API, however is not very clear for a newcomer on how to use it.
Add example of using Task.async_stream to get the result of the first async task to complete.
Mailing list thread: https://groups.google.com/g/elixir-lang-core/c/ZIFsisK12CM/m/-mDgg-DmCAAJ
=> Add example to Task.async_stream documentation

lib/mix/lib/mix/task.ex
Hi there 👋 
I was creating a mix task and noticed that when `@moduledoc false` is set, it overrides the stated behaviour of `@shortdoc`:
> Define the @shortdoc attribute if you wish to make the task publicly visible on mix help. Omit this attribute if you do not want your task to be listed via mix help.
In other words, the task will not appear via `mix help` if `@moduledoc false` even if a `@shortdoc` is set.
I was a bit surprised by this until I read [Hiding Internal Modules and Functions](https://hexdocs.pm/elixir/writing-documentation.html#hiding-internal-modules-and-functions). In retrospect, it makes perfect sense.
However, this was not obvious to me solely in the context of the mix documentation alone — and implies knowledge of behaviour documented elsewhere. So I figured a …
=> Addition to @shortdoc documentation

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
Hi. I just noticed that `Enum.dedup/1` isn't working properly on non-list enumerables in the 1.12-rc.0.
```elixir
[1, 1, 0, 2] |> Stream.map(& &1) |> Enum.dedup()
[1, 1, 0, 2]
```
After investigating, I realized this was a bug I introduced myself in a previous PR :see_no_evil:.
Really sorry for that.
=> Fixing bug in Enum.dedup/1

lib/elixir/lib/exception.ex, lib/elixir/test/elixir/exception_test.exs
Previously it was wrongly hinting that the
behaviour Behaviour expected a private or undefined function to be present,
when the callback was optional.
=> Fix optional callback blame hint

lib/mix/lib/mix/shell.ex, lib/mix/lib/mix/shell/io.ex, lib/mix/lib/mix/shell/process.ex, lib/mix/lib/mix/shell/quiet.ex, lib/mix/test/mix/shell/io_test.exs
Hello 👋 
As [proposed](https://groups.google.com/g/elixir-lang-core/c/yMn-Z4SqhEc) in the core mailing list, this is a change that adds an option to change the default behaviour of the `Enter` key as input for `Mix.Shell.IO.yes?`.
Currently, a user can simply press`Enter` to accept the prompt. The proposed change allows this this action to reject the prompt instead. Its rationale is to provide the option to enforce an explicit confirmation from the user, which may be a desirable safety net if accepting the prompt is for a potentially dangerous or irreversible operation.
As suggested by @josevalim the option would be `default: :yes | :no`; e.g:
```elixir
if Mix.Shell.IO.yes?("Delete everything? [yN]", default: :no) do
delete_everything!()
end
if Mix.Shell.IO.yes?("Accept non-destructive …
```
=> Added `default` option to `Mix.Shell.IO.yes?`

lib/elixir/lib/path.ex
If you give a binary to Path that is not utf-8 encoded, it will preserve it as is
related to #10897
=> Path module will always return a binary() type

lib/elixir/lib/uri.ex, lib/elixir/test/elixir/uri_test.exs
The URI module is not quite in compliance with the canonical RFC3986,
when handling IPv6 literal hostnames. These should be stored with
`[]` included. This is handled correctly in the authority field, but
not in the hostname field.
We can't change this behaviour now, so add doc & test.
closes #10896
```
$ bin/elixir lib/elixir/test/elixir/uri_test.exs
Excluding tags: [windows: true]
........................................................
Finished in 1.2 seconds (1.1s on load, 0.04s async, 0.00s sync)
32 doctests, 24 tests, 0 failures
Randomized with seed 555840
```
NB `gmake docs` fails here, but I think this is a previous commit. Using elixir /master/:
```
gmake docs
==> ex_doc (elixir)
CANONICAL=master/ bin/elixir ../ex_doc/bin/ex_doc "Elixir" "1.13.0-dev" "lib/elixir/ebin" --main …
```
=> Improve URI docs & tests for IPv6 literals (#10896)

lib/elixir/lib/application.ex
Hi,
I found myself wanting to access a specific attribute of a configuration option such as `Application.get_env(:hello, HelloWeb.Endpoint)[:signing_salt]` but the documentation didn't cover this syntax.
It took around half an hour of Googling, scouring the docs and ultimately finding a StackOverflow answer to get the correct answer. I think this extra context on how I arrived at a solution was necessary to include in this PR comment because the SO thread at https://stackoverflow.com/questions/35725536/how-to-read-config-variable-in-phoenix-elixir shows a bunch of upvotes and a marked answer for an incorrect solution.
So I figured I'd open a PR here to clarify the docs to demonstrate this usage example.
I broke up the existing paragraph into 2 paragraphs because it wrapped to 6 lines of …
=> Improve docs for using Application.get_env/3

lib/iex/lib/iex/helpers.ex
This PR adds `IEx.Helpers.t/1` to module doc examples for easier lookup. It also sorts the lines alphabetically.
=> Add IEx.Helpers.t/1 to module doc examples

lib/elixir/pages/syntax-reference.md
While studying the Elixir AST, I found that Elixir docs were lacking regarding some AST constructs like the Access and Multi alias calls.
In this PR I'm addinng a bit of documentation on what I found by experimenting, the rest of the context can be found in this Elixir Forum thread: https://elixirforum.com/t/is-there-a-complete-elixir-ast-reference/38923
This message: https://elixirforum.com/t/is-there-a-complete-elixir-ast-reference/38923/8 mentions the case of `foo()()`, but while it's easy to demonstrate with a code snippet, I'm not sure about how to clearly explain it in the docs.
I'm copying it here:
> > My interest however was in the cases where the first element in that 3-tuple is another 3-tuple.
>
> Yes, in any situation where you have call on the left hand of `()` (call) …
=> Add documentation for Access syntax and multi alias AST representation

lib/elixir/lib/protocol.ex, lib/elixir/test/elixir/kernel/warning_test.exs
Closes #10901
WIP because we need to improve the warning messages.
```elixir
defprotocol MyProtocol do
@spec with_specs(any(), keyword()) :: tuple()
def with_specs(term, options \\ [])
def without_specs(term, options \\ [])
@callback foo(term) :: {:ok, term}
@callback foo(term, 1) :: {:ok, term}
@macrocallback bar(term) :: {:ok, term}
@optional_callbacks [foo: 1, with_specs: 2]
@optional_callbacks [without_specs: 2, foo: 2]
end
```
```console
$ mix
Compiling 2 files (.ex)
warning: callback foo/2 defined inside protocol, which is discourage; please define it with the def/2.
lib/my_protocol.ex:1: MyProtocol (module)
warning: callback foo/1 defined inside protocol, which is discourage; please define it with the def/2.
lib/my_protocol.ex:1: MyProtocol (module)
warning: macrocallback bar/1 …
```
=> Warn if @callback, @macrocallback and @optional_callbacks defined inside protocol

lib/mix/lib/mix.ex, lib/mix/test/mix_test.exs
This is especially useful for scripts that depend on features from libraries that are only available on specific Elixir versions.
=> Mix.install/2: Add :elixir option

lib/elixir/lib/protocol.ex, lib/elixir/test/elixir/kernel/warning_test.exs
This was causing an error:
** (FunctionClauseError) no function clause matching in Protocol.callback_ast_to_fa/1
Introduced in PR: #10912, commit: 485cc13946e5c24dd4c31ebb03e85876c33fa468
=> Fix case when callback spec uses when clause

lib/elixir/pages/operators.md
It was broken due to the changes in d9a23d0d38ce1ada6583eca1c6ce6c861114fca7
=> Fix table in Operators page

lib/elixir/lib/module.ex
Worth mentioning that we have also a few more standard attributes:
- `@tag` for ExUnit
- `@shortdoc` for Mix
but since they are not part of Elixir, they are not included in this list.
cc @msaraiva
=> Add Module.reserved_attributes/0

lib/elixir/lib/integer.ex
Noticed that the current implementation of `guarded_pow` would grow the stack by `n` function calls where `n == Integer.digits(e, 2) |> Enum.count(&(&1 == 1))`. Worked through refactoring the function to make it [iterative](https://github.com/thepeoplesbourgeois/passive_support/commit/30e0e2907eb4b3596f05a62eeafa24bb03cdf7b2?branch=30e0e2907eb4b3596f05a62eeafa24bb03cdf7b2&diff=unified#diff-97f7a84541b5395f07935eb65206f12d55394a9fc276e82b98e1c10ffffb9a81R90), which lead me to realize a way to [tail-call optimize it](https://github.com/thepeoplesbourgeois/passive_support/commit/f171b71231450d19e2f8597ac5c18d6985de8680#diff-97f7a84541b5395f07935eb65206f12d55394a9fc276e82b98e1c10ffffb9a81R87), but decided it'd be the most help to the most people if I suggested it as a change here.
Averaged …
=> Tail-call recursion `guarded_pow`

lib/mix/lib/mix/tasks/local.hex.ex
I believe the documentation for the `mix local.hex` task is incorrect, or at least confusing.
It is written that:
> If both options are set, --force takes precedence.
I understand it as "if --force is set, then --if-missing is not considered" (the installation is forced whether Hex is already installed or not). In practice, it is not true, `--force` only bypasses the shell prompt. If it is not what the sentence means, then I don't understand it.
I suggest a simple rewrite of that sentence to match the current implementation and avoid ambiguity.
=> Clarify mix local.hex documentation when both options are set

lib/elixir/lib/protocol.ex, lib/elixir/test/elixir/protocol_test.exs
Related discussion: https://github.com/elixir-lang/elixir/pull/10927#issuecomment-823279830
While trying to break things, I have come up with this issue.
```elixir
defprotocol AProtocol do
def foo(term)
@callback bar(term)
end
```
The code above raised:
```
== Compilation error in file lib/a_protocol.ex ==
** (FunctionClauseError) no function clause matching in Protocol.callback_ast_to_fa/1
The following arguments were given to Protocol.callback_ast_to_fa/1:
{:callback, {:bar, [line: 4], [{:term, [line: 4], nil}]}, {AProtocol, {4, 1}}}
Attempted function clauses (showing 2 out of 2):
defp callback_ast_to_fa({kind, {:"::", meta, [{name, _, args}, _return]}, _pos}) when kind === :callback or kind === :macrocallback
defp callback_ast_to_fa({kind, {:when, _, [{:"::", meta, [{name, _, args}, …
```
=> Add catch-all clause to Protocol.callback_ast_to_fa/1

lib/elixir/lib/enum.ex
Convert the code block into an inline, so it is part of the paragraph.
Before the paragraph was split by the codeblock.
Before:
After:
=> Improve readability: Fix minor detail Enumerable doc

lib/iex/lib/iex/autocomplete.ex, lib/iex/test/iex/autocomplete_test.exs
Supporting path autocompletion on strings that start with `".` or `"/`.
Thanks @fhunleth, this PR is basically a hard copy of what you have on your toolshed project.
Closes #10888
=> IEx path autocompletion

.github/workflows/ci.yml
Move continue-on-error to step level. Apparently this setting works different when set at the task and the step level
https://github.com/actions/toolkit/issues/399#issuecomment-738700569
Now the CI will be considered as successful if the development branches fail.
=> Refrain GitHub CI from failing in development branches

lib/iex/lib/iex/autocomplete.ex, lib/iex/test/iex/autocomplete_test.exs
Path autocompletion on should be also triggered for `"C:/<tab>` (where C can be any letter, upper or lower cased), so we can autocomplete absolute paths on Windows too
=> Allowing absolute path completion on Windows

lib/elixir/lib/macro.ex
Every time I need to traverse the AST I find myself running some examples in the console to remember how `Macro.prewalk/2` works.
So I thought it might be useful to add an example in the docs.
This is my first PR in Elixir so any feedback is highly appreciated 🙇‍♂️
=> Add documentation for `Macro.prewalk/2`

lib/mix/lib/mix.ex
Closes #10957
I couldn't reproduce it with a test. I tried the following but it passed before & after the patch.
test "recover from deps errors", %{tmp_dir: tmp_dir} do
assert_raise Mix.Error, fn ->
Mix.install([
{:bad, path: Path.join(tmp_dir, "install_test")}
])
end
Mix.install([
{:install_test, path: Path.join(tmp_dir, "install_test")}
])
assert apply(InstallTest, :hello, []) == :world
end
Manual test shows it seems to work well:
~% rm -rf ~/.cache/mix && iex
Erlang/OTP 24 [RELEASE CANDIDATE 2] [erts-11.2] [source-25b1520b77] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]
Interactive Elixir (1.13.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Mix.install(decimal: "~ 2.0")
** (Mix.Error) Required version "~ 2.0" for package decimal is incorrectly specified …
=> Mix.install/2: Recover from deps.get failures

lib/elixir/lib/kernel.ex
Such limitation was removed in 4a2047af1fda32f814e6b9a07b5aa5acd59e1d6b
=> Remove note about length limitation in in/2

lib/ex_unit/lib/ex_unit.ex, lib/mix/lib/mix/tasks/test.ex
Make it more obvious what a seed of 0 does.
This came out from helping someone on Slack better understand what seed does in exunit.
=> Improve ExUnit seed docs

lib/elixir/lib/enum.ex
The existing unzip implementation is generic for all enumerable types. However, large optimizations are available if the input is a list.
First, instead of doing two reverse operations at the end, we can do one at the beginning. This optimization is unavailable in the existing generic implementation in order to avoid materializing an enumerable that might be generated lazily.
Second, we can accumulate the two output lists in two separate parameters, rather than in the reduce function's single accumulator. This avoids generating a tuple per input element that would just be matched away and discarded.
Testing with Benchfella shows a roughly 2x to 3x performance improvement depending on the size of the list.
=> Optimize Enum.unzip/1 for lists

lib/elixir/lib/task/supervised.ex, lib/elixir/test/elixir/task_test.exs
:wave: 
I was working with some code computing `max_concurrency` dynamically and stumbled upon indefinitely blocking call when the value supplied was zero.
```elixir
Task.async_stream(1..1000, fn x -> IO.inspect(x) end, max_concurrency: 0) |> Enum.to_list()
```
=> Disallow streaming with max_concurrency=0

lib/elixir/lib/code.ex, lib/elixir/lib/code/formatter.ex, lib/elixir/lib/code/normalizer.ex, lib/elixir/test/elixir/code_normalizer/comments_test.exs, lib/elixir/test/elixir/code_normalizer/general_test.exs, lib/elixir/test/elixir/code_normalizer/literals_test.exs, lib/elixir/test/elixir/code_normalizer_test.exs, lib/elixir/test/elixir/test_helper.exs
This adds `quoted_to_algebra/2` to the `Code` module, as discussed in [this proposal](https://groups.google.com/u/1/g/elixir-lang-core/c/-8CPorfVTxg).
I feel the testing can be improved, if so I would like some guidance.
=> Expose more formatter functions in the `Code` module

lib/elixir/lib/code/formatter.ex, lib/elixir/lib/code/normalizer.ex, lib/elixir/lib/exception.ex, lib/elixir/lib/inspect/algebra.ex, lib/elixir/lib/kernel/cli.ex, lib/elixir/lib/macro.ex, lib/elixir/src/elixir_compiler.erl, lib/elixir/src/elixir_erl.erl, lib/elixir/test/elixir/code_normalizer/quoted_ast_test.exs, lib/elixir/test/elixir/exception_test.exs, lib/elixir/test/elixir/kernel/expansion_test.exs, lib/elixir/test/elixir/kernel/guard_test.exs, lib/elixir/test/elixir/kernel/parser_test.exs, lib/elixir/test/elixir/kernel_test.exs, lib/elixir/test/elixir/macro_test.exs, lib/elixir/test/elixir/typespec_test.exs, lib/ex_unit/lib/ex_unit/formatter.ex, lib/ex_unit/test/ex_unit/assertions_test.exs, lib/iex/lib/iex/evaluator.ex, lib/iex/lib/iex/introspection.ex, lib/iex/test/iex/helpers_test.exs
Still WIP. This helped find some bugs in the normalizer, which were fixed on master, and there are some formatting errors that need to be tackled for this to be ready. Finally, FunctionClauseError.blame relies on Macro.to_string/2, so that needs to be addressed too.
=> Use Code.quoted_to_algebra on Macro.to_string

lib/elixir/lib/code/normalizer.ex, lib/elixir/test/elixir/code_normalizer/formatted_ast_test.exs
This is work in progress. I found this bug while playing around with the idea of a `mix deps.add` task. Blocks were normalized as if they were lists, and metadata was lost, breaking the comments placement.
=> Preserve metadata on regular blocks

README.md
There is currently no official Libera webchat setup. I will try to update this again once one is available.
=> Change freenode reference to Libera

lib/elixir/lib/macro.ex
Functions are not literals, even `fn` and `&` ones
```
iex(1)> Macro.quoted_literal? quote(do: func())
false
iex(2)> Macro.quoted_literal? quote(do: func)
false
iex(3)> Macro.quoted_literal? quote(do: func(1, 2, 3))
false
iex(4)> Macro.quoted_literal? quote(do: fn x -> x end)
false
iex(5)> Macro.quoted_literal? quote(do: (& &1))
false
iex(6)> Macro.quoted_literal? quote(do: def(f(x), [do: x]))
false
```
=> Fix documentation for `Macro.quoted_literal?`

lib/elixir/src/elixir_aliases.erl, lib/elixir/src/elixir_expand.erl, lib/elixir/test/elixir/kernel/expansion_test.exs
Fixes #11000 
Not proficient erlang dev here, so a detailed review would really be welcome.
=> Compile time error when aliasing non-Elixir modules without :as

lib/elixir/lib/exception.ex, lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/exception_test.exs, lib/elixir/test/elixir/kernel/quote_test.exs, lib/elixir/test/elixir/kernel/raise_test.exs
This PR uses EEP 54 so Elixir exceptions are nicely
formatted by Erlang callers. Take this code:
raise "this is a test"
Before:
** exception error: #{'__exception__' => true,
'__struct__' => 'Elixir.RuntimeError',
message => <<"this is a test">>}
in function  'Elixir.Foo':bar/0 (iex, line 2)
After:
** exception error: #Elixir.RuntimeError
in function  'Elixir.Foo':bar/0 (iex, line 2)
*** this is a test
This depends on https://github.com/erlang/otp/pull/4764.
=> Better format Elixir exceptions in Erlang

lib/elixir/lib/code.ex
* Fixed some spelling mistakes.
* Use "AST" in capitals consistently.
:+1:
=> Add `end` token to example to avoid possible syntax highlighting issues.

lib/elixir/lib/path.ex
Documentation update for #11023 
Clarify the behavior of `Path.extname/1` in docstrings and doctests, namely how it behaves when given a filename that is just a file extension (like ".gitignore"). I also mentioned when you might want to use `Path.basename/1` instead, which was brought up by @josevalim in the associated issue (#11023).
=> Clarify `Path.extname/1` doc(test)s (#11023)

lib/mix/lib/mix/tasks/release.ex
The following phrase, which appears in the Config Providers documentation, is grammatically incorrect:
> The runtime configuration outlined in the previous section, which is handled by the Config.Reader provider.
Given the context, I think the phrase should be:
> The runtime configuration outlined in the previous section is handled by the `Config.Reader` provider.
=> Small grammar fix for Config Providers section

lib/elixir/src/elixir_expand.erl, lib/elixir/src/elixir_parser.yrl, lib/elixir/test/elixir/kernel/parser_test.exs, lib/elixir/test/elixir/kernel/tracers_test.exs
This adds `identifier_locaiton` metadata to qualified identifiers and `last` metadata to aliases, as discussed in [this proposal](https://groups.google.com/u/1/g/elixir-lang-core/c/6APSoyKdKIc)
=> Add `identifier_location` and `last` metadata

lib/elixir/lib/code.ex
Would you please do review?
If I mistake start/end point branch, please comment to me.
I think that Code.ensure_loaded!/1 is added from 1.12.0.
@doc since: "1.12.0" is unnecessary here, so I also think that there may be nothing now.
If I shall waste your time, I apologize.
=> add @doc since: "1.12.0"

lib/ex_unit/lib/ex_unit/cli_formatter.ex, lib/ex_unit/lib/ex_unit/runner_stats.ex, lib/ex_unit/test/ex_unit/callbacks_test.exs, lib/ex_unit/test/ex_unit/runner_stats_test.exs
This resolves #10974
There's two separate changes here, and I've tried to summarize them in their respective commits.
The first commit fixes the count emitted by the `ExUnit.CLIFormatter`, in the event that a module's tests are invalidated. This seemed to be a simple case of properly updating the `failure_counter` when a module finishes with an error, taking care to not double-count the failed tests.
The second commit fixes the exit code emitted when a module's tests are invalidated, and also ensures that those invalidated tests are added to the `ExUnit.FailuresManifest`. This is a very similar change, and modifies `ExUnit.RunnerStats` to handle `:module_finished` messages, by invalidating any tests within a failed module.
I've never worked with the `ExUnit` codebase before, so it's …
=> Invalidate a module's tests if an on_exit hook errors in setup_all

lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/kernel/warning_test.exs, lib/ex_unit/lib/ex_unit/diff.ex
This resolves #11028
I don't write a ton of Erlang, so it's entirely possible that this isn't very idiomatic code, and I'm happy to go back and rework anything as requested :)
=> Warn if ?\lettter is used but there is no such escape sequence

lib/elixir/lib/exception.ex, lib/elixir/test/elixir/exception_test.exs
Not all elixir developers may understand what "apply" means in this case.  Especially if they are beginners and are not using
`Kernel.apply/3` directly (but instead using `.` to call the function or if this is being raised by library code).
However, calling `:foo` a function (example from the tests) isn't quite right (as it is an atom that could represent a function when paired with a module) so the wording could probably be improved further.
=> Improve the error message when apply fails

lib/mix/lib/mix/tasks/xref.ex, lib/mix/test/mix/tasks/xref_test.exs
As proposed [on elixir-core](https://groups.google.com/g/elixir-lang-core/c/Hmg5y8S3v4E/m/FVK50RWBAQAJ)
Other PR forthcoming...
=> Add `--fail-above` option to `mix xref`

lib/elixir/lib/kernel.ex
A per #11050, this PR improves the docs on `sigil_r` to notice that using `~r()` and trying to match escaped parentheses will raise an exception, so any other enclosing character is recommended, specially `~r//` and `~r""`.
=> Improve docs for `sigil_r`

lib/elixir/lib/enum.ex
This PR tries to improve the docs for `Enum.zip_reduce/3` by copying the starting line from `Enum.zip_reduce/4` to make docs clearer.
=> Update `Enum.zip_reduce/3` docs

.github/workflows/ci.yml
https://github.blog/changelog/2021-04-29-github-actions-ubuntu-16-04-lts-virtual-environment-will-be-removed-on-september-20-2021/
=> ci: Use Ubuntu 18.04

lib/elixir/lib/kernel.ex
Add doc example for atoms like module names.
=> Add doc example for :"Elixir.AnAtom"

lib/elixir/lib/code/normalizer.ex, lib/elixir/test/elixir/code_normalizer/formatted_ast_test.exs
The normalizer adds a `:closing` line to calls even if there is a `do` block, forcing the formatter to add parenthesis. So for code like this one:
```elixir
module DemoMod do
def foo, do: :bar
end
```
`Code.quoted_to_algebra` will produce this code:
```elixir
module(DemoMod) do
def foo, do: :bar
end
```
While `Code.format_string!` will produce the output without parenthesis.
I added a check to not force the `:closing` metadata to calls if the call has `:do` metadata.
=> Preserve user choice on parenthesis before do block

lib/mix/lib/mix/rebar.ex, lib/mix/test/mix/rebar_test.exs
Not super sure of this, but noticed #11062 and thought I'd take a stab at it.
Fixes #11062.
=> Ensure unconstrained rebar deps generate valid mix specifications.

lib/elixir/lib/kernel.ex
Add exception details for docs.
When using `<>/2` for pattern matching, the match should always happen on the RHS (right hand side) var, if it doesn't, then you'll get an ArgumentError with:
```
** (ArgumentError) the left argument of <> operator inside a match should always be a literal binary because its size can't be verified. Got: x
```
=> fix: docs for <>/2 operator

lib/elixir/lib/regex.ex, lib/elixir/test/elixir/regex_test.exs, lib/ex_unit/test/ex_unit/assertions_test.exs, lib/mix/test/mix/tasks/deps.git_test.exs, lib/mix/test/mix/tasks/local.public_keys_test.exs, lib/mix/test/mix/tasks/profile.cprof_test.exs, lib/mix/test/mix/tasks/profile.eprof_test.exs, lib/mix/test/mix/tasks/profile.fprof_test.exs
As per docs https://github.com/elixir-lang/elixir/pull/11051, using `~r//` is recommended over using `~r()`. This PR updates the sigil_r delimiter used at multiple places.
=> Update sigil_r use as per docs

CHANGELOG.md, lib/eex/lib/eex.ex, lib/eex/lib/eex/compiler.ex, lib/eex/test/eex_test.exs
As per https://groups.google.com/g/elixir-lang-core/c/Z-C2PFRwyw4
This PR adds the `:parser_options` option to `EEx.Compiler` which allows passing in custom options without having to modify the global options through `Code.put_compiler_option/2`
=> Add parser_options to EEx.Compiler

lib/elixir/lib/enum.ex
This is building off the closed pull request here: https://github.com/elixir-lang/elixir/pull/11034, where it was observed that `:lists.append/1` out performs `Enum.concat/1` for lists of lists. 
I've made a change so that `:lists.append/1` is used when a list of lists is passed into `Enum.concat/1`, otherwise it will default to the previous implementation. 
I've run some benchmarks of my own that confirm the insights from the previous pull request: https://github.com/greg-rychlewski/concat-test/blob/master/benchmark.exs.
Here is the output for the benchmarks:
```
Name               ips        average  deviation         median         99th %
proposal        709.45        1.41 ms    ±40.08%        1.30 ms        4.12 ms
master          376.83        2.65 ms    ±27.31%        2.49 ms …
```
=> Optimize Enum.concat/1 for lists of lists

CODE_OF_CONDUCT.md
There isn't currently an official Webchat for Libera, so I wanted to change the link to an IRCS protocol link. But it seems GitHub won't render it as a link even if I use an inline link style (see: https://github.com/github/markup/issues/426). So in the end I removed the channel link.
=> Update reference to IRC channel in CoC

lib/elixir/lib/code.ex
The comment column is required to calculate the range a node and it's surrounding comments span in the source code by inspecting the ast and the list of comments.
I'm writing some functions that allow users to perform ast based "find and replace", and the lack of column numbers in comments make it hard to map a node and its comments to a range in the source code so we can replace it
=> Don't discard comments column information

lib/elixir/lib/enum.ex
Hi! I noticed that the generic implementation of `Enum.zip/2` relying on `zip_with` with an anonymous function was significantly slower on lists than having dedicated private functions.
Some quick benchmarks suggest a speedup of 2.5~3x compared to the current implementation:
https://github.com/sabiwara/elixir_benches/blob/main/bench/fast_enum_zip.results.txt
Note: I went with a tail-recursive implementation, but I benchmarked [a body-recursive version](https://github.com/sabiwara/elixir_benches/commit/608d9fd786061e8d719331f9a706770fc8062796) as well and it seems noticeably slower (due to the JIT?) so I kept the former.
=> Optimize Enum.zip/2

lib/elixir/lib/code/normalizer.ex, lib/elixir/test/elixir/code_normalizer/quoted_ast_test.exs
The Elixir.Normalizer lets us feed any arbitrary AST to the formatter, but if the user provides a list, and an element is a 2-tuple that is not one of the last elements, and the first element is a wrapped atom with `format: :keyword` metadata, then the formatter will happily print it as a keyword list element, despite it being invalid syntax, for example:
```elixir
iex> opts = [literal_encoder: &{:ok, {:__block__, &2, [&1]}}]
iex> {_, _, [[tuple]]} = Code.string_to_quoted("[a: b]", opts)
iex> Macro.to_string([tuple, :not_a_tuple, tuple])
"[a: b, :not_a_tuple, a: b]"
```
With this PR we would get the expected output:
```elixir
iex> Macro.to_string([tuple, :not_a_tuple, tuple])
"[{:a, b}, :not_a_tuple, a: b]"
```
=> Fix normalization of partial keyword list elements

lib/mix/lib/mix/compilers/elixir.ex, lib/mix/test/mix/tasks/compile.elixir_test.exs, lib/mix/test/mix/tasks/test_test.exs, lib/mix/test/test_helper.exs
As discussed [on the mailing list](https://groups.google.com/g/elixir-lang-core/c/8-30JVn_8M0/m/hUWxonjwAQAJ), I think this adds the right check by hashing the content, but I'm lacking tests.
Does it look like I'm on the right track?
=> Rely on modification time and hash to determine modified sources

lib/elixir/lib/string.ex
The private `byte_size_remaining_at` function does not return a falsy value.
=> Remove unreachable code in String module

lib/elixir/lib/inspect/algebra.ex
It returns Inspect.Algebra.t, just like concat/2 which it calls last
=> Fix Inspect.Algebra.color/3 return type in spec

lib/elixir/lib/task.ex, lib/elixir/test/elixir/task_test.exs
This PR implements the new `Task` function `Task.completed/1` as proposed in the [elixir-lang group](https://groups.google.com/g/elixir-lang-core/c/ickqmBBoSMk/m/EGp507x9AAAJ?utm_medium=email&utm_source=footer).
This function models a task that immediately completes with a known result. As documented in the `@doc` block, it's a useful convenience when working with groups of asynchronous tasks where some inputs may have a result that can be determined without actually running the task. Here's a quick example:
```elixir
def process(data) do
tasks =
for entry <- data do
if invalid_input?(entry) do
Task.completed({:error, :invalid_input})
else
Task.async(fn -> further_process(entry) end)
end
end
Task.await_many(tasks)
end
```
Here are a couple links to prior art in .NET: …
=> add `Task.completed/1`

lib/elixir/lib/kernel.ex
This PR serves:
- To augment the annotation surrounding `Kernel.match?/2`; and specifically,
- To counsel caution when using the pin operator, namely by citing a misuse of the pin operator. 
I initially posted the [following question](https://elixir-lang.slack.com/archives/C03EPRA3B/p1626111373286800) in the `#general` channel of Elixir Slack:
> I’m curious why:
> 
> ```
> iex> match?(%{x: 1, y: 2}, %{x: 1, y: 2, z: 3})
> true
> iex> attrs = %{x: 1, y: 2}
> iex> match?(^attrs, %{x: 1, y: 2, z: 3})
> false
> ```
>
> ?
@LostKobrakai helped me to understand that I was misusing the pin operator. I've reworked @LostKobrakai's comments from Slack into the proposed annotations. 
The behaviour has snagged me a few times, and hence, I'm wondering whether we might augment the documentation …
=> Augment documentation for `Kernel.match?/2`; counsel caution when using the pin operator

lib/elixir/lib/calendar/date_range.ex, lib/elixir/lib/enum.ex, lib/elixir/lib/exception.ex, lib/elixir/test/elixir/calendar/date_range_test.exs, lib/elixir/test/elixir/range_test.exs
Fixes https://github.com/elixir-lang/elixir/issues/11110
Handles cases not covered by https://github.com/elixir-lang/elixir/commit/13ba96be3cef5e4325fc3570f65e2eef4cce9314
There are 2 more usages but those look safe. If I understand it correctly they happen only on compile time
- https://github.com/elixir-lang/elixir/blob/58ca6524f88bfe7e963deafe0e7d6aa07a568003/lib/elixir/lib/kernel.ex#L4071
- https://github.com/elixir-lang/elixir/blob/58ca6524f88bfe7e963deafe0e7d6aa07a568003/lib/elixir/lib/kernel.ex#L4077
=> Keep backwards compatibility on Range and Date.Range

CHANGELOG.md, lib/ex_unit/lib/ex_unit.ex, lib/ex_unit/mix.exs, lib/ex_unit/test/ex_unit_test.exs, lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/tasks/test_test.exs
From [the mailing list conversation](https://groups.google.com/g/elixir-lang-core/c/KOrTrFvXxiM).
It is nice to be able to differentiate between different reasons for failure of a test suite, specifically whether the tests failed or `--warnings-as-errors` detected warnings. Currently, both failure reasons exit with code 1, but this change modifies the exit code of a `--warnings-as-errors` failure to 2.
I looked for a `/lib/mix/test/mix/compilers/test_test.exs` to modify, but it looks like there are no tests for this file. Let me know if you want me to add tests :grin:
=> Change exit status for test failures to 2

lib/elixir/src/elixir_parser.yrl, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/kernel/parser_test.exs, lib/elixir/test/erlang/tokenizer_test.erl
Indentation metadata is preserved for heredoc sigils, but it's not considered for heredoc strings or charlists. It's reasonable since they're literals anyways, but using the `literal_encoder` option knowing the indentation of the node comes in handy.
=> Preserve heredoc indentation metadata

lib/elixir/lib/option_parser.ex, lib/elixir/test/elixir/option_parser_test.exs
I typed `mix test --fauled` repeatedly and found the error could
be improved. This change adds the `did you mean` suggestion with the
most likely match to the error message.
The `0.8` cutoff is pulled from the exceptions.ex file.
=> Add `did you mean` to error for unfound CLI option

lib/ex_unit/lib/ex_unit/doc_test.ex
If we define the module like this:
defmodule :foo do
end
it won't get the `__info__/1` callback. However, we still may want to
use doctests to test it.
=> Make doctest work for "Erlang" modules

lib/elixir/lib/keyword.ex
So at first I saw that the word "duplicated" was used throughout the doc, which isn't quite correct. Better to use the adjective "duplicate".
I noticed many other issues and decided to give it a thorough read. Hope you like the changes.
=> Overhaul of documentation for `Keyword` module

lib/elixir/lib/code/fragment.ex, lib/elixir/test/elixir/code_fragment_test.exs
Before:
```ex
iex(1)> Code.Fragment.surround_context(" Enum", {1, 4})
%{begin: {1, 1}, context: {:alias, 'Enum'}, end: {1, 6}}
```
After:
```ex
iex(1)> Code.Fragment.surround_context(" Enum", {1, 4})
%{begin: {1, 2}, context: {:alias, 'Enum'}, end: {1, 6}}
```
=> Fix Code.Fragment.surround_context/3 range for spaced identifiers

lib/elixir/lib/string.ex
- `[parts: :infinity, trim: true]` can use the `trim_all` argument to
`:binary.split/3`
- `[parts: 2, trim: false]` can use the basic `:binary.split/2` behavior
=> `String.split/3`: special case some additional arguments

.vscode/settings.json, lib/elixir/lib/keyword.ex, lib/elixir/test/elixir/keyword_test.exs, lib/elixir/test/elixir/map_test.exs
This PR implements `Keyword.validate/2` and `Keyword.validate!/2` as discussed in the mailing list.
The original implementation for `validate!/2` can be found in [Nx.Defn.Kernel](https://github.com/elixir-nx/nx/blob/c8353de695a3d70dc6d518e0ab2ec832faa7df68/nx/lib/nx/defn/kernel.ex#L741)
=> feat: add keyword validate

lib/elixir/lib/code/typespec.ex, lib/elixir/test/elixir/typespec_test.exs
I noticed this crash:
iex(1)> h :binary.decode_hex
** (ArgumentError) invalid runtime value for option :line in quote, got: {412, 14}
(elixir 1.13.0-dev) src/elixir_quote.erl:59: :elixir_quote.validate_runtime/2
(elixir 1.13.0-dev) lib/code/typespec.ex:294: Code.Typespec.typespec_to_quoted/1
(elixir 1.13.0-dev) lib/code/typespec.ex:39: anonymous fn/2 in Code.Typespec.spec_to_quoted/2
(elixir 1.13.0-dev) lib/enum.ex:2386: Enum."-reduce/3-lists^foldl/2-0-"/3
(elixir 1.13.0-dev) lib/code/typespec.ex:38: Code.Typespec.spec_to_quoted/2
(iex 1.13.0-dev) lib/iex/introspection.ex:483: anonymous fn/2 in IEx.Introspection.get_spec/3
(elixir 1.13.0-dev) lib/enum.ex:1583: Enum."-map/2-lists^map/1-0-"/2
(iex 1.13.0-dev) lib/iex/introspection.ex:482: IEx.Introspection.get_spec/3
It can be reproduced …
=> Code.Typespec: handle column in anno on newer OTP versions

lib/mix/lib/mix/tasks/xref.ex
I've just [changed ExDoc master](https://github.com/elixir-lang/ex_doc/commit/b620c68f7a1d5baca16cbd74fae9b81ea371f9a7) to detect code blocks with no explicit language and starting with "$ " to use shell lexer so now we'll get e.g.:
This is a pretty safe heuristic to use. `$ ` is never going to be valid Elixir syntax. `$ ` happens to be valid Erlang code but I think it's fine to pick the wrong highlighting in that incredibly rare situation to run into in practice.
=> mix xref: Update docs

lib/elixir/lib/list.ex
Added examples for
- foldl/3 with accumulator of list type
- foldr/3 with accumulator of map type
to show that accumulator can be of any type, not just a number.
Also hyperlinked the word 'accumulator' in the foldl/3 and foldr/3 function definitions to acc documentation (https://hexdocs.pm/elixir/Enum.html#t:acc/0)
=> More examples for foldl/3 and foldr/3 + link to accumulator doc

lib/mix/lib/mix/tasks/local.rebar.ex
while reading the docs noticed a small improved that could be made into this paragraph.
- Remove extra white space.
- add an for the `argument`
=> Small improvement on mix local docs

lib/mix/lib/mix/tasks/local.rebar.ex
`mix local.hex` has an `--if-missing` flag, but the option isn't available for `mix local.rebar`. This PR adds the same feature to `mix local.rebar`.
=> Add --if-missing option to mix local.rebar

lib/mix/lib/mix.ex, lib/mix/lib/mix/tasks/deps.compile.ex
With this patch, and the commit just before it (f4f44e2), we can correctly mix install both of these packages:
```elixir
Mix.install [
:certifi,
:erqwest
]
IO.inspect :certifi.cacertfile()
:ok = :erqwest.start_client(:default)
IO.inspect :erqwest.get(:default, "https://hex.pm/api", %{headers: [{"user-agent", "erqwest"}]})
```
=> mix deps.compile: Copy priv/ before compilation

lib/elixir/lib/string.ex
Small nit, but the docs for `valid?/1` render with an ambiguous `arg1` rather than following the rest of the API with `string`: https://hexdocs.pm/elixir/1.12/String.html#valid?/1
=> Update valid? for docs

lib/elixir/lib/code/fragment.ex, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/code_fragment_test.exs, lib/iex/lib/iex/autocomplete.ex, lib/iex/test/iex/autocomplete_test.exs
This is still WIP but there is a part where I can already collect feedback, which is how to show sigils in IEx. I decided to show the `~CHAR` with the function name in parentheses, so there is a mapping between what is autocompleted and what is invoked:
=> Add sigil completion to code fragment

CHANGELOG.md, lib/mix/lib/mix/compilers/elixir.ex, lib/mix/lib/mix/project_stack.ex, lib/mix/lib/mix/tasks/compile.app.ex, lib/mix/lib/mix/tasks/compile.elixir.ex, lib/mix/lib/mix/tasks/compile.protocols.ex, lib/mix/lib/mix/tasks/loadconfig.ex, lib/mix/test/mix/tasks/compile.elixir_test.exs, lib/mix/test/mix/tasks/deps.git_test.exs, lib/mix/test/mix/umbrella_test.exs, lib/mix/test/test_helper.exs
Whenever there is a change to the lock file or the config file, we will now only recompile the code that depends on the dependencies that changed (or that depends on any dependency that depends on the dependency that changed).
With the improvements in #11190, it means that we now only get a full recompilation when:
1. an app is removed from the lock file
2. when you change the configuration for your own app in config/config.exs (or an imported file from there)
3. when you change elixirc_options/elixirc_paths
This is currently WIP, tests still pending.
=> Recompile only necessary deps whenever config/lock change

lib/elixir/lib/io/ansi/docs.ex, lib/elixir/test/elixir/io/ansi/docs_test.exs
Ref:
> `-type chunk_element_inline_type() :: a | code | strong | b | em | i.`
https://erlang.org/doc/apps/erl_docgen/doc_storage.html#eep-48--documentation-storage-and-format
=> IEx.Helpers.h: Support `<b>` and `<strong>` tags in erlang+html format

.github/workflows/ci.yml, lib/logger/lib/logger/translator.ex
Cherry-picked dac1b43688324f95ddd4f8642b31ee9afa75aea4 and also add OTP-24 to the CI matrix since is officially supported from v1.11.4 onwards.
Related to #11221 .
=> Fix logger translator with otp-24 

lib/elixir/lib/enum.ex
A tiny PR to add some documentation to the Enumerable module,
based on [this elixir-core discussion](https://groups.google.com/g/elixir-lang-core/c/2oga5zVfDmQ)
=> Document how Enumerable suspension can be tested (in `t:Enumerable.result`)

lib/elixir/lib/io.ex
Adds is_device private guard cheking the argument is a device.
The use case is that I have wasted a lot of time trying to figure out why I wasn't able to print an IO.ANSI string.
I was executing `IO.inspect(term, printable_limit: :infinity)` on a big string, and I switched to IO.puts to see how it looked, 
`IO.puts(term, printable_limit: :infinity)`,  I was getting a cryptic CaseClause error not matching. Long story short, `IO.puts` does not take options, and the first argument is a device, not the term to inspect/print. So this guard will guide you in the right path.
=> Add guards to IO.puts/2 and IO.inspect/3

lib/elixir/lib/process.ex
See https://erlang.org/doc/man/erlang.html#spawn_opt-2 as reference
Monitor tuple option seems to have been added rather recently,
it's missing in OTP 23.0 docs:
https://erlang.org/documentation/doc-11.0-rc2/erts-11.0/doc/html/erlang.html#spawn_opt-2
There are more types exported from the erlang module now, possibly
Elixir could reference those in more places, but I think it's fine
to copy / inline the simple ones because they may not be exported
in older Erlang/OTP versions that Elixir still supports. (and it's clearer
since they may be hard to find and there is no auto link)
=> Add more variants to Process.spawn_opt type

lib/elixir/src/elixir_interpolation.erl, lib/elixir/test/elixir/kernel/parser_test.exs
=> Fix nfd cluster columns

lib/mix/lib/mix/tasks/deps.unlock.ex, lib/mix/test/mix/tasks/deps_test.exs
Current behaviour:
Does not output empty line with * when no dependencies were unlocked
Adds test for that behaviour
=> Fixes output of deps.unlock when dependency is not locked

lib/elixir/lib/kernel.ex
When the `unmatched_returns` option of Dialyzer is enabled, functions which can return more than a single value must be explicitly matched against. This fixes `Kernel.tap/2` to be compatible with that option.
=> Kernel.tap/2: Explicitly ignore return value for compatibility with Dialyzer unmatched_returns

lib/elixir/lib/keyword.ex, lib/elixir/lib/map.ex
PR is based on [this proposal](https://groups.google.com/g/elixir-lang-core/c/oDIt4mKUc6A).
- `:maps.filter/2` [supports a map iterator](https://github.com/erlang/otp/blob/master/lib/stdlib/src/maps.erl#L302) as first parameter. As we're not currently exposing map iterators through the `Map` module at all, my assumption is that this support is not required for `Map.filter/2` etc., simplifying the code a little. Is this correct?
- `:maps.filter/2`'s source code has [some error handling/decorating](https://github.com/erlang/otp/blob/master/lib/stdlib/src/maps.erl#L312). I'm not 100% sure how to convert this to Elixir code. Is this already handled by Elixir's own `FunctionClause`-handling where "function clauses that were tried" are printed? We might be able to [remove this …
=> Map filter

lib/elixir/lib/integer.ex
a and b matches the documentation and this also makes the heading in
doc to be `def extended_gcd(a, b)` instead of `def extended_gcd(n, n)`.
=> Use a b instead of n for Integer.extended_gcd

lib/elixir/lib/code/formatter.ex, lib/elixir/test/elixir/code_formatter/general_test.exs, lib/mix/lib/mix/tasks/deps.loadpaths.ex, lib/mix/lib/mix/tasks/format.ex, lib/mix/test/mix/tasks/deps_test.exs, lib/mix/test/mix/tasks/format_test.exs
This PR adds formatter plugins which customizes how the formatter behaves.
Plugins must implement the `Mix.Tasks.Format` behaviour. For example, imagine
that your project uses Markdown in two distinct ways: via a custom `~M` sigil and
via files with the `.md` and `.markdown` extensions. A custom plugin would look
like this:
```elixir
defmodule MixMarkdownFormatter do
@behaviour Mix.Tasks.Format
def features(_opts) do
[sigils: [:M], extensions: [".md", ".markdown"]]
end
def format(contents, opts) do
end
end
```
Now any application can use your formatter as follows:
```elixir
[
plugins: [MixMarkdownFormatter],
inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}", "posts/*.{md,markdown}"]
]
```
Remember that, when running the formatter with plugins, you must make
sure that your …
=> Formatter plugins

lib/elixir/lib/code.ex
Fixes two documentation typos in the code.ex `@moduledoc`
`ensure_lodead!` => `ensure_loaded!`
`ensure_lodead?` => `ensure_loaded?`
No other changes. I didn't bother testing this either, since I made the edit in Github's web interface. Sorry if this somehow breaks doc tests or is otherwise just not helpful.
P.S.
It looks like this typo was already fixed on master. The commit is 7aabaa7e38dea3b4c1039cd3df2699d452101c1a, if you'd like to cherry-pick that one instead.
The main purpose of this PR is to update the v1.12.x `Code` docs at https://hexdocs.pm/elixir/1.12/Code.html. 
All the specific patch versions there (v1.12.0-v1.12.3) still have these typos. 
I haven't looked into how Hex.pm loads `:elixir` docs for different patch versions, so I'm sorry if this PR is totally misplaced or …
=> docs(code): fix `ensure_loaded` typos in `Code` docs

lib/mix/lib/mix/tasks/xref.ex, lib/mix/test/mix/tasks/xref_test.exs
Currently, excluded paths still count for connections. In the example test, the file `d.ex` is said to be `compile-connected` because it has a single dependency on `e.ex`. If `e.ex` is excluded, I believe that `d.ex` should no longer be considered a compile-connected dependency. This PR fixes that.
Use case:
We `use MyApp` just about everywhere, and `lib/my_app.ex` is known to not refer to anything. I would like to ask for compile-connected dependencies but exclude `lib/my_app.ex`. This way I may call `use MyApp` even in the few files that we use as compile-time dependencies.
Implementation-wise, I am wondering if it wouldn't be cleaner and simpler to filter the whole list of `file_references` once at the beginning. This might entail a bit of unnecessary processing when explicit …
=> Add support for `mix xref graph --label=compile-connected --excluded=…`

lib/elixir/lib/macro/env.ex
The docs for  `fetch_alias/2` and `fetch_macro_alias/2` state incorrectly that these functions return either the alias or `nil` (instead of `{:ok, atom()} | :error`).
In case of `lookup_import/2` I believe the proposed wording is more correct (though my English is not very good so I can be wrong).
=> Fix docs for new functions in Macro.Env

lib/iex/lib/iex/info.ex
Fixes #11262 
This is my initial stab at adding this documentation.
It's based on my own interpretation of the code of the existing `IEx.Info`-implementations as well as `IEx.Helpers.i/1`.
Please let me know in what ways this documentation can be improved. I expect that parts are too specific, and in other parts important information might be missing.
:slightly_smiling_face:
=> Adding documentation to the IEx.Info protocol

lib/elixir/lib/kernel.ex
This code example has the top and bottom line "outside" the formatted code box:
By adding one space of indentation (to 4), the whole code example is formatted as code:
=> Fix indentation of code example

lib/elixir/lib/list.ex
Earlier it was throwing `ArithmeticError` which seems confusing, instead now it will fail on function clause which should give user better feedback that the arguments are in wrong order.
=> Better errors when arguments reordered

lib/elixir/lib/kernel.ex
This commit documents that `apply/3` can only
be used to call public functions in the target
module.
=> Update documentation for `apply/3`

lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/tasks/test_test.exs
This is meant to make GitLab CI integration with partitions much easier as will allow to use
```shell
MIX_TEST_PARTITION=${CI_NODE_INDEX} mix test --cover --partitions ${CI_NODE_TOTAL}
```
As a test task instead of additionally taking care of case when the parallel testing is disabled.
=> Ignore `MIX_TEST_PARTITION` when partitions set to 1

lib/mix/lib/mix/task.ex, lib/mix/test/mix/aliases_test.exs
Before this commit, we were failing with a `FunctionClauseError` a bit deeper in Mix itself. Now, if you give a bad alias to `:aliases`, we raise a nice and helpful error message.
=> Improve error message on bad Mix aliases

lib/elixir/lib/io.ex
In https://hexdocs.pm/elixir/1.12/IO.html#chardata_to_string/1, the function signature tells that it accept string:
It's incorrect because it accept the `chardata` which's string (binary) or list which make confusing when reading the doc. This patch fix by add bodyless clause that accept `chardata` as a first argument.
=> Fix IO.chardata_to_string/1 misleading in exdoc

lib/elixir/lib/regex.ex
This funtion can return a list of tuples containing two integers when
the `return: :index` option is provided.
=> Correct return type in Regex.scan/3 function spec

lib/elixir/lib/calendar.ex, lib/elixir/lib/calendar/date.ex, lib/elixir/lib/calendar/iso.ex, lib/elixir/test/elixir/calendar/holocene.exs, lib/elixir/test/elixir/calendar/iso_test.exs
In order to support calendars which can change
era any time during the calendar year, the callback
Calendar.year_of_era/1 is changed to Calendar.year_of_era/3.
Since Calendar.ISO.year_of_era/1 is a public function,
default arguments for month and day are set if
year_of_era/1 is called to allow compatibility with
any existing code that relies upon this function.
=> Change Calendar.year_of_era/1 callback to /3

lib/elixir/lib/kernel.ex
Adding a paragraph to the docs of `Kernel.defoverridable/1` noting that changing the visibility of the function is allowed.
Fixes #11292
=> Adding a snippet to the docs of `defoverridable/1`

lib/elixir/lib/module.ex
Fix docs of Module.safe_concat/1 / Module.safe_concat/2:
- Remove mention of handling charlist (which it does not).
- Also mention in the docs of `Module.concat/1` / `Module.concat/2` that
this handles both binaries and atoms.
Fixes #11298
=> Fix docs of Module.safe_concat/1 / Module.safe_concat/2

lib/ex_unit/test/ex_unit/capture_log_test.exs, lib/logger/lib/logger/backends/console.ex, lib/logger/lib/logger/formatter.ex, lib/logger/test/logger/backends/console_test.exs, lib/logger/test/logger/handler_test.exs, lib/logger/test/logger_test.exs
yes.. this is not very "backward compatible"..
I guess adding some config flag to enable it, and
default it to false.. would be proper (?)
=> Emit notice logs in :console backend

lib/elixir/unicode/unicode.ex
The patch computes byte lookups based on the prefix. For example,
Á, É, etc all have the same prefix <<195>>, so they are lumped
together for lookup and then we just do a byte lookup later. We
tried doing the byte lookup on 64-element tuple (since the byte
is always within 0b10000000 and 0b10111111) but that's slower,
especially because we need to check the byte range for invalid
Unicode, instead the last byte lookup is a case. Grouping the
top-level lookup makes the cost of a miss 3x cheaper albeit a
hit is 10% more expensive) and reduces bytecode size.
=> Group Unicode upcase/downcase by prefix

lib/elixir/lib/calendar/iso.ex
They have been copied from the Calendar behaviour..
=> Add specs to Calendar.ISO.parse_*/1 functions

lib/elixir/lib/kernel/typespec.ex, lib/elixir/test/elixir/typespec_test.exs
Closes #11352.
I believe that this behaviour it is consistent with other invalid field errors:
```
iex(1)> defmodule Foo.Bar do
...(1)>   defstruct [a: 1]
...(1)>   def bar, do: %__MODULE__{b: 1}
...(1)> end
** (KeyError) key :b not found
expanding struct: Foo.Bar.__struct__/1
```
=> Typespecs: show expanded module name on inexistent struct field error

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
[Below is my intro/pitch from the [previous discussion](https://groups.google.com/g/elixir-lang-core/c/LYmkUopaWN4/m/SwBzRt2zBQAJ) on the elixir-lang-core mailing list.]
Rotate pulls a slice of an enumerable out and replaces that slice somewhere else.
The classic use case is this: Suppose you have a list of to-do items, which the user has ordered by priority:
1. Apply to college
2. Brush the dog
3. Change the car's oil
4. Deliver flowers
5. Exchange gifts
A rotate occurs when the user selects some number of elements and drags them to a new place in the list. Let's say they selected items 3 & 4 from the preceding and dragged them above item 2. When they release the mouse, the new order should be:
1. Apply to college
2. Change the car's oil
3. Deliver flowers
4. Brush the dog
5. Exchange …
=> Add Enum.slide/3

lib/elixir/lib/code/normalizer.ex, lib/elixir/test/elixir/code_normalizer/formatted_ast_test.exs
This was originally reported and fixed by @msaraiva in https://github.com/doorgan/sourceror/pull/30
Considering a tuple like this one:
```elixir
{SomeModule, opt1: true, opt2: false}
```
The last element is a keyword list without square brackets, and the formatter preserves that style. If we use `Code.string_to_qutoed` and then `Code.quoted_to_algebra`(as `Macro.to_string` does), the keyword list gets brackets inserted:
```elixir
iex> opts = [literal_encoder: &{:ok, {:__block__, &2, [&1]}}]
iex> {:ok, quoted} = Code.string_to_quoted("{SomeModule, opt1: true, opt2: false}", opts)
iex> Macro.to_string(quoted)
"{SomeModule, [opt1: true, opt2: false]}"
```
=> Keep keyword format of tuple last element

lib/elixir/lib/config.ex, lib/elixir/test/elixir/config_test.exs
It fixes the following bug:
```elixir
iex(1)> require Config
Config
iex(2)> Config.config_env()
* 2nd argument: not a tuple
:erlang.element(1, nil)
(elixir 1.12.3) lib/config.ex:188: Config.__env__!/0
```
=> Fix Config.config_env/0 with empty Process dictionary

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
This fixes two issues I've discovered in v1.13-rc.0 (stuff that should have been in #11349 😬).
- Adds support for negative _insertion_ indices:
iex> Enum.slide([:a, :b, :c, :d, :e, :f], 1..2, -2)
[:a, :d, :e, :b, :c, :f]
iex> Enum.slide([:a, :b, :c, :d, :e, :f], -5..-3//1, -2)
[:a, :e, :b, :c, :d, :f]
- Give a clear `RuntimeError`, rather than a baffling `CondClauseError`, when you ask for an insertion point that matches the last element of your range
iex> XUtil.Enum.slide([:a, :b, :c, :d, :e, :f], 1..2, 2) 
** (RuntimeError) Insertion index for slide must be outside the range being moved (tried to insert 1..2 at 2)
=> Correct oversights in Enum.slide/3

lib/elixir/lib/map.ex
Per the discussion in #11239, this adds a note that if the function you pass to `Map.map/2` produces duplicate keys, only the last one will be kept.
=> Call out what happens to duplicate keys in Map.map/2 in the docs

lib/elixir/lib/application.ex, lib/elixir/test/elixir/application_test.exs, lib/mix/test/mix/tasks/archive_test.exs
In Elixir v1.12.0 it is giving the following error
when calling `Application.compile_env(@app, :key)`
** (FunctionClauseError) no function clause matching in Application."MACRO-compile_env"/4
=> Allow Application.compile_env* to accept attributes

lib/elixir/lib/task/supervisor.ex
This fixes a few issues I ran into while digging into the `Task.Supervisor` documentation for the first time.
Most of it is pretty minor, but there are maybe two things worth calling out:
1. In 2017, 6d1deb2032d1a9b21877a6757033de1bc88987a0 migrated `Task.Supervisor` to use `DynamicSupervisor`. In doing so, it added an optional keyword list to many of the functions, but not all of the docs got updated to note the correct number of arguments on those functions.
2. The `start_link/1` docs indicated that it was possible for `async` to receive `:restart` options, which as best I can tell hasn't been true at least since that 2017 rewrite.
=> Corrections, clarifications, and copyediting to Task.Supervisor docs

lib/iex/lib/iex/server.ex
Stopping evaluator before exit IEx.Server seems to be fixing the issue https://github.com/elixir-lang/elixir/issues/11385
However, I might be missing some other use cases.
=> Remsh: stop IEx.Evaluator before exit IEx.Server

lib/elixir/lib/task/supervisor.ex
Clarify that `Task.Supervisor.children/1` ignores children that are restarting.
Plus note about calling the function under low memory condition, (same that applies to `DynamicSupervisor.which_children/1`)
=> Add note to `Task.Supervisor.children/1`

lib/elixir/lib/code/normalizer.ex, lib/elixir/test/elixir/code_normalizer/formatted_ast_test.exs
This fixes #11393 
It turns out this was another normalizer bug.
The AST for a module attribute is
```elixir
{:@, attr_meta, [
{:name, name_meta, [value]}
]}
```
`value` here is any quoted expression.
This was handled as 2 nested calls: one pass for `:@` and one for `:name`. The second pass for `:name` won't know that it's part of a module attribute definition, so it will be handled as a function call. The formatter removes brackets whenever possible on function call, which caused the bug.
I figured adding a new clause would be more predictable than adding more fields to the `state` that we then need to clean up.
=> Fix normalizer not preserving user choice on module attribute lists

lib/elixir/lib/registry.ex, lib/elixir/test/elixir/registry_test.exs
PR is based on [this proposal](https://groups.google.com/g/elixir-lang-core/c/chazhfKGmOg)
Adds `Registry.count_select/2`
I was doubting if it should accept arbitrary full match spec or only `match_head` and optional `guards` similar to `count_match/4`, considering that the third element of the spec is always `[true]`, we could hide that.
However, by accepting full match spec we enable users to make use of [ex2ms](https://github.com/ericmj/ex2ms)
=> add Registry.count_select/2

lib/elixir/lib/exception.ex, lib/elixir/lib/inspect.ex, lib/elixir/lib/inspect/algebra.ex, lib/elixir/lib/inspect/utils.ex, lib/elixir/src/elixir_compiler.erl, lib/elixir/test/elixir/inspect_test.exs, lib/ex_unit/test/ex_unit/formatter_test.exs
When a faulty implementation of the Inspect protocol is used,
the user is returned an `Inspect.Error` struct when the user tries to inspect it,
also IEx prints `Inspect.Error` upon inspection or when a struct with a fault inspect is returned.
This is the default behaviour in Elixir, because it uses the :safe  option in Inspect.Opts is to true by default.
Since Kernel.inspect/2 will return a string, an no warning is emitted, it is very likely that an error like this can go unnoticed.
This PR tries to make it as clear as possible for the user, by introducing the :stacktrace field in the Inspect.Error exception,
and by emitting a runtime warning.
Given the following faulty implementation:
```elixir
defmodule Failing do
@enforce_keys [:name]
defstruct @enforce_keys
defimpl Inspect do
def …
```
=> Improve user experience when there is a faulty Inspect implementation

lib/elixir/src/elixir_compiler.erl
Module bodies, especially in tests, tend to be
long, which affects the performance of passes
such as beam_ssa_opt and beam_bool. This commit
disables those passes during module definition.
As an example, this makes loading Elixir's test
suite 7-8% faster.
=> Disable ssa and bool passes

lib/elixir/lib/stream.ex
Simple fix, the sentence was just worded a little oddly so I took out the extra "and an accumulator."
=> Fixed Verbiage in documentation for Stream.transform/3

lib/elixir/lib/version.ex
Do not pattern match on internal opaque type structure
outside of the module with that opaque type definition.
Fixes related dialyzer issues.
=> Fix opaque Version.Requirement usage

lib/elixir/lib/code/normalizer.ex, lib/elixir/test/elixir/code_normalizer/formatted_ast_test.exs
Regular blocks were interpreted as a call, so if the last expression in a block was a kw list then the wrapper block would be removed, causing the formatter to crash
=> Fix normalization of kw list in blocks

lib/elixir/lib/keyword.ex, lib/elixir/lib/map.ex, lib/elixir/lib/map_set.ex, lib/elixir/test/elixir/map_set_test.exs, lib/mix/lib/mix/compilers/elixir.ex, lib/mix/lib/mix/tasks/compile.protocols.ex
The map operation is optimized since Erlang/OTP 24+
as we don't need to do an additional traversal to
create tuples.
=> Add Map.from_keys/2 and Keyword.from_keys/2

lib/iex/lib/iex.ex, lib/iex/lib/iex/evaluator.ex, lib/iex/lib/iex/server.ex, lib/iex/test/iex/helpers_test.exs
Please refer to #11418 for a feature discussion.
I am not sure if the error message is descriptive enough, but AFAIU for a better report we’d need to introduce a new type of error and I tend to avoid it here.
=> #11418 Disallow shorthand pipe after matches

CHANGELOG.md
Make it more clear what the behavior change is.
Relates to this change: https://github.com/elixir-lang/elixir/commit/587c80eae6e29002370523f79273d56dabd48582#diff-43a76a6112c9082ee3ddb63acc2419db8764edd039cb52e29e436734b414574b
Related ElixirForum post: https://elixirforum.com/t/elixir-version-of-a-safe-navigation-operator-navigating-nil-in-maps-structs/6023/29
=> Update wording for 1.13 get_in update

lib/elixir/lib/version.ex
This is to avoid ambiguity in cases like
iex> Version.parse_requirement!("~> 1.2.3 or < 3.4.5 and > 5.6.7")
#Version.Requirement<~> 1.2.3 or < 3.4.5 and > 5.6.7>
Before:
After:
=> Colorize Version.Requirement source in Inspect protocol

lib/elixir/lib/base.ex, lib/elixir/test/elixir/base_test.exs
Each `Base` function had `keyword` as the option type, which didn't help guard against typos or mismatched options.
This also includes a small fix to the `identity` spec, which passed unused options in many cases and used `pad:` rather than `padding:` where appropriate.
=> Specific base typespecs

lib/elixir/lib/stream.ex, lib/elixir/test/elixir/stream_test.exs
@josevalim  mentioned in [this twitch stream](https://www.twitch.tv/videos/1225900187) (around minute 37) that Stream.duplicate/2 would be a good addition.  Thoughts?
```
iex> stream = Stream.duplicate([1, 2], 3)
iex> Enum.to_list(stream)
[[1, 2], [1, 2], [1, 2]]
```
=> Add Stream.duplicate/1

lib/mix/lib/mix/tasks/test.coverage.ex, lib/mix/test/mix/tasks/test_test.exs
Adds an explicit warning when exiting with an error code because of a
failed test coverage threshold.
Example:
```
-----------|--------------------------
62.35% | Total
Coverage test failed, threshold not met:
Coverage:   62.35%
Threshold: 100.00%
```
=> Mix.Tasks.Test.Coverage warns on failure

lib/elixir/src/elixir_errors.erl, lib/elixir/test/elixir/kernel/errors_test.exs
Restriction added only for "missing terminator" error + empty line.
We could inform the user that EOF was reached, but not all evaluated elixir code is in a file. For example:
```sh
elixir -e "defmodule Foo do"
```
should show: 
```
** (TokenMissingError) nofile:1:17: missing terminator: end (for "do" starting at line 1)
|
1 | defmodule Foo do
|                 ^
(elixir 1.14.0-dev) lib/code.ex:403: Code.validated_eval_string/3
```
So I didn't add it. Let me know if you think it is worth it, shouldn't be a big of a change.
=> Don't show snippet for EOF line

lib/elixir/lib/module.ex
Export `t:Module.definition/0` and `t:Module.def_kind/0`.
They are referenced throughout the documentation for `Module` so it makes sense to expose them.
=> Export types in Module

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/kernel_test.exs
Fixes #11469
I'm not 100% about where would be the best place to add a test, if one is needed
=> Set a max line_length for Macro.to_string

lib/elixir/lib/keyword.ex
Use the more concise syntax on Keyword examples, and add an example to `Keyword.replace_lazy/3` with a duplicated key
=> Improve Keyword docs and examples

lib/elixir/docs.exs, lib/elixir/lib/dynamic_supervisor.ex, lib/elixir/lib/partition_supervisor.ex, lib/elixir/lib/supervisor.ex, lib/elixir/lib/task/supervisor.ex, lib/elixir/test/elixir/dynamic_supervisor_test.exs, lib/elixir/test/elixir/partition_supervisor_test.exs
A supervisor with that starts multiple partitions of the same child.
Certain processes may become bottlenecks in large systems.
If those processes can have their state trivially partitioned,
in a way there is no dependency between them, then they can use
the `PartitionSupervisor` to create multiple isolated and
independent partitions.
Once the `PartitionSupervisor` starts, you can dispatch to its
children using `{:via, PartitionSupervisor, {name, key}}`, where
`name` is the name of the `PartitionSupervisor` and key is used
for routing.
=> Add PartitionSupervisor

lib/elixir/test/elixir/typespec_test.exs
To be consistent with b1414ee1d0d78a6681303d24a07e2254bcb76e39
=> Use Enumerable.t() outside Enum module

lib/elixir/lib/string.ex
I'm not sure if this is right, so I'm leaving it here as a suggestion, but it seems like there is a double "when" on the TODO comment.
=> Remove double when on TODO comment

lib/elixir/lib/base.ex, lib/elixir/test/elixir/base_test.exs
As discussed on today's livestream, what to do about "odd-length string" may not be immediately obvious.
=> Make Base.decode16's odd-length message more helpful

lib/mix/lib/mix/tasks/format.ex
Would you consider allowing plugins to override the builtin formatter for `.ex`/`.exs` files?
=> Check plugins first so they can format `.ex` and `.exs` files

lib/mix/lib/mix/release.ex, lib/mix/lib/mix/tasks/release.ex, lib/mix/test/mix/release_test.exs
Today, there is a mode validation check when doing a Mix Release that
prevents a parent application that has an application mode of
`:permanent`, for example, while a child application has mode `:load`,
as it might be unsafe.
However, some complex applications may need more control over the
application load/start order.  For such cases, the user would need a
way to tell Mix.Release to don't be strict while constructing the
`.rel` file.
Here, we add an option `:skip_mode_validation_for` to the release
options (default: `[]`) which disables such strict check to specified
applicaations.  The default value ensures the current behavior is
preserved.
=> Allow bypassing application mode validation in release spec

lib/elixir/lib/string.ex
After updating my fork and running `make test`, I got the following:
```
1) doctest String.replace/4 (103) (StringTest)
test/elixir/string_test.exs:6
Doctest failed
doctest:
iex> String.replace(String.normalize("é", :nfd), "e", "o")
"ó"
code:  String.replace(String.normalize("é", :nfd), "e", "o") === "ó"
left:  "ó"
right: "ó"
stacktrace:
lib/string.ex:1519: String (module)
```
Something was wrong with the expected `"ó"` character, so I corrected it. Tests now run without any failures.
=> Fix failing doctest for String.replace/3

lib/elixir/lib/enum.ex
1. It replaces the your of "I" pronoun with "You" which is the standard in the docs.
2. It replaces "value" with "element" which is the terminology and type used in Enum.
3. It replace "ints" with "integers" to make example more readable.
=> Streamline t:Enumerable.t/1 docs

lib/elixir/pages/typespecs.md
I was hit by this one last night and took me a while to figure it out.
The writing could be improved though.
The Erlang documentation could also be improved.
https://www.erlang.org/doc/reference_manual/typespec.html
=> Add note about which attributes support guard notation in typespecs

lib/elixir/lib/protocol.ex, lib/elixir/test/elixir/kernel/warning_test.exs
During the upgrade to elixir v1.13 I got a compilation error caused by a 0-arity callback defined inside a protocol. Since  #10912 the expected behavior in these scenarios is to show a warning for the callbacks inside the protocol, seems that we don't yet support 0-arity callbacks defined without parens.
Compilation error:
```
* 1st argument: not a list
:erlang.length(nil)
(elixir 1.13.1) lib/protocol.ex:726: Protocol.callback_ast_to_fa/1
(stdlib 3.17) lists.erl:1254: :lists.flatmap/2
(elixir 1.13.1) lib/protocol.ex:742: Protocol.callback_metas/2
(elixir 1.13.1) lib/protocol.ex:761: Protocol.__before_compile__/1
(stdlib 3.17) lists.erl:1267: :lists.foldl/3
```
Example of a module that triggers the compilation error:
```elixir …
```
=> Warn on 0-arity callbacks inside protocols

lib/elixir/lib/base.ex
Recently I got warning from Dialyzer when calling `Base.decode16!(some_text, case: :mixed)`. I found that the typespec is using `encode_case` type instead of `decode_case` type.
=> Fix typespec for Base.decode16!/2

lib/elixir/lib/kernel/typespec.ex, lib/elixir/test/elixir/typespec_test.exs
=> Define exception field as true instead of term when expanding struct type

lib/elixir/lib/file.ex
=> Fix hidden escape chars in File.stream!/3 docs

.github/workflows/release.yml
Trying to tackle #11318. This PR create a new workflow to build and publish asset when GitHub Release is created. Here it's summarized: 
* When the tag is created, the workflow will create a draft release start building Elixir.
* Build Elixir with 3 OTP versions, 22, 23, and 24. And upload assets to the release. Those OTP releases is the latest of OTP in each release.
* Build Docs.zip against OTP 24 and upload it to the release.
* Generate `sha1.txt` and `sha256.txt` for the checksum of zip files.
Here is the workflow [1]: 
And the release [2]:
[1] https://github.com/wingyplus/elixir/actions/runs/1634690409
[2] https://github.com/wingyplus/elixir/releases/tag/v1.14.0-dev
=> Pre-built Elixir release

lib/elixir/src/elixir_erl_for.erl, lib/elixir/test/elixir/kernel/comprehension_test.exs
Current implementation of `:elixir_erl_for.build_reduce/7` discards a scope, resulting in an accumulator name clash for nested `for/1`s when `into:` option is passed to more than one of them:
```elixir
for x <- [1, 1, 2], uniq: true do
for y <- [3, 3], uniq: true do
x * y
end
end
#⇒ ** (MatchError) no match of right hand side value: {[3], %{3 => true}}
```
Expected behaviour:
```elixir
#⇒ [[3], [6]]
```
This PR provides a fix by preserving a scope in calls to `build_reduce/7`.
=> Fix the nested `uniq:` acc name clash by preserving a scope

lib/elixir/lib/kernel/special_forms.ex
based on https://elixirforum.com/t/for-comprehension-theres-no-assignment-only-filters/44930/10
Adding mention of variable assignment as filters, and provide alternative for variable assignment based on generators.
=> Add assignment as generator documentation at for comprehension

lib/elixir/lib/calendar/datetime.ex
Hi,
I noticed a couple of functions in the `DateTime` module had the default argument name `map` in the documentation, while the rest is consistently `datetime`.
`to_naive(map)` -> `to_naive(datetime)`
=> Use consistent argument name in DateTime doc

lib/elixir/lib/atom.ex, lib/elixir/src/elixir.erl, lib/elixir/src/elixir_aliases.erl, lib/elixir/src/elixir_erl.erl, lib/elixir/src/elixir_expand.erl, lib/elixir/src/elixir_quote.erl, lib/elixir/src/elixir_rewrite.erl, lib/elixir/test/elixir/kernel/warning_test.exs
This function was added in OTP 23 and its the functional equivalent to
`:erlang.atom_to_binary/2` with `:utf8` as the second argument.
Part of #9603
=> Use :erlang.atom_to_binary/1

.github/workflows/notify.exs
Fun fact, this was discovered in a tree-sitter-elixir CI run :smile_cat:
=> Fix syntax in notifications script

lib/elixir/lib/file.ex
`File.write/2` and `File.write!/2` has similar codes.
this PR change `File.write!/2` to call `File.write/2`, likes `File.rm!` , `File.cp!` ...
other motivation:
`File.write/2` and `File.write!/2` has bit different when passed character list  👀
```
iex(2)> File.write(["hoge.txt"], "content")
:ok
iex(3)> File.write!(["hoge.txt"], "content")
** (File.Error) could not write to file "hoge.txt": bad argument
(elixir 1.12.2) lib/file.ex:1054: File.write!/3
```
=> refactoring: File.write!/2  calls File.write/2

.github/workflows/notify.exs
Currently, the notify.exs will generate the checksum to:
```
* Docs.zip - sha1sum - 3812e2db7c71a6a8b03b75d06ca6debb46aebc55  Docs.zip
* Docs.zip - sha256sum - cafe86adc01fcc700c83f353aedf746eeffd3b6e1542cedff18af64956ae539b  Docs.zip
* elixir-otp-23.zip - sha1sum - 35f999b98cbfa5888fefbeafaaf73f661a903bb7  elixir-otp-23.zip
* elixir-otp-23.zip - sha256sum - 11f970adc3ddc759f349b0e00b6aecd06a1d460f21488d2ffe8f6738f2518728  elixir-otp-23.zip
* elixir-otp-24.zip - sha1sum - c4224ce1b78247d7c5e04c7cd4576496fd49f002  elixir-otp-24.zip
* elixir-otp-24.zip - sha256sum - 677fe7a147a40e5ee876eeb7bb8e4b968d2a8a9c42793561b61a08269ca91c19  elixir-otp-24.zip
```
The result have a file name and newline at the end of each line. This change strip
that, so the result will be:
```
* Docs.zip - sha1sum - …
```
=> Strip name from checksum file

lib/elixir/src/elixir.hrl, lib/elixir/src/elixir_bitstring.erl, lib/elixir/src/elixir_erl_pass.erl, lib/elixir/src/elixir_expand.erl, lib/elixir/src/elixir_rewrite.erl, lib/elixir/test/elixir/kernel/binary_test.exs, lib/elixir/test/elixir/kernel/expansion_test.exs
Related with https://github.com/elixir-lang/elixir/issues/9603 (and also this reported issue https://github.com/elixir-lang/elixir/issues/10890).
In order to support the usage of guard expressions to calculate sizes in bitstring matching, the validations logic is affected, because only integer and variables were being allowed so far.
The changes implemented in OTP 23 offer more freedom to developers since guard expressions are now allowed, but there are cases where expressions would result in non-integer size values. In those cases, the match fails but no compilation or specific errors.
See https://github.com/erlang/eep/blob/master/eeps/eep-0052.md#rationale and please confirm this also makes sense for Elixir (which is what I assumed).
Note: This solution is reusing the guard expansion …
=> EEP 52: Support for size expression in bitstring matching

lib/elixir/lib/kernel/special_forms.ex
👋  I wanted to add something to the documentation for `try/after` to indicate that you cannot return anything from the `after` block.  When you spend some time thinking about it - it makes sense that `after` could never return a value, but so many of the examples show the `after` block at the bottom which is usually where the return value for a block of code comes from.
=> Enhance documentation for SpecialForms.try

lib/elixir/lib/kernel.ex
Current docs treat membership tests on lists and ranges using `Kernel.in/2` with the same warning in the doc saying that comparison on large lists/ranges is inefficient.
This is true for lists, but not for ranges. A more efficient check is done there which can run in constant time.
Update docs to explain that.
Have omitted going into detail on how membership checks for ranges with steps are done, as that seems less relevant, and the general comment that the check can be done efficiently still holds true.
=> expand Kernel.in/2 docs re range check efficiency

lib/mix/lib/mix/tasks/test.coverage.ex
An incorrect variable is being passed to the `display/2` function on line [353 ](https://github.com/sh41/elixir/blob/51811b24bb84dea7be87bfdddf21244fd47065b2/lib/mix/lib/mix/tasks/test.coverage.ex#L353)for the Total line in the coverage summary report. The result is that that Total line will always display in red no matter what the threshold is set to. 
The correct threshold value is retrieved on line [348 ](https://github.com/sh41/elixir/blob/51811b24bb84dea7be87bfdddf21244fd47065b2/lib/mix/lib/mix/tasks/test.coverage.ex#L348)from the `opts` or the default and is used on line [351 ](https://github.com/sh41/elixir/blob/51811b24bb84dea7be87bfdddf21244fd47065b2/lib/mix/lib/mix/tasks/test.coverage.ex#L351)for the body of the summary report. The final call to display then reverts to using the …
=> Fix coverage threshold ignored for Total line in Summary

lib/elixir/lib/code/normalizer.ex, lib/elixir/test/elixir/code_normalizer/formatted_ast_test.exs, lib/elixir/test/elixir/code_normalizer/quoted_ast_test.exs, lib/elixir/test/elixir/kernel/quote_test.exs, lib/elixir/test/elixir/macro_test.exs
The following code would crash:
iex> Code.quoted_to_algebra(Elixir)
** (MatchError) no match of right hand side value: "Elixir"
(elixir 1.13.1) lib/code/normalizer.ex:254: Code.Normalizer.normalize_literal/3
(elixir 1.13.1) lib/code.ex:1107: Code.quoted_to_algebra/2
Therefore, this as well:
iex> Macro.to_string(Elixir)
** (MatchError) no match of right hand side value: "Elixir"
(elixir 1.13.1) lib/code/normalizer.ex:254: Code.Normalizer.normalize_literal/3
(elixir 1.13.1) lib/code.ex:1107: Code.quoted_to_algebra/2
(elixir 1.13.1) lib/macro.ex:948: Macro.to_string/1
=> Fix bug with edge-case when converting to algebra quoted Elixir alias

lib/elixir/lib/enum.ex
1. Uses anonymous functions instead of the mention of the function itself when it applies.
2. Rename argument from `fun` to `sorter` as it is not necessarily a function.
=> Improve docs for Enum.sort*

lib/elixir/pages/unicode-security.md, lib/elixir/pages/unicode-syntax.md, lib/elixir/test/elixir/kernel/parser_test.exs, lib/elixir/unicode/IdentifierType.txt, lib/elixir/unicode/tokenizer.ex, lib/elixir/unicode/unicode.ex
(This was originally extracted from the [reference implementation of UTS39](https://github.com/elixir-lang/elixir/pull/11569), which has a much higher-level overview).
This PR prevents Elixir identifiers from including \p{Identifier_Status=Restricted} codepoints; implemented using the unicode 'IdentifierTypes' that correspond to the 'Restricted' status, so that if Elixir wanted to allow some additional 'IdentifierTypes' like eg. 'Technical' characters it could do so, while still preventing 'Uncommon_Use' or 'Obsolete' codepoints (if documented, still conformant w/uts39). This impl conforms with UTS 39, clause 1 ('general security profile for identifiers'); added a new page to docs, with subheading for Clauses C1-C5 from the standard, similar to how unicode-syntax.md has R1-R6 for the …
=> Don't allow restricted characters in identifiers (UTS 39, C1)

lib/elixir/src/elixir.erl, lib/elixir/test/elixir/code_test.exs
Before this fix, evaluating `b = a` with assignments of: `a: 1, a: 2, c:
3` would eval AST equivalent to `^c = a`. This happened due to binding
normalization generating version numbers larger than the total number of
bindings. Later in the pipeline, the number of bindings is used to
compute the next version number, which would then conflict with an
existing binding.
This commit fixes that by not increasing the version number when
a repeated binding is normalized.
Closes #11581
=> Fix duplicate bindings causing weird behaviour

lib/mix/lib/mix/tasks/format.ex, lib/mix/test/mix/tasks/format_test.exs
Support Sigils inside embedded expressions in files formatted by a formatter plugin.
Implementation of https://groups.google.com/g/elixir-lang-core/c/jFswzSUjsP4
=> Embedded Elixir Expressions in Formatter Plugins

lib/elixir/lib/code/formatter.ex, lib/elixir/test/elixir/code_formatter/general_test.exs, lib/mix/lib/mix/tasks/format.ex, lib/mix/test/mix/tasks/format_test.exs
Allows formatter plugins to print errors with accurate file and
line information. The line is only provided when a sigil is being
formatted.
Plugins would be able to log error information similar to how Code.format_string!/2
errors are logged for compile errors when formatting Elixir code.
=> Supply file and line to formatter plugins

lib/elixir/lib/kernel.ex
PR attempts to clarify that some examples, while valid, are not actually useful.
Current documentation states "The main feature of `get_in/2` is precisely that it aborts traversal  when a `nil` value is found.".
Unless I'm missing something, this is not accurate; the main and only actual feature of `get_in` is how it treats functions. `nil` safety is already given by the fact that `nil[...]` returns `nil`.
=> Tweak documentation for `get_in`

lib/mix/lib/mix/release.ex, lib/mix/test/mix/release_test.exs
Currently, if a `releases/COOKIE` file exists with a given cookie, and
a user later manually adds a `:cookie` configuration to the release,
then, even using the flag `--overwrite` when releasing, the user is
asked if they want to overwrite the file.
To reproduce:
1. `mix new myapp && cd myapp`
2. Add a simple release to it without defining a cookie:
```elixir
releases: [
myapp: [
applications: [
myapp: :permanent
]
]
]
```
3. `mix release` (random cookie gets generated)
4. Add a manual cookie to the release:
```elixir
releases: [
myapp: [
applications: [
myapp: :permanent
],
cookie: "somecookie"  # <---
]
]
```
5. `mix release --overwrite`
6. User gets asked if they want to overwrite `releases/COOKIE`.
```
mix release --overwrite
Generated myapp app
* assembling myapp-0.1.0 on MIX_ENV=dev …
```
=> fix(release): do not ask to change cookie if overwrite is set

lib/mix/lib/mix/task.ex, lib/mix/lib/mix/tasks/do.ex, lib/mix/test/mix/tasks/do_test.exs
This PR implements an idea that was proposed in the discussion about #10984.
The idea is to add the `--app` option to the `do` task, so we have more control to indicate where tasks are executed (which makes sense in the context of umbrella projects).
#10984 is solved in an indirect way because this solution will emit warnings when the given apps do not exist, something that is impossible in the context of the `cmd` task (the other task that accepts `--app` so far). So, we would need to teach that it is better to run tasks (even the `cmd task`) via `mix do` if we want to indicate in which apps tasks should run.
```bash
mix do --app my_app --app second_app test, cmd echo hello
==> my_app
...
1 doctest, 1 test, 0 failures
==> second_app
...
1 doctest, 1 test, 0 failures
==> my_app
hello
==> …
```
=> Add the ability to run tasks in given apps for umbrella applications

lib/iex/lib/iex/helpers.ex, lib/iex/test/iex/helpers_test.exs
It's a follow-up PR to #11536 to fix typo, but it also moves tests around atoms into a separate test.
Open question: should `pid/1` throw an exception if no process found by the name?
=> Update tests for pid/1 IEx helper

lib/elixir/lib/kernel.ex, lib/elixir/lib/string.ex
So far Elixir only exposed binary_part/3 as part of its
functions to manipulate binaries, since that's allowed in
guards.
However, `binary_part/3` is quite limited in that it
expects both `start` and `start+size` to fall within the
binary. This could lead developers to use String.slice/2
or String.slice/3 when a binary operation would be more
performant or appropriate.
This pull request therefore adds `binary_slice/2` and
`binary_slice/3` that nicely integrates with binaries
and ranges, and behaves similarly to their `Enum.slice`
and `String.slice` counterparts.
=> Add binary_slice/2 and binary_slice/3

lib/elixir/lib/string_io.ex
This fixes #11619 by removing `child_spec/1` from the `StringIO` docs.
=> Remove `child_spec/1` from `StringIO` docs

lib/elixir/lib/config.ex
While upgrading an application from 1.8, it wasn't clear from the docs how to replace `Mix.env()` calls outside of config files. After some brief discussion and a quick local test, I found a simple solution that will compliment the existing docs, assuming it works as expected.
This will work as expected, right?
=> Clarify app env usage

lib/ex_unit/test/ex_unit/capture_log_test.exs, lib/logger/lib/logger/backends/console.ex, lib/logger/lib/logger/formatter.ex, lib/logger/test/logger/formatter_test.exs, lib/logger/test/logger/handler_test.exs, lib/logger/test/logger/translator_test.exs, lib/logger/test/logger_test.exs
This PR fixes #11629.
- `$levelpad` is removed from `@default_pattern` of `Logger.Formatter`
- Functions related to levelpad are annotated with `@deprecated`
=> Deprecate levelpad of Logger.Formatter

lib/mix/test/mix/dep_test.exs
:digraph_utils.topsort/1 can return a different (but also valid)
topological ordering
The test failure on OTP 25.0-rc1 was:
1) test deps_paths (Mix.DepTest)
test/mix/dep_test.exs:491
Assertion with == failed
code:  assert Enum.map(Mix.Dep.load_on_environment([]), & &1.app) == [:git_repo, :abc_repo, :deps_repo]
left:  [:abc_repo, :git_repo, :deps_repo]
right: [:git_repo, :abc_repo, :deps_repo]
stacktrace:
test/mix/dep_test.exs:499: anonymous fn/0 in Mix.DepTest."test deps_paths"/1
(elixir 1.14.0-dev) lib/file.ex:1555: File.cd!/2
test/test_helper.exs:127: MixTest.Case.in_fixture/3
test/mix/dep_test.exs:31: Mix.DepTest.with_deps/2
test/mix/dep_test.exs:497: (test)
=> Update Mix.DepTest for OTP 25

lib/mix/test/mix/tasks/test_test.exs
The order in which tests for umbrella applications get executed can be different
depending on OTP version. See also #11636
The test failure was:
1) test logs and errors umbrella with file path (Mix.Tasks.TestTest)
test/mix/tasks/test_test.exs:432
Assertion with =~ failed
code:  assert mix(["test", "apps/unknown_app/test"]) =~
"==> bar\nPaths given to \"mix test\" did not match any directory/file: apps/unknown_app/test\n==> foo\nPaths given to \"mix test\" did not match any directory/file: apps/unknown_app/test\n"
left:  "==> foo\nCompiling 1 file (.ex)\nGenerated foo app\n==> bar\nCompiling 1 file (.ex)\nGenerated bar app\n==> foo\nPaths given to \"mix test\" did not match any directory/file: apps/unknown_app/test\n==> bar\nPaths given to \"mix test\" did not match any directory/file: …
=> Update Mix.TasksTestTest for OTP 25

lib/elixir/lib/gen_server.ex
There is currently no reference in the GenServer documentation about how the exit reason impacts the supervision tree and related processes. I found the relevant information in the Supervisor documentation. I think it would be good to add that reference to the GenServer docs, as I was personally searching through the GenServer docs for `:stop` and no references to the exit reason came up.
=> Add explanation for exit reason to GenServer

lib/mix/lib/mix/dep/loader.ex, lib/mix/lib/mix/tasks/deps.ex, lib/mix/lib/mix/tasks/local.rebar.ex, lib/mix/test/mix/dep_test.exs, lib/mix/test/test_helper.exs
* Remove mentions from documentation
* Remove rebar from @scm_manager in Mix.Dep.Loader
* Change manager: :rebar to manager: :rebar3 in test
* Remove rebar_exclude test filter from mix test_helper.exs
(there are no more Rebar 2 tests after they got removed
in 5cca5e5fbb48d746b03e38b41d1b7b1b33c4fb26 )
=> Remove Rebar 2 leftovers

lib/mix/lib/mix/tasks/local.rebar.ex
This PR would handle the `mix local.rebar` task called with no arguments (path for `rebar3`):
It fix the current error:
```
mix local.rebar --force
** (Mix) Invalid arguments given to mix local.rebar. To find out the proper call syntax run "mix help local.rebar"
```
and trace command action:
```
mix local.rebar --force
* installing Rebar locally from "https://repo.hex.pm/installs/1.13.0/rebar3-3.15.2" with options [sha512: "dc559ace623406453c424debbcccb3eca3d40403920f6be0e240f5ec7e8f2836886fd3a3d6355e06d924781143f1275c35067e8ad7d1fe0995e35e74dedc6f17", force: true]
* creating /home/user/.mix/elixir/1.14.0/rebar3
```
=> Handle 'mix local.rebar' command options without arguments

lib/mix/lib/mix/release.ex
Neither `:version_path` nor `:version` seem to be set to `{:from_app, app}`.
Close #11654
=> Remove `{:from_app, app}` from typespec and docs

lib/mix/lib/mix/tasks/profile.cprof.ex, lib/mix/lib/mix/tasks/profile.eprof.ex, lib/mix/lib/mix/tasks/profile.fprof.ex, lib/mix/test/mix/tasks/profile.cprof_test.exs, lib/mix/test/mix/tasks/profile.eprof_test.exs, lib/mix/test/mix/tasks/profile.fprof_test.exs
As discussed in: https://groups.google.com/g/elixir-lang-core/c/f0gP0It-yuU
But basically:
* right now no return value is documented/discussed so should not
be relied upon
* the original profiler themselves all return the return value,
so it should be possible
* I need it in Benchee :angel:
Happy to make any kind of adjustments. I was thinking about introducing a behavior as all of these functions were very samey (and in fact in Benchee we rely on them being the same) but not sure it's needed here.
Thanks for all your work y'all! :green_heart: 
The bunny thanks thee!
=> Profiler return the return value of the function

bin/elixir, lib/elixir/lib/kernel/cli.ex, lib/elixir/test/elixir/kernel/cli_test.exs
Before this patch we had this:
iex> :os.cmd('elixir --sname foo --rpc-eval bar')
''
iex> :os.cmd('elixir --sname foo --rpc-eval')
'No file named \n'
=> Show errors for incorrect `--rpc-eval` usage

lib/elixir/lib/dynamic_supervisor.ex, lib/elixir/lib/supervisor.ex
Adjust child_spec documentation to note that DynamicSupervisor requires the :id field, but ignores the value otherwise.
=> child_spec documentation for DynamicSupervisor

lib/elixir/src/elixir.erl, lib/elixir/test/elixir/code_test.exs, lib/iex/lib/iex/evaluator.ex
The stacktraces now include the evaluation file and line.
=> Improve eval stacktraces on Erlang/OTP 25+

lib/eex/lib/eex/compiler.ex, lib/eex/lib/eex/tokenizer.ex, lib/eex/test/eex/tokenizer_test.exs
This commit moves the line and column to the last argument to be handled as a metadata as you can see in the example below:
```elixir
assert T.tokenize('foo', 1, 1, @opts) ==
{:ok, [{:text, 'foo', %{line: 1, column: 1}}, {:eof, %{line: 1, column: 4}}]}
```
=> Refactor Eex Tokenizer

lib/elixir/lib/task.ex, lib/elixir/lib/task/supervised.ex, lib/elixir/test/elixir/task_test.exs
This change allows developers to see what the value was when the task failed without breaking changes. in `Task.async_stream`
More details here: https://groups.google.com/g/elixir-lang-core/c/XCQIKQc3KxM
=> Add zip_value_to_exit option to Task.async_stream

lib/elixir/lib/enum.ex
Brought to you by:
```
warning: ExDoc.Markdown.Earmark (warning) lib/elixir/lib/enum.ex:223 Closing unclosed backquotes ` at end of input
```
=> Fix `Enumerable.slice` docs

lib/elixir/lib/module/types/unify.ex, lib/elixir/test/elixir/module/types/types_test.exs, lib/elixir/test/elixir/module/types/unify_test.exs
This may not be the correct way to solve this, since it affects the error messages sometimes in surprising ways, but since I've spent some time debugging this I thought opening a PR is a simple way to show the result of my investigation.
edit: But I kind of like the error messages from test examples, the order of type trace makes sense, maybe just the var names need to be improved.
edit2: Rebased without changes to fix Windows CI
Relates to (closes?) #11658
=> Tweak type unification to fix infinite loop with recursive vars

lib/elixir/lib/macro.ex
I was trying to deal with Macro.pipe and realized that maybe this could be a good/simple/minor improvement for now.
I hope it fits
This PR:
=> Improve Macro.pipe/3 docs

lib/elixir/lib/range.ex, lib/elixir/test/elixir/range_test.exs
When working with ranges a lot, this helps to shift a range in a single, pipe-able operation.
I chose `shift` over `add` because add could be misinterpreted to mean you're expanding the range. DateTime and friends use `add` for moving around.
I still have concerns about `shift` because in an array context `shift` could be taken to mean "remove the first". While elixir doesn't do this, it could be unexpected for those from other languages.
Perhaps this is why the function doesn't exist - but I couldn't find it in the PR or Issue history on the main repo. So even if this gets closed as `wont-merge` it'll at least help with discoverability for the next person.
=> Add Range.shift/2

lib/elixir/lib/inspect/algebra.ex
It is now being called with :infinity atom as width at line 1045
=> Update Inspect.Algebra.fits?/5 spec

lib/mix/lib/mix/release.ex, lib/mix/lib/mix/tasks/release.ex, lib/mix/test/mix/release_test.exs
In releases, the final step for stripping chunks of out BEAM files is to
gzip compress the file. This change lets users pass `compress: false` to
turn this off. Somewhat unintuitively, turning compression off here
enables better compression at a later step. This is due to the archive
compressors being able to process all BEAM files rather than restarting
compression for each individual BEAM file.
For some Nerves devices, reducing the total number of bytes sent to
update software is much more important than reducing the on-disk usage.
This is due to their network connections being metered. Given enough
devices, even small size redunctions can result in meaningful savings.
Here are more details:
The default Nerves configuration puts all of the BEAM files in one
SquashFS archive. While …
=> Support disabling BEAM compression in mix releases

lib/elixir/lib/kernel.ex
The space is not technically missing, so it's not a typo. I just added it for consistency with the common formatting of the documentation.
I'm sorry for this insignificant PR. I can remove it if it's not important.
=> Add space before argument for documentation consistency

lib/logger/lib/logger.ex, lib/logger/lib/logger/app.ex, lib/logger/lib/logger/filter.ex, lib/logger/test/logger_test.exs
Add functions for controlling the logging level on a per-process basis. Currently only supports changing the logging level for the current process.
- Add `Logger.put_process_level/2`,
- Add `Logger.get_process_level/1`,
- Add `Logger.delete_process_level/1`,
- Rewrite `Logger.enable/1`, `Logger.enabled?/1` and `Logger.disable/1` to reuse the new functions.
[Original discussion on elixir-lang-core](https://groups.google.com/g/elixir-lang-core/c/tpoS68TV42s/m/h-6u6E79AwAJ).
=> Add Logger.put_process_level/2 and rewrite enable/1 and disable/1

lib/mix/lib/mix/tasks/do.ex, lib/mix/test/mix/tasks/do_test.exs
I use this language every day for work so I wanted to jump in and contribute. This pull request should close #11682 where PowerShell and cmd would have a hard time handling the comma symbol in `mix do`. Based on the feedback on the issue it was requested to make the plus symbol an alternative. So now instead of doing
```elixir
mix do deps.get, compile
```
you can now also do
```elixir
mix do deps.get + compile
```
I updated the documentation with an example on how that would work.
=> Allow plus symbol in mix do as alternative to comma

lib/elixir/lib/code/formatter.ex, lib/elixir/test/elixir/code_formatter/literals_test.exs
Formatting `:"\\"` preserves the quotes and doesn't transform it as `:\\`, which is a different atom.
Closes #11698
=> Fix bug when formatting :"\\"

lib/elixir/lib/kernel/parallel_compiler.ex, lib/elixir/test/elixir/kernel/parallel_compiler_test.exs, lib/mix/test/mix/tasks/compile.elixir_test.exs
Populates the `position` field in `Mix.Task.Compiler.Diagnostic` when fails to expand a struct (invalid key).
Closes #11700
=> Add line in diagnostic for invalid struct key

lib/ex_unit/lib/ex_unit/assertions.ex
The `catch_exit` doc contains a code example that uses `assert_receive`, while the description above recommends `assert_received`.
Fix the typo in the doc. `assert_receive` would be correct here, as we don't know when the exit message from the spawned process will be delivered to the test process.
=> Fix use of assert_receive[d] in catch_exit doc

lib/elixir/lib/calendar/datetime.ex, lib/elixir/test/elixir/calendar/datetime_test.exs
Allows parsing dates with ISO8601 basic format using `DateTime.from_iso8601`.
=> Support ISO8601 basic format parsing with `DateTime.from_iso8601`

lib/mix/lib/mix/utils.ex
Running `mix local.hex` results in the following error on an IPv6-only freebsd 13.0 jail:
```
$ mix local.hex --force
** (Mix) httpc request failed with: {:failed_connect, [{:to_address, {'repo.hex.pm', 443}}, {:inet, [:inet], :eprotonosupport}]}
```
```
$ iex
Erlang/OTP 24 [erts-12.1.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit] [dtrace] [sharing-preserving]
Interactive Elixir (1.13.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :gen_tcp.connect 'repo.hex.pm', 80, [{:active, false}]
{:error, :eprotonosupport}
iex(2)> :gen_tcp.connect 'repo.hex.pm', 80, [{:active, false}, :inet6]
{:ok, #Port<0.10>}
iex(3)> :gen_tcp.connect 'repo.hex.pm', 443, [{:active, false}]
{:error, :eprotonosupport}
iex(4)> :gen_tcp.connect 'repo.hex.pm', 443, [{:active, false}, …
```
=> Add more reasons to fallback to inet or inet6 for mix

lib/elixir/lib/module/types/expr.ex, lib/elixir/test/elixir/module/types/map_test.exs, lib/elixir/test/elixir/module/types/types_test.exs
=> Change map updates type checking direction

lib/elixir/lib/supervisor.ex
Thank you for all the great documentation! Here's a fix for a typo :)
=> fix typo in the supervisor docs

.github/workflows/ci.yml, .github/workflows/release.yml
- release.yml now automatically fetches latest stable ExDoc version.
- ci.yml now builds docs using latest stable and main ExDoc version.
Related discussion: https://github.com/elixir-lang/ex_doc/issues/1539#issuecomment-1079763510
You can see the successful Release action here: https://github.com/eksperimental/elixir/runs/5711389346?check_suite_focus=true
and the draft release: https://github.com/eksperimental/elixir/releases/tag/untagged-7d5611d46ff9a5abfe44
=> CI: Use latest stable and main ex_doc version

lib/elixir/lib/kernel.ex, lib/elixir/lib/macro.ex
Reading through the documentation of the `then/2` macro It was first a bit confusing what it returns. 
While the examples make this clear, This PR adds the information that the macro returns the result of the given second argument, function `fun`.
For consistency this PR also adds the same explicitness to the `tap/2` macro.
Additionally this PR also replaces the mentions of `|>` with `|>/2` so it directly links to the pipe operator documentation, similar how it was already present in:
https://github.com/elixir-lang/elixir/blob/4095d29b2a10c07f30b2435f91f1c9fbf7ea7d75/lib/iex/lib/iex.ex#L117
=> Improve docs for then and tap

lib/elixir/src/elixir_expand.erl, lib/elixir/src/elixir_module.erl
fixes #11586 
```elixir
iex(1)> alias Nil    
warning: Nil resolves to :'Elixir.Nil'
iex:1
Nil
iex(2)> alias True   
warning: True resolves to :'Elixir.True'
iex:2
True
iex(3)> alias False
warning: False resolves to :'Elixir.False'
iex:3
False
iex(4)> alias Nowarning
Nowarning
iex(5)> 
```
=> Warn if any of True, False, and Nil aliases are used

lib/elixir/lib/version.ex, lib/elixir/test/elixir/version_test.exs
Closes #11735 by implementing the simple fix of re-inserting the "." into the build parts returned from `Version.Parser.parse_version/1`.
Updated two test cases which already had build tags but were not asserting on the parse result, as well as a test for `to_string` on `Version` values.
=> Fix Version.parse/1 incorrectly stripping dots from build field

lib/elixir/lib/registry.ex, lib/elixir/test/elixir/registry_test.exs
=> Make Registry.send work when value part is present

lib/mix/lib/mix/compilers/test.ex, lib/mix/test/mix/tasks/test_test.exs
Run all ExUnit after_suite callbacks even when the suite had no tests.
I tried to respect the boundaries of each application here so it's probably a bit more than what could've been required. I am open to changing it up to something simpler such as this right in `Mix.Tasks.Test` if that's preferred.
```elixir
stats = %{excluded: 0, failures: 0, skipped: 0, total: 0})
after_suite_callbacks = Application.fetch_env!(:ex_unit, :after_suite)
Enum.each(after_suite_callbacks, fn callback -> callback.(stats) end)
```
Also, I wanted to add some tests for the mix task itself but couldn't find a great spot to put this kind of thing in there.
Let me know your feedback! 😃 ❤️ 
Fixes #11746
=> Run after_suite even when no tests were ran

lib/ex_unit/lib/ex_unit/runner.ex, lib/ex_unit/test/ex_unit/case_test.exs, lib/mix/test/mix/cli_test.exs
There are certain tests names that could collide since when sanitizing unknown
characters are replaced with a hyphen.
This avoids test with name "foo-bar" and "foo+bar" to use the same temporary directory.
=> Add short hash to tmp_dir in ExUnit to avoid test name collision

README.md
Once this is merged https://github.com/elixir-lang/elixir-lang.github.com/pull/1604 we can merge this pull request to have a beautiful logo in GitHub dark mode 😄 🌃
=> Add dark logo in README with #gh-dark-mode-only

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
Hi,
I noticed that `Enum.with_index/2` could be optimized for lists using a specialized implementation
- x2 on Intel Chip, see [bench](https://github.com/sabiwara/elixir_benches/blob/main/bench/fast_enum_with_index.results.txt)
- x3 on M1 Chip / OTP 25, see [bench](https://github.com/sabiwara/elixir_benches/blob/main/bench/fast_enum_with_index.results_m1.txt)
~I tried both tail-recursion and [body-recursion](https://github.com/sabiwara/elixir_benches/blob/main/lib/fast_enum.ex#L438-L442=), and went with tail-recursion because it was considerably faster, especially on ARM (x2).~
Edit: after the additional benchmarks from below, I updated to body-recursion which consistently uses less memory. Let me know your thoughts.
=> Optimize Enum.with_index/2 for lists

lib/mix/lib/mix/tasks/escript.build.ex
Previously it was not clear to everyone that the escripts entrypoint
can't be in the `mix.exs` file but has to be separate.
This resulted in rare cases where people asked in the elixir forum why
their escripts module wasn't found.
The proposed changes should make this a bit more clear, though could of
course be improved by some explaining words that accompany the 2 snippets.
Fixes #11770
=> Make individual files in `escript.build` example better distinguishable

lib/ex_unit/lib/ex_unit/case.ex
- Add the missing `:describe_line` tag.
- Reformat the other bullets as this formatting is ignored in ex_doc output anyway and makes it consistent with other sections
=> Add missing known tag `:describe_line` to ExUnit.Case docs

lib/elixir/test/elixir/kernel/defaults_test.exs
The following warning was in the output of the test
warning: variable "foo" does not exist and is being expanded to "foo()", please use parentheses to remove the ambiguity or change the variable name
test/elixir/kernel/defaults_test.exs:75: Kernel.DefaultsTest.Kernel.ErrorsTest.ClauseWithDefaults5.hello/2
=> Remove warning in Kernel default tests

lib/elixir/lib/string.ex
`<<104, 195, 169, 108, 108, 111>>`  was being printed in the test output.
=> Supress output in doctest in String module

lib/elixir/lib/string_io.ex, lib/elixir/test/elixir/string_io_test.exs, lib/logger/lib/logger/backends/console.ex
Mailing list discussion: https://groups.google.com/g/elixir-lang-core/c/RR7nbeHsluQ
This uses the existing `no_translation` erlang error to handle transcoding issues. This will not solve the same problem when using a normal file. (Upcoming PR in OTP itself)
*EDIT: Removed comment about tests since they have been fixed.*
=> Improve Error in case of StringIO write with invalid characters

lib/mix/lib/mix/tasks/release.ex, lib/mix/test/mix/tasks/release_test.exs
As it is confusing to have
"Release created at my_app!" as "!" is not part of the app name.
=> Mix: Remove exclamation mark from message release command

lib/mix/lib/mix/tasks/release.init.ex
Use ## for comments, so when the whole block is comment out, comments stay as comments.
=> Use duoble # for comments in release script

lib/ex_unit/lib/ex_unit/callbacks.ex, lib/ex_unit/test/ex_unit/supervised_test.exs
Adds a version of `start_supervised` and `start_supervised!` that explicitly links the started process to the test process, ensuring that any crashes are propagated to the test, failing it and providing a helpful test failure output.
More context on the change here: https://github.com/elixir-lang/elixir/issues/11737
1. Can we test `start_link_supervised` with a process that crashes where we assert on the EXIT message received without race conditions?
2. Are any other tests missing? I didn't want to repeat every `start_supervised` test since it just delegates to it under the hood, but the `stop_supervised` one was relevant
3. Do the docs make sense?
=> Adds start_link_supervised

lib/ex_unit/lib/ex_unit/callbacks.ex
Found by [dialyzer](https://github.com/michallepicki/elixir-lang-dialyzer-runs/runs/6167409296?check_suite_focus=true) :)
=> Fix ExUnit.Callbacks.start_link_supervised!/2 spec

lib/iex/lib/iex/helpers.ex
VS Code seems to be the most popular editor these days, and it requires a parameter `--goto` for opening files.
I spent a few trials and one web search before I found this out and thought that may be useful for others.
=> Update IEx.Helpers docs for open/1

lib/ex_unit/lib/ex_unit.ex, lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/test/ex_unit_test.exs
This PR add `ExUnit.rerun/1` to rerun tests given a list of test modules.
Often times, when writing a tutorial in Livebook, I want to write a test case for
the users so they could interactively write some code to make it pass. This is especially
helpful when we use Livebook as a teaching medium.
Currently, there are no ways to support ruruning a test without rewriting it. 
Add `ExUnit.rerun/1` to take in a list of test modules to be rerun:
```elixir
defmodule SampleTest do
test "true" do
assert false
end
end
ExUnit.rerun([SampleTest])
```
For more, refer to the [proposal in the mailing list](https://groups.google.com/g/elixir-lang-core/c/KCNzR5Kv0Qg)
=> Add ExUnit.run/1 to rerun test modules

lib/elixir/lib/task.ex, lib/elixir/lib/task/supervisor.ex, lib/elixir/test/elixir/task/supervisor_test.exs, lib/elixir/test/elixir/task_test.exs
This field can be used for reflection purposes.
Closes #11716.
Closes #11720.
=> Store :mfa in the Task struct

lib/elixir/test/elixir/code_test.exs, lib/mix/lib/mix/tasks/format.ex, lib/mix/test/mix/tasks/format_test.exs
Previously it was adding an empty line to empty files during the `mix format` task.
This PR makes it so empty files are skipped and remain unchanged.
Fixes #11800
=> Skip empty files during `mix format`

lib/elixir/lib/gen_server.ex
As I was reading the docs, it was not clear what the `continue` argument
was just by reading its name.
handle_call and handle_cast use `request` for a similar argument,
so I unified it.
=> GenServer: Rename `continue` argument in handle_continue/2

lib/elixir/lib/enum.ex
This commit adds a notice in the docs.
=> Add when :asc/:desc were introduced in Enum.sort/2

lib/elixir/lib/option_parser.ex
This option was missing and it caused a Dialyzer error when used.
=> Add allow_nonexistent_atoms to OptionParser spec

lib/elixir/lib/enum.ex
The speed increase goes from 47% up to 93% for enumerables of up to 100,000 elements.
Benchmark results: https://gist.github.com/eksperimental/c9ed94e418b4caa7fe61aff65b18c836
Benchmark repo: https://github.com/eksperimental/benchmark/tree/enum_sort_by
The optmization is done by saving unnecesary traversing of the list when sorting descendenly.
=> Optimize Enum.sort_by/3 when sorter is :desc

README.md
GitHub says: The unauthenticated git protocol on port 9418 is no longer
supported.
```
$ git clone git://github.com/elixir-lang/ex_doc.git
Cloning into 'ex_doc'...
fatal: remote error:
The unauthenticated git protocol on port 9418 is no longer supported.
Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.
$ git clone https://github.com/elixir-lang/ex_doc.git
Cloning into 'ex_doc'...
remote: Enumerating objects: 18840, done.
remote: Counting objects: 100% (2920/2920), done.
remote: Compressing objects: 100% (1208/1208), done.
remote: Total 18840 (delta 1813), reused 2539 (delta 1638), pack-reused 15920
Receiving objects: 100% (18840/18840), 11.29 MiB | 22.24 MiB/s, done.
Resolving deltas: 100% (10856/10856), done.
```
=> Update README instructions for cloning ex_doc

lib/mix/lib/mix/tasks/format.ex, lib/mix/test/mix/tasks/format_test.exs
Fixes #11817
For better integration with editors when using plugins (e.g. the `.heex` support from `Phoenix.LiveView.HTMLFormatter`), it's useful to be able to pipe data to `mix format` over stdin while preserving support for plugins. Prior to this, stdin was always assumed to be elixir code.
```sh
$ echo "<div>\nhello</div>" | ../../elixir/bin/elixir ../../elixir/bin/mix format --stdin-filename test.html.heex -
<div>
hello
</div>
$ cat .formatter.exs                                                                                 
[
import_deps: [:ecto, :phoenix],
plugins: [Phoenix.LiveView.HTMLFormatter],
inputs: ["*.{ex,exs,heex}", "priv/*/seeds.exs", "{config,lib,test}/**/*.{ex,exs,heex}"],
subdirectories: ["priv/*/migrations"]
]
```
Without specifying the filename:
```sh
$ echo …
```
=> Support filename in `mix format -` when reading from stdin

lib/ex_unit/lib/ex_unit/cli_formatter.ex, lib/ex_unit/test/ex_unit_test.exs
Fixes #11825 
Code example:
```elixir
ExUnit.start(seed: 0, exclude: :skip)
defmodule SkippedTest do
@tag :skip
describe "skip test" do
test "integers" do
assert 1 == 1
end
end
end
```
Result:
=> When all tests are excluded, colorize summary in yellow with message

lib/elixir/lib/exception.ex, lib/elixir/test/elixir/exception_test.exs
Should fix #11820 by reverting the `is_struct` macro during runtime for better guard blaming.
Reverting the macro like that relies heavily on the current `is_struct` implementation, so tests to check if the pattern for the macro output has changed were added. Couldn't find a better option for doing that during runtime ☹
=> Improve Exception blame for is_struct guard by reverting the macro

lib/ex_unit/lib/ex_unit.ex
If anything else is given to this function, the error is the usual "protocol not implemented". With a is_list/1 guard, it's going to be easier to see what went wrong.
=> Add a guard to ExUnit.configure/1

lib/elixir/lib/supervisor.ex
The first change is because the was it is expressed it seems like
only a list of modules, a list of tuples or a list of maps is accepts,
while a list with any of these values is.
The second change mentions that an empty children list will return {:ok, pid}.
=> Clarify docs for Supervisor.start_link/2

lib/elixir/lib/calendar.ex, lib/elixir/test/elixir/calendar_test.exs
```elixir
for width <- ~w(9 10 11), do: Calendar.strftime(~D[1970-01-01], "%#{width}A")
```
```elixir
[" Thursday", "  Thursday", "   Thursday"]
```
```elixir
[" Thursday", "Thursday", "   Thursday"]
```
A width of 10 is set to "1" because the second "0" is parsed as setting the padding character.
This PR changes the parsing of  "0" for padding to only happen if the width is still `nil`, once we begin parsing digits for a width we keep doing so.
=> Handle Calendar.strftime widths with "0" in them

lib/elixir/src/elixir_tokenizer.erl
The warning messages stated that an atom containing starting with a number and containing only ASCII letters, numbers and underscores does not require quoting, e.g. `:401`, but this is not the case; `:401` is a syntax error, as is `:1a`, etc.
This commit changes the warning message to make clear that unquoted atoms/calls and keywords must not start with a number.
=> Improve warning message on quoted atoms/calls/keywords

.formatter.exs, lib/elixir/lib/code.ex, lib/elixir/lib/code/formatter.ex, lib/elixir/test/elixir/code_formatter/containers_test.exs, lib/elixir/test/elixir/module/types/types_test.exs
Hi,
This PR adds a `normalize_bitstring_modifiers` boolean option as specified as https://github.com/elixir-lang/elixir/issues/11811. Hope it helps.
I'm happy to keep working on this issue and add `enforce_calls_on_right_hand_side_of` in an upcoming PR if nobody is working on this.
=> Add `normalize_bitstring_modifiers` option to formatter

lib/elixir/lib/enum.ex
The previous default could go from 1.52x to 2.21x slower; same goes for memory usage.
The benchmark:
https://github.com/eksperimental/benchmark/blob/enum_sort_by/benchmarks/enum_sort_by_default_sorter.exs
The benchmark results:
https://gist.github.com/eksperimental/f16e6df01e193cf075157a932bcd573c
Closes: https://github.com/elixir-lang/elixir/issues/11808
=> Replace default sorter in Enum.sort_by/3 with :asc

lib/elixir/lib/partition_supervisor.ex
If the routing may change, we should **not** rely on that exact implementation
=> Update PartitionSupervisor implementation notes

lib/elixir/lib/partition_supervisor.ex, lib/elixir/test/elixir/partition_supervisor_test.exs
The PartitionSupervisor used a named ETS table to manage partitions, and as a result, it required the name to be an atom. However, only using atom names is limiting because it prevents the use of global or via tuples for registration.
This removes the `:named_table` option from a PartitionSupervisor's ETS table and instead stores a reference to the table with `:persistent_term`. Without the named table requirement, it's possible to register with any viable supervisor name.
Oban uses `Task.Supervisor` to track jobs, and it's not unusual to have hundreds of tasks running through one supervisor. I want to run some benchmarks to identify if that's, in fact, a bottleneck, and `PartitionedSupervisor` seemed like a perfect fit. But unfortunately, Oban uses a registry for all process names, and I …
=> Allow any valid name for PartitionSupervisor

lib/elixir/lib/macro.ex, lib/elixir/pages/unicode-syntax.md, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/code_formatter/general_test.exs, lib/elixir/test/elixir/kernel/parser_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs, lib/elixir/unicode/security.ex, lib/elixir/unicode/tokenizer.ex
Implement desired changes from #11753.
**Concretely, this is intended to address a regression in 1.14-dev where folks couldn't use the `µ` symbol in an atom or variable** like `µsecs`.
- The easily-typed 'Opt + m' shortcut on Mac produces the 'MICRO SIGN' unicode character, which is a Restricted codepoint according to the Unicode General Security Profile.
- The Greek 'lowercase mu', visually nearly identical, is Allowed -- but causes a Mixed Script error when combined with Latin-script letters in an identifier.
Now we support custom, elixir-specific normalizations, the first and only of which is the 'µ' mapping.
This also fixes 2 other normalization-related items:
**NFC normalization** -- non-NFC identifiers used to be an error, but now that's done automatically for us.
- This will affect …
=> nfc and additional normalizations for identifiers

lib/elixir/lib/code/fragment.ex
This PR adds missing options to Code.Fragment.surround_context spec and adds a note about another difference between `cursor_context` and `surround_context`
=> Improve Code.Fragment.surround_context spec

lib/elixir/lib/dynamic_supervisor.ex, lib/elixir/lib/supervisor.ex
Introduces t:Supervisor.sup_flags/0, and strealines the functions in
DynamicSupervisor and Supervisor that use Erlang typespecs.
=> Introduce t:Supervisor.sup_flags/0 + Streamline specs

lib/mix/lib/mix/dep/converger.ex, lib/mix/test/mix/dep/converger_test.exs, lib/mix/test/mix/dep_test.exs
So, I work on an umbrella project and every now and then I get this error about a cycle in my dependency graph. However, it wouldn't tell me which dependencies were causing the cycle. To solve this, I used a DFS to find the cycle and added the cyclic dependencies to the Mix.raise argument.
=> Mix.Dep.Converger now tells which deps formed a cycle

lib/elixir/lib/macro.ex
I realized that the example for `prewalk/2` is a bit confusing since some people might assume that `5 + 3 * 7` is transformed to `5 * 3 + 7` while in reality it's transformed into something like `5 * (3 + 7)` because the tree shape is not changed.
I think by showing the previous and new AST in the example can be more helpful for the developer.
I also added an example for `prewalk/3` and included some references to these functions in the `postwalk/2` and `postwalk/3`
=> Update prewalk and postwalk documentation

lib/elixir/src/elixir_compiler.erl
Docs will be compiled on the next pass.
=> Skip docs on secondary bootstrap

lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/test/ex_unit/case_test.exs
The argument passed to "use ExUnit.Case" must be a list of options,
but we were not enforcing this anywhere. This could result in
hard-to-debug errors.
With this commit, we'll now check said argument with Keyword.keyword?/1
and potentially raise an ArgumentError.
=> Validate argument passed to "use ExUnit.Case"

lib/mix/lib/mix/tasks/app.config.ex, lib/mix/lib/mix/tasks/compile.all.ex, lib/mix/lib/mix/tasks/compile.ex, lib/mix/lib/mix/tasks/eval.ex, lib/mix/lib/mix/tasks/run.ex, lib/mix/test/mix/tasks/eval_test.exs
The goal of this task is to have an equivalent for `bin/my_app eval` in releases, so developers can easily run commands that apply for both releases and regular code.
My biggest concern is if the differences between `mix eval` and `mix run` are clear in the docs, so feedback on this area is welcome!
=> Add mix eval

lib/elixir/lib/file.ex
Getting Dialyzer working on an existing project and have this issue.
> `delayed_write`
> The same as `{delayed_write, Size, Delay}` with reasonable default values for `Size` and `Delay` (roughly some 64 KB, 2 seconds).
-  https://www.erlang.org/doc/man/file.html#open-2
=> Add :delayed_write to t:File.stream_mode/0

lib/elixir/lib/kernel.ex
It took the inspiration from the Erlang docs for `tl/1`
<https://www.erlang.org/doc/man/erlang.html#tl-1>
=> Make documentation for hd/1 and tl/1 more beginner friendly

lib/elixir/lib/uri.ex
Stumbled across this while reading through the docs.
=> Fix `URI.new!/1` doc typo

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/issue.yml
I tried to port everything that we had in the previous issue template, plus a few additions such as adding an agreement check box and direct links to online communities to ask questions.
You can see how the form will look like:
- https://github.com/eksperimental/elixir/issues/new/choose
- https://github.com/eksperimental/elixir/issues/new?assignees=&labels=&template=issue.yml 
/cc @yordis
=> Improve Github issue template

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/issue.yml
Two new lines are interpreted as a paragraph break.
=> GitHub Template: Separate paragraphs when rendered

.github/workflows/ci.yml, .github/workflows/notify.yml, .github/workflows/release.yml
Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>
=> chore: Set permissions for GitHub actions

lib/elixir/lib/code/fragment.ex, lib/elixir/test/elixir/code_fragment_test.exs
=> Return keywords in Code.Fragment.surround_context

lib/elixir/pages/patterns-and-guards.md
Hi there! 👋
This commit adds a little documentation about being able to use `map.field` inside guards.
I couldn't find in the docs any mention, thought it would be good to write there it's a possibility, what do you think?
Thanks!
=> Add documentation about using guards for map fields

bin/elixir.bat
The *nix equivalent shell script echoes the full erl.exe path and args to stdout when the environment variable ELIXIR_CLI_DRY_RUN is set instead of executing it.
This patch adds this behaviour to the Windows bat file for consistency.
Note that whether or not the user has defined the useWerl env variable is also considered when deciding what to echo.
This patch is based on a conversation with @josevalim at ElixirConfEU 2022 with some minor tweaks :-)
=> Teach elixir.bat about ELIXIR_CLI_DRY_RUN

lib/elixir/lib/map_set.ex
I hate to bring this issue up again, but it's still causing friction, see [elixirforum thread](https://elixirforum.com/t/trying-to-decipher-a-the-pattern-can-never-match-the-type-dialyzer-error-message/48305)
I think with this change, the only disadvantage is that the field will need to be named `map` even if the internal implementation changes? I don't know if changing it to something more general would be considered a breaking change or not.
=> Change MapSet.t definition to make Dialyzer happy

lib/elixir/lib/module.ex, lib/elixir/test/elixir/module_test.exs
Now it returns an empty list, instead of nil.
Closes: https://github.com/elixir-lang/elixir/issues/11918
=> Replace misspelt :nillify_clauses option with :skip_clauses in Module.get_definition/3

lib/elixir/lib/gen_server.ex
The list of different invokation cases was separated from the sentence that introduces those cases.
=> Reorder format_status documentation

lib/elixir/lib/code/fragment.ex, lib/elixir/test/elixir/code_fragment_test.exs, lib/iex/lib/iex/autocomplete.ex
For simplicity I changed the returned aliases to contain `__MODULE__` string. This approach will not be optimal if we would like to handle other less trivial cases, e.g. `some_macro().Submodule` or `@my_attr.Submodule`. I'm not sure about the macro one but the attribute one would be useful.
Fixes #11875
=> Add support for __MODULE__ in Code.Fragment

lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/test/ex_unit/case_test.exs
See: https://github.com/elixir-lang/elixir/issues/11844
This commit changes ExUnit.Case to show a more specific error message
when the test name is too long that would cause SystemLimitError.
=> Display friendly error when test name is too long (#11844)

lib/elixir/lib/inspect/algebra.ex, lib/elixir/lib/module.ex
`Module.get_definition` returns `nil` when `:ets.lookup(set, {:def, {name, arity}})` returns `[]`
`Algebra.nest` reutrns `t` in
```
def nest(doc, 0, _mode) when is_doc(doc) do
doc
end
```
=> Add missing return types

lib/elixir/lib/code.ex
Without this patch the implementation will lead to errors in code that depends on a truthy result
```
if Code.delete_path(potentially_bad_path) do
do_sth()
end
```
=> Raise when inderlying erlang function doesn't return boolean

lib/ex_unit/lib/ex_unit/assertions.ex, lib/ex_unit/test/ex_unit/assertions_test.exs
#11885
The `refute` test case will cause a "warning: this check/guard will always yield the same result" warning, so didn't add that.
```
test "refute when operator be overrode" do
refute [_a] =~ [1, 2]
end
```
=> Fix ExUnit assertion when operator be overrode

lib/mix/lib/mix/tasks/release.ex
Based on the conversation here: https://groups.google.com/g/elixir-lang-core/c/LEzORYzFemA/m/AfjVbVlzBAAJ?utm_medium=email&utm_source=footer
There didn't seem to be any tests around this option based on a quick search for the option.
=> Let `:runtime_config_path` accept false to skip the runtime.exs

lib/mix/lib/mix/tasks/format.ex
Hey folks! 👋 
There is a duplicated call for `Code.format_string!/2` in the Mix.Format task. This is a somewhat silly change - but from a local benchmark, **it cuts uncached `Mix.Format` execution time by half in relation to the main branch!** 🏃 
Happily, the duplicated call is only present on the main branch - it was introduced after the latest tag (1.13.4). 
You may need to compile Elixir locally to run the benchmark using the development Elixir version. [Here are some instructions on how to do it](https://github.com/antedeguemon/format_benchmark/blob/master/README.md). Note that running the benchmark using Elixir 1.13.4 will likely yield equal results for both scenarios.
[(Full benchmark experiments are available in this Github repository. An experiment for _formating from stdin_ is …
=> Removes duplicated formatter call

lib/mix/lib/mix/tasks/xref.ex, lib/mix/test/mix/tasks/xref_test.exs
Previously this would be silently ignored
=> Make `mix xref graph --exclude` raise error for files that are not found

lib/elixir/lib/io.ex
`:all` is still an accepted value, so it makes sense to have it in the `@spec` or Dialyzer fails on this function. I also updated the docs to mention the deprecation so that folks don't have to hunt it down across Elixir versions 😉
=> Fix spec and docs for IO.binread/2

lib/elixir/lib/string.ex
I noticed that the documentation for string omits three useful escapes which are supported. I've put these in ASCII order, as the other escapes are
=> Include backslash, space, and null byte in string escape documentation

lib/elixir/lib/map.ex
The map docs state that the `%{map | ...}` update syntax is for atom keys only, however it also works for any term with `=>` as far as I understand, so I updated the docs accordingly.
=> Map docs: update syntax is not for atom keys only

lib/elixir/lib/calendar/date_range.ex, lib/iex/test/iex/helpers_test.exs
first_in_iso_days and last_in_iso_days are both integers. This commit
updates the Date.Range typespec to reflect that.
Fixes https://github.com/elixir-lang/elixir/issues/11947.
=> Fix Date.Range.first_in_iso_days/last_in_iso_days typespec

lib/elixir/lib/kernel.ex
=> Document that `Kernel.match?/2` cannot take a variable pattern

lib/elixir/lib/map_set.ex, lib/elixir/test/elixir/map_set_test.exs
Hello there,
Since we have implementations for [union](https://hexdocs.pm/elixir/1.13.4/MapSet.html#union/2), [difference](https://hexdocs.pm/elixir/1.13.4/MapSet.html#difference/2) and [intersection](https://hexdocs.pm/elixir/1.13.4/MapSet.html#intersection/2) I believe it makes sense to have one for `disjoint`.
I saw myself writing this function multiple times and I thought it could be useful to more people.
I'm using the high level `difference` twice followed by a call to `union`. I noticed that most of the functions use the inner `map` directly. Please let me know if you prefer a different implementation.
Thank you for creating and maintaining Elixir! :bouquet:
=> Add disjoint function to MapSet

lib/mix/lib/mix/tasks/xref.ex, lib/mix/test/mix/tasks/xref_test.exs
`mix xref graph --label compile-connected` would benefit from a way to deal with an acceptable list of core dependencies that should be excluded, provided they don't have any outside dependencies.
I am proposing a `--trim` API to merge these core paths and remove the resulting group after verifying it has no dependency. The command `--merge` exposes the merging part without the deletion.
We have a CI script that insures we don't introduce transitive compile-time dependencies, using `--label compile-connected` and `--fail-above 0`.
One complexity is that we have a core of compile-time dependencies that are in more than a single file. In particular, in the same way that we have `use BobbyWeb, :something` in most of the web layer, we have `use Bobby` used in the app layer, and web layer via …
=> `mix xref graph --group`

lib/elixir/lib/kernel/parallel_compiler.ex, lib/mix/lib/mix/task.compiler.ex
1. mix compiler actually returns chardata (or iodata) in message
```
%Mix.Task.Compiler.Diagnostic{
file: "/Users/lukaszsamson/bug_repro/phx_error_path_umbr_umbrella/apps/phx_error_path_umbr_web/lib/phx_error_path_umbr_web/views/page_view.ex",
severity: :warning,
message: ["IO.π/0", " is undefined or private", ""],
position: 3,
compiler_name: "Elixir",
details: nil
}
```
2. `{0, column >= 0}` is not a location result from ParallelCompiler.
BTW shouldn't `Kernel.ParallelCompiler.locationa type allow ranges as in case of `Mix.Task.Compiler.Diagnostic.position`?
=> Improve diagnostic and compile typespec

lib/elixir/lib/dynamic_supervisor.ex
Tries to improve (on top of the improvement) the wording on the docs to distinguish that `DynamicSupervisor` (in contrast to `Supervisor`) can **only** start children dynamically. I think this distinction is important because `Supervisor` can also start children "dynamically" (although the initialization requirements are different). 
PS.: See whole discussion [here](https://elixirforum.com/t/difference-between-supervisors-and-dynamicsupervisors-what-am-i-missing/48821/5?u=thiagomajesk).
=> Make wording on the DynSup docs more direct

lib/iex/lib/iex/helpers.ex, lib/iex/test/iex/helpers_test.exs
Close #11968
The problem was that `print_table` uses a [max_length](https://github.com/elixir-lang/elixir/blob/main/lib/iex/lib/iex/helpers.ex#L790-L791=) in which case `String.pad_trailing` would not be adding any space.
=> Fix exports/1 in IEx for long fun names

lib/elixir/lib/supervisor.ex
Follow up on the improvements of https://github.com/elixir-lang/elixir/pull/11970. WDYT?
The idea is to make clear that `DynamicSupervisor` is an efficient way of starting children dynamically (and not the only way).
PS.: @josevalim I wonder if this distinction should be made in the guides as well, what is your opinion about it? I remember reading it and being confused about this in particular (like I mentioned in the forums before).
=> Update DynSup reference in Supervisor docs

lib/elixir/lib/file.ex
Hello,
I noticed that some of the functions in the `File` module could accept atom arguments such as `nil` as their paths and would actually succeed.
```
iex(1)> File.copy("mix.exs", nil)
{:ok, 2281}
iex(2)> File.exists?("nil")
true
iex(3)> File.rename(nil, true)
:ok
```
This is incoherent with the rest of the module which fails early on invalid data (typically using `IO.chardata_to_string/1`), doesn't match the typespecs and could silently provoke unexpected bugs.
Note: It is also the case for `File.write!/2` in 1.13, but this has already been fixed in https://github.com/elixir-lang/elixir/pull/11555.
=> Have File.rename/2 and File.copy/2 check path types

lib/elixir/lib/enum.ex
Add an another example to show that the `joiner` is inserted between elements of the highest level of the `enumerable`, whereas the nested elements are simply stuck together.
=> Add example with nested arrays to Enum.join/2

lib/elixir/lib/enum.ex, lib/elixir/lib/stream.ex
Add an example showing that a Stream can also be passed as `leftover`, because Enum.take/2 is later called inside those functions.
Indeed, both functions use Stream.Reducers.chunk_every/5 which calls Enum.take/2.
=> Add example to Enum.chunk_every/4 and Stream.chunk_every/4

lib/elixir/lib/inspect.ex, lib/elixir/lib/regex.ex, lib/elixir/test/elixir/inspect_test.exs
Hi,
This is a proposal to improve inspection of `Regex` built from an atom list.
```
iex(1)> Regex.compile!("foo", [:caseless])
~r/foo/
```
This issue was mentioned [in this forum ](https://elixirforum.com/t/is-it-normal-that-regex-compile-2-does-not-print-regex-modifiers-when-atoms-are-passed-in-options/48992).
Feel free to close if we want to keep it this way or follow a different approach 🙂
=> Show list opts when inspecting Regex

lib/elixir/lib/regex.ex
- Add `:` to modifiers to show that they are atoms
- Add examples to Regex.compile/2 where modifiers are given
Related to #11991
=> Improve documentation and examples about modifiers

lib/elixir/lib/regex.ex, lib/elixir/test/elixir/inspect_test.exs, lib/elixir/test/elixir/regex_test.exs
Adding a bit of sustaining updates to the PR #11991:
* Updated the type spec on `Regex.opts` to indicate options can be `[term]`, ie: a list of atoms
* Added a test to verify options' type preservation from `Regex.opts`
* Added a test to verify options' type preservation from `inspect`
Test execution evidence:
```
%make test_stdlib
==> elixir (ex_unit)
Excluding tags: [windows: true]
. . .
Finished in 17.7 seconds (7.5s on load, 4.9s async, 5.2s sync)
1881 doctests, 4080 tests, 0 failures, 13 excluded
```
=> [SUSTAIN] Updating type spec/tests for recent PR to Regex options

lib/elixir/lib/regex.ex
This is a follow-up for #11991.
I realized thanks to https://github.com/elixir-lang/elixir/pull/11995 that the `@type` `list(atom)` was inconsistent with other functions. Besides, it is technically incorrect, since `Regex.compile!("foo", [newline: :cr])` works (despite being marked as non-available in the [doc](https://hexdocs.pm/elixir/master/Regex.html#module-modifiers)).
Also updated the docs to add one more example and a more accurate description.
=> Fix @type for Regex, add doctest example

lib/elixir/lib/enum.ex
In the doc:
https://github.com/elixir-lang/elixir/blob/fb729784e5504f499b0179c4f154e73ea2a6f216/lib/elixir/lib/enum.ex#L206
Enum module is described as:
"Provides a set of algorithms to work with enumerables."
I'll suggest that a clearer description would be :
"Provides a set of functions to work with enumerables."
=> A better description for Enum module

Makefile
This is particularly useful on Windows where make could be under for example:
C:\Program Files (x86)\GnuWin32\bin\make.exe
=> Escape `$(MAKE)` path

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel_test.exs
=> Add Kernel.dbg/0 which debugs binding/0

lib/elixir/lib/exception.ex, lib/elixir/src/elixir_erl_pass.erl, lib/elixir/src/elixir_erl_try.erl, lib/elixir/test/elixir/exception_test.exs, lib/elixir/test/elixir/kernel/errors_test.exs
```elixir
iex(3)> nil.id
** (UndefinedFunctionError) function nil.id/0 is undefined. If you are using the dot syntax, such as map.field or module.function(), make sure the left side of the dot is an atom or a map
nil.id()
```
The message looks very obvious to an Elixir dev used to it, but it could quite a lot to unpack and some prior knowledge is assumed:
- `nil` is an atom
- modules are atoms, so `nil` gets interpreted as a module
- elixir doesn't distinguish between `user.id` and `user.id()` because of how its AST works
Besides, this message might be slightly sub-optimal:
- AFAIK `nil`, `true` and `false` are not actually allowed module names, despite being atoms
- "If you are using the dot syntax" -> this comes from `apply/3`, but in this case we know the dot syntax was used
- the …
=> Proposal: Improve error messages for dot syntax

lib/elixir/lib/file.ex, lib/elixir/test/elixir/file_test.exs, lib/mix/lib/mix/release.ex, lib/mix/lib/mix/utils.ex
=> Add dereference_symlinks to File.cp*

lib/elixir/lib/dynamic_supervisor.ex, lib/elixir/test/elixir/dynamic_supervisor_test.exs, lib/elixir/test/elixir/supervisor_test.exs
It would not accept 0 as a valid shutdown value.
It only happened in DynamicSupervisor, but tests are added for both DynamicSupervisor and Supervisor modules.
=> Fix bug DynamicSupervisor child_spec validation

lib/elixir/lib/map_set.ex, lib/elixir/test/elixir/map_set_test.exs
We can do this now that Elixir requires OTP 24+, since the new :sets
API is also built on top of maps.
Part of https://github.com/elixir-lang/elixir/issues/10433.
=> Use :sets v2 under the hood in MapSet

lib/logger/lib/logger.ex, lib/logger/lib/logger/backends/console.ex
This includes two changes:
- `Logger.Backends.Console` did refer to a `Metadata` section without a hint of it being in `Logger`
- `Logger` still had an example of configuring `Logger.Backends.Console`. I've removed that last one, given I've seen many people in the past trying to configure `Logger` with `config :logger, :console, [logger_options]` and wonder why they don't apply.
=> Improve logger documentation

.github/workflows/ci.yml
* Use `erlef/setup-beam` for installing Erlang instead of installing via chocolatey. So we're using the same tool like release pipeline does.
* Use `Remove-Item` instead of `del`. 
* Add OTP 25 to the matrix.
=> Use setup-beam on Windows platform

lib/mix/lib/mix/tasks/test.ex
Fixes a typo in the mix test documentation to change "past" to "paste".
=> Update test.ex to fix documentation typo

lib/elixir/src/elixir_expand.erl, lib/elixir/src/elixir_fn.erl, lib/elixir/test/elixir/kernel/expansion_test.exs, lib/elixir/test/elixir/kernel/tracers_test.exs
While this PR fixes the bug, I'm not really sure about my approach.
Is merging the capture and dot meta keywords acceptable? Or should I explicitly pass the dot meta to trace emit? 
Do we want `capture_meta` emitted on tracer?
Is it OK that `:no_parens` meta gets passed when expanding macros (see comment in expansion_test.exs)
Fixes https://github.com/elixir-lang/elixir/issues/12023
=> Emit consistent position meta on fn capture traces

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
Closes #12039.
We should probably backport this to 1.14 as well.
=> Fix bug in Enum.drop/2

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
I found one last bug in `Enum.slice` with stepped ranges on streams, which might be including an extra element:
```elixir
iex(3)>  1..10 |> Stream.take(10) |> Enum.slice(2..5//2)
[3, 5, 6]
iex(4)>  1..10 |> Enum.take(10) |> Enum.slice(2..5//2)
[3, 5]
```
=> Fix bug: Enum.slice selecting extra element

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel_test.exs
`binary_slice/2` has some inconsistencies with `Enum.slice/2` and could crash in some cases:
```elixir
iex> binary_slice "abc", -1..0
"b"
iex> Enum.slice 'abc', -1..0
[]
iex> binary_slice "abcdef", 1..3//2
"b"
iex> Enum.slice 'abcdef', 1..3//2
'bd'
iex> binary_slice "ab", -5..-5
* 3rd argument: out of range
:erlang.binary_part("ab", 0, -2)
(elixir 1.15.0-dev) lib/kernel.ex:4666: Kernel.binary_slice/2
```
Note: most of the changes are based on the `slice_range` private function in the Kernel module, I tried to keep the consistency in style and variable naming.
Note 2: this new implementation passes the following prop-based test:
```elixir
check all(
binary <- binary(),
start <- integer(),
stop <- integer(),
step <- …
```
=> Fix bugs in binary_slice/2

lib/elixir/lib/string.ex
I have the following code
```elixir
@spec maybe_compile(map()) :: map()
defp maybe_compile(%{operator: operator, value: %Regex{}} = condition)
when operator == "regex" or operator == "match" do
condition
end
defp maybe_compile(%{operator: operator} = condition)
when operator == "regex" or operator == "match" do
with true <- String.valid?(condition.value),
{:ok, compiled_value} <- Regex.compile(condition.value) do
%{condition | value: compiled_value}
else
false -> raise "\"condition\" value was invalid regex #{inspect(condition.value)}"
{:error, reason} -> raise "\"condition\" value was invalid regex #{inspect(reason)}"
end
end
```
dialyzer thinks the false can never happen in my code, because String.valid? claims it only takes in Strings and not any type.
=> String.valid? takes in an any type and returns a boolean

lib/elixir/lib/enum.ex
Add missing `@spec` for `Enum.slide/3`.
=> Add spec for Enum.slide/3

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
The first bug can happen on empty lists:
```elixir
iex> Enum.slide([], 1, 2)
** (FunctionClauseError) no function clause matching in Enum.slide_list_start/4
The following arguments were given to Enum.slide_list_start/4:
[]
1
2
2
Attempted function clauses (showing 2 out of 2):
defp slide_list_start([h | t], start, middle, last) when start > 0 and start <= middle and middle <= last
defp slide_list_start(list, 0, middle, last)
(elixir 1.13.4) lib/enum.ex:2665: Enum.slide_list_start/4
```
The second bug is on a weird edge case because an assumed invariant (`start <= stop`) isn't actually checked (but only happens for some precise values of the insertion index):
```
iex> Enum.slide([1, 2, 3, 4], 2..1//1, -3)
** (FunctionClauseError) no function clause matching in Enum.slide_list_start/4
The …
```
=> Fixing edge cases in Enum.slide/3

lib/mix/lib/mix/tasks/format.ex, lib/mix/test/mix/tasks/format_test.exs
Hi!
While working on a formatter plugin I noticed that formatting only allowed one plugin per file extension type. 
So if you had two plugins targeting `.heex` files, only one would succeed - the first one defined within the `plugins: []` array of `.formatter.exs`.
~~This wasn't the case for sigils though~~ https://github.com/elixir-lang/elixir/blob/27857609b0a922c5ee138e4d2609a5b189410bc8/lib/mix/lib/mix/tasks/format.ex#L298-L301
~~Seeing as multiple formatters per sigil was already supported, I thought the same could be done for formats based on file extension.~~
One thing I am not certain on is backward compatibility - if these functions have to be newly defined or not. 
Let me know what you think :)
It seems I wrong on the multiple formatters for sigils! Vaguely recall it working …
=> Allow multiple formatters per file extension and sigil

lib/elixir/src/elixir_bitstring.erl, lib/elixir/src/elixir_erl_pass.erl, lib/elixir/test/elixir/kernel/expansion_test.exs
Use `{modifier, meta, nil}` instead of `{modifier, meta, []}` for bitstring modifier inner AST for consistency.
=> Replace inner AST for bitstring modifiers

lib/elixir/lib/task.ex
I wonder if this part in the line right below
> that gives you explicit control on how to handle the results
should be changed with `gives -> give` as well?
=> typo: improves -> improve

.github/workflows/ci.yml, .github/workflows/release.yml
The ubuntu-18.04 nows deprecated today [1]. This changes start moving it
to version 20.04 instead.
[1] https://github.com/actions/virtual-environments/issues/6002.
=> Bump ubuntu to 20.04

lib/elixir/lib/code/fragment.ex, lib/elixir/lib/macro.ex
Found from working #12038. Fixes 2 ex_doc warning. Here is build log https://github.com/wingyplus/elixir/runs/7727863757?check_suite_focus=true#step:9:111
=> Fix unclosed backquotes in Code.Fragment and Macro

lib/ex_unit/lib/ex_unit/capture_log.ex
The fact that `capture_log([level: :info])` doesn't capture `Logger.info` calls if `Logger.level/0`is `:notice` or higher caught me off guard, so I figured it'd be good to mention here that the `Logger` `:level` config still applies.
This note is copied directly from `Logger.Backends.Console` since that's
where this behavior originates.
=> Clarify CaptureLog level vs Logger level

lib/mix/lib/mix.ex, lib/mix/lib/mix/dep/lock.ex, lib/mix/test/mix/tasks/compile.elixir_test.exs, lib/mix/test/mix/tasks/deps.git_test.exs, lib/mix/test/mix_test.exs, lib/mix/test/test_helper.exs
Closes #12044
This is especially useful to test an existing project along with its configuration and dependency resolution. Excerpt from the docs:
```elixir
Mix.install(
[
{:hexpm, path: "/tmp/hexpm", env: :dev},
],
config_path: "/tmp/hexpm/config/config.exs",
lockfile: "/tmp/hexpm/mix.lock"
)
Hexpm.Repo.query!("SELECT COUNT(1) from packages")
#=> ...
```
=> Mix.install: Add :config_path and :lockfile options

lib/ex_unit/lib/ex_unit/diff.ex, lib/ex_unit/test/ex_unit/diff_test.exs
Properly handle diffs of charlists using the `~c` sigil notation:
Relates to https://github.com/elixir-lang/elixir/issues/12065
=> Fix ExUnit.Diff handling of charlists

lib/eex/lib/eex/compiler.ex, lib/elixir/lib/function.ex, lib/elixir/lib/inspect.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/list.ex, lib/elixir/lib/macro.ex, lib/elixir/lib/string.ex, lib/elixir/test/elixir/inspect_test.exs, lib/elixir/test/elixir/macro_test.exs, lib/mix/lib/mix/tasks/compile.erlang.ex, lib/mix/test/mix/tasks/compile.erlang_test.exs
Inspect charlists as `~c` sigils.
Also updates doctests to use the correct syntax.
Relates to https://github.com/elixir-lang/elixir/issues/12065
=> Inspect charlists as ~c sigils

lib/iex/lib/iex/info.ex
Updates `IEx.Info` which was still mentioning single quotes:
Relates to #12065
=> Update IEx.Info for charlists

lib/mix/lib/mix/shell/process.ex
The docs included a non existing function `Mix.shell().prompt?/1` which has been corrected.
The examples are also not clear enough and doesn't make it 'obvious' that this should be run in the test files
=> correct typo and add more info on shell process docs

lib/elixir/lib/dynamic_supervisor.ex, lib/elixir/lib/partition_supervisor.ex, lib/elixir/lib/supervisor.ex, lib/elixir/test/elixir/dynamic_supervisor_test.exs, lib/elixir/test/elixir/partition_supervisor_test.exs, lib/elixir/test/elixir/supervisor_test.exs
This adds support for [Automatic Shutdown](https://www.erlang.org/doc/design_principles/sup_princ.html#automatic-shutdown) (EEP 56) to Supervisor. This functionality was added in Erlang R24 and leaks processes with older versions so should require 1.15. I believe it should have been listed in #10433 as well.
I tried to summarize the docs in a way that Elixir users wouldn't need to cross reference the OTP ones to use the feature, other than that it's mostly passing through options to `:supervisor` and spec/doc updates.
=> Add support for automatic shutdown to Supervisor

lib/mix/lib/mix/dep/converger.ex, lib/mix/lib/mix/dep/loader.ex, lib/mix/lib/mix/dep/umbrella.ex, lib/mix/lib/mix/hex.ex, lib/mix/lib/mix/tasks/deps.compile.ex
The user is already fetching external packages,
so it is ok for us to install those too and improve
the user experience.
Other commands such as `mix deps.compile` will still
prompt.
Closes #12086.
=> Automatically install Hex and Rebar on deps.get/deps.update

lib/elixir/lib/float.ex, lib/elixir/test/elixir/float_test.exs
When floats are expressed in scientific notation,
`:erlang.binary_to_float/1` can raise an `ArgumentError` if the `e` exponent
is too big. For example, `1.0e400`. Because of this, we rescue the
`ArgumentError` and return `:error`.
=> Don't raise on overflowing floats in Float.parse/1

lib/mix/lib/mix/tasks/format.ex
Low-hanging fruit but help avoid confusion 🙈 
Documentation for `mix format` points that when `-` is passed, _output_ is read from stdin instead of _input_.
=> Better `mix format` doc wording

lib/elixir/pages/patterns-and-guards.md
```diff
- A binary in a pattern can match multiple segments at the same
+ A binary in a pattern can match multiple segments at the same time
```
=> Add missing word in docs

lib/elixir/lib/keyword.ex, lib/elixir/lib/map.ex, lib/elixir/lib/map_set.ex, lib/elixir/test/elixir/keyword_test.exs, lib/elixir/test/elixir/map_set_test.exs, lib/elixir/test/elixir/map_test.exs
As per [this discussion](https://groups.google.com/g/elixir-lang-core/c/2OEFTGEHPMM) in mailing group - here is a pr that adds implementations of `split_with/2` to the Map and Keyword modules
=> Add Map.split_with/2 and Keyword.split_with/2

lib/elixir/lib/keyword.ex
Alternatively, maybe introduce a private `do_split_with` that doesn't have a spec?
=> Do not use Keyword.split_with/2 on a list of atoms

lib/elixir/lib/code.ex, lib/elixir/lib/code/formatter.ex, lib/elixir/lib/inspect/algebra.ex, lib/elixir/lib/macro.ex, lib/elixir/src/elixir.app.src, lib/elixir/test/elixir/code_normalizer/quoted_ast_test.exs, lib/elixir/test/elixir/kernel_test.exs
Add a `syntax_colors to `Code.quoted_to_algebra/2` and have `dbg/1` pass it if ANSI colors are enabled.
Close #12101.
=> Handle syntax_colors in quoted_to_algebra and dbg

lib/elixir/lib/code.ex, lib/elixir/lib/exception.ex, lib/elixir/lib/inspect.ex, lib/elixir/lib/inspect/algebra.ex, lib/elixir/lib/keyword.ex, lib/elixir/lib/protocol.ex, lib/elixir/lib/range.ex, lib/elixir/pages/unicode-syntax.md, lib/elixir/src/elixir_bitstring.erl, lib/elixir/test/elixir/exception_test.exs, lib/iex/lib/iex.ex, lib/mix/lib/mix/tasks/compile.elixir.ex, man/common
While going through the "Getting started" documentation I noticed a missing comma in the nice hint that a macro is defined.
> iex> Integer.is_odd(3)
> ** (UndefinedFunctionError) function Integer.is_odd/1 is undefined or private. However there is a macro with the same name and arity. Be sure to require Integer if you intend to invoke this macro
A simple search for "however " in the repository yielded a few cases of this simple grammatical mistake. I've added commas and semicolons to these where appropriate (which is most uses).
Note that this was not a blind find/replace. For example, "however" does not need commas when used as an adverb:
>   `NaiveDateTime.to_iso8601/2` and `DateTime.to_iso8601/2` allow you to produce
>    either basic or extended formatted strings, and …
=> Add commas to bare usage of "however" where appropriate

lib/mix/lib/mix/tasks/xref.ex, lib/mix/test/mix/tasks/xref_test.exs
When using this feature, first thing I wanted to write was
```
GROUP=\
lib/example.ex,\
[...]
lib/other_example.ex,\
mix xref graph --group=$GROUP ...
```
=> Allow trailing comma in `xref group --group` parameter

lib/elixir/lib/kernel.ex
Improve docs for guards for the following cases: 
- adds examples for `is_map_key` guard. I was looking for something like that but because it is called `is_map_key` instead of `has_map_key` I just figured out it was what I wanted because I found it in some random article (but not in the docs). Examples could have helped here.
- exceptions for `hd/1` and `tl/1` were not highlighted because of the precedence of "#=>" before the exceptions themselves 
- `++/2` is the right associative (found that in erlang docs), added an example similar to what we have for `--/2`.
---
Playing with these `is_map_key/2` I also had another interesting discovery. With a `MapSet` it does not raise an exception. While I do understand it happens because MapSets are implemented over  `Map` for compatibility …
=> improve misc of docs for guards 

lib/ex_unit/lib/ex_unit/callbacks.ex
It uses `def clean_up_tmp_directory` in the docs when defining the setup callback, giving the impression that this function has to be public, when it is not the case.
This commits changes it to `defp`
=> ExUnit: define setup callback as private function in docs

lib/elixir/lib/supervisor.ex
I think I have found a typo in the Supervisor doc.
=> Fix a typo in Supervisor doc

lib/iex/lib/iex/server.ex, lib/iex/test/iex/helpers_test.exs, lib/iex/test/iex/interaction_test.exs, lib/iex/test/test_helper.exs
This fixes a bug where multiline paste stopped working whenever the input reader was killed. Instead we use the IO protocol directly.
However, in order to use the IO protocol, we need to write the prompt instead of sending it as a prompt, which requires test changes.
Closes #12137.
=> Do not spawn a process to read IO

lib/mix/lib/mix/tasks/release.ex
Since Elixir 1.11 the `reboot_system_after_config` option is opt-in when using default runtime config (bc5bb85). I've traced through `Config.Provider` and `Config.Reader` and set my release directories to be read-only to confirm that I'm able to start an application without writing runtime configuration to a temporary file with Elixir 1.13.4.
Please feel free to request alternative wording or styling if preferred!
=> Update docs for release runtime configuration without reboot

lib/elixir/lib/calendar/datetime.ex, lib/elixir/test/elixir/calendar/datetime_test.exs
Got an argument error that I think could be more helpful:
```sh
** (ArgumentError) unsupported time unit. Expected :second, :millisecond, :microsecond, :nanosecond, or a positive integer, got "day"
code: DateTime.add(DateTime.utc_now(), -1, "day")
```
I expected to have all the supported time unit in the error. Since the error comes from `System.convert_time_unit`, I simply added a conditional that raise a new error.
=> Add complete list of time units on DateTime.add/3 argument error

lib/elixir/lib/code/normalizer.ex, lib/elixir/test/elixir/code_normalizer/quoted_ast_test.exs
Closes #12162
The problem is that `:erlang.binary_to_atom(<<...>>), :utf8)` is an edge case algebra-wise (https://github.com/elixir-lang/elixir/blob/main/lib/elixir/lib/code/normalizer.ex#L87) because it represents an atom interpolation:
```elixir
iex(1)> Code.quoted_to_algebra(quote do: :erlang.binary_to_atom(<<>>, :utf8))
{:doc_group, {:doc_cons, ":\"", "\""}, :self}
```
The formatter makes the distinction where the string isn't actually interpolated [here](https://github.com/elixir-lang/elixir/blob/main/lib/elixir/lib/code/formatter.ex#L343), but the normalizer emitted a non-normalized `:utf8` literal which breaks the formatter.
=> Fix formatter edge case on :erlang.binary_to_atom/2

lib/elixir/lib/range.ex
Don't know if my understanding is wrong or not, that if last greater or equal to first will be an increasing range with step of 1, vice versa
=> fix range first and last description in module doc

lib/elixir/src/elixir_erl_for.erl, lib/elixir/src/elixir_erl_pass.erl, lib/elixir/src/elixir_expand.erl, lib/elixir/test/elixir/kernel/comprehension_test.exs, lib/elixir/test/elixir/kernel/expansion_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs
Close #12107
Hi, this is a suggestion how we could fix the issue:
- if `uniq` is true but `into` is false, it is basically the same as if uniq wasn't here, so we can ignore `uniq` (building a map with `nil` keys etc... don't make much sense)
- this is an incorrect use of `uniq`, so we should probably better add a warning that just ignore it silently
=> Handle unused :uniq comprehensions

lib/logger/lib/logger/translator.ex
While implementing a custom `Logger.Translator`, I discovered that there weren't any types specified. This could help others in a similar situation.
=> Add typespec for Logger.Translator.translate/4

lib/elixir/lib/uri.ex, lib/elixir/test/elixir/uri_test.exs
Fixes #12175
I've added tests for all the examples from the RFC. That test might need a bit of cosmetics,
but I think it's a good idea keeping them in such a way that the original test material is
immediately recognizable.
I've struggled quite a bit with the fix. I started to make progress when I decided to discard the existing implementation and roll my own...
I have the gut feeling there might still be edge cases though. But, at least all the URI tests are green now.
=> Fix uri merge

lib/ex_unit/lib/ex_unit/assertions.ex
adding an example of how to pass arguments to the function you want to assert raises an exception
=> add example to ExUnit.Assertions.assert_raise/2 doc

lib/elixir/lib/calendar/time.ex
=> Fix Time.add/3 documentation

lib/elixir/lib/regex.ex
Update documentation of `Regex.replace/4`.
- Try to improve the explanation of how works specific captures when a match occurs, including the necessary syntax on regex argument (brackets) to generate the capture.  
- Adding another example of how works capture in a function.
=> Improve replace documentation of module regex

lib/mix/lib/mix.ex, lib/mix/lib/mix/cli.ex, lib/mix/lib/mix/project.ex, lib/mix/lib/mix/project_stack.ex, lib/mix/lib/mix/task.ex, lib/mix/lib/mix/tasks/help.ex, lib/mix/lib/mix/tasks/test.coverage.ex, lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/cli_test.exs, lib/mix/test/mix/project_test.exs, lib/mix/test/mix/task_test.exs
The goal is to unify all CLI defaults in a single
in a way where we can load said configuration
before we load the project itself.
See the "CLI configuration" section in Mix.Project for more information.
=> Support "def cli" in Mix.Project

lib/ex_unit/lib/ex_unit.ex, lib/ex_unit/lib/ex_unit/cli_formatter.ex
So, I use a very dark gray terminal background, and the location part of the ex_unit output is not really readable:
I had a look at cli_formatter, and it seems the colors are hard coded. So I put together a trivial change to allow them all to be configured instead.
However, I couldn't work out how to test this: when I try to `make compile` I get:
~~~
20∙51∙02≻ make compile
==> unicode (compile)
20:51:06.671 [error] GenServer :elixir_code_server terminating
** (stop) {:badcast, {:reset_warnings, #PID<0.93.0>}}
Last message: {:"$gen_cast", {:reset_warnings, #PID<0.93.0>}}
State: {:elixir_code_server, %{}, {[], [], 0}, %{}}
== Compilation error in file lib/elixir/unicode/unicode.ex ==
** (UndefinedFunctionError) function Kernel.LexicalTracker.import_dispatch/4 is undefined or private. Did …
=> start to add config to ex_unit colors

lib/elixir/src/elixir_expand.erl
I was [playing around with `[foo: 1 | tail]`](https://elixirforum.com/t/syntax-to-augment-keyword/51305) and noticed that the error message for `|` is not quite accurate
=> Add precision to error message

lib/elixir/lib/calendar/datetime.ex
We were only spec'ing `DateTime.from_iso8601/3`.
=> Add spec for DateTime.from_iso8601/2

lib/elixir/src/elixir_erl_for.erl
Hello,
I just noticed that filters in `for` are using a multiple guard (`when x == false when x == nil`) while `if` is using `orelese` (`when x === false or x === nil`).
Out of curiosity, I [benchmarked the difference](https://github.com/sabiwara/elixir_benches/commit/ab7833581b957be19afa97ead11d909f01aa4f37) without expecting any, but it turns out there is a reproducible overhead of multiple guards over a plain `orelse`.
Even if it isn't a big gain, it is basically a free one so I figured I'd open a PR. It also has the merit of being consistent with truthiness implementation elsewhere. WDYT?
=> Use orelse in for guard

lib/eex/lib/eex/compiler.ex, lib/eex/test/eex/tokenizer_test.exs, lib/eex/test/eex_test.exs
Also fixes the error message to show at the line the comment was created.
=> Add snippet when <%-- is not closed

lib/elixir/src/elixir_clauses.erl, lib/elixir/src/elixir_expand.erl, lib/elixir/src/elixir_utils.erl, lib/elixir/test/elixir/kernel/expansion_test.exs
Close #12222
~I tried to add a test, but even when trying to use `defmodule` within `Code.eval_quoted`, it still raises the regular compile error before type checking. Maybe it is due to how the parallel checker works?~
Changed approach: make sure the proper `CompileError` gets raised when passing extra options to the block syntax, using the same way of checking options for both `with` and `for`.
=> Handle options consistently in with/1 and for/1

lib/elixir/lib/calendar/date.ex, lib/elixir/lib/calendar/datetime.ex, lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/lib/calendar/time.ex
Hi,
I thought maybe doctests could be helpful to visualize how the recently added `before?/2` and `after?/2` functions work.
Maybe we should also explain something like
> `before?` can also be used to compare (a DateTime without the time zone information|across more
complex calendar types by considering only the time fields|...), see `compare/2` for more information.
But I wasn't sure if we should include doctests for these too or if I should include them in this PR. WDYT?
=> Add doctests to before?/2 and after?/2 functions

lib/elixir/lib/path.ex
Under the hood [`Path.wildcard/2` uses `:filelib.wildcard/2`](https://github.com/elixir-lang/elixir/blob/c407a1e2ad824453335909ce8885c807f1d96953/lib/elixir/lib/path.ex#L674), which is hinted by copied documentation (from [here](https://github.com/erlang/otp/blob/6664a6f85d06b2b7d09067c19c67cab2c48b4729/lib/stdlib/doc/src/filelib.xml#L235-L237) to [here](https://github.com/elixir-lang/elixir/blob/c407a1e2ad824453335909ce8885c807f1d96953/lib/elixir/lib/path.ex#L637-L639)). 
However, the escaping part of the doc is missing, which makes one dive into the code. 
This PR copies this part as well.
=> Document char escaping for Path.wildcard/2

.github/workflows/release.yml, .github/workflows/release_pre_built/action.yml
- Release pre built composite action
- Use new composite action from release workflow
According to #12038, we would like to automate HexDocs publishing into s3 in the same way that Bob does. 
After some research within [bob repository](https://github.com/hexpm/bob/blob/main/priv/scripts/elixir/elixir.sh#L121), I could find that each of the elixir applications generated documentation with ExDoc is uploaded via aws cli following a `${app}-${version}` pattern.
This PR extracts a composite action that:
- Builds elixir release
- ExDoc
- generates docs
This PR updates the current release workflow so it uses this composite action but does not upload anything for the time being. This ensures that the current releasing workflow won't be affected. This is just a pre-face of two more PRs that …
=> release pre built composite action

.github/workflows/publish_docs.yaml
Now that https://github.com/elixir-lang/elixir/pull/12234 is merged, we can use the `release_pre_built` composite action to upload *HexDocs* to `S3`.  This is the first part of #12038.  The workflow will be triggered when a push is done in `main` or `v*.*` branches. The upload is done in the same way that bob does, check [here](https://github.com/hexpm/bob/blob/main/priv/scripts/elixir/elixir.sh#L122). 
When `make Docs.zip` step is performed within the composite action. Then the docs for each of the applications, is in`/doc` folder and available in this action.  
* AWS_ACCESS_KEY_ID
* AWS_REGION
* AWS_SECRET_ACCESS_KEY
The easiest way to test this is to:
1) create a bucket in AWS, which can be easily done via terraform:
```hcl
resource "aws_s3_bucket" "hex_docs" {
bucket = …
```
=> Publish hexdocs to s3 for main and version branches

.github/workflows/ci.yml
The new repo.hex.pm action uses latest ExDoc already.
=> Only build docs on ExDoc main on CI

lib/elixir/lib/enum.ex
Add examples to use Enum.group_by/3 on multiple keys.
Based on [this comment](https://elixirforum.com/t/how-to-use-enum-group-by-with-multi-columns/22122/3).
=> Add examples to Enum.group_by/3

Makefile
In versions of GNU Make prior to 4.4, ".NOTPARALLEL: compile" made the whole build run serially. In 4.4 and later, ".NOTPARALLEL: compile" makes only the compile target run serially.
This breaks the build and can lead to e.g. EEx being built before Mix.
Ref: https://bugs.gentoo.org/870016
=> Disable parallel build in Make 4.4

lib/elixir/src/elixir_erl_for.erl
I'm sorry, I just realized that I made a mistake in a [previous PR](https://github.com/elixir-lang/elixir/pull/12116/files#diff-1a2516ae4428444dcbaa8145d7ddc3392734519d455a18a2e6072a3de87f8d75L33-R32) and accidentally broke the optimization when a `for` comprehension result isn't used. This has been broken since 1.14.1.
I could confirm it works again after the fix:
```elixir
iex(1)> quote do
...(1)> for x <- [], do: x
...(1)> 1
...(1)> end
{:__block__, [],
[{:for, [], [{:<-, [], [{:x, [], Elixir}, []]}, [do: {:x, [], Elixir}]]}, 1]}
iex(2)> |> :elixir.quoted_to_erl(__ENV__) |> elem(0)
{:block, 0,
[
{:call, 0, {:remote, 0, {:atom, 0, Enum}, {:atom, 0, :reduce}},
[
{nil, 0},
{nil, 0},
{:fun, 0,
{:clauses,
[
{:clause, 0, [{:var, 0, :_@3}, {:var, 0, :_@4}], [],
[{:block, 0, [{:var, 0, :_@3}, …
```
=> Fix unused for optimization

lib/elixir/lib/gen_server.ex
- Explain what 'parent process' means in this context
- Explain when `c:terminate/2` is useful vs a monitor
- Move the "not guaranteed" warning higher up in the description
=> Clarify docs on terminate/2

lib/elixir/lib/path.ex, lib/elixir/test/elixir/path_test.exs
A fix for `Path.wildcard/2` when the wildcard contains a `..` like `Path.wilcard("h*/../w*")`.
=> Fix wildcard edge case

lib/elixir/lib/gen_server.ex
Determined by experimentation:
```elixir
defmodule Experiment do
use GenServer, shutdown: 15_000
def start_link(_args) do
GenServer.start_link(__MODULE__, nil, name: __MODULE__)
end
@impl GenServer
def init(_args) do
Process.flag(:trap_exit, true)
{:ok, %{}}
end
def handle_call({:hi, int}, _from, state) do
IO.inspect "got hi #{int}..."
Process.sleep(1_000)
{:reply, :ok, state}
end
def terminate(reason, state) do
IO.inspect inspect(:erlang.process_info(self(), :messages)), label: "terminating"
end
end
```
Place that in a supervision tree, `iex -S mix`, and call
```elixir
iex> for i <- 1..20, do: spawn(fn -> GenServer.call(Experiment, {:hi, i}) end)
iex> System.stop()
```
or
```elixir
iex> for i <- 1..5, do: spawn(fn -> GenServer.call(Experiment, {:hi, i}) end)
iex> System.stop()
iex> for i …
```
=> Another clarification for terminate/2

lib/elixir/lib/task/supervisor.ex
Both `async_nolink/3` and `async_nolink/5` require that you use a `temporary` restart strategy (the former simply calls the latter) but the docs do not make this sufficiently clear. This bit me while messing with them, as I thought the caveat only applied to the latter, but alas, it is not so.
=> Clarify that `Task.Supervisor.async_nolink/3` must also have a :temporary restart strategy

lib/elixir/lib/kernel/typespec.ex, lib/elixir/test/elixir/typespec_test.exs
Follow up on https://github.com/elixir-lang/elixir/pull/12258#issuecomment-1323203064 to fix another edge case.
```elixir
@type t :: %URI.t(){}
end
```
Note: I hesitate to just add some matching on `:__aliases__` and `:__MODULE__` pre-expansion, but I thought it was safer and more robust to match after the expansion to cover possible macro cases, even if that means a bit more nested code to handle it. WDYT?
=> Fix invalid typespec: struct

lib/elixir/lib/calendar.ex, lib/elixir/test/elixir/calendar_test.exs
=> Fix Calendar.strftime/2 format negative year incorrectly

lib/elixir/lib/code/formatter.ex, lib/elixir/lib/macro.ex, lib/elixir/src/elixir_bitstring.erl
Apply refactor suggested in https://github.com/elixir-lang/elixir/pull/12270#issuecomment-1327482191 and remove duplicated definitions of bitstring modifiers.
=> Refactor: use :elixir_bitstring to avoid duplication

lib/elixir/src/elixir_parser.yrl, lib/elixir/test/elixir/code_formatter/integration_test.exs
Close https://github.com/elixir-lang/elixir/issues/12273
This was caused by `Code.format_string` calling `Code.string_to_quoted_with_comments` with the option `literal_encoder: &{:ok, {:__block__, &2, [&1]}})`
Minimal example:
```elixir
iex(9)> Code.string_to_quoted_with_comments(~c"if 1, do: max 1, 2", literal_encoder: &{:ok, {:__block__, &2, [&1]}})
* 1st argument: not an atom
:erlang.atom_to_list({:__block__, [format: :keyword, line: 1], [:do]})
(elixir 1.15.0-dev) lib/elixir/src/elixir_parser.yrl:1222: :elixir_parser.warn_nested_no_parens_keyword/2
(elixir 1.15.0-dev) lib/elixir/src/elixir_parser.yrl:577: :elixir_parser.yeccpars2_463/7
(elixir 1.15.0-dev) /Users/sabiwara/.asdf/installs/erlang/25.0/lib/parsetools-2.4/include/y …
```
=> Fix formatter error on nested do without parenthesis

lib/mix/lib/mix/tasks/profile.fprof.ex, lib/mix/test/mix/tasks/profile.fprof_test.exs
The fprof mix task was using a tracer process. When tracing larger workloads, this tracer would get overloaded and cause issues (such as consuming too much memory, possibly crashing the VM). 
This is recommended in fprof docs: https://www.erlang.org/docs/23/man/fprof.html
I'm not sure this should be the default, maybe it should be behind an option.
=> fprof mix task: trace to file

lib/elixir/lib/partition_supervisor.ex
The existing example for `ParititionSupervisor` used `DynamicSupervisor`. Having to consider the two together made it a bit harder (IMO) to understand the part that was unique to `PartitionSupervisor`.
This PR adds a simpler example and also shows the `{:via` tuple needed to send a message to a partition.
=> Clarify partition supervisor

lib/elixir/lib/kernel/parallel_compiler.ex
During a typical recompilation in our codebase, we identified a long wait unaccounted for during logs emitted by `mix compile --profile time`. You can see the discrepancy here:
```bash
$ time mix compile --profile time
Compiling 53 files (.ex)
[profile]    152ms compiling +      0ms waiting for # super/secret/file.ex
[profile] Finished compilation cycle of 61 modules in 13129ms
[profile] Finished group pass check of 4749 modules in 3693ms
mix compile --profile time  105.24s user 49.85s system 135% cpu 1:54.71 total
```
We tracked this down to https://github.com/elixir-lang/elixir/blob/c02ea5406d8a4fa7ee6dc5ad8d26c78de35e761e/lib/elixir/lib/kernel/parallel_compiler.ex#L275-L278, where we eventually learned that most of the `:code.which/1` calls were taking ~25ms each because the module was …
=> Ensure all runtime_modules loaded before mapping their paths

lib/elixir/lib/enum.ex
The docstring for `Enum.count_until/3` references itself:
> See [count/2](https://hexdocs.pm/elixir/Enum.html#count/2) and [count_until/3](https://hexdocs.pm/elixir/Enum.html#count_until/3) for more information.
This PR changes that to reference `Enum.count_until/2` instead.
=> Fix circular reference in Enum.count_until/3 docstring

lib/elixir/lib/kernel/parallel_compiler.ex, lib/elixir/lib/module/parallel_checker.ex, lib/mix/lib/mix/compilers/elixir.ex
Backport of https://github.com/elixir-lang/elixir/commit/8f867100bb9d3bff1155907d9b355f64e85fc96d to `v1.14`
=> Precompile runtime module paths

lib/mix/lib/mix/tasks/eval.ex, lib/mix/lib/mix/tasks/release.init.ex, lib/mix/test/mix/tasks/eval_test.exs, lib/mix/test/mix/tasks/release_test.exs
It is handy for writing custom actions to communicate and operate with the release.
=> Allow passing extra arguments to eval release command

lib/elixir/pages/writing-documentation.md
Hi 
I've stumbled upon that those two links — 
1. https://help.github.com/articles/basic-writing-and-formatting-syntax/
2. https://guides.github.com/features/mastering-markdown/
Results to one resource — 
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax
(1) and (2) are basically point to the same resource, so I removed one and made this PR, because it did confuse me, and I think it is confusing in general that two (kinda of) different links point to the same resource at the end.
=> writing-documentation: removed redundant link

lib/elixir/lib/uri.ex, lib/elixir/test/elixir/uri_test.exs
This adds `URI.join_path/2` which was [proposed on the Elixir mailing list](https://groups.google.com/g/elixir-lang-core/c/KstQ_7ty6W4/m/CJxEBCCoDQAJ). This can be really useful when joining path segments on to a base url that already has a path.
```
iex> URI.join_path(URI.parse("http://example.com/foo"), "/my-path") |> URI.to_string()
"http://example.com/foo/my-path"
```
Do we like this function name? I chose it because it's similar to `Path.join/2`. However, there's also `URI.append_query/2`, so this could also be named `URI.append_path`.
Do we want to support providing `path` as a list so it would work similar to `Path.join/1`? I'm thinking it's simpler to just accept a string, but I figured I should double-check.
Also, this function strips any non-path URL segments like query strings …
=> Add `URI.append_path/2`

lib/elixir/lib/code.ex, lib/elixir/test/elixir/code_test.exs
=> Add Code.loaded?/1

lib/elixir/lib/kernel/parallel_compiler.ex, lib/elixir/test/elixir/kernel/parallel_compiler_test.exs
When running `mix compile --profile time`, we currently get output about how long each file took to compile, and how long it spent waiting for other compile-time dependencies to be available, but it doesn't say what those module are.
We can, for example, use `mix xref trace` and `mix xref graph` to determine what those dependencies are, but it isn't easy to analyze which ones will actually have an impact in practice on the compile times of the dependent modules.
This PR adds more detail to the `--profile time` option of the Elixir compiler, so that it also lists how long each module spent waiting for each dependency to become available.
I also looked into leaving the output the same unless the user also passes the `--verbose` option, but the problem is that it then outputs the file name …
=> Add details about waiting modules in `--profile time` compiler output

lib/elixir/test/elixir/system_test.exs
That's a proposal to fix #12290
Not signed binaries are just killed by codesign:
```
$ ./echo-elixir-test foo
zsh: killed     ./echo-elixir-test foo
```
But copying or linking works fine and there's no need to install `coreutils`. Makes sense?
/edit I'm getting the very same error as reported on the issue :)
=> system_test - link instead of copy to bypass macos 13 codesign

lib/mix/lib/mix/tasks/do.ex
Fixes a shell snippet that is supposed to illustrate the use of the comma separator.
=> Fix shell snippet in mix do doc

lib/elixir/lib/module.ex
Fixing a small typo I run into while reading the docs.
=> Fix arity of __after_verify__ in Compile callbacks documentation

lib/elixir/lib/map.ex, lib/elixir/test/elixir/keyword_test.exs, lib/elixir/test/elixir/map_test.exs
Following up from https://elixirforum.com/t/map-intersection-2/53121/12. I didn't see any duplicates, hopefully it's okay I pushed up.
My first PR, so tried to follow https://github.com/elixir-lang/elixir#contributing & https://github.com/elixir-lang/elixir/blob/main/CODE_OF_CONDUCT.md as best as I could.
---
* Add corresponding functions for Erlang's [`:maps.intersect/2`](https://www.erlang.org/doc/man/maps.html#intersect-2) & [`:maps.intersect_with/3`](https://www.erlang.org/doc/man/maps.html#intersect_with-3).
* Largely cargo-culted from `Map.merge/3`, including the tests & docs. More than happy to extend these.
* I extended the diff list in `KeywordTest` since I wasn't sure if extending `Keyword` would be out-of-scope. Happy to add a `Keyword.intersect` function as well, if desired.
* …
=> Add Map.intersect/2 and Map.intersect/3

lib/elixir/lib/kernel.ex
This change:
- Explicitly mention that both numbers need to be integers for the result to be an integer to make that condition clearer. Before this change, the docs explicitly mentions base had to be an integer, but there is no mention of this condition for the exponent.
- Adds `@spec` for the float-integer and integer-float input combinations.
=> Improve docs for Kernel.pow

bin/elixir
This fixes #1234 where previous escaping pattern accidentally used invalid character range in the regexp.
By using `@` as a pattern delimiter and pushing the `-` to the end of the bracket we avoid both problems (wrong escaping, and accidental character range).
=> Fix escaping of positional args in bin/elixir (#12345)

lib/elixir/src/elixir_erl_for.erl
Optimizing simple `for` comprehensions as `Enum.map/2` when possible, e.g. just looping on a variable (instead of `Enum.reduce |> :lists.reverse`).
=> Optimize for as Enum.map/2 when sensible

lib/elixir/src/elixir_erl_for.erl
In the same spirit as https://github.com/elixir-lang/elixir/pull/12352, `for x <- ..., into: %{}, do: ...` can use `Enum.map |> :maps.from_list` instead of `Enum.reduce |> :lists.reverse |> :maps.from_list`:
=> Optimize for into map as Enum.map/2

lib/elixir/lib/code.ex
Also, although `:parser_options` is mentioned ("... the `:parser_options` compiler option ..."), no link is supplied.
=> Fix some wording in the docs

lib/elixir/lib/macro.ex, lib/elixir/src/elixir_parser.yrl, lib/elixir/test/elixir/macro_test.exs
Addresses the issue discussed in https://github.com/elixir-lang/elixir/issues/12351.
This adds a piece of `from_brackets` metadata to `Access.get/3` calls that is used to determine when raising this error is necessary. I was not sure how much context/suggestion to offer in the error message, so I tried to strike a balance between being helpful and overly prescriptive to the user.
Please let me know if I've broken any conventions, need to add more tests, or could improve the error message here as this is my first time contributing! Thanks.
=> Add error message when piping into an expression ending in bracket-based access

lib/iex/lib/iex/server.ex
In 7132a115296e86038cb495f6d07d2e38180cd71b, an additional argument was added to `IEx.Server.take_over?/5`, `counter`.
old:
```
defp take_over?(take_pid, take_ref, take_location, take_whereami, take_opts)
```
new:
```
defp take_over?(take_pid, take_ref, take_location, take_whereami, take_opts, counter)
```
`take_over?/6` is called at two places in IEx.Server, lines 60 and 201.
In one of those locations (line 60), the new `counter` argument was placed in the second-to-last position rather than the last position.
```
if take_over?(take_pid, take_ref, take_location, take_whereami, 1, take_opts)
```
I'm still working through a test for the test suite, but the following set of steps reproduces the issue when using elixir compiled from `main` as of time of writing:
```
% mix new testapp
% cd …
```
=> Fix out-of-order arguments in IEx.Server.shell_loop

lib/elixir/lib/dynamic_supervisor.ex
Renamed `opts` to `options` and linked to `start_link/1` for the options.
=> Improve docs for DynamicSupervisor.child_spec/1

lib/iex/lib/iex/broker.ex
The return type changed in
https://github.com/elixir-lang/elixir/commit/7132a115296e86038cb495f6d07d2e38180cd71b#diff-3e0ede30fd7f00793f4a685a30d4dfc03dfd3c881e1f648d9299b03470ad5a42R134
=> Fix IEx.Broker.take_over/3 spec

lib/elixir/lib/code/fragment.ex, lib/elixir/test/elixir/code_fragment_test.exs
Hey 👋
Addressing this issue https://github.com/elixir-lang/elixir/issues/11876.
This is probably not the correct or optimal way to achieve this but I just gave it a shot while trying to understand the `Code.Fragment` module better. So I'm happy to completely retry it with a different suggested approach.
The return types are as suggested in the issue:
```elixir
iex(1)> Code.Fragment.cursor_context("DateTime.utc_now()")
:none
iex(2)> Code.Fragment.cursor_context("DateTime.utc_now().")
{:dot, {:dot_call, {:alias, ~c"DateTime"}, ~c"utc_now"}, []}
iex(3)> Code.Fragment.cursor_context("DateTime.utc_now().ho")
{:dot, {:dot_call, {:alias, ~c"DateTime"}, ~c"utc_now"}, ~c"ho"}
iex(4)>
```
=> Support nested expressions in `cursor_context/1`

lib/elixir/src/elixir_erl.erl
I am not entirely sure why the pass `from_core` -> `to_core` is even necessary, but I suppose it might invoke some compiler optimizations that operate on Core Erlang. Anyway, unless I am very much mistaken, `core` is not a valid option for the `compile` module: it is ignored and this function was actually returning BEAM byte code instead.
=> Fix elixir_erl:debug_info/4 returning core_v1

lib/elixir/lib/enum.ex, lib/elixir/lib/range.ex
<details>
<summary>Banchee report</summary>
```
Operating System: Linux
CPU Information: AMD Ryzen 7 PRO 6850U with Radeon Graphics
Number of Available Cores: 16
Available memory: 30.13 GB
Elixir 1.15.0-dev
Erlang 25.2
Benchmark suite executing with the following configuration:
warmup: 2 s
time: 10 s
memory time: 2 s
reduction time: 0 ns
parallel: 1
inputs: 100, 1000, 100_000, 10_000
Estimated total run time: 1.87 min
Benchmarking :list.seq with input 100 ...
Benchmarking :list.seq with input 1000 ...
Benchmarking :list.seq with input 100_000 ...
Benchmarking :list.seq with input 10_000 ...
Benchmarking Range + Enum.to_list with input 100 ...
Benchmarking Range + Enum.to_list with input 1000 ...
Benchmarking Range + Enum.to_list with input 100_000 ...
Benchmarking Range + Enum.to_list …
```
=> Optimize Enum.to_list for ranges, closes #12383

lib/elixir/lib/code/normalizer.ex, lib/elixir/test/elixir/code_normalizer/formatted_ast_test.exs
`normalize_call/2` was passing the old `state.parent_meta` when normalizing call arguments, which prevented `:line` meta from being correctly applied to unwrapped literals. This had the effect of causing comment collapses in certain cases:
```elixir
assert_same """
block do
1 + 1
2 + 2
end
""",
literal_encoder: fn literal, _ -> {:ok, literal} end
"""
block do
1 + 1
2 + 2
end
"""
```
=> `Code.Normalizer`: Use correct meta fields in `normalize_call/2`

lib/ex_unit/lib/ex_unit/callbacks.ex, lib/ex_unit/test/ex_unit/callbacks_test.exs
Attempt to improve the error in https://github.com/elixir-lang/elixir/issues/12381.
@josevalim if we carry around the caller's file/line, we can make a nice error right? Are there downsides here that I'm missing?
(Also, we could use `:erlang.raise/3` and make it seem like the error is actually coming from the setup call?)
=> Improve errors for ExUnit callbacks

lib/elixir/lib/enum.ex
While doing a small [benchmark](https://github.com/sabiwara/elixir_benches/commit/533fa8f35fd7b5e43939e49700139f5bec80bbba), I noticed that `:lists.sort/1` followed by `:lists.reverse` is still 2~4x faster and uses ~1.4x less memory than using `:lists.sort/2`.
=> Optimize Enum.sort(list, :asc | :desc)

lib/elixir/lib/string.ex, lib/elixir/test/elixir/string_test.exs
Based on the discussion on #12354, this PR adds an optional `:fast_ascii` option to `String.valid?/2` (based on the `bit56` algorithm discussed there). I've confirmed that this implementation yields the same benefits as observed previously:
<details>
<summary>Benchmark (OTP26, ARM)</summary>
```
iex(3)> Benchee.run(
...(3)>   %{
...(3)>     "stock" => fn {valid, input} -> ^valid = String.valid?(input) end,
...(3)>     "fast_ascii" => fn {valid, input} -> ^valid = String.valid?(input, :fast_ascii) end,
...(3)>   },
...(3)>   time: 10,
...(3)>   memory_time: 2,
...(3)>   inputs: %{
...(3)>     1 => {false, String.duplicate("a", 0) <> <<128::8>>},
...(3)>     4 => {false, String.duplicate("a", 3) <> <<128::8>>},
...(3)>     8 => {false, String.duplicate("a", 7) <> <<128::8>>},
...(3)>     16 …
```
=> Add `:fast_ascii` mode to `String.valid?/2`

lib/logger/lib/logger.ex, lib/logger/lib/logger/app.ex, lib/logger/lib/logger/config.ex, lib/logger/lib/logger/filter.ex, lib/logger/lib/logger/handler.ex, lib/logger/test/logger/handler_test.exs
The separation will help us extract the Logger
formatter into its own entity in future commits.
=> Convert Logger translator into a logger filter

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
Make `Enum` tests for maps independent of Map ordering, in order to fix tests for [OTP26](https://github.com/erlang/otp/releases/tag/OTP-26.0-rc1). (see also: https://github.com/elixir-lang/elixir/pull/12404)
=> Fix Enum tests for maps in OTP26

lib/elixir/lib/inspect.ex, lib/elixir/lib/inspect/algebra.ex, lib/elixir/test/elixir/inspect_test.exs, lib/elixir/test/elixir/map_test.exs
Add `:sort_maps` to `Inspect.Opts.custom_options` in order to make inspect tests deterministic and fix them in [OTP26](https://github.com/erlang/otp/releases/tag/OTP-26.0-rc1).
Note: other tests like `Enum` tests also need to be fixed, will do it in a separate PR.
=> Add :sort_maps to Inspect.Opts.custom_options

lib/mix/lib/mix/tasks/deps.compile.ex
While writing an experimental language server, I was firing up a separate VM to host the project. From this VM, i would get consistent crashes when trying to invoke `Mix.Task.run("deps.compile")` when it tried to compile `telemetry`, which is a rebar3 project. The reason was that the language server vm sets the current directory away from the project after the project is bootstrapped, and again during the compilation process. The global nature of `File.cd!` meant the command was being run from the incorrect directory, which led compilation to fail. 
This is a far edge case, but it seems to me that using the `cd:` option to `Mix.Shell` should be much safer than relying on the race-prone `File.cd!`.
This change drops the use of File.cd! when invoking Mix.shell in favor of passing the cd …
=> Use the cd option in Mix.Shell

lib/ex_unit/lib/ex_unit/capture_log.ex, lib/ex_unit/lib/ex_unit/capture_server.ex, lib/ex_unit/test/ex_unit/capture_log_test.exs
=> Use Erlang logger handlers in ExUnit.CaptureLog

lib/logger/lib/logger.ex
Part of https://github.com/elixir-lang/elixir/issues/9465.
=> Add Logger.add_handlers/1

lib/logger/lib/logger.ex, lib/logger/lib/logger/app.ex, lib/logger/mix.exs, lib/logger/test/logger_test.exs
Part of https://github.com/elixir-lang/elixir/issues/9465.
=> Expose :logger's global metadata

lib/elixir/test/elixir/kernel/raise_test.exs
Without this extra purge, tests are failing on OTP26 RC1 (`fun.()` still returning `:ok`).
But maybe we can just remove this test since `BadFunctionError` is already tested.
=> Fix badfunc test on OTP26

lib/elixir/lib/module/types.ex, lib/elixir/lib/module/types/of.ex, lib/elixir/src/elixir_map.erl, lib/elixir/test/elixir/module/types/pattern_test.exs
This should be the last fix regarding non-deterministic key order in OTP26 maps.
- One fix to make struct expansion deterministic
- One fix to make pattern typing deterministic
=> Deterministic struct expansion

lib/elixir/lib/protocol.ex
The protocols documentation doesn't include an obvious "how to use the protocol" after you've defined it. It does have an example in the "Types" section but it felt a bit tucked away. Hopefully this makes it pretty obvious to new readers.
=> Include direct example of calling protocol function

lib/elixir/lib/exception.ex, lib/elixir/src/elixir_clauses.erl, lib/elixir/src/elixir_erl_pass.erl, lib/elixir/src/elixir_erl_try.erl, lib/elixir/test/erlang/control_test.erl, lib/elixir/test/erlang/function_test.erl
Since the [`maybe`](https://www.erlang.org/doc/reference_manual/expressions.html#maybe) expression has been added to erlang:
- `else` has became a keyword, so it is better to quote its atom
- when `else` doesn't match, it throws an `{:else_clause, value}`, since our `with` is quite similar we might as well use the same for consistency
=> Follow-up for Erlang `maybe`

lib/logger/lib/logger.ex
Some metaprogramming was leading to `@doc since: "1.11.0"` being used for all generated Logger macros. Instead, it should be present only for "newer" Erlang levels (such as `notice` or `critical`), and not levels such as `error` which were always present in Elixir.
=> Fix "@doc since" for some Logger macros

lib/elixir/test/elixir/exception_test.exs
I noticed one more failing test on OTP26 due to non-deterministic map inspection (see also https://github.com/elixir-lang/elixir/pull/12418):
=> Fix more map inspection tests

lib/elixir/lib/string.ex
Like [this person here](https://elixirforum.com/t/is-this-a-correct-way-to-avoid-wasting-or-reaching-the-atom-limit/23137), I misunderstood what was happening when one calls `String.to_atom`. This commit makes a minor documentation change to make the difference more explicit. 
-----------
In the link, the person asked:
> As I have to generate several atoms from strings and as atoms are not garbage collected and there’s a limit for each process, does this function is correct to “save” them atoms ? :
> 
> ```
> def string_to_atom(str) do
>     try do
>       String.to_existing_atom(str)
>     rescue
>       ArgumentError -> String.to_atom(str)
>     end
>   end
> ```
> Or do you know any smarter (or “elixier”) way to achieve this (perhaps without this ugly “try rescue”) ?
=> Make `to_atom` vs `to_exsting_atom` usage more explicit

lib/ex_unit/lib/ex_unit/cli_formatter.ex, lib/mix/lib/mix/tasks/test.coverage.ex, lib/mix/test/mix/dep_test.exs
Fixes `make test_mix` on OTP 26:
1. Make mix test reports deterministic 91c258f78dc505e4cbd5ffce4d8e0f657eb43111
The reports for the following were both relying on map keys ordering:
- mix test
- mix test.cover
2. Fix non-deterministic test 534b48237d0e919604d7bd8119d9350fc36c7e15
=> Make mix test reports deterministic in OTP26

lib/elixir/lib/io/ansi/docs.ex
Fixes the sorting for metadata printing in OTP 26.
=> Sort metadata before printing

lib/mix/lib/mix/tasks/test.ex
=> Correctly document mix test --profile-require option

lib/ex_unit/lib/ex_unit.ex, lib/mix/lib/mix/compilers/test.ex, lib/mix/test/mix/tasks/test_test.exs
Addresses https://groups.google.com/g/elixir-lang-core/c/yjs-zaFvZJc
Looking for feedback on implementation and testing strategy.
=> Use `seed` to randomize require order of test files

lib/elixir/lib/calendar.ex, lib/elixir/lib/calendar/datetime.ex, lib/elixir/lib/calendar/iso.ex, lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/test/elixir/calendar/holocene.exs, lib/elixir/test/elixir/calendar/naive_datetime_test.exs
Addresses https://groups.google.com/g/elixir-lang-core/c/dfAn00VCA9Q
=> Add DateTime/NaiveDateTime.beginning_of_day and DateTime/NaiveDateTime.end_of_day

lib/elixir/lib/code/formatter.ex, lib/elixir/lib/macro.ex, lib/elixir/src/elixir_errors.erl, lib/elixir/src/elixir_parser.yrl, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/code_formatter/general_test.exs, lib/elixir/test/elixir/code_fragment_test.exs, lib/elixir/test/elixir/kernel/parser_test.exs, lib/elixir/test/elixir/kernel/sigils_test.exs, lib/elixir/test/erlang/tokenizer_test.erl
First pass at #12447.
Still need to update docs 🙃
=> Add support for multi-letter uppercase sigils

lib/elixir/lib/system.ex
+spp is defaulted to `false` and we should show that. I also included some docs from the +spp docs for finding it.
=> Showing the "default" for the :parallelism option

lib/iex/lib/iex.ex, lib/iex/lib/iex/evaluator.ex
On a mission to purge clutter, moving elixir related stuff into its own folder.  Besides, this lets you override "default" `iex.exs` by setting an env variable instead of loading the default one at `~/`.
=> Supporting IEX_HOME like MIX_HOME

lib/elixir/lib/module.ex
The ability to call `module.__info__(:struct)` has been added since 1.14 but the doc wasn't mentioning since when
=> Document supported version for __info__(:struct)

lib/elixir/lib/stream.ex, lib/elixir/test/elixir/stream_test.exs
=> Fix Stream.zip/1 with empty list inducing memory spike

lib/mix/lib/mix/tasks/compile.elixir.ex, lib/mix/test/mix/tasks/compile.elixir_test.exs
Without this, moving or copying a directory would not recompile beam files despite the fact their `:source` absolute path is obsolete. This could create issues with `ex_doc` when generating links.
=> Include cwd in compiler cache key

lib/elixir/lib/calendar.ex
There was a report on the ElixirForum about the docs for [`Calendar.strftime/3`](https://hexdocs.pm/elixir/1.14.3/Calendar.html#strftime/3) being difficult to read/understand: https://elixirforum.com/t/converting-time-to-remedial-human-form/54511/3
This PR attempts to improve the docs by making it more clear that the "User Options" section corresponds to the `user_options` argument and that the "Accpeted string formats" section applies to the `string_format` argument.
I also thought about moving one of the examples higher up in the docs since the docs for this function are quite lengthy but I wasn't sure if that was against the documentation guidelines for Elixir since I'm not aware of any other function that has examples up front instead of at the bottom.
Another alternative to consider …
=> Readability improvements for Calendar.strftime/3

CHANGELOG.md, lib/iex/lib/iex/info.ex, lib/iex/test/iex/info_test.exs
Since regexes are also represented with a sigil, I thought it might be a good idea for them to implement `IEx.Info` too.
Feel free to close if you prefer to avoid it.
=> Implement IEx.Info for Regex

CHANGELOG.md
Took me a while to dig this out, but seems like https://github.com/elixir-lang/elixir/commit/335c0f6748c4f2ec60cfc8c0577932ebf5d81a4a wasn't included in the changelog.
Figured this out because some Xandra tests were breaking on Elixir 1.14.2, which has this bug.
=> Add missing entry to CHANGELOG for v1.14.3

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
Hi, I made a follow-up similar to https://github.com/elixir-lang/elixir/pull/12472 for `cond` expressions:
Unlike `case`, I figured it might be nice to give the result of each clause's left-expression, since it is truthiness based and the result might even be used on the right-hand side.
=> Add more info for :cond expressions in dbg/1

lib/elixir/test/elixir/kernel/dialyzer_test.exs
I'm a bit out of my depth trying to investigate why, but dialyzer tests break on OTP26 with errors like
I couldn't pinpoint which change is causing this. Adding all the "unknown" modules to the PLT manually fixed the tests, but I'm not sure if there is a regression in dialyzer itself to be fixed instead?
=> Fix dialyzer tests in OTP26

lib/mix/lib/mix/utils.ex
OTP26-rc2 changed the default behaviour of the http client from `:verify_none` to `:verify_peer` which results in following error when trying to install hex: 
```
Mix requires the Hex package manager to fetch dependencies
Shall I install Hex? (if running non-interactively, use "mix local.hex --force") [Yn] 
** (Mix) httpc request failed with: {:failed_connect, [{:to_address, {~c"repo.hex.pm", 443}}, {:inet, [:inet], {:options, {:verify, {:missing_dep_cacertfile_or_cacerts}}}}]}
```
This PR fixes this, by explicitly defining `:verify_none`.
=> Add explicit `:verify_none` for httpc

lib/mix/lib/mix/tasks/format.ex, lib/mix/test/mix/tasks/format_test.exs
This came up today with a custom formatter that we have for json files. Vscode's ElixirLS created a directory called "apps/our_app/.elixir_ls/build/test/lib/phoenix/priv/templates/phx.gen.json" and running `mix format` resulted in the following error:
```
** (File.Error) could not read file "/Users/edennis/sandbox/...": illegal operation on a directory
(elixir 1.13.4) lib/file.ex:355: File.read!/1
(mix 1.13.4) lib/mix/tasks/format.ex:563: Mix.Tasks.Format.format_file/2
(elixir 1.13.4) lib/task/supervised.ex:89: Task.Supervised.invoke_mfa/2
(elixir 1.13.4) lib/task/supervised.ex:34: Task.Supervised.reply/4
(stdlib 3.17.2.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
```
The fact that we're accidentally formatting files from ElixirLS is of course an issue of ours, but with the exception …
=> Don't call formatter on directories

lib/iex/test/iex/autocomplete_test.exs, lib/iex/test/iex/interaction_test.exs
The `:user` module seems to be removed, so I changed the test to use `:logger`.
Also added `sort_maps` for "inspect opts" test to make it pass again.
This fixes the last failing tests for OTP26-rc2 for me.
=> Add iex tests for OTP26

lib/iex/test/iex/autocomplete_test.exs, lib/iex/test/iex/interaction_test.exs
Couldn't think of a more elegant solution than string matching the fields of the resulting map output. 
Hope that's good enough.
=> Backport test fixes from #12491

lib/elixir/lib/option_parser.ex, lib/elixir/test/elixir/option_parser_test.exs, lib/mix/lib/mix/tasks/run.ex, lib/mix/test/mix/tasks/run_test.exs
Attempt to fix #12460
What about `mix run file -- arg1 arg2`? It will return argv as `["--", "arg1", "arg2"]`, I'd like to confirm that's the expected value.
=> Add `:return_separator` to `OptionParser`

lib/elixir/lib/string.ex
Every time I try to convert a string to a module name, I receive an error, which I find to be very confusing. I believe the example in the document can help to address this issue. Therefore, I am aware that the document needs to be very simple and basic. 
You get to decide. 🙏🏻 
Hopefully I didn't squander your time.
Thanks
=> Clarification to convert a string to module name by `to_existing_atom`

lib/mix/lib/mix/utils.ex
I am trying to implement a `mix` builder for `rebar3` to improve compatibility. `rebar3` has a slightly different model for compiling its dependencies in that it (usually) compiles in-place, having the code checked out to `_build/default/lib`. This is effectively `MIX_DEPS_PATH=./_build/default/lib` and `MIX_BUILD_PATH=./_build/default`. Setting these values breaks due to `symlink_or_copy` getting the same path as source and target from `Mix.Project`.
=> Make symlink_or_copy a no-op if source is same as target

lib/elixir/src/elixir_interpolation.erl, lib/elixir/test/erlang/string_test.erl, lib/elixir/test/erlang/tokenizer_test.erl
Fixes #12503. Running the example given in that issue with this build of Elixir now gives the expected columns.
=> Fix column count when tokenizing escaped interpolations

lib/elixir/lib/macro/env.ex
[Discussion on mailing list](https://groups.google.com/g/elixir-lang-core/c/3Ea3CuJH-3Q)
@josevalim, in your response on the mailing list, you wrote `fetch_alias_as`. I had originally thought of it as `fetch_aliased_as`, which read a bit better to me, but I do not feel strongly at all. If you would prefer `fetch_alias_as`, I'm happy to update and rebase this!
=> Add `Macro.Env.lookup_alias_as/2`

lib/mix/lib/mix/project.ex, lib/mix/test/mix/dep_test.exs
Partial Implementation of https://github.com/jshmrtn/mix-dependency-submission/issues/5#issuecomment-1494907802 as discussed with @josevalim 
While implementing this feature, I noticed that `Mix.Project.traverse_deps/2` allways returns paths for nested dependencies instead of calling the `fun` argument. This PR also solves that and tests it directly with the new `deps_tree` tests.
=> Introduce `Mix.Project.deps_tree/1`

lib/elixir/lib/map.ex
The behaviour of Map.get/3 is clear from the documentation.
However, it might not be immediately obvious that a nil value under a key does not lead to the default value being returned, so it might be worth adding an example to illustrate.
=> Add an example to Map.get documentation where key is present, but value is nil

lib/elixir/pages/naming-conventions.md
The quality of the documentation is top-notch, a pleasure to read :clap:
=> Fix typo in naming-conventions.md

lib/ex_unit/lib/ex_unit/case_template.ex
The [documentation](https://hexdocs.pm/ex_unit/ExUnit.CaseTemplate.html) states that when using `ExUnit.CaseTemplate` _All the functions and macros defined in MyCase are imported into the test case_, but that is not the case in my machine, on the main branch, without this change.
=> Actually import case template functions into test case modules

lib/elixir/lib/gen_server.ex
Per the discussion on Elixir Core. I am creating a pull request for further discussion. 
1. Use arguments and variables to describe what the arguments to GenServer callbacks and result tuples do. 
2. Call out the purpose of `c:init/1` by having it be more than a passthrough for the initial GenServer state. 
3. Do less work in the function heads and add more intermediate variables to label important beginner concepts. 
-bt
=> Make GenServer documentation friendlier to beginners

lib/elixir/lib/port.ex
This PR updates the documentation for `Port.info/2` to clarify how that function differs from `Port.info/1`. I'm only adding parentheses to the description in `Port.info/1` to keep it consistent with `Port.info/2` (and I did so there because the sentence might be confusing otherwise).
=> Clarify difference between `Port.info/1` and `Port.info/2` in docs

lib/mix/lib/mix/tasks/format.ex, lib/mix/test/mix/tasks/format_test.exs
I found a need for this today. I was setting up a mix alias like:
```elixir
check: [
"format --check-formatted",
"dialyzer --ignore-exit-status",
"credo diff --from-git-merge-base develop --strict --mute-exit-status",
"sobelow --verbose --strict --private --threshold medium"
]
```
However, if code isn't formatted, `--check-formatted` raises and error and returns a non-zero exit code, preventing the rest of the commands from running. In my case, I don't want that.
What I ended up doing is using a custom mix task:
```elixir
defmodule Mix.Tasks.CheckFormatWithoutExit do
@moduledoc """
Runs `mix format --check-formatted` and prints the result in the terminal without returning an error exit code.
"""
use Mix.Task
@spec run(list(binary())) :: :ok
@impl Mix.Task
def run(args) do …
```
=> Add --no-exit option to mix format

lib/elixir/lib/module.ex
To match the code in module.ex as well as actual
test examples such as [1]
1. https://github.com/elixir-lang/elixir/blob/ee9d529bf2b500933c15f3247873f83e2332a6fe/lib/elixir/test/elixir/fixtures/dialyzer/remote_call.ex#L6
=> module.ex: correct a typo in @dialyzer suppression example

lib/elixir/lib/module.ex
This had me stumped for a second, thought it was worth clarifying.
=> Document what an @external_resource path is relative to.

lib/logger/lib/logger.ex, lib/logger/lib/logger/app.ex
See discussion [here](https://groups.google.com/g/elixir-lang-core/c/T3v2JJWOR-g/m/FvDCTVo8HQAJ?utm_medium=email&utm_source=footer).
If the `:config` provided to `:default_handler` is a keyword list, we will now convert it into a map as expected by `:logger_std_h`, to support deep `Config.config` keyword list merging.
This implementation does not touch things that are not keyword lists, passing them through to `:logger_std_h` verbatim so it can issue its own error messages as appropriate.
=> Convert Logger's default_handler config into maps

CHANGELOG.md, lib/mix/lib/mix/hex.ex, lib/mix/lib/mix/local.ex, lib/mix/lib/mix/tasks/local.hex.ex, lib/mix/lib/mix/tasks/local.rebar.ex
The domain change is backwards compatible because repo.hex.pm will redirect to builds.hex.pm in the future and we are correctly following the redirects.
=> Use new domain repo.hex.pm => builds.hex.pm

lib/elixir/lib/module.ex
Discovered in https://github.com/elixir-lsp/elixir_sense/pull/219#issuecomment-1532906412
It seems some options discussed in https://github.com/elixir-lang/elixir/pull/10926 didn't make it to the final commit.
BTW we have a convention that underscored attributes are private and undocumented (`@__struct__`, `@__functions__`, `@__impl__`) and yet there is one publicly documented: `@__records__`. Should this one be included here? In my opinion we should list here all underscored ones as well. Reserved word has some meaning - expect things to break unless you know what you are doing.
=> Add missing reserved attributes

lib/iex/lib/iex/autocomplete.ex, lib/iex/test/iex/autocomplete_test.exs
Complete struct fields after `%URI{var | `
Complete map fields after `%{map | some: \"foo\",`
I have no idea how to make `%{map | ` work though as in this case `Code.Fragment.container_cursor_to_quoted` returns `{:%{}, [line: 1], [{:__cursor__, [line: 1], []}]}` and `map` variable as well as map update AST is lost
=> Make struct field completion work in map update syntax

lib/mix/lib/mix/tasks/format.ex, lib/mix/test/mix/tasks/format_test.exs
This address https://github.com/elixir-lsp/elixir-ls/issues/526 and https://groups.google.com/g/elixir-lang-core/c/r5FA-4_Fu9o/m/rZiFgGOJBAAJ
In the case of IDE trying to format snippets or files, it is possible that another task is running concurrently that may change `cwd` while we are recovering the formatter options. This end up showing as the formatter failing. It is particularly visible for people using "Format on Save", as recompilation usually happens at save time.
To avoid the problem, I introduce a new option as discussed above, `:relative_to`. I did not expand the general `mix format` to accept the option, as it is right now only documented to work from the root of the project and I did not see a need for it.
I reused the `prefix` concept that was already existing for plugins, …
=> add relative_to for formatter_for_file

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
Adding a specialized implementation of `Enum.map/2` for ranges leads to a noticeable speed improvement ([~1.40x](https://github.com/sabiwara/elixir_benches/commit/14c8e3a7b327591e3eaa6fb708758d371223c427)).
- the implementation is based on the existing [`Enum.reduce/3`](https://github.com/elixir-lang/elixir/blob/89e3ecc944f2eb5508e4614c3a1e3279086bdbea/lib/elixir/lib/enum.ex#L4348-L4356) implementation
- when benchmarking, I noticed that inlining the private helpers made a huge difference and could also speed-up `reduce_range/5`, so I added it as well
- this will also impact `for` which compiles to `Enum.map/2` in some cases since 1.15
=> Optimize Enum.map/2 for ranges

lib/elixir/src/elixir_tokenizer.erl
Before this patch we had:
iex(1)> ~Decimal"1"
** (SyntaxError) iex:1:1: invalid sigil name, it should be either a one-letter lowercase letter or a sequence of uppercase letters only~Decimal"1"
Now, it's:
iex(1)> ~Decimal"1"
** (SyntaxError) iex:1:1: invalid sigil name, it should be either a one-letter lowercase letter or a sequence of uppercase letters only, got: ~Decimal"1"
=> Improve sigil SyntaxError

lib/elixir/lib/calendar/datetime.ex, lib/elixir/lib/calendar/naive_datetime.ex
This pull request adds support for passing a time unit to `NaiveDateTime` and `DateTime`'s  `utc_now/1` and creates an alternative `utc_now/2` that accepts both a custom time unit and calendar.
Closes #12557
=> Support precision in NaiveDateTime/DateTime.utc_now

lib/elixir/lib/enum.ex, lib/elixir/lib/map.ex
That maps show up in `Enum.reduce/4` as a `{key, value}` tuple may not be obvious to new users of Elixir, and after not using that function that way in a while, I found myself looking online to confirm the syntax. I thought it'd be nice if an example was in the docs, which will also make it show up in some IDEs.
I added this only on `Enum.reduce/4`, not `/3` because I couldn't think of a straighforward way one would use `Enum.reduce/3` with a map. (I can't think of when one would want to get back something like `{first_key_name: total_count}`)
=> add example of Enum.reduce/4 on a map to docs

lib/elixir/lib/system.ex
since https://github.com/elixir-lang/elixir/pull/12558 it is also being called with :native as the time_unit
=> Update System.os_time/1 spec

lib/elixir/src/elixir.erl
Fixes issue reported in https://github.com/elixir-lang/elixir/pull/12564 comments.
According to https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/fileno?view=msvc-170 when there is no associated output stream to `stdout`, `_fileno` returns `-2` without setting an error, which causes otp to return `ebadf` on `prim_tty:isatty`. Its not clear yet if this behaviour is intended, and a bug report will be filed for otp.
Either way, considering that the signature of the function is `true | false | ebadf`, I think elixir should use `== true` as a condition to enable ANSI.
=> Disable ANSI when stdout is not a valid file descriptor

lib/elixir/lib/code.ex
Alternatively maybe the Code.print_diagnostic function should accept either this diagnostic map or the mix struct, or the call site should always construct a map. Currently the compiler is passing the struct: https://github.com/elixir-lang/elixir/blob/df521d308694b187fa1dc8835f1e5c8f7b79e4e8/lib/mix/lib/mix/compilers/elixir.ex#L712
=> Update diagnostic type for compatibility with Mix.Task.Compiler.Diagnostic struct

.github/workflows/notify.yml, .github/workflows/release.yml, .github/workflows/repo.hex.pm.yml
Add OTP26 to other github actions or migrates depending.
=> Add OPT 26 to other Github actions

lib/elixir/lib/kernel/special_forms.ex
- Remove obsolete documentation disclaimer about `:generated` option in `quote/1` (now gets propagated)
- Precise that this can be used to ignore dialyzer errors, since this is not obvious it has this effect and can be useful knowledge
=> Remove obsolete doc about :generated option in quote/1

lib/elixir/pages/typespecs.md
'no_return' was removed from functions like `File.copy!/3` in https://github.com/elixir-lang/elixir/pull/8092
In the comment thread, someone asked whether the documentation should mention that certain other functions may raise, but José responded:
> Any function can fail any time in face of invalid input
=> Note about typespecs for functions which raise

lib/mix/lib/mix/task.ex, lib/mix/test/fixtures/umbrella_test/apps/bar/mix.exs, lib/mix/test/fixtures/umbrella_test/apps/foo/mix.exs, lib/mix/test/mix/task_test.exs
Previously, when an alias existed within an umbrella child, running this from the umbrella root would result in an error that the mix task was not found.
This commit checks the aliases of the children, and if any of the children have the alias then it will be executed in the children. Any children that do not have the alias will be skipped.
I don't like the implementation here, so I'd appreciate any pointers for how to do this in 1 pass.
Closes #12572
=> Consider mix alises in umbrella projects

lib/elixir/lib/code.ex, lib/elixir/lib/kernel/parallel_compiler.ex, lib/elixir/lib/module/parallel_checker.ex, lib/elixir/src/elixir_errors.erl, lib/elixir/test/elixir/code_test.exs
Close https://github.com/elixir-lang/elixir/issues/12585
I'm not sure if this is the way we want to close this, but it seems that the expected format for compiler diagnostics is absolute paths, so if we want to have `Code.with_diagnostics/2` return relative paths, I believe this is where we should format it?
=> Code.with_diagnostics/2 formats paths as relative

lib/elixir/lib/module.ex, lib/elixir/test/elixir/kernel/lexical_tracker_test.exs, lib/elixir/test/elixir/module_test.exs
See #12608 for context.
This PR currently retains (and adds tests for) the behavior described in #12610, but it's an easy fix if we want to include that here.
=> Add `Module.get_last_attribute/3`

lib/elixir/lib/agent.ex, lib/elixir/lib/application.ex, lib/elixir/lib/dynamic_supervisor.ex, lib/elixir/lib/gen_server.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/supervisor.ex, lib/elixir/lib/task.ex, lib/elixir/pages/library-guidelines.md, lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/lib/ex_unit/case_template.ex, lib/mix/lib/mix/project.ex, lib/mix/lib/mix/task.ex
One common concern about using Elixir libraries
is that "use SomeModule" does not make clear how
it impacts the caller. Most of the time those
changes are minor but it is impossible to know
without reading the source code.
This pull request suggests defining a summary
alongside each module that succinctly explains
the impact of using it.
This is documented as best practice in our guides
and we added the note to all of Elixir modules.
=> Define "nutrition facts" for "use SomeModule"

lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/test/ex_unit/case_test.exs
Note: I wanted to post a proposal before opening this PR, but don't have time this moment and thought it better to put this out there. Happy to post a proposal later tonight if desired.
---
This PR introduces a new function, `ExUnit.Case.most_recent_registered_test/1`, primarily to allow library authors blessed access to compile-time test and tag information.
As tests are defined, `ExUnit.Case.register_test/6` builds `%ExUnit.Test{}` structs and inserts them into the `:ex_unit_tests` module attribute of the case module. These structs contain useful contextual information, namely the aggregated and normalized test tags from the module, describe, and test level (as well as registered tags). These tags are very versatile and useful for confirmation -- I'm using them heavily in …
=> [ExUnit] Expose compile-time test and tag information

.github/workflows/builds.hex.pm.yml
The generated https://hexdocs.pm/elixir/docs_config.js is missing all tags.
I haven't tested this fix but seems like this could be the issue: https://github.com/actions/checkout#fetch-all-history-for-all-tags-and-branches
=> Fix generated docs_config.js on CI

lib/elixir/lib/kernel.ex
Add a missing `s` at the end of the word `functions`, in the documentation section on structural comparison.
The sentence becomes:
```
The functions in this module perform structural comparison.
```
=> Fix typo in Kernel/Structural-comparison docs

lib/elixir/lib/path.ex, lib/elixir/test/elixir/path_test.exs, lib/iex/test/iex/helpers_test.exs
The function already assumes there are no symlinks, so expanding dots does not add additional uncertainty.
=> Expand dots in relative_to and deprecate relative cwd

lib/elixir/lib/kernel/special_forms.ex
Fixes the failing tests on main due to an extra byte in the doctest assertion
=> Fix binary match UTF-16 doctest

lib/elixir/lib/path.ex, lib/elixir/test/elixir/path_test.exs, lib/iex/lib/iex/info.ex, lib/mix/lib/mix/utils.ex
Adds a `:force` option in `Path.relative_to` and `Path.relative_to_cwd` which allows up traversals.
`Path.relative_to` does not return proper relative paths in some cases. Some examples follow (also check the added tests):
```elixir
iex> Path.relative_to("foo", "foo/bar")
"foo" # wrong, implies ./foo/bar/foo - should be ../foo
iex> Path.relative_to("/usr/../usr", "/")
"usr/../usr"
iex> Path.relative_to("/usr", "/etc/..")
"/usr"
iex> Path.relative_to("/./etc/../usr", "/")
"./etc/../usr"
iex> Path.relative_to("/usr/foo/tmp", "/usr/foo/bar/buzz")
"/usr/foo/tmp" # Should be ../../tmp
```
By expanding first the two paths we can easily calculate the number of "cd ups" and construct a relative path. The only case for which an absolute path should be returned is when it is not possible to `mv` …
=> Support parent relative paths in Path.relative_to

lib/elixir/test/elixir/kernel/warning_test.exs
This pull request refactors the warning tests so that they'll be quoted with column information and assertions will take that into account.
=> Check columns by default on warnings tests

lib/elixir/test/elixir/kernel/warning_test.exs
Removes two test cases in `warnings_test.exs` that were not effective.
Closes #12648
=> Remove useless assertions in warnings_test

lib/ex_unit/lib/ex_unit/runner.ex, lib/ex_unit/test/ex_unit/callbacks_test.exs
=> mark test cases as invalid when an exit occurs during setup_all

.github/workflows/builds.hex.pm.yml
We need newer OTP so that we get nsis 3.08 (not 3.06)
=> Bump Ubuntu version for builds.hex.pm.yml

lib/elixir/test/elixir/kernel/warning_test.exs
Enables and asserts on columns for unused variable tests in `warning_tests.exs`
=> Enable column on unused variable test

lib/elixir/lib/macro/env.ex
I noticed that several functions within [`Macro.Env`](https://hexdocs.pm/elixir/1.15.0-rc.2/Macro.Env.html#summary) used default variable names (e.g. `map`) in the docs.
=> Name arguments in Macro.Env functions docs

lib/elixir/lib/module.ex
This PR updates the `@file` documentation and states that `@file` is only valid from within the expression block and its scope, not affecting module-level diagnostics.
=> Improve @file attribute docs

lib/elixir/lib/calendar/date.ex, lib/elixir/lib/calendar/datetime.ex, lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/lib/calendar/time.ex, lib/elixir/lib/code.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/macro.ex, lib/elixir/lib/macro/env.ex, lib/elixir/lib/module.ex, lib/elixir/lib/module/types/unify.ex, lib/mix/lib/mix/generator.ex, lib/mix/lib/mix/release.ex, lib/mix/lib/mix/task.ex
Many functions returning booleans are quoting them with backticks ([example](https://hexdocs.pm/elixir/Kernel.html#is_boolean/1)), but several cases didn't ([example](https://hexdocs.pm/elixir/Kernel.html#is_exception/1)).
=> Consistently use backticks when documenting boolean returns

lib/elixir/test/elixir/code_test.exs, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/kernel/parser_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs
This PR updates syntax and missing token errors tests to assert on the error message rather than it's format.
This is part of #12670
=> Assert on error message rather than format

lib/elixir/test/elixir/module/types/integration_test.exs
This pull request updates some tests that were asserting directly on the warning format to check only its content instead.
This is useful for the upcoming pull request that improves the visuals of the compiler warnings.
=> Assert on compiler warnings content rather than format

lib/iex/lib/iex/evaluator.ex, lib/iex/test/iex/interaction_test.exs
Similar to what happened on ex_unit on #12670, IEx is always printing exceptions as red and this conflicts with the the new exception's red ansi characters.
This pull request adds the same behavior of omitting the colors if we find an ansi reset in the formatted exception.
Before:
After:
I can also add a test for this if needed :)
=> Don't color IEx exception if it contains ANSI

bin/elixir, bin/elixir.bat, bin/iex, bin/iex.bat, lib/elixir/src/elixir.erl, lib/iex/lib/iex.ex, lib/iex/lib/iex/cli.ex
=> Fix dbg on Erlang/OTP 25-

Makefile
This change allows us to have `make test_ex_unit` for example, to run the formatting checks.
I think this is helpful since it allows us to fix formatting errors fast rather than fix a bunch of them later (or possibly pushing without running the entire suite and causing the CI to fail on formatting)
=> Check formatting when running tests for specific projects

lib/ex_unit/test/ex_unit/doc_test_test.exs
This PR allows us to assert on relative lines again in the doctest tests, making the tests less fragile to code being added/moved around.
=> Assert on relative lines in doctest tests

bin/elixir
Fixes: #12677
using printf here prevents an error when outputting the filtered flag `-e` as doing this with `echo "-e"` doesn't output anything (deleting the option we wanted to filter). 
This is explained here better than I ever could: https://unix.stackexchange.com/a/65819
=> Use printf instead of echo to output flags

lib/elixir/lib/code.ex, lib/elixir/src/elixir_errors.erl, lib/elixir/src/elixir_parser.yrl, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/kernel/parser_test.exs, lib/elixir/test/erlang/tokenizer_test.erl
Close https://github.com/elixir-lang/elixir/issues/12705
As discussed, an exception is made for one-letter sigils to prevent potential regressions, and since there is no risk of atom exhaustion for `26 * 2` possibilities.
=> Parser honors :static_atoms_encoder for multi-letter sigils

lib/elixir/lib/module/parallel_checker.ex, lib/elixir/test/elixir/kernel/diagnostics_test.exs, lib/elixir/test/elixir/module/types/integration_test.exs
Rewords grouped warnings message from `"Invalid call also found at"` to `"Similar warning found at"`.
=> Reword grouped warnings message

lib/elixir/lib/regex.ex
This mirrors the useful note in [`Regex.run/3`](https://hexdocs.pm/elixir/Regex.html#run/3) that would have saved me some confusion.
=> Mention where to find valid `on: capture` options in `Regex.split/{2..3}`.

lib/elixir/src/elixir_errors.erl
I noticed that we were building a list just in order to increment a counter, I wondered if a simple recursion wouldn't be better.
Feel free to close if you prefer the previous version.
=> Refactoring: use recursion instead of building list

lib/elixir/lib/exception.ex, lib/elixir/src/elixir_errors.erl, lib/elixir/test/elixir/kernel/diagnostics_test.exs, lib/iex/test/iex/interaction_test.exs
This pull request adds one more padding space to the error snippet when we're in single-digit line, so that it stays aligned with the stacktrace.
We go from this:
```
$ elixir -e "1 +* 2"
** (SyntaxError) invalid syntax found on nofile:1:4:
┌─ error: nofile:1:4
│
1 │ 1 +* 2
│    ^
│
syntax error before: '*'
(elixir 1.16.0-dev) lib/code.ex:542: Code.validated_eval_string/3
```
To this:
```
$ elixir -e "1 +* 2"
** (SyntaxError) invalid syntax found on nofile:1:4:
┌─ error: nofile:1:4
│
1 │ 1 +* 2
│    ^
│
syntax error before: '*'
(elixir 1.16.0-dev) lib/code.ex:542: Code.validated_eval_string/3
```
=> Align error snippet with stacktrace on single digit lines

lib/elixir/src/elixir_errors.erl
While implementing fancy error reporting for diagnostics, I've noticed when the line was zero, `do_get_file_line` would get stuck into infinite recursion. This PR just tweaks the base case to avoid this issue.
I also think we should not even try to read the file if the line number is zero, even if it is readable.
=> Fix infinite recursion in do_get_file_line

lib/elixir/lib/kernel.ex, lib/elixir/lib/kernel/utils.ex, lib/elixir/lib/macro/env.ex, lib/elixir/test/elixir/code_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs
This pull request fixes the diagnostic position that was being reported in the duplicate struct fields diagnostic.
Now we get the env from inside the defstruct macro and bring it to the IO.warn call
=> Report correct position for duplicate struct fields diagnostic

lib/ex_unit/lib/ex_unit/capture_server.ex, lib/ex_unit/test/ex_unit/capture_log_test.exs
Close https://github.com/elixir-lang/elixir/issues/12720
[`update_handler_config/3`](https://www.erlang.org/doc/man/logger.html#update_handler_config-3)seems to work but I'm not sure if there is a need for a more involved fix, and if this might create issues when used concurrently with different options?
=> Always respect options passed to capture_log

lib/elixir/lib/file.ex
Updates the `File.ls` documentation to mention that directories are included in the result list.
The text inspired by the documentation of `:file.list_dir` that we use: https://www.erlang.org/doc/man/file.html#list_dir-1
I've also thought about adding an example of listing only non-directory files by using `File.ls |> Enum.reject(&File.is_dir?/1)` but I think we don't need that much here. 
Closes #12731
=> Improve File.ls/1 docs

lib/mix/lib/mix/tasks/release.ex, lib/mix/lib/mix/tasks/release.init.ex
On UNIX, `$@` was already available in `env.sh`. This patch adds similar capability for `env.bat`.
For a more complete example, users can:
```sh
export MYAPP_ARGS="$@"
```
and then:
```elixir
def start(_type, _args) do
if args = System.get_env("MYAPP_ARGS") do
args
|> OptionParser.split()
|> # ...
end
end
```
Parsing command-line arguments in Elixir is not ideal given various escaping rules and whitespace handling so depending on their needs, users might instead leave this up to the shell:
```sh
i=1
export MYAPP_ARGC=$#
for arg; do
export "MYAPP_ARG$i"="$arg"
i=$((i + 1))
done
```
```elixir
def start(_type, _args) do
if argc = System.get_env("MYAPP_ARGC") do
for i <- 1..System.to_integer(argc) do
System.fetch_env!("MYAPP_ARG#{i}")
end
end
end
```
=> Pass `%*` to `env.bat` and document accordingly

lib/elixir/lib/exception.ex
In particular, for `FunctionClauseError` and `UndefinedFunctionError` for now.
I think this could be extended to other exceptions as well, but this just kicks off the discussion.
cc @sabiwara
=> Make some fields of exceptions public

lib/elixir/lib/code.ex
Clarification following this [discussion](https://github.com/elixir-lang/elixir/issues/12276#issuecomment-1616246865).
Alternatively, since it seems a fairly common use case, I wonder if a `rescue: true` option wouldn't improve the ergonomics here?
=> Clarify that Code.with_diagnostics/2 does not rescue

lib/elixir/pages/anti-patterns/what-anti-patterns.md
I have updated the presentation file for the anti-patterns section (what-anti-patterns.md). Basically, I added a link to our full paper published in EMSE instead of the link to the slides of our short paper. Additionally, I fixed the broken link to the original repository.
=> Updated links to original paper and repository

lib/elixir/pages/meta-programming/domain-specific-languages.md, lib/elixir/pages/meta-programming/macros.md, lib/elixir/pages/meta-programming/quote-and-unquote.md, lib/elixir/scripts/elixir_docs.exs
As discussed with @josevalim and team.
This PR only moves the guides *as is*, without changes to the content of the guides themselves. I only removed the `---` YAML comments from the top of those files. This is so we don't have to review the files themselves 👍 
This is part of #12747.
=> Move meta-programming guide here from elixir-lang.org

lib/elixir/pages/anti-patterns/design-anti-patterns.md, lib/elixir/pages/anti-patterns/process-anti-patterns.md
This is what we generally use in Elixir, so I think we should do it in the anti-patterns guides too.
cc @lucasvegi
=> Indent some Markdown guides

lib/elixir/pages/anti-patterns/code-anti-patterns.md
@josevalim would you be open to mentioning the pattern (that I always use 😬) of doing `_five_min = 60 * 5`, to essentially replicate named arguments and stuff like that? I think it might make sense in this section.
=> Add "Comments" anti-pattern to the guides

man/mix.1
A minor change proposes adding space between text and reference to be more compliant with citation style.
=> Add unbreakable space when citing on the man page

lib/elixir/pages/anti-patterns/process-anti-patterns.md
As this anti-pattern was a 'generalization' of Agent Obsession, I left a note mentioning it to preserve the history of this smell. This way, the results of our research on the prevalence and relevance of this anti-pattern can also assist the developers here.
=> "Scattered process interfaces" (Anti-pattern documentation)

lib/elixir/pages/meta-programming/domain-specific-languages.md
Since the first sentence is an intro to the DSLs and is a general outline, I recommend having a slightly more rigorous definition of DSLs.
Therefore, I took a one-sentence definition from the following paper, one of the most important research papers in the field:
Mernik, M., Heering, J., & Sloane, A. M. (2005). When and how to develop domain-specific languages. ACM computing surveys (CSUR), 37(4), 316-344
=> Revise the description of DSLs

lib/mix/lib/mix.ex
There are cases when starting installed apps manually is more optimal
=> Allow to opt out of starting apps in Mix.install

lib/elixir/src/elixir_env.erl, lib/elixir/src/elixir_fn.erl, lib/elixir/test/elixir/kernel/warning_test.exs
Instead of expanding `&1` as `{:x1, _, :elixir_fn}`, we'll expand it in the default context with the name `&1`:
```elixir
{:"&1", _, nil}
```
Close https://github.com/elixir-lang/elixir/issues/12612
Commit [Rewrite test depending on current line](https://github.com/elixir-lang/elixir/commit/270d72365c84f7e64711c2e19febb18953ba9690) fixed a test that was really annoying to keep up to date 🙂
=> Expand captured args with regular context

lib/iex/test/iex/helpers_test.exs
Unfortunately a previous commit  8bc67d384b0c21d9bbc7145829ecd49e128038b3 was not enough to fully address #12741. Here is a followup which completely fixes this issue. 
Here is an error log of the issue which addresses this patch:
```
..................................................................................................
1) test pid/1,3 builds a PID from integers (IEx.HelpersTest)
test/iex/helpers_test.exs:1383
* 1st argument: not a textual representation of a pid
code: assert inspect(pid(0, 32767, 3276)) == "#PID<0.32767.3276>"
stacktrace:
:erlang.list_to_pid(~c"<0.32767.3276>")
(iex 1.15.2) lib/iex/helpers.ex:1358: IEx.Helpers.pid/3
test/iex/helpers_test.exs:1384: (test)
...
2) test pid/1,3 builds a PID from string …
```
=> Use PID valid for 32-bit systems, followup to #12741

lib/elixir/pages/references/syntax-reference.md
I don't think this syntax rule was documented in the syntax reference, although it is rejected by the compiler in practice. Would it be a good idea to mention it?
I think there might be value in it especially since this is different from many languages like python or javascript.
Also wonder if we could improve the error messages. This one is nice:
But this one might be confusing:
=> Document whitespace rules for keyword syntax

lib/elixir/pages/references/operators.md, lib/elixir/pages/references/patterns-and-guards.md
There's some ambiguity about the word `inequal`, so I suggest replacing it with the stricter `not equal`
=> Fix typos and unclosed brackets

lib/elixir/lib/regex.ex, lib/elixir/pages/references/compatibility-and-deprecations.md
This addresses:
- #12785
Pending questions:
=> Clarify upgrade path for `Regex.regex?` (#12785)

lib/elixir/lib/range.ex
Add missing typespec for [`Range.size`](https://hexdocs.pm/elixir/1.12/Range.html#size/1)
=> Add typespec for Range.size

lib/elixir/lib/supervisor.ex
We don't have a type for something that can be started or passed to `Supervisor.child_spec/2`, which is what this PR introduces.
The name is 100% up for discussion. 😄 
I didn't include `:supervisor.child_spec()` in the typespec because `Supervisor.child_spec/2` doesn't accept the old tuple format, so it would have to have its own typespec. I think this is a fairly good compromise.
=> Add Supervisor.module_spec/0 type

lib/iex/lib/iex/introspection.ex
Close https://github.com/elixir-lang/elixir/issues/12796
This fixes the issue, I'm not sure if this should/could be fixed upstream in `Code.fetch_docs` but will have a look.
=> Remove erlang doc duplicates in IEx

lib/ex_unit/lib/ex_unit/case_template.ex
=> Fix typo in documentation by removing duplicated `async: true` option

lib/elixir/lib/io.ex
Fix newlines in documentation for IO module. Tested the visual change by copy-pasting the paragraph before/after the fix into `Earmark.as_html(text)`, then making a screenshot of the rendered HTML.
Before:
After:
=> Fix newlines in io.ex

lib/iex/lib/iex/introspection.ex, lib/iex/test/iex/helpers_test.exs
Sorry this should have been done in https://github.com/elixir-lang/elixir/pull/12803, I spent some more time cleaning up afterwards.
Mostly:
- `t` for a single type would be fetching the docs at least twice, possibly more (`get_docs` was called in a loop) => fetch once
- error handling wasn't done for non-existing types and functions
Before
After
=> Cleanup erlang shell docs

lib/elixir/lib/task/supervisor.ex
It's mentioned in docs to Task.async_stream/5, but not here.
=> Mention :zip_input_on_exit in Task.Supervisor too

lib/elixir/lib/kernel.ex
'Perform' doesn't make sense here. I think 'performant' is what the author meant.
=> Change word 'perform' to 'performant' - kernel.ex
