lib/elixir/lib/calendar/datetime.ex, lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/test/elixir/calendar/datetime_test.exs, lib/elixir/test/elixir/calendar/naive_datetime_test.exs
Fixes #12818 
Also add error messages to `DateTime.diff`, `DateTime.add`, `NaiveDateTime.add` and cover error messages with tests.
=> Fix supported time units

lib/elixir/pages/getting-started/lists-and-tuples.md
Currently the guide says
> One very common use case for tuples is to use them to return extra information from a function.
but I find it does not explicitly say why.
Hopefully this change makes it clearer. I'm an Elixir beginner, so the explanation may be wrong though :)
=> Explain why functions returns extra information with tuples

lib/elixir/lib/code/fragment.ex, lib/elixir/test/elixir/code_fragment_test.exs
Close #12829
It was actually a missing `?` in the range, so `?( = 40` was in `?0..9 = 48..9` 😅
=> Fix bug in surround_context alias handling

lib/elixir/lib/kernel/special_forms.ex
In the documentation for the _with_ special form, examples of area function take a _map_ argument, but fetch from an undefined _opts_. Subsequent examples in the with section use _opts_, so I've corrected the functions to take the _opts_ argument.
=> fix examples in with documentation

lib/elixir/src/elixir_def.erl, lib/elixir/test/elixir/kernel/overridable_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs, lib/elixir/test/elixir/kernel_test.exs
Closes #12812
~This works, but I am not sure why Check needed to be `false` in the first place.
Therefore I am not sure what side effect it can have, although tests are passing.
The fix might need to be somewhere else, maybe around [here](https://github.com/elixir-lang/elixir/blob/main/lib/elixir/lib/kernel.ex#L5202-L5206), but I would need more pointers.~
Edit: New approach: warn for unused funs/macros/defaults disregarding of having unquotes, keep disabling other warnings (`late_function_head`, `ungrouped_arity`...)
=> Warn on unused defp/defmacrop using unquote/1

lib/elixir/test/elixir/module_test.exs
Very occasionally (less than 1 in 10 runs?), I'm seeing an error log when running tests:
There's probably a race condition on a global flag, this test being `async`?
Note: Because I can't reproduce it consistently, it is hard to confirm that my fix works 🙃
=> Avoid error log in test

lib/elixir/lib/string.ex, lib/elixir/test/elixir/range_test.exs, lib/elixir/test/elixir/string_test.exs
In 4 out of 10 times, I'm getting the following warnings:
This PR captures and asserts these (they weren't tested yet).
=> Capture negative step slice warnings in tests

lib/elixir/lib/io/ansi.ex, lib/elixir/test/elixir/io/ansi_test.exs
If `enabled` is set to `true` an invalid ANSI sequence will raise an `ArgumentError`. On the other hand if `enabled` is set to `false` no error is raised and the sequence is silently ignored.
This can lead to inconsistent behaviours for CLI commands based on a configuration setting. Additionally since in tests a common pattern is to disable ANSI sequences you may have successful tests but exceptions when executing the code in production with enabled ANSI sequences.
=> consistently raise in case of invalid ANSI sequences in `IO.ANSI.format`

lib/elixir/lib/code/fragment.ex, lib/elixir/test/elixir/code_fragment_test.exs
Sorry, I realized that in https://github.com/elixir-lang/elixir/pull/12846 I forgot to handle spaces (e.g. `fun . (`).
=> Fragment handle anonymous calls with extra spaces

lib/elixir/lib/exception.ex, lib/elixir/test/elixir/exception_test.exs
This PR improves the error messages when a module is correctly spelled, but has mis-cased letters.
We will now get error messages like
```elixir
iex(1)> ENum.map([1, 2, 3], & &1 + 1)
09:39:24.348 [error] beam/beam_load.c(180): Error loading module 'Elixir.ENum':
module name in object code is 'Elixir.Enum'
09:39:24.355 [error] beam/beam_load.c(180): Error loading module 'Elixir.ENum':
module name in object code is 'Elixir.Enum'
** (UndefinedFunctionError) function ENum.map/2 is undefined (module ENum is not available). Did you mean:
* Enum.map/2
ENum.map([1, 2, 3], #Function<42.125776118/1 in :erl_eval.expr/6>)
iex:1: (file)
```
I saw two experienced developers who are new to Elixir get stuck on this issue on the same day, not including a mention on Twitter!
[Twitter …
=> Improve UndefinedFunctionError for mis-cased module

lib/elixir/lib/calendar/datetime.ex
I answered a question about converting from local to UTC in Elixir Slack and thought it might be nice to have a brief example at the top of the docs here.
=> Quick examples of timetime shifts

lib/elixir/lib/macro/env.ex, lib/elixir/pages/getting-started/binaries-strings-and-charlists.md
=> Fixed code that was not verified by the linter 

lib/elixir/pages/mix-and-otp/dynamic-supervisor.md
With Elixir version 1.15, to use `:observer.start()` in combination with iex, it is necessary to manually add the needed dependencies.
The needed dependencies are already mentioned in the "getting started" guide. This PR copies the note from there to the "mix guide" as requested in [an issue at another repository](https://github.com/elixir-lang/elixir-lang.github.com/issues/1712#issue-1848760461).
The same PR is opened in the repository `elixir-lang/elixir-lang.github.com` (https://github.com/elixir-lang/elixir-lang.github.com/pull/1713).
=> Harmonize note about needed dependencies for observer.

lib/elixir/lib/exception.ex, lib/elixir/test/elixir/exception_test.exs
This PR builds off of #12839, handling the case where a developer forgets to alias a module, resulting in UndefinedFunctionError.
Imagine we have the following modules in our Elixir program.
```elixir
def MyAppWeb.Context.Event do
def foo, do: :bar
end
def MyAppWeb.OtherContext.Event do
def foo, do: :bar
end
```
If the developer attempts to reference this module, but forgets to type the alias, they will now get module suggestions like.
```elixir
** (UndefinedFunctionError) function Event.foo/0 is undefined (module Event is not available). Did you mean:
* MyAppWeb.Context.Event.foo/0
* MyAppWeb.OtherContext.Event.foo/0
Event.foo()
iex:4: (file)
```
**TODO**
=> Improve UndefinedFunctionError for unqualified module

lib/elixir/src/elixir_def.erl, lib/elixir/src/elixir_overridable.erl
This fixes an oversight when I changed the type of `CheckClauses` from a boolean to `all | none | unused_only` in 
https://github.com/elixir-lang/elixir/pull/12832, but forgot to update one call site in `elixir_overridable`.
`false` was de facto behaving as `unused_only` since would fail both the `== none` and `== all` checks.
Added a guard too to prevent the propagation of this kind of error.
=> Fix unused function warning with overridables

lib/elixir/lib/code/fragment.ex, lib/elixir/test/elixir/code_fragment_test.exs
=> Fix `Code.Fragment.surround_context/2` for submodules of non-aliases

lib/elixir/lib/gen_server.ex
`eror` => `error` in mermaid graph on line 168.
=> Typo in gen_server.ex docs

lib/elixir/lib/inspect.ex, lib/elixir/test/elixir/inspect_test.exs
Removes extra backslash using normalize function, although it assumes that `\#` and `#` are equivalent regular expressions in Erlang.
```elixir
iex> ~R/#{2,}/
~r/\#{2,}/
iex> ~r/\#{2,}/
~r/\#{2,}/
iex> ~R/\#{2,}/
~r/\#{2,}/
```
Closes #12901.
=> Fix regex inspect for escaped hash

man/elixir.1.in, man/mix.1
Pull request proposes a minor update of two man-pages (Elixir & Mix), where I added a link to the Hex package manager. Several programming languages have their package manager mentioned on the man page; hence, I believe that Elixir should also have this.
=> Update man page with package manager

lib/elixir/lib/access.ex, lib/elixir/test/elixir/access_test.exs
Based on [this mailing list thread](https://groups.google.com/g/elixir-lang-core/c/nN6w-PkvK9s/m/Txzw9pmPAQAJ), adds `Access.at/2` which supports a default value in case the index does not exist.
=> Add Access.at/2

lib/mix/lib/mix/tasks/format.ex
The text was true at some point, but now the code is always compiled
before running the formatter if formatter.exs includes plugins, so
it doesn't apply anymore.
=> Fix remark in mix format docs

lib/elixir/src/elixir_tokenizer.erl
This will allow us to use this information when building more detailed error messages about mismatched delimiters, allowing us to have access to both start and ending tokens' positions.
=> Save column information on start delimiter tokens

lib/elixir/lib/exception.ex, lib/elixir/src/elixir.erl, lib/elixir/src/elixir_errors.erl, lib/elixir/src/elixir_interpolation.erl, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/src/elixir_tokenizer.hrl, lib/elixir/test/elixir/kernel/parser_test.exs, lib/elixir/test/erlang/string_test.erl, lib/elixir/test/erlang/tokenizer_test.erl, lib/iex/test/iex/interaction_test.exs
This PR adds a new exception, MismatchedDelimiterError, that will contain necessary information such as start and end position so that we can build nice-looking error messages with it.
The only thing I'm not very happy with my implementation is the way we're passing the start and end information from the tokenizer (reusing existing {line, column} structure), so I'm open to suggestions here
=> Add MistmatchedDelimiterError

lib/elixir/lib/code/typespec.ex
The guards for these functions were already allowing binaries, which allows either a file name or a binary containing the BEAM object code to be passed in. The specs, however, only specified `module`. (Note that `fetch_types/1` already specified `module | binary`.)
=> Fix spec in `Code.Typespec.fetch_types/1` and `fetch_callbacks/1`

lib/elixir/lib/exception.ex, lib/elixir/src/elixir_errors.erl, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/kernel/diagnostics_test.exs, lib/elixir/test/elixir/kernel/parser_test.exs, lib/iex/test/iex/interaction_test.exs
This PR uses the `start` and `end` information contained in tokens to show a more precise message on mismatched delimiters error.
I'm opening it as a draft since there's still some tests missing implementations and I'll refactor the implementation a bit before fully opening for review.
@josevalim would you mind taking a look at the test cases and giving some feedback?
=> Improve mismatched delimiter message

lib/elixir/pages/references/operators.md
The operators has been deprecated.
Reverts elixir-lang/elixir#12932
=> Revert "Add `<|>` to the list of parsable but unused operators"

lib/elixir/src/elixir_errors.erl, lib/elixir/test/elixir/kernel/diagnostics_test.exs
Fixes crash in `iolist_to_binary` if source code contains unicode char, now treats it as unicode
=> Unicode support for mismatched delimiter errors

lib/elixir/lib/calendar/naive_datetime.ex
The field actually has an underscore.
=> docs: `NaiveDateTime` - fix reference to `DateTime.time_zone`

lib/elixir/src/elixir_env.erl, lib/elixir/src/elixir_errors.erl, lib/elixir/src/elixir_expand.erl, lib/elixir/test/elixir/kernel/diagnostics_test.exs
This PR adds a span that highlights variables when showing printing errors/warnings.
Q: I think we'll have to set the `:columns` parser option to `true` by default, right? @josevalim
Otherwise there will be no columns for us to actually show errors like this
I haven't dived into the undefined local function call yet, but I believe if we get its AST the algorithm would be finding the token with the biggest line number and column and treat it as the ending, and then we use its position as the span. If the span ending line is greater than our current line, we just highlight from `start_column` to the end of line, wdyt?
=> Add span to unused/undefined variable diagnostics

lib/elixir/scripts/windows_installer/installer.nsi
1. If we couldn't verify installed OTP, don't quit but let user proceed with installing just Elixir
2. When checking installed OTPs, pick the recent most installed. Previously we were picking the first one which was basically guaranteed to be too old.
3. If we find an existing Elixir installation but it doesn't match the OTP version, offer to download the OTP version this Elixir installer was compiled against (which usually would be the newer version)
4. Add "Verify Erlang/OTP" button which re-checks for installed OTP.
Closes #12678.
=> Improve Windows Installer

lib/elixir/src/elixir_expand.erl, lib/elixir/src/elixir_rewrite.erl, lib/elixir/test/elixir/kernel/expansion_test.exs
Simplify emitted erlang AST for signed numbers following discussions in https://github.com/elixir-lang/elixir/pull/12949.
Before, `-1` would be:
- `{:integer, _, -1}` in matches
- `{:op, _, :-, {:integer, _, 1}}` otherwise
With this PR:
- `{:integer, _, -1}`, always
=> Always rewrite signed numbers during expansion

lib/elixir/test/erlang/control_test.erl
```sh
lib/elixir/test/erlang/control_test.erl:17:43: Warning: matching on the float 0.0 will no longer also match -0.0 in OTP 27. If you specifically intend to match 0.0 alone, write +0.0 instead.
%   17|     [{clause, _, [{op, _, '+', {float, _, 0.0}}], [], [{atom, _, pos}]},
%     |                                           ^
lib/elixir/test/erlang/control_test.erl:18:43: Warning: matching on the float 0.0 will no longer also match -0.0 in OTP 27. If you specifically intend to match 0.0 alone, write +0.0 instead.
%   18|      {clause, _, [{op, _, '-', {float, _, 0.0}}], [], [{atom, _, neg}]}]
%     |
```
=> Fix OTP 26.1 warning in tests

lib/elixir/test/elixir/kernel/parser_test.exs
Found these sigil-related assertions that were commented on the multi-char sigil PR, they still pass, so I guess this should be fine
=> Uncomment assertions in test

lib/elixir/lib/module/types.ex, lib/elixir/src/elixir_errors.erl, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/kernel/parser_test.exs, lib/elixir/test/elixir/module/types/types_test.exs, lib/iex/test/iex/interaction_test.exs
Updates two error messages that were relying on the previous format to do some indentation
We shouldn't update the tests here because they already don't assert on the errors specific formatting.
```
** (SyntaxError) invalid syntax found on aaaaa.ex:7:1:
error: unexpected reserved word: end
HINT: the "end" on line 3 may not have a matching "do" defined before it (based on indentation)
│
7 │ end
│ ^
│
└─ aaaaa.ex:7:1
(elixir 1.16.0-dev) lib/code.ex:1463: Code.require_file/2
```
```
** (SyntaxError) invalid syntax found on aaaaa.ex:7:1:
error: unexpected reserved word: end
HINT: the "end" on line 3 may not have a matching "do" defined before it (based on indentation)
│
7 │ end
│ ^
│
└─ aaaaa.ex:7:1
(elixir 1.16.0-dev) lib/code.ex:1463: Code.require_file/2
```
=> Update indentantion on "HINT" labels

lib/elixir/lib/macro.ex
In https://github.com/elixir-lang/elixir/pull/12972, I realized the doc is actually inaccurate.
=> Improve Macro.path/2 docs

lib/elixir/pages/cheatsheets/enum-cheat.cheatmd
Been reading the docs and came across a minor typo - this PR fixes it.
=> Fix typo in the Enum cheatsheet

lib/elixir/pages/getting-started/protocols.md
A small edit on the "Deriving" section of the "Protocols" chapter in "Getting Started".
Changing "we should be fine with the implementation of Any" to
"should we be fine with the implementation of any" hopefully
better communicates that we can use the Any implementation of
the protocol if we wish to but not that we have to.
=> Clarify Any Protocol implementation derivation

lib/elixir/lib/exception.ex
This should prevent Dialyzer from reporting `no_return` errors for `format_stacktrace/0`
=> Fix Exception.format_stacktrace/1 spec

lib/elixir/lib/exception.ex
From this function's documentation:
> The arity may also be a list of arguments.
Called with a list of args at https://github.com/elixir-lang/elixir/blob/a19140a479a3a263fa4769b58aa7c7bffd01da25/lib/elixir/lib/exception.ex#L447 and https://github.com/elixir-lang/elixir/blob/a19140a479a3a263fa4769b58aa7c7bffd01da25/lib/ex_unit/lib/ex_unit/formatter.ex#L223
=> Fix Exception.format_mfa spec again

lib/elixir/pages/anti-patterns/code-anti-patterns.md
I was prompted to add a new anti-pattern, which I see as a specialization of "speculative assumptions". However, I was already not the biggest fan of speculative assumptions, because I don't think the "speculative assumption" is the intent of the developer. Most of the times, it is rather that the developer writes a code in a non-assertive style, which becomes an anti-pattern. So I have renamed "speculative assumptions" to "non-assertive patterns". We could also call it "Broad patterns" or "Loose patterns". The new anti-pattern is called "non-assertive truthiness", but it may be called "Broad truthiness" or "Loose truthiness".
Thoughts?
/cc @lucasvegi @whatyouhide
=> New anti-pattern

lib/ex_unit/lib/ex_unit/filters.ex
The parse_kv function always gets called with a binary second argument, from line 139.
This function clause was kept after refactoring in https://github.com/elixir-lang/elixir/commit/4971af9fc9848b3c8e081a62f586014eda23f446
=> Clean up unreachable function clause in  ex_unit/filters.ex

lib/elixir/lib/task/supervisor.ex
This pull request adds a note to Task.Supervisor documentation regarding the `:shutdown` option requiring any spawned tasks to be trapping exits for the timeout value to have an effect.
I have personally seen users be confused about this (myself included), as the current phrasing can make it sound like the Task.Supervisor would somehow be responsible for keeping the Tasks alive, while in reality the Tasks need to also trap the exits for the timeout value to have an observable effect.
Aside from my anecdotal evidence, I found at least https://elixirforum.com/t/task-supervisor-and-sigterm/49920 being puzzled about the same thing.
While it can be fair to say that knowledge of processes and exit signals would be prerequisite information to effectively use Task.Supervisor, I feel like this …
=> Document need of Tasks to trap exits for Task.Supervisor :shutdown to have effect

lib/elixir/lib/module/types/behaviour.ex, lib/elixir/test/elixir/kernel/warning_test.exs
Close https://github.com/elixir-lang/elixir/issues/12841
The first commit improves the [message for the remaining warning](https://github.com/elixir-lang/elixir/pull/13006/commits/eeb5652d128d291178aaefa55dec9528e3be2f03#diff-d617989cbb2ccf2d27a606096a66a4d23c05640a477f3b835f287c442353f83bR1382)
=> Fix warnings on conflicting callbacks

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel/alias_test.exs
Attempt at fixing https://github.com/elixir-lang/elixir/issues/12456 
@josevalim is this the kind of fix you had in mind?
It might be a bit hacky but fixes it for now, opening the PR to move the discussion forward.
=> Fix overriding with Elixir. prefixed defmodule

lib/elixir/pages/anti-patterns/code-anti-patterns.md
hey there, first PR so sorry if it's no good.
I'm guessing from the proposed substitution of `&&/2` with `and/2` that this `or` should have been `and`
=> fix typo in code-smells/non-assertive truthiness documentation

lib/elixir/pages/getting-started/basic-types.md, lib/elixir/pages/mix-and-otp/task-and-gen-tcp.md
`is an a float` → `is a float`
`valuesare`     → `values are`
`specificatio`  → `specification`
=> Fix typos in elixir/pages/

lib/elixir/lib/io/ansi/docs.ex, lib/elixir/test/elixir/io/ansi/docs_test.exs, lib/iex/lib/iex/introspection.ex
Update `IEx.introspection.print_doc/5` to trasverse the list of headings and split each heading into multiple headings, in case the heading has any newline characters (`\n`). This fixes an issue where using the `h` macro with some functions ended up with a broken output for the function signature, as the padding done by `IO.ANSI.Docs.print_headings/2` does not take into consideration the fact the the headings can contain newline characters, and thus end up in multiple lines.
Here's a before and after comparison of running `h dbg` in `iex`:
=> Fix IEx doc printing for headings with newline characters

lib/elixir/pages/anti-patterns/code-anti-patterns.md, lib/elixir/pages/anti-patterns/design-anti-patterns.md, lib/elixir/pages/anti-patterns/process-anti-patterns.md
I really appreciate these anti-pattern docs, thank you!
=> Fix typos in anti-patterns documentation

lib/elixir/lib/calendar/datetime.ex
Two small things I noticed while scouring the docs. Please disregard or adjust as needed, or let me know if there is anything I can do to improve the change.
=> Fix text in DateTime.add/4 docs

lib/elixir/lib/enum.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/map.ex, lib/elixir/lib/option_parser.ex, lib/elixir/lib/supervisor/spec.ex, lib/elixir/src/elixir_clauses.erl, lib/elixir/test/elixir/kernel/expansion_test.exs
The word *duplicated* isn't wrong but *duplicate* sounds better in these cases. :+1:
=> Change the word "duplicated" to "duplicate"

lib/elixir/lib/code/fragment.ex
I don't know how to reproduce it but I've seen this stacktrace
```
an exception was raised:
** (CaseClauseError) no case clause matching: :none
(elixir 1.15.6) <REDACTED: user-file-path>:408: Code.Fragment.dot_3
(elixir 1.15.6) <REDACTED: user-file-path>:629: Code.Fragment.position_surround_context_4
(elixir 1.15.6) <REDACTED: user-file-path>:604: Code.Fragment.surround_context_3
```
Looking at https://github.com/elixir-lang/elixir/blob/927b10df80ee1c1c7396e68efe00d06bc3e80420/lib/elixir/lib/code/fragment.ex#L408, only `operator` can return `:none` and it seems a mistake as other branches return `{:none, 0}`
=> Fix crash in surround_context

lib/elixir/lib/module.ex
Taken from this list:
https://www.erlang.org/doc/man/dialyzer.html#type-warn_option
Fixes #13036
=> Add missing dialyzer attributes

lib/elixir/lib/gen_server.ex
This check is now done in OTP directly: https://github.com/erlang/otp/pull/5008
Relates to https://github.com/elixir-lang/elixir/issues/11220
Note: I wasn't sure about the clause in stop/3, but I fear this would make it a breaking change (cf this [branch](https://github.com/elixir-lang/elixir/compare/main...sabiwara:remove-call-self-2?expand=1))
=> Remove calling_self clause in GenServer

lib/elixir/lib/float.ex, lib/elixir/lib/inspect.ex, lib/elixir/lib/list/chars.ex, lib/elixir/lib/string/chars.ex
Relates to #11220
Did a quick prop-based sanity check just to make sure there is no unexpected change in behavior / edge case:
```elixir
iex> for f <- StreamData.float(), Float.to_string(f) != :erlang.float_to_binary(f, [:short]), do: throw f
```
=> Use :erlang.float_to_binary/2 in Float.to_string/1

lib/elixir/pages/cheatsheets/enum-cheat.cheatmd
Fix typo related to `Enum.slide/3` in the Enum cheatsheet:
`["apple", "banana", "orange", "pear", "grape", ] `-> `["apple", "banana", "orange", "pear", "grape"]`
=> Fix typo related to Enum.slide/3 in the Enum cheatsheet

lib/mix/lib/mix/utils.ex
Relates to https://github.com/elixir-lang/elixir/issues/11220
Hope I didn't misunderstood "Use new system certificates" and the TODO, feel free to close if that's the case.
Note: [`:httpc.ssl_verify_host_options/1`](https://www.erlang.org/doc/man/httpc#ssl_verify_host_options-1) is available from 25.1, which would imply 1.17 compatibility is from OTP 25.1, not 25 (is this a showstopper?).
=> Always use system certificates

lib/elixir/pages/anti-patterns/design-anti-patterns.md
I have seen this in many tools/plugins
=> Additional remarks for application config anti-pattern

lib/elixir/lib/gen_server.ex
Restores graph removed in f5a61d1, with correct request -> reply arrow ordering.
Jose mentioned fixing it on the forum thread (https://elixirforum.com/t/elixir-v1-16-0-rc-0-released/59386/8), but after building it I noticed the removal commit. Not sure if it was removed due to the "bug" or because the graph was not wanted any more.
I do not believe its possible to get the client nodes on the same "level", so this may not be appropriate to merge anyway.
```mermaid
graph BT
C(Client #3) ~~~ B(Client #2) ~~~ A(Client #1)
A & B & C -->|request| GenServer
GenServer -.->|reply| A & B & C
```
I actually think this would be better read in the inverse also, but again, the different "levels" for the clients is problematic.
```mermaid
graph TB
C(Client #3) ~~~ B(Client #2) ~~~ A(Client #1)
A & B & C …
```
=> Restore GenServer introduction mermaid graph

lib/elixir/lib/path.ex
This PR addresses `File.Error` being raised if `File.cwd` returns an error or `nil`. We do not need to read cwd with already absolute paths and when called with relative_to argument
The current behavior results in crashes with error messages such as:
```
** (File.Error) could not get current working directory nil: no such file or directory
(elixir 1.13.4) <REDACTED: user-file-path>:1503: File.cwd!/0
(elixir 1.13.4) <REDACTED: user-file-path>:162: Path.expand/1
```
=> Lazily evaluate File.cwd! in Path.expand and Path.absname

lib/mix/lib/mix/local/installer.ex, lib/mix/lib/mix/tasks/archive.install.ex, lib/mix/lib/mix/tasks/escript.install.ex, lib/mix/test/mix/local/installer_test.exs
```
mix archive.install github phoenixframework/phoenix --sparse installer
```
Didn't test escript but it should be identical to archive install
=> Support --sparse in archive.install and escript.install

lib/logger/lib/logger.ex
Hey there 👋🏾 
Logger metadata accepts also a map. It looks like it's not documented.
i.e.
```elixir
Logger.info("this is a info message", %{something: :reported, this: :info})
```
This PR tries to improve the documentation.
NOTE: If the map case is accidentally covered please let me know and I'll just close the PR. Thanks!
=> Update logger documentation

lib/elixir/lib/path.ex
Add a doctest to `Path.absname/2` using the new lazy path signature introduced in https://github.com/elixir-lang/elixir/pull/13061.
I figured examples might be helpful for people who are not so familiar with specs.
=> Add doctest for absname with lazy path

lib/elixir/pages/getting-started/enumerable-and-streams.md
Fix typo in Getting Started - Enumerables and Streams docs:
```diff
- The Enum and Stream modules provide a wide-range functions but know all of them at heart.
+ The Enum and Stream modules provide a wide range of functions, but you don't have to know all of them by heart.
```
=> Fix typo in "Getting Started - Enumerables and Streams" docs

lib/elixir/lib/code.ex, lib/elixir/lib/code/typespec.ex, lib/iex/lib/iex/helpers.ex, lib/iex/lib/iex/info.ex
`:beam_lib.info/1` returns `{:error, :beam_lib, info_rsn()}` on error
```
an exception was raised:
** (FunctionClauseError) no function clause matching in Keyword.fetch/2
(elixir 1.15.4) <REDACTED: user-file-path>:571: Keyword.fetch({:error, :beam_lib, {:not_a_beam_file, ""}}, :module)
(elixir 1.15.4) <REDACTED: user-file-path>:2032: Code.get_beam_and_path/1
(elixir 1.15.4) <REDACTED: user-file-path>:1994: Code.fetch_docs/1
```
=> Fix crashes when :beam_lib.info(beam) returns error

lib/elixir/lib/kernel/special_forms.ex
Update the docs to reinforce that we only operate on "matching messages" and explicitly call out that unmatched messages remain in the mailbox.
=> Clarify receive docs for unmatched messages

lib/elixir/pages/getting-started/basic-types.md
Fixing a typo in [Getting Started – Identifying functions and documentation](https://hexdocs.pm/elixir/1.16/basic-types.html#identifying-functions-and-documentation).
`Before we move on to the next data type, let's talk about how Elixir identity functions.`
-->
`Before we move on to the next data type, let's talk about how Elixir identifies functions.`
=> Fix typo in getting-started guide

lib/elixir/lib/string.ex
See: https://github.com/elixir-lang/elixir/pull/13090#discussion_r1388543874
=> Use `in/2` in `String.replace_invalid/2` guards

lib/mix/lib/mix/tasks/help.ex, lib/mix/test/mix/tasks/help_test.exs
This is an initial draft MR for discussing some details on the [proposal](https://groups.google.com/g/elixir-lang-core/c/_TC7KMJgajw)
This first commit pretty prints the output of `mix help ALIAS` (tests need to be updated)
Sample `mix.exs`:
```elixir
defp aliases do
[
an_alias: [&hello/1, "deps.get --only #{Mix.env()}", "compile"],
another_alias: [
"format --check-formatted priv/hello1.exs",
"cmd priv/world.sh",
fn _ -> Mix.Task.reenable("format") end,
"format --check-formatted priv/hello2.exs"
]
]
end
```
**Current output** 
**Formatted output**
We could also pretty print the alias in a single line but I personally don't like it for lengthy aliases.
How should we handle functions? Is the current way they are formatted ok?
=> Pretty print alias definition in mix help

lib/mix/lib/mix/scm/git.ex, lib/mix/test/mix/scm/git_test.exs
When using git dependencies, a branch/ref/tag specifier is passed verbatim to `System.cmd/3`. This can lead to intimidating error messages when they are not provided as a binary (for instance, an atom like `tag: :stable`):
```
** (ArgumentError) all arguments for System.cmd/3 must be binaries
(elixir 1.15.6) lib/system.ex:1083: System.cmd/3
(mix 1.15.6) lib/mix/scm/git.ex:287: Mix.SCM.Git.git!/2
(mix 1.15.6) lib/mix/scm/git.ex:136: Mix.SCM.Git.checkout/2
(elixir 1.15.6) lib/file.ex:1624: File.cd!/2
(mix 1.15.6) lib/mix/dep/fetcher.ex:64: Mix.Dep.Fetcher.do_fetch/3
(mix 1.15.6) lib/mix/dep/converger.ex:229: Mix.Dep.Converger.all/8
(mix 1.15.6) lib/mix/dep/converger.ex:162: Mix.Dep.Converger.init_all/8
(mix 1.15.6) lib/mix/dep/converger.ex:110: Mix.Dep.Converger.all/4
```
This PR adds a …
=> Produce better error messages for non-binary mix git deps refspecs.

lib/elixir/pages/getting-started/keywords-and-maps.md, lib/elixir/pages/mix-and-otp/distributed-tasks.md, lib/elixir/pages/mix-and-otp/genservers.md, lib/elixir/pages/references/syntax-reference.md
=> Fix links references

lib/iex/lib/iex/autocomplete.ex
Some of the expansion has to be use the current shell environment
-->
Some of the expansion has to use the current shell environment
=> Fix typo/wording in @doc for expand

lib/elixir/lib/kernel.ex, lib/elixir/src/elixir_bitstring.erl, lib/elixir/test/elixir/kernel/binary_test.exs
Close https://github.com/elixir-lang/elixir/issues/13089
=> Auto infer size of matched variable in bitstrings

lib/elixir/lib/code/formatter.ex, lib/elixir/test/elixir/code_formatter/containers_test.exs
Close https://github.com/elixir-lang/elixir/issues/13103
=> Formatter keeps quotes in atom keys

lib/elixir/pages/getting-started/case-cond-and-if.md
Fix a broken link to the "Guards" section of the "Patterns and Guards" references page.
The link is from the "Case, Cond and If" getting-started page.
=> Fix a broken link to the "Guards" section

lib/elixir/lib/config.ex
ExDoc main emitted these warnings on Elixir main:
```
warning: documentation references module "Mix.Config" but it is hidden
│
49 │   `Mix.Config`, which was specific to Mix and has been deprecated.
│   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
│
└─ lib/elixir/lib/config.ex:49: Config (module)
warning: documentation references module "Mix.Config" but it is hidden
│
51 │   You can leverage `Config` instead of `Mix.Config` in three steps. The first
│   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
│
└─ lib/elixir/lib/config.ex:51: Config (module)
```
Another idea to solve it is to set `skip_code_autolink_to: ["Mix.Config"]`.
=> Update `Mix.Config` mentions

lib/mix/lib/mix/task.ex
ExDoc main emitted the following warning on Elixir main:
```
warning: documentation references function "Mix.CLI.preferred_cli_env/1" but it is hidden
│
1 │ defmodule Mix.Task do
│ ~~~~~~~~~~~~~~~~~~~~~
│
└─ (mix 1.17.0-dev) lib/mix/lib/mix/task.ex:1: Mix.Task.preferred_cli_env/1
```
and the warning was pointing to the wrong location. Not sure if it's worth addressing but here's what happened: `defdelegate` without explicit `@doc` adds the `@doc "See <delegating_to>"` however here we're delegating to a module with `@moduledoc false` hence the warning.
I decided to just update the docs. At some point I imagine this function would become a `@doc false` anyway.
Before:
After:
=> Update Mix.Task.preferred_cli_env/1 docs

lib/elixir/lib/calendar/time.ex
Since spec tells that `Time.add` support `:hour` and `:minute`:
```elixir
@spec add(Calendar.time(), integer(), :hour | :minute | System.time_unit()) :: t()
```
But actual message is:
```elixir
Time.add(Time.utc_now(), 2, :minutes)
** (ArgumentError) unsupported time unit. Expected :second, :millisecond, :microsecond, :nanosecond, or a positive integer, got :minutes
```
After fix:
```elixir
Time.add(Time.utc_now(), 2, :minutes)
** (ArgumentError) unsupported time unit. Expected :hour, :minute, :second, :millisecond, :microsecond, :nanosecond, or a positive integer, got :minutes
=> Update Time.add message about units

lib/elixir/lib/calendar/time.ex, lib/elixir/test/elixir/calendar/time_test.exs
Before this fix the test fails because the code runs through `System.convert_time_unit/3` into `System.normalize_time_unit/1`.
```sh
1) test add/2 (TimeTest)
lib/elixir/test/elixir/calendar/time_test.exs:94
Wrong message for ArgumentError
expected:
~r/Expected :hour, :minute, :second/
actual:
"unsupported time unit. Expected :second, :millisecond, :microsecond, :nanosecond, or a positive integer, got 0"
code: assert_raise ArgumentError, ~r/Expected :hour, :minute, :second/, fn ->
stacktrace:
lib/elixir/test/elixir/calendar/time_test.exs:99: (test)
```
=> Raise in Time.add/3 for non-positive integer

lib/ex_unit/lib/ex_unit/formatter.ex
These functions are public but they don't have specs. We should decide what to do with the `formatter_callback` type I introduced. The arguments it takes are not really documented, so we should write up some docs on that? Thoughts?
=> Add some specs and types to ExUnit.Formatter

lib/elixir/lib/path.ex
Currently the documentation renders incorrectly in https://hexdocs.pm/elixir/Path.html#wildcard/2
=> Properly escape `\` in Path.wildcard docs

lib/ex_unit/lib/ex_unit/formatter.ex
=> Add callback docs to ExUnit.Formatter

lib/logger/lib/logger.ex, lib/logger/test/logger_test.exs
This PR adds `Logger.levels/0`, which returns all the available levels of Logger.
It's useful when checking the levels provided by a user.
---
Edit: Is it possible to backport it to 1.16? Or, we have to wait a few month to use it in a stable version. (1.16 is in the RC state, I'm not sure if merging new features is allowed.)
=> Add Logger.levels/0

lib/elixir/pages/getting-started/lists-and-tuples.md
`String.split/2` is mentioned, but `String.split/1` is actually used in the example.
=> Update arity of String.split

lib/elixir/lib/option_parser.ex
When handling unknown switches, results of `OptionParser.parse/2` depend on whether the supplied switches already exist as atoms.
This PR adds examples to aid developer expectations about this fact.
N.B. The PR is split into 5 commits to aid readability, but can be squashed before merging.
=> Enrich option parser docs for unknown switches

lib/elixir/scripts/windows_installer/installer.nsi
We don't need this right now but it could be useful in the future, if anything to detect if Elixir was installed using this installer.
Demo:
iex> {:ok, r} = :win32reg.open([:read])
iex> :win32reg.change_key(r, ~c"\\hklm\\software\\wow6432node\\elixir\\elixir")
iex> :win32reg.value(r, ~c"installroot")
{:ok, ~c"C:\\Program Files\\Elixir"}
=> Update Windows installer to write Elixir install root to registry

lib/elixir/lib/regex.ex
for example:
```elixir
r = ~r/a[^
b
]d/x
Regex.match?(r, "a\nd")
```
=> clarify treatment of whitespace in extended regexes

lib/mix/lib/mix/tasks/deps.clean.ex
Removes the hard fail when removing files for `deps.clean` and logs the errors
```shell
../elixir/bin/elixir ../elixir/bin/mix deps.clean --all
* Cleaning bunt
warning: errors occurred while deleting files for dependency: bunt 
file: /home/daven/Documents/personal_projects/thousand_island/deps/bunt, reason: permission denied
* Cleaning credo
warning: errors occurred while deleting files for dependency: credo 
file: /home/daven/Documents/personal_projects/thousand_island/deps/credo, reason: permission denied
* Cleaning dialyxir
warning: errors occurred while deleting files for dependency: dialyxir 
file: /home/daven/Documents/personal_projects/thousand_island/deps/dialyxir, reason: permission denied
* Cleaning earmark_parser
warning: errors occurred while deleting files for dependency: …
```
=> Add warning when deps clean fails

lib/elixir/lib/task.ex
First, as always, thanks to y'all for elixir and all your great work on it :green_heart: I'm truly happy to be a part of this community where discussion & contributions are always welcome, where we (well, more y'all) push the boundaries of what was previously thought possible and somehow it all happens without breaking things all the time :rocket: 
The `Task` module is one of the coolest modules in elixir and is probably the first contact and experience of a lot of beginners with parallelism in elixir. I hence find it worthwhile to warn about the memory copying and its impacts here as it might easily lead to unwelcome results, so it's worth pointing out.
This is only a first draft, not sure if this is the best place to put it - feedback very welcome.
Honestly `Task.async`/`Task.await` may …
=> Mention dangers around `Task` and sending a lot of data along

CHANGELOG.md
:wave: Me again, but as always thanks for all your fantastic work! :green_heart: 
Kudos go to @sabiwara, full log/discussion at: https://github.com/bencheeorg/benchee/issues/406
As best as I learned this was introduced in #11420 and fixed in aabe465
It shouldn't affect almost anyone except for scripting usage of elixir and (probably most notably) benchee benchmarks that don't call functions in a module.
I think this warrants a Changelog entry. Not sure if [Compiler] is right and my entry is probably way too wordy - happy to adjust it.
I'll also write up a notice at benchee and potentially a blog post so that people can know to potentially redo benchmarks they ran on 1.14-1.15 by either wrapping the functions or the `Benchee.run` invocation in modules or running on an unaffected Elixir …
=> Mention the fixed regression

lib/elixir/lib/exception.ex, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/kernel/diagnostics_test.exs, lib/elixir/test/elixir/kernel/parser_test.exs
'expected """"" ' looks a bit odd, but I'm open to ideas on how we handle it (if needed)
perhaps using single quotes or only 'expected """ ' like at the top
=> Improve diagnostics for unclosed heredocs

lib/elixir/lib/port.ex
Before in the docs the port number seems to be `0.1444` but in the last example it jumped to `0.1464` which I think is a small error or something I don't understand :)
Thanks for everything as always! :green_heart:
=> Fix the port number in the port docs

lib/elixir/pages/anti-patterns/process-anti-patterns.md
As per usual, thanks to all of ya for your great work!
Follow up to/extension of #13173
First draft, happy to adjust and extend it in many ways. I had trouble coming up with a simple example as we needed a bunch of data to make sure it's not good. I could have employed the first anti pattern myself and did repeated statistics calculation, but that'd have been worse :sweat-smile:
I remembered José's comment around sending along the `conn` and figured it's central enough in elixir to not throw anyone off.
If someone has a better example, happy to redo it!
Thanks y'all! :green-heart:
=> Document the process anti pattern of sending large data

lib/elixir/pages/anti-patterns/code-anti-patterns.md
Function clauses in the example are in reversed order.
=> Fix example in non-assertive map access antipattern

lib/elixir/pages/anti-patterns/process-anti-patterns.md
While going through the new anti-patterns docs I found this small typo
=> Fix typo in docs: `Keywoird` -> `Keyword`

lib/elixir/pages/anti-patterns/code-anti-patterns.md, lib/elixir/pages/anti-patterns/design-anti-patterns.md, lib/elixir/pages/anti-patterns/macro-anti-patterns.md
This PR **a)** fixes some small typos and **b)** makes some subtle tweaks to the language in the anti-pattern docs in the name of brevity and (I hope) greater clarity.
=> Fix typos and tweak language in anti-pattern docs

lib/elixir/pages/getting-started/binaries-strings-and-charlists.md
I was reading the docs, and I found something odd. By checking this [commit](https://github.com/elixir-lang/elixir/pull/12850/commits/3c3e3d3f12dd2a5763520738578dd8145345f9b0), I believe the author wanted to say _force_ istead of _for_.
=> Fix typo in charlists documentation

lib/elixir/pages/anti-patterns/code-anti-patterns.md
I noticed a typo in an explanatory comment in one of the refactoring examples in the Code Anti-Patterns doc. This fixes that.
=> Code anti patterns typo fix

lib/ex_unit/lib/ex_unit/assertions.ex
I verified that `assert_receive` originally took `100` as the default value for `timeout`, and the documentation has remained unchanged since then.
https://github.com/elixir-lang/elixir/blob/fe96d709ad87515ecfa6c3580a8745c44902857d/lib/ex_unit/lib/ex_unit/assertions.ex#L234
=> Improve docs for assert_receive/3

lib/elixir/lib/module/types/descr.ex, lib/elixir/src/elixir_compiler.erl, lib/elixir/test/elixir/module/types/descr_test.exs
The bitmap represents all non-divisible types.
Currently it implements all types in our system,
but atoms, lists, tuples, maps, and functions
will be given more precise types later on.
Dynamic has not been yet implemented nor a
optimizations for term.
=> Add bitmask types to descr

lib/elixir/pages/references/patterns-and-guards.md
Spotted a remaining single-quote charlist in the[ Pattern matching reference](https://hexdocs.pm/elixir/1.16.0/patterns-and-guards.html#lists)
=> Replace single quotes in charlist in doc

lib/elixir/lib/code/normalizer.ex, lib/elixir/test/elixir/code_normalizer/quoted_ast_test.exs
Closes https://github.com/elixir-lang/elixir/issues/13248
I'm not 100% confident with the fix, it might have unwanted side effects in cases I didn't consider.
The idea is to prevent entering the special cases for `:do` keys if we're inside an operand, so I moved the `allow_keyword?` check up.
=> Fix Code.Normalizer for keyword operand with :do key

lib/elixir/pages/anti-patterns/process-anti-patterns.md
The description incorrectly states that both processes are initialized with 0, while in the code the second process receives a non-default initial value.
=> Process anti-patterns: fix the explanation to match the explained code example

lib/elixir/pages/anti-patterns/macro-anti-patterns.md
=> Macro anti-patterns: fix incorrect error message in code examples

lib/elixir/lib/application.ex, lib/mix/lib/mix.ex, lib/mix/lib/mix/state.ex, lib/mix/lib/mix/tasks/run.ex
Spotted while reading code and docs.
=> docs: minor wording and typo fixes

lib/elixir/lib/task/supervisor.ex
Hi!
I spent some time struggling trying to implement something relatively simple with `Task.async_stream`/  `Task.Supervisor.async_stream_nolink`, did many experiments, until I realized it was due to a misunderstanding and that I could actually solve it simply.
In my previous mental model, `Task.Supervisor.async_stream_nolink` meant "fire and forget" without a mean to cleanup dangling tasks if I wanted to bail on the first error. I didn't realize these tasks were cleaned up by an extra monitor when the stream halted, making it perfectly suited for my needs without any need to hack.
This PR is an attempt to clarify this behavior in the doc, and leave a couple of recipes which I think can be very useful for daily tasks and understanding.
Another idea could be to simplify this common use …
=> Document the behavior of async_stream_nolink

lib/elixir/lib/code.ex
`:beam_lib.chunks/2` can return more error codes, see https://www.erlang.org/doc/man/beam_lib#chunks-2
https://www.erlang.org/doc/man/beam_lib#type-chnk_rsn
=> Fix `CaseClauseError` in `Code.fetch_docs`

lib/mix/lib/mix/dep/loader.ex, lib/mix/test/mix/tasks/deps_test.exs
I was playing with `MIX_EXS` and noticed that error messages coming from `mix dep.*` tasks where still mentioning `mix.exs` instead of the custom mixfile.
The problem being that `from` field in `Mix.Dep` structs didn't consider custom mixfiles apparently.
Does this change make sense?
=> fix: correct mixfile path on error messages when custom MIX_EXS

lib/elixir/pages/getting-started/debugging.md, lib/mix/lib/mix/tasks/profile.cprof.ex, lib/mix/lib/mix/tasks/profile.eprof.ex, lib/mix/lib/mix/tasks/profile.fprof.ex
Improve navigability of profile-related docs by adding clickable links to:
- https://hexdocs.pm/elixir/debugging.html#other-tools-and-community
- https://hexdocs.pm/mix/Mix.Tasks.Profile.Eprof.html
- https://hexdocs.pm/mix/Mix.Tasks.Profile.Cprof.html
- https://hexdocs.pm/mix/Mix.Tasks.Profile.Fprof.html
=> Make c/e/fprof clickable links in doc

lib/elixir/pages/getting-started/basic-types.md
There is a missing exclamation mark from the result of the `"hello #{string}!"` interpolation.
=> Fix string interpolation example in basic-types.md

lib/ex_unit/lib/ex_unit.ex, lib/ex_unit/lib/ex_unit/callbacks.ex, lib/ex_unit/lib/ex_unit/on_exit_handler/supervisor.ex, lib/ex_unit/test/ex_unit/supervised_test.exs
=> Integrate `start_supervised` supervisor with :$caller

lib/elixir/lib/protocol.ex, lib/elixir/scripts/elixir_docs.exs, lib/elixir/test/elixir/protocol_test.exs
=> Default `defimpl` to `@moduledoc false`

lib/elixir/pages/getting-started/basic-types.md
I thought that it might be useful to explicitly call out this difference between Elixir and some other programming languages. The difference caught me off guard when I started writing a few simple functions in Elixir.
=> Add explicit clarification that values like 0 and "" are truthy in Elixir

lib/elixir/src/elixir_clauses.erl, lib/elixir/src/elixir_erl_pass.erl
As discussed in https://github.com/elixir-lang/elixir/issues/6738.
A nice side-effect is that we are able to remove a bunch of `generated` except from the `raise` clause.
The compiler and dialyzer should be able to track actual issues without false positives.
=> Translate with/1 as a closure

lib/elixir/lib/task.ex, lib/elixir/lib/task/supervised.ex, lib/elixir/lib/task/supervisor.ex, lib/elixir/test/elixir/task/supervisor_test.exs, lib/elixir/test/elixir/task_test.exs
This is a proposal for discussion.
Working with `async_stream*` functions can be a bit error prone and requires to constantly double check the doc (which often needs to jump to a separate function), since any typo in an option would fail either silently or much later down the lane when a timeout/exception happens.
The proposal is to validate these upfront instead of lazily, and with helpful error messages.
I also plan to add a dedicated type `t:Task.async_stream_options/1` following [this pattern](https://hexdocs.pm/elixir/1.16.0/GenServer.html#t:option/0), which could help check the spec in the IDE more easily. Thoughts?
=> Validate options in async_stream* functions

lib/iex/lib/iex/helpers.ex
I thought it would be useful to bring over the `c` helper for debugging purposes.  We already have `n`, so I figured why not also have `c`.   This is my first contribution to Elixir, so please let me know if I missed anything.  Thanks!
=> Add `c` alias to `IEx.Helpers`

lib/elixir/pages/references/typespecs.md
I noticed that I couldn't see `{...}` in the table of literals that are supported in type specifications. I did not know what that shorthand signified, so I tried it in a test spec: `@spec foo({...}) :: integer()`. But that results in an error:
> ... in typespecs is only allowed inside lists, as in [term(), ...], or inside functions, as in (... -> term())Elixir
That makes me think that `{...}` is possibly not a valid shorthand value, hence this speculative PR to remove mention of it :)
=> Remove mention of {...} as a shorthand in type specifications

lib/elixir/src/elixir_parser.yrl, lib/elixir/test/elixir/kernel/tracers_test.exs
Currently, the `:from_brackets` metadata seems to only be populated when used against a literal map or keyword list or a function call (`Foo.bar()[:baz]`).
This populates it in all cases, which includes variables `foo[:bar]` and module attributes `@foo[:bar]`, as well as adding tests for tracing the hidden `Access.get/2` function, similar to the `Kernel.string/1` function as with interpolation.
=> Include from_brackets metadata in all cases

lib/elixir/lib/kernel.ex
The error message for `var <> "suffix" =` hasn't been updated following the [support of pinned variables on the left-handside operand](https://github.com/elixir-lang/elixir/pull/13106).
```elixir
** (ArgumentError) the left argument of <> operator inside a match should always be a literal binary because its size can't be verified. Got: var
```
Updated message:
```elixir
** (ArgumentError) the left argument of <> operator inside a match should always be either a literal binary or an existing variable matched with the pin operator (such as ^some_var) because its size can't be verified. Got: var
```
Based the phrasing on the similar error following `%{var => 1} = 1`
```elixir
error: cannot use variable var as map key inside a pattern. Map keys in patterns can only be literals (such as atoms, …
```
=> Update argument error message when matching with <>

lib/elixir/lib/system.ex, lib/elixir/test/elixir/system_test.exs
`System.shell` returns an error for an empty string:
```elixir
iex(3)> System.shell("")
/bin/sh: -c: line 1: syntax error near unexpected token `)'
/bin/sh: -c: line 1: `)'
{"", 2}
```
With the fix in this PR:
```elixir
iex(1)> System.shell("")
{"", 0}
iex(2)> System.shell("   ")
{"", 0}
```
=> Handle empty string in System.shell

lib/iex/lib/iex/history.ex, lib/iex/test/iex/helpers_test.exs
Makes the pruning update the history size. Without this update, the size didn't reflect the actual length of the history, which caused the error message to return non-sensical values as the upper limit of the history.
=> Fix bug in iex history

lib/elixir/lib/node.ex
Node.spawn/5 should refer to :erlang.spawn_opt/5
=> Update node.ex doc link

lib/iex/lib/iex/history.ex, lib/iex/test/iex/helpers_test.exs
My previous PR (#13333) caused a regression:
Since now `size` represents the actual size of the history, the condition in this prune clause would make the pruning stop too early, causing unbounded growth of the history.
Additionally, there was an off-by-one error, also fixed by adjusting the formula.
=> Fix unbounded growth in iex history

lib/elixir/lib/module/types/descr.ex, lib/elixir/test/elixir/module/types/descr_test.exs
The last bit was unused, and unless I misunderstood, is causing bugs:
- building types up by `union` would always generate even numbers like `4094`
- building types down by `difference` would lead to odd numbers like `4095`
```elixir
iex> Enum.reduce([integer(), float(), binary(), map(), non_empty_list(), empty_list(), tuple(), fun(), pid(), port(), reference()], &union/2)
%{bitmap: 4094}
iex> difference(term(), atom())
%{bitmap: 4095}
```
These would generate the same representations but wouldn't be `equal?`  in https://github.com/elixir-lang/elixir/pull/13330:
```elixir
iex> Descr.to_quoted_string(%{bitmap: 4094}) == Descr.to_quoted_string(%{bitmap: 4095})
true
```
After the fix:
```elixir
iex> Enum.reduce([integer(), float(), binary(), map(), non_empty_list(), empty_list(), tuple(), …
```
=> Fix bit offset in Module.Types.Descr

lib/iex/lib/iex/history.ex, lib/iex/test/iex/helpers_test.exs
This is not related to #13333 or #13336, but to a bug that already existed for a while and was reported in Elixir's slack by @axelson.
Existing behaviour:
```
v0idpwn:~/oss/elixir$ iex
Erlang/OTP 26 [erts-14.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit:ns]
Interactive Elixir (1.15.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 1
1
iex(2)> 2
2
iex(3)> 3
3
iex(4)> Process.exit(self(), :hi)
** (EXIT from #PID<0.110.0>) shell process exited with reason: :hi
Interactive Elixir (1.15.4) - press Ctrl+C to exit (type h() ENTER for help)
iex(4)> 4
4
iex(5)> v(-1)
** (RuntimeError) v(-1) is out of bounds, the currently preserved history ranges from 4 to 5 (or use negative numbers to look from the end)
(iex 1.15.4) lib/iex/history.ex:58: IEx.History.nth/2
(iex …
```
=> Fix bug in negative lookups in v/1

lib/elixir/lib/module/types/descr.ex, lib/elixir/test/elixir/module/types/descr_test.exs
Implement the representation for set-theoretic gradual types, including `dynamic()`.
This is done by adding a field `:dynamic` to the descr. It points to another descr representing the "dynamic component" of the type, while the rest of the descr is the "static component". The set operations are modified to account for that.
`dynamic()` is the descr `%{dynamic: @term}`: it can hold for any type at runtime, but its static component is empty since there is no type it is guaranteed to produce.
More explanations are in the comments!
=> Add gradual types to descr

lib/elixir/lib/kernel/parallel_compiler.ex, lib/elixir/src/elixir_code_server.erl, lib/elixir/src/elixir_compiler.erl
The compiler freezing is mostly caused a bug upstream,
but it may be speed up compilation to avoid purging as
we compile, as purging blocks the code server.
Closes #13264.
=> Do not purge compiler modules during compilation, only after

lib/elixir/lib/enum.ex, lib/elixir/lib/float.ex, lib/elixir/lib/inspect.ex, lib/elixir/lib/map.ex, lib/elixir/lib/registry.ex, lib/elixir/test/elixir/enum_test.exs, lib/elixir/test/elixir/float_test.exs
This PR fixes most of the small breakage in the CI due to the `-0.0` change and non-deterministic order of keys.
There is still a breaking test for `Registry`, and I haven't looked into `IEx`/`mix` etc yet, will look into it later.
=> Fixes to support 0TP27

lib/ex_unit/lib/ex_unit/diff.ex, lib/ex_unit/test/ex_unit/diff_test.exs
Take these two tests:
```elixir
test "correctly colored" do
assert [{:foo}] = [{:bar}]
end
test "incorrectly colored" do
val = [{:foo}]
assert ^val = [{:bar}]
end
```
When diffing the match without a pin, `diff_value/3` would be passed the quoted version of `[{:foo}]` (`[{:{}, [], [:foo]}]`) as the left argument, allowing it to recurse deeper into the structure to find the correct diff.
When diffing the match with the pin, `diff_value/3` would be passed `[{:foo}]` instead, prohibiting it from recursively refining the diff, leading to overly broad diffs. The fix is to explicitly escape the pin value in the call to `diff_value/3` inside of `diff_pin/3`.
This fixes #13348
=> ExUnit.Diff: Escape pinned values when computing diff

lib/ex_unit/test/ex_unit/capture_io_test.exs
Most likely due to this change
https://github.com/erlang/otp/commit/be9c343f7188f5845c8e2f31a614e4d257452abf
=> Fix assertion for ex_unit test in OTP27

lib/elixir/pages/getting-started/binaries-strings-and-charlists.md
The bitstring constructor syntax reference [`<<>>`](https://hexdocs.pm/elixir/1.16.1/Kernel.SpecialForms.html#%3C%3C%3E%3E/1) isn't easy for newcomers to discover. It's not SEO friendly and the [getting started guide for bitstrings](https://hexdocs.pm/elixir/binaries-strings-and-charlists.html#bitstrings) doesn't indicate that subtle link's the full reference.
The old getting started guide on [elixir-lang.org](http://web.archive.org/web/20230216152522/https://elixir-lang.org/getting-started/binaries-strings-and-char-lists.html#bitstrings) called out to it in plain English, and I think it's worth adding back in some form.
I've added it back in this PR at the bottom of the bitstring section in bold, in addition to removing the `/1` from the `<<>>/1` link at the top.
_My impetus for this …
=> Add callout to full bitstring reference in the getting started guide.

lib/ex_unit/lib/ex_unit/doc_test.ex
`MapSet`s are no longer inspected as `#MapSet<[:foo, :bar]>` since [expression-based inspection](https://hexdocs.pm/elixir/1.14/changelog.html#expression-based-inspection-and-inspect-improvements) has been introduced.
- This is also true for `Version.Requirement` and most "pure" data structs (either a sigil, raw representation or expression-based)
- Functions, pids or refs are not convenient to illustrate this point having a non-deterministic representation
- `HashSet` & co are deprecated
The only exploitable example I could find would be non-UTC `DateTime`s, but open to better suggestions if any.
=> Fix doctest example since Inspect.MapSet changed

lib/elixir/lib/exception.ex, lib/iex/test/iex/helpers_test.exs
I noticed the required callbacks of `Exception` behaviour were not documented with `@doc`. The relevant documentation was only on `defexception` which made it inaccessible via `Code.fetch_docs(Exception)`
=> Add documentation to `Exception` callbacks

lib/elixir/lib/string.ex, lib/elixir/src/elixir_utils.erl, lib/elixir/test/elixir/string_test.exs
Close https://github.com/elixir-lang/elixir/issues/13349
Copies the implementation of https://github.com/erlang/otp/pull/7879
=> Use Erlang's implementation of jaro distance, fix bugs

lib/iex/lib/iex/helpers.ex
Not sure about functions like [nl](https://hexdocs.pm/iex/1.16.1/IEx.Helpers.html#nl/2) or [l](https://hexdocs.pm/iex/1.16.1/IEx.Helpers.html#l/1), do they need a specs 🤔
=> Add some specs to `IEx.Helpers`

lib/elixir/lib/enum.ex, lib/elixir/lib/stream.ex
Document in words and doctest how `Enum.zip` can be used to create a keyword list.
=> document using Enum.zip to create a keyword list

lib/ex_unit/lib/ex_unit/capture_io.ex, lib/ex_unit/test/ex_unit/capture_io_test.exs
`capture_io/1,2,3` does not capture IO from a process that was already started. This change allows someone to pass a `:pid` option so that `Process.group_leader/2` is called on the target process rather than the calling process.
=> Support IO capture from an already-started process

lib/iex/lib/iex/helpers.ex, lib/mix/lib/mix.ex, lib/mix/test/mix_test.exs
Extends `IEx.Helpers.recompile/0` to work with `Mix.install/2`. Specifically, it there are mix-installed local dependencies, those get recompiled.
=> Support recompiling local Mix.install/2 dependencies

lib/iex/lib/iex/helpers.ex, lib/mix/lib/mix.ex, lib/mix/test/mix_test.exs
After calling `Mix.install/2`, one may retrieve the installation directory with `Mix.install_project_dir/0` and then use the MIX_INSTALL_RESTORE_PROJECT_DIR environment variable in another session as a starting point for a different `Mix.install/2`.
Implementation-wise we copy the restore dir contents, do the installation, then remove files for the dependencies that are not used.
=> Add environment variable for reusing Mix.install/2 installation

lib/ex_unit/lib/ex_unit/callbacks.ex
`start_link_supervised!` is missing from the paragraph that lists all the callbacks and functions implemented by `ExUnit.Callbacks`. I thought it would be nice to add it there since it's the only one missing.
=> Update ExUnit.Callbacks docs to reference `start_link_supervised!`

lib/elixir/lib/enum.ex
Had a student not really get the rem(x, 2) == 0 example and also not realize it could return none or all, or even that you could use the function pattern matching.
=> Add more examples to the enum filter

lib/mix/lib/mix.ex
Otherwise `Mix.State.get/1` raises.
=> Ensure install-related functions do not crash when Mix is not started

lib/logger/lib/logger/translator.ex
OTP27 introduces a new `:process_label` key between `:registered_name` and `:error_info` (https://github.com/erlang/otp/pull/7720), breaking the pattern-matching on the keyword-list:
This PR just fixes the CI, but doesn't do anything with the label. We could maybe display it if `!= :undefined`?
=> Logger handles :process_label from OTP27

lib/elixir/lib/protocol.ex, lib/elixir/test/elixir/protocol/consolidation_test.exs, lib/iex/test/iex/helpers_test.exs
Not 100% sure, should we do this replacement following https://github.com/erlang/otp/pull/8091?
=> Replace deprecated :code.lib_dir/2 usages

lib/elixir/test/elixir/code_test.exs, lib/elixir/test/elixir/kernel/cli_test.exs, lib/ex_unit/test/ex_unit/capture_io_test.exs
Following this [suggestion](https://github.com/elixir-lang/elixir/pull/13396#discussion_r1514005612) from @whatyouhide.
(I'm never sure which one to use and tend to check existing code for consistency, this will avoid me propagating the old pattern 😄)
=> Use System.otp_release/0 in tests for consistency

lib/ex_unit/lib/ex_unit.ex, lib/ex_unit/lib/ex_unit/runner.ex, lib/ex_unit/lib/ex_unit/server.ex, lib/ex_unit/mix.exs, lib/ex_unit/test/ex_unit_test.exs, lib/mix/lib/mix/tasks/test.ex
The world isn't perfect and so are our tests. When debugging flaky tests I found myself wanting to run `mix test` repeatedly until a test fails. Of course you can do a loop in bash, fish, etc., but a lot of time is spent on starting the BEAM and the application.
This is where this PR comes in. It proposes a new flag `--repeat-until-failure` that re-runs all tests until at least one fails.
=> add --repeat-until-failure to mix test

lib/elixir/pages/getting-started/try-catch-and-rescue.md
Currently, in the [try, catch, and rescue docs](https://hexdocs.pm/elixir/try-catch-and-rescue.html#fail-fast-let-it-crash) the phrase 'something unexpected' renders as 'something _unexpected'.
See screenshot:
=> Fix typo: remove stray '_' from front of 'unexpected'

lib/mix/lib/mix/project.ex
Believe the backticks on `use`s, should just be uses.
=> Fix Project docs Markdown - incorrect backticks

lib/elixir/lib/process.ex, lib/elixir/test/elixir/process_test.exs
I'm open to reworking this completely, but I wanted to propose making the OTP 27.0 `:proc_lib.set_label/1` functionality easy to use.
I think we can make a lot of observability and error reporting clearer if we can start using these labels in a lot of places.
Example of effect: https://github.com/mtrudel/bandit/pull/319
=> Wrap :proc_lib label functionality

lib/elixir/lib/module/types/descr.ex, lib/elixir/lib/module/types/of.ex, lib/elixir/test/elixir/module/types/descr_test.exs
This relation checks if the input given to a function/operator is a compatible subtype of its expected type, that is, if they coincide at runtime and there are no static values in the input that cannot be covered by the expected type at runtime.
If this relation is not validated, then a warning should be produced as either:
- the input type is statically known to produce values that will never be covered in the expected type
e.g., `integer() or tuple()` is not a consistent subtype of `dynamic() and tuple()`, and we can blame the input type for containing integers
- OR none of the unknown values that may be given as inputs at runtime will ever be covered in the expected type 
e.g., `dynamic() and atom()` is not a consistent subtype of `dynamic() and tuple()` 
More examples:
`dynamic() and …
=> Add compatibility relation for gradual typechecking

lib/elixir/lib/task/supervised.ex, lib/elixir/test/elixir/task_test.exs, lib/logger/lib/logger/translator.ex, lib/logger/test/logger/translator_test.exs
https://github.com/elixir-lang/elixir/pull/13394#issuecomment-1989602688
@josevalim is this the right approach?
If yes will handle other reports in a similar fashion (GenServer, gen_event...)
=> Log :$process_label in Task crash report

lib/ex_unit/lib/ex_unit/callbacks.ex, lib/ex_unit/test/ex_unit/case_test.exs
This is a proposal following https://github.com/elixir-lang/elixir/issues/13414 to improve the discoverability.
~~Note: the suite is flaky right now as the test seems to be interfering with other exunit tests, this is just a draft to discuss the proposal.~~
=> Warn when using @tag outside of describe

lib/elixir/lib/macro/env.ex
type `Macro.meta()` does not exist
=> Fix expand_import and expand_require specs

lib/elixir/lib/keyword.ex
Since [Enum module has this type](https://hexdocs.pm/elixir/1.16.2/Enum.html#t:default/0) and Keyword module has more than two functions which operates default values.
=> Add default type to Keyword module

lib/mix/lib/mix/tasks/xref.ex, lib/mix/test/mix/tasks/xref_test.exs
I think it is the same issue as https://github.com/elixir-lang/elixir/pull/13351/files#r1491807968
Arbitrary order mentioned in [doc](https://erlang.org/documentation/doc-15.0-rc1/lib/stdlib-6.0/doc/html/digraph_utils.html#cyclic_strong_components/1).
Fixes a failing test on OTP27.
=> Fix mix xref order across OTP versions (OTP 27)

.github/workflows/ci.yml, lib/iex/test/iex/helpers_test.exs
Approach discussed [here](https://github.com/elixir-lang/elixir/pull/13352#issuecomment-2012640055): skip the tests blocked by the `:shell_docs` change for now and add OTP27 to the CI.
The issue for the TODO has been added here: https://github.com/elixir-lang/elixir/issues/13438.
=> Add OTP 27.0-rc2 to CI

lib/elixir/pages/getting-started/basic-types.md
This commit improves the readability of a sentence in the basic-types section of the Elixir documentation.
=> Improve readability of documentation

lib/elixir/src/elixir_erl_pass.erl
Close https://github.com/elixir-lang/elixir/issues/13446
Fixes both:
```elixir
with {:ok, contents} <- File.read(path),
{:ok, result} <- {:ok, String.trim(contents)} do
{:ok, result}
end
```
```elixir
with {:ok, contents} <- File.read(path),
{:ok, result} <- {:ok, String.trim(contents)} do
{:ok, result}
else
error -> {:error, error}
end
```
=> Mark with/1 internal clauses as generates

lib/elixir/pages/references/naming-conventions.md
let's official-ize the following conventions:
- get, fetch, fetch!
- compare/2
=> adds more expected naming conventions to the list

lib/elixir/lib/uri.ex, lib/elixir/test/elixir/uri_test.exs
Resolves #13462
When a url string is schema less and the host is followed by a colon without setting the actual port, `:uri_string.parse/1` returns the port to be `:undefined`. As long as the url string is parseable, we should translate `:undefiend` to `nil`, in order to ensure we return a valid URI struct.
=> Translate `:undefined` URI port to `nil`

lib/logger/lib/logger/translator.ex, lib/logger/test/logger/translator_test.exs
This PR addresses an issue where `:gen_statem` modules terminate silently in Elixir, as their termination reports aren't translated. This is particularly troublesome in cases where mix dependencies use `:gen_statem` internally, and may fail silently.
I've made a small repo for reproducing the issue [here](https://github.com/Moosieus/a-sad-state-machine).
I haven't exhaustively evaluated all possible errors or diagnostics that could be included, but I think what's here is a reasonable starting point.
=> Translate `:gen_statem` termination reports

lib/elixir/lib/calendar/datetime.ex
This already works but using it will make dialyzer complain.
=> Loosen typespec to match implementation of DateTime.to_unix/2

lib/elixir/lib/file.ex
Note that `File.rm` works correctly
Repro:
```
{:ok, socket} = :socket.open(:local, :stream)
:ok = :socket.bind(socket, %{family: :local, path: "socket"})
File.rm_rf("socket")
{:error, :eio, "socket"}
File.rm("socket")
:ok
```
=> Do not error when File.rm_rf is called on unix domain socket on windows

lib/elixir/pages/references/compatibility-and-deprecations.md
I thought we can already make it explicit so that people can find the information easily?
=> Document supported OTP versions for 1.17

lib/elixir/lib/calendar/date.ex, lib/elixir/lib/calendar/duration.ex, lib/elixir/lib/calendar/iso.ex, lib/elixir/lib/calendar/time.ex, lib/elixir/test/elixir/calendar/date_test.exs, lib/elixir/test/elixir/calendar/datetime_test.exs, lib/elixir/test/elixir/calendar/duration_test.exs, lib/elixir/test/elixir/calendar/naive_datetime_test.exs, lib/elixir/test/elixir/calendar/time_test.exs
This PR introduces new Duration types: `t:Duration.date_unit_pair/0` and `t:Duration.time_unit_pair/0` to be used in `{Date, Time}.shift/2`. This corrects the spec of the two functions.
It also introduces two new Duration constructors: `Duration.new_date_units!/1` and `Duration.new_time_units!/1` with separate validators to return useful error messages. These are based on the existing validation for `Duration.new!/1`, making sure that we share as much code as possible.
---
I find the names for the new Duration constructors not ideal, happy about suggestions!
=> Separate Duration date and time unit specs

lib/elixir/pages/getting-started/basic-types.md
The exclaimation mark was missing in the result of the concatenation.
=> Fix-basic-types-docu

lib/elixir/lib/stream.ex
SInce https://github.com/elixir-lang/elixir/pull/13486/files#diff-11ced97f76da97ec34bfa29d332bf443d59bb797a59312f6a5d94392978aedeaR1210 we now support an offset or a function, but the spec didn't reflect that.
=> Fix typespec for Stream.with_index/2

lib/elixir/lib/kernel.ex
Small fix for the `binary_part/3` function documentation where the argument `size` was shown as plain text instead of quoted.
=> Formatting fix for binary_part/3 documentation

lib/elixir/lib/file/stat.ex
Example code for which Dialyzer emitted warning:
```elixir
channel_pid = :ssh_sftp.start_channel(ssh_connection)
{:ok, record} = :ssh_sftp.read_file_info(channel_pid, "/home/dummy/test.file")
stat = File.Stat.from_record(record)
case stat.mtime do
:undefined -> nil
modification_time -> modification_time
end
```
Fixes #13497
=> Update File.Stat.t type definition to mirror :file.file_info type.

lib/elixir/pages/getting-started/try-catch-and-rescue.md
FWIW, I find `catch` useful sometimes for when a `GenServer.call/3` times out; raising is not always the best strategy.
But I didn't want to alter the basic advice given here without discussion.
=> Expand description of how `catch` works

lib/elixir/lib/task.ex
The listed examples had the headings reversed. This is a documentation only change.
=> Correct task remote vs. local documentation

lib/elixir/lib/process.ex
This functionality is present since OTP 26.2:
https://github.com/erlang/otp/pull/7707
Discussed at https://github.com/elixir-lang/elixir/issues/12857#issuecomment-2068886344
=> Expose getting process dictionary value for specific key in Process.info/2

lib/mix/lib/mix.ex, lib/mix/lib/mix/utils.ex
Allow specifying a custom cacertfile for mix operations that need to make HTTPS requests. This allows mix operations to run in corporate environments that have a managed network with an SSL proxy that requires use of a custom cert file instead of the system default.
Without environment variable on work laptop: 
```
> mix local.hex
** (Mix) httpc request failed with: {:failed_connect, [{:to_address, {~c"builds.hex.pm", 443}}, {:inet, [:inet], {:tls_alert, {:unknown_ca, ~c"TLS client: In state wait_cert_cr at ssl_handshake.erl:2125 generated CLIENT ALERT: Fatal - Unknown CA\n"}}}]}
Could not install Hex because Mix could not download metadata at https://builds.hex.pm/installs/hex-1.x.csv.
Alternatively, you can compile and install Hex directly with this command:
$ mix archive.install github …
```
=> Use HEX_CACERTS_PATH environment variable to allow custom override of system defined CA certificates

lib/logger/lib/logger.ex
👋 
I think that the spec for `Logger.level/0` is invalid: `:all` and `:none` may be missing.
According to https://www.erlang.org/doc/man/logger#get_primary_config-0 and https://www.erlang.org/doc/man/logger#type-primary_config,
returned type for `:logger.get_primary_config` is:
```erlang
#{level => level() | all | none,
metadata => metadata(),
filter_default => log | stop,
filters => [{filter_id(), filter()}]}
```
Thus, inside `Logger.level/0` fun, `level` could also be `all` and `none` when calling:
```elixir
%{level: level} = :logger.get_primary_config()
```
=> fix(spec): add :all and :none for Logger.level/0

lib/elixir/lib/string.ex
As a user of the docs, when looking for information on how to pattern match with strings and binaries the first place one looks is the String docs.
Currently there isn't anything here for pattern matching besides a small example matching a character. The user would either have to go from the reference section to the patterns and guards guide or go to the <<>>/1 special forms docs.
This change just adds a link to the special forms docs and the guide to signpost the user to those resources.
=> Add some signposting to the String docs for pattern matching

lib/elixir/lib/module/types/descr.ex, lib/elixir/test/elixir/module/types/descr_test.exs
Introducing a representation for map types, closed or open, with required or optional atom keys.
The representation is by disjunctive normal forms, that is, lists of pairs `{positive_map, negative_maps}`. A map type is the union of each element of the list, and each element is the difference of the `positive_map` with the `negative_maps`.
For instance, `%{a: integer()} and not %{..., b: atom()}` is stored as the pair with a positive `{:closed, %{a: integer()}}` and a negative `{:open, %{b: atom()}}`.
Set-theoretic operations constitute in distributing `or`, `and`, `and not` along those lists. 
To handle optional fields, bit 10 of the bitmap is used to represent the `not_set()` special type. A key may be absent if and only if its value type contains `not_set()`.
TODO, after that 
- add …
=> Map types representation

lib/elixir/lib/module/types/descr.ex
Makes the quoted representation deterministic and fixes this flaky test:
=> Use deterministic key order when quoting maps

lib/elixir/lib/kernel/utils.ex, lib/elixir/lib/module/types/descr.ex, lib/elixir/lib/module/types/expr.ex, lib/elixir/lib/module/types/helpers.ex, lib/elixir/lib/module/types/of.ex, lib/elixir/lib/module/types/pattern.ex, lib/elixir/src/elixir_map.erl, lib/elixir/test/elixir/kernel/expansion_test.exs, lib/elixir/test/elixir/module/types/descr_test.exs, lib/elixir/test/elixir/module/types/expr_test.exs
With this pull request, we now warn:
* `expr.field` when `expr` may not be a map
* `expr.call()` when `expr` may not be an atom
* `expr.call(...)` when `expr` may not be an atom
* `&expr.foo/1` when `expr` may not be an atom
Furthermore, we lay down the ground work for checking undefined and deprecation warnings across unions. For example, if you write this code:
```elixir
mod = if something?, do: Foo, else: Bar
mod.some_function()
```
In the future, it will warn if any of Foo OR Bar do not define the relevant function.
Finally, we improve pretty printing of maps and aliases.
=> Type inference for structs and type checking for dot/remote

lib/elixir/lib/module/types/of.ex, lib/elixir/test/elixir/module/types/expr_test.exs
The hint makes sense for the `:bad_map` case but seems unwarranted for `:bad_key`:
=> Remove dot hint when the issue is a missing key in a map

lib/elixir/pages/mix-and-otp/introduction-to-mix.md, lib/ex_unit/lib/ex_unit/cli_formatter.ex, lib/ex_unit/test/ex_unit_test.exs, lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/tasks/test_test.exs
Some CI environments may report the wrong number
of cores to the Erlang VM. So we choose to print
the number of max cases along side the seed
(both which affect randomness of tests) at the
top of each suite.
=> Include max cases in ExUnit reports

lib/elixir/src/elixir_expand.erl
There are no tests covering this case and probably it's very rare so it went undetected for long time
=> Fix warn case return value in pid expansion

lib/elixir/lib/calendar/datetime.ex
I had to lookup the code to find the answer, I thought it would be nice to document it?
=> Document default unit of DateTime.utc_now/1

lib/elixir/lib/exception.ex
Feel free to rephrase, I am not super happy with the wording.
Whenever I search for exceptions in hex_doc, I often first search for [`Exception`](https://hexdocs.pm/elixir/main/Exception.html), without any useful info on how to implement the behaviour. I figured a link to the relevant section could improve discoverability.
I also mentioned that the module didn't mention at all about the behaviour, but [`defexception`](https://hexdocs.pm/elixir/main/Kernel.html#defexception/1) does.
=> Link to defexception in Exception doc and mention the behaviour

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel_test.exs
Implemented based on `is_struct/1`.
The second commit adds an admonition to `is_map/1` to increase awareness:
=> Add Kernel.is_non_struct_map/1 guard

lib/elixir/lib/bitwise.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/list.ex, lib/ex_unit/lib/ex_unit/doc_test.ex, lib/ex_unit/test/ex_unit/doc_test_test.exs, lib/mix/lib/mix/tasks/test.ex
I noticed that the `; otherwise returns ...` pattern was omnipresent, applying @whatyouhide's [suggestion](https://github.com/elixir-lang/elixir/pull/13534#discussion_r1589927754) to other occurrences for consistency.
=> Replace semi-column by comma before otherwise

CHANGELOG.md
There was a minor typo in the changelog.
=> Correct minor typo

lib/elixir/pages/references/gradual-set-theoretic-types.md
I assume the text meant to refer to the aforementioned `(integer() -> integer())` set?
Thanks for adding this documentation by the way. 🙏
=> Fix typo in the gradual set-theoretic types documentation

lib/elixir/lib/gen_event.ex
The link in the documentation is not up-to-date. The article is now hosted on the Dashbit Blog
=> Correct link in GenEvent docs

lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/tasks/test_test.exs
Recently, we tried to override the `failures_manifest_file` configuration in our CI pipeline to achieve the partitioning of our test suite on top of the same file system. 
Thanks :)
=> Fix default failures_manifest_file

lib/elixir/lib/kernel/lexical_tracker.ex, lib/elixir/lib/macro/env.ex, lib/elixir/test/elixir/kernel/alias_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs
Close https://github.com/elixir-lang/elixir/issues/13549
=> Warn on unused shadowed aliases

lib/elixir/lib/calendar/date.ex, lib/elixir/lib/calendar/iso.ex, lib/elixir/test/elixir/calendar/date_test.exs, lib/elixir/test/elixir/calendar/iso_test.exs
Based on the discussion in https://github.com/elixir-explorer/adbc/issues/74, this PR
- allows `Date` to accept  year outside the ISO8601 range
- relaxes the year guards -- as long as it's an integer
- relaxes the days guard in `Calendar.ISO.date_from_iso_days/1`, so that we can do computations like `Date.add/1`
- prints as `Date.new!` instead of the sigil if the date is outside the ISO8601 range
=> Allow `Date` to accept year outside ISO8601 range

lib/elixir/lib/regex.ex
I tried to add a couple of additional specs, doc examples and links to increase discoverability for `Regex` options.
=> Improve specs and docs for the Regex module

lib/elixir/lib/regex.ex, lib/elixir/pages/references/typespecs.md
Even if I understand we might want to push defining type options over plural options type, it feels that the keyword syntax should still be documented explicitly in the [Typespecs reference](https://hexdocs.pm/elixir/main/typespecs.html#keyword-lists).
The first commit is a small fix to be consistent in the use of keyword spec syntax, I forgot to fix this one in #13552.
=> Explain keyword spec syntax in typespecs reference

lib/elixir/lib/calendar/iso.ex
is_year used to do more before 3d7f4dddbf9759fbc003518a802ec6cccdbfdc6a
=> Remove duplicated is_integer in Calendar.ISO.valid_date?/3

lib/elixir/pages/getting-started/io-and-the-file-system.md
When I was following the documentation to learn Elixir just now, I entered the following code in iex: `{:ok, file} = File.open("/home/username/.zshrc", [:write])`. This ended up clearing my `.zshrc` configuration file. Fortunately, I had a backup. However, if others don't have a backup or input the path to a more important file, I understand this could result in their files being cleared. Therefore, I added a warning prompt when dealing with `File.open("path/to/file/hello", [:write])`. English is not my native language, and I used AI to translate these prompts. Feel free to modify if it's not good enough, but I feel it's necessary to give readers a heads-up, as there's still some risk involved.
=> Add Warning Prompt for File Write Operations in Elixir Learning Documentation

lib/elixir/lib/io.ex
- Mention it prints to the standard output
- Refer to `IO.inspect/3` for printing in other devices
=> Improve IO.inspect/2 docs with regards to devices

CHANGELOG.md
When reading the 1.17 changelog, in my opinion people less familiar with how typecheckers work can read too much into the promised improvements, and they might be disappointed afterwards when trying out the typechecker. For example, these two points especially:
> Elixir v1.17 will emit the following warnings at compile-time:
> - Pattern matching against a map or a struct that does not have the given key, such as %{adress: ...} = user (notice address vs adress)
> - Updating a struct or a map that does not define the given key, such as %{user | adress: ...}
mention maps in general, but if I understand correctly this will only work for maps in limited situations when the map type with its keys is statically known, e.g. when updating a map literal defined in the same function.
I think it's …
=> Add note about statically known maps keys and types tracking across function calls to the changelog

lib/elixir/lib/kernel/lexical_tracker.ex, lib/elixir/src/elixir_lexical.erl, lib/elixir/test/elixir/kernel/lexical_tracker_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs
Closes https://github.com/elixir-lang/elixir/issues/13563.
For now, I went with the suggestion to fix the issue:
>  Perhaps we could track the scope of the alias in such cases (for example, only consider it overridden if outside of a function?).
We might be able to do something even smarter with `function` in order to track unused shadowing within a function, I'm not sure yet, will keep exploring. Otherwise seems like a good compromise if this keeps the `state` simpler.
=> Fix false positive with nested shadowed alias

lib/elixir/pages/getting-started/sigils.md, lib/elixir/src/elixir_import.erl, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/kernel/parser_test.exs
This commit adds support for sigils containing integers. Integers must be proceeded by an upper case alpha, but can otherwise be mixed (e.g., `~A1B2C3`).
=> Add support for sigils containing integers

lib/elixir/lib/kernel/lexical_tracker.ex, lib/elixir/lib/macro/env.ex, lib/elixir/src/elixir_lexical.erl, lib/elixir/test/elixir/kernel/alias_test.exs, lib/elixir/test/elixir/kernel/lexical_tracker_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs
Close https://github.com/elixir-lang/elixir/issues/13563
=> Revert alias shadowing warning due to false positives

lib/elixir/lib/kernel.ex, lib/elixir/src/elixir_quote.erl, lib/elixir/test/elixir/kernel/expansion_test.exs
It seems the bug has been introduced in df64d5c6a1be3c3d24e2db43bda0c19ff0d36366 (and 169595f5347bc6f1c6fd8234a9478b794cb853fe) where `import` meta has been renamed to `imports` but some places were missed This bug was present since 1.14.0
=> Fix typo in meta key name in elixir_quote

lib/elixir/lib/kernel.ex
Highlighted in red it shows "section" repeated twice
=> Remove duplicate instances of word "section"

lib/mix/lib/mix/tasks/xref.ex
"False positives" might not be the best way to describe this case; if not, please advise.
=> Document why 'mix xref' can give false positives

lib/elixir/pages/getting-started/alias-require-and-import.md
Browsing the docs I found the page and found it weird that it didn't mention use (as the 4 of them go together), reading the page I realized that it _does_ mention `use` but it's just not mentioned in the headline so this seemed like an easy fix.
I did _not_ modify the file name, although I think it'd be better to also rename the file (and references to it). However, I was worried about breaking outside links to https://hexdocs.pm/elixir/alias-require-and-import.html I'm looking for guidance on:
* is the breakage ok
* should we just not break
* should we break and maybe leave a note in the existing file that documenation moved (and hide from the getting started)
Thanks for all your work as usual! :green_heart:
=> Make clear the " alias, require, and import " also talks about use

lib/elixir/lib/macro/env.ex
:elixir_dispatch.expand_require/6 does not return a {:function, receiver, name} tuple
https://github.com/elixir-lang/elixir/blob/37d36f8bd6d4d8e9f0f4e179bf607b9644447638/lib/elixir/src/elixir_dispatch.erl#L237-L244
=> Remove redundant case clause from Macro.Env.expand_require

lib/iex/lib/iex/introspection.ex, lib/iex/test/iex/helpers_test.exs
Approach 1 for discussion - only use shell docs for OTP26-, and use the new markdown + existing IO.ANSI.Docs markdown.
Will bring back specs, supports tables & skips mermaid charts.
Still need to fix tests.
=> Only use shell_docs for html docs (OTP26-)

lib/elixir/lib/system.ex, lib/elixir/test/elixir/system_test.exs, lib/mix/lib/mix/shell.ex
=> Add support for use_stdio option to System.shell and Mix.Shell.cmd

lib/elixir/src/elixir_quote.erl, lib/elixir/test/elixir/macro_test.exs
Attempts to solve #13593 
Attempts to solve an issue that causes `Macro.escape/2` to crash when
given certain tuples.
Note that, as discussed in the reported issue, `Macro.escape({:quote, [column: 10], [:foo]})` still produces
: `{:{}, [], [:quote, [], [:foo]]}` which is arguably wrong.
=> Correctly Macro.escape :quote triplet without meta

lib/mix/lib/mix/tasks/test.coverage.ex
Today the coverage HTML files are generated one at a time using `:cover.analyse_to_file`.
This PR changes this code to use `:cover.async_analyse_to_file` to generate the files in parallel, speeding up the coverage report. 
On a M1 in a project with 1k modules, the time to generate the HTML files went from 4 seconds to 1.2 seconds.
=> Generate cover HTML files in parallel

lib/mix/lib/mix/tasks/profile.eprof.ex, lib/mix/lib/mix/tasks/profile.tprof.ex, lib/mix/test/mix/tasks/profile.tprof_test.exs
Close https://github.com/elixir-lang/elixir/issues/13581
Sharing my draft for feedback as I think the implementation is now done - I still need to do the moduledocs.
I used `profile.eprof` as a  base, since these are actually quite close.
Reviewing this commit [Actually implement tprof](https://github.com/elixir-lang/elixir/commit/5ac62df9013b26008964a7a11f9fe85bf1a70d33) might help the review since it highlights the differences.
<details>
<summary>Sample outputs</summary>
```elixir
mix profile.tprof -e "Enum.each(1..5, &String.Chars.Integer.to_string/1)"
Warmup...
Profile results of #PID<0.107.0>
Total                                              20 100.00    2    0.10
String.Chars.Integer.to_string/1                    5   0.00    0    0.00
anonymous fn/0 in …
```
=> Implement mix profile.tprof

lib/elixir/src/elixir_fn.erl, lib/elixir/test/elixir/kernel/expansion_test.exs
`&` variables exist in the code so it makes sense to preserve the position in expansion
=> Keep position meta on & capture special variables in expanded AST

lib/elixir/lib/calendar/duration.ex, lib/elixir/lib/calendar/iso.ex, lib/elixir/test/elixir/calendar/duration_test.exs
Negative durations are actually [specified](https://tc39.es/proposal-temporal/docs/duration.html#from) in ISO 8601-2 while individual negative units are not. The [Java Duration class](https://docs.oracle.com/javase/8/docs/api/java/time/Duration.html#parse-java.lang.CharSequence-) supports both features and i think the negative duration prefix may actually be more common than the one for individual units. IMHO it makes sense that we also support both in the standard library.
=> Support negative period prefix in `Calendar.ISO.parse_duration/1`

lib/mix/lib/mix/tasks/compile.ex
As far as I can tell, this is how it behaves but it wasn't explicitly documented?
=> Add precision about --warnings-as-errors

lib/elixir/lib/calendar/duration.ex, lib/elixir/lib/calendar/iso.ex, lib/elixir/test/elixir/calendar/duration_test.exs
Following up to supporting the minus sign prefix, this adds support for the plus sign prefix to comply with the ISO 8601-2 Duration specification.
Referencing PR: https://github.com/elixir-lang/elixir/pull/13608
=> Support plus sign prefix in `Calendar.ISO.parse_duration/1`

lib/elixir/lib/calendar/duration.ex, lib/elixir/test/elixir/calendar/duration_test.exs
This PR implements `Duration.to_iso8601/1` which transforms a `Duration.t()` to the ISO8601-2 duration string representation, for instance:
```elixir
iex> Duration.new!(year: 3, hour: 12) |> Duration.to_iso8601()
"P3YT12H"
```
A few open points:
Zero duration is represented as `PT0S`. All other variants are possible (`P0D` for instance is shorter - this is the second example in the Wikipedia article).
The wikipedia states that the 3 following formats are permitted:
> PnYnMnDTnHnMnS
> PnW
> P\<date>T\<time> 
We don't need the 3rd.  The first two tell us that either you have a week-only duration, or a duration with all possible components except weeks.
According to the [iso8601-duration](https://www.npmjs.com/package/iso8601-duration) npm lib doc, an extension to iso8601:2019 allows weeks …
=> Implement `Duration.to_iso8601/1`

lib/mix/lib/mix/tasks/profile.tprof.ex, lib/mix/test/mix/tasks/profile.tprof_test.exs
A small follow-up for https://github.com/elixir-lang/elixir/pull/13605, I didn't include it in the MVP to keep the PR smaller.
One of the niceties of `tprof` is the ability to sort per "per call measurement", perhaps we can expose the option?
We might consider some other [options](https://www.erlang.org/doc/apps/tools/tprof.html#t:column/0) as well, but sorting by percentage seems redundant since it should be proportional?
```elixir
$ mix profile.tprof -e "Enum.each(1..5, &String.Chars.Integer.to_string/1)" --sort per_call
Warmup...
Profile results of #PID<0.106.0>
Total                                              20 100.00    6    0.30
String.Chars.Integer.to_string/1                    5   0.00    0    0.00
Enum.reduce_range/5                                 3   0.00    0    0.00 …
```
=> Add sort :per_call option to tprof

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
Dbg currently is not showing any bindings when executed on if statement so it's very hard to guess what's going on:
```elixir
if a do
b
else
c
end #=> 2
```
This pr extends dbg to support if statements:
```elixir
If condition:
true and x #=> true
If expression (do clause executed):
if true and x do
map[:a] * 2
else
map[:b]
end #=> 10
```
I proposed this on [elixir forum](https://elixirforum.com/t/dbg-block-and-better-dbg-for-case-if-with/63477) with other tweaks to dbg, but did not get any answers.
=> implement dbg for if expressions

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
It's slightly modified code from boolean operator dbg code:
```elixir
(
a = 1
b = a + 2
a + b
)
|> dbg()
```
generates:
```elixir
Code block:
(
a = 1 #=> 1
b = a + 2 #=> 3
a + b #=> 4
)
```
I was thinking of adding also the value returned from the block, but it's the same as last expression - for integers it may be ok, but for bigger data structures it will be just noise.
=> implement dbg for code blocks

lib/elixir/lib/float.ex, lib/elixir/lib/string.ex, lib/elixir/test/elixir/string_test.exs
Strings like `.3` cannot be parsed using `String.to_float/1` or `Float.parse/1`, which is a surprising and noteworthy difference from other languages like JS and Ruby which can parse this.
=> Document bare decimal case on String.to_float/1 and Float.parse/1

lib/mix/lib/mix/tasks/profile.tprof.ex, lib/mix/test/mix/tasks/profile.tprof_test.exs
Expose this "Type" param of tprof's [`inspect/3` function](https://www.erlang.org/doc/apps/tools/tprof.html#inspect/3).
I struggled a bit to find a good name for the argument, alternative proposals welcome.
I also considered making this a boolean flag but I finally decided to stick to Erlang's atoms.
`process` (default):
```elixir
$mix profile.tprof -e "Task.async_stream(1..2, & &1 ** 2) |> Enum.to_list()"
Warmup...
Profile results of #PID<0.109.0>
Total                                              99 100.00   16    0.16
:elixir_aliases.concat/1                            1   0.00    0    0.00
...
:erlang.send/2                                      6  31.25    5    0.83
Profile done over 53 matching functions
Profile results of #PID<0.110.0>
Total …
```
=> Add :report option to aggregate results over multiple processes in tprof

lib/mix/lib/mix/compilers/test.ex, lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/tasks/test_test.exs
As discussed in https://github.com/elixir-lang/elixir/pull/13589. This adds a new option to mix test called `--max-requires` that controls the concurrency of the test file compilation. Setting this to 1 allows to enforce a deterministic compilation order to better reproduce flaky tests.
Relates to https://github.com/elixir-lang/elixir/pull/13634.
Again, sadly, I don't know a good way to add tests for this with the current setup.
=> add --max-requires to mix test

lib/elixir/test/elixir/exception_test.exs, lib/elixir/test/elixir/inspect_test.exs, lib/elixir/test/elixir/kernel/raise_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs, lib/elixir/test/elixir/kernel_test.exs, lib/elixir/test/elixir/record_test.exs, lib/elixir/test/elixir/typespec_test.exs, lib/ex_unit/lib/ex_unit/server.ex, lib/ex_unit/test/ex_unit/assertions_test.exs, lib/ex_unit/test/ex_unit_test.exs
In order to have more deterministic test runs when using `--max-cases 1` and `--max-requires 1` (https://github.com/elixir-lang/elixir/pull/13635) (see also https://github.com/elixir-lang/elixir/pull/13589), we need to run tests in compilation order (FIFO).
In the past, ExUnit.Server appended new tests to the front of a list, which would result in the most recently added test to be run first.
Let's quickly demonstrate the problem this causes for deterministic runs with a simple example:
Imagine a test (let's call if FooTest) that takes a non-deterministic amount of time to run. For now let's assume that it sometimes takes 1 second and sometimes up to 5. And as async tests execute in parallel with compilation of other test files, we could have the following scenario:
FooTest is compiled …
=> use a `:queue` to store modules in ExUnit.Server

lib/elixir/lib/calendar/date.ex, lib/elixir/lib/calendar/datetime.ex, lib/elixir/lib/calendar/duration.ex, lib/elixir/lib/calendar/naive_datetime.ex
Motivated by some comments in the [ThinkingElixir podcast](https://podcast.thinkingelixir.com/205) 😅
=> Extend Duration shift documentation

lib/ex_unit/lib/ex_unit/case.ex
while addressing the `ExUnit.Case.register_test/3` deprecation in https://github.com/elixir-wallaby/wallaby/pull/776, I wondered how long `register_test/6` had been around. In looking at the source and the docs, I uncovered what I believe is an incorrect `since` attribute
=> Update case.ex with correct `:since` for register_test/6

lib/elixir/lib/module/types/helpers.ex
This hint should help users fixing these warning, like [this one](https://github.com/phoenixframework/phoenix/commit/34d0ffef6aebcb5d4f210978aabca53b0e57f1ae#diff-d939a953683e8fcff02626d9d2e4f3a473107a977eddf6bf043117a2eded463fR149).
Sample code which can trigger the issue:
```elixir
def inverse(x) do
1 / x
rescue
err -> err.message
end
```
=> Add more information to anonymous rescue hint

lib/elixir/lib/regex.ex
Reverting adding new types for options because they were not exhaustive, and will be hard to keep in sync with Erlang, which has upcoming changes planned for `:re`.
See https://github.com/elixir-lang/elixir/pull/13643#discussion_r1629390738
Closes https://github.com/elixir-lang/elixir/issues/13598.
Keeping the doc improvements.
=> Revert types from #13552

lib/mix/lib/mix/generator.ex, lib/mix/test/mix/generator_test.exs
Discussion: https://groups.google.com/g/elixir-lang-core/c/-4EM5d_ex6o/m/-qa1ZBVTAAAJ
=> `format_elixir: true` option for file generation

lib/elixir/lib/process.ex, lib/elixir/test/elixir/process_test.exs
A while ago OTP timer module was [changed](https://github.com/erlang/otp/commit/06cacbca485bbd4dc64e24d7e9fe743fb0a3610b) to support sleeping with arbitrarily high integer timeout values. Given that `Process.sleep/1` is almost the same as `:timer.sleep/1` it seems that Elixir could support this too.
There are a number of ways to implement it, each with it's own tradeoffs regarding backward compatibility when supplying wrong types.
In this PR I just translated Erlang's implementation to Elixir. This allows it to keep `FunctionClauseError` on bad input, but error text now mentions  `timeout > 4_294_967_295` guard which can be confusing to the end user.
```
❯ bin/elixir -e "Process.sleep(:atom)"
** (FunctionClauseError) no function clause matching in Process.sleep/1    
The following …
```
=> Handle arbitrarily high integer values in Process.sleep/1

lib/iex/lib/iex.ex, lib/iex/lib/iex/config.ex, lib/iex/lib/iex/evaluator.ex, lib/iex/test/iex/interaction_test.exs, lib/iex/test/test_helper.exs
As discussed [in the google group](https://groups.google.com/g/elixir-lang-core/c/qphuwdQxcsc) this PR adds a `dot_iex` config option to the iex application for dot-iex path configuration
Let me know if there are any changes you would like to see!
=> Add `dot_iex` IEx.Config key to take precedence over existing configurations

lib/elixir/pages/anti-patterns/design-anti-patterns.md
Small example typo in the [Design-anti-patterns](https://hexdocs.pm/elixir/main/design-anti-patterns.html#alternative-return-types)
=> Correct example in the docs

lib/ex_unit/test/ex_unit_test.exs
Relates to https://github.com/elixir-lang/elixir/pull/13639#issuecomment-2158497390, https://github.com/elixir-lang/elixir/commit/ecac839810905f2da826c5cca01cb4e0e9fc5a95
@josevalim
=> add test for mix test --only async/sync filter

bin/elixir.ps1, bin/elixirc.ps1, bin/iex.ps1, bin/mix.ps1, lib/elixir/test/elixir/kernel/cli_test.exs, lib/elixir/test/elixir/test_helper.exs
This is the first step to replace _BAT_ scripts for Windows.
PowerShell works on Linux and MacOS too, so the scripts are supporting those systems as well.
~~The only requirement is that users have at least the version 7.2 LTS.~~
This feature was previously discussed with @josevalim :)
PS: I ran the test suite using "bin/elixir.ps1" in the `lib/mix/test/test_helper.exs` file (`elixir_executable` fun), and it's working good. I was not able to build and run on Windows yet, but the commands using the `ELIXIR_CLI_DRY_RUN` env var seems to be correct there :)
=> Add PowerShell scripts

.github/workflows/builds.hex.pm.yml, .github/workflows/release.yml, .github/workflows/release_pre_built/action.yml
The idea is to have a way to ensure that the artifacts were not tempered after the build.
You can find details in the projects page:
https://github.com/actions/attest-build-provenance
There is also the docs page:
https://docs.github.com/en/actions/security-guides/using-artifact-attestations-to-establish-provenance-for-builds
=> Use GitHub Actions' "artifact attestation" feature 

lib/mix/lib/mix/tasks/release.ex
Nodes using short names can still be connected across machines.
See question 1. in [this thread](https://erlangforums.com/t/difference-between-short-and-long-names-how-erlang-resolves-them/1531). I also verified this with two machines on a local network by adding an entry to `/etc/hosts`, such that the short name is resolved to the peer IP.
My understanding is that the resolution is exactly the same. Picking one or the other only determines if the validation requires FQDN or rejects FQDN, and nodes can only connect to other nodes using the same mode. I am interested to know what was the original motivation for two distinct modes in the first place (in Erlang), if someone is aware, please leave a comment.
=> Update RELEASE_DISTRIBUTION docs

lib/elixir/src/elixir_erl_pass.erl, lib/elixir/test/elixir/fixtures/dialyzer/with_no_return.ex, lib/elixir/test/elixir/kernel/dialyzer_test.exs
Close #13656
Will backport after merge.
=> Fix dialyzer error when with else clause is calling a no_return function

lib/elixir/lib/code/identifier.ex, lib/elixir/test/elixir/inspect_test.exs
This reduces confusion when working with zero-width characters or alternative spaces.
Relates to #13673
I used [this](https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Special-purpose_characters) as a base and compared with python which seems to have a similar strategy for almost all of these.
=> Inspect special purpose chars using their unicode representation

lib/mix/lib/mix/tasks/release.init.ex
* Validate value of `!RELEASE_DISTRIBUTION!`
* Validate value of `!RELEASE_MODE!`
* Exit with `ERRORLEVEL` set to `1` on errors.
Previously we did not and so apps that use releases and rely on exit codes to report errors were not doing so (e.g. Livebook).
* Rename rpc node name from `rem-(...)` to `rpc-(...)`
Also updates generated `rel/env.bat.exs`.
=> Improvements to generated rel/bin/app.bat

lib/elixir/lib/enum.ex, lib/elixir/pages/cheatsheets/enum-cheat.cheatmd, lib/elixir/test/elixir/enum_test.exs
Proposal draft to include `Enum.sum/2`.
If we agree on the signature, will send a similar PR for `Enum.product/2`.
Side note: ~might also bench specific implementations for lists to see if it's worth it.~
Edit: [done](https://github.com/sabiwara/elixir_benches/commit/c5f0146e672468dc6e7bd4ff336483361b774c60), shows a 40% increase. Not bad, will update accordingly.
=> Add Enum.sum_by/2

lib/elixir/lib/enum.ex, lib/elixir/pages/cheatsheets/enum-cheat.cheatmd, lib/elixir/test/elixir/enum_test.exs
Follow up for https://github.com/elixir-lang/elixir/pull/12885
=> Add Enum.product_by/2

lib/elixir/lib/registry.ex, lib/elixir/lib/string.ex, lib/elixir/lib/task.ex, lib/elixir/test/elixir/registry_test.exs
Just a small refactoring to use the newly added `Enum.sum_by/2` when relevant.
I did this mostly out of curiosity, feel free to close.
=> Use Enum.sum_by/2 when appropriate

lib/logger/lib/logger/translator.ex, lib/logger/test/logger/translator_test.exs
Closes #13682
Will backport after merge.
=> Fix logger crash when :gen_statem format_status/2 returns non-tuple

lib/elixir/pages/references/syntax-reference.md
These typos were introduced in [f1f54df](https://github.com/elixir-lang/elixir/commit/f1f54df22a0fc5282f3412844cea98f38f0b7df0)
=> Fix some issues in syntax reference

lib/mix/lib/mix/tasks/release.init.ex
before
```
-start_epmd false -erl_epmd_port 6789false
```
after
```
-start_epmd false -erl_epmd_port 6789
```
=> Fixes vm.args.eex generated file when `remote?` is false

lib/elixir/lib/float.ex, lib/elixir/lib/map.ex, lib/elixir/src/elixir_rewrite.erl
Inline more regularly used functions in the standard Elixir modules to their Erlang STDLIB counterparts:
- `Float.to_charlist/1`
- `Float.to_string/1`
- ~~`List.duplicate/2`~~
- ~~`List.flatten/1`~~
- ~~`List.flatten/2`~~
- `Map.from_keys/2`
- ~~`Map.merge/3`~~
Great care was taken to ensure function guards already applied to the Elixir functions were subsets of the function guards in Erlang's STDLIB. ~~For example, `Map.merge/3` [specified](https://github.com/elixir-lang/elixir/blob/v1.17.1/lib/elixir/lib/map.ex#L651) the combiner function must be `is_function(fun, 3)` and Erlang's `:maps.merge_with` also [already specifies](https://github.com/erlang/otp/blob/OTP-27.0/lib/stdlib/src/maps.erl#L381) that argument must be `is_function(Combiner, 3)`.~~
The one exception to the above is the …
=> Inline more functions

lib/elixir/lib/exception.ex, lib/elixir/test/elixir/exception_test.exs
=> Add MissingDependenciesError exception

Makefile, lib/elixir/pages/references/unicode-syntax.md, lib/elixir/test/elixir/kernel/warning_test.exs, lib/elixir/unicode/security.ex, lib/elixir/unicode/tokenizer.ex
PR following up on [Directional confusability: _א1 and _1א not detected -- unicode 15.1's new TR55, and updated TR39](https://github.com/elixir-lang/elixir/issues/12929), proposing two changes:
1. per discussion of recent updates to Unicode's UTS39/55 in the issue linked above, we allow safe script mixing in identifiers, using a heuristic derived from the concept of identifier chunks from uts55. Basically we allow limited script mixing in identifiers like `foo_bar_baz`, only when separated by underscore, where `foo`, `bar`, `baz` chunks must be single-script or highly-restrictive.
2. provide directional confusability detection (which was needed even without script mixing, as the example from the issue above shows) by reversing spans of rtl-direction chars in bidi_skeleton, so that we …
=> Draft of directional confusability protection & allowing script mixing in identifiers when separated by underscores

lib/elixir/lib/dynamic_supervisor.ex
Clearly distinguishes between an init option provided as initial argument to DynamicSupervisor, and a regular "GenServer type" option provided as third argument in `start_link/3`
fix #13675
=>  change DynamicSupervisor doc to avoid confusions

lib/elixir/lib/enum.ex
A small suggestion to address this: https://github.com/elixir-lang/elixir/pull/13671#discussion_r1663384927.
=> Minor change in Enum.with/2 docs

lib/elixir/lib/kernel/special_forms.ex
Hello! Thanks for making Elixir.
I ran into this error message from `:telemetry` and couldn't understand why it was happening, even after doing some web searches & reading the Elixir docs:
> [info] The function passed as a handler with ID “…” is a local function.
This means that it is either an anonymous function or a capture of a function without a module specified. That may cause a performance penalty when calling that handler. For more details see the note in telemetry:attach/4 documentation.
[telemetry — telemetry v1.2.1](https://hexdocs.pm/telemetry/telemetry.html#attach/4)
After I asked on the Elixir Forums, I was pointed to a mailing list thread ([https://groups.google.com/g/elixir-lang-core/c/rW_BRCULsGk/m/9rrYEwwtAwAJ 1](https://groups.google.com/g/elixir-lang-core/c/rW_BRCULsGk/m …
=> Clarify what specifying the module name does with &

lib/elixir/pages/references/syntax-reference.md
Was reading the docs for my favorite language and came across a minor typo. This PR fixes it.
=> Fix a typo in the docs

lib/mix/lib/mix/scm/git.ex, lib/mix/lib/mix/tasks/deps.ex, lib/mix/test/mix/tasks/deps.git_test.exs
An optimization to fetch only the about-to-be-used refs introduced when the :depth option was added broke support for specifying a SHA1 prefix as :ref. Such possibility was neither documented nor tested, but certainly used in the wild. This use case is now explicitly supported with a new test case.
We maintain this fetch optimization whenever :branch, :tag or :depth is specified. We fetch all refs when :ref is used without :depth to be able to resolve short SHA1 refs, and require full commit hashes to use :ref and :depth together.
When using :ref with :depth, a full SHA1 is required by Git and surfaced in our docs. We enforce it when validating the options, leaving room for longer hashes.
This commit brings back two tests to cover the :ref and :depth functionality, and adds a new one to …
=> Bring back support for Git :ref and :depth used together

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel/guard_test.exs
Currently, it is not possible to define a guard in Elixir using a dynamic name at compile time like it it possible with `def` and `defmacro`.
As an example the following code fails to compile
```elixir
defmodule MyModule do
@states [:a, :b, :c]
for state <- @states do
defguard unquote(String.to_atom("is_#{state}"))(state) when state == unquote(state)
end
end
```
```
== Compilation error in file text.ex ==
** (ArgumentError) invalid syntax in defguard unquote(String.to_atom("is_#{state}"))(state)
(elixir 1.17.0) lib/kernel.ex:5789: Kernel.define_guard/3
(elixir 1.17.0) expanding macro: Kernel.defguard/1
text.ex:5: MyModule (module)
```
This ensures that an unquote syntax is also accepted in `defguard` and `defguardp` + tests.
=> Enable use of unquote in defguard(p)

lib/mix/lib/mix/tasks/escript.build.ex, lib/mix/test/fixtures/escript_test/lib/escript_test.ex, lib/mix/test/mix/tasks/escript_test.exs
I noticed that Elixir builds escript archive with all modules, app files and priv files flattened out. Contrarily rebar builds escript with directory layout batching `_build`.
The [:code](https://www.erlang.org/doc/apps/kernel/code) documentation states:
```
When an `escript` file contains an archive, there are no restrictions on the
name of the `escript` and no restrictions on how many applications that can be
stored in the embedded archive. Single Beam files can also reside on the top
level in the archive. At startup, the top directory in the embedded archive and
all (second level) `ebin` directories in the embedded archive are added to the
code path.
```
From the above it is clear that modules are loaded correctly with a flat structure, however when we deal with multiple applications, …
=> Fix escript archive layout and support priv

lib/mix/test/mix/tasks/escript_test.exs
As per https://github.com/elixir-lang/elixir/pull/13730#discussion_r1686991493.
=> Refactor escript tests to use less modules

lib/elixir/lib/behaviour.ex, lib/elixir/lib/module.ex
=> Document behaviour_info/1

lib/mix/lib/mix/dep/loader.ex, lib/mix/lib/mix/rebar.ex, lib/mix/lib/mix/shell.ex, lib/mix/lib/mix/tasks/deps.compile.ex, lib/mix/test/mix/rebar_test.exs
=> Use System.cmd rather than System.shell for Rebar3 to avoid escaping

lib/iex/lib/iex/server.ex, lib/iex/test/iex/interaction_test.exs
Issue: #13745
I think rather than delete the `abnormal_reason?/1` directly, add the report with distinct color is better.
=> Add report for "normal" exits in IEx

lib/elixir/lib/kernel.ex
Now that we've co-located the Elixir guides with moduledocs in ex_doc, we can link directly to them in the `defguard/1` `@doc` for:
- more context on guards themselves
- naming conventions for your own guards
Also normalizes the lead-in verb `Defines...` with `defimpl/1`, `defprotocol/2`, `defexception/1`, `defstruct/1` and friends; and directly references the macro argument `guard`.
=> Improve defguard/1 docs with links to guides.

lib/mix/lib/mix/release.ex, lib/mix/test/mix/release_test.exs
When copying .app files to a release, remove references to
`:compile_mtime` so that their contents don't change between builds.
=> Make .app files deterministic in releases

CHANGELOG.md, lib/elixir/lib/list.ex, lib/elixir/test/elixir/list_test.exs
As discussed, `List.zip/1` is actually [less efficient ](https://github.com/sabiwara/elixir_benches/commit/324187bee06dcc709bdea03a366acb4f8cae17ff)than its `Enum` counterpart and doesn't make much sense API-wise.
It seems it was just introduced [a long time ago](https://github.com/elixir-lang/elixir/commit/284012d46c30b526635f5077ea974bf5f7edf345) and was never removed after `Enum.zip/1` got introduced.
=> Soft-deprecate List.zip/1 in favor of Enum.zip/1

CHANGELOG.md, lib/elixir/lib/list.ex, lib/elixir/test/elixir/list_test.exs
We have several options here:
1. just call `:lists.suffix` (if so, perhaps we can do the same for starts_with? / prefix)
2. copy its exact [implementation](https://github.com/erlang/otp/blob/master/lib/stdlib/src/lists.erl#L359-L361) 
3. this PR implementation - inspired by 2. but walking two lists at once and having a consistent `FunctionClauseError` with `starts_with?/2` (see [these tests](https://github.com/elixir-lang/elixir/blob/main/lib/elixir/test/elixir/list_test.exs#L281-L285))
=> Add List.ends_with?/2

lib/elixir/pages/getting-started/keywords-and-maps.md
Per the discussion at the Elixir forum:
https://elixirforum.com/t/why-are-reverse-1-and-at-1-in-enum/65353/20
Update the documentation to better clarify the actual behavior of maps in Elixir.
=> Clarify map key ordering functionality in docs

lib/elixir/lib/keyword.ex
Changed 'and how **the** compare with maps' to 'and how **they** compare with maps'.
=> minor doc bug. change 'the' to 'they'

lib/logger/lib/logger/formatter.ex
=> Add required conditions for Logger's metadata to be print

lib/elixir/scripts/elixir_docs.exs
If mermaid is synchronously loaded, a slow load can prevent the sidebar navigation from displaying since it loads async and must wait for mermaid. Instead, we load mermaid asynchronously and then call `mermaidLoaded()` when loading is finished. See elixir-lang/ex_doc#1941
=> Load mermaid asynchronously

lib/elixir/lib/system.ex
Several of the functions in System that deal with time had a typespec that only allowed the `time_unit` type even though they accepted the `:native time` unit. This confuses dialyzer if `:native` is passed to these functions
=> Ensure :native is a valid parameter type

lib/elixir/pages/getting-started/try-catch-and-rescue.md
I really enjoy this functionality and find it helpful but I believe it's the only time in the language when the final executed expression doesn't determine the return value. Making this explicit in the docs could help clarify any confusion.
=> Add doc to explain return value with after clauses

lib/elixir/lib/enum.ex
This optimization generates important speedups for `Enum.flat_map/2` when using it for map-filtering (returning a list of 0 or 1 elements).
- much faster for both lists and enumerables (1.5~3x)
- more memory efficient for enumerables (don't push empty lists to the list of lists)
See [benchmark](https://github.com/sabiwara/elixir_benches/commit/f5970d7a920784822cc4566a8eebdd9abcc952dd).
=> Optimize Enum.flat_map/2 for filtering

lib/elixir/lib/enum.ex, lib/elixir/pages/cheatsheets/enum-cheat.cheatmd
- this common recipe is mentioned in [`filter`'s doc](https://hexdocs.pm/elixir/Enum.html#filter/2) but not in flat_map itself, it is probably worth mentioning it
- `flat_map` is already listed in the [cheatsheet](https://hexdocs.pm/elixir/enum-cheat.html#flat_map-enum-fun) under the flattening section, but it probably deserves to be also mentioned in the filtering section for better discoverability
=> Add visibility for flat_map filtering in docs

lib/mix/lib/mix/tasks/release.init.ex, lib/mix/test/mix/tasks/release_test.exs
This PR addresses an issue (#13672) with path resolution in `mix release` when scripts are executed via relative symlinks.
The original script did not correctly resolve paths, leading to errors when the release script was invoked through a symlink that pointed to a relative path.
The fix ensures that **SELF** is always resolved to an absolute path, regardless of how the script is invoked.
This update improves the reliability of release scripts in environments where symlinks are used. Additionally, tests have been added to verify that both absolute and relative symlinks work correctly with the updated path resolution logic.
=> Fix relative path resolution in "mix release" for symlinked scripts

lib/elixir/pages/anti-patterns/macro-anti-patterns.md, lib/iex/test/iex/pry_test.exs
Came across 2 typos - one in a test and one in a doc - this PR fixes them.
Thanks for all the hard work on the language!!
=> Fix typos in a test and in a doc

lib/elixir/pages/getting-started/comprehensions.md, lib/elixir/pages/getting-started/module-attributes.md, lib/elixir/pages/getting-started/protocols.md, lib/elixir/pages/getting-started/try-catch-and-rescue.md, lib/elixir/pages/getting-started/writing-documentation.md
Hello, again! :slightly_smiling_face: 
I found a few more typos while working through the rest of getting started after #13800.
These docs were great, I enjoyed reading them to be introduced to Elixir. Nice work!
=> Fix a few more minor typos

lib/elixir/lib/string.ex
Makes this explicit since it was deemed surprising in https://github.com/elixir-lang/elixir-lang.github.com/pull/1768
=> Explicitly mention trimming in String.split/1 doc

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs, lib/ex_unit/test/ex_unit/assertions_test.exs
Close https://github.com/elixir-lang/elixir/issues/13806
We had two options:
- assert_not_match_context in  `expand_once` (but that would duplicate the logic from `:elixir_expand`)
- do not expand and let it fail later - consistent with what happens for `__CALLER__` or `__STACKTRACE__` => went with this one
=> Fix: Macro.expand/2 should not expand __ENV__ on :match context

lib/elixir/lib/gen_server.ex
Fix the arg value in GenServer example. 
Related history pr code: https://github.com/elixir-lang/elixir/commit/9e8ae6efc50eedbc59a4a6583cada871e3c99be7#diff-07e9c029fa058bfd89482ef285ba58c16a3f3a64158a3267d8dea0391710da26L357
=> Fix code example in GenServer docs

lib/elixir/pages/getting-started/basic-types.md
This rule of thumb used to in the getting started page, but it got dropped when moved to hexdocs, I'm not sure if it was intentional.
It was helpful to point new devs to the suggestion when onboarding to elixir.
=> Add a rule of thumb to the guide.

lib/ex_unit/lib/ex_unit/assertions.ex, lib/ex_unit/test/ex_unit/assertions_test.exs
Close https://github.com/elixir-lang/elixir/issues/13814
Indeed as pointed out by José guards being able were a side effect of the shared implementation between `match?` and regular `=`.
The `match?` version would not be strictly equivalent, since there is no way to to reuse extracted variables after matches, but this is probably an OK limitation in practice.
=> Do not allow guards in assert/1

lib/mix/lib/mix/tasks/compile.all.ex
The `compile_path` should not be cached as per the comment.
=> Fix compilation path caching

lib/mix/lib/mix/tasks/release.init.ex
Using pushd that takes consideration for the drive in the path, when it is different form where the command is launch.
Reference to #13820
=> Moving to good directory with good drive on windows

lib/elixir/lib/kernel.ex, lib/ex_unit/lib/ex_unit.ex, lib/mix/lib/mix.ex, lib/mix/lib/mix/tasks/release.ex
Docs only changes. Some links were 404, some having obsolete anchors. Quickly checked other links as well, everything else should be fine.
=> Fix broken/outdated erlang doc links

lib/elixir/pages/getting-started/recursion.md
This should provide a link for a reader to investigate more about that new syntax shown in the example.
=> docs: add link to capture syntax

lib/elixir/lib/module/types/descr.ex, lib/elixir/test/elixir/module/types/descr_test.exs
1. Add map_delete, map_fetch, map_put operations for map types
2. Rework function map_split_on_key into two direct functions map_get and map_delete 
3. Add an optimization for map_difference.
If we are doing the difference of an open map with a single key, we can directly compute the difference of that key in both maps to simplify the result.
4. Also, added the possibility for map keys to be `not_set()` since it is used in `map_delete`.
=> Add map delete, put, fetch type operations 

.github/workflows/release.yml
Before this patch, release.yml workflow was only compiling and publishing builds on tag pushes.
This patch additionally handles branch pushes (main, v1.17, etc) and publishes them to corresponding releases (main-latest, v1.17-latest, etc).
When we first looked at using GitHub releases for main builds, we discarded the idea because we didn't want to keep re-creating (and thus sending out notifications) releases. There was no API to update the SHA the release was pointing to either. It's obvious in hindsight but all we need to do is to update the _tag_ with the latest SHA and force-push the tag that the release is pointing to. So it is logically the same release but we update the SHA (through tag) and upload updated release assets.
Demo:
We now have two places where we build main and …
=> Add releases for main & maintenance branches

lib/elixir/lib/map.ex
Addition to description of Map.pop!/2
=> Map.pop!/2 description modification

.github/workflows/release.yml
I see that we've already requested a token with attestation permission. So the GITHUB_TOKEN environment variable might not be necessary anymore. 
Here is the test removed from my fork repository https://github.com/wingyplus/elixir/actions/runs/10907530737.
=> Remove GITHUB_TOKEN out of attest-build-provenance

lib/elixir/pages/mix-and-otp/docs-tests-and-with.md
Suppresses compiler warning about single quoted strings.
Before:
```
warning: single-quoted strings represent charlists. Use ~c"" if you indeed want a charlist or use "" instead
│
12 │     {:ok, socket} = :gen_tcp.connect('localhost', 4040, opts)
│                                      ~
│
└─ test/kv_server_test.exs:12:38
```
After:
no warning emitted.
=> Use ~c to represent charlist arg for :gen_tcp.connect/3

lib/elixir/lib/calendar/iso.ex, lib/elixir/test/elixir/calendar/duration_test.exs
The parsing of fractional durations checked for non-negativity by testing `second > 0`, which reports `false` for not only negative integers but also for 0.
The JavaScript libraries that I tested disagree whether "-PT-0,6S" represents a positive or negative duration, "moment" and "tinyduration" reported positive, "luxon" (the successor to moment) reported negative. My reading of the specification gives me no reason to doubt that a double negative should result in anything but a positive total result.
It is worth mentioning that as the scale units are represented as integers, there is no clean way to implement fractional parsing of non-second units. Currently, fractional non-second durations simply fail to parse. [Wikipedia](https://en.wikipedia.org/wiki/ISO_8601#Durations) gives "0.5Y" as …
=> Fix parsing of fractional durations

lib/elixir/lib/inspect/algebra.ex, lib/elixir/test/elixir/code_formatter/calls_test.exs, lib/elixir/test/elixir/config/provider_test.exs
Tentative fix for https://github.com/elixir-lang/elixir/issues/13775
The problem is that the closing bracket `")"` is ignored when evaluating the nested group for which fitting is enabled.
```elixir
["f" · disable([
²⟨"(" · _⟩ · ²⟨enable([
²⟨"%" · ∅ · "{" · _ · ["x"]⟩ · _ · "}"
])⟩ · _ · ")" · ∅
])]
```
The approach:
- `fits?` doesn't return a bool anymore, but `:fit | :no_fit | :break_next`, `:break_next` meaning that we wouldn't actually fit without breaking within the nested `:enabled`
- add more modes to `format` to make sure we break in the nested `:enabled`
=> Formatter fix: next_break_fits respects line_length

lib/elixir/lib/string.ex
A minor proposal inspired by the explanation in https://hexdocs.pm/elixir/String.html#split_at/2 to improve discoverability.
=> Explicit String.at/2 access cost and alternatives

lib/logger/test/logger/translator_test.exs
This patch fixes logger tests when running with Erlang 27.1. I have also made backward compatibility, which at least works with Erlang 27.0.1.
Have tested `v1.17` and `main` branches with Erlang 27.1 and 27.0.1.
Based on forum discussion: https://elixirforum.com/t/elixir-v1-17-3-released/66156/2
=> Fix logger translator tests under erlang 27.1

lib/logger/lib/logger.ex
Hi,
This is causing layout issue in [main](https://hexdocs.pm/logger/main/Logger.html) docs
Thanks.
=> fixes Logger docs layout

.formatter.exs, lib/elixir/lib/code.ex, lib/elixir/lib/code/formatter.ex, lib/elixir/lib/code/normalizer.ex, lib/elixir/lib/macro.ex, lib/elixir/test/elixir/code_formatter/containers_test.exs, lib/elixir/test/elixir/code_formatter/literals_test.exs, lib/elixir/test/elixir/code_formatter/migration_test.exs, lib/elixir/test/elixir/code_normalizer/formatted_ast_test.exs, lib/elixir/test/elixir/macro_test.exs
This is the first step of reworking how we organize and define migration options to the formatter, which can be summarized by the following doc update:
- `normalize_` options become `migrate_` options
- instead of being `true` by default, `migrate_` options will default to a new `migrate` option, itself defaulting to `false`
- `Code.quoted_to_algebra` was relying on `normalize_charlists_as_sigils` so that charlists would be represented as sigils => should be the responsibility of the normalizer, this is now fixed
- the biggest part of the actual diff is actually fixing tests and moving migration tests to their own file
Next steps:
- add `migrate_unless`
- add the `--migrate` option to `mix format`
=> Rework migrate options for the formatter

lib/elixir/lib/code/fragment.ex, lib/elixir/test/elixir/code_fragment_test.exs
Related to part 1. of https://github.com/elixir-lang/elixir/issues/13818
=> Fix Code.Fragment.surround_context for keyword keys

lib/elixir/lib/code.ex, lib/elixir/lib/code/formatter.ex, lib/elixir/test/elixir/code_formatter/migration_test.exs
Take 2 for https://github.com/elixir-lang/elixir/pull/13769.
The prep work has been done in:
- https://github.com/elixir-lang/elixir/pull/13841
- https://github.com/elixir-lang/elixir/pull/13808
=> Add :migrate_unless option to formatter

lib/elixir/src/elixir_bitstring.erl, lib/elixir/src/elixir_tokenizer.erl, lib/mix/lib/mix/tasks/format.ex, lib/mix/test/mix/tasks/format_test.exs
The second commit is suggesting to run `mix --format` as previously suggested - open to more suggestions about the wording or formatting of the message.
=> Add --migrate flag to mix format

lib/elixir/lib/code/formatter.ex, lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
Running `format --migrate` would break the Elixir codebase as of now, this PR fixes it:
- by avoiding formatting unless within `defmacro` - we can resue this approach for the pipe operator for [this](https://github.com/elixir-lang/elixir/issues/12122#issuecomment-2366508169)
- removing a test for `dbg` since we plan to deprecate - or is that too early? I can perhaps try to find a workaround using `Code.eval_string` in this case
=> Disable migrate_unless within defmacro

lib/elixir/lib/kernel.ex
I think we are now ready? Or should we wait 1.19.0?
=> Soft-deprecate Kernel.unless/2

lib/elixir/pages/getting-started/case-cond-and-if.md, lib/elixir/pages/meta-programming/macros.md
I think it is actually a nice simplification since it's one less thing in the getting started.
I'm also trying to rewrite [the macro guide](https://hexdocs.pm/elixir/macros.html) which is using `unless` as an example, I'm not sure what's the best candidate:
- `if`: less trivial and a tad verbose because will need to write it in terms of `case`
- `&&`: should be straightforward to change the existing guide, and can easily be implemented in terms of `if` (but maybe less "interesting/impressive" than implementing `if`?)
- keep unless?
- something else?
=> Remove mentions to unless/2 in the case/cond/if guide

lib/logger/lib/logger.ex
The previous docs didn't mention that logger may drop messages entirely, which I think is important to call out (and not just because I finished a long debugging journey to find these :) ).
This should give a fair overview of the built-in overload protections, similar to what I tried to do in erlang/otp#8855
I think this can really help folks be aware of some of these.
As always, thank you a lot for all your work :green_heart:
=> Provide some more pointers for logger overload protection

lib/elixir/lib/code/formatter.ex, lib/elixir/test/elixir/code_formatter/migration_test.exs
[See conversation here](https://github.com/elixir-lang/elixir/pull/13844#discussion_r1771993140)
```elixir
unless Widget |> where(foo: ^bar) |> Repo.exists?(), do: ...
if Widget |> where(foo: ^bar) |> Repo.exists?() |> Kernel.!(), do: ...
if !(Widget |> where(foo: ^bar) |> Repo.exists?()), do:
```
this behaviour is unchanged. any desire for consistency across all pipes, rather than different behaviour with 1-vs-2+?
```elixir
a |> unless(...)
!a |> if(...)
a |> b() |> unless(...)
a |> b() |> Kernel.!() |> if(...)
```
=> unless rewrites: don't use `Kernel.!` in conditions in the head

lib/elixir/pages/mix-and-otp/genservers.md
First, a big thank you to all the maintainers for the amazing work on keeping this language so wonderful! ❤️
Allow me to contribute a tiny PR.
As I followed the Genservers documentation page, I came across two places which I thought could be improved.
First, a small article misuse fix.
Secondly, I noticed the term `dictionary`. However, I believe we're actually dealing with `map`s in that section. Furthermore, `dict`s are deprecated now.
=> Fix lexical errors in genservers doc

lib/elixir/lib/config.ex
Corrects a link to a moved section after the changes related to anti-pattern documentation.
=> Use direct link for application config information

Makefile
* `man/iex.1` & `man/elixir.1` are evaluated from `BUILD_MANPAGES`
* no diff in output of `build_man`.
```shell
commit 458a00b2a (HEAD -> makefile)
Author: Ariel Otilibili <otilibil@eurecom.fr>
Refactored pre-requisites of `build_man`
0
Switched to branch 'main'
Your branch is up to date with 'origin/main'.
commit b5282802a (HEAD -> main, origin/main, origin/HEAD)
Author: Jean Klingler <sabiwara@gmail.com>
Disable migrate_unless within defmacro and remove dbg for unless (#13850)
0
0
```
=> Refactored pre-requisites of `build_man`

lib/elixir/pages/references/operators.md
[The new `...` operator](https://github.com/elixir-lang/elixir/commit/d68c8d6cddadd8ec5995dddaf4cee0e22e4ca440#diff-7e4167a9de48e2dcae64fae18a5b2ddad1d4aeff8f2dde274eb6f127ef65ac11R148) snuck by me, and it's perfect for something I've wanted to do in Matcha for a while. This PR documents it in the [Operators reference > Custom and overridden operators > Defining custom operators](https://hexdocs.pm/elixir/operators.html#defining-custom-operators) listing to increase visibility.
=> Document new unused `...` operator in correct place in operators.md

lib/mix/lib/mix/tasks/test.ex
I was hunting down a slow test and wasn't sure if `--slowest` and `--slowest-modules` considered time spent in `setup` and `setup_all`.  
After some testing, I found that they both count time spent in `setup` and neither counts the time spent in `setup_all`.  
Maybe this is obvious to other people, but it wasn't to me, and might be worth adding to the documentation. 
---
Here are the updated docs:
=> Update docs for mix test --slowest and --slowest-modules

lib/elixir/src/elixir_erl_pass.erl, lib/elixir/test/elixir/fixtures/dialyzer/with_throwing_else.ex, lib/elixir/test/elixir/kernel/dialyzer_test.exs
Close https://github.com/elixir-lang/elixir/issues/13868
Note: I tried to add "generated" to a bunch of places, like to the `call` or to all else clauses, but it didn't fix it.
This ended up being the solution.
=> Fix another dialyzer Kernel.with edge case

lib/elixir/lib/supervisor.ex
change `c:init/1` to`init/2` in the `typedoc`'s text
=> fix  #13864: `typedoc` for `init_option`

lib/mix/lib/mix/tasks/new.ex
The .gitignore file would reference '/.fetch' files, which caused some confusion (cf.
https://elixir-lang.slack.com/archives/C03EPRA3B/p1727706411018609).
Some research suggests that these files are no longer generated as of commit 59b6e2ee8bce86b424a9825915f6d91f81d8e770 so let's stop mentioning them in the .gitignore, too.
=> Update .gitignore generated by 'mix new'

lib/elixir/lib/agent.ex, lib/elixir/lib/gen_event.ex, lib/elixir/lib/gen_server.ex, lib/elixir/lib/inspect/algebra.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/map_set.ex, lib/elixir/lib/regex.ex, lib/elixir/lib/registry.ex, lib/elixir/lib/stream.ex
Some functions are using a mix of `any` and `term` within the same signature, which somebody pointed out to me is confusing as it seems to indicate some kind of nuance.
I know that specs are not meant to stay forever, so I gave up fixing all instances of `any`, but I searched for these mixed specs and replaced `any` by `term` (sometimes in other functions of the same module too) for consistency.
```elixir
Path.wildcard("lib/**/*.ex") |> Enum.flat_map(fn file -> File.read!(file) |> Code.string_to_quoted() |> Macro.prewalker() |> Stream.filter(&match?({:@, _, [{x, _, _} | _]} when x in [:spec, :callback], &1)) |> Stream.map(&Macro.to_string/1) |> Stream.filter(& &1 =~ ~r/\bany\b/ && &1 =~ "term") |> Stream.map(& file <> "\t" <> &1)  end) |> Enum.each(&IO.puts/1)
```
=> Replace any -> term in modules or functions mixing them

lib/elixir/pages/mix-and-otp/agents.md
I think it is better to rename the variable in this case and avoid indirectly referring to a deprecated module.
> [!NOTE]
> The term "dict" or "dictionary" is still used in several areas in the project (not only documentation), is it better to handle all of them in a single PR?
=> Replace "dict" with "map" in Agents documentation page

lib/elixir/pages/getting-started/keywords-and-maps.md
Minor fix. There is no `get_in/3`. `get_in/2` is the one that allows dynamic access.
=> docs: replace get_in/3 with get_in/2 in maps guide

lib/elixir/pages/getting-started/basic-types.md
This might be confusing otherwise especially for an [explanation about arity](https://hexdocs.pm/elixir/1.17.3/basic-types.html#identifying-functions-and-documentation).
=> Fix signature of trunc/1 in guide

lib/elixir/pages/getting-started/basic-types.md, lib/elixir/pages/getting-started/case-cond-and-if.md, lib/elixir/pages/getting-started/lists-and-tuples.md, lib/elixir/pages/getting-started/pattern-matching.md
Draft for discussion following https://github.com/elixir-lang/elixir/pull/13882.
In the first 4 pages of the getting starting guide, we don't really need the notion of arity, it first comes up in the [Anonymous function](https://hexdocs.pm/elixir/1.17.3/anonymous-functions.html) guide.
As a first step, I tried to edit these pages to consistently use arity-less links, to see how it would look like.
If we prefer to keep some functions with arity, I could edit the PR to at least preserve new links that were not links at all, e.g. `rem`.
A next step could be to move the arity explanation to anonymous functions.
=> Consistently use links without arities in getting started first pages

lib/elixir/lib/code.ex, lib/elixir/lib/task.ex, lib/elixir/lib/task/supervisor.ex, lib/elixir/pages/getting-started/basic-types.md, lib/elixir/pages/getting-started/binaries-strings-and-charlists.md, lib/elixir/pages/getting-started/debugging.md, lib/elixir/pages/getting-started/module-attributes.md, lib/elixir/pages/getting-started/modules-and-functions.md, lib/elixir/pages/getting-started/try-catch-and-rescue.md, lib/elixir/pages/meta-programming/macros.md, lib/elixir/pages/mix-and-otp/distributed-tasks.md
Cf individual commits for more details
=> Various small improvements in guides and docs

lib/elixir/pages/getting-started/anonymous-functions.md, lib/elixir/pages/getting-started/basic-types.md
From this [page](https://hexdocs.pm/elixir/1.17.3/basic-types.html#identifying-functions-and-documentation) to this [one](https://hexdocs.pm/elixir/1.17.3/anonymous-functions.html), as previously suggested in https://github.com/elixir-lang/elixir/pull/13885.
I think it is quite natural, since this page relies on the concept of arity, and we don't need it up to this point.
Split the commit into move & (minor) edit for easier review.
=> Move fun/arity explanation later in getting started

lib/mix/lib/mix/project.ex, lib/mix/lib/mix/tasks/clean.ex, lib/mix/lib/mix/tasks/deps.clean.ex, lib/mix/lib/mix/tasks/deps.get.ex, lib/mix/lib/mix/tasks/deps.unlock.ex, lib/mix/lib/mix/tasks/deps.update.ex
Wraps `mix deps.{get,update,unlock,clean}` in a lock to avoid conflicts with concurrent `deps/` and `mix.lock` writes.
=> Wrap deps tasks in a lock

.github/workflows/release_pre_built/action.yml
This is regression by https://github.com/elixir-lang/elixir/pull/13845. Docs artifact needs to fetch the tags before start building it to make version selection works.
Fixes #13892
=> Fetch tags before building docs

lib/elixir/lib/inspect/algebra.ex
I noticed this function was public without a doc, should we document it or hide it?
It was added in the context of a [formatter bug fix](https://github.com/elixir-lang/elixir/commit/4212fbf36e65b062430877cdadee5c1f33e10ae0#diff-c39f084ee74a44527298ef9e4b035e263913b9f07dc9940823bb1b8504fad600R585), so probably the latter?
=> Add @doc false to Inspect.Algebra.no_limit/1

lib/elixir/pages/getting-started/processes.md
As it stands, it could be interpreted as if one of the clauses supported is `case/2` which isn't the intent.
Reworded to use `exactly` instead of `such` to match the wording in https://hexdocs.pm/elixir/Kernel.SpecialForms.html#receive/1-variable-handling
=> docs: reword similarity between receive/1 and case/2 in getting-started/processes

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
Take 2 for https://github.com/elixir-lang/elixir/pull/12477, without using the process dict, as a draft for discussion.
I also added tests for guards and `WithClauseError` which needed to be taken into account.
=> Add more info for :with expressions in dbg/1

lib/elixir/lib/inspect.ex, lib/elixir/lib/list/chars.ex, lib/elixir/lib/string/chars.ex
This is a suggestion to use the `Float.to_string/1` and `Float.to_charlist/1` functions in the `String.Chars` and `List.Chars` protocols. Furthermore, it also changes `Inspect` to use `Float.to_charlist/1`. The reasoning behind is consistency, so the functions match the others in the protocols.
This PR, updates the functions in the same places as updated in https://github.com/elixir-lang/elixir/pull/13046 except for in Float itself.
The changes all refer to these lines in Float:
https://github.com/elixir-lang/elixir/blob/ed75e6066cafe9feca5ca9d6894361a9745c1f95/lib/elixir/lib/float.ex#L602
https://github.com/elixir-lang/elixir/blob/ed75e6066cafe9feca5ca9d6894361a9745c1f95/lib/elixir/lib/float.ex#L631
=> Use Float.{to_string/1, to_charlist/1} when possible

lib/elixir/lib/integer.ex
This pr simplifies digits and undigits and removes some guard clauses.
- Removes redundant `do_` from the function heads which are separated by their arity anyway.
- Simplify guard clauses
=> Simplify Integer.digits/2 and Integer.undigits/2

lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/lib/ex_unit/runner.ex, lib/ex_unit/lib/ex_unit/server.ex, lib/ex_unit/test/ex_unit_test.exs
This is a proposal to add a new `ExUnit.Case` option to support more use cases for running tests concurrently.
This addresses situations like the following example.
Imagine you have several test modules that depend on resources which can't be used concurrently.
These test modules depend on `MockServiceA`:
- `ServiceA.Module1Test`
- `ServiceA.Module2Test`
And these test modules depend on `MockServiceB`:
- `ServiceB.Module1Test`
- `ServiceB.Module2Test`
Because access to the two mock services needs to be serialized, we can't use the `:async` option and that means all tests are executed sequentially even though tests that only depend on one of the services can run concurrently with other tests that don't depend on it.
```
CPU0: ServiceA.Module1Test -> ServiceA.Module2Test -> …
```
=> Support `:group` option in ExUnit

lib/elixir/lib/access.ex
This had been bugging me for a bit, so here's a pull request to fix it.
=> Fix a small typo in a warning in Access

CHANGELOG.md, lib/elixir/lib/macro.ex
=> Fix warning when dbg with/1 with catch-all clause

lib/iex/lib/iex/helpers.ex, lib/iex/lib/iex/mix_listener.ex, lib/mix/lib/mix.ex, lib/mix/lib/mix/compilers/elixir.ex, lib/mix/lib/mix/project.ex, lib/mix/lib/mix/pubsub.ex, lib/mix/lib/mix/pubsub/subscriber.ex, lib/mix/lib/mix/sync/lock.ex, lib/mix/lib/mix/sync/pubsub.ex, lib/mix/lib/mix/task.compiler.ex, lib/mix/lib/mix/tasks/compile.all.ex, lib/mix/lib/mix/tasks/compile.elixir.ex, lib/mix/lib/mix/tasks/compile.ex, lib/mix/lib/mix/tasks/deps.loadpaths.ex, lib/mix/lib/mix/tasks/loadpaths.ex, lib/mix/test/fixtures/compile_listeners/deps/reloader/lib/reloader.ex, lib/mix/test/fixtures/compile_listeners/deps/reloader/mix.exs, lib/mix/test/mix/sync/lock_test.exs, lib/mix/test/mix/sync/pubsub_test.exs, lib/mix/test/mix/tasks/compile_test.exs
This introduces Mix listeners API. A project may specify listeners as follows:
```elixir
def project do
[
...,
listeners: [SomeDep.MixListener]
]
end
```
or
```elixir
config :mix, :listeners, [SomeDep.MixListener]
```
where each listener is a child spec. A listener is started on Mix startup (after `deps.loadpaths`) and receives events as messages. Currently the only message is `{:modules_compiled, info}` and `info.module_diff` specifies which modules have been added/changed/removed. Also, for now we have a restriction such that listeners must come from dependencies or be already in the path (since we start listeners right after `deps.loadpaths`).
One immediate use case that this PR implements is IEx. Up to this point, IEx didn't know when `mix compile` was called separately, so a …
=> Add API for listening to concurrent mix compilations

lib/mix/lib/mix/compilers/elixir.ex, lib/mix/lib/mix/compilers/erlang.ex, lib/mix/lib/mix/tasks/compile.elixir.ex, lib/mix/lib/mix/tasks/compile.erlang.ex, lib/mix/test/mix/sync/pubsub_test.exs, lib/mix/test/mix/tasks/compile_test.exs
Follow up to #13896.
One thing to note is that `:compile.file` removes the file and if the compilation fails, there is no .beam file. This means that a module may be notified as changed, but it has no file on the disk. Not sure if we should convert such entries as deleted, or ignore them, or perhaps keep as changed.
=> Notify modules diff from compile.erlang

lib/mix/lib/mix/task.compiler.ex, lib/mix/lib/mix/tasks/deps.compile.ex, lib/mix/lib/mix/tasks/deps.loadpaths.ex, lib/mix/test/fixtures/compile_listeners/deps/reloader/lib/reloader.ex, lib/mix/test/mix/tasks/compile_test.exs
Sends `{:dep_compiled, info}` after every dependency compiled with `deps.compile`. This can be used to detect when rebar/make dependencies are recompiled (in which case the listener may want to purge all modules from that dependency).
=> Notify each dep compilation from deps.compile

lib/elixir/lib/uri.ex
This PR aims to improve doc of `URI.encode`:
+ Provide a clearer explanation for the `predicate` argument, including its execution logic and the built-in functions that can be used.
+ List common use cases for the built-in functions. For example, `URI.char_unescaped?/1` for the whole URL, `URI.char_unreserved?/1` for URI components.
+ Correct the line - "See `encode_www_form/1` if you are interested in escaping reserved
characters too.", which is not very precise:
* if we want to escape reserved characters, we should use `URI.char_unreserved?/1`, not `URI.encode_www_form/1`.
* We only use `URI.encode_www_form/1` when we want to encode a string as "x-www-form-urlencoded".
+ Remove the explanation of truthy and falsy values, as we should assume developers are already familiar with them. …
=> Improve doc of URI.encode

lib/mix/lib/mix/compilers/elixir.ex, lib/mix/lib/mix/compilers/erlang.ex, lib/mix/lib/mix/task.compiler.ex, lib/mix/lib/mix/tasks/clean.ex, lib/mix/lib/mix/tasks/compile.all.ex, lib/mix/lib/mix/tasks/compile.elixir.ex, lib/mix/lib/mix/tasks/compile.erlang.ex, lib/mix/lib/mix/tasks/compile.ex, lib/mix/test/mix/tasks/compile.elixir_test.exs, lib/mix/test/mix/tasks/compile.erlang_test.exs, lib/mix/test/mix/tasks/compile_test.exs
Adds `Mix.Task.Compiler.diagnostics()` that fetches all warning diagnostics persisted by each compiler in its manifest.
=> Add API for fetching all persisted compiler diagnostics

lib/elixir/lib/code/fragment.ex, lib/elixir/test/elixir/code_fragment_test.exs
Close https://github.com/elixir-lang/elixir/issues/13818
There is a precedent for the name `capture_arg` is used [here](https://github.com/elixir-lang/elixir/blob/5902c29ad5f264021a9a9b447a25e2d8b4c45ea4/lib/elixir/src/elixir_fn.erl#L198-L201), so I thought it would be clear, but happy to rename it.
=> Code.Fragment.surround_context/2 handles &123 as :capture_arg

lib/elixir/lib/macro.ex, lib/elixir/src/elixir_quote.erl, lib/ex_unit/test/ex_unit/doc_test_test.exs
As discussed [here](https://github.com/elixir-lang/elixir/pull/13905#issuecomment-2418081776).
=> :prune_metadata keeps delimiters

lib/elixir/lib/code/normalizer.ex, lib/elixir/test/elixir/code_normalizer/quoted_ast_test.exs
This is the first issue described in https://github.com/elixir-lang/elixir/issues/13895.
=> Fix crash in Macro.to_string

.github/workflows/release.yml
Adds attestations to the releases. This makes it simpler for consumers to check the build provenance of the uploaded release artifacts.
This will also improve the [OpenSSF Scorecard](https://scorecard.dev/) Score for [Signed Releases](https://github.com/ossf/scorecard/blob/ea7e27ed41b76ab879c862fa0ca4cc9c61764ee4/docs/checks.md#signed-releases) from 0 to 8 once the 10 most recent release artifacts are signed.
=> Upload Release Attestations

lib/mix/lib/mix/project.ex
The lock can be useful in other projects. For example in the Phoenix code reloader we want to implement a mix listener and purge stale modules before compilation, which should happen within a lock, as we do in `IEx.Helpers.recompile/1`:
https://github.com/elixir-lang/elixir/blob/f17fc8b4c30c7143a527ceacf8d9a603ae14f54a/lib/iex/lib/iex/helpers.ex#L139-L142
=> Make Mix.Project.with_build_lock/2 public

lib/elixir/pages/mix-and-otp/genservers.md
Simple change from `bk` to `bucket` for consistency with the rest of the doc
=> Update genservers.md - change `bk` to `bucket`

lib/elixir/lib/code/normalizer.ex, lib/elixir/test/elixir/code_normalizer/quoted_ast_test.exs
=> Fix edge case in normalizer for keyword args

lib/elixir/lib/option_parser.ex, lib/elixir/test/elixir/option_parser_test.exs
Given this scenario:
`OptionParser.parse!(["--foo_bar", "baz"], strict: [foo_bar: :string])`
the current error message is:
```
** (OptionParser.ParseError) 1 error found!
--foo_bar : Missing argument of type string
(elixir 1.17.2) lib/option_parser.ex:301: OptionParser.parse!/2
iex:5: (file)
```
This PR fixes it to instead be
```
** (OptionParser.ParseError) 1 error found!
--foo_bar : Unknown option. Did you mean --foo-bar?
(elixir 1.17.2) lib/option_parser.ex:301: OptionParser.parse!/2
iex:5: (file)
```
=> fix(OptionParser): correct error message when flag has underscores

lib/elixir/lib/module/behaviour.ex, lib/elixir/lib/module/types.ex, lib/elixir/lib/module/types/expr.ex, lib/elixir/lib/module/types/helpers.ex, lib/elixir/lib/module/types/of.ex, lib/elixir/lib/module/types/pattern.ex, lib/elixir/test/elixir/module/types/expr_test.exs, lib/elixir/test/elixir/module/types/type_helper.exs
The main goal is to allow checking to continue even if it finds typing violations, so we can infer return types. The violations are replaced by `dynamic()`. Only the first violation is reported to avoid cascading failures.
=> Refactor the current type checker for return type inference

lib/elixir/lib/module/types/descr.ex, lib/elixir/test/elixir/module/types/descr_test.exs
Add type safe operators to perform tuple insertion and deletion at a given integer index.
Deals with dynamic by considering which values make the operation succeed (e.g., inserting at position 2 into a tuple requires tuples of size at least 2)
=> Add tuple type operators for insertion and deletion

lib/elixir/pages/getting-started/keywords-and-maps.md
based on watching theprimeagen stream where he was learning elixir, i noticed confusion around keyword lists. i tried to make it more clear. josé valim asked me in twitch chat if i could make a PR, so here's my attempt. 
first example talking about keyword lists actually doesn't contain a keyword list, so the user is trying to parse where the keyword list is, but it doesnt exist. made more clear that we'll get there.
made more clear how multiple optional arguments look in syntax and reinforce the 3 syntax formats for keyword lists.
the ecto query example is confusing, it's not obvious how it relates to keyword lists, so tried to make it more clear by giving expansion of function it would generate. should be confirmed it's correct. 
same for if/2, that it takes in a keyword list. 
lastly, …
=> updates to keywords_and_maps documentation

lib/elixir/pages/mix-and-otp/introduction-to-mix.md, lib/mix/lib/mix/tasks/compile.elixir.ex, lib/mix/lib/mix/tasks/xref.ex
As discussed in #13762 ([comment](https://github.com/elixir-lang/elixir/issues/13762#issuecomment-2275246711)), I added a "transitive dependencies" section to "Meta-programming anti-patterns".
I obviously open to feedback, whether typos or more general remarks about the content of the section. I've tried to keep it simple whilst exposing the problem, linking to `mix xref` when complexity arises.
This also fixes the documentation of `mix xref` a bit, since it only stated "runtime dependencies" can cause compile-connected ones, whilst all dependencies are affected.
=> Add transitive dependencies section to Meta-programming anti-pattern

lib/elixir/lib/record.ex, lib/elixir/test/elixir/record_test.exs
cc @jonatanklosko @lukaszsamson
=> Store record metadata in the documentation chunk

lib/elixir/lib/kernel/parallel_compiler.ex
While going over the compilation times of our big monolith with @josevalim , we were suspecting that some steps of the `ParallelCompiler` could be taking a while.
As such, this MR introduces two additional logs about the time it takes to:
- Execute the `each_cycle` callback;
- Execute the `spawn_workers/8` function when we might be in a deadlock situation.
=> Parallel compiler emits more profile info

lib/elixir/pages/anti-patterns/code-anti-patterns.md
:nail_care: Thank you for the anti-pattern docs on this!
This behavior is totally not obvious due to how the optimization works.
=> Chore: Fix typo

lib/elixir/lib/macro.ex, lib/elixir/src/elixir_quote.erl, lib/elixir/test/elixir/code_normalizer/quoted_ast_test.exs, lib/elixir/test/elixir/kernel/expansion_test.exs, lib/elixir/test/elixir/kernel/quote_test.exs, lib/elixir/test/elixir/macro_test.exs, lib/mix/test/mix/tasks/xref_test.exs
I didn't fix all tests yet, this is a proof of concept for discussion.
The idea is to introduce a shallow validation when using `unquote`, to give early feedback to meta-programmers when building obviously invalid AST which might fail later down the lane in a way that would then be non-obvious and harder to debug.
In order to avoid any slowdown especially when building complex ASTs, we do not loop on the whole AST (args just have to be a list), but this could catch many trivial errors e.g. forgetting to escape a map.
I had the idea on the back of my mind for a while, but https://github.com/elixir-lang/elixir/issues/13948 reminded me of it.
Note: This could perhaps just be a warning for now if we want to be conservative.
=> Proposal: shallow validation of unquoted AST

lib/elixir/src/elixir_parser.yrl, lib/elixir/test/elixir/kernel/parser_test.exs
Blocks with a single expression are not present in the AST, so for expressions like `(1 + 2) * 2` there is no way to tell if the parentheses are in the source.
cc @mhanberg for Spitfire :D
cc @lukaszsamson
=> Add metadata about single-expression block closing/opening

lib/elixir/test/elixir/kernel/string_tokenizer_test.exs
Close #13951
As discussed in the issue, this is already fixed in main, but I thought perhaps adding a test to prevent future regressions would be beneficial? 🪃
=> Add test for call with thai atom

lib/elixir/src/elixir_quote.erl, lib/elixir/test/elixir/kernel/quote_test.exs
Extending https://github.com/elixir-lang/elixir/pull/13950 to `unquote_splicing`, which was just checking `is_list`.
=> Improve validation of unquote_splicing AST

lib/elixir/lib/code/formatter.ex, lib/elixir/lib/code/normalizer.ex, lib/elixir/lib/macro.ex, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/code_formatter/calls_test.exs, lib/elixir/test/elixir/code_formatter/operators_test.exs
Currently given a code `Foo."bar\nbaz"(1, 2)`, the formatter would keep adding extra `\` on every format.
=> Fix formatter adding extra escapes to remote call functions

lib/elixir/lib/module/types/descr.ex, lib/elixir/test/elixir/module/types/descr_test.exs
Computes the type of all values in a tuple
e.g. for `{integer(), atom()}` it is `integer() or atom()`
for `{float(), ...}` it is `term()` as there could be any other values inside
=> Add tuple values operator

lib/logger/lib/logger.ex
The documentation for this function stated that it would override primary logger level, which is not true.
=> Fix `Logger.put_process_level/2` note

lib/elixir/src/elixir_parser.yrl, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/kernel/parser_test.exs, lib/elixir/unicode/security.ex
Currently, the AST does not distinguish between `Foo.foo` and `Foo."foo"`. This adds `:delimiter` meta to the call root (where the identifier location is also stored), so similarly to atoms:
```
iex(1)> Code.string_to_quoted!(~S[:"🐈"],
...(1)>   token_metadata: true,
...(1)>   literal_encoder: &{:ok, {:__block__, &2, [&1]}}
...(1)> )
{:__block__, [delimiter: "\"", line: 1], [:"🐈"]}
iex(2)> Code.string_to_quoted!(~S[Foo."🐈"],
...(2)>   token_metadata: true,
...(2)>   literal_encoder: &{:ok, {:__block__, &2, [&1]}}
...(2)> )
{{:., [line: 1], [{:__aliases__, [last: [line: 1], line: 1], [:Foo]}, :"🐈"]},
[no_parens: true, delimiter: "\"", line: 1], []}
```
=> Add delimiter meta to demote calls with quoted identifier

lib/elixir/src/elixir_parser.yrl, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/kernel/parser_test.exs, lib/elixir/test/erlang/tokenizer_test.erl
Currently both `:'foo'` and `Foo.'foo'` have `delimiter: ~S["]` in the metadata, this changes it to single quote.
This also adds `:delimiter` meta for keyword atoms.
=> Fix delimiter metadata for single quote atoms and remote calls

.github/workflows/ci.yml
Hey there lovely folks! :green_heart: 
Commits should speak for themselves, only include a new OTP version and bump Ubuntu to 24.04 (20.04 will be EOL soon) both _should_ work but as usual the CI may foil my plans :)
Thanks for all your amazing work! :green_heart:
=> Bump ci (OTP 27.1 and Ubuntu 24.04)

lib/elixir/lib/uri.ex, lib/elixir/test/elixir/uri_test.exs
Only occurs when mixing strings and URIs, but the docs seem to encourage that.
Without the fix the test results in the following error:
```
1) test merge/2 (URITest)
test/elixir/uri_test.exs:376
** (KeyError) key :scheme not found in: "http://google.com/foo"
If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
code: assert URI.merge("http://google.com/foo", URI.new!("//example.com/baz"))
stacktrace:
(elixir 1.18.0-dev) lib/uri.ex:911: URI.merge/2
test/elixir/uri_test.exs:390: (test)
```
That's because that (one) particular clause didn't check for the base to be a `%URI{}`.
Happy to also backport it to the 1.17 branch (should be easy/ probably cherry-pickable) but:
1. seems like an extreme edge case
2. a workaround is available (use URI/URI …
=> Fix bug with schemaless URI in `URI.merge/2`

.github/workflows/ci.yml
During #13969 I saw that Windows also seemed a bit outdated but didn't wanna touch it yet (as less trust in Windows/experience with OTP testing on it)
According to setup-beam this should be possible:
https://github.com/erlef/setup-beam?tab=readme-ov-file#compatibility-between-operating-system-and-erlangotp
Unsure what the testing strategy for Windows is, but I went with "newest OTP minor for all supported OTP majors".
Thank you for all your work!
=> Bump Windows Runner & add more OTP versions

lib/logger/lib/logger/formatter.ex
Clarifies the current behavior as pointed out in https://elixirforum.com/t/charlist-values-are-not-showing-up-in-logger-metadata/67256.
Alternatively, we could support it by removing [this line](https://github.com/elixir-lang/elixir/blob/main/lib/logger/lib/logger/formatter.ex#L537) (but it would crash on invalid charlists) or add a `try/rescue` with `List.to_string`?
=> Clarify that charlists cannot be used as logger metadata

lib/elixir/src/elixir_parser.yrl, lib/elixir/test/elixir/kernel/parser_test.exs
Once we parse
```elixir
%{:key1 => 1, :key2 => 2}
```
the entries become `[{:key1, 1}, {:key2, 2}]` in the AST and there is no information about `=>`. This adds a `assoc: [line: ..., column: ...]` to the key AST nodes.
cc @mhanberg
=> Add AST metadata about assoc operator location

lib/elixir/lib/access.ex
Thank you for putting the time and effort in these informative error messages.
This PR fixes a typo in the error raised by `Access.get_and_update/3`
=> Fix typo in Access.get_and_update/3 error message

lib/ex_unit/lib/ex_unit.ex
Simplifies the language used to describe a "basic setup for ExUnit"
In particular, I removed the term "test case" which was an alias for a "test module". "test case" can easily be confused with a `test` block, so the explanation is something difficult to understand
=> Simplify the explanation of a basic test case

lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/lib/calendar/time.ex
The changes align `NaiveDateTime.from_erl` and `Time.from_erl` specs with their corresponding `NaiveDateTime.new` and `Time.new` specs.
The `new` function specs accept a non-negative integer or a tuple of {seconds, precision} for microseconds.
Here's `NaiveDateTime.new/8`'s spec: https://github.com/elixir-lang/elixir/blob/cb2e03688ec699b79676c1925c86ac83cfaf0edf/lib/elixir/lib/calendar/naive_datetime.ex#L248-L257
And `NaiveDateTime.from_erl`'s spec + implementation: https://github.com/elixir-lang/elixir/blob/cb2e03688ec699b79676c1925c86ac83cfaf0edf/lib/elixir/lib/calendar/naive_datetime.ex#L1004-L1011
Here's the `Time.new/5` spec: https://github.com/elixir-lang/elixir/blob/cb2e03688ec699b79676c1925c86ac83cfaf0edf/lib/elixir/lib/calendar/time.ex#L114-L120
And the corresponding `from_erl`: …
=> Tweak `NaiveDateTime.from_erl` and `Time.from_erl` specs

lib/elixir/lib/module/types/descr.ex, lib/elixir/test/elixir/module/types/descr_test.exs
Add pruning to tuple_difference and tuple_union. This eliminates obviously empty negations 
(such as `{integer(), atom()} and not {atom(), ...}`) from the representation, which drastically reduces its size in corner cases like the example added.
=> Improve perf of tuple operations

lib/elixir/lib/module/types/descr.ex, lib/elixir/test/elixir/module/types/descr_test.exs
Normalize list types before printing them. For instance, `list(integer()) or list(number())` will appear as `list(number())`.
=> Add list normalization for printing

lib/elixir/pages/references/gradual-set-theoretic-types.md
Fix a small typo in the `gradual-set-theoretics-types.md` documentation
=> Fix `tyoes` -> `types` typo

lib/elixir/lib/kernel.ex
This is a bit of a speculative PR. I'm not sure what the proper wording should be, but after a bit of discussion on Discord, this seems maybe okay.
My general complaint about the current text is that it's not very obvious why it's even there. The sentence starting with "However" seems like it may be better to remove entirely. However (heh), it seems like this can be improved. Really, there's a kind of strange table of behaviors possible for struct construction and updating, especially when involving `@enforce_keys`. Part of me feels like this can be ignored until potential improvements to the static type system, but I think it is and will still be somewhat relevant for runtime behavior.
I considered specifying that `struct/2` can produce results that don't exactly honor `@enforce_keys`, …
=> Clarify `struct!/2` update behavior

lib/elixir/src/elixir_parser.yrl, lib/elixir/test/elixir/kernel/parser_test.exs
Supersedes #13995 to avoid traversing meta.
This changes the `:parens` meta from #13940, so that instead of
```elixir
[
parens: [
[line: 1, column: 5, closing: [line: 1, column: 13]],
[line: 1, column: 6, closing: [line: 1, column: 12]]
]
]
```
we do
```elixir
[
parens: [line: 1, column: 5, closing: [line: 1, column: 13]],
parens: [line: 1, column: 6, closing: [line: 1, column: 12]]
]
```
The list can still be retrieved easily by calling `Keyword.get_values/2`.
cc @mhanberg
=> Add separate metadata entry for every block parens

lib/elixir/lib/module/types/descr.ex, lib/elixir/test/elixir/module/types/descr_test.exs
The difference of two maps whose fields are the same but for one is equal to the first map, but with its differing field being subtracted the second map's field. This leads to printing simpler map types
e.g. `%{a: number(), b: atom(), c: pid()} and not %{a: integer(), b: atom(), c: pid()}` prints as `%{a: float(), b: atom(), c: pid()}`
=> Add map normalization case

lib/ex_unit/lib/ex_unit/diff.ex, lib/ex_unit/test/ex_unit/diff_test.exs, lib/ex_unit/test/ex_unit/formatter_test.exs
Solves #13624 When the elements are equal then we pass them as ast, when deleted or inserted we pass maps as `%{a: 1, b: 2}` and fall into inspect in safe_to_algebra. This pr changes maps to ast representation so it's formatted correctly in the function that handles maps.
I wrote a test, but I couldn't make it fail initially. However, it did fail when I added a regular assertion in my code. There are likely similar issues with other data structure, but now that I know what to change, it should be easier to extend the fix. It wasn't easy to find the issue with all the pattern matching in function heads and the single-element tuple which is not that easy to spot. It would be helpful to have a `dbg` implementation for multiple function heads.
=> Format inserted/deleted maps in list assertions 

lib/elixir/src/elixir_parser.yrl, lib/elixir/test/elixir/kernel/parser_test.exs
Edge case, but preferably we want to avoid loosing information.
=> Add token metadata to distinguish between :nil and nil

lib/elixir/lib/stream.ex
This is based on trying to clarify/make more obvious a missunderstanding I held until ~yesterday.
Namely I thought that calling an `Enum` function on a stream would result in the equivalent of `Enum.to_list` and hence all stream benefits would be forfeit. Yes, it should be clear seeing `Enum.take` work that this isn't the case, but it's not always so easy.
This turned out wrong as @benwilson512 pointed out eloquently here: https://elixirforum.com/t/why-is-stream-reduce-while-missing/34422/2
Not sure if this is the best place or way to highlight this in the docs, but I thought I'd give it a shot. One could argue that this documentation belongs in the `Enum` module, but for `Stream` documentation that module is the primary source - plus it's more about `Stream`s implementation of …
=> Clarify the interplay of `Stream` and `Enum`

lib/elixir/lib/process.ex
Previously, the example contained 2 issues.
1. A syntax error on `receive` as there were no parens.
2. The example was incomplete, and would hang on the 2nd receive
This commit updates the example to reflect the original intent, by sending 2 messages and getting a `:noproc` on the 2nd `receive`.
This was originally added in https://github.com/elixir-lang/elixir/commit/65829ef4e80406a30ddaaa27e92bdcbb4292a069#diff-8041c84ced048086c5c0b41e19df8d1ed59f0fdd769487a656ddac42f928d213R554
=> Fix docs for Process.monitor/2

lib/mix/lib/mix/project.ex
We were recently bit by costly code hiding in `project/0` config. Solved via moving to a lazy function `:docs` function value. Hoping to help others.
=> Add `project/0` warning

lib/elixir/lib/calendar/duration.ex
just wanted to remove the superfluous `s` on "extensions", but imho the subclause about "full compatibility" is not really helpful.
=> simplify docs for `Duration.to_iso8601/1`

lib/elixir/lib/calendar/datetime.ex, lib/elixir/lib/calendar/duration.ex, lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/test/elixir/calendar/duration_test.exs
Without this function, projects like Phoenix.HTML, Postgrex, and similar would have to implement this function over and over.
=> Add a human readable representation of duration

lib/iex/lib/iex/introspection.ex
This code added in 6951f0cd2af548fedb212d6c9b1284bc861841df was made obsolete in aee7fbc0dc3cdee77fbe3d4a6442b2e0b53afe5d (v1.1). Correct macrocallback handling was added in 04f151b68b0dc1e5679cda3fa66b70fe3e07579a (v1.10) and since then macro caller arg is passed to typespecs as `term()` instead of `Macro.Env.t()`
=> Remove not needed macrocallback code

lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/kernel/warning_test.exs, lib/elixir/test/erlang/atom_test.erl
Since this is my first contribution to Elixir (which I always loved), I am not really sure about the process :)
Should I also add a `CHANGELOG` entry? From the history it seems that not all people do that.
One extra question: now tests start to show warnings:
```
» make test
Generated elixir app
==> elixir (eunit)
warning: single quotes around calls are deprecated. Use double quotes instead.
└─ nofile:1:8
warning: single quotes around atoms are deprecated. Use double quotes instead.
└─ nofile:1:1
All 126 tests passed.
```
But, I fail to find the source code for them. Any ideas?
Closes https://github.com/elixir-lang/elixir/issues/13958
=> Deprecate single quites in quoted atoms and calls, refs #13958

CHANGELOG.md
Kind of strange to read that "a single operating system running Elixir"
=> Improve wording in CHANGELOG.md

lib/mix/lib/mix/tasks/compile.app.ex, lib/mix/test/mix/tasks/compile.app_test.exs
=> Touch the compile path when writing .app file for the first time

lib/elixir/lib/kernel.ex
Support min and max in guards, for: https://github.com/elixir-lang/elixir/issues/11985
How would you prefer this to be tested? I've looked through `kernel_test.exs` and `guard_test.exs` and I'm not seeing anything specific for guards that delegate to the Erlang builtin guards.
Thank you!
=> Support min and max in guards

lib/mix/lib/mix/tasks/do.ex, lib/mix/test/mix/tasks/do_test.exs
Yucksies!
```
→ mix do
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Mix.Tasks.Do.run/1    
The following arguments were given to anonymous fn/1 in Mix.Tasks.Do.run/1:
[]
(mix 1.17.3) lib/mix/tasks/do.ex:61: anonymous fn/1 in Mix.Tasks.Do.run/1
(elixir 1.17.3) lib/enum.ex:987: Enum."-each/2-lists^foreach/1-0-"/2
(mix 1.17.3) lib/mix/task.ex:495: anonymous fn/3 in Mix.Task.run_task/5
(mix 1.17.3) lib/mix/cli.ex:96: Mix.CLI.run_task/2
/Users/andrea/.asdf/installs/elixir/1.17.3/bin/mix:2: (file)
```
=> Improve error message on empty "mix do"

lib/mix/lib/mix/tasks/xref.ex
Because copy-pasting the current example results in an error:
```console
$ mix xref graph --format cycle
** (Mix) Unknown --format cycle in mix xref graph
```
But the "fix" works
```console
$ mix xref graph --format cycles | head
119 cycles found. Showing them in decreasing size:
Cycle of length 45:
extra/lib/plausible/stats/sampling.ex
lib/plausible/stats/query.ex
lib/plausible/stats/legacy/legacy_query_builder.ex
lib/plausible/stats/metrics.ex
extra/lib/plausible/stats/goal/revenue.ex
lib/plausible/goal/schema.ex
Failed to write log message to stdout, trying stderr
00:04:58.920 [error] Writer crashed (:epipe)
** (ErlangError) Erlang error: :terminated
(stdlib 6.0) io.erl:198: :io.put_chars(:standard_io, [[[], "    lib/plausible/auth/auth.ex"], 10])
(mix 1.17.1) …
```
=> Fix a typo in "mix xref" docs

lib/elixir/lib/range.ex
Was confused by the current warning, a bug can be introduced if somebody blindly adds `-1` as step.
=> Improve warning in Range.new/2 with negative step

lib/elixir/lib/json.ex, lib/elixir/test/elixir/json_test.exs
Should be backported if accepted.
=> Implement JSON.Encoder for Calendar types

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel_test.exs
Otherwise the type system complains about the fact that the `nil` clause is never used (in v1.18 rc.0):
To be backported once/if merged.
=> Fix type warning in pop_in/1

lib/elixir/lib/calendar/datetime.ex, lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/lib/code.ex, lib/elixir/lib/code/formatter.ex, lib/elixir/lib/io/ansi/docs.ex, lib/elixir/lib/system.ex, lib/elixir/test/elixir/code_formatter/migration_test.exs, lib/elixir/test/elixir/exception_test.exs, lib/elixir/test/elixir/file_test.exs, lib/elixir/test/elixir/io/ansi/docs_test.exs, lib/elixir/test/elixir/kernel/cli_test.exs, lib/elixir/test/elixir/kernel_test.exs, lib/elixir/test/elixir/macro_test.exs, lib/elixir/test/elixir/module/types/descr_test.exs, lib/elixir/test/elixir/path_test.exs, lib/elixir/test/elixir/uri_test.exs, lib/iex/lib/iex/helpers.ex, lib/mix/lib/mix/tasks/compile.ex, lib/mix/lib/mix/utils.ex
First step of https://github.com/elixir-lang/elixir/issues/12122.
~The next step is to add a warning indicating to run mix format.~ => we decided not to add any warning here, since there's no ambiguity
The second commit is just auto-generated.
=> Add :migrate_call_parens_on_pipe formatter option

Makefile
Prior to this we had a regression, the source link was using the tag as seen as the bottom of the screen:
=> Do not set docs source_ref to -latest tags

lib/elixir/lib/range.ex
=> improve warning message for range with negative step some more

lib/elixir/lib/process.ex
I believe the correct word is `then` not `than`
=> Correct typo in Process doc

lib/elixir/lib/module/types/descr.ex, lib/elixir/test/elixir/module/types/descr_test.exs
For printing types (tuples and maps), we do a general pass that fuses elements that differ by one element or less.
Example:
`{:ok, integer()} or {:ok, float()}` is shown as `{:ok, float() or integer()}`
`%{..., a: float()} or %{..., a: integer()}`is shown as `%{..., a: float() or integer()}`
and
```
:error or
({%Decimal{coef: :inf, exp: integer(), sign: integer()}, binary()} or
{%Decimal{coef: :NaN, exp: integer(), sign: integer()}, binary()} or
{%Decimal{coef: integer(), exp: integer(), sign: integer()}, term()} or
{%Decimal{coef: :inf, exp: integer(), sign: integer()} or
%Decimal{coef: :NaN, exp: integer(), sign: integer()} or
%Decimal{coef: integer(), exp: integer(), sign: integer()}, term()})
```
is shown as
```
:error or
({%Decimal{coef: integer() or (:NaN or :inf), exp: integer(), …
```
=> Fuse maps and tuples for printing

lib/elixir/pages/getting-started/alias-require-and-import.md
Reading the docs at the moment and loving them. 🎉
Fixes a typo in `alias-require-and-import.md`.
=> Fix typo in alias-require-and-import.md

lib/elixir/src/elixir_fn.erl, lib/elixir/test/elixir/kernel/expansion_test.exs, lib/elixir/test/elixir/kernel/fn_test.exs
=> Remove no_parens when using capture with arity

lib/elixir/lib/gen_server.ex, lib/elixir/lib/supervisor.ex
Make it easier to navigate docs and jump to relevant sections about [`:restart`](https://hexdocs.pm/elixir/1.18.0/Supervisor.html#module-restart-values-restart) and [`:shutdown`](https://hexdocs.pm/elixir/1.18.0/Supervisor.html#module-shutdown-values-shutdown) from [`GenServer`](https://hexdocs.pm/elixir/1.18.0/GenServer.html#module-how-to-supervise), and from/to [this](https://hexdocs.pm/elixir/1.18.0/Supervisor.html#module-child-specification).
After (GenServer)
After (Supervisor)
=> Improve doc navigability for child spec options

.github/workflows/release.yml
=> Fix Release Signing

lib/elixir/src/elixir_fn.erl, lib/elixir/test/elixir/kernel/fn_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs
Close https://github.com/elixir-lang/elixir/issues/14091
Separated the first commit for easier review: 5f5ef9c919213e1fdae6a2d1efee1e48f31851fb
We needed to make the decision **after** expansion, so we need to distinguish if we come from the arity notation and propagate this info.
Using the example from https://github.com/elixir-lang/elixir/issues/14089:
Feedback welcome on the wording, this isn't my strong suit :)
=> Deprecate complex module expressions in &mod.fun/arity captures

lib/ex_unit/lib/ex_unit/cli_formatter.ex, lib/ex_unit/test/ex_unit_test.exs, lib/mix/test/mix/tasks/test_test.exs
Discussed here: https://groups.google.com/g/elixir-lang-core/c/xh-hMsDi7c4
This PR omits the count of excluded tests from the overall test count in the CLI summary report
**Before:** `27 tests, 3 failures, 14 excluded`
**After:** `13 tests, 3 failures, 14 excluded`
=> [ex_unit] Omit excluded tests from test count in CLI summary

lib/elixir/lib/file.ex
Many typespecs did not exactly match the underlying [implementation](https://github.com/erlang/otp/blob/master/lib/kernel/src/file.erl#L652). For example. File.read can throw an error atom that is not defined inside File.posix() type.
```Elixir
iex(2)> File.read("\x00")
{:error, :badarg}
```
This change does not have the expected effect of generating a warning on patterns that are unable to match such as 
```Elixir
{:error, :non_existing_error} = File.read("path")
```
Because dialyzer is treating any union type with more than 13 members as the common type. When using File.posix() any atom is considered to be acceptable by dialyzer.
Even though type checking passes I think it makes sense to add the full specification in order to have complete documentation and make sure any implementation …
=> Update specs to match OTP definitions

lib/elixir/src/elixir_parser.yrl, lib/elixir/test/elixir/kernel/parser_test.exs
=> Remove duplicated metadata in nested call AST

lib/elixir/lib/macro.ex
=> Better document AST metadata in Macro

lib/elixir/lib/file.ex
the mistakes were introduced in https://github.com/elixir-lang/elixir/pull/14121
=> Fix mistakes in type specs in the File module

lib/elixir/lib/calendar/date.ex, lib/elixir/lib/module/types/apply.ex, lib/elixir/lib/module/types/descr.ex, lib/elixir/lib/module/types/expr.ex, lib/elixir/lib/module/types/helpers.ex, lib/elixir/lib/module/types/of.ex, lib/elixir/test/elixir/module/types/descr_test.exs, lib/elixir/test/elixir/module/types/integration_test.exs, lib/elixir/unicode/security.ex
=> Type checking of protocols in for-comprehensions

lib/elixir/lib/macro.ex
Missed in https://github.com/elixir-lang/elixir/pull/14120
=> Document `assoc` metadata entry

lib/mix/lib/mix.ex, lib/mix/lib/mix/sync/lock.ex
Apparently Android does not allow hard links, see https://groups.google.com/g/elixir-lang-core/c/YRpdDlH-aGA/m/PXLcuC3uBAAJ?utm_medium=email&utm_source=footer.
I believe that with an extra step we could adjust the implementation to work with symlinks (in our case, the useful property of hard links is that creating the link fails if the source file no longer exists). If you think it's worth it, I can revisit it in a separate PR, though for edge cases like this a flag may be enough.
=> Add an environment variable to optionally disable compilation locking

lib/elixir/lib/calendar/iso.ex
The benchmark with go made me think if we can get any speed gains in synthetic tests :D
This pr changes datetime formatting functions:
around 55% of memory usage and 3x speedup when serializing with optional 4x when using iodata ;)
It also adds new functions `*_to_iodata` that can be used by libraries that operate on iodata like ecto or json
```elixir
defmodule CalendarStringBench do
def run do
datetime = ~U[2024-12-30 12:21:45.000123Z]
Benchee.run(
%{
"Elixir.DateTime.to_string" => fn -> DateTime.to_string(datetime) end,
"Calendar.ISO.datetime_to_string" => fn ->
Calendar.ISO.naive_datetime_to_string(
datetime.year,
datetime.month,
datetime.day,
datetime.hour,
datetime.minute,
datetime.second,
datetime.microsecond
)
end,
"Calendar.IOISO.datetime_to_string" => fn -> …
```
=> dk_use_iodata_for_datetime_formatting

lib/elixir/lib/calendar/duration.ex, lib/elixir/lib/json.ex, lib/elixir/test/elixir/json_test.exs
@josevalim New pr because there is too much changes comparing to the previous one
The previous one can still be used after making the new functions private.
In the new test case for `encode_to_iodata!` the list currently looks like this: 
```
[
91,
[34, [["12", 58, "34", 58 | "56"], 46 | "78"], 34],
44,
[34, ["2024", 45, "12", 45 | "31"], 34],
44,
[
34,
["2010", 45, ["0" | "4"], 45 | "17"],
84,
[["14", 58, ["0" | "0"], 58, "0" | "0"], 46 | "123"],
34
],
44,
[
34,
["2010", 45, ["0" | "4"], 45 | "17"],
84,
[["14", 58, ["0" | "0"], 58, "0" | "0"], 46 | "123"],
90,
34
],
44,
[34, "P2MT3H", 34],
93
]
```
=> use iodata for json serialization

lib/mix/lib/mix/tasks/do.ex
A coworker and I had to test this ourselves to figure out what would happen in `mix do compile + test` if the compilation step failed, so I figured it'd be worth calling out this behavior in the docs.
=> Clarify that `mix do` early-exits on error

lib/elixir/lib/calendar/datetime.ex, lib/elixir/lib/calendar/naive_datetime.ex
continues on top of #14130 the changes in iso.ex are in the previous pr.
Main changes are the use of iodata in `iso8601` functions for date related modules that are used in  json serialization.
It also exposes the `Calendar.ISO.microseconds_to_iodata(ms, p)` as public because its the same logic as in the iso module that I refactored.
=> Dk use iodata in iso 8601 and json serialization

lib/mix/lib/mix/task.compiler.ex
Just a very minor typo fix - I noticed it when I was going over the new fun stuff about compiler listeners.
=> Fix minor typo in lib/mix/lib/mix/task.compiler.ex

lib/elixir/lib/registry.ex
=> Clarify metadata behavior in Registry :via docs

lib/elixir/lib/calendar.ex
It was not obvious that the microsecond precision affects the formatting.
=> add note about microsecond precision in Calendar.strftime

lib/elixir/lib/calendar/datetime.ex
During our upgrade to Elixir 1.18 we got some compile warnings about the usage of `==` on `DateTime` structs. <https://hexdocs.pm/elixir/1.18.1/DateTime.html> suggested using `compare/2` which led to replacing
```elixir
if user.password_reset_token_sent_at > oldest_allowed_token_datetime do
```
with
```elixir
if DateTime.compare(user.password_reset_token_sent_at, oldest_allowed_token_datetime) == :gt do
```
However, a far better solution is:
```elixir
if DateTime.after?(user.password_reset_token_sent_at, oldest_allowed_token_datetime) do
```
To make it easier for developers to think of these functions (`after?` and `before?`), I suggest mentioning them alongside `compare/2`.
=> mention alternatives to DateTime.compare/2 for comparison

lib/elixir/lib/calendar/date.ex, lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/lib/calendar/time.ex
Similar to https://github.com/elixir-lang/elixir/pull/14147
During our upgrade to Elixir 1.18 we got some compile warnings about the usage of `==` on `DateTime` structs. <https://hexdocs.pm/elixir/1.18.1/DateTime.html> suggested using `compare/2` which led to replacing
```elixir
if user.password_reset_token_sent_at > oldest_allowed_token_datetime do
```
with
```elixir
if DateTime.compare(user.password_reset_token_sent_at, oldest_allowed_token_datetime) == :gt do
```
However, a far better solution is:
```elixir```
if DateTime.after?(user.password_reset_token_sent_at, oldest_allowed_token_datetime) do
```
To make it easier for developers to think of these functions (`after?/2` and `before?/2`), I suggest mentioning them alongside `compare/2`.
=> mention alternatives to compare/2 for comparison in other dates and times

lib/iex/lib/iex/autocomplete.ex, lib/iex/test/iex/autocomplete_test.exs
Fixes the behaviour of autocompleting map update with structures described in issue #14149 
```elixir
iex> u = %URI{}
iex> %{u | 
```
Autocompleting the last line now works properly
=> [IEx][Autocomplete] Fix crashing on autocompleting structs

lib/elixir/lib/float.ex
In https://github.com/elixir-lang/elixir/pull/14130 I  benchmarked building binaries vs building lists.
Building lists is faster, and as erlang uses lists natively we can leverage that in float parsing.
On average it is 1.5x faster no matter the input size:
```
Name                    ips        average  deviation         median         99th %                                                                                                                      
IOFloat.parse      239.03 K        4.18 μs   ±130.63%        4.05 μs        6.09 μs                                                                                                                      
Float.parse        149.34 K        6.70 μs   ±128.69%        5.75 μs       36.58 μs …
```
=> Optimize Float.parse/1

lib/elixir/src/elixir_tokenizer.erl
I was confused when I saw the current charlist warning and this PR slightly tweaks the language to make the reason for the warning clearer. Specifically I wanted to highlight that this is not a stylistic disagreement, but is about a deprecation, which the current language omits.
P.s. this is my first PR on elixir and would welcome feedback. A huge fan of the language and all of the work y'all do!
=> Improve warning for charlist deprecation

lib/elixir/lib/kernel/typespec.ex, lib/elixir/test/elixir/typespec_test.exs
Close https://github.com/elixir-lang/elixir/issues/14153
=> Prevent infinite loop in compiler for some invalid type specs

lib/ex_unit/lib/ex_unit/diff.ex, lib/ex_unit/test/ex_unit/diff_test.exs
Close https://github.com/elixir-lang/elixir/issues/14157
=> Fix ExUnit crash when diffing bitstring specifiers

lib/mix/lib/mix/tasks/release.ex
Without the VC++ Runtime you get an error when trying to run the release:
```
Unable to load emulator DLL
([...erts folder]\bin\beam.smp.dll)
```
Someone [ran into this before on the elixir forum](https://elixirforum.com/t/mix-release-or-rather-erl-exe-package-require-additional-files-to-work-standalone/29090) but the help was not updated.
Note: I have [asked in the Erlang forum](https://erlangforums.com/t/minimum-visual-c-runtime-version/4369) what the minimum version of the runtime is.
=> Document VC++ required for Windows releases

lib/elixir/lib/path.ex
Not a big issue, but while reading the docs for the function, I had a moment of confusion as they were referencing a `relative_to` argument which wasn't there in the function signature.
The PR switches from `cwd` to `relative_to`, which is more generic and more consistent with possible use cases of the function.
=> Improve clarity of Path.safe_relative/2 argument names

lib/elixir/lib/calendar/iso.ex
Benchmarked for worst case scenario - 6digits and offset
`datetime = "2015-01-23 23:50:07.012345-02:30"`
```
Name                                          ips        average  deviation         median         99th %
Calendar.IOISO.parse_naive_datetime        4.61 M      216.69 ns  ±7284.06%         180 ns         320 ns
Calendar.ISO.parse_naive_datetime          2.23 M      448.94 ns  ±3245.43%         341 ns         621 ns
Comparison: 
Calendar.IOISO.parse_naive_datetime        4.61 M
Calendar.ISO.parse_naive_datetime          2.23 M - 2.07x slower +232.25 ns
Extended statistics: 
Name                                        minimum        maximum    sample size                     mode
Calendar.IOISO.parse_naive_datetime          150 ns    19540150 ns         5.49 M                   180 …
```
=> Optimize parsing microseconds and offset in calendar

lib/mix/lib/mix/sync/lock.ex, lib/mix/lib/mix/sync/pubsub.ex
Fixes https://github.com/elixir-lang/elixir/issues/14168.
=> allow other users to write to mix_pubsub and mix_lock folders

lib/mix/lib/mix/sync/lock.ex, lib/mix/lib/mix/sync/pubsub.ex
We call `File.mkdir_p!` when necessary down the line already, so there's no need for doing that twice.
=> Remove duplicate call to mkdir in concurrency lock

lib/elixir/lib/calendar.ex, lib/elixir/lib/calendar/date.ex
The callback and the function docs are update to reflect that day_of_week is an ordinal value.
=> Update Calendar.day_of_week callback and Date.day_of_week/2 docs

lib/elixir/lib/json.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/map_set.ex, lib/elixir/lib/string.ex, lib/elixir/pages/anti-patterns/process-anti-patterns.md, lib/elixir/pages/getting-started/debugging.md, lib/elixir/pages/mix-and-otp/agents.md, lib/elixir/pages/mix-and-otp/distributed-tasks.md, lib/elixir/pages/mix-and-otp/erlang-term-storage.md, lib/elixir/pages/mix-and-otp/task-and-gen-tcp.md, lib/ex_unit/lib/ex_unit.ex, lib/mix/lib/mix/tasks/profile.eprof.ex, lib/mix/lib/mix/tasks/profile.fprof.ex, lib/mix/lib/mix/tasks/profile.tprof.ex, lib/mix/lib/mix/tasks/release.ex, lib/mix/lib/mix/tasks/test.coverage.ex
See individual commits:
- add some missing links
- fix a broken epmd link: http://www.erlang.org/doc/man/epmd.html -> https://www.erlang.org/doc/apps/erts/epmd_cmd
- use backticked modules rather than hard-coded when possible
=> Add and simplify links to erlang documentation

lib/elixir/pages/references/typespecs.md
This [discussion](https://github.com/elixir-lang/elixir/pull/14172#discussion_r1913088800) made me realize that today the doc for typespecs does not call out the fact this is the "old typesystem" and it doesn't represent the upcoming type system.
I can see how this might be confusing for people who haven't followed the type system discussions closely or are learning Elixir, and do not realize a) that these two are separate b) how they relate/differ
Feel free to modify the copy.
=> Mention the new type system in typespecs doc

lib/elixir/lib/module/parallel_checker.ex, lib/elixir/lib/module/types.ex, lib/elixir/lib/module/types/apply.ex, lib/elixir/lib/module/types/descr.ex, lib/elixir/lib/module/types/expr.ex, lib/elixir/lib/module/types/helpers.ex, lib/elixir/lib/module/types/of.ex, lib/elixir/lib/module/types/pattern.ex, lib/elixir/lib/string.ex, lib/elixir/pages/references/gradual-set-theoretic-types.md, lib/elixir/src/elixir_bitstring.erl, lib/elixir/test/elixir/calendar/iso_test.exs, lib/elixir/test/elixir/inspect_test.exs, lib/elixir/test/elixir/integer_test.exs, lib/elixir/test/elixir/kernel/comprehension_test.exs, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/kernel/expansion_test.exs, lib/elixir/test/elixir/module/types/descr_test.exs, lib/elixir/test/elixir/module/types/expr_test.exs, lib/elixir/test/elixir/module/types/infer_test.exs, lib/elixir/test/elixir/module/types/integration_test.exs, lib/elixir/test/elixir/module/types/pattern_test.exs, lib/elixir/test/elixir/module/types/type_helper.exs, lib/mix/lib/mix/compilers/elixir.ex, lib/mix/lib/mix/tasks/local.hex.ex
Prior to this PR, we performed type inference only in patterns. This pull requests adds type inference to most expressions in Elixir, including function calls, paving the way for us to add inference of guards.
The best way to show this is with an example. The following code:
def add_foo_bar(x) do
x.foo + x.bar
end
Will automatically infer that x is a map, which has at least the `.foo` and `.bar` keys, where their values must be integers or floats. The return type is either an integer or a float.
There are about 10 TODOs I must tackle before merging this.
=> Turn type inference up to 1000

lib/elixir/lib/access.ex, lib/elixir/lib/calendar/date.ex, lib/elixir/test/elixir/calendar/date_range_test.exs, lib/elixir/test/elixir/version_test.exs
=> Fix warning in tests and some doctest whitespace 

lib/elixir/lib/protocol.ex, lib/elixir/test/elixir/fixtures/consolidation/extra_def.ex, lib/elixir/test/elixir/fixtures/consolidation/sample.ex, lib/elixir/test/elixir/protocol/consolidation_test.exs
We can feel the excitement in the commits 😄 https://github.com/elixir-lang/elixir/pull/14145/commits/1763865312f8ad4c51c3a69450ad9e8d86921960.
I tried `main` on a project and got a compiler crash due to this [dependency](https://github.com/lexmag/msgpax/blob/e2f31aacdbd476fec4be6abbc88d51e0dfae8c9a/lib/msgpax/packer.ex#L110) which defines regular functions inside a protocol, basically:
```elixir
defprotocol Msgpax.Packer do
def pack(term)
Kernel.def(pack_nan(), do: <<0xCB, -1::64>>)
end
```
The lib should probably be fixed and we should probably not allow this in the first place (same spirit as https://github.com/elixir-lang/elixir/issues/14158), but right now this crashes the compiler on consolidation: (`fun: :pack_nan, arity: 0`)
```elixir
08:40:08.671 [error] Task #PID<0.7509.0> …
```
=> Prevent crash on zero arity def in protocol

lib/ex_unit/lib/ex_unit/formatter.ex, lib/ex_unit/test/ex_unit/formatter_test.exs
The hint for `:equivalent_but_different_strings` is not shown when you run `mix test --no-color`. 
This PR fixes it by running `find_diff` regardless of whether the `diff_formatter` is enabled. The returned hints are always kept and the formatted result is set to nil if the `diff_formatter` is not enabled.
=> Show hints when run mix test --no-color

CHANGELOG.md
This has been reverted in https://github.com/elixir-lang/elixir/commit/b15de1cad66e249fe71f14d4696e2abd5933f60b
=> Remove changelog entry after reverting #14172

lib/elixir/lib/enum.ex
Consistently use `enumerable`(`s`), currently:
- https://hexdocs.pm/elixir/1.18.1/Enum.html#zip_reduce/3
- https://hexdocs.pm/elixir/1.18.1/Enum.html#unzip/1
=> Update argument name for documentation

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
Taking 40164fc29 one step further and support and/or boolean operators, leveraging the new list of nodes approach:
Basically we'll generate these:
```elixir
{:multi_value, {:falsy, [], nil}, result = falsy}
(
result = result || x
{:multi_value, {:||, [], [{:falsy, [], nil}, {:x, [], nil}]}, result}
)
(
result = result && 1 / x
{:value, {:&&, [], [...args]},, result}
)
```
I think `__block__` would make sense too and could be done in a same way.
=> Print intermediate results of dbg for boolean operators

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
As discussed in https://github.com/elixir-lang/elixir/pull/14217#issuecomment-2609153258
=> Print intermediate results of dbg for blocks

lib/elixir/pages/anti-patterns/code-anti-patterns.md
The paragraph preceding the change mentions two reasons (atoms aren't garbage collected, and the Erlang VM limits the number of atoms).
=> Fix typo in code anti-patterns doc

lib/elixir/lib/module/types/descr.ex, lib/elixir/test/elixir/module/types/descr_test.exs
Fixes https://github.com/elixir-lang/elixir/issues/14203
Replaces https://github.com/elixir-lang/elixir/pull/14205
Only implemented maps for now, once approved I'm happy to copy it for tuples.
We do only one pass at keys, and are able to switch the strategy in the middle (including just bailing if a key is missing or an expectation is not met).
It also fixes the bamboo example.
Perf-wise it seems to not spend a lot of time at all in the new code:
<details><summary>Profiling details</summary>
<p>
```elixir
:tprof.profile(Mix, :install, [[:bamboo], [force: true]], %{type: :call_time, pattern: [{Module.Types.Descr,:_, :_}], report: {:total, {:measurement, :descending}}})
```
```
Generated bamboo app
FUNCTION                                                                        CALLS  TIME …
```
=> Optimize map unions to avoid building long lists

lib/ex_unit/lib/ex_unit/doc_test.ex, lib/ex_unit/test/ex_unit/doc_test_test.exs
=> Add `:inspect_opts` option for doctest

lib/elixir/lib/string.ex, lib/elixir/pages/getting-started/keywords-and-maps.md
Close https://github.com/elixir-lang/elixir/issues/14222
=> Fix String.split/3 example in guide and add note in docs

lib/elixir/lib/kernel/cli.ex
I wanted to try out the new `--color`/`--no-color` options in Elixir 1.18.2 and disabling color doesn't work.
If I create the following file `test.exs`
```elixir
IO.puts(IO.ANSI.format([:bright, "test message", :reset]))
```
and run it from my color enabled terminal it correctly displays in bright text.
If I run it with `elixir --no-color test.exs` it still prints it with bright text.
After applying the patch in this PR it prints correctly without any ANSI color escape sequences.
This seems to be an error when the changes introduced in 786f3ce79721779efdd4985989c72264b98b2e7c where refectored: https://github.com/elixir-lang/elixir/commit/2c1a836db32898d2b7a17b0dd28e07425bf46213#diff-78a6fd95d2c5f4d0c0a5414b1393fc082ac242d2f70a665abe06f5e571da557d
=> Fix `--no-color` not working

lib/elixir/lib/module/types/descr.ex, lib/elixir/test/elixir/module/types/descr_test.exs
Same idea as https://github.com/elixir-lang/elixir/pull/14215 for tuples.
=> Implement optimization of tuple unions

lib/elixir/lib/module/types/descr.ex
Another mechanical refactor.
Comparing map keys by casting them into sets is much slower and memory intensive than checking map size + loop over the keys ([bench](https://github.com/sabiwara/elixir_benches/commit/b37865c25ea1fa639585bcb958137a488974acd6)).
Also using `Enum.count_until` to bail at the second different key found.
We could probably avoid the extra `Enum.find` pass by re-using the pattern from map fusion, but we can't reuse the exact same code because we're not checking for subtypes here (well, perhaps we could actually leverage this information and do something smart?)
Finally, removed the `?` from the name since it doesn't return a bool.
=> Refactor Descr.map_all_but_one

lib/elixir/lib/module/types/descr.ex
I noticed a couple of places where we were building intermediate lists which could be done in a single pass.
=> Mechanical refactor of Descr, avoid intermediate lists

lib/elixir/lib/exception.ex
1. Adds example to the module with only an explanation but no example, to see how the error is caused.
2. Some module in exception do not have description for example: UnicodeConversionError module
4. These changes was added to enrich the documentation to assist developers understand how the exception are raised.
=> Feat:  Add examples to exception.ex for clearer error handling

lib/elixir/lib/exception.ex
Noticed a small typo in the example of a typespec typo 😄
=> Use the correct incorrect typespec definition in exception.ex

lib/elixir/lib/process.ex
I'm adding a note section to have the same note that explicts the difference between exit/1 and exit/2 from erlang documentation directly in elixir doc. I could also add a link to erlang docs if it's better.
=> Improving docs: Add note section to Process.exit/2 to make it clear

lib/elixir/lib/calendar.ex, lib/elixir/test/elixir/calendar_test.exs
This PR introduces support for 2-arity functions for `Calendar.strftime/3` options per this [proposal](https://groups.google.com/g/elixir-lang-core/c/Uxe0nKFeBk4).  
The result is that the options functions may be 1-arity and receive the term to be processed or 2-arity in which case they receive both the term and the datetime argument to `Calendar.strftime/3`.
The function documentation is updated but may well benefit from further work.
A single test case is added to verify that 2-arity functions are supported, and that the datetime is correctly passed to them.  All tests are passing.
=> Support 2-arity options for Calendar.strftime/3

lib/iex/lib/iex/helpers.ex, lib/iex/lib/iex/introspection.ex, lib/mix/lib/mix/tasks/help.ex, lib/mix/test/mix/tasks/help_test.exs
=> Add mix help Mod, mix help :mod, mix help Mod.fun and mix help Mod.fun/arity

lib/elixir/lib/kernel/typespec.ex
I noticed the `name` and `tag` is mixed in `record` macro implementation
=> Fix inconsistent variable naming in record typespec macro

lib/ex_unit/lib/ex_unit/callbacks.ex
Seems like a modal verb "will" is missig.
=> Fix typo in the documentation for ExUnit Callbacks.

.github/workflows/ci.yml, .github/workflows/ort/action.yml, .github/workflows/release.yml, .ort.yml, .ort/config/config.yml, .ort/config/evaluator.rules.kts, LICENSES/Apache-2.0.txt, LICENSES/LicenseRef-elixir-trademark-policy.txt, LICENSES/LicenseRef-scancode-unicode.txt
Implement Source SBoM Generation
This PR implements source SBoM generation using [OSS Review Toolkit](https://oss-review-toolkit.org/ort/)
in the following formats:
* CycloneDX (v1.6) JSON / XML
* SPDX (v2.2) JSON / YML
The PR implements a very simple Open Source Policy with a list of allowed licenses. Namely:
* `Apache-2.0` (Elixir itself / copied OTP code)
* `LicenseRef-elixir-trademark-policy` (Elixir Logo)
* `LicenseRef-scancode-unicode` (Unicode Files)
The idea is that if we add other code / dependencies with other licenses, the inclusion has to be
agreed by the Elixir team and the list extended.
This PR implements the technical parts of [OpenChain](https://openchainproject.org/) ISO/IEC 18974:2023.
Specifically:
> **§ 4.1.5 Standard practice implementation**
>
> The program shall …
=> Setup OSS Review Toolkit SBoM generation

.github/workflows/ort/action.yml, .github/workflows/release.yml, .ort.yml, .ort/config/config.yml, project.spdx.yml
Follow up of #14241
* Removes unused actions code
* Declare special files correctly (docs, build tools etc.)
* Remove default fallback rule (no file license header and no exception configured => error in CI)
* Implement exception for binary files and test fixtures
* Replace `Unmanaged` package manager with `SpdxDocumentFile` to improve fields like `name` and `homepage` in SPDX
Some more changes will need to be done in the future about declaring the erlang dependency and publish the correct purls, but that currently has an issue. (https://github.com/oss-review-toolkit/ort/discussions/9904) I'll open a PR about that once there's a working solution.
=> Improve SBoM Details

.github/workflows/ort/action.yml, .ort.yml, .ort/config/config.yml, project.spdx.yml
Follow up of #14241
* Declares Erlang Dependency
* Declares elixir applications (required for `purl` to identify in case of elixir vulnerabilities)
* Switches back to the official ORT action repo
* Will pass the [NTIA SBoM checker](https://github.com/spdx/ntia-conformance-checker?tab=readme-ov-file)
* Does not yet pass since https://github.com/aboutcode-org/scancode-toolkit/issues/4131 is not yet done
* The CI will inject the version info into the ORT config & SPDX file at runtime. The way this is implemented allows:
* If somebody declares Elixir as a dependency, everything should scan as expected, but will not contain any version information
* When the CI uses it, all version info is injected and present in the resulting SBoM
=> Expose Packages in SBoM

lib/elixir/lib/port.ex, lib/elixir/lib/system.ex, lib/mix/lib/mix/tasks/cmd.ex
This patch makes two small changes to the documentation:
First, "zombie" processes are in a terminated state and will appear in "ps" output in "Z" state.  The problem described in our documentation seems to actually be about the "orphan" condition, in which a process continues running after its parent terminates.  Most unix systems will reparent the process with PID 1 but this can vary, but there is no convention that the process should stop unless it has been wired using eg. "prctl" to detect a terminated parent.  The distinction between zombie and orphan is important because it means the child is still active.
Second, our suggestion that the child process should detect stdin closure is a good workaround but is not generally true for applications that aren't doing their work on stdio. …
=> Minor doc update: "orphan" processes

lib/elixir/lib/access.ex, lib/elixir/lib/exception.ex, lib/elixir/lib/kernel/special_forms.ex, lib/elixir/lib/keyword.ex, lib/elixir/lib/map.ex, lib/elixir/test/elixir/exception_test.exs, lib/elixir/test/elixir/kernel/raise_test.exs, lib/elixir/test/elixir/kernel/with_test.exs, lib/elixir/test/elixir/keyword_test.exs, lib/elixir/test/elixir/map_test.exs, lib/ex_unit/test/ex_unit/callbacks_test.exs
It would be ideal if the exception would contain the left part of the match but just pretty printing it makes much difference. 
I'm just not sure what to do with the doctest?
=> pretty format terms in errors

lib/elixir/lib/kernel.ex
This PR fixes a minor typo in the docs.
=> Fix a typo

lib/ex_unit/lib/ex_unit/diff.ex, lib/ex_unit/test/ex_unit/diff_test.exs
I found the reason of #14268 
we passed the length of left list and then the code looked like this:
```
left = [:b, :c]
right = [:a, :b, :c]
{parsed_right = [:a, :b], improper_right = [:c]} = split_right_list(right, length(left), [])
```
I added one test, and fixed ~~two~~ one, which looks like it's invalid currently.
~~There are still two failing tests - I may need a hand with this.~~
=> Fix for ex_unit diff bug 

lib/elixir/lib/module/types.ex
Found a typo in a comment in `types.ex`. This PR fixes it.
=> Fix a typo in types.ex

lib/ex_unit/lib/ex_unit/diff.ex, lib/ex_unit/test/ex_unit/diff_test.exs, lib/ex_unit/test/ex_unit/formatter_test.exs
Close https://github.com/elixir-lang/elixir/issues/14291
Should be backported after merge.
=> Fix regression when diffing nested improper lists

.ort.yml, .ort/config/evaluator.rules.kts, OPEN_SOURCE_POLICY.md, README.md
* Adds an Open Source Policy to the project.
* Makes Elixir ready for OpenChain certification
> We have a documented policy governing the open source license compliance of supplied software.
Yes, will be published at https://github.com/elixir-lang/elixir/blob/main/OPEN_SOURCE_POLICY.md
> We have a documented procedure to communicate the existence of the open source policy to program participants.
* Published Policy
* Referenced in README
* Once certified, we'll also add a badge to the README
> We have identified the roles and responsibilities that affect the performance and effectiveness of the program.
See Policy §7
> We have identified and documented the competencies required for each role.
See Policy §7
> We have documented the assessed competence for each program participant.
See …
=> Implement Open Source Policy

lib/elixir/lib/dynamic_supervisor.ex
While playing around with DynamicSupervisor, I got confused because the typespec mentions `{:error, :already_started}`, although unlike Supervisor, DynamicSupervisor ignores the child spec ids that would normally cause this value to be returned.
This PR expands the docs for Dynamic Supervisor's `start_child` function and `on_start_child` typespec to explain that although the `id` is ignored, `:already_started` can still be returned when using name registration.
=> Add more docs about :already_started for DynamicSupervisor

lib/iex/lib/iex/autocomplete.ex, lib/iex/test/iex/autocomplete_test.exs
This PR fixes
```
*** ERROR: Shell process terminated! (^G to start new job) ***
21:39:55.166 [error] Process #PID<0.70.0> raised an exception
** (FunctionClauseError) no function clause matching in Module.concat/2
(elixir 1.18.2) lib/module.ex:961: Module.concat(Elixir, {:__MODULE__, [line: 1], nil})
(iex 1.18.2) lib/iex/autocomplete.ex:471: IEx.Autocomplete.value_from_alias/2
(iex 1.18.2) lib/iex/autocomplete.ex:422: IEx.Autocomplete.container_context_struct/4
(iex 1.18.2) lib/iex/autocomplete.ex:334: IEx.Autocomplete.expand_container_context/4
(iex 1.18.2) lib/iex/autocomplete.ex:82: IEx.Autocomplete.expand_code/2
(kernel 9.2.4.6) group.erl:685: :group.get_line1/5
(kernel 9.2.4.6) group.erl:517: :group.get_chars_loop/10
(kernel 9.2.4.6) group.erl:213: :group.io_request/6
iex(1)> …
```
=> Fix autocomplete crash when expanding struct with `__MODULE__`

lib/elixir/lib/json.ex, lib/elixir/test/elixir/json_test.exs
=> Encode any JSON key to string, closes #14305

lib/elixir/lib/module/types/of.ex, lib/mix/lib/mix/pubsub.ex
=> Fix two more typos in comments

lib/elixir/pages/references/syntax-reference.md
In multiple places in the docs, multi-line strings are referred to as heredocs, such as the following:
From: [https://hexdocs.pm/elixir/1.18.3/module-attributes.html#:~:text=Elixir promotes the use of Markdown with heredocs to write readable documentation](<https://hexdocs.pm/elixir/1.18.3/module-attributes.html#:~:text=Elixir promotes the use of Markdown with heredocs to write readable documentation>)
> Elixir promotes the use of Markdown with heredocs to write readable documentation. Heredocs are multi-line strings, they start and end with triple double-quotes, keeping the formatting of the inner text
From: [https://hexdocs.pm/elixir/1.18.3/sigils.html#:~:text=Sigils also support heredocs](<https://hexdocs.pm/elixir/1.18.3/sigils.html#:~:text=Sigils also support heredocs>)
> Sigils also …
=> Document that multi-line strings are heredocs

lib/elixir/lib/module/types.ex, lib/elixir/test/elixir/kernel/warning_test.exs
This adds some text to the warning explaining it only affects private functions and that making the function public will silence the warning.
=> types.ex - improve warning message about defp defaults

lib/elixir/lib/exception.ex, lib/elixir/test/elixir/exception_test.exs
Close https://github.com/elixir-lang/elixir/issues/14322
https://github.com/erlang/otp/blob/57cee857031cc08a47c7d2f4f21a6fac87781f91/lib/public_key/src/pubkey_os_cacerts.erl#L300
Before
After
=> Fix handling of ErlangError when :general key is chardata

lib/mix/lib/mix/tasks/xref.ex, lib/mix/lib/mix/utils.ex, lib/mix/test/mix/tasks/xref_test.exs, lib/mix/test/mix/utils_test.exs
This patch adds support for output the xref graph as a two level Map of Maps which can be trivially loaded by anything that can process JSON data. The top level Map contains keys which specify source files whose values are maps contain sink files as keys, and dependency type data as values. Source files with no dependencies have empty maps as values. For example a if "lib/foo.ex" has a compile time dependency on "lib/bar.ex" which had no dependencies at all, then the output would look like this:
```
{
"lib/foo.ex": { "lib/bar.ex": "compile" },
"lib/bar.ex": {},
}
```
At the same time it adds support for renaming existing xref_graph.dot and xref_graph.json files to have a .bak extension instead of overwriting them.
This patch also includes logic to fix some misleading verbiage output by …
=> mix xref graph - add json support and related changes

.github/workflows/ort/action.yml, .ort.yml, .ort/config/evaluator.rules.kts
Also removes superfluous ORT evaluator rule since the Elixir TM license was fully propagated: https://github.com/aboutcode-org/scancode-toolkit/pull/4165
=> Update ORT Action & Executable

.github/workflows/ci-markdown.yml, .github/workflows/ci.yml, .github/workflows/notify.yml, .github/workflows/ort/action.yml, .github/workflows/release.yml, .github/workflows/release_pre_built/action.yml
This PR pins all GH Actions to a specific commit sha.
All actions invocations are written as `uses: [REPO]/[NAME]@[SHA] # [VERSION]`. This is supported by dependabot and it will automatically create PRs with both the SHA and version change in the comment.
As seen with [`tj-actions/changed-files`](https://semgrep.dev/blog/2025/popular-github-action-tj-actionschanged-files-is-compromised/) last week, any version (even if using a tag) can compromise a repository. The only way to prevent this, is to pin the version to a specific SHA.
This is also recommended by ScoreCard: https://github.com/ossf/scorecard/blob/main/docs/checks.md#pinned-dependencies
This will potentially create a lot of dependabot update PRs with the current configuration. In the projects I maintain and pinned the …
=> Pin GitHub Actions

.github/workflows/ci-markdown.yml, .github/workflows/release.yml
Sets top level permissions for each GH Action workflow to `contents: read` and gives more permissions to jobs where necessary.
Each job should have the minimal set of permissions available so that it can't access / manipulate information in case of a malicious action or if a user manages to inject code into the CI.
This is also recommended by ScoreCard: https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
=> Limit GH Actions Token Permissions

.github/workflows/ci.yml
Previous issues with this seem to have been resolved. See my fork CI: https://github.com/maennchen/elixir/actions/runs/13922102826/job/38957556085
=> Enable warnings_as_errors for Erlang only on latest

RELEASE.md
Fulfills the [release_notes_vulns](https://www.bestpractices.dev/en/criteria/0#0.release_notes_vulns) OpenSSF Best Practices Badge requirements.
=> Add CVE CHANGELOG disclosure requirement to `RELEASE.md`

lib/elixir/lib/uri.ex, lib/elixir/test/elixir/uri_test.exs
This PR fixes a bug in `URI.merge/2` that was revealed via the W3C test suite of the JSON-LD 1.1 algorithms. The merging with a base ending in dot segments without a trailing slash was not handled correctly. 
Example:
```elixir
URI.merge("http://a/bb/ccc/.", "g") |> to_string()
```
=> Fix URI.merge/2 handling of base with trailing dots

CONTRIBUTING.md
Fulfills the [test_policy](https://www.bestpractices.dev/en/criteria/0#0.test_policy) and [tests_documented_added](https://www.bestpractices.dev/en/criteria/0#0.tests_documented_added) OpenSSF Best Practices Badge requirements.
=> Add test policy to CONTRIBUTING.md

lib/elixir/lib/uri.ex, lib/elixir/test/elixir/uri_test.exs
Here's another fix for a `URI.merge/2` issue that was uncovered by the W3C JSON-LD 1.1 Test suite.
The current implementation incorrectly rejects base URIs with a scheme but without a host:
```elixir
iex> URI.merge("tag:example", "foo")
** (ArgumentError) you must merge onto an absolute URI
(elixir 1.18.2) lib/uri.ex:903: URI.merge/2
```
=> Fix URI.merge/2 to handle base URIs with scheme but without host

lib/elixir/lib/uri.ex, lib/elixir/test/elixir/uri_test.exs
Yet another fix of an issue in `URI.merge/2` revealed by the W3C JSON-LD 1.1 test suite. The problem is that resolving a relative path with dot segments against a base URI incorrectly removes the trailing slash when the resolution ends at the root path.
Minimal example:
```elixir
URI.merge("http://a/b", "..") |> to_string()
```
=> Fix URI.merge/2 trailing slash handling at root path

lib/ex_unit/lib/ex_unit/capture_server.ex, lib/ex_unit/test/ex_unit/capture_log_test.exs
When a process that traps exits used ExUnit's log capture functionality, it would receive stray exits from the Tasks started inside it that could lead to issues if not handled. We fix this by disabling exit trapping while awaiting the tasks in the CaptureServer's log handler.
=> Prevent exits from leaking in ExUnit.CaptureServer

Makefile
The message probably refers to the "Building documentation" section that has been moved to CONTRIBUTING.md in a2af062.
=> Fix mention of README in Makefile

lib/elixir/lib/config.ex
I felt the current wording of the sentence was a bit clumsy and not super clear, so this should read better and help remove all doubt.
=> improve Config.config_env/0 docs

lib/logger/lib/logger/utils.ex, lib/logger/test/logger/translator_test.exs
Currently `handle_otp_reports` logger option doesn't seem to have any effect. It's passed as `otp` option to `Logger.Utils.translator/2` (which is always attached as a primary logger) and the only clause that uses this option seemingly can never match. Here's an example:
```elixir
:logger.remove_primary_filter(:logger_translator)
:logger.add_primary_filter(
:logger_translator,
{&Logger.Utils.translator/2, %{otp: false, sasl: false, translators: [{Logger.Translator, :translate}]}}
)
Task.start(fn -> exit("Exit") end)
Process.sleep(1_000)
```
```
12:25:45.123 [error] Task #PID<0.97.0> started from #PID<0.94.0> terminating
** (stop) "Exit"
logger.exs:8: anonymous fn/0 in :elixir_compiler_0.__FILE__/1
(elixir 1.18.3) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
Function: …
```
=> Drop otp log events if `handle_otp_reports` is set to false

lib/elixir/lib/access.ex, lib/elixir/test/elixir/access_test.exs
Hi, I am adding `Access.values/0` as discussed [here](https://groups.google.com/g/elixir-lang-core/c/z3dK1TEhwsg), and also `Access.keys/0` for parity with keys. If you think `Access.keys/0` is not useful and should not be added, I can remove it from the PR.
I am not adding any explicit unit tests as I find the coverage by doctests enough, but I can write some if you wish so.
Thank you for reviewing the changes!
=> Add Access.values/0

lib/mix/lib/mix.ex, lib/mix/lib/mix/tasks/deps.compile.ex, lib/mix/lib/mix/tasks/deps.loadpaths.ex, lib/mix/lib/mix/tasks/deps.parallel.ex, lib/mix/lib/mix/tasks/deps.partition.ex, lib/mix/lib/mix/tasks/loadconfig.ex, lib/mix/test/fixtures/umbrella_dep/mix.exs, lib/mix/test/mix/tasks/deps_test.exs, lib/mix/test/mix/tasks/loadconfig_test.exs, lib/mix/test/mix/umbrella_test.exs, lib/mix/test/test_helper.exs
The implementation uses a TCP port to distribute the work. We chose to not use the Erlang distribution as that may affect the user app running afterwards.
When compiling Livebook on 10 core machine:
```
livebook$ rm -rf _build/; time mix deps.compile
real	0m25.865s
user	0m48.625s
sys	0m10.504s
```
```
livebook$ rm -rf _build/; time MIX_OS_DEPS_COMPILE_PARTITION_COUNT=4  mix deps.compile
real	0m12.337s
user	0m0.417s
sys	0m0.533s
```
In this case, increasing more than 4 did not decrease compilation times (perhaps expected due to the cost of starting new instances and that compilation itself is already parallel within the same dependency). Closes #14200.
=> Add MIX_OS_DEPS_COMPILE_PARTITION_COUNT for concurrent deps compilation

lib/elixir/lib/uri.ex, lib/elixir/test/elixir/uri_test.exs
Yet another fix of an issue in `URI.merge/2`. The problem concerns merging against a base with non-hierarchical URI schemes without authority (like "urn:"). According to the RFC 3986 merging algorithm, when dealing with base URIs that have a scheme but no authority, the path should be directly resolved. The current behavior however prepends a leading slash, which is neither standards-compliant nor useful in practice.
Example:
```elixir
URI.merge("ex:", "test") |> to_string()
```
This should be the last fix in the series of corrections to the `URI.merge/2` algorithm, as this makes the last failing test related to URI merging of the W3C JSON-LD 1.1 test suite pass.
Additionally, this PR reorganizes the grown `URI.merge/2` tests into a `describe` block for better structure and readability.
=> Fix URI.merge/2 handling of authorityless base

lib/elixir/src/elixir_erl.erl, lib/elixir/test/elixir/map_test.exs
Close https://github.com/elixir-lang/elixir/issues/14362
For instance, the erlang AST for `<<255, 127::7>>` is:
```elixir
{:bin, 1,
[
{:bin_element, 1, {:integer, 1, 255}, :default, [:integer]},
{:bin_element, 1, {:integer, 1, 127}, {:integer, 1, 7}, [:integer]}
]}
```
To be backported after merge.
=> Handle non-binary bitstring in struct default values

lib/elixir/lib/calendar/time.ex
From https://groups.google.com/g/elixir-lang-core/c/KvOYiBk1j1Q
=> Modify `Time.utc_now/1` to allow truncation and add `Time.utc_now/2`

lib/ex_unit/lib/ex_unit/case.ex
Looks like this:
This is 90% for me because I kind of always forget. Do we like it?
=> Add Mermaid graph about ExUnit processes

lib/elixir/scripts/mix_docs.exs
It seems mermaid was only added to Elixir docs itself, not ExUnit/Mix/etc.
https://hexdocs.pm/ex_unit/main/ExUnit.Case.html#module-process-architecture
Copy pasting the config from elixir_docs.exs did the trick, but there might be a nicer way that avoids the duplication there.
This PR just enables mermaid, but it seems the chart above doesn't work on the latest version (couldn't figure out why):
=> Enable usage of mermaid in ExUnit &co

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/regex_test.exs
Elixir has historically relied on a behaviour that, when regexes were compiled, its native parts were compiled to a binary. Erlang/OTP 28 changes this and emits a reference, which means they can no longer be inlined at compile-time. In other words, you can no longer define a regex in a module body and store it in a module attribute or escape it inside a function.
In order to avoid breakage, we are adding a special case to module attributes that recompiles injected regexes, however, we are also attaching a deprecation to it. We could theoretically fix this generally by introducing some sort of `Macro.Escape` protocol, which we could be used by projects like Explorer and similar, but I think keeping a distinction between those would be important. For example, similar issues would happen …
=> Recompile regexes when escaped from module attributes

lib/elixir/test/elixir/regex_test.exs
This was introduced in https://github.com/elixir-lang/elixir/commit/76c64a0f32a5993286e5bce9b00149f0a85693ce#r154645508 but for 1.18 there's no deprecation warning so the test would fail on OTP 28 builds.
=> Remove deprecation warning check for 1.18

lib/mix/lib/mix/tasks/test.coverage.ex, lib/mix/test/mix/tasks/test_test.exs
Prep for #14343 
Allows output to be piped into `$GITHUB_STEP_SUMMARY` and get a reasonable result.
=> Update test coverage summary to produce a markdown-ish table

lib/logger/lib/logger/utils.ex, lib/logger/test/logger/translator_test.exs
The thing that is bothering me and that I'm looking for a way to address is the fact that translators are destructive to the report log messages. Most reports don't survive default translator and are replaced with a chardata, but some logger handlers clearly have a demand for the original report data, since they go as far as [parsing](https://github.com/getsentry/sentry-elixir/blob/b770388e728096ffd16be485332698a8308f5e44/lib/sentry/logger_handler.ex#L503-L518) [chardata](https://github.com/getsentry/sentry-elixir/blob/b770388e728096ffd16be485332698a8308f5e44/lib/sentry/logger_handler.ex#L543-L579) to build their own report.
One idea I have is that instead of converting report to chardata, translator could wrap the `report_cb` callback function, since the existing one would be useless …
=> Preserve logger reports through translation by encapculating translated output in report_cb

lib/elixir/lib/kernel.ex
Since elixir has built-in type `term()`, it may mislead to thoughts that `left` can be of any type. But it must be a string, so I guess it's better to say it explicit
=> Fix doc for text-base match operator

lib/elixir/lib/inspect.ex
It wasn't obvious that we needed to pass a list of fields, I initially tried `optional: true`.
This makes it more explicit and adds a working example.
I thought it might actually be beneficial to allow some sugar like `optional: :all` for convenience, WDYT?
Otherwise I find myself doing things like
```elixir
@fields [foo: 1, ...]
@derive {Inspect, optional: Keyword.keys(@fields)}
defstruct @fields
```
=> Add more docs about :optional in Inspect

lib/elixir/lib/io.ex
=> Fix typos in IO documentation

lib/elixir/lib/inspect.ex, lib/elixir/test/elixir/inspect_test.exs
Follow-up for https://github.com/elixir-lang/elixir/pull/14399
The second commit is not directly related, but improves the error message when we pass an invalid type - currently we'd be getting:
=> Allow optional: :all when deriving Inspect

lib/elixir/lib/partition_supervisor.ex
=> Add a couple of types to PartitionSupervisor

lib/elixir/lib/regex.ex
This patch, which works on 1.18.x but does not work on 1.19 is an attempt to implement String.Chars protocol and also a Regex.to_string() and Regex.modifiers() and Regex.to_string!() and Regex.modifiers!() functions.
The idea is to make it possible to safely embed precompiled regexes into other regexes in a similar way as that supported by perl.  The general idea is that ~r/foo/x turns into "(?x-ims:foo\n)", and etc. Thus it should match the same as it would have in its original form when it is embedded into a pattern which has a different set of modifiers.
For review by Jose.
=> Add Regex.to_embed/2

lib/elixir/lib/kernel.ex, lib/elixir/lib/kernel/special_forms.ex
I don't like the doctest because of `Macro.to_string/1`, but I can't find a more appropriate example without using `context`(which is `Kernel.SpecialFormsTest` in this case) and with sense for a doc-reader
=> Added doctest for unquote_splicing in block context

lib/elixir/lib/calendar/date_range.ex, lib/elixir/lib/code/formatter.ex, lib/elixir/lib/inspect/algebra.ex, lib/elixir/test/elixir/inspect/algebra_test.exs
Before we had `doc_fits` and `doc_group` which could be nested arbitrarily and complicated the formatting and fitting logic. By merging them into optimistic/pessimistic groups, we can simplify the API and logic.
=> Simplify algebra rendering

lib/eex/lib/eex/compiler.ex, lib/eex/test/eex_test.exs, lib/elixir/lib/code.ex, lib/elixir/src/elixir.erl, lib/elixir/src/elixir_errors.erl, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/code_test.exs, lib/iex/lib/iex/evaluator.ex
=> Add :indentation to Code.string_to_quoted/2

README.md
Just some small language changes following https://github.com/elixir-lang/elixir/commit/1cbc4934fb93acca4a6a8c669fced0639fca577c. 🙂
=> Update README sections on community interaction and feature proposals

lib/elixir/test/elixir/exception_test.exs, lib/elixir/test/elixir/module_test.exs, lib/elixir/test/elixir/protocol/consolidation_test.exs, lib/elixir/test/elixir/test_helper.exs, lib/iex/test/iex/helpers_test.exs, lib/iex/test/iex/interaction_test.exs, lib/iex/test/iex/pry_test.exs, lib/iex/test/test_helper.exs
=> Use Test Modules in tests instead of Elixir built-in modules

.github/workflows/ci.yml, .gitignore, Makefile, lib/eex/test/test_helper.exs, lib/elixir/scripts/cover.exs, lib/elixir/scripts/cover_record.exs, lib/elixir/test/elixir/exception_test.exs, lib/elixir/test/elixir/kernel/dialyzer_test.exs, lib/elixir/test/elixir/module/types/integration_test.exs, lib/elixir/test/elixir/test_helper.exs, lib/ex_unit/lib/ex_unit/diff.ex, lib/ex_unit/test/ex_unit/formatter_test.exs, lib/ex_unit/test/test_helper.exs, lib/iex/test/iex/helpers_test.exs, lib/iex/test/test_helper.exs, lib/logger/test/test_helper.exs, lib/mix/lib/mix/tasks/test.coverage.ex, lib/mix/test/test_helper.exs
Implements test coverage reporting.
=> Test Coverage Reporting

lib/mix/lib/mix/tasks/release.ex
One message remains if you set the release option to quiet
=> Update info message to respect release quiet option

lib/elixir/lib/keyword.ex
This seems to be the only uncovered line from `Keyword` (excluding the deprecated ones).
=> Improve coverage for `Keyword.delete_first/2`

lib/elixir/lib/code/fragment.ex, lib/elixir/test/elixir/code_fragment_test.exs, lib/iex/lib/iex/autocomplete.ex, lib/iex/test/iex/autocomplete_test.exs
This makes it so suggestions after `)`, `]`, `}`, and literals
only include block keywords and binary operators.
For example, `if true d|`, where `|` is the cursor position,
should only suggest `do`.
Closes #14392.
=> Add block_keyword_or_binary_operator to Code.Fragment

lib/logger/lib/logger.ex
I came across the `Logger`  runtime config param `:translator_inspect_opts` and there is no mention in the docs of what are the allowed options. I had to look through the source code to figure out that these options are later passed to a call to `Kernel.inspect/2`.
This PR helps remediate that by adding a reference to the docs for `Kernel.inspect/2` in the documentation of the runtime config param `:translator_inspect_opts`. We could link to the `Inspect.Opts` module directly perhaps, but I figured that this can be a problem if for any reason the `Kernel.inspect/2` function changes its spec at some point, and/or the options are moved elsewhere.
=> Add a doc reference that helps identify the possible values for Logger :translator_inspect_opts

lib/iex/lib/iex/helpers.ex, lib/iex/test/iex/helpers_test.exs
@josevalim as discussed, a first draft for a `process_info` helper in IEx.
=> IEx.Helpers.process_info/1

lib/elixir/lib/base.ex, lib/elixir/test/elixir/base_test.exs
This is a first PR to add this kind of functions. If we like the direction, I'll go ahead and add `valid32?/2` and `valid64?/2`.
=> Add Base.valid{n}?/2 functions

lib/elixir/lib/base.ex
Since https://github.com/elixir-lang/elixir/pull/14429 seemed to indicate that using `rescue` to check for tuple membership was not optimal, I tried to replace it by defensively checking the index (not beautiful I know 😅).
The result looks promising, although since `decode_` function is overall doing more work than `valid_?` the results are less impressive in comparison.
The result is more flaky here - sometimes getting 14% speed increase, sometimes 55% - but it's consistently quite faster for a big string.
```elixir
Name               ips        average  deviation         median         99th %
no_raise        3.50 M      285.86 ns ±10510.17%         208 ns         375 ns
original        3.32 M      301.58 ns ±10681.55%         208 ns         375 ns
Comparison: 
no_raise        3.50 M …
```
=> Optimize Base.decode*

lib/elixir/lib/base.ex
- Using `and` instead of relying on a global `rescue` has a significant impact
- Using a guard instead of a local `rescue` to check if the char is a non-nil member of a tuple also has almost as big of an impact
I haven't benched/done other functions yet, wanted to first share this one and wait for the feedback.
Reusing @whatyouhide 's `big_string` [benchmark](https://github.com/elixir-lang/elixir/pull/14417#issuecomment-2789524253):
```elixir
Name                      ips        average  deviation         median         99th %
bool_plus_guard       11.97 M       83.56 ns ±13110.49%       20.90 ns      104.20 ns
bool                   4.72 M      212.01 ns ±19289.61%          84 ns         250 ns
original               1.31 M      765.72 ns  ±3523.35%         500 ns        1417 ns …
```
=> Optimize Base.valid16?/2

lib/elixir/lib/kernel/special_forms.ex
According to a discussion [here](https://github.com/elixir-lang/elixir/pull/14423)
=> Change first doctest for case/2

lib/elixir/lib/base.ex
I realized I had a mistake in my previous benchmark for https://github.com/elixir-lang/elixir/pull/14429 - I was using an invalid string so it was measuring the case the function bails early 🤦
For valid strings, the speedup was almost non-existent as is - but provided we inline the `valid_char_name` function we can still achieve a ~2x speedup for valid strings over the pre-optimization implementation.
Updated benchmark:
https://github.com/sabiwara/elixir_benches/commit/af34130fed193bde6503103bb581ab08ab6fe815
=> Inline function in Base.valid16? implementation

lib/elixir/lib/base.ex
Benchmark & results [here](https://github.com/sabiwara/elixir_benches/commit/803a4e2963fdda8dc62a78bfd5ea4a6aa0767aaf#diff-edafe37a3de42994a530815924c98d2173500f46836238cae88ac60c33435838R47-R48) - TLDR ~2x speedup for valid strings :)
=> Optimize valid64? and url_valid64?

lib/elixir/lib/base.ex
The last one :)
Benchmark here https://github.com/sabiwara/elixir_benches/commit/73794bca2ab95af3ab73a32af7dfceeaf7d53b83 - also ~2x faster.
=> Optimize valid32? and hex_valid32?

lib/mix/lib/mix/compilers/erlang.ex, lib/mix/test/mix/tasks/compile.erlang_test.exs
Aligns compiler to these changes: https://github.com/erlang/otp/pull/9363
Related PR: https://github.com/elixir-lang/elixir/pull/14018
=> Send warnings to stderr in Erlang compiler

lib/elixir/lib/exception.ex
The api for links is ln(existing, new) but the old text said "from existing to new", where it should have said "to existing from new".
This fixes the text to make it more clear. Likely this error came from the example using "source.txt" and "target.txt" and it being natural to say "to target".
This changes the example to use "existing.txt" and "link.txt" so it is more obvious what is going on.
=> File.LinkError - fix confusing wording

lib/elixir/test/elixir/process_test.exs, lib/elixir/test/elixir/stream_test.exs, lib/elixir/test/elixir/test_helper.exs, lib/ex_unit/examples/one_of_each.exs, lib/ex_unit/test/ex_unit/assertions_test.exs, lib/ex_unit/test/ex_unit/capture_log_test.exs, lib/ex_unit/test/test_helper.exs, lib/iex/test/test_helper.exs, lib/logger/test/logger/translator_test.exs, lib/logger/test/test_helper.exs, lib/mix/test/mix/dep_test.exs, lib/mix/test/mix/umbrella_test.exs, lib/mix/test/test_helper.exs
=> Consistenly apply timeouts across suites

lib/elixir/pages/getting-started/case-cond-and-if.md
This is just to fix a small typo in the "getting started" section of the documentation
=> Fix typo in cond documentation

lib/elixir/lib/kernel/special_forms.ex
Rewrote some code snippets to remove side effects and compiler warnings. Also added a couple of tests and made them more consistent in `try/1`
=> Rewrite SpecialForms doc examples as doctests

lib/elixir/lib/string.ex
Discussed on https://groups.google.com/g/elixir-lang-core/c/JtWvn9aghgQ
The code addition itself is quite small.
=> Add String.count/2

lib/elixir/lib/kernel.ex
Add doctests where it's possible and make sense
=> Add doctests to Kernel module

lib/elixir/lib/kernel.ex
The structure of the `if` doc was a bit hard to understand, since:
- we now had the following 3 sections: "One-liner examples" / "Blocks examples" / "Examples"
- some examples were far away from the points they were illustrating (e.g. "Otherwise, `nil` will be
returned.")
- mixing of the `if(foo, do: bar)` and `if foo, do: bar` form, but AFAIK the former is less common and idiomatic nowadays?
I also noticed that the fact we can define a variable in the `if` condition wasn't explicitly documented, as well as scope rules more broadly (even if they aren't specific to `if`, it's probably the more common place people encounter it). Inspired from  [this](https://hexdocs.pm/elixir/1.18.3/try-catch-and-rescue.html#variables-scope)
=> Rework if/2 docs and mention variable scope

lib/elixir/lib/kernel/error_handler.ex, lib/elixir/lib/kernel/parallel_compiler.ex, lib/elixir/lib/module.ex, lib/elixir/lib/module/types/apply.ex, lib/elixir/src/elixir_erl.erl, lib/elixir/src/elixir_erl_compiler.erl, lib/elixir/src/elixir_module.erl, lib/elixir/test/elixir/kernel/parallel_compiler_test.exs, lib/elixir/test/elixir/module_test.exs, lib/iex/test/iex/helpers_test.exs, lib/mix/lib/mix/compilers/elixir.ex, lib/mix/lib/mix/tasks/deps.compile.ex, lib/mix/test/mix/tasks/app.config_test.exs, lib/mix/test/mix/tasks/app.start_test.exs, lib/mix/test/mix/tasks/archive_test.exs, lib/mix/test/mix/tasks/compile.elixir_test.exs
Prior to this pull request, Elixir would load modules as soon as
they were defined. However, because Erlang code loading
happens within a single process (the code server), this would
make it a bottleneck, reducing the amount of parallelization.
This pull request makes it so modules are loaded lazily. This
reduces the pressure on the code server, making compilation
up to 2x faster for large projects, and also reduces the amount
of overall work done.
Implementation wise, the parallel compiler already acts as a
mechanism to resolve modules during compilation, so we build
on that. This has the additional benefit of making compilation more
consistent: `Code.ensure_loaded` will be less dependent on the
order code is compiled.
The only potential regression in this approach happens if you
have …
=> Load modules lazily and only if needed

lib/elixir/lib/calendar/duration.ex
The "circular dependency" is only for Dialyzer for now so I think this is okay.
=> Use t:Calendar.microsecond/0 in Duration docs

lib/elixir/lib/code.ex
`iex> Code.loaded?(Atom)`  gave race condition, at least localy.
=> Improve docs for `Code` module

lib/mix/lib/mix/tasks/xref.ex
Fix the markdown link syntax for "strongly connected components" on line 386. The link was incorrectly formatted as (text)[url] instead of the proper markdown format [text](url), which caused it to render incorrectly in the generated documentation.
This fix ensures the link will properly render as a clickable hyperlink when the documentation is generated, improving the user experience for developers consulting the Mix.Tasks.Xref documentation.
=> docs: fix inverted markdown link format in Mix.Tasks.Xref

lib/elixir/test/elixir/application_test.exs
I'm not sure why here are two identical tests(with `@app` and `:elixir`, which the same), but we expect the message only once, and if something bad is sent from `assert compile_env(:elixir, :unknown, :default) == [nested: [key: :value]]`, we will check the right message from `assert compile_env(@app, :unknown, :default) == [nested: [key: :value]]` and this will be a false positive result.
=> Add two missed assertions to application tests

lib/elixir/lib/regex.ex, lib/elixir/test/elixir/regex_test.exs
=> Fix Regex.split/2 edge case with empty chunks

lib/elixir/lib/string.ex
Replace Russian "оптимизации" (eng. optimisations, added [here](https://github.com/elixir-lang/elixir/commit/802d5ebc00cb9ad47992d0ac624af83bba8afc32)) with Ukrainian "оптимізації" in `String.codepoints/1` examples.
It includes more Cyrillic characters like "ї" and "і" (distinct from the Latin "i" in Unicode), and will also bring a tiny smile to Ukrainian developers during these difficult times 💙💛
=> Adjust examples in `String.codepoints/1`

lib/elixir/test/elixir/enum_test.exs
Checked for some holes in the coverage, often due to not testing the `Enumerable.reduce` fallback.
Reusing [this handy pattern](https://github.com/elixir-lang/elixir/blob/main/lib/elixir/test/elixir/enum_test.exs#L272) (also [here](https://github.com/elixir-lang/elixir/blob/main/lib/elixir/test/elixir/enum_test.exs#L237)) when I need a stream.
=> Improve test coverage for Enum for non-list inputs

lib/mix/lib/mix/tasks/xref.ex, lib/mix/test/mix/tasks/xref_test.exs
This pull request fixes the behavior of the `--min-cycle-size` option in `mix xref graph --format cycles`.
Previously, cycles with a size equal to the specified minimum were excluded.
For example, running `mix xref graph --format cycles --min-cycle-size 2` would only include cycles of size >= 3, which is unintuitive and inconsistent with the option name.
This change updates the behavior to be inclusive, so that `--min-cycle-size 2` includes **all cycles of size >= 2**, as expected.
Fixes: #14474
=> Make `--min-cycle-size` in `mix xref graph` inclusive

lib/elixir/test/elixir/enum_test.exs
For sort, is a bit challenging to ensure that we go through all these branches, except for using a big enough collection.
=> Increase test coverage for Enum

lib/mix/lib/mix/local.ex, lib/mix/lib/mix/rebar.ex, lib/mix/lib/mix/tasks/local.hex.ex, lib/mix/lib/mix/tasks/local.rebar.ex, lib/mix/test/mix/local_test.exs, lib/mix/test/test_helper.exs
See https://github.com/hexpm/hex/pull/1069
I've manually executed release scripts from the Hex PR so the following URLs are already working and thus this can be tested locally.
- https://builds.hex.pm/installs/hex.csv
- https://builds.hex.pm/installs/1.17.0/hex-2.2.1-otp-25.ez
- ...
- https://builds.hex.pm/installs/rebar.csv
- https://builds.hex.pm/installs/1.18.3/rebar3-3.22.0-otp-25
- ...
=> Install Hex and Rebar per OTP release

CHANGELOG.md, lib/elixir/lib/node.ex
ExDoc detected these wrong references
=> Fix warnings due to incorrect references in docs detected by ExDoc

Makefile
Usage:
$ DOCS_OPTIONS="--warnings-as-errors" make docs
$ DOCS_OPTIONS="--warnings-as-errors --formatter html" make docs
=> Introduce DOCS_OPTIONS env variable in Makefile

.github/workflows/ci.yml, Makefile
Implements https://github.com/elixir-lang/elixir/pull/14480#issuecomment-2867583787
Depends on #14484
=> CI: build does using `--warnings-as-error` ExDoc flag

lib/elixir/lib/node.ex
`opts` is confusing when the original arg name was `type`.
Additional add guards for `tick_time`.
=> Improve arg name in recently deprecated `Node.start/2-3`

lib/elixir/pages/getting-started/debugging.md
This PR fixes the markdown link formatting in the debugging documentation where commas were incorrectly placed inside the link brackets rather than outside. This small correction improves the visual consistency of links throughout the documentation and follows standard markdown best practices.
Before:
* Integration with OS level tracers, such as [Linux Trace Toolkit,](url) [DTRACE,](url) and [SystemTap](url)
After:
* Integration with OS level tracers, such as [Linux Trace Toolkit](url), [DTRACE](url), and [SystemTap](url)
=> Doc: Fix markdown link formatting in debugging guide

lib/elixir/lib/module/types/of.ex, lib/elixir/test/elixir/module/types/integration_test.exs
Tentative fix for https://github.com/elixir-lang/elixir/issues/14365
=> Allow using protocol list implementation on improper lists

lib/elixir/test/elixir/module/types/integration_test.exs
I also wanted to understand why and what broke it and add a comment, seems to be linked to [this](https://github.com/elixir-lang/elixir/pull/14343#issuecomment-2748222909) but I'm not sure what makes a test trigger it?
There's nothing logged either to indicate what went wrong, so maybe it's a separate issue?
=> Fix CI cover

lib/elixir/lib/module/types/descr.ex, lib/elixir/lib/module/types/expr.ex, lib/elixir/test/elixir/module/types/descr_test.exs, lib/elixir/test/elixir/module/types/expr_test.exs
Implementing set-theoretic function types with correct variance properties: contravariant for arguments, covariant for returns.
The representation uses BDDs: binary trees with functions as internal nodes and 0/1 leaves where paths to 1-leaves represent function intersections present in the type.
So type `(integer() -> atom()) and (float() -> pid())` is represented as:
```
integer() -> atom()
/                \
float() -> pid()             0
/              \
1               0
```
Function nodes are triples `{tag, inputs, output}` where `tag` is `:weak` (`:strong` to be implemented), `inputs` is a list of argument types, and `output` is the return type.
Set-theoretic operations (union, intersection, difference) distribute along the BDD structure. 
Function operators include:
- …
=> Add set-theoretic function types

lib/ex_unit/lib/ex_unit/case.ex
the strong "never" in async is contradicted by the new `parameterize` setting
=> exunit.case docs: parameterize violates the "never run concurrently" async docs

lib/elixir/lib/enum.ex
Benchmarks show an important impact for both [count_until/2](https://github.com/sabiwara/elixir_benches/commit/b2e3f35f0df44dfbad8cd5c4a3b80fc2) and [count_until/3](https://github.com/sabiwara/elixir_benches/commit/d3bfaf575889c10317508905b3f5034e7a0eb3aa)
=> Optimize Enum.count_until/2-3

lib/elixir/lib/module.ex
also corrects a typo
verified the section links are formatted correctly with local spin through `make docs`
=> Module docs: make section references into links

lib/mix/lib/mix/tasks/release.init.ex
wmic is no longer available on Windows 11.
As a reminder, this codepath is only hit when setting:
reboot_system_after_config: true
So I'd guess few users were affected.
=> mix release: Fix RELEASE_SYS_CONFIG for Windows 11

lib/elixir/pages/anti-patterns/code-anti-patterns.md
- Add comparison table for access notations
- Improve explanations with clearer examples
- Add example of error propagation
- Include guidance for when to use each access method
- Format examples for better readability
=> docs: enhance non-assertive map access anti-pattern documentation

lib/elixir/lib/application.ex, lib/elixir/lib/enum.ex
It wasn't available to define arguments order in `fun` from docs and doctests, so I think it should be said excplicitly
=> Enum scan improvements

lib/mix/lib/mix/local.ex, lib/mix/lib/mix/rebar.ex, lib/mix/lib/mix/tasks/local.hex.ex, lib/mix/lib/mix/tasks/local.rebar.ex, lib/mix/test/mix/local_test.exs, lib/mix/test/test_helper.exs
Back port of https://github.com/elixir-lang/elixir/pull/14477
=> Install Hex and Rebar per OTP release (Elixir v1.18)

lib/elixir/lib/exception.ex, lib/elixir/test/elixir/exception_test.exs
According to https://github.com/elixir-lang/elixir/issues/14519
=> Put error doctests to run pipeline

lib/elixir/lib/gen_server.ex
This PR comes as a result of discussion in [elixirforum thread](https://elixirforum.com/t/multiple-liveviews-on-the-same-page-sharing-data/70941) where the documentation for `GenServer.call/3` was found to be lacking explicit mention of PID as a valid value for the `server` argument. Documentation sends reader to "Name registration" section, which in its vast majority covers the subject of naming and registering GenServers. While it in fact mentions the possibility of using PID in one of the paragraphs, it is arguably better to make a distinction as PID is neither a "name" nor something that the user can "register". This change should make it clear for situations where only PID is available, without deep referring to another section of the documentation, potentially overlooking the single …
=> Minor documentation update - explicit mention of PID in `GenServer.call/3`

lib/elixir/lib/exception.ex
I noticed this this error in ElixirLS. I don't know what code triggered it but the `ErlangError.normalize` implementation doesn't seem correct in assuming that Access protocol can be used on unknown value coming from stack trace.
```
** (UndefinedFunctionError) function Foo.fetch_2 is undefined (Foo does not implement the Access behaviour
You can use the "struct.field" syntax to access struct fields. You can also use Access.key/1 to access struct fields dynamically inside <REDACTED: user-file-path>)
(foo_tools 0.1.0) Foo.fetch(%Foo{direct: MapSet.new([]), transient: %{}, all: MapSet.new([])}, :transient)
(elixir 1.17.3) <REDACTED: user-file-path>:322: Access.get/3
(elixir 1.17.3) <REDACTED: user-file-path>:2288: ErlangError.normalize/2
(elixir 1.17.3) <REDACTED: user-file-path>:192: …
```
=> Do not use Access protocol on values that may be structs when normalizing erlang errors

lib/elixir/lib/module/types/descr.ex, lib/elixir/test/elixir/module/types/descr_test.exs
Introduce a new function to simplify tuple types by eliminating negations. Refactor existing tuple reduction logic into `tuple_reduce` to be able to either keep tuple literals as is (for negation elimination) or join their content (to compute `tuple_values`).
=> Add tuple elimination of negations 

lib/elixir/lib/io/ansi.ex
Here's what it looks like:
The main reason for this is that the alternative is to `:reset` and restore the color settings which isn't ideal in code that doesn't care about colors.
=> Add ANSI codes to turn off conceal and crossed_out

lib/elixir/lib/inspect.ex, lib/elixir/lib/inspect/algebra.ex, lib/elixir/lib/map_set.ex, lib/elixir/lib/stream.ex, lib/elixir/test/elixir/inspect_test.exs, lib/iex/lib/iex/info.ex
=> Allow updated options to be returned from Inspect protocol

lib/elixir/src/elixir_quote.erl, lib/elixir/test/elixir/macro_test.exs
Close https://github.com/elixir-lang/elixir/issues/14497
This approach might be overkill, maybe making it regex aware is better here. I'm not sure.
=> More precise error message when escaping a regex with a ref

lib/elixir/lib/module/types/descr.ex
In the same way we introduced `non_disjoint_intersection`
to optimize compatibility, we introduce `empty_difference`
to optimize subtyping.
=> Optimize subtype? by aborting early

lib/mix/test/mix/tasks/profile.tprof_test.exs
Fixes: #14564
This fix implements `Erlang/OTP` version check. The alternative solution could be:
```elixir
[_warmup, _profile_results, _columns, _total, first, second, _profile_done, ""] =
String.split(result, ~r/\n+/)
list = Enum.map([first, second], &String.split(&1, ~r/\s+/))
sort_func = fn result_colls ->
result_colls
|> List.last()
|> String.to_float()
end
list == Enum.sort_by(list, sort_func)
```
The alternative solution additionally does not relies on `3.\d{2}` value pattern of `PER CALL` column.
=> Relax assertions when both PER CALL values are equal (Erlang/OTP 28) 

lib/elixir/pages/mix-and-otp/distributed-tasks.md
As a follow-up to issue #14559, where I clearly failed to read the instructions properly, here is a pull request making the desired shell location in the OTP learners' project painfully obvious for those like myself.
=> Clarify why and how to start second session for tests

lib/elixir/lib/port.ex, lib/elixir/src/elixir_map.erl
In these two cases, the existing text has the opposite meaning to that intended.
=> Fix use of prefer with '-ing'

lib/mix/test/mix/tasks/profile.tprof_test.exs
In https://github.com/elixir-lang/elixir/pull/14565, we changed the memory "per-call" sorted test to be memory "calls" sorted, which is exactly the same as the previous test.
If we don't want to test per call sorting, we could just remove it?
=> Remove redundant memory-per-call test

lib/elixir/src/elixir_erl_pass.erl, lib/elixir/test/elixir/fixtures/dialyzer/opaque_inline.ex, lib/elixir/test/elixir/kernel/dialyzer_test.exs
Close https://github.com/elixir-lang/elixir/issues/14576
Maybe we don't need the test if these are expensive, but I could confirm it works.
=> Mark inlined function call result as generated

lib/elixir/src/elixir_erl_pass.erl
Fixes
```
true.asd
** (BadMapError) expected a map, got:
false
iex:2: (file)
```
=> Fix invalid warning on no parens call on true

lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/code_test.exs
I noticed code with invalid UTF8 escapes crash with badarg
repro:
```
:"\x963"
```
or
```
C.\"j\\x963<?j[On%K^!q5;V[`iU.WEI[\\<5\" )Mm0l@
```
```
* 1st argument: invalid UTF8 encoding
:erlang.binary_to_atom(<<150, 51>>, :utf8)
(elixir 1.18.4) src/elixir_tokenizer.erl:1021: :elixir_tokenizer.unsafe_to_atom/4
(elixir 1.18.4) src/elixir_tokenizer.erl:507: :elixir_tokenizer.tokenize/5
```
Other cases dealing with invalid UTF8 tend to raise `UnicodeConversionError`. I'm not convinced this is the best approach though. Maybe the tokenizer should return errors instead of raising
=> Consistently raise UnicodeConversionError in tokenizer

lib/elixir/lib/module/types/descr.ex, lib/elixir/test/elixir/module/types/descr_test.exs
Adopt a fully nod representation for tuples, as union of (non-empty, see below) positive tuples. All negations are eliminated as soon as they appear.
This simplifies the code for many tuple operators.
Additionally: made tuple constructor `tuple_descr` check emptiness of the list of types used to create a tuple. This makes `tuple([none(), integer()])` instantly create `none()`. Combined with the new representation, this allows checking for emptiness of tuple types in constant time (if the field is present, it is non-empty).
=> Simplified tuple definitions by removing negations.

lib/elixir/lib/module/types/apply.ex, lib/elixir/lib/module/types/descr.ex, lib/elixir/lib/module/types/expr.ex, lib/elixir/test/elixir/module/types/descr_test.exs, lib/elixir/test/elixir/module/types/expr_test.exs, lib/elixir/test/elixir/module/types/integration_test.exs
- 1. Memoize `phi()`.
- 2. Fast path: if there are no `none()` in the arguments of an intersection, we can compute subtyping quicker using `fun_apply`
- 3. Remove duplicates in `tuple_difference` (reuses `tuple_union` logic).
2. and 3. are sufficient to make the `fun_from_inferred_clauses` work. 
1. will be necessary for large function intersections with empty arguments.
Also adds inferred intersection types, in `fun_from_inferred_clauses`.
=> Perf optimizations and inferred intersections

lib/iex/lib/iex/helpers.ex, lib/iex/test/iex/helpers_test.exs
Probably not a very frequent case but it might be puzzling to `ls some_file/foo` and get back a non-existing path.
This makes it consistent with the shell `ls`:
=> Increase test coverage of IEx ls helper and handle edge case

lib/mix/lib/mix/tasks/test.ex
The issue is introduced in 99be673
The code is a bit complex because `require_test_helper` which might call `ExUnit.configure` is wrapped in the `try/catch`, which prevents it from assigning it to `opts` once in for all and pass it around.
https://github.com/elixir-lang/elixir/blob/main/lib/mix/lib/mix/tasks/test.ex#L663-L670
These two both now work:
```elixir
ExUnit.start(failures_manifest_path: "failed.txt")
```
```elixir
ExUnit.start(failures_manifest_path: "failed.txt")
raise "test the try/catch"
```
=> Prevent mix test from overriding :failures_manifest_path option

lib/elixir/lib/macro/env.ex, lib/elixir/src/elixir_dispatch.erl
This PR adds a new option `:local_for_callback` to `Macro.Env.expand_import` in order to allow hooking into local macro resolution and providing a custom resolver.
Rationale:
In ElixirSense minicompiler I need to resolve local macros using the metadata extracted from the AST. The current mechanism relying on `:elixir_def.local_for` is not going to work correctly when there is no real compilation in process. The current hacky code using `extra` filled with `__info__(:macros)` only returns public macros and with that only those already compiled and loadable. The result is improper tracking of references in traversed code.
Example code using the new option:
```elixir
case Macro.Env.expand_import(env, meta, fun, arity,
trace: true,
allow_locals: allow_locals,
check_deprecations: false, …
```
=> Add local_for_callback option to Macro.Env.expand_import

lib/ex_unit/lib/ex_unit/cli_formatter.ex, lib/ex_unit/lib/ex_unit/runner.ex, lib/ex_unit/mix.exs, lib/mix/lib/mix/compilers/test.ex, lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/tasks/test_test.exs
=> Add mix test --dry-run flag

lib/elixir/pages/getting-started/erlang-libraries.md
This will ensure that it appears in the short search results on ExDoc instead of having to navigate through to the search results.
=> Add ETS to the Erlang Term Storage section of erlang libs

lib/mix/lib/mix/dep.ex
This doesn't seem relevant to dep resolution and is quite spammy:
Before
After
=> Drop :app_properties when rendering dependency in mix

lib/elixir/lib/module/types/descr.ex
it's being always called with a map
=> Clean up unreachable clause of Types.Descr.atom_only? helper

lib/elixir/lib/io.ex
I've noticed that often people forget about the :printable_limit and :limit options of IO.inspeact . Adding it to the doc example will make it easier for for people to see these options in editors and online documentation.
=> chore: Add printable_limit and limit to IO.inspect doc examples

lib/mix/lib/mix/utils.ex, lib/mix/test/mix/utils_test.exs
DOT syntax requires escaping quotes in quoted string Other control characters are not strictly required to be escaped but a DOT graph containing them will most likely not be parsed by other tools See reference DOT syntax https://graphviz.org/doc/info/lang.html
=> Escape quotes and control chars in DOT

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
Print intermediate results when using dbg with pipes.
=> Print intermediate results of dbg for pipes

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
closes #14684 
based on the logic of min_max_by
=> feat - Enum.min_max sorter

lib/elixir/lib/enum.ex
- Add min_max/1 spec for confirming quickly that it returns a tuple
- Add back min_max/2 spec for the empty_result fallback clause, as a separate spec with non overlapping domain
- Add min_max/2 empty head so that the doc shows 2nd arg as sorter_or_empty_fallback and not just empty_fallback from the first clause
(min_max/3 spec didn't change, was only re-formatted for compactness)
=> Improve Enum.min_max/1,2,3 specs and docs

lib/elixir/src/elixir_expand.erl, lib/elixir/test/elixir/kernel/expansion_test.exs
I noticed this code crashes
```
iex(1)> defmodule A do
...(1)> @asd Foo
...(1)> alias @asd.{Bar}
...(1)> end
** (FunctionClauseError) no function clause matching in :elixir_aliases.do_concat/2    
The following arguments were given to :elixir_aliases.do_concat/2:
[
{{:., [line: 3], [Module, :__get_attribute__]}, [line: 3], [A, :asd, 3, true]},
:Bar
]
"Elixir"
(elixir 1.18.4) src/elixir_aliases.erl:183: :elixir_aliases.do_concat/2
(elixir 1.18.4) src/elixir_aliases.erl:171: :elixir_aliases.concat/1
(elixir 1.18.4) src/elixir_expand.erl:575: anonymous fn/8 in :elixir_expand.expand_multi_alias_call/7
(elixir 1.18.4) src/elixir_expand.erl:701: :elixir_expand.mapfold/5
(elixir 1.18.4) src/elixir_expand.erl:625: :elixir_expand.expand_block/5
(elixir 1.18.4) src/elixir_expand.erl:48: …
```
=> Fix expand crash on invalid multialias root

lib/ex_unit/lib/ex_unit/case.ex
Errors were a bit cryptic when running `mix test`.
`@tag "a"` before:
```
== Compilation error in file test/ex_unit_tag_error_test.exs ==
** (FunctionClauseError) no function clause matching in anonymous fn/2 in ExUnit.Case.normalize_tags/1
The following arguments were given to anonymous fn/2 in ExUnit.Case.normalize_tags/1:
"a"
%{}
(ex_unit 1.18.4) lib/ex_unit/case.ex:896: anonymous fn/2 in ExUnit.Case.normalize_tags/1
(elixir 1.18.4) lib/enum.ex:2546: Enum."-reduce/3-lists^foldl/2-0-"/3
(ex_unit 1.18.4) lib/ex_unit/case.ex:669: ExUnit.Case.register_test/6
test/ex_unit_tag_error_test.exs:7: (module)
(elixir 1.18.4) lib/kernel/parallel_compiler.ex:542: Kernel.ParallelCompiler.require_file/2
(elixir 1.18.4) lib/kernel/parallel_compiler.ex:425: anonymous fn/5 in …
```
=> ExUnit: Raise explaining what failed on invalid tags

lib/elixir/lib/dynamic_supervisor.ex, lib/elixir/lib/supervisor.ex, lib/elixir/lib/task/supervisor.ex
Avoid using the term exception as it could be confusing for the user and mislead him thinking it could be an Elixir `t:Exception.t/0`.
=> Rephrase docs when mentioning out-of-memory errors

lib/elixir/lib/kernel.ex, lib/elixir/lib/macro.ex, lib/elixir/lib/regex.ex, lib/elixir/src/elixir_quote.erl, lib/elixir/test/elixir/macro_test.exs, lib/elixir/test/elixir/test_helper.exs
Take 2 for https://github.com/elixir-lang/elixir/pull/14719.
Leverages `:re.import` added in https://github.com/erlang/otp/pull/9976.
Here I went for `Macro.escape` rather than `:elixir_expand`, because `:elixir_expand` is harder to work with since we're already in AST land and the AST for a struct is hard to pattern-match on.
This works since `Macro.escape` is used in `~r`, and also fixes the escaping issue discussed previously. But this is violating the assumption that escape emits AST for a literal, which is probably a no-go.
Will work on supporting the `:export` option separately since this is not strictly needed for this.
=> Add __escape__/1 and use it to fix Regex escaping in OTP28.1 

lib/mix/lib/mix/tasks/profile.fprof.ex, lib/mix/lib/mix/tasks/test.ex
Related PR: https://github.com/elixir-lang/elixir/pull/14635
=> Use thin-space (U+2009) as a numeric separator in regular English language

lib/elixir/src/elixir_quote.erl, lib/elixir/test/elixir/macro_test.exs
Small improvement following https://github.com/elixir-lang/elixir/pull/14720.
Applying the same shallow-validation we use for `unquote` to fail early and provide better feedback if `Macro.escape` returns obviously broken AST (e.g. forgot to use `quote`).
Will backport.
=> Shallow-validate the return of __escape__/1

lib/elixir/lib/code/fragment.ex
I noticed this crash in the logs. I'm not sure what input produced that error.
```
an exception was raised:
** (FunctionClauseError) no function clause matching in Code.Fragment.drop_tokens_2
(elixir 1.18.3) <REDACTED: user-file-path>:1209: Code.Fragment.drop_tokens([], 2)
(elixir 1.18.3) <REDACTED: user-file-path>:1184: Code.Fragment.container_cursor_to_quoted_2
```
=> Fix trailing token crash

lib/elixir/src/elixir_bitstring.erl, lib/elixir/test/elixir/kernel/expansion_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs
Close https://github.com/elixir-lang/elixir/issues/14737
=> Do not consider variables from pattern in bitstring spec

.github/workflows/release.yml
- **Introduced `environment: release`** to the `publish-to-hex` job so that only workflows explicitly targeting the release environment can read sensitive values.  
- **Added a safeguard** – `if: ${{ vars.HEX_AWS_REGION }}` – to skip the job in forks that don’t define release variables.  
- **Converted non-secret AWS settings to environment variables**  
- `${{ vars.HEX_AWS_REGION }}`  
- `${{ vars.HEX_AWS_S3_BUCKET }}`  
These are configuration values, not credentials, so variables are a better fit and remain visible only to jobs using the `release` environment.  
- **Scoped Fastly secrets to the purge step** instead of the whole job, keeping tokens out of steps that don’t need them.
Placing secrets in an environment and scoping them to the minimum surface area:
* prevents forks and …
=> Tighten secret scope in `release.yml`

.github/workflows/release.yml
Backported PRs:
* https://github.com/elixir-lang/elixir/pull/14604
* https://github.com/elixir-lang/elixir/pull/14627
The commits are based on the SBoM PR (#14241) which changed the actions.
Adding `attestations: write` permission fixes the issue. See
https://github.com/maennchen/elixir/actions/runs/17445512019/job/49539258297
=> Fix backport of workload identity & CI release scope

lib/elixir/lib/access.ex
This PR replaces the `Enum.filter |> Enum.map` chain in `Access.filter` with a more efficient `for` comprehension that eliminates unnecessary intermediate list creation, which (I believe) should be a somewhat meaningful improvement for large lists.
The tests for the module pass locally:
```sh
$> bin/elixir lib/elixir/test/elixir/access_test.exs
Running ExUnit with seed: 375552, max_cases: 20
Excluding tags: [:re_import, {:windows, true}, {:distributed, true}]
...............................................................................................
Finished in 0.1 seconds (0.09s on load, 0.01s async, 0.00s sync)
54 doctests, 41 tests, 0 failures
```
=> Optimize Access.filter to eliminate intermediate list creation

lib/elixir/pages/references/compatibility-and-deprecations.md, lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/tasks/test_test.exs
Close https://github.com/elixir-lang/elixir/issues/14751
=> Have mix test fail if warnings and --warnings-as-errors

.github/workflows/release.yml
Follow up to https://github.com/elixir-lang/elixir/pull/14627#issuecomment-3292707930
Apparently, GitHub evaluates job conditions before taking the environment into account. This leaves me with 3 options (and a lot more not great ones):
* Move the condition to each step instead of the job
* Extract the steps into a shared workflow and call that one conditionally (something like `.github/workflows/publish_builds_hex_pm/action.yml`)
* Just make it fail if the variables are not present **<= chose this one**
=> Correct builds.hex.pm Publish Condition in CI

lib/elixir/lib/kernel.ex, lib/elixir/lib/kernel/utils.ex, lib/elixir/lib/macro.ex, lib/elixir/src/elixir_quote.erl, lib/elixir/test/elixir/macro_test.exs
Close https://github.com/elixir-lang/elixir/issues/14771
=> Bugfix: Macro.escape/1 properly escapes meta in :quote tuples

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
I tested several scenarios and noticed that the memory usage could easily go down by a 3~6x factor:
https://github.com/sabiwara/elixir_benches/commit/db829b8ab0dcd4f2b2e888985b53f9083cfffb16
See individual commits.
For `Enum.into(struct, map, fun)` (first commit), I actually just had to remove a specialized clause that doesn't feel needed, was probably just copy-pasted from into/2.
Optimizing `MapSet` as a collectable feels legit, given it is a core data structure - in the same way that we have some optimizations for ranges as enumerables. Especially given the factors involved.
As a follow-up, I also plan to optimize `into: MapSet.new()` in comprehensions.
Given how wasteful it is right now (see bench above), it kind of defeats the purpose of trying to merge steps in one pass vs a regular …
=> Optimize Enum.into/2 and Enum.into/3

lib/elixir/lib/json.ex
Show usage of `:except` option and reword docs to explicitly encourage using `:only`.
=> Update `JSON.Encoder` moduledoc around `:only` and `:except`

lib/iex/lib/iex/evaluator.ex, lib/iex/lib/iex/server.ex, lib/iex/test/iex/interaction_test.exs
For example:
If you pasted this into an iex shell, you might have a very very bad day.
```elixir
MyApp.Accounts.User
|> Ecto.Query.where(user], user.id == 1) # note the missing open bracket
|> MyApp.Repo.delete_all()
```
---
This is still rough, things I'm not sure about:
1. I'm not sure how we feel about the method of just rewriting the evaluated code to check for this condition.
2. I'm trying to display the operator, but it's using the tokenized representation of it and I couldn't find a mapper for that. I can just not display the operator, or I can write a mapping function myself.
3. I should probably colorize and indent the message properly, but wanted to validate the approach before pushing further.
---
In practice it looks like this:
```elixir
Interactive Elixir (1.20.0-dev) - press …
```
=> make errors when piping in expressions safer

lib/elixir/lib/module/parallel_checker.ex, lib/elixir/lib/module/types/descr.ex, lib/elixir/src/elixir_erl.erl, lib/elixir/test/elixir/module/types/descr_test.exs, lib/elixir/test/elixir/module/types/expr_test.exs, lib/elixir/test/elixir/module/types/integration_test.exs, lib/elixir/test/elixir/protocol/consolidation_test.exs
Changing the representation of maps, tuples to instead use trees (binary decision diagrams).
As we use more and more the difference operator in the type system (e.g. to compute `fun_from_inferred_clauses(args_clauses)` for inferred function types from patterns), the "DNF" representation started running into pathological cases and hog out time during emptiness checks, and printing.
The BDD is now used for set operations and subtyping, and translated (using previous logic and simplications) to DNF for printing and type operations like map fetch.
The BDD representation is common to maps, tuples, lists and functions. Some functions are generic (called bdd_difference, bdd_intersection, ...). 
We also changes some algorithms:
- `tuple_eliminate_negation` was not generating disjoint tuples. It …
=> Rewrite maps, tuples, lists as BDDs. Performance improvements.

lib/elixir/src/elixir_erl_for.erl
Follow-up for https://github.com/elixir-lang/elixir/pull/14774.
Fixes the discrepancy found in the previous benchmark: https://github.com/sabiwara/elixir_benches/commit/cd1c9a30adb9e6521bffc5d502accbacccfcb76d.
Before
After
Note: this is basically the same as building a list, but we don't need the `lists:reverse` step and replace it with `MapSet.new/1`.
=> Optimize for comprehensions into: MapSet

lib/mix/lib/mix/tasks/test.ex
These are documented in the ExUnit.Case docs, but documenting them here makes sense too as mix is usually used to invoke the tests.
=> Add mix test examples for filtering with `--only` and `--exclude`

lib/mix/lib/mix/sync/lock.ex, lib/mix/lib/mix/sync/pubsub.ex, lib/mix/lib/mix/utils.ex
=> Improve user detection in lock and pubsub implementation

lib/mix/lib/mix/tasks/test.ex
Matches the docs recommendation: https://hexdocs.pm/mix/1.19.0-rc.0/Mix.Tasks.Test.html.
The current hint ,`test_ignore_filters: false`, causes the following error:
The second commit provides better feedack is we forget to wrap the config into a list, otherwise it fails later down the line since we build and propagate an improper list. It might be overkill, happy to remove it.
Alternatively, we could use `Enum.concat` over `++` which could be slightly better?
To be backported.
=> Fix inaccurate hint for disabling :test_ignore_filters

lib/elixir/lib/module/types/descr.ex, lib/elixir/test/elixir/module/types/descr_test.exs
The changes were done as part of this commit and are now reverted: https://github.com/elixir-lang/elixir/pull/14693/commits/d157f5fe8e444e324be7b7ea1ad57196c36f924b
=> Fix optimizations for closed map checking

lib/elixir/lib/module/types/expr.ex, lib/elixir/lib/task.ex, lib/elixir/pages/getting-started/debugging.md, lib/elixir/test/elixir/module/types/expr_test.exs
Elixir v1.19 introduces a warning related to structs,
hint: given pattern matching is enough to catch typing errors, you may optionally convert the struct update into a map update. For example, instead of:
user = some_fun()
%User{user | name: "John Doe"}
it is enough to write:
%User{} = user = some_fun()
%{user | name: "John Doe"}
Since this could be seen by new-comers to the language, offering a better user experience by avoiding abbreviations. Favoring the usage of "some_function" instead of "some_fun"
=> Use "some_function" instead of "sum_fun" in warnings
