elixir-lang/elixir

- lib/ex_unit/lib/ex_unit/formatter.ex
- lib/ex_unit/test/ex_unit/assertions_test.exs
- lib/mix/lib/mix/dep/loader.ex
- lib/mix/lib/mix/task.ex
- lib/mix/test/mix/rebar_test.exs
- Just a few minor changes to clean up some doc's / and tests.
> Fix a few simple typo's, found while perusing the code.

- lib/mix/test/mix/tasks/new_test.exs
Hi,
Just adding a missing `assert` call and fixing some expected matchings.
Cheers
> add missing assert call

- lib/elixir/lib/kernel.ex
- lib/elixir/test/elixir/kernel/errors_test.exs
> Improve error message when using attributes inside match in module

- lib/logger/lib/logger.ex
- lib/logger/test/logger/backends/console_test.exs
> Fix the logging with `metadata[:function]`

- lib/elixir/lib/record.ex
- Also adds docs for defining records that were extracted with anonymous functions
Changing Record#extract to a function removes ArgumentErrors that arise from Macro.escape when extracting records defining anonymous functions.
```elixir
iex(2)> Record.extract :apns_connection, from_lib: "apns/include/apns.hrl"
** (ArgumentError) cannot escape #Function<12.90072148/2 in :erl_eval.expr/5>. The supported values are: lists, tuples, maps, atoms, numbers, bitstrings, pids and remote functions in the format &Mod.fun/arity
(elixir) src/elixir_quote.erl:302: :elixir_quote.bad_escape/1
(elixir) src/elixir_quote.erl:246: :elixir_quote.do_quote/3
(elixir) src/elixir_quote.erl:383: :elixir_quote.do_splice/5
(elixir) src/elixir_quote.erl:141: :elixir_quote.escape/2
(elixir) lib/macro.ex:307: …
```
> Change Record#extract to a function

- lib/elixir/lib/kernel.ex
This PR is very similar to #3046. I was just reading through the `Kernel` module and fixed some docs here and there. I left some comments in the diff for the "biggest" changes.
Thanks!
> Documentation polishes for some of the functions in the Kernel module

- lib/elixir/lib/kernel.ex
This PR is very similar to #3048 and #3046. I'm going through the `Kernel` module and fixing minor things in the docs as I go, but there are a lot of functions in there so I'm doing a chunk at a time :).
I've added comments in the diff to justify some changes. Thanks!
> Polish the docs of a bunch of Kernel functions

- lib/elixir/test/erlang/atom_test.erl
Test case for issue #3059, #2986
> Add positive test case for punctuation in atoms

- lib/elixir/lib/bitwise.ex
- lib/elixir/test/doc_test.exs
Clarify and expand textual descriptions; add examples.
> Hack The Docs contribution

- lib/elixir/lib/task/supervised.ex
- lib/logger/lib/logger/translator.ex
- lib/logger/test/logger/translator_test.exs
From 17.4 OTP behaviours include the stacktrace in the logged reason when `exit/1` is called. If an Elixir exception is raised, or the reason can be normalized to an Elixir exception (not `ErlangError`), the exception is formatted as an exception: 
```
** (Exception) message
```
Otherwise the reason is formatted using Exception.format_exit/1:
```
** (stop) :reason
```
Addresses #3052.
TODO:
> Handle OTP 17.4 error_logger terminate reasons

- lib/mix/lib/mix/utils.ex
The remaining call is for windows systems using powershell and I don't know the appropriate token
parsing for powershell command lines. And it's down to one commit.
> Replaced all but one Mix.shell.cmd call with System.cmd. 

- lib/mix/lib/mix/tasks/new.ex
> remove blank in README template

- lib/elixir/lib/float.ex
- Fixed some whitespace
- Fixed some argument names
- Rephrased a couple of sentences
Let me know if I can do anything else. Thanks!
> Polish the docs for the functions in the `Float` module

- lib/elixir/lib/dict.ex
- lib/elixir/test/elixir/dict_test.exs
> Adds Dict.get_lazy/3, Dict.pop_lazy/3, Dict.put_new_lazy/3

- lib/elixir/lib/regex.ex
not a major flaw but missed the developer without understanding
> the example is correct but in the description have a small difference

- lib/elixir/lib/exception.ex
- lib/elixir/lib/kernel/special_forms.ex
- lib/mix/lib/mix/compilers/erlang.ex
inspired by https://github.com/elixir-lang/elixir-lang.github.com/pull/490/
> remove duplicate words + add quotes to nil and false

- lib/elixir/src/elixir_errors.erl
Following up on https://github.com/elixir-lang/elixir/pull/3145.
These are covered by `invalid_quoted_token` in `errors_test.exs`.  The only difference I am aware of is there is no fall-back equivalent to what was line 70.  Not sure if that was needed or just there to avoid a `case` without a catch-all option.
> Refactor compiler errors (elixir_errors:parse_error/4)

- lib/elixir/lib/enum.ex
- lib/elixir/lib/stream.ex
- lib/elixir/lib/stream/reducers.ex
- lib/elixir/test/elixir/enum_test.exs
- lib/elixir/test/elixir/stream_test.exs
Extra wish: Backport to 1.0.4 :)
> Add dedup(_by) and usort(_by) to Enum and Stream.

- lib/elixir/lib/stream.ex
> Make Stream.dedup/1 use Stream.dedup_by/2.

- lib/elixir/lib/enum.ex
- lib/elixir/test/elixir/enum_test.exs
Fixes https://github.com/elixir-lang/elixir/issues/3142
> Deprecate Enum.uniq/2 in favor of Enum.uniq_by/2

- lib/elixir/lib/behaviour.ex
- lib/elixir/lib/code.ex
- lib/elixir/src/elixir_module.erl
- lib/elixir/test/elixir/behaviour_test.exs
- lib/elixir/test/elixir/kernel/docs_test.exs
> Store behaviour docs in the byte code

- lib/eex/lib/eex/engine.ex
as per https://github.com/elixir-lang/elixir/pull/3205#discussion_r27139001
> correct @spec for `handle_expr`

- lib/elixir/lib/set.ex
Just some rephrasing, some formatting and some minor corrections.
> Polish the docs for the `Set` module

- lib/iex/lib/iex/evaluator.ex
- lib/iex/lib/iex/helpers.ex
- lib/iex/lib/iex/history.ex
- lib/iex/test/iex/helpers_test.exs
Continuation of #2318. Closes #2264. Cancels #3123.
> Improve handling of the IEx history state

- lib/eex/lib/eex/engine.ex
in the same fashion as https://github.com/elixir-lang/elixir-lang.github.com/pull/503
the following command will search for repeated words
```bash
ag -i '\b((?!end)[a-z]+)\s+\1\b'
```
or to be used in https://github.com/elixir-lang/elixir-lang.github.com
```bash
ag -i '\b((?!(end|iex|true))[a-z]+)\s+\1\b'
```
> remove repeated word

- lib/mix/lib/mix/tasks/new.ex
- lib/mix/test/mix/tasks/new_test.exs
My attempt to do #3275. What are your thoughts? :)
Also, is there a way to run just one file or module or tests in this project? I couldn't work out how to do anything more specific than `make test`.
Cheers,
Louis
> Check on mix new if the given application module exists and raises if so

- lib/eex/lib/eex.ex
The old formatting is much nicer. :)
This reverts commit d49fb0662c98ef4079dbad35128034495e03592f.
#3297
> Revert d49fb06 now underlying issue has been resolved.

- Makefile
- lib/elixir/test/elixir/kernel/cli_test.exs
Hi,
I am packaging elixir for the official Debian archive. These changes make small improvements to the packaging, which is BTW already quite good, to make it even easier to build distribution packages.
The commits messages for each individual  commit should be self-explanatory.
> Packaging improvements

- lib/elixir/lib/port.ex
- lib/elixir/src/elixir_rewrite.erl
- lib/elixir/test/elixir/port_test.exs
Hey, I would appreciate any feedback on this.
> Correct `Port.info/1,2` functions

- lib/iex/lib/iex/autocomplete.ex
- lib/iex/test/iex/autocomplete_test.exs
Possible fix for
https://github.com/elixir-lang/elixir/issues/3361
> IEx Autocomplete assumes module at each level, issue 3361

- lib/iex/lib/iex/helpers.ex
- lib/iex/test/iex/helpers_test.exs
* Remove current v/0
* Add v/0 such that v() == v(-1)
> Changes to "v" IEx helper

- lib/elixir/lib/kernel/special_forms.ex
Restructured to walk through types and the various options followed by an overview of binary matching. Small section on performance and optimization.
> Restructure and add to Kernel.<<>>/2 docs

- lib/mix/lib/mix/tasks/archive.install.ex
- lib/mix/test/mix/tasks/archive_test.exs
RFC @ericmj — This should close #3345.  Thanks in advance for your feedback :tada:
> Remove previous archive after download success

- lib/elixir/lib/string.ex
Noticed a couple of sentences in the String documentation that I thought could be improved.
Very open to suggestions if you have any.
> Minor string documentation improvements 

- lib/ex_unit/lib/ex_unit/capture_log.ex
- lib/ex_unit/lib/ex_unit/server.ex
- lib/ex_unit/test/ex_unit/capture_log_test.exs
- lib/ex_unit/test/ex_unit_test.exs
> Move add/remove logger backend to client

- lib/mix/lib/mix/tasks/archive.install.ex
- lib/mix/test/mix/tasks/archive_test.exs
Alright @ericmj, here's another go at #3345.  Let me know your thoughts.
> Only remove extra archives

- CONTRIBUTING.md
link to search issues in CONTRIBUTING.md
> link to search issues

- lib/elixir/lib/enum.ex
- lib/elixir/lib/stream.ex
As mention in #3473
I forked from the branch `v1.0`
Unfortunately I wasn't able to test the change, which should be necessary.
However when I was trying to test I got the following error:
```
simo@simo:~/elixir$ ls
bin              LEGAL    Makefile   rebar.config  VERSION
CHANGELOG.md     lib      README.md  RELEASE.md
CONTRIBUTING.md  LICENSE  rebar      src
simo@simo:~/elixir$ make clean
cd lib/elixir && ../../rebar clean
==> elixir (clean)
rm -rf ebin
rm -rf lib/*/ebin
rm -rf lib/elixir/test/ebin
rm -rf lib/*/tmp
rm -rf lib/mix/test/fixtures/git_repo
rm -rf lib/mix/test/fixtures/deps_on_git_repo
rm -rf lib/mix/test/fixtures/git_rebar
rm -rf lib/elixir/src/elixir.app.src
simo@simo:~/elixir$ make test
==> elixir (compile)
unexpected error compiling src/elixir_parser.yrl …
```
> Fix int take

- lib/logger/lib/logger.ex
- lib/logger/test/logger_test.exs
> Make `Logger.log/3` macro and introduce `Logger.bare_log/3` instead

- lib/elixir/lib/enum.ex
- lib/elixir/test/elixir/enum_test.exs
* Enum.slice/3 check for integers in `start` and `count` arguments.
* Enum.slice/2 check for integers in range limits.
solves https://github.com/elixir-lang/elixir/issues/3509
> Enum.slice Check for integers in arguments

- lib/elixir/lib/enum.ex
- lib/elixir/test/elixir/enum_test.exs
Plus a new tests has been added, dealting with negative floats
previous commit: https://github.com/elixir-lang/elixir/pull/3512
> Enum.slice/2: guard added was missing from previous commit

- lib/elixir/lib/task.ex
See https://github.com/elixir-lang/elixir/issues/3527
> Fixing typo in Task.Supervisor.async/4 distributed task docs

- lib/elixir/lib/task.ex
- lib/elixir/test/elixir/task_test.exs
> Introduce Task.yield/2 and Task.shutdown/2

- lib/elixir/lib/kernel.ex
Indent the code samples for `__protocol__/1`, `impl_for/1` and `impl_for!/1`.
> Indent code sample for __protocol__/1 & impl_for/1

- lib/elixir/lib/file.ex
New pull request with changes suggested in previous pull request squashed into a single commit.
> Added documentation and examples for File.stream!

- Makefile
- RELEASE.md
> Rename release_zip to release_precompiled. Fixes #3543

- lib/elixir/src/elixir_tokenizer.erl
- lib/elixir/test/elixir/kernel/fn_test.exs
- lib/elixir/test/erlang/tokenizer_test.erl
partial fix for issue #3486
pin operator  is a different issue and will take some more investgation to find the cause.
> capture non-symbolic operators (&and/2, &not/1, &c.)

- lib/mix/lib/mix/config.ex
- lib/mix/lib/mix/tasks/app.start.ex
- lib/mix/test/mix/tasks/app.start_test.exs
> Warn if app configured but not started when build_embedded

- lib/elixir/lib/kernel.ex
- lib/elixir/lib/macro.ex
> documentaion for module names, variable names and custom sigils

- lib/ex_unit/test/ex_unit/capture_log_test.exs
> Fix race condition in `CaptureLogTest`

- lib/elixir/lib/regex.ex
> Mention sigil_R as valid option to create a regex

- lib/elixir/lib/kernel.ex
fixes a few types, and re-word some things,
regex added
please let me know what you think @jisaacstone
original PR: https://github.com/elixir-lang/elixir/pull/3574
> Improvements in module,  function & variable  names syntax

- lib/elixir/lib/bitwise.ex
At least, I'm 99% sure this is a typo :)
> fix a typo in bitwise documentation

- lib/elixir/lib/application.ex
- lib/elixir/test/elixir/application_test.exs
I've added in the functions mentioned in #3603 plus `:application.get_all_key/1`, but while I'm looking at it are there any others you'd like in here? (as you specified 'at least' those three)
Also I'd be very happy with any feedback on the typespecs/docs and the tests themselves, as I wasn't sure of the best/safest things to test. 
Thanks! :smile:
> (#3603) add more application functions

- lib/iex/lib/iex.ex
I found the wording for dynamic values for your iex prompt to be confusing.  I
believe this reads a bit more clearly.
> Update documentation for IEx.configure

- lib/iex/lib/iex/helpers.ex
- lib/iex/test/iex/helpers_test.exs
Based on the discussion [here](https://groups.google.com/forum/#!topic/elixir-lang-core/btK-iVEBFFo), I have added pid helper to iex since it was straightforward.
Let me know if anything can be improved wrt documentation, implementation or test cases in this pull request.
> iex pid helper, using :c.pid

- lib/elixir/lib/gen_event.ex
- lib/elixir/lib/gen_server.ex
> Add and document GenServer/GenEvent callbacks

- lib/elixir/lib/io.ex
- lib/elixir/lib/kernel.ex
- lib/elixir/lib/process.ex
Also change some wording in process.ex
> Correct double words

- lib/elixir/lib/code.ex
- lib/elixir/lib/kernel.ex
- lib/elixir/lib/string.ex
- lib/elixir/test/elixir/kernel/quote_test.exs
- lib/ex_unit/lib/ex_unit/formatter.ex
- lib/mix/lib/mix/hex.ex
- lib/mix/lib/mix/project.ex
- lib/mix/lib/mix/tasks/app.start.ex
- lib/mix/lib/mix/tasks/compile.ex
- lib/mix/lib/mix/tasks/profile.fprof.ex
please read the commit message for a description
> Corrections

- lib/elixir/lib/kernel/special_forms.ex
when https://github.com/elixir-lang/elixir-lang.github.com/pull/595#issuecomment-139146400 is resolved, we may want to use the improved example in the docs.
> Mention the Pin Operator in its documentation

- lib/mix/lib/mix.ex
Put it in a better way.
Closes: https://github.com/elixir-lang/elixir/issues/3696
> Rephrase @doc for Mix.raise/2

- lib/ex_unit/lib/ex_unit/assertions.ex
- lib/ex_unit/test/ex_unit/assertions_test.exs
> Display pinned vars in the receive assertions

- lib/elixir/lib/gen_event.ex
- lib/elixir/lib/gen_event/stream.ex
- lib/elixir/lib/gen_server.ex
> Make it clearer that unimplemented callbacks always stop

- lib/ex_unit/lib/ex_unit/assertions.ex
- lib/ex_unit/test/ex_unit/assertions_test.exs
This should close #3703. Also, I added tests for `assert_raise/3` because there were none :).
> Better assert raise messages

- lib/mix/lib/mix/hex.ex
- lib/mix/lib/mix/tasks/local.hex.ex
I forgot to include Hex in the list of apps to be formatted
> Title case Hex

- lib/elixir/lib/string.ex
#3742 got me looking at what `\g{N}` is, and I found some slightly confusing documentation around `String.replace/4`.
> little more explanation of `String.replace/4`'s `:insert_replace` option

- lib/elixir/lib/bitwise.ex
- lib/elixir/lib/enum.ex
- lib/elixir/lib/exception.ex
- lib/elixir/lib/kernel.ex
- lib/elixir/lib/kernel/special_forms.ex
- lib/elixir/lib/keyword.ex
- lib/elixir/lib/list.ex
- lib/elixir/lib/map.ex
- lib/elixir/lib/module.ex
- lib/elixir/lib/range.ex
- lib/elixir/lib/record.ex
- lib/elixir/lib/regex.ex
- lib/mix/lib/mix/scm.ex
> Improve Summaries

- lib/eex/lib/eex.ex
- lib/elixir/lib/io.ex
- lib/mix/lib/mix/scm.ex
- lib/mix/lib/mix/shell.ex
- lib/mix/lib/mix/tasks/archive.uninstall.ex
....even thought i have already submitted a fix for ex_doc https://github.com/elixir-lang/ex_doc/pull/439
> Remove trailing semicolong from summaries

- Makefile
- README.md
fixes README and also the MakeFile
> License: Use NOTICE (remove LEGAL)

- Makefile
Closes https://github.com/elixir-lang/elixir/issues/3775
> Add text Files to Docs.zip

- lib/ex_unit/lib/ex_unit/assertions.ex
- lib/ex_unit/test/ex_unit/assertions_test.exs
> Fix assertion errors with more than 1 pinned var

- lib/elixir/test/elixir/macro_test.exs
test added as per @lexmag's [suggestion](https://github.com/elixir-lang/elixir/pull/3780/files#r40504458)
> Macro.to_string/2 : add test

- lib/elixir/lib/port.ex
This is a fix for the open issue #3688 .
I tried to follow all the suggestions discussed in the thread (especially rephrasing the sentences from the Erlang doc).
> Remove external links in summary and update docs for Port.

- lib/elixir/lib/enum.ex
this is the last example left, to comply with https://github.com/elixir-lang/elixir/pull/3786
> Remove surrounding spaces in range example

- lib/elixir/lib/gen_event.ex
I think these comments would help people understand what it going on in the example better.
> Add comments to the first GenEvent example.

- lib/elixir/lib/file.ex
> Fix small typo in docs for File.rename/2

- lib/elixir/lib/gen_server.ex
> Add more info about :via registry to GenServer

- lib/mix/lib/mix/tasks/test.ex
Display warning for files matching :warn_test_pattern that are not
matching :test_pattern. Default config,"*_test.ex".
> New config, :warn_test_pattern

- lib/elixir/lib/module.ex
Use more descriptive name for variable and explicitly show when warning isn't generated.
> Tidy up implementation for warning on @attribute redefinition

- lib/elixir/lib/task.ex
- lib/elixir/test/elixir/task_test.exs
I paired with @katiespiders on this fix for #3894.  A couple things to note:
* @josevalim asked for TODO comments about the fact that the `nil` check should be removed in elixir 1.3.  We did that originally but then I thought it would be better to encode the TODO as part of the tests so that they notify when the Elixir version is bumped to `1.3.x`.  It would probably be better to have `only_until_version` warn instead of fail when the test passes on 1.3 (as you'll want to be able to bump the version to 1.3 without breaking the build) but I wasn't sure of a good way to do that -- `Logger.warn` didn't print anything (I assume you are capturing logs or something).  Let me know if you'd like to see that work differently or if you'd prefer we roll back to the TODOs.  I added the …
> Provide helpful error from `Task` functions when called from wrong process

- lib/iex/lib/iex/helpers.ex
> Do not start apps on "recompile" in an IEx session with --no-start

- lib/elixir/lib/gen_event.ex
- lib/elixir/lib/gen_server.ex
- lib/elixir/test/elixir/gen_event_test.exs
- lib/elixir/test/elixir/gen_server_test.exs
added stop/3 to GenServer and GenEvent using :gen.stop
> Support new gen:stop in GenEvent and GenServer

- lib/eex/lib/eex/engine.ex
- lib/eex/test/eex/smart_engine_test.exs
resolve #3327 
The code is almost the same with that in phoenix_html except I changed `fetch_assign` to `fetch_assign!`
> eex engine raises on missing assigns

- lib/elixir/lib/map.ex
- lib/elixir/lib/map_set.ex
- lib/elixir/test/doc_test.exs
- lib/elixir/test/elixir/map_set_test.exs
- lib/elixir/test/elixir/map_test.exs
See discussion at https://github.com/elixir-lang/elixir/issues/3855
> Add `new/1` and `new/2` to Map and MapSet (mirroring the Keyword variant)

- lib/elixir/lib/integer.ex
- lib/elixir/test/elixir/integer_test.exs
- Add examples to Integer.is_odd/1 and Integer.is_even/1
￼- rename tests
> Integer docs

- lib/elixir/lib/kernel/special_forms.ex
- lib/elixir/src/elixir_exp.erl
- lib/elixir/src/elixir_import.erl
- lib/elixir/src/elixir_translator.erl
- lib/elixir/src/elixir_with.erl
- lib/elixir/test/elixir/kernel/expansion_test.exs
- lib/elixir/test/elixir/kernel/with_test.exs
> Introduce with

- lib/iex/lib/iex/helpers.ex
- lib/iex/lib/iex/info.ex
I started working on a prototype for the `i/1` IEx helper discussed in the [mailing list](https://groups.google.com/forum/#!topic/elixir-lang-core/sBlrH4r_Gmk), on IRC and drafted in [whatyouhide/iex_info](https://github.com/whatyouhide/iex_info).
@josevalim this is clearly just a proof of concept, I opened a PR this early so that we can take a look at the direction this is taking. Wdyt?
> First incomplete version of the i/1 IEx helper

- lib/iex/lib/iex/info.ex
- lib/iex/test/iex/helpers_test.exs
- lib/iex/test/iex/info_test.exs
I added tests for all the implementations of `IEx.Info` and for the `i/1` IEx helper.
> IEx.Info tests

- lib/elixir/lib/float.ex
- lib/elixir/lib/inspect.ex
- lib/elixir/lib/integer.ex
- lib/elixir/lib/io/ansi/docs.ex
- lib/elixir/lib/kernel/special_forms.ex
- lib/elixir/lib/kernel/typespec.ex
- lib/elixir/lib/macro.ex
- lib/elixir/lib/module.ex
- lib/elixir/lib/option_parser.ex
- lib/elixir/lib/path.ex
- lib/elixir/lib/regex.ex
- lib/elixir/lib/string.ex
- lib/elixir/lib/string_io.ex
- lib/elixir/lib/version.ex
- lib/elixir/test/elixir/kernel/binary_test.exs
- lib/elixir/test/elixir/kernel/comprehension_test.exs
- lib/elixir/test/elixir/kernel/expansion_test.exs
- lib/elixir/test/elixir/macro_test.exs
- lib/elixir/test/elixir/string_io_test.exs
- lib/elixir/unicode/unicode.ex
- lib/ex_unit/lib/ex_unit/doc_test.ex
- lib/iex/lib/iex/helpers.ex
- lib/mix/lib/mix/task.ex
> Make Macro.to_string/1 consistent with Kernel.inspect/1 for bitstrings

- CHANGELOG.md
just a few things noticed when reading the changelog
hope it helps
> quick changelog 1.2 edits

- bin/elixir.bat
- bin/elixirc.bat
- bin/iex.bat
- bin/mix.bat
Adding a new test at the top of the Windows batch files to enable an end-user to easily see the output of the various Elixir batch files. This will make figuring out issues with the Win batch files a bit easier.
> Adding Code For Diagnostics To Windows Batch Files

- lib/elixir/lib/system.ex
- lib/elixir/src/elixir_rewrite.erl
- lib/elixir/test/elixir/system_test.exs
This PR adds the `System.time_offset/0-1` functions discuessed in #4018 by @lexmag and @fishcakez.
> Add System.time_offset/0-1

- lib/elixir/lib/option_parser.ex
That is, english grammar, not elixir grammar :)
> fix grammar:  does -> do.

- lib/elixir/src/elixir_import.erl
- lib/elixir/test/elixir/kernel/errors_test.exs
> Properly handle import with invalid options

- lib/elixir/lib/kernel/special_forms.ex
fixes a small spelling mistake
> update Kernel.SpecialForms.import summary

- lib/elixir/pages/Writing Documentation.md
This PR basically does what it says in the title.
Keep up the good work! :+1:
> Fix small typo in Writing Documentation.md

- lib/mix/lib/mix.ex
- lib/mix/lib/mix/cli.ex
- lib/mix/lib/mix/task.ex
- lib/mix/test/mix/cli_test.exs
- lib/mix/test/mix/task_test.exs
- lib/mix/test/mix_test.exs
- man/mix.1
I implemented mix debug option as described in #4106.
> Add mix debug mode. Close #4106.

- lib/elixir/lib/task.ex
> task.ex docfix

- lib/iex/lib/iex/info.ex
> Support remote pids/ports with IEx helper i/1

- lib/iex/lib/iex/config.ex
- lib/iex/test/iex/config_test.exs
From a discussion on IRC with @fishcakez, I discovered that IEx.Config had a bug that was causing an error.
> Fixes bug in IEx.Config.configuration

- lib/elixir/lib/protocol.ex
- lib/elixir/test/elixir/protocol_test.exs
> Warn when defimp is called for consolidated protocol

- lib/elixir/lib/regex.ex
- lib/elixir/test/elixir/regex_test.exs
Closes issue #4203. Not the prettiest implementation, but it does work. Any suggestion on how to make it better, please?
> Implemented option :include_captures in Regex.split/3

- lib/elixir/lib/gen_event.ex
Thanks to Bibek Pandey for bringing this up: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/elixir-lang-talk/_tT_B13stKI/TUY755IGEgAJ
> Fix documentation for GenEvent Streaming

- lib/elixir/lib/base.ex
Sorry, I forgot to add the docs in  #4237.
> Add doc about ignore: :whitespace to Base.decode64.

- lib/elixir/lib/range.ex
Added examples of applying Enum functions to Range to clarify that Range includes some functions from Enum such as count/1, member/2, and reduce/3.
> Added @moduledoc documentation to Range

- lib/elixir/lib/string.ex
- lib/elixir/test/elixir/string_test.exs
See associated [issue 4246](https://github.com/elixir-lang/elixir/issues/4246)
Please check thoroughly that this is OK before merging. Thanks.
> String.replace_trailing bug fix.

- lib/elixir/lib/exception.ex
- lib/elixir/lib/kernel/special_forms.ex
- lib/elixir/src/elixir_try.erl
- lib/elixir/src/elixir_with.erl
- lib/elixir/test/elixir/kernel/expansion_test.exs
- lib/elixir/test/elixir/kernel/with_test.exs
> Optional else clauses can be added to special form with

- lib/elixir/lib/enum.ex
Fix example and use iex> so it can be tested by doctest
> Fix Enum.uniq_by example

- lib/elixir/lib/kernel/special_forms.ex
...based on the Getting Started Guide
> Improve docs for `case` and `cond`

- lib/elixir/lib/io/ansi.ex
- lib/elixir/lib/protocol.ex
- lib/mix/lib/mix/task.ex
...making it consistent with the rest of the typespecs
> Removes the use of () in built in typespecs

- bin/iex
See discussion on mailing list https://groups.google.com/forum/#!topic/elixir-lang-talk/AKVD3ekLyfo
(I couldn't help myself. Felt weird not to just go ahead and send the pull request on. We can close if unneeded.)
> Improve documentation for iex -S

- lib/elixir/lib/kernel.ex
- lib/elixir/lib/range.ex
- lib/elixir/test/elixir/enum_test.exs
- lib/elixir/test/elixir/kernel/typespec_test.exs
- lib/elixir/test/elixir/macro_test.exs
- lib/elixir/test/elixir/stream_test.exs
...by removing spaces around it
> Standardize use of range operator (..)

- lib/mix/lib/mix/scm/git.ex
- lib/mix/test/fixtures/deps_status/deps/tagged/mix.exs
- lib/mix/test/mix/tasks/deps_test.exs
This is an attempt to fix #4309. I'm a little new to the `Mix.Dep*` part of the codebase, so I'm not sure this is a good solution; also, this is of course a work-in-progress as it completely lacks tests, but I wanted to see if the direction is right before moving on. Let me know what I can do :)
> [WIP] Correctly checkout rev when updating mix.exs

- lib/iex/lib/iex/autocomplete.ex
- lib/iex/test/iex/autocomplete_test.exs
When I am trying things out in IEx, I use the `r` helper
very often, but when defining new functions, the completions are
not available, so I thought it would be better if they would.
```elixir
defmodule MyMod do
def foo, do: "foo"
end
MyMod. # tab shows foo
r(MyMod)
MyMod. # tab still shows only foo
```
With this PR, the functions newly defined are shown when the module is reloaded.
However, I am not really sure this is the best approach, as
the functions removed when reloading will still be shown.
As it is already the case, it is not a regression, but it would
be better if there were a way to have really up to date completions.
So I have a few questions
1. Does what I am trying to do in this PR seems ok?
2. Is there a better way to update the completions to handle reloaded modules?
3. …
> Update iex autocomplete to show new functions in reloaded modules.

- lib/elixir/test/elixir/file_test.exs
It is only once every four years, but still :smile:
> Do not expect every year to be bissextile.

- lib/elixir/lib/process.ex
I add test cases to support the docs - I'm not sure if the Elixir team wants or cares about the tests, but they are there to prove the point
> Clarify docs for Process.register/2 and Process.unregister/1

- lib/elixir/lib/float.ex
- lib/elixir/lib/integer.ex
- lib/elixir/lib/uri.ex
based on discussion: https://github.com/elixir-lang/elixir/pull/4371#discussion-diff-55514919
> replace "of the form" with "in the form of"

- lib/elixir/lib/kernel/special_forms.ex
- lib/elixir/lib/macro.ex
previous discussion: https://github.com/elixir-lang/elixir/pull/4372#issuecomment-193999174
> Replace `quote do:` one-liners with quote do...end

- lib/elixir/pages/Typespecs.md
- lib/ex_unit/lib/ex_unit/case.ex
As suggested in changes recently introduced in https://github.com/elixir-lang/elixir/pull/4362
> Use "key-value pairs" instead of "key-values"

- lib/elixir/lib/module.ex
> need colon to make gen_event atom

- lib/ex_unit/lib/ex_unit/assertions.ex
I'm submitting this PR because the docs/arguments for the ExUnit received assertions really confused me.
The docs for refute_receive/3 said:
>   Asserts `message` was not received (and won't be received) within the the `timeout` period.
Yes the method signature said:
```elixir
refute_receive(not_expected, timeout \\ Application.fetch_env!(:ex_unit, :refute_receive_timeout), message \\ nil)
```
I had to look through the source and examples to determine that message was actually the failure message and not the message we weren't expecting.
> Make arguments and docs more clear for assert_receive, assert_recevied, refute_receive, and refute_received

- lib/elixir/pages/Writing Documentation.md
Minor addition to the writing-documentation.md file to explain best practice for documenting functions with multiple clauses.
I often found myself in a dilemma on how to document multiple clauses. See [gist](https://gist.github.com/stephenmoloney/16efb1e7168fdbeb74f9) as an example.
Add to elixir docs best practice guideline.
Please check that this change to the docs actually reflects best practice before merging and that this change is not misleading! 
Thanks ! :+1:
> documenting functions with multiple clauses.

- lib/elixir/test/elixir/version_test.exs
> Add coverage to private function Version.to_matchable/2

- lib/elixir/lib/macro.ex
Note I removed the line that said
> Raises if the pipeline is ill-formed.
since as far as I can tell this function never raises (its actual spec is `unpipe(term) :: [{term, non_neg_integer}]` I think). Let me know how this looks!
> Add more docs to Macro.unpipe/1

- lib/ex_unit/lib/ex_unit/callbacks.ex
Considering this case:
```elixir
defmodule CallbacksCase do
setup do
{:ok, :something}
end
test "nothing", do: assert true
end
```
Before this commit exunit callbacks return value merger was failing with
`(RuntimeError) expected ExUnit callback in CallbacksCase to return :ok or
{:ok, keyword | map}, got :something instead`.
But callback didn't return `:something`, it returned `{:ok, something}`.
After this commit same case will fail with
`(RuntimeError) expected ExUnit callback in CallbacksCase to return :ok or
{:ok, keywords | map}, got {:ok, :something} instead`.
This behaviour is achieved by moving all the checks to `__merge__/3` function.
`context_merge/3` now only works with maps and raises 'reserved keys' errors.
> Improve merge exception texts inside exunit callbacks

- lib/elixir/lib/exception.ex
- lib/elixir/test/elixir/access_test.exs
- lib/elixir/test/elixir/exception_test.exs
- lib/elixir/test/elixir/kernel/errors_test.exs
- lib/elixir/test/elixir/kernel/raise_test.exs
- lib/ex_unit/test/ex_unit/assertions_test.exs
- lib/ex_unit/test/ex_unit/doc_test_test.exs
- lib/iex/test/iex/helpers_test.exs
- lib/logger/test/logger/translator_test.exs
Closes https://github.com/elixir-lang/elixir/issues/4405
> Hint function may be private if not available

- lib/elixir/lib/system.ex
@josevalim as discussed earlier today. I also changed the name of `System.convert_time_unit/1` to `System.normalize_time_unit/1` so that it's more in line with the docs and doesn't create confusion with `convert_time_unit/3`. Let me know what you think :)
btw I also fixed handling of positive integers in `normalize_time_unit/3` as pointed out by @fishcakez :)
> Polish here and there in the System module

- lib/ex_unit/lib/ex_unit/formatter.ex
- lib/ex_unit/test/ex_unit/formatter_test.exs
> Enhance difference highlighting for numbers

- lib/elixir/lib/enum.ex
Improvement to https://github.com/elixir-lang/elixir/pull/4484
As suggested by @princemaple
in https://github.com/elixir-lang/elixir/pull/4414#issuecomment-206592281
> Enum.sum/2: Simplified formula for ranges

- lib/elixir/lib/exception.ex
- lib/elixir/lib/gen_server.ex
- lib/elixir/test/elixir/exception_test.exs
- lib/elixir/test/elixir/gen_server_test.exs
Refers to solve #4479
Any better ideas on error message contents?
> Raise nice error message if you try to GenServer.call/3 from yourself

- lib/elixir/test/elixir/gen_server_test.exs
Hey, fellows!
I am trying to add more tests.
But for now I get stuck with killing GenServer to test call/3 for killed process.
When I am calling ```GenServer.stop(:stack, :kill)``` it raises misleading message:
```
15:41:27.897 [error] GenServer :stack terminating
** (stop) :kill
Last message: []
State: [:hello]
```
End even ```assert catch_exit``` or ```assert catch_error``` can't stop it.
Any ideas to tackle this one?
> Added more tests in GenServer.call/3

- lib/mix/lib/mix/local/installer.ex
- lib/mix/lib/mix/tasks/archive.install.ex
- lib/mix/lib/mix/tasks/escript.install.ex
Refers to #4330
But i don't figure how to test this behavioural
> Check the file is an actual escript before writing to disk #4330

- lib/elixir/lib/enum.ex
This may help others when they're looking for a way to dedup the entire list.
> Add a note about `uniq/1` to `dedup/1`

- lib/elixir/pages/Naming Conventions.md
> Use consistent spacing in code snippet.

- lib/elixir/lib/string.ex
- lib/elixir/test/elixir/string_test.exs
- lib/elixir/unicode/unicode.ex
> Introduce String.pad_{leading,trailing}/3 and String.trim{,_leading,_trailing}/2

- lib/ex_unit/examples/difference.exs
- lib/ex_unit/lib/ex_unit/diff.ex
- lib/ex_unit/test/ex_unit/diff_test.exs
> Consider improper lists in ExUnit.Diff.format/3

- lib/elixir/lib/kernel.ex
- lib/elixir/test/elixir/kernel_test.exs
This should fix #4466, attacking it from two fronts :) Me and @lexmag worked on this together, that's where the authorship of the commits comes from.
> Fix unquoted range

- lib/mix/lib/mix/tasks/deps.clean.ex
- lib/mix/test/mix/tasks/deps_test.exs
> mix deps.clean should not remove source of local deps

- lib/elixir/lib/map.ex
reposted, as I accidentally closed https://github.com/elixir-lang/elixir/pull/4583
> Map: correct arg name and add backticks

- lib/ex_unit/lib/ex_unit/diff.ex
- lib/ex_unit/lib/ex_unit/formatter.ex
- lib/ex_unit/test/ex_unit/diff_test.exs
> Limit execution time for difference formatting and pre-filter non-similar strings

- lib/elixir/src/elixir_with.erl
- lib/elixir/test/elixir/kernel/warning_test.exs
- lib/elixir/test/elixir/kernel/with_test.exs
> Do not emit warning when "with" clause always matches

- lib/elixir/lib/inspect.ex
- lib/elixir/lib/integer.ex
- lib/elixir/test/elixir/integer_test.exs
Docs, guards and function optimizations
> Integer improvements

- lib/elixir/lib/kernel/special_forms.ex
See https://groups.google.com/forum/#!topic/elixir-lang-core/NWvFwUWo2QQ for background conversation.
> Add section about `after` to special forms docs.

- lib/elixir/lib/inspect.ex
- lib/elixir/lib/list/chars.ex
- lib/elixir/lib/string/chars.ex
- lib/elixir/test/elixir/protocol_test.exs
> Replace "thing" arg with more appropriate "term" arg

- lib/logger/lib/logger/utils.ex
This PR partially solves https://github.com/elixir-lang/elixir/pull/4582#discussion_r62423420
@josevalim: I haven't implemented your suggestion for checking valid values for the options.
I think we should come up with a mechanism something that can help us check all values, otherwise it's gonna be a lot of code duplication.
regarding keys, a simple struct!/1 will do it (i think), let me know if this works for you.
> [WIP] Correct inspect options

- lib/eex/lib/eex/engine.ex
- lib/elixir/lib/enum.ex
- lib/elixir/lib/io.ex
- lib/elixir/lib/keyword.ex
- lib/elixir/lib/map.ex
- lib/elixir/lib/regex.ex
- lib/elixir/lib/string.ex
- lib/elixir/lib/task.ex
- lib/elixir/lib/uri.ex
- lib/elixir/test/elixir/io_test.exs
How does this look for #4608 ?
> IO.warn to unify warnings

- lib/elixir/lib/application.ex
Adds what described in #4546.
Since we already define `GenServer` as a behaviour (with a bunch of `@callbacks`) and document such callbacks, changing the behaviour when `use GenServer` is called from `:gen_server` to `GenServer` should be just a matter of actually changing that line :).
`Supervisor` (which is mentioned in the issue) needs no work for now as far as I understand, as we already defines the behaviour and uses `@behaviour Supervisor` when `use Supervisor` is called.
As for `Application`, I added two `@callback` definitions to it and documented them; also, I changed `use Application` so that it calls `@behaviour Application` instead of `@behaviour :application`. Erlang's `application` module only defines `start/2` and `stop/1` as callbacks …
> Make Application a behaviour (instead of using :application)

- lib/elixir/lib/kernel/special_forms.ex
As discussed here: https://github.com/elixir-lang/elixir/commit/5e531cbc35b70548b27075be62145592060cd19e#commitcomment-17477889
> Style fix for try ... after docs

- lib/elixir/lib/kernel/parallel_compiler.ex
I was working around `Kernel.ParallelCompiler.spawn_compilers/8` lately (yeah, **eight**! 😛), and thought it could benefit from a little refactoring. Basically, we pass around a "state" in this function which is formed by its eight arguments: in this PR, I changed the state to be a map. I think this brings some improvements: first of all, all arguments are always named, which is great when reading the code. Second, when calling `spawn_compilers` recursively, now just the `state` with some updated fields has to be passed around (instead of always the full eight arguments, even if only one changed).
I'm not 100% sold on this PR myself, maybe the benefits are not that much as to justify it, but I thought it would be worth to have others look at it and tell what they think :)
Small note: …
> Use a map to pass around in Kernel.ParallelCompiler.spawn_compilers

- lib/mix/lib/mix/compilers/elixir.ex
As discussed in #4639:
Changes mix elixir compiler/manifest so that files and modules are separate entities. Also updates sources to use their own record to make the manifest look prettier, but still internally uses a map.
As per IRC conversation, does not implement backwards compatibility for `:v3` because it was never released.
/cc @josevalim
> mix elixir compiler manifest: separate file and module

- lib/mix/lib/mix/local.ex
It's a very minor thing, but... 🐶
> Improve spelling of private function name

- lib/mix/lib/mix/tasks/compile.xref.ex
- lib/mix/lib/mix/tasks/xref.ex
- lib/mix/test/mix/tasks/xref_test.exs
> Change grouped warning format, split test, and rename needs_xref

- lib/mix/lib/mix/compilers/elixir.ex
Amount of time is basically the same, but for ecto master manifest:
1.2.5 (without dispatches!!):
`-rw-r--r--  1 ericentin  staff  71148 May 22 14:42 _build/shared/lib/ecto/.compile.elixir`
this branch (with dispatches):
`-rw-r--r--  1 ericentin  staff  28502 May 22 14:43 _build/shared/lib/ecto/.compile.elixir`
/cc @josevalim @ericmj
> use `:erlang.term_to_binary` for elixir compiler manifest storage

- lib/elixir/lib/path.ex
- lib/elixir/test/elixir/path_test.exs
Prior this commit(s) three tests failed under windows.
> Fix path tests windows

- lib/mix/lib/mix/tasks/xref.ex
- lib/mix/test/mix/tasks/xref_test.exs
> Adds mix_project_config[:xref][:exclude] for Xref

- lib/iex/test/iex/interaction_test.exs
Tries to fix this race condition: https://travis-ci.org/elixir-lang/elixir/builds/132115026
> Fix test race in IEx

- lib/elixir/lib/calendar.ex
Implements #4671
I chose to use `{:error, :unsupported_calendar}` for the error tuple in cases where `Calendar.ISO` is not the calendar for the given `Date` or `NaiveDateTime`, I can change that if there is a more descriptive atom to use.
Been awhile since my last PR, so let me have it if I've forgotten something :)
> Add to_erl/from_erl conversions to Time/Date/NaiveDateTime

- lib/logger/lib/logger/formatter.ex
> Remove incorrect reference to arrays

- lib/elixir/lib/integer.ex
- lib/elixir/test/elixir/integer_test.exs
This is a leftover from a rebase when https://github.com/elixir-lang/elixir/pull/4582
was implemented.
> Replace last remains of char_list with charlist

- lib/elixir/test/elixir/enum_test.exs
- lib/elixir/test/elixir/stream_test.exs
Also, now testing the correct function in the negative test for drop_every/2. 
(Sorry about the small PR, it was because of the typo in #4698)
> Add some extra tests for take_every and drop_every.

- lib/elixir/lib/kernel.ex
- lib/elixir/lib/kernel/typespec.ex
- lib/elixir/lib/module.ex
- lib/elixir/src/elixir_module.erl
- lib/elixir/test/elixir/kernel/typespec_test.exs
Not sure if this is a good implementation, so I'm opening this for early feedback :) Also, I'm open to suggestions on possible additional tests to add for this.
Related to #3980.
> Add support for the @optional_callbacks behaviour attribute

- lib/elixir/lib/string.ex
- lib/ex_unit/examples/difference.exs
- lib/ex_unit/lib/ex_unit/assertions.ex
- lib/ex_unit/lib/ex_unit/diff.ex
- lib/ex_unit/lib/ex_unit/formatter.ex
- lib/ex_unit/test/ex_unit/diff_test.exs
> Separated ExUnit difference highlighting

- lib/elixir/lib/uri.ex
Mainly:
* renamed a bunch to make them clearer (especially one-letter variables)
* renamed a couple of private functions so that their name is more expressive
* added guards to some functions
I also slightly refactored a couple of things and moved a private function around to be closed to where it's used. I left a couple of comments in the code for a few things I'm not super sure about :)
\cc @lexmag, I'd appreciate your input on this :)
> Refactor things here and there in the URI module

- lib/elixir/lib/uri.ex
\cc @lexmag and @josevalim, since I'm in favour of the indentation we discussed, here's a fix for a bunch of cases in `URI` :)
> Fixes indentation around in the URI module

- CHANGELOG.md
Perhaps that could be made clear?
> This example confused me before I understood it was using another library

- lib/elixir/lib/access.ex
It was described, but not implemented, on #4009
`Access.at/1` can be used to access any index in a list.
```
iex> list = [%{name: "john"}, %{name: "mary"}]
iex> get_in(list, [Access.at(1), :name])
"mary"
iex> get_and_update_in(list, [Access.at(0), :name], fn
...>   prev -> {prev, String.upcase(prev)}
...> end)
{"john", [%{name: "JOHN"}, %{name: "mary"}]}
iex> pop_in(list, [Access.at(0), :name])
{"john", [%{}, %{name: "mary"}]}
```
> Implement Access.at/1

- CHANGELOG.md
ref: https://twitter.com/erniemiller/status/737285233272328192
special thanks to @JEG2 and @ernie
> Switch date sigil in Changelog to correct YYYY-MM-DD

- lib/elixir/lib/enum.ex
- lib/elixir/test/elixir/enum_test.exs
Note: This is a housekeeping request, not intended to introduce any functional changes.
I had an idea, which we can shoot down or I can fully commit to if you like it: Basically I think that it would be nice if functions are specified with signature, and sorted in order within the test file. Would make it easier to find tests and have a cleaner code base.
I know some functions are already following this pattern, so this kind of a manual housekeeping task.
Summary of changes:
* Reorder test in alphabetical order.
* Specify signature for function being tested.
* Add missing tests where applicable.
* Reorder the function definitions in the main Enum file as well.
> Update Enum tests

- lib/logger/lib/logger.ex
- lib/logger/lib/logger/backends/console.ex
This takes the async logging to :user further by:
* Buffering formatted events while we wait for a reply from the device
* Dropping events when buffer is full
* Handling a unicode error only when we need to, fortunately :user sends the old buffer back so don't need to hold onto it
/cc @josevalim @olafura
> Batch IO with console backend and handle unicode errors

- lib/ex_unit/lib/ex_unit/assertions.ex
- lib/mix/lib/mix/dep/converger.ex
- lib/mix/lib/mix/project.ex
- lib/mix/lib/mix/scm/git.ex
- lib/mix/test/mix/scm/git_test.exs
- lib/mix/test/mix/umbrella_test.exs
* Mix error messages to start with uppercase;
* all other raise message should start with lowercase.
> Correct casing in error messages

- CODE_OF_CONDUCT.md
- lib/elixir/lib/kernel.ex
- lib/mix/lib/mix/local.ex
- lib/mix/lib/mix/shell/quiet.ex
* Remove use of em-dash(—) in favour of parenthesis
* Remove double words (on on)
* Add missing arity in function mention
* Fix wrongly closed backtick
> Small fixes

- lib/elixir/lib/access.ex
- lib/elixir/lib/kernel/special_forms.ex
- lib/mix/lib/mix/rebar.ex
- lib/mix/lib/mix/tasks/app.tree.ex
- lib/mix/lib/mix/tasks/deps.tree.ex
Typical use cases are `true`, `false`, `nil`
> Add backticks where needed

- lib/mix/lib/mix/hex.ex
- lib/mix/lib/mix/tasks/deps.compile.ex
As mentioned in this mailing list thread:
https://groups.google.com/d/msg/elixir-lang-core/JptOMxrLxcs/95mR6YYJDAAJ
...I could not figure out what the command to force install rebar was.
Including the information in the prompt will help users figure this out
without having to ask like I did.
> Provide information about how to force install hex and rebar.

- lib/elixir/test/elixir/system_test.exs
As mentioned in https://github.com/elixir-lang/elixir/issues/4753 Windows echo is not a separate executable
it is a builtin to the shell (cmd.exe).
Create separate System.cmd/3 tests for windows which use the cmd.exe the echo a message.
Also change after block of test "cmd/2 with absolute and relative paths win" - sometimes File.rm_rf!
failed with 'permission denied'.
> Fix failing tests for System.cmd/3 on windows

- lib/elixir/lib/kernel/parallel_compiler.ex
> Use heuristic for compiler errors

- lib/mix/lib/mix/dep/elixir_scm.ex
- lib/mix/lib/mix/tasks/compile.protocols.ex
- lib/mix/test/mix/tasks/compile.elixir_test.exs
- lib/mix/test/mix/tasks/deps_test.exs
> use ETF for elixir_scm and protocols manifests

- lib/elixir/lib/string.ex
- lib/ex_unit/examples/difference.exs
- lib/ex_unit/lib/ex_unit/diff.ex
- lib/ex_unit/test/ex_unit/diff_test.exs
Closes #4682.
__Before:__
__After:__
> Enhance difference highlighting for keywords

- lib/elixir/lib/kernel/lexical_tracker.ex
After chatting with alisdair on IRC I realized this comment was out of date, so I updated it. :)
> Improve Kernel.LexicalTracker module docs

- lib/elixir/src/elixir_scope.erl
- lib/elixir/src/elixir_with.erl
- lib/elixir/test/elixir/kernel/with_test.exs
> Make sure with/1 does not leak variables to else

- lib/elixir/src/elixir_map.erl
- lib/elixir/test/elixir/kernel/lexical_tracker_test.exs
> Make sure struct expansion results in a remote dispatch

- lib/mix/lib/mix/tasks/compile.xref.ex
- lib/mix/lib/mix/tasks/xref.ex
- lib/mix/test/mix/tasks/xref_test.exs
> mix xref command-style

- lib/mix/lib/mix/tasks/xref.ex
Just a couple of typos and grammatical improvements.
/cc @josevalim
> more mix xref doc improvements

- lib/elixir/lib/map.ex
> Document the "map" data type in the Map module

- lib/elixir/lib/tuple.ex
> Add docs for the "tuple" data type to the Tuple module

- lib/ex_unit/lib/ex_unit/on_exit_handler.ex
- lib/ex_unit/lib/ex_unit/runner.ex
> Ensure we get test process reply when it's finished in time

- lib/elixir/test/elixir/kernel/lexical_tracker_test.exs
Ensures that we're testing typespec/lexical tracker interaction more throughly.
/cc @josevalim
> Improve lexical tracker test

- lib/mix/lib/mix/tasks/escript.build.ex
I was a little confused on what the escript module was actually supposed to look like, so I added a small example module based on the Mixfile module above
> Add example escript module to doc

- lib/iex/lib/iex/helpers.ex
- lib/iex/test/iex/helpers_test.exs
As discussed in #4836 I updated the `c/1` helper to compile in memory.
> Make iex c helper compile in memory by default, closes #4836

- lib/iex/lib/iex/helpers.ex
- lib/iex/test/iex/helpers_test.exs
As discussed with @josevalim on IRC earlier this evening.
I'm not sure about mentioning it in the "There are many other helpers available:" section, since it's probably not useful as an interactive command.
> `import_if_available/2` for use with .iex.exs

- lib/elixir/lib/kernel/parallel_compiler.ex
- lib/elixir/lib/kernel/typespec.ex
- lib/elixir/test/elixir/protocol_test.exs
- lib/ex_unit/lib/ex_unit/doc_test.ex
- lib/iex/lib/iex/helpers.ex
- lib/mix/lib/mix/compilers/elixir.ex
- lib/mix/test/mix/tasks/compile.elixir_test.exs
Along then same line of https://github.com/elixir-lang/elixir/pull/4754
> Spell properly BEAM

- lib/elixir/lib/agent.ex
- lib/elixir/lib/application.ex
- lib/elixir/lib/file.ex
- lib/elixir/lib/gen_event.ex
- lib/elixir/lib/gen_server.ex
- lib/elixir/lib/io.ex
- lib/elixir/lib/kernel.ex
- lib/elixir/lib/kernel/lexical_tracker.ex
- lib/elixir/lib/module/locals_tracker.ex
- lib/elixir/lib/node.ex
- lib/elixir/lib/process.ex
- lib/elixir/lib/supervisor.ex
- lib/elixir/lib/task/supervisor.ex
- lib/elixir/src/elixir_env.erl
- lib/elixir/src/elixir_quote.erl
- lib/elixir/test/elixir/inspect_test.exs
- lib/elixir/test/elixir/string/chars_test.exs
- lib/elixir/test/elixir/task_test.exs
- lib/ex_unit/lib/ex_unit/doc_test.ex
- lib/iex/lib/iex/server.ex
- lib/iex/test/iex/info_test.exs
- lib/mix/lib/mix/tasks/profile.fprof.ex
> Properly spell PID

- lib/mix/lib/mix/tasks/new.ex
Following this conversation -> https://github.com/elixir-lang/elixir/pull/4906/files/9c42bed6cc2a30643fe6ac44dd805babf4f84e1e#r69283526
> Hexdocs -> HexDocs

- lib/mix/lib/mix/tasks/test.ex
- lib/mix/test/mix/tasks/test_test.exs
- lib/mix/test/test_helper.exs
> mix test --listen-on-stdin

- lib/elixir/lib/option_parser.ex
I also
* fixed some style in just a couple of lines of code
* renamed a couple of variables for clarity
> Polish and fix docs for OptionParser

- lib/mix/lib/mix/tasks/test.ex
- lib/mix/test/mix/tasks/test_test.exs
> mix test --listen-on-stdin will no longer exit on failure

- lib/elixir/lib/exception.ex
- lib/elixir/test/elixir/exception_test.exs
As proposed by @fishcakez in https://github.com/elixir-ecto/db_connection/issues/48#issuecomment-229505806
> Clearer "no process" error

- bin/elixir.bat
Windows 10 console now supports ANSI!
This PR adds code to detect:
- if running in a terminal
- if `powershell` is available (needed to test for ANSI support)
- if ANSI is supported
If and only if all of the above are true, the `-elixir ansi_enabled true` launch option is added to the `erl.exe` and `werl.exe` command lines.
Tested on Windows 10 and Windows 8.
> Add Windows ANSI detection

- lib/elixir/lib/string.ex
As mentioned in https://github.com/elixir-lang/elixir/issues/4943.
> Add specs for String.replace_* functions

- lib/elixir/src/elixir_with.erl
- lib/elixir/test/elixir/kernel/with_test.exs
> The else clause in with supports guards

- lib/elixir/test/elixir/enum_test.exs
- Enum.to_list/1: Optimize for ranges
- Add tests for Enum.reverse/1, Enum.reverse/2 and Enum.to_list/1
> Enum to list

- lib/elixir/lib/kernel.ex
Opening this as a PR instead of just pushing it to ask for feedback on a couple of things, I pointed them out in the comments. :)
> Polish the docs for Kernel.use/2

- lib/elixir/lib/task.ex
- lib/elixir/test/elixir/task_test.exs
* Added documentation and doctest
have I mentioned how much I :heart: doctests?
Thanks for all your work on Elixir everyone :)
Tobi
> Task.await/1 returns the reply of a task

- lib/elixir/lib/kernel.ex
- lib/elixir/test/elixir/kernel_test.exs
> Enhance in/2 to support |/2

- lib/elixir/lib/keyword.ex
- lib/elixir/test/elixir/keyword_test.exs
> Improve error message for Keyword.get_and_update/3

- lib/elixir/lib/enum.ex
- lib/elixir/test/elixir/enum_test.exs
Fix issue #5004 add test to include checks
> Return nil in Enum.find_index/2 if the element is not found in a Stream

- lib/elixir/lib/kernel.ex
> Docs and typespec for Kernel.get_and_update_in/3 now mention :pop

- lib/elixir/lib/path.ex
Following changes in https://github.com/elixir-lang/elixir/pull/4885
> Use underscore in function names: dirsep => dir_sep

- lib/elixir/lib/enum.ex
closes https://github.com/elixir-lang/elixir/issues/5023
> Enum slice docs + fix typespec

- lib/elixir/lib/gen_server.ex
This is just a first iteration. After my experience with https://github.com/elixir-lang/elixir/pull/5010 I figured there will be a lot of changes anyway.
I'm not sure which functions from `:sys` should be documented, I think I listed those that are most useful for debugging processes. As to custom install handler, it's not clear to me, what such handler would do, so I left it out for now.
Closes #4918
> Document :sys module and give example on how to use it

- lib/elixir/lib/option_parser.ex
We used `strict` all over the place, and that variable held a boolean. I renamed it to `strict?` to make it more idiomatic and clearer.
> Rename a variable in OptionParser to make its type clearer

- lib/elixir/lib/behaviour.ex
First of a bunch of PRs where we deprecated stuff that we wanted to deprecate for version 1.4 :)
> Deprecated the Behaviour module and its macros

- lib/elixir/lib/integer.ex
Based on suggestion in https://github.com/elixir-lang/elixir/issues/5046
> Integer.digits/2: Make example even clearer

- lib/elixir/lib/string.ex
- lib/elixir/test/elixir/string_test.exs
In response to issue number #5069  I implemented a check which sees if the incoming string is "" and if trim is true.
> Fix for issue 5069

- lib/mix/lib/mix.ex
> Correct link to mix environments

- lib/elixir/src/elixir_tokenizer.erl
- lib/elixir/test/elixir/kernel/errors_test.exs
- lib/iex/test/iex/interaction_test.exs
Updated error message and tests to fix #5122
> Enhancing error message for token matching failure

- lib/iex/lib/iex/autocomplete.ex
- lib/iex/test/iex/autocomplete_test.exs
Fix for #5132 
I'm not 100% sure the tests are right, or if there are any unusual implications with this fix, but all tests are passing.
> Resolves issue with autocompletion on structs not working in IEx

- lib/elixir/lib/enum.ex
- lib/elixir/lib/stream.ex
- lib/elixir/lib/stream/reducers.ex
- lib/elixir/test/elixir/enum_test.exs
- lib/elixir/test/elixir/stream_test.exs
This pull request adds map_every/3 to Enum and Stream module, fixex #5138
> Support Enum.map_every/3 and Stream.map_every/3

- lib/elixir/lib/kernel/special_forms.ex
Add the punctuation mark "," after link words
> Update special_forms.ex documentation

- lib/elixir/lib/exception.ex
- lib/elixir/test/elixir/exception_test.exs
Should be a start for #5152 :) Let me know what you think!
> Improve UndefinedFunctionError when using macros without require

- lib/elixir/pages/Guards.md
Final part of #5129 :)
\cc @fishcakez
> Add a "Guards" page to the docs

- lib/elixir/lib/stream.ex
Minor (and a bit random) improvements, but they may still be worth it :)
> Polish some code around Stream.zip/2

- lib/eex/lib/eex/engine.ex
Those pesky off by 1 errors. :)
> Correct small inaccuracy in EEx.Engine moduledoc

- lib/mix/lib/mix/scm/git.ex
- lib/mix/test/mix/tasks/deps.git_test.exs
- lib/mix/test/test_helper.exs
fixes https://github.com/elixir-lang/elixir/issues/5176
> exclude git sparse tests when git < 1.7.4

- lib/mix/lib/mix/utils.ex
> Keep mtime when copying files

- lib/elixir/lib/option_parser.ex
@josevalim decided to go with a PR anyways, I prefer if someone else gives this a look before merging anyways :)
> Refactor some error messages in OptionParser

- lib/ex_unit/lib/ex_unit/assertions.ex
- lib/ex_unit/test/ex_unit/assertions_test.exs
Fixes #5199
When using assert_receive, it is possible for the following sequence of
events:
1. `after` timeout triggers, indicating messages was not received
2. Process receive messages
3. `Process.info(self(), :messages)` is called and gets message
`assert_receive` was waiting for.
Previously, `assert_receive` would not check the output `Process.info(self, :messages)` for the expected pattern, so it would print a confusing error message that said "No message matching <pattern> after <timeout>ms", but then show a matching message in the "Process mailbox" section.  Now, for this special race-condition, a long-form explanation that the message is being delivered at or near the timeout is being printed, along with how this could impact production and how to fix it if it only impacts tests. …
> Explain race condition in assert_receive to user when it happens

- lib/elixir/lib/string.ex
> Document additional options for String.split/3

- lib/mix/lib/mix/tasks/cmd.ex
- lib/mix/test/mix/tasks/cmd_test.exs
Discussion in 
https://github.com/elixir-lang/elixir/pull/5211
> change mix cmd to use --app instead of --only

- lib/ex_unit/lib/ex_unit/assertions.ex
> Fix recently introduced typo

- lib/elixir/test/elixir/enum_test.exs
Those match some missing cases.
> Extended test suite for Enum.concat/2

- lib/elixir/pages/Operators.md
> Add a section about comparison operators in the "Operators" page

- lib/elixir/pages/Operators.md
based on 
https://github.com/elixir-lang/elixir/pull/5238/files#diff-50948d471af46f8f79bf8d175641fa42R67
by @fboyer
> Correct operator type name in sorting order

- lib/elixir/lib/task.ex
- lib/elixir/test/elixir/task_test.exs
If the monitor no longer exists Task.shutdown/2 would block forever
waiting for it. Always setup new monitor and try to get the right down
result.
> Fix Task.shutdown/1,2 infinite block when no monitor

- lib/mix/lib/mix/tasks/new.ex
- lib/mix/test/mix/tasks/new_test.exs
> Check directory existence in mix task new

- lib/ex_unit/lib/ex_unit/capture_log.ex
- lib/logger/lib/logger.ex
- lib/logger/lib/logger/app.ex
- lib/logger/lib/logger/backends/console.ex
- lib/logger/lib/logger/config.ex
- lib/logger/lib/logger/error_handler.ex
- lib/logger/lib/logger/translator.ex
- lib/logger/lib/logger/watcher.ex
- lib/logger/test/logger/backends/console_test.exs
- lib/logger/test/logger/error_handler_test.exs
- lib/logger/test/logger/translator_test.exs
- lib/logger/test/logger_test.exs
- lib/logger/test/test_helper.exs
> Switch Logger to Erlang's gen_event

- lib/elixir/lib/module.ex
- lib/mix/lib/mix/tasks/archive.install.ex
- lib/mix/lib/mix/tasks/deps.ex
- lib/mix/lib/mix/tasks/escript.build.ex
- lib/mix/lib/mix/tasks/escript.install.ex
- lib/mix/lib/mix/tasks/new.ex
Additionally, the are still some other changes that could be done of the same kind, but they are all part of tests.
let me know if you want to have consistency in tests as well.
```elixir
$ ag -s "my[a-z0-9]"
...
lib/elixir/test/elixir/kernel/typespec_test.exs
43:    assert_raise CompileError, ~r"invalid type specification: mytype = 1", fn ->
45:        @type mytype = 1
53:        @type mytype :: "foobar"
74:      @type mytype :: term
77:    assert [type: {:mytype, {:type, _, :term, []}, []}] =
101:      @type mytype :: 10
103:    assert [type: {:mytype, {:integer, _, 10}, []}] =
109:      @type mytype :: -10
112:    assert [type: {:mytype, {:op, _, :-, {:integer, _, 10}}, []}] =
129:      @type mytype :: binary
132:    assert [type: {:mytype, {:type, _, :binary, []}, []}] =
138: …
```
> Consistency: Use underscore after "my" adjective in underscore

- CHANGELOG.md
There were a few other functions added in #5140.
> Improve changelog entry.

- lib/elixir/lib/regex.ex
> Add an example of Regex.scan/3 using unicode

- lib/mix/lib/mix/tasks/new.ex
- lib/mix/test/mix/cli_test.exs
- lib/mix/test/mix/tasks/new_test.exs
* Include a link to ExDoc and update links to hexdocs.pm
* Generate @moduledoc and @doc with doctests
* For --sup projects, move the application module to Mod.Application
/cc @elixir-lang/elixir
> Update applications built by mix new

- lib/elixir/lib/macro.ex
- lib/elixir/src/elixir_exp.erl
- lib/elixir/src/elixir_translator.erl
- lib/elixir/test/elixir/kernel/expansion_test.exs
As discussed in https://github.com/elixir-lang/elixir/pull/5301#pullrequestreview-3711427
> Reword "pseudo-variables" with "compilation environment macros"

- lib/elixir/lib/calendar.ex
related to: https://github.com/elixir-lang/elixir/pull/5244
> Use singular time units

- lib/logger/lib/logger/app.ex
> Fix typo: :sasl_logger_tty_h -> :sasl_report_tty_h

- lib/elixir/lib/exception.ex
- lib/elixir/test/elixir/file_test.exs
Closes https://github.com/elixir-lang/elixir/issues/5296
> File.rmdir!/1: give a less confusing error message when directory is not empty

- CHANGELOG.md
- lib/elixir/lib/code.ex
- lib/elixir/lib/inspect/algebra.ex
- lib/elixir/lib/kernel.ex
- lib/elixir/lib/kernel/special_forms.ex
- lib/elixir/lib/macro.ex
- lib/elixir/lib/macro/env.ex
- lib/elixir/lib/module.ex
- lib/elixir/lib/option_parser.ex
- lib/elixir/lib/string.ex
- lib/elixir/lib/task.ex
- lib/elixir/pages/Naming Conventions.md
- lib/iex/lib/iex.ex
Continuation of https://github.com/elixir-lang/elixir/pull/5301
> Documentation: Add arity, correct arity, and link to callbacks and types

- lib/elixir/lib/kernel.ex
Missing space in docs for defstruct
> Add missing space

- lib/elixir/lib/calendar.ex
- lib/elixir/test/elixir/calendar_test.exs
> Add Date/Time/NaiveDateTime.compare/2

- lib/elixir/lib/inspect.ex
As discussed on IRC
\cc @josevalim
> Append with cons instead of prepend + reverse in inspect

- lib/eex/lib/eex.ex
- lib/eex/lib/eex/compiler.ex
- lib/eex/lib/eex/engine.ex
- lib/eex/lib/eex/tokenizer.ex
This PR covers all specs for the EEx project. 
Additionally it adds guards to functions whenever applicable.
> [WIP] Complete specs and guards for EEx

- lib/elixir/lib/access.ex
I have read the code in _access.ex_ from top to bottom and since I was on it I edited little things here and there in passing.
This is a summary of the patch:
* Small grammar/typo corrections.
* Specify in some places what happens if a given key is not present.
* Some functions document they accept _anything_ that implements the `Access` behaviour, but according to their patterns only structs match (in addition to maps and keyword lists). Some edits revise this, which is also coherent with the sentence "_The implementation should be added to the
module that defines the struct being accessed_".
* There is a bunch of functions that are meant to be used by `get_in/2` and friends but their documentation didn't specifically say they return _functions_ with that purpose.
* There are some …
> Edit pass over access.ex

- lib/elixir/lib/io.ex
- lib/elixir/lib/string.ex
- lib/elixir/src/elixir_utils.erl
- lib/elixir/test/elixir/base_test.exs
- lib/elixir/test/elixir/file_test.exs
- lib/elixir/test/elixir/inspect_test.exs
- lib/elixir/test/elixir/io_test.exs
- lib/elixir/test/elixir/kernel/binary_test.exs
- lib/elixir/test/elixir/kernel/char_list_test.exs
- lib/elixir/test/elixir/path_test.exs
- lib/elixir/test/elixir/string_io_test.exs
- lib/elixir/test/elixir/system_test.exs
- lib/ex_unit/lib/ex_unit/case.ex
Following spelling convention in https://github.com/elixir-lang/elixir/pull/4754
> Properly spell UTF-8

- lib/elixir/lib/calendar.ex
- lib/elixir/lib/option_parser.ex
- lib/ex_unit/lib/ex_unit/assertions.ex
- lib/mix/lib/mix/tasks/xref.ex
- lib/mix/test/mix/tasks/xref_test.exs
I would advice not to merge the squash the commits in this PR
> Various fixes

- Makefile
e.g.
$ make docs_elixir DOCS_FORMAT=epub
> Add Makefile variable to control ExDoc output format.

- lib/elixir/lib/path.ex
As discussed in
https://github.com/elixir-lang/elixir/commit/c4ea85d7e5d01e17c0cd2c9d7efcb48395b16fdc#commitcomment-19701579
> Remove code for Erlang version which is no longer supported

- lib/elixir/lib/kernel.ex
Two suggestions for wording in the `module_nesting` function comment.
Thanks for Elixir!
> Improve a line in Kernel comment

- lib/elixir/lib/kernel.ex
Inspired by this comment: https://github.com/elixir-lang/elixir/pull/5441#issuecomment-259980455 :)
> Document implicit function try

- lib/elixir/lib/path.ex
Hi all,
just a double space there.
Thanks!
> Remove double space from Path

- lib/mix/lib/mix/tasks/new.ex
Not an amazing PR by any means 😛
> Don't print `cd .` to shell

- lib/elixir/lib/calendar.ex
- lib/elixir/lib/kernel.ex
- lib/elixir/lib/kernel/typespec.ex
- lib/elixir/lib/module.ex
- lib/elixir/lib/module/locals_tracker.ex
- lib/elixir/src/elixir_def.erl
- lib/elixir/src/elixir_module.erl
- lib/elixir/src/elixir_quote.erl
- lib/elixir/test/elixir/gen_event_test.exs
- lib/elixir/test/elixir/kernel/warning_test.exs
- lib/elixir/test/elixir/macro_test.exs
- lib/elixir/test/elixir/module_test.exs
- lib/ex_unit/lib/ex_unit/case.ex
- lib/iex/lib/iex/config.ex
- lib/mix/test/mix/local_test.exs
> Refactor and warn on unused module attributes

- lib/elixir/lib/keyword.ex
- lib/elixir/test/elixir/keyword_test.exs
> Raise when given non-keyword-lists in Keyword.merge/2

- lib/mix/lib/mix/tasks/compile.app.ex
- lib/mix/test/mix/tasks/compile.app_test.exs
> Improve error messages when validating Mixfiles' application/0

- lib/mix/lib/mix/compilers/erlang.ex
- lib/mix/lib/mix/tasks/compile.erlang.ex
- lib/mix/lib/mix/tasks/compile.leex.ex
- lib/mix/lib/mix/tasks/compile.yecc.ex
> Improve option validation in Erlang-related compilers

- lib/ex_unit/examples/difference.exs
- lib/ex_unit/lib/ex_unit/cli_formatter.ex
- lib/ex_unit/lib/ex_unit/formatter.ex
> Use red or green background for whitespace-only diffs

- lib/elixir/test/elixir/code_test.exs
- lib/elixir/test/elixir/exception_test.exs
- lib/elixir/test/elixir/uri_test.exs
As requested by @lexmag 
https://github.com/elixir-lang/elixir/pull/5284#issuecomment-261787701
> Add underscore when file names, variables and atoms

- lib/iex/lib/iex/autocomplete.ex
- lib/iex/lib/iex/evaluator.ex
- lib/iex/test/iex/autocomplete_test.exs
> Improve IEx autocompletion to handle manual imports.

- lib/elixir/lib/atom.ex
- lib/elixir/lib/file.ex
- lib/elixir/lib/float.ex
- lib/elixir/lib/inspect.ex
- lib/elixir/lib/inspect/algebra.ex
- lib/elixir/lib/integer.ex
- lib/elixir/lib/kernel.ex
- lib/elixir/lib/kernel/typespec.ex
- lib/elixir/lib/list/chars.ex
- lib/elixir/lib/string.ex
- lib/elixir/src/elixir.erl
- lib/elixir/src/elixir_dispatch.erl
- lib/elixir/src/elixir_rewrite.erl
I am not sure about a couple things, I will leave comments under those :)
> Hard-deprecate the "char_list" spelling

- lib/elixir/test/elixir/code_test.exs
What I did:
* Better test names
* Removed a few duplicate tests
* Used a few `describe/2` blocks to organize tests a bit more
I am not sure how much these type of PR is appreciated, I think it's good to have organized tests that are easy to understand and navigate but maybe other members of the team feel that this is not worth it. Let me know! :D
> Tidy up tests for Code

- lib/mix/lib/mix/tasks/escript.build.ex
- lib/mix/test/fixtures/deps_status/deps/ok/mix.exs
- lib/mix/test/mix/tasks/escript_test.exs
Not really sure if this is a feasible solution for https://github.com/elixir-lang/elixir/issues/5538, but at least it *appears* to be a working solution so I figured a PR wouldn't hurt 😄
> Use Elixir apps from deps when building escripts

- lib/elixir/lib/module.ex
Hello!
This caught me out today. I thought it would be good to document this caveat :)
Thanks,
Louis
> Add detail on usage restrictions to Module.defines?/{2,3}

- lib/elixir/lib/agent.ex
- lib/elixir/lib/gen_server.ex
- lib/elixir/lib/supervisor.ex
Heya
A small wording tweak :)
Cheers,
Louis
> Minor grammar tweak

- lib/elixir/lib/collectable.ex
I think it was pretty cryptic how to use the `Collectable` protocol, so I added a couple of examples in the style of what we do in the `Enumerable` protocol. Let me know what you think!
> Add examples and polish docs for the Collectable protocol

- lib/mix/lib/mix/tasks/do.ex
- lib/mix/test/mix/tasks/do_test.exs
> Ignore left part of comma if empty in "mix do"

- .travis.yml
:tada:
(wasn't available on Travis immediately but it is now :) )
> Test against Erlang 19.2 (newest release)

- lib/elixir/src/elixir_aliases.erl
- lib/elixir/test/elixir/kernel/alias_test.exs
> Fix removal of aliases

- lib/elixir/lib/system.ex
Ref: https://github.com/elixir-lang/elixir/pull/5610#discussion_r94416531
> Update typespec for System.get_env/1

- lib/mix/lib/mix/tasks/deps.ex
It wasn't clear what is the valid syntax for version requirements.
> Add link to version spec to mix deps documentation

- lib/elixir/lib/calendar.ex
> Fix typespecs in Calendar

- lib/elixir/lib/macro.ex
Hi all,
please see if this change makes sense.
The break in the phrase looked like a bit of a typo.
Cheers!
> Rephrase doc in Macro

- ISSUE_TEMPLATE.md
...in ISSUE_TEMPLATE
In the same vein as https://github.com/elixir-lang/elixir-lang.github.com/commit/779d43c077bfa73028d03983175cef0a4a70d214
> Use `elixir --version` instead of `elixir -v`

- lib/elixir/lib/task.ex
Not sure how you like to write examples. Perhaps this sort of example doesn't belong in the main docs. Let me know.
> Add an example for Task.async_stream/3

- lib/elixir/lib/macro.ex
- lib/elixir/test/elixir/macro_test.exs
Adds a way to generate a list of variables on a whim.
The idea is pretty much copied from the Elixir Koans https://github.com/elixirkoans/elixir-koans/blob/master/lib/koans.ex#L46 
#5689
> Create list of args based on Macro.var

- lib/mix/lib/mix/dep/loader.ex
- lib/mix/lib/mix/tasks/deps.compile.ex
> Run `make clean` for erlang.mk

- lib/elixir/lib/gen_event.ex
- lib/elixir/src/elixir_dispatch.erl
As discussed on IRC with @josevalim.
> Hard deprecate GenEvent and provide alternatives in its docs

- lib/elixir/lib/option_parser.ex
- lib/elixir/test/elixir/option_parser_test.exs
Fixes #5708.
Should be merged or closed after discussion reaches result :).
> Implement allow_inexistent_atoms? for OptionParser

- lib/elixir/test/elixir/option_parser_test.exs
In PR #5709 @whatyouhide mentioned that this tests are violating new style guide, this PR should fix it.
> Fixed codestyle for OptionParser tests

- lib/mix/lib/mix/dep/converger.ex
- lib/mix/test/mix/tasks/deps_test.exs
> Warning for duplicated deps on project root level

- lib/elixir/lib/exception.ex
- lib/elixir/lib/file.ex
- lib/elixir/test/elixir/file_test.exs
As proposed in https://groups.google.com/d/msg/elixir-lang-core/bSDn7lNlOv8/nnybSV27CAAJ
> Add hard links

- lib/elixir/lib/file.ex
This improves readability while still keeping the code short and concise. Single-letter aliases are hard to follow (you have to lookup the `alias` call) and IMO it is misleading to alias what looks like an Elixir module (`F`) to what is an Erlang module.
Thoughts are welcome :)
> Stop aliasing :file to F in the File module

- lib/elixir/lib/path.ex
In the same vein as
https://github.com/elixir-lang/elixir/pull/5768
> Stop aliasing :filename to FN in the Path module

- lib/elixir/src/elixir_exp.erl
- lib/elixir/src/elixir_exp_clauses.erl
- lib/elixir/src/elixir_translator.erl
- lib/elixir/test/elixir/kernel/expansion_test.exs
@josevalim do you think we should remove the test for this error from [`errors_test.exs`](https://github.com/elixir-lang/elixir/blob/68739491bf154f7b369c54206a98e05849fad7e5/lib/elixir/test/elixir/kernel/errors_test.exs#L788-L793)?
> Move compile error for _ in cond to elixir_exp

- lib/elixir/lib/calendar.ex
It supports negative integers.
> Fix typespec of DateTime.from_unix!

- lib/elixir/lib/registry.ex
- lib/elixir/test/elixir/registry_test.exs
PR according to [Elixir Core Mailing List Proposal](https://groups.google.com/forum/#!topic/elixir-lang-core/SXNog8I-UYw)
> Support of ETS guard conditions for Registry.match

- RELEASE.md
- lib/elixir/pages/Deprecations.md
Additionally correct link in master
> Add instructions to RELEASE to update Deprecations page

- lib/mix/lib/mix/task.ex
A question came up in the Elixir slack regarding command line arguments to mix tasks. I thought it would be useful to provide the use of args in the example.
> Provide a Mix Task example with use of args

- lib/elixir/lib/process.ex
Originally discussed in https://github.com/elixir-lang/elixir/pull/5880#discussion_r106071314
> Add spec to Process.sleep/1

- lib/elixir/lib/process.ex
Originally discussed in https://github.com/elixir-lang/elixir/pull/5880#discussion_r106071471
> Use defdelegate/2 whenever possible in Process module

- lib/elixir/lib/kernel.ex
- lib/elixir/lib/process.ex
> Improve docs for Process.link/1

- ISSUE_TEMPLATE.md
It will make it easier for people to fill out the template
> Add space after semi-colon in Issue Template

- lib/elixir/pages/Typespecs.md
- lib/elixir/test/elixir/kernel/typespec_test.exs
Originally discussed in https://github.com/elixir-lang/elixir/pull/5876
> Document and test function/0 built-in type

- lib/elixir/lib/enum.ex
Extracted from https://github.com/elixir-lang/elixir/pull/5818
> Perform only single protocol dispatching on Enum.fetch/2

- lib/elixir/lib/kernel/special_forms.ex
Source: http://erlang.org/doc/reference_manual/expressions.html#id80928
> Add information about after clause timeout limit

- lib/elixir/lib/registry.ex
> Comment edit in registry.ex [ci skip]

- lib/elixir/lib/integer.ex
- lib/elixir/test/elixir/integer_test.exs
* 	Optimize Integer.gcd/2 when dealing with same integers
* 	Add spec for edge-case in Integer.gcd/2
/cc @fxn @lexmag @Qqwy
> Integer.gcd/2 improvements 

- bin/elixirc
- bin/elixirc.bat
- Use present continuous in elixirc bin files
- Align descriptions of options in elixirc bin files
> Standardize elixirc bin files

- lib/elixir/lib/kernel.ex
Also replace call to `:lists.delete/2` with `List.delete/2`
> Replace calls to :maps.update/3 with Map.replace!/3

- Makefile
The files are generated here
https://github.com/eksperimental/elixir/blob/85b68fe8783fd4b7db3a733cb78b4690cc23e543/Makefile#L237-L247
> Remove temporary files in "clean_man" target in Makefile

- lib/elixir/lib/access.ex
- lib/elixir/lib/kernel.ex
These are a bit more finely-grained specs.
It completes the whole module.
I have tested it with Dialyzer to remove any warnings it could cause.
Docs for Access.get_and_update/3 and callback, have been improved as well.
> [WIP] Improve specs in Access module

- lib/elixir/lib/kernel.ex
- lib/elixir/lib/module.ex
- lib/elixir/test/elixir/kernel/overridable_test.exs
> Make defoverridable/1 accept a module name as an argument

- lib/elixir/lib/enum.ex
- lib/elixir/lib/uri.ex
Trying to slowly remove the clutter, not sure if worth if for you folks.
> Silence compilation warnings about the deprecation of Dict

- lib/elixir/lib/version.ex
We don't need the complexity and abstraction of the DSL for such little code. The resulting amount of code is pretty much the same in conciseness, and a few lines of code smaller.
> Get rid of the requirement-parsing DSL in Version

- lib/logger/lib/logger/translator.ex
- lib/logger/test/logger/translator_test.exs
Always show client pid/name/node when present but only show stacktrace on debug.
Note: Backport to 1.4 when merged
> Handle OTP 20 GenServer log messages

- lib/elixir/lib/regex.ex
Use a similar optimization technique to the one in plug https://github.com/elixir-lang/plug/pull/547
This allows us to keep as large parts of the initial binary as possible,
in the case of no escapes, no allocation is needed.
In most cases it should be about twice as fast, in case no escape is needed,
in can be even 10x faster. For small strings, it will be about 15% slower, but
with entire execution in range of 50μs, this should be acceptable.
> Optimize Regex.escape/1

- lib/iex/lib/iex/autocomplete.ex
- lib/iex/test/iex/autocomplete_test.exs
> Skip autocompletion of module names that are invalid without being quoted

- .gitignore
- lib/mix/lib/mix/tasks/new.ex
As discussed in the mailing list.
> Prepend slash to directories in .gitignore files and generated ones

- lib/elixir/lib/module.ex
- lib/elixir/src/elixir_module.erl
- lib/elixir/src/elixir_overridable.erl
- lib/elixir/test/elixir/kernel/impl_test.exs
> Do not warn about missing @impl for overridable functions

- lib/mix/lib/mix/dep.ex
- lib/mix/lib/mix/local.ex
- lib/mix/lib/mix/tasks/archive.install.ex
- lib/mix/test/mix/tasks/deps_test.exs
Related to https://github.com/elixir-lang/elixir/pull/6007
> Use double quote when displaying file paths and extensions

- lib/iex/lib/iex/autocomplete.ex
- lib/iex/test/iex/autocomplete_test.exs
If a function is defined with default arguments and @doc set to false,
the original function would be excluded from autocompletion,
but the automatically created functions with smaller arities would still remain
Example.
> iex> String.r<TAB>
> replace/3             replace/4             replace_leading/3
> replace_prefix/3      replace_suffix/3      replace_trailing/3
> reverse/1             rjust/2
rjust/2 is listed,
but it shouldn't, same as rjust/3 (the original function) is not shown.
> Remove in IEX autocompletion default arg. functions with @doc false

- lib/elixir/src/elixir_dispatch.erl
Hope this helps maintaining the CHANGELOG and Deprecation pages
> Sort deprecation clauses alphabetically in :elixir_dispatch

- lib/mix/test/mix/shell/io_test.exs
- lib/mix/test/mix/tasks/xref_test.exs
- lib/mix/test/test_helper.exs
Understandably development on Elixir language itself on Windows is less tested because of personal preferences and lack of support in Travis CI... I develop on Windows because I need to occasionally write some C#.
The current test suite does not pass in Windows. This pull request is aimed to address some issues in the test suite..
Please let me know if it's easier to put everything in one branch or separated for different fixes.
> Test Suite Windows compatibility

- appveyor.yml
See #6141 and https://github.com/elixir-lang/elixir/pull/6141#issuecomment-303732946
Here's what it looks like:
https://ci.appveyor.com/project/xiamx/elixir/history
Status badge:
https://www.appveyor.com/docs/status-badges/
> Add CI for Windows with Appveyor

- CHANGELOG.md
This PR adds a note to the CHANGELOG about the Version parser updates. Also see: #6155
> add note to CHANGELOG.md about Version parser updates

- lib/elixir/lib/enum.ex
- lib/elixir/lib/stream.ex
- lib/elixir/lib/stream/reducers.ex
- lib/elixir/test/elixir/enum_test.exs
- lib/elixir/test/elixir/stream_test.exs
As requested by @josevalim in #5888, here is the initial changes I've made in order to implement `Stream.chunk_by/4`.
> Provide Enum.chunk_by/4 and Stream.chunk_by/4

- lib/mix/lib/mix/compilers/elixir.ex
- lib/mix/lib/mix/compilers/test.ex
- lib/mix/lib/mix/tasks/xref.ex
- lib/mix/test/mix/tasks/compile.elixir_test.exs
Fix for #5983. A test is missing (and will be added tomorrow).
> Store multiple sources in case of module conflicts

- lib/logger/lib/logger/translator.ex
- lib/logger/test/logger/translator_test.exs
* :message_queue_len and :current_stacktrace added
* :messages and :dictionary not always present
> Handle changes to crash reports in OTP 20

- CHANGELOG.md
It documments commit 7ad7d3d7c9ae498fee46a3ee9d9281df7c5b491d
> Add bugfix to CHANGELOG of IEx

- lib/elixir/src/elixir_erl_pass.erl
It is very common to have "#{inspect foo}" calls inside strings,
especially when producing error messages. Since we know Kernel.inspect/2
always returns a string, we can safely drop the wrapping
String.Chars.to_string/1 call that is otherwise always present during
interpolation.
> Optimize inspect calls inside interpolation

- lib/elixir/lib/process.ex
> Fix typo in Process docs

- lib/ex_unit/lib/ex_unit/case.ex
- lib/ex_unit/test/ex_unit/describe_test.exs
> Prevent describe blocks with the same name in ExUnit

- lib/elixir/lib/task.ex
- lib/elixir/lib/task/supervised.ex
- lib/elixir/lib/task/supervisor.ex
- lib/elixir/test/elixir/task/supervisor_test.exs
- lib/elixir/test/elixir/task_test.exs
Closes #6212.
Suggestions on how to better test this would be appreciated.
> Add :ordered option to async_stream

- lib/elixir/unicode/properties.ex
As mentioned in https://github.com/elixir-lang/elixir/issues/4617.
> Use :binary.split/3 in String.Break.split/1

- lib/elixir/lib/exception.ex
- lib/elixir/lib/kernel/typespec.ex
- lib/elixir/pages/Deprecations.md
- lib/elixir/test/elixir/kernel/typespec_test.exs
- lib/iex/lib/iex/evaluator.ex
- lib/mix/lib/mix/project.ex
> Emit warning when using %{foo => bar} in typespecs

- lib/elixir/pages/Deprecations.md
https://github.com/elixir-lang/elixir/pull/6258#discussion_r124097551
> Add EEx depracation to Deprecations.md

- lib/elixir/lib/keyword.ex
- lib/elixir/lib/map.ex
Re-arranges docs so that happy-path is shown first and matches `replace!/3` docs
> Minor update to Map.replace/3 and Keyword.replace/3 docs

- lib/elixir/pages/Typespecs.md
> Fix @spec in Defining a specification section from Typespecs documentation

- lib/iex/lib/iex/helpers.ex
Closes #6348
Similar to: https://github.com/wojtekmach/elixir/blob/b13a58607e2aac7c6c6d7df3344865a406921dac/lib/iex/lib/iex/helpers.ex#L207
> Add note about precompiled source code for IEx.Helper.open/2

- lib/elixir/lib/calendar/date.ex
> Correct Date Documentation

- lib/elixir/lib/gen_event.ex
~Can also just make the fix `provides a`~
> Fix gen_event docs typo

- lib/elixir/lib/calendar/time.ex
> Fix Time.new spec

- lib/elixir/lib/supervisor.ex
Change *supervisr* -> *supervisor*.
> Fix spelling

- lib/logger/lib/logger.ex
I just saw one in the commit log, so here is the correction. Have a good one!
> [Trivial] [Docs] Fix typos

- lib/elixir/src/elixir_parser.yrl
- lib/elixir/test/elixir/kernel/warning_test.exs
> Warn if unary operators are followed by new lines

- lib/elixir/lib/enum.ex
> Fix Enum.reduce/3 documentation

- lib/elixir/lib/kernel/special_forms.ex
* Add the example of partially applied module function
* Improve local function example
* Improve list example
> Improve doc for Kernel.SpecialForms.&/1

- lib/elixir/lib/inspect/algebra.ex
Hello Elixir core team,
I forge ahead in my mission to revolutionize the language with minimalistic pull requests.
Cheers!
> Fix typo in Inspect.Algebra doc

- lib/elixir/lib/port.ex
- lib/elixir/lib/process.ex
- lib/elixir/src/elixir_rewrite.erl
- lib/elixir/test/elixir/port_test.exs
> Add Port.monitor/1 and Port.demonitor/1 functions

- lib/elixir/lib/kernel.ex
- lib/elixir/lib/port.ex
- lib/elixir/lib/regex.ex
- lib/elixir/src/elixir_bitstring.erl
- lib/elixir/test/elixir/kernel/expansion_test.exs
- lib/elixir/test/elixir/stream_test.exs
- lib/ex_unit/test/ex_unit/doc_test_test.exs
- lib/iex/lib/iex/autocomplete.ex
found with https://github.com/lucasdemarchi/codespell
> Fix a few spelling errors

- lib/mix/lib/mix/dep/converger.ex
- lib/mix/test/mix/umbrella_test.exs
> Loading umbrella project apps optional deps

- lib/elixir/src/elixir_clauses.erl
- lib/elixir/test/elixir/kernel/warning_test.exs
> Warn if catch comes before rescue in try

- lib/elixir/src/elixir_clauses.erl
- lib/elixir/src/elixir_def.erl
- lib/elixir/test/elixir/kernel/errors_test.exs
> Improve the error message for rescue, catch and else inside def

- lib/elixir/src/elixir_clauses.erl
- lib/elixir/test/elixir/kernel/warning_test.exs
> Warning on the use of length(x) == 0 on guards

- lib/elixir/lib/keyword.ex
This optimises all functions similar to Keyword.delete/2:
* Keyword.delete/3
* Keyword.delete_first/2
* Keyword.pop/3
* Keyword.pop_lazy/3
* Keyword.pop_first/3
There are three major changes for "delete" family:
* use by-hand recursion instead of non-BIF :lists calls
* in case we end up not deleting a value, use trow-catch to return the
original list unmodified (this significantly lowers memory use)
* build the result through body recursion, this way when we unwind the stack
we free all the data and leave no garbage behind for the GC.
For the "pop" family:
* use by-hand recursion instead of non-BIF :lists calls
* do only a single pass over the list instead of two passes that previous
fetch + delete algorithm did
In benchmarks, the new Keyword.delete/2 functions is twice as fast as the old …
> Optimise Keyword.delete/2 and friends

- lib/elixir/lib/io.ex
The purpose of this PR is to add more info about the function IO.puts.  Add info about the return value of the function and also 2 examples of how to use it.
> Improve docs on IO.puts/2 function

- lib/ex_unit/lib/ex_unit/callbacks.ex
- lib/ex_unit/test/ex_unit/supervised_test.exs
> Add ExUnit.Callbacks.start_supervised!/2

- Makefile
Ref https://github.com/elixir-lang/elixir/issues/6562#issuecomment-333213263
I tested it by both manually unpacking and via `asdf`. cc @ericmj
> Include lib/*/lib files in Precompiled.zip

- lib/elixir/src/elixir_aliases.erl
Small changes to improve the wording in alias error messages.
> Improve the wording in alias error messages

- lib/elixir/lib/task.ex
My main reason for submitting this pull-request is that I had some confusion about what happens to the task process when a timeout occurs. Will it stop or will it continue to run? Hopefully, this change will make it more clear.
I also changed "function will exit" to "current process will exit" to make it more clear that the process is exiting.
Finally, I moved all discussion of timeouts into the same paragraph.
Hopefully this is helpful. Thanks! ✨
> Task.await/2 doc updates

- lib/elixir/lib/code.ex
- lib/elixir/lib/code/formatter.ex
- lib/elixir/test/elixir/code/identifier_test.exs
- lib/elixir/test/elixir/code_formatter/calls_test.exs
- lib/elixir/test/elixir/code_formatter/comments_test.exs
- lib/elixir/test/elixir/code_formatter/containers_test.exs
- lib/elixir/test/elixir/code_formatter/general_test.exs
- lib/elixir/test/elixir/code_formatter/integration_test.exs
- lib/elixir/test/elixir/code_formatter/literals_test.exs
- lib/elixir/test/elixir/code_formatter/operators_test.exs
- lib/elixir/test/elixir/code_identifier_test.exs
- lib/elixir/test/elixir/test_helper.exs
The `mix format` task is coming in another pull request.
> Add a code formatter

- lib/ex_unit/lib/ex_unit/capture_log.ex
- lib/ex_unit/test/ex_unit/capture_log_test.exs
> Improving the error message for capture_log when Logger is down

- .formatter.exs
- .travis.yml
- lib/elixir/lib/code/formatter.ex
- lib/elixir/src/elixir.erl
- lib/elixir/src/elixir_parser.yrl
- lib/elixir/test/elixir/code_formatter/operators_test.exs
- lib/mix/lib/mix/tasks/format.ex
- lib/mix/test/mix/tasks/format_test.exs
- scripts/random_file.exs
All code in this PR has been formatted by the formatter.
> Add mix format

- lib/elixir/test/elixir/fixtures/dialyzer/callback.ex
- lib/elixir/test/elixir/kernel/dialyzer_test.exs
- lib/elixir/test/elixir/kernel/typespec_test.exs
- lib/iex/lib/iex/introspection.ex
- lib/iex/test/iex/helpers_test.exs
> Show the multiple clauses for the same callback on IEx.Introspection.b/1

- lib/mix/test/mix/tasks/deps.path_test.exs
This formats this file according to the new formatter. One down!
> Run the code formatter on Mix.Tasks.DepsPathTest

- lib/elixir/lib/port.ex
This was a quite simple one :)
> Run the code formatter on Port

- lib/elixir/test/elixir/code_formatter/integration_test.exs
Formatting a test for the formatter - so meta!
> Run the code formatter on CodeFormatter.IntegrationTest

- lib/mix/lib/mix/tasks/escript.install.ex
No additional changes were necessary.
> Formatted lib/mix/lib/mix/tasks/escript.install.ex

- lib/elixir/test/elixir/kernel/parallel_compiler_test.exs
> Fix test race condition accessing tmp directory

- lib/elixir/lib/string_io.ex
Build passing for all three:
`bin/elixirc lib/elixir/lib/string_io.ex -o lib/elixir/ebin`
`bin/elixir lib/elixir/test/elixir/string_io_test.exs`
`make test`
> Run code formatter on lib/elixir/lib/string_io.ex

- lib/elixir/lib/set.ex
bin/elixirc lib/elixir/lib/set.ex -o lib/elixir/ebin
bin/elixir lib/elixir/test/elixir/set.exs
make test
After running all three, this is build passing!
> Run code formatter on lib/elixir/lib/set.ex

- lib/mix/test/mix/project_test.exs
Ran the code formatter as request on lib/mix/test/mix/project_test.exs!
> Run the Formatter on lib/mix/test/mix/project_test.exs

- lib/iex/test/test_helper.exs
I did have to put the comment on line 74 back. The formatter moved it to the beginning of the function body
> Run formatter on lib/iex/test/test_helper.exs

- lib/elixir/test/elixir/fixtures/dialyzer/protocol_opaque.ex
Not sure why the build failed initially on something unrelated. Is this a flakey test?
> Run the code formatter on Dialyzer.ProtocolOpaque

- lib/iex/lib/iex/helpers.ex
Code formatted according to #6643.
> Format IEx.Helpers

- lib/mix/lib/mix/tasks/xref.ex
Previous PR had a hanging build. Let's try this again
> Run the formatter on Mix.Tasks.Xref

- lib/elixir/unicode/unicode.ex
Formatting file `lib/elixir/unicode/unicode.ex` as per #6643.
> Run the code formatter on String.Unicode

- lib/elixir/test/elixir/node_test.exs
Formatting file lib/elixir/test/elixir/node_test.exs as per #6643.
> Run the code formatter on lib/elixir/test/elixir/node_test.exs

- lib/elixir/test/elixir/collectable_test.exs
> Run format on collectable_test.exs

- lib/elixir/lib/stream.ex
bin/elixirc lib/elixir/lib/stream.ex -o lib/elixir/ebin
bin/elixir lib/elixir/test/elixir/stream_test.exs
make test
After running all three, this is build passing.
> Run code formatter on lib/elixir/lib/stream.ex

- lib/elixir/lib/enum.ex
Apologies for an immediate follow up PR to #6782, but I had a shower thought on how to make the language more clear after the PR was merged.
Thanks!
> improve clarity of group_by docs

- lib/eex/lib/eex/tokenizer.ex
> Run formatter on lib/eex/lib/eex/tokenizer.ex

- lib/mix/test/mix/tasks/run_test.exs
- 3b8e28b just executed `bin/elixir bin/mix format lib/mix/test/mix/tasks/run_test.exs`
- f7133b9 `Example 3: calls with many arguments` pattern at #6643
- 86a8a7a `Example 1: multi-line data structures` pattern at #6643 
passed tests `make test`
> Run the code formatter on Mix.Tasks.RunTest

- lib/mix/lib/mix/tasks/compile.yecc.ex
Formatting file lib/mix/tasks/compile.yecc.ex  #6643
> Run the code formatter on lib/mix/tasks/compile.yecc.ex

- lib/elixir/lib/gen_server.ex
Couple of places where I don't understand the formatter output...
> Run code formatter on GenServer

- lib/mix/test/test_helper.exs
There are a couple of gnarly `for` comprehensions in this file that were condensed into a single line. I'm not sure if that's the preferred style or not. Happy to make changes 😀
> Run code formatter on lib/mix/test/test_helper.exs

- lib/elixir/test/elixir/kernel/binary_test.exs
Please let me know if I need to change something. :)
> Run code formatter on lib/elixir/test/elixir/kernel/binary_test.exs

- lib/elixir/lib/io/ansi/docs.ex
Formatter lib/elixir/lib/io/ansi/docs.ex to #6643
> Run code formatter on lib/elixir/lib/io/ansi/docs.ex

- lib/iex/lib/iex/evaluator.ex
Ran the formatter on lib/iex/lib/iex/evaluator.ex!
> Run the Formatter on lib/iex/lib/iex/evaluator.ex

- lib/mix/lib/mix/cli.ex
Hello! Following the instructions in https://github.com/elixir-lang/elixir/issues/6643, I ended up running the formatter on the Mix.CLI module.
Let me know if other change are needed.
Thanks!
> Run the code formatter on Mix.CLI

- lib/elixir/test/elixir/code_formatter/calls_test.exs
In response to https://github.com/elixir-lang/elixir/issues/6643 .
> Run the code formatter on lib/elixir/test/elixir/code_formatter/calls_test.exs

- lib/elixir/lib/stream/reducers.ex
Ran through the steps in #6643 and extracted some anonymous functions that are passed as arguments in the process.
This is such a great tool! Thanks! 🙏
> Run code formatter on Stream.Reducers

- lib/iex/test/iex/helpers_test.exs
Changes `lib/iex/test/iex/helpers_test.exs` for the new code format.
> Update code format per new style

- lib/elixir/test/elixir/task/supervisor_test.exs
> Run code formatter on lib/elixir/test/elixir/task/supervisor_test.exs

- lib/elixir/test/elixir/kernel/impl_test.exs
> Format kernel/impl_test.exs

- lib/mix/test/mix/tasks/compile.erlang_test.exs
> Run code formatter on lib/mix/test/mix/tasks/compile.erlang_test.exs

- lib/elixir/test/elixir/kernel/raise_test.exs
> Run code formatter on Kernel.RaiseTest

- lib/elixir/lib/gen_server.ex
Implementation changed after this commit: https://github.com/elixir-lang/elixir/commit/c907598cb1e508aac1664d8f198cc3f157fc3426
> Update default implementation in GenServer docs

- lib/logger/lib/logger.ex
The previous docs assumed an example using a string message
See https://github.com/elixir-lang/elixir/issues/6941#issuecomment-337018865
> Fix docs about logging strings vs funcs

- lib/elixir/src/elixir_parser.yrl
- lib/elixir/test/elixir/code_formatter/integration_test.exs
- lib/elixir/test/elixir/code_test.exs
Closes #6945.
Not sure the test is optimal but it's a start :).
> Fix a bug where we discarded some meta in some literals in the parser

- lib/elixir/lib/calendar.ex
- lib/elixir/lib/calendar/datetime.ex
- lib/elixir/lib/calendar/naive_datetime.ex
- lib/elixir/lib/calendar/time.ex
- lib/elixir/test/elixir/calendar_test.exs
> Add truncate to Time, DateTime and NaiveDateTime

- lib/elixir/src/elixir_erl_pass.erl
- lib/elixir/src/elixir_expand.erl
Since they modify the AST the correct place for the transformation is not the
macro expansion like today, but rather the erlang pass.
A note for people running git blame:
This transformation was done in the first place to correct the error that is
raised by `erlang:andalso/2` and `erlang:orelse/2` in case the first argument
is not a boolean. The rewrite changes it from `:badarg` into
`{:badbool, op, value}`. The inlining of both functions into a case would be
done anyway in the erlang compiler.
> Move andalso and orelse expansion to the erl pass

- lib/elixir/src/elixir_erl_for.erl
- lib/elixir/src/elixir_expand.erl
- lib/elixir/test/elixir/kernel/comprehension_test.exs
- lib/elixir/test/elixir/kernel/expansion_test.exs
> Support uniq: true in for comprehensions

- lib/elixir/src/elixir_def.erl
- lib/elixir/test/elixir/kernel/warning_test.exs
> Warn duplicate definitions in macros

- lib/elixir/src/elixir_erl_pass.erl
- lib/elixir/test/elixir/fixtures/dialyzer/with.ex
Add generated: true to guard clauses from else in with clauses
Resolves #6426
> Remove dialyzer warnings from else in with clauses

- lib/elixir/src/elixir_fn.erl
- lib/elixir/test/elixir/kernel/errors_test.exs
Closes #7029 
Would this be heading in the right direction?
> [WIP] Throw Error if anonymous functions has default arguments

- lib/elixir/lib/macro/env.ex
- lib/elixir/test/elixir/macro_test.exs
- lib/ex_unit/lib/ex_unit/assertions.ex
- lib/ex_unit/test/ex_unit/assertions_test.exs
> assert_receive should expand in match context

- lib/elixir/lib/calendar/date.ex
Ref https://github.com/elixir-lang/elixir/pull/6313#discussion_r152953013
> Change Date.range/2 to only accept dates

- lib/mix/lib/mix/tasks/xref.ex
- lib/mix/test/mix/tasks/xref_test.exs
The function will return a flat list of maps containing information on all the called functions.
Closes #6967
~~- [ ] Work out how to support Umbrella apps (?)~~
> Added public function `Mix.Tasks.Xref.calls/0` (#6967)

- lib/iex/lib/iex/helpers.ex
This is a small PR that just seems useful. Would appreciate a quick look. I'm not aware if there is an easier way to do this.
> add a ref function similar to pid, but for Reference types

- lib/elixir/lib/exception.ex
Provide an optional callback for exception: blame/2 that can be used to
augment the exceptions with some additional data that requires expensive
computation and shouldn't be done in every place, for example,
FunctionClauseError that will look up the clauses in the .beam file.
Closes #7074
> Make Exception.blame/3 extensible

- lib/elixir/src/elixir_def.erl
- lib/elixir/test/elixir/kernel/docs_test.exs
- lib/elixir/test/elixir/kernel/warning_test.exs
> Remove multiple clauses warning for default values on bodiless clause

- lib/elixir/lib/kernel.ex
- lib/elixir/lib/protocol.ex
Provides hex documentation requested by Issue #7019
> Add documentation for Protocol.derive

- lib/elixir/lib/enum.ex
- lib/elixir/lib/stream.ex
- lib/elixir/src/elixir_dispatch.erl
- lib/elixir/src/elixir_parser.yrl
Closes https://github.com/elixir-lang/elixir/issues/7135.
> Hard-deprecate some things for 1.7

- lib/elixir/lib/integer.ex
Relates in some way to: https://github.com/elixir-lang/elixir/pull/7187
> Simplify recursion

- lib/mix/lib/mix/tasks/format.ex
> Mix.Tasks.Format: Fix grammatical error

- .travis.yml
> Include OTP 20.2 in build matrix

- lib/elixir/lib/calendar/date_range.ex
> Hide format of Date.Range.first|last_in_iso_days types

- lib/mix/lib/mix/dep.ex
- lib/mix/lib/mix/project.ex
- lib/mix/lib/mix/project_stack.ex
- lib/mix/test/mix/dep_test.exs
> Add Mix.Dep.clear_cached/0

- lib/elixir/lib/supervisor.ex
> Re-add missing Supervisor behaviour

- lib/elixir/test/elixir/macro_test.exs
Fix two Macro.to_string tests that weren't really testing much.
> Fix two Macro.to_string tests

- .travis.yml
- Makefile
Hopefully this will reduce the amount of commits and pull requests with unformatted files.
> Check the Elixir codebase is formatted before running tests

- lib/elixir/lib/kernel/special_forms.ex
- lib/elixir/lib/macro/env.ex
- lib/elixir/src/elixir.hrl
- lib/elixir/src/elixir_clauses.erl
- lib/elixir/src/elixir_env.erl
- lib/elixir/src/elixir_erl_pass.erl
- lib/elixir/src/elixir_erl_try.erl
- lib/elixir/src/elixir_erl_var.erl
- lib/elixir/src/elixir_expand.erl
- lib/elixir/src/elixir_import.erl
- lib/elixir/test/elixir/kernel/errors_test.exs
- lib/elixir/test/elixir/kernel/raise_test.exs
This still needs probably more tests and additional docs, but I wanted to see if the approach for the implementation makes sense.
Closes #7097
> Introduce __STACKTRACE__

- lib/elixir/lib/uri.ex
> Clarify documentation for URI.to_string/1

- lib/mix/lib/mix/tasks/profile.eprof.ex
- lib/mix/test/mix/tasks/profile.eprof_test.exs
Closes #7292
CC @pdgonzalez872
> Fixed eprof to work with multiple processes

- lib/elixir/pages/Guards.md
[ci skip]
Closes  #7332
---
@ianrumford I'd love to hear, if you think this makes it clearer.
> Clarify behaviour of failing gaurds

- lib/elixir/lib/system.ex
Ref https://github.com/elixir-lang/elixir/pull/7336#issuecomment-364707581
> Use ISO8601 in System.build_info (2nd attempt)

- lib/elixir/pages/Typespecs.md
Addresses [#7339](https://github.com/elixir-lang/elixir/issues/7339)
> Doco error in typespecs #7339

- lib/elixir/lib/option_parser.ex
- lib/elixir/test/elixir/option_parser_test.exs
> Deprecate dynamic mode in OptionParser and promote strict

- lib/iex/lib/iex/introspection.ex
- lib/iex/test/iex/helpers_test.exs
> Show better error when h/1 is used on type

- lib/elixir/src/elixir_bitstring.erl
- lib/elixir/test/elixir/kernel/expansion_test.exs
> Handle nested bitstring pattern matching failures in a better way

- lib/elixir/pages/Typespecs.md
I found this page a little too abstract on first encounter. I thought a concrete example at the top would help newcomers.
> Add a simple, concrete @spec example

- README.md
Some tiny alterations to help make the intended meaning immediately clear.
> Rewording for ease of reading

- lib/elixir/lib/calendar/naive_datetime.ex
Hello everyone :) I'm beginner and i want to help the community, i followed that issue #7445, i hope i help a little.
> Updated NaiveDateTime moduledoc to use new/8.

- lib/elixir/pages/Operators.md
> coma is not an operator

- lib/elixir/lib/kernel.ex
- lib/elixir/lib/kernel/typespec.ex
- lib/elixir/lib/module.ex
- lib/elixir/src/elixir_def.erl
- lib/elixir/src/elixir_erl.erl
- lib/elixir/src/elixir_locals.erl
- lib/elixir/src/elixir_module.erl
- lib/elixir/src/elixir_overridable.erl
- lib/elixir/test/elixir/kernel/warning_test.exs
Right now we support the new API only for internal attributes.
External attributes are being added next.
> Move accumulate attributes to a separate table

- lib/logger/lib/logger.ex
- lib/logger/lib/logger/backends/console.ex
- lib/logger/lib/logger/formatter.ex
- lib/logger/lib/logger/utils.ex
- lib/logger/test/logger_test.exs
> Handle bad chardata lookalikes in Logger

- lib/elixir/src/elixir_erl.erl
- lib/elixir/src/elixir_module.erl
- lib/elixir/test/elixir/kernel/errors_test.exs
- lib/elixir/test/elixir/kernel/warning_test.exs
* error on undefined inlined functions
* warn on parse transforms
Closes #7409 
Addresses another part of #5800
> Validate @compile attribute in elixir

- lib/elixir/src/elixir_expand.erl
- lib/elixir/test/elixir/kernel/expansion_test.exs
> Improve error message for invalid clauses inside local functions

- lib/elixir/src/elixir_expand.erl
- lib/elixir/test/elixir/kernel/expansion_test.exs
> Improve error messages for lists concatenation operator

- lib/iex/lib/iex/pry.ex
Found a small typo here.. :smile:
> Fix typo in a handle_call comment in iex's pry.ex

- lib/elixir/lib/code/formatter.ex
Found a small typo in the formatter :smile:
> Fix typo in formatter

- lib/elixir/lib/function.ex
Sorry for the noise :sweat_smile: 
Offtopic:
Quick vim tips: `:set spell spelllang=en_gb`
> Fix function typos.

- lib/elixir/lib/function.ex
A bunch of improvements that I was late for making in https://github.com/elixir-lang/elixir/pull/7503 :).
Notable things:
* I removed the `Function.value/0` type. I think we should be conservative with types since then they're public API and since this type was just defined as `term/0`, I used `term` instead.
* Added some additional examples.
* Restructured docs a bit.
* Fixed the spec for `info/2` (which was defined as `info(fun)`) so that it is defined for `info/2` and so that it encodes the information that the passed item is returned as well.
> Improve documentation and specs in the Function module

- lib/elixir/lib/regex.ex
> Modify regex example output

- lib/elixir/lib/gen_server.ex
Hi all, just a couple of small typos.
Cheers!
> Fix typos in GenServer @moduledoc

- lib/elixir/lib/uri.ex
- lib/elixir/test/elixir/uri_test.exs
> Fix parsing of queries with just "?" in URI.parse/1

- lib/elixir/src/elixir_erl_for.erl
- lib/elixir/test/elixir/fixtures/dialyzer/for_bitstring.ex
- lib/elixir/test/elixir/kernel/dialyzer_test.exs
> Adds meta generated to for comprehension clauses with bitstrings

- lib/elixir/lib/kernel/typespec.ex
- lib/elixir/test/elixir/typespec_test.exs
> Fix typespecs for named records

- lib/elixir/lib/string.ex
- Improve specs to reflect that when limit is 0, it will return true,
and mention this in the docs.
- Add guards so it will fail when wrong types are give
> Improve String.printable?/2

- lib/elixir/src/elixir_tokenizer.erl
- lib/elixir/test/elixir/kernel/warning_test.exs
> Warn when a variable that ends in ! or ? is followed by = with no space

- CHANGELOG.md
- lib/elixir/pages/Compatibility and Deprecations.md
It could be ambiguous  whether it was soft or hard-deprecated
> Deprecation table: mention in table heading "Hard-deprecated in"

- lib/elixir/lib/string.ex
The new implementation is 10x to 150x faster on the benchmark data.
The full benchmark: https://gist.github.com/michalmuskala/b8dea400a9902356f5bc53c201161a05
> Optimise String.starts_with?/2

- lib/elixir/lib/enum.ex
- lib/elixir/lib/range.ex
- lib/elixir/test/elixir/range_test.exs
As opposed to `left..right` and `x..y`
> Use first..last in ranges

- lib/elixir/lib/application.ex
Update to match the wrapped functions: https://github.com/erlang/otp/blob/1526eaead833b3bdcd3555a12e2af62c359e7868/lib/kernel/src/application.erl#L269
> More precise started and loaded_applications typespec

- lib/elixir/lib/stream.ex
- lib/elixir/test/elixir/stream_test.exs
> Consider possible accumulator in Stream.do_zip_step/2

- lib/elixir/lib/option_parser.ex
Hi all,
just a space I found missing.
Cheers!
> Fix space in OptionParser docs

- lib/elixir/pages/Operators.md
Added reference to operators like in https://github.com/smorin/elixir/edit/master/lib/elixir/pages/Guards.md
> Added References to Operators

- lib/ex_unit/lib/ex_unit/callbacks.ex
- lib/ex_unit/lib/ex_unit/case.ex
- lib/ex_unit/lib/ex_unit/cli_formatter.ex
- lib/ex_unit/lib/ex_unit/runner.ex
- lib/ex_unit/test/ex_unit/doc_test_test.exs
> Change `:type` to `:test_type` and properly document

- lib/elixir/lib/code/formatter.ex
- lib/elixir/src/elixir_parser.yrl
- lib/elixir/test/elixir/code_formatter/comments_test.exs
- lib/elixir/test/elixir/code_formatter/general_test.exs
ref: https://github.com/elixir-lang/elixir/issues/7718
> [Formatter : anon_fun] When fn is followed by a newline, use multi-clause formatting style

- lib/logger/lib/logger.ex
- lib/logger/mix.exs
- lib/logger/test/logger_test.exs
> Add metadata based compile time logger purging

- lib/logger/lib/logger.ex
If-clauses in first conditional shouldn’t double up on the future “will”.
I double check with three native English speakes :)
> Correct grammar in Logger documentation

- lib/elixir/lib/gen_server.ex
Hi,
as I was going through the docs I may have spotted a typo.
> Typo in gen_server.ex comments

- lib/mix/lib/mix/tasks/new.ex
Updated with umbrella project example
> Updated with umbrella project example

- lib/mix/lib/mix.ex
Example of aliases calling tasks to show its capabilities
> Example: aliases tasks 2 show its capabilities

- lib/elixir/lib/kernel.ex
- lib/elixir/test/elixir/kernel/guard_test.exs
ref: https://github.com/elixir-lang/elixir/issues/7795
> [Kernel] add assert no guard

- lib/iex/lib/iex/helpers.ex
I think it would be nice to be able to force recompile right in the IEx during development.
> Allow force recompilation in IEx

- lib/elixir/lib/integer.ex
- lib/elixir/lib/kernel.ex
- lib/elixir/lib/list.ex
- lib/elixir/lib/map.ex
- lib/elixir/lib/tuple.ex
Where better to get feedback from than the source? As a relatively new user of Elixir (since v1.6) with a background in teaching methodology, here are a few suggestions to make the Hex documentation more helpful and intuitive for new users.
For context, see: 
* https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/elixir-lang-core/SAejGg2e-io/kpA_3qVVCAAJ
* https://elixirforum.com/t/discussion-incorporating-erlang-otp-21-map-guards-in-elixir/14816/39
PLEASE NOTE: These edits are meant as a starting point to confirm that the design decisions for the documentation--based on their merits--are viewed by the Elixir Core Team as steps in the right direction.
When this is hopefully confirmed (if you are unconvinced that my revisions will be helpful, let's discuss your …
> Beginner-friendly revisions to Elixir's documentation

- lib/mix/lib/mix/tasks/compile.all.ex
- lib/mix/test/mix/tasks/compile_test.exs
> Ensure Mix.Dep.cached() is set before compilation

- lib/mix/lib/mix/tasks/run.ex
Hi!
Thanks for making Elixir.
I really like this programming language ❤️ 
I found typo about `mix run` on `elixir 1.6`
I fixed it.
> fix document about mix run on elixir1.6

- lib/elixir/lib/code/formatter.ex
- lib/elixir/test/elixir/code_formatter/comments_test.exs
> Do not force single clause to be unfit

- lib/elixir/lib/kernel/typespec.ex
- lib/elixir/lib/module.ex
- lib/elixir/src/elixir_erl.erl
- lib/elixir/test/elixir/kernel/docs_test.exs
- lib/iex/lib/iex/autocomplete.ex
- lib/iex/lib/iex/introspection.ex
> Compile documentation metadata

- lib/elixir/lib/gen_server.ex
- lib/elixir/lib/option_parser.ex
- lib/elixir/lib/stream.ex
- lib/elixir/lib/string.ex
> Use garbage-collected as a single word

- lib/elixir/lib/kernel.ex
> Extended documentation for sigils

- CHANGELOG.md
- lib/elixir/lib/calendar.ex
- lib/elixir/lib/calendar/date.ex
- lib/elixir/lib/enum.ex
- lib/elixir/lib/kernel.ex
- lib/elixir/lib/macro.ex
- lib/elixir/lib/string.ex
- lib/mix/lib/mix.ex
- lib/mix/lib/mix/dep.ex
> Use backtick in "returns true" and "returns false" in docs

- lib/elixir/lib/kernel.ex
- lib/mix/lib/mix/tasks/compile.ex
- lib/mix/lib/mix/tasks/format.ex
- lib/mix/lib/mix/tasks/profile.eprof.ex
- lib/mix/lib/mix/tasks/xref.ex
> Use passive present tense

- CHANGELOG.md
Just a few minor details I saw while going through `CHANGELOG.md`.
> Microscopic edits in CHANGELOG.md

- lib/eex/test/eex_test.exs
- lib/elixir/lib/collectable.ex
- lib/elixir/lib/enum.ex
- lib/elixir/test/elixir/enum_test.exs
- lib/ex_unit/lib/ex_unit/assertions.ex
- lib/mix/lib/mix/compilers/elixir.ex
> Deprecate using non-empty lists with the Collectable protocol

- lib/elixir/lib/process.ex
I miss some examples in Process functions then i resolved to add ones. 
https://hexdocs.pm/elixir/Process.html#content
> Update Process documentation

- lib/ex_unit/lib/ex_unit/assertions.ex
Added some additional information as requested in the following [post](https://elixirforum.com/t/asserting-exit-logg-and-state-of-running-process/15148/2)
> Clarify how to assert on exits from linked processes.

- lib/elixir/lib/string_io.ex
> Added missing @doc :since metadata for StringIO.open/3

- lib/elixir/lib/module.ex
- lib/elixir/src/elixir_module.erl
- lib/elixir/test/elixir/kernel/errors_test.exs
This is an attempt to implement the check from #5800: `multiple_on_loads`: multiple `on_load` attributes.
I'm not sure if this is the right spot to perform the check :)
> Check duplicated @on_load attributes

- lib/mix/lib/mix/dep.ex
- lib/mix/test/mix/dep_test.exs
> Properly populate top_level field of deps

- lib/logger/lib/logger.ex
- lib/logger/test/logger_test.exs
> Optimize metadata merging and ensure no nil leakage

- lib/elixir/lib/module.ex
The current examples always returning false, and I thought that showing when it would return `true` would be helpful (and it matches `Module.defines?/2`) :)
I've also formatted a few examples in this module.
> Improve Module.defines?/3 examples

- lib/elixir/lib/kernel.ex
- lib/elixir/lib/macro.ex
- lib/elixir/lib/module.ex
- lib/elixir/src/elixir.hrl
- lib/elixir/src/elixir_bootstrap.erl
- lib/elixir/src/elixir_dispatch.erl
- lib/elixir/src/elixir_env.erl
- lib/elixir/src/elixir_erl.erl
- lib/elixir/src/elixir_erl_for.erl
- lib/elixir/src/elixir_erl_pass.erl
- lib/elixir/src/elixir_erl_try.erl
- lib/elixir/src/elixir_erl_var.erl
- lib/elixir/src/elixir_expand.erl
- lib/elixir/src/elixir_locals.erl
- lib/elixir/src/elixir_map.erl
- lib/elixir/src/elixir_module.erl
- lib/elixir/src/elixir_quote.erl
This is several loosely related changes to the compiler that either clean things up or improve performance. With all the changes, on some benchmarks the compiler performance improved about 5%.
> Improvements to the compiler

- lib/ex_unit/lib/ex_unit/assertions.ex
- lib/ex_unit/test/ex_unit/assertions_test.exs
> Consistently expand patterns and guards in assertions

- lib/elixir/lib/calendar/datetime.ex
The speed up comes from the fact we don't convert to and
from iso days for the date part in certain cases.
Discussed on #7986. /cc @dcuddeback.
> Speed up from_iso8601 when offset does not change days

- lib/mix/lib/mix/tasks/help.ex
- lib/mix/test/mix/tasks/help_test.exs
> mix help when theres a task and alias

- lib/elixir/src/elixir_expand.erl
- lib/elixir/test/elixir/kernel/expansion_test.exs
- lib/elixir/test/elixir/kernel/guard_test.exs
- lib/iex/test/iex/helpers_test.exs
Fixes #8023 
Let me know if you have any suggestions for improving the wording here.
> Change error message for calling missing function in a guard

- lib/elixir/lib/calendar/datetime.ex
- lib/elixir/test/elixir/calendar_test.exs
> Take negative years into account in DateTime

- lib/elixir/src/elixir_rewrite.erl
- lib/elixir/test/elixir/kernel/expansion_test.exs
Minor things I spotted while reading https://github.com/elixir-lang/elixir/pull/8043 :)
cc @michalmuskala
> Minor improvements in match operators code

- lib/elixir/test/elixir/kernel/errors_test.exs
> InvaliadStructFieldValue -> InvalidStructFieldValue

- lib/elixir/lib/task/supervisor.ex
Spotted while reading https://github.com/elixir-lang/elixir/pull/8060
> Fix typos in Task.Supervisor documentation

- lib/elixir/lib/process.ex
t:dest was between alive?/1 doc and spec :)
> Update Process docs

- lib/elixir/src/elixir_import.erl
> Fix arity of try/1 in :elixir_import.special_form

- lib/elixir/lib/process.ex
Hi all, 
just a double space fixed.
Cheers!
> Fix double space in Process @moduledoc

- lib/elixir/lib/calendar/date.ex
- lib/elixir/lib/calendar/naive_datetime.ex
- lib/elixir/lib/calendar/time.ex
- lib/elixir/lib/kernel.ex
- lib/elixir/lib/range.ex
I've limited myself to the `@type t :: %_{}` construction.
> Use __MODULE__ in `@type t` definitions

- lib/elixir/lib/inspect.ex
- lib/elixir/lib/kernel.ex
- lib/elixir/test/elixir/inspect_test.exs
> Allow Inspect protocol to be derivable with the only/except options

- lib/ex_unit/lib/ex_unit/runner.ex
Now the `:module_finished` message will include the results of the
finished tests.
Resolves #8112
> Update test module sent to formatters

- lib/elixir/lib/agent.ex
Minor tweaks I did while reading the source code of `Agent`:
* The sample code quoting `Mix.TasksServer` is out of sync. After some discussion, it has been replaced by a simple counter.
* The `Agent` API receives both anonymous functions and MFAs, the patch removes "anonymous" in a sentence of the introduction and refers more vaguely to _functions_.
* I believe functions are _called_ or _invoked_, but I wouldn't say a function is _executed_. You execute a _function call_, or a _callback_, though.
* Specifies that the function passed to `start_link/2` is invoked in the server process.
* Underlines that the value returned by the function passed to `start_link/2` is the _initial_ state of the agent.
> Minor tweaks to Agent docs

- lib/elixir/lib/version.ex
> Add Version.parse_requirement!/1

- lib/elixir/lib/kernel.ex
> Document that "else" can be used directly in function definitions

- lib/elixir/lib/kernel/typespec.ex
- lib/elixir/lib/port.ex
- lib/elixir/lib/process.ex
- lib/elixir/test/elixir/kernel/errors_test.exs
> Raise on invalid type annotation in typespecs
