lib/mix/lib/mix/tasks/new.ex
In 88be750a the `config_umbrella` template was changed to work on its own, not as an addendum to the config template. But the create_file call still concatenated them together, giving redundant text and two `use Mix.Config` calls (see below).
```
use Mix.Config
#
#
use Mix.Config
import_config "../apps/*/config/config.exs"
#
```
=> Mix new --umbrella: use only umbrella template for config.exs, not both umbrella and normal

lib/mix/lib/mix/tasks/compile.ex
The return value of Mix.compilers() is `[:yecc, :leex, :erlang, :elixir, :app]`
=> sync documentation with code

lib/elixir/lib/enum.ex
Also explain that the function won't reduce a one-element list.
=> Mention Enum.reduce/3 in Enum.reduce/2's documentation.

lib/ex_unit/lib/ex_unit/callbacks.ex
I stumbled across this describing the difference between `setup_all` and `setup`:
defmodule AssertionTest do
use ExUnit.Case, async: true
setup_all do
end
setup do
end
end
I think it is more clear if we take the phrasing from the `@moduledoc`here:
What do you think?
=> [ExUnit] Clarify example in Callback docs

lib/mix/lib/mix/rebar.ex, lib/mix/test/mix/rebar_test.exs
Rebar3 uses a slightly different style for specifying specific refs when
defining dependencies. http://www.rebar3.org/v3.0/docs/dependencies
=> Support rebar3 style git refs in rebar.config files

lib/elixir/lib/supervisor.ex
Supervisor uses Stack implementation where exists start_link/1 function but at the top of this documentation page there is no impelementation of that function so we have to make second parameter of start_link/2 function optional
=> Fix implementation of Stack module which doesn't fit to the Supervisor implementation

lib/elixir/lib/agent.ex
I was reading through the Agent docs and had a difficult time with the wording for lines 64-68. The changes seem to have a smoother flow and now the second sentence lines up with the order of the functions in the example. The remaining changes were small but also help with the readability. Also there was a missing "an".
=> Reword Agent docs for readability

lib/elixir/lib/gen_server.ex
The link was pointed to the mix introduction but the prior
paragraph says to check the GenServer tutorial in the Getting
Started guide. Also, some minor changes to the wording in the
preceding paragraph
=> Provide link to Elixir's GenServer tutorial page

lib/elixir/lib/gen_server.ex
It's my understanding that the valid return values for handle_cast are different from the ones for handle_call.
The Erlang docs are not very clear on that matter but I gathered that form multiple source across the web (i.e http://learnyousomeerlang.com/clients-and-servers). If that's incorrect I'd love to understand why.
I find the current format not very clear anyway as it's easy to miss the `handle_cast`, so I'd probably be in favour of re-arranging it if possible.
=> Split handle_call and handle_cast callbacks in GenServer docs

CONTRIBUTING.md, README.md, lib/elixir/lib/enum.ex, lib/elixir/lib/io/ansi.ex, lib/elixir/lib/kernel/special_forms.ex, lib/elixir/lib/list.ex, lib/elixir/lib/module.ex, lib/elixir/lib/node.ex, lib/elixir/lib/port.ex, lib/elixir/lib/string.ex, lib/elixir/test/elixir/io/ansi/docs_test.exs, lib/ex_unit/lib/ex_unit/doc_test.ex, lib/mix/lib/mix.ex, lib/mix/lib/mix/tasks/compile.leex.ex, lib/mix/lib/mix/tasks/compile.yecc.ex, man/elixir.1.in, man/elixirc.1, man/iex.1.in, man/mix.1
* update URL where the used http link redirects to https, and as well when a package is provided and the https link is available.
* remove period adjacent to URLs.
* standardize erlang.org/doc links to use www
* also update a wikipedia link that redirected to a different page ( https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Non-characters)
=> update url to use https. standardize erlang.org/doc links to use www

lib/elixir/lib/enum.ex, lib/elixir/lib/stream.ex, lib/elixir/test/elixir/enum_test.exs
variables renamed according to dicussion in https://github.com/elixir-lang/elixir/issues/3487
Defguard added for Enum.take_every(collection, 1)
More tests added, and sort of unified documentation between the two modules.
=> Enum & Stream, take/2 & take_every/2 variables renamed. +Improvements

lib/elixir/lib/enum.ex
as suggested by @lexmag in https://github.com/elixir-lang/elixir/pull/3489/files#r34588122
=> Enum.take_every/1: remove unnecesary Module reference

lib/elixir/lib/task.ex
Just thought I'd check how Elixir implemented monitoring for Task and noticed this in the documentation. This brings it in line with what I see in the code.
=> Clarify which call sets up the Task monitor

lib/mix/lib/mix/dep/lock.ex
Adds an explicit sort of the input map to Mix.Dep.Lock.write/1 since maps do not explicitly have an order.
@ericmj
=> Add explicit sort of map to Mix.Dep.Lock.write/1

CHANGELOG.md, lib/elixir/lib/enum.ex, lib/elixir/lib/inspect/algebra.ex, lib/elixir/test/elixir/enum_test.exs
as per discussed in the mailing list
Rename functions introduced in: https://github.com/elixir-lang/elixir/pull/2901, https://github.com/elixir-lang/elixir/pull/1047, https://github.com/elixir-lang/elixir/pull/1267
/cc @xavier, @manpages, @brunoro
=> rename Enum.minmax* and Inspect.Algebra.folddoc due to inconsitencies in their names

lib/elixir/lib/bitwise.ex
Having the `__using__/1` function listed, was imcompatible with the statement "These macros can be used in guards"
=> Bitwise module: remove @doc in __using__ and move it to @moduledoc

lib/ex_unit/lib/ex_unit/capture_io.ex, lib/ex_unit/lib/ex_unit/server.ex, lib/ex_unit/test/ex_unit/capture_io_test.exs
=> Fix re-registering of device after an exit signal in the `ExUnit.CaptureIO`

lib/logger/lib/logger.ex, lib/logger/lib/logger/backends/console.ex, lib/logger/test/logger/backends/console_test.exs, lib/logger/test/logger_test.exs
=> Improve Logger metadata handling

lib/mix/lib/mix/task.ex
I added a link to the documentation for the Mix module, in particular to the section that talks about aliasing.
=> Polish the documentation for Mix.Task.alias?/1

lib/elixir/lib/gen_server.ex
I'm an Elixir newbie and wanted to set up a cleanup for my supervised GenServer. However, it took me 2 hours to figure out, how to do this under a Supervisor and then another half hour to find the `Process.flag/2` method.
I'm not sure if the description is too long at this point but it would have saved me some time and wondering.
=> Better documentation for the GenServer terminate callback

lib/elixir/lib/io.ex
Please correct me if `IO.inspect` does not always return a string.
=> IO.inspect: @specs fixed, + see full options

lib/elixir/lib/inspect.ex
The docs for the Inspect protocol mentioned that if there's an error while inspecting a struct (for which the Inspect protocol has been implemented), then the struct is printed with a raw representation.
This PR makes it clear that an `ArgumentError` is raised and the struct is printed raw in the error message. I'm adding this note as I was bitten by this earlier today, thinking I could rely on `inspect/2` printing my struct as `%MyStruct{...}` in case of errors (I wanted to print it as `#MyStruct<...>` only for some cases).
On a related note, yes, I came to the conclusion that printing a struct differently based on its content is probably a bad idea. Nonetheless, maybe these changes in the docs make this clearer :)
=> Tweak the docs for the Inspect protocol

lib/elixir/lib/task.ex
Per the discussion here: https://groups.google.com/forum/#!topic/elixir-lang-talk/SZSSPaLBX0s
The example as it stands in the doc will cause an application to fail to start, as it will keep retrying a worker that promptly exits. This PR clarifies the options one might need to run such a task successfully.
=> Mention restart: :transient in Task moduledoc

lib/elixir/lib/enum.ex
I added a note that clarifies that `Enum.reduce/2` calls the reducer function `n - 1` times where `n` is the length of the enumerable. [This StackOverflow question](http://stackoverflow.com/questions/31836820/enum-reduce-2-doesnt-output-io/31837323#31837323) lead to this PR. Let me know what you think!
=> Add a note to the docs for Enum.reduce/2

lib/mix/lib/mix/dep/lock.ex
From
```
** (SyntaxError) nofile:9: syntax error before: ','
(elixir) lib/code.ex:168: Code.eval_string/3
...
```
to
```
** (SyntaxError) mix.lock:9: syntax error before: ','
(elixir) lib/code.ex:168: Code.eval_string/3
...
```
This kind of errors might happen in case of bad git conflict resolution.
On a slightly different note, I've spotted double output on master branch:
```
% mix deps
** (SyntaxError) mix.lock:9: syntax error before: ','
(elixir) lib/code.ex:168: Code.eval_string/3
(mix) lib/mix/dep/lock.ex:65: Mix.Dep.Lock.read/0
(mix) lib/mix/tasks/deps.ex:110: Mix.Tasks.Deps.run/1
(mix) lib/mix/cli.ex:60: Mix.CLI.run_task/2
22:03:02.042 [error] Process #PID<0.47.0> raised an exception
** (SyntaxError) mix.lock:9: syntax error before: ','
(elixir) src/elixir.erl:156: :elixir.eval/3 …
```
=> Improve error message in case of lockfile eval failure

lib/ex_unit/lib/ex_unit/doc_test.ex
I mentioned that you can write an expression without a result if you don't want to assert on the value of that expression:
iex> pid = spawn fn -> :ok end
iex> is_pid pid
true
I also killed some trailing whitespace in the same file (sorry, I guess it has to be done at some point :P). Let me know what you think!
=> Mention expressions without results in doctests

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
Github issue #3483
Simple enough - added a clause to the `pipe` function that matches a binary operator with 2 arguments and raises an error
(I'm new so I welcome suggestions & criticism of all kinds)
=> Raise if piping into binary operator with 2 args already

lib/ex_unit/lib/ex_unit/assertions.ex, lib/ex_unit/lib/ex_unit/doc_test.ex, lib/ex_unit/test/ex_unit/assertions_test.exs, lib/ex_unit/test/ex_unit/doc_test_test.exs
After the discussion on #3555, I felt I need some easier to review code as examples.
This changes address both my initial issue on #3555 with doctest not providing much help in diagnosing runtime errors as well as @fishcakez concern on a similar issue for `assert_raise` (in two separate commits).
The code implements my solution of preserving the original stacktrace, since the error messages already preserve the original `Exception` and `message`. Both cases are resolved in a similar way, but there is no code reuse between them. 
Feel free to provide feedback on the code and general approach. I've been with Elixir for about 2 weeks, so it is quite possible that I am missing things both at the high and low level :-)
=> Provide more information on the cause of exceptions (problems discussed in #3555)

lib/mix/lib/mix/tasks/profile.fprof.ex, lib/mix/test/mix/tasks/profile.fprof_test.exs
Based on the discussion [on the mailing list](https://groups.google.com/d/msg/elixir-lang-talk/IBTHFO_EC7A/48QccC4Q4jMJ) and further discussion on irc channel.
There's one known documentation issue I wasn't able to resolve (I'll add a note in the commit), but hopefully the pull's at least in the ballpark :-)
=> profile.fprof mix task

lib/ex_unit/lib/ex_unit.ex, lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/lib/ex_unit/runner.ex, lib/ex_unit/mix.exs
Follow up to https://github.com/elixir-lang/elixir/pull/3390#issuecomment-129831660
I've made it into a separate ExUnit configuration because I couldn't think of any other use cases for default tags, except for setting the `timeout` tag, but that's already a separate ExUnit configuration. If you want configurable default tags instead I'll change it.
/cc @josevalim
=> Introduce :capture_log ExUnit configuration.

lib/mix/lib/mix/tasks/test.ex
It helps in the following situation, for example:
`mix test run --no-start` or `mix test test/my_app_test.ex` (note `s` is missing)
I think we could list files given after the task name as well.
=> Raise an error if there are no files available to run test

lib/elixir/lib/kernel/special_forms.ex
Noticed this behaviour, found issue #482 stating it was intentional, decided to document it.
=> Added a blub about underscore names to the `import` documentation

lib/elixir/lib/file.ex, lib/elixir/lib/float.ex, lib/elixir/lib/gen_server.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/option_parser.ex, lib/elixir/lib/regex.ex, lib/mix/lib/mix/task.ex
Closes: https://github.com/elixir-lang/ex_doc/issues/283
also [reported to earmark](https://github.com/pragdave/earmark/issues/27)
The following commands were used to find the buggy strings:
`ag "[\r\n]\ {4}\[*-]([^\r\n]+[\r\n])+\ {7,}"`
`ag "[\r\n]\ {4}[-*]([^\r\n]+[\r\n])(\ {4,}[^\r\n]+[\r\n])+\ {7,}"`
=> Fix indentention inside lists

lib/elixir/lib/file.ex
In fact IO.gets always returns a line ended by a LF symbol in such the cases. So we have to take this into account when comparing user input with a target string.
=> Fix doc comment for File.cp_r

lib/elixir/lib/behaviour.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/kernel/typespec.ex, lib/elixir/lib/module.ex, lib/elixir/src/elixir_module.erl, lib/elixir/test/elixir/kernel/docs_test.exs, lib/elixir/test/elixir/kernel/typespec_test.exs
Implements (at least part of!) #3465.
* Updates existing `@callback` attr to attach `@doc` and raise on invalid use of defaults in typespec
* Adds new `@macrocallback` attr, which can be used to define behaviour macro callbacks. Also supports `@doc` and raise on invalid use of defaults in typespec
* Refactors `Behaviour` as a thin layer above the "new" `@callback` and `@macrocallback` attrs
* Adds `Kernel.Typespec.beam_callbackdocs/1`, which returns all callback docs from the given module's beam code.
=> @callback can now be used directly (without Behaviour). Add @macrocallback.

lib/elixir/test/elixir/kernel/warning_test.exs
This was the warning:
> test/elixir/kernel/warning_test.exs:55: warning: variable message is unused
=> Fix warning in warning_test.exs

lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/kernel/binary_test.exs, lib/elixir/test/elixir/kernel/char_list_test.exs, lib/elixir/test/elixir/kernel/errors_test.exs
issue #3503
This will raise:
```elixir
foo = """
this """
```
This will not:
```elixir
foo = """
this \"\"\"
"""
```
=> Raise if heredic terminator in invalid location

lib/elixir/lib/kernel/typespec.ex, lib/elixir/test/elixir/kernel/typespec_test.exs
Addresses #3598 
Since assignments (and everything else) are just application, I had to change a test that previously returned a generic error that was now returning the more specific error. Not sure if this should still be done or not due to that, but here's the code if people think it's a good idea having seen the impact of the change.
=> Improve error message when no return value specified in func spec

lib/ex_unit/lib/ex_unit/assertions.ex, lib/ex_unit/test/ex_unit/assertions_test.exs
Follow-up to https://github.com/elixir-lang/elixir/issues/3488#issuecomment-133423879.
=> Improve error messages for `match?` assertions

lib/elixir/lib/kernel.ex, lib/elixir/lib/kernel/typespec.ex, lib/elixir/lib/module.ex, lib/elixir/src/elixir_module.erl, lib/ex_unit/lib/ex_unit/doc_test.ex, lib/ex_unit/test/ex_unit/doc_test_test.exs
Note that this will change line numbers `Code.get_docs` returns for `:docs` and `:moduledoc` sections.
=> Line numbers for doctest errors. Fixes issue #3592

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel_test.exs
`Kernel.if` and `Kernel.unless` are now only valid if there is exactly
one `do` key and optionally an `else` key.
Any calls to the if macro that do not satisfy these conditions raise an
ArgumentError with a relevant error message.
This closes #3614 and is an alternative to #3615
=> fix(Kernel): check arguments on if and unless

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel_test.exs, lib/logger/lib/logger.ex, lib/logger/lib/logger/formatter.ex, lib/logger/test/logger/backends/console_test.exs, lib/logger/test/logger_test.exs
And do not inject `:application` key in metadata if it has `nil` value.
=> Cut off "Elixir." prefix for modules in Logger metadata

lib/ex_unit/test/ex_unit/assertions_test.exs
removes the following warnings:
- test/ex_unit/assertions_test.exs:218: warning: variable x is unused
- test/ex_unit/assertions_test.exs:229: warning: variable x is unused
=> ExUnit: Fix warning in test

lib/elixir/lib/option_parser.ex
While reading the docs for the [OptionParser.parse/2 function](http://elixir-lang.org/docs/v1.0/elixir/OptionParser.html#parse/2) I found that no code examples was given for the :keep switch. So I thought to write an example and open this pr.
Let me know if something is missing. The test suite is green.
=> add docs for :keep option in OptionParser module

lib/elixir/lib/list.ex
The delete_at code sample has an "iex" missing the ">" right afterwards . Wasn't sure if that might throw off some doctests or not, so better to be safe than sorry.
=> Add missing character in delete_at code sample

.travis.yml
Minor travis tweak to support newer versions of erlang including 17.5, 17.5.3 and 18.0
Here is where I located the latest versions
https://packages.erlang-solutions.com/erlang/
=> Upgrade travis to check against Erlang 17.5 and 18.0

lib/elixir/lib/file.ex
When working on f/File.rename, noticed what I think is a small documentation typo.
I renamed "tmp" to "b.txt" to avoid confusion with "/tmp"
Here's the tests I did to manually ensure I had it the right way around.
```
iex(1)> File.cp_r "/tmp/aha/one/a.txt", "/tmp/aha/two"
{:error, :eisdir, "/tmp/aha/one/a.txt"}
iex(2)> File.cp_r "/tmp/aha/one/a.txt", "/tmp/aha/two/b.txt"
{:ok, ["/tmp/aha/two/b.txt"]}
```
=> Fix type in File.cp_r when files involed (renamed tmp to b.txt)

lib/elixir/lib/regex.ex
Functions with unnamed arguments: When not giving a variable with a name, the parser will choose the name: "arg1" , "arg2", etc. This command will search for the ex_doc generated documentation.
`ag "(?<=signature\"><strong>).*\W(arg|atom|binary|bool|float|int|list)\d+.*\)" ./doc`
=> Regex.regex?/1: name unnamed argument and improve docs

lib/elixir/lib/gen_server.ex, lib/elixir/lib/io.ex, lib/elixir/lib/option_parser.ex, lib/elixir/lib/string.ex, lib/elixir/lib/supervisor.ex, lib/ex_unit/lib/ex_unit/assertions.ex, lib/mix/lib/mix/dep/loader.ex, lib/mix/lib/mix/tasks/archive.install.ex, lib/mix/lib/mix/utils.ex, lib/mix/test/mix/dep_test.exs, lib/mix/test/mix/scm_test.exs
Run the following command, and reviewed the occurences one by one.
```sh
ag -i '\ban?\s+[aeiou]\w+\b'
ag '\ban?\s+[BCDFGHJKLMNPQRSTVWXYZ][A-Z]+\b'
ag -i '\ban?\s+[aeiou]\w+\b'
```
=> Correct indefinite article a/an

lib/eex/lib/eex.ex, lib/mix/lib/mix/dep/converger.ex, lib/mix/lib/mix/tasks/new.ex
Solves a bug in the docs, http://elixir-lang.org/docs/master/eex/EEx.html
search for "special- case"
For the ones in the documentation, a space will be added in after the hyphen.
Just for consistency and to ease detection, I have replaced the ones in
comments as well.
Command to detect these lines:
ag "\w+-\n"
=> Avoid splitting words that use hyphen

lib/elixir/lib/kernel.ex, lib/elixir/unicode/unicode.ex, lib/ex_unit/test/ex_unit/callbacks_test.exs, lib/mix/lib/mix/compilers/erlang.ex, lib/mix/lib/mix/dep/converger.ex, lib/mix/lib/mix/shell/process.ex, lib/mix/lib/mix/tasks/deps.clean.ex, lib/mix/test/mix/tasks/deps_test.exs
Kernel.raise messages should not start with uppercase, and should not
have trailing punctuation.
Mix.raise messages should start with uppercase, and should not have a trailing
puntuation.
ag '(?<!Mix\.)raise\s+\"+(?!([A-Z]+\b))[A-Z]'
ag 'Mix\.raise\s+\"(?!(mix|rebar))+[a-z]'
ag "raise\s+\"+.+\.\"\s*\n"
=> Format raise message consistently

lib/ex_unit/lib/ex_unit.ex
=> spelling `miliseconds` -> `milliseconds`

lib/elixir/lib/kernel/special_forms.ex
From `variables defined in the macro does not affect` to `variables defined in the macro do not affect`
=> Fix `does` → `do` verbal agreement in special_forms.ex

CONTRIBUTING.md, README.md
Corrects the indentation,
and change `bash` code blocks  to a more generic one: `sh`
actually, github doesn't show colors with bash but does now with sh
=> Fix markdown files

CONTRIBUTING.md, lib/elixir/lib/application.ex, lib/elixir/lib/code.ex, lib/elixir/lib/file.ex, lib/elixir/lib/gen_event.ex, lib/elixir/lib/gen_server.ex, lib/elixir/lib/kernel/typespec.ex, lib/elixir/lib/list.ex, lib/elixir/lib/module.ex, lib/elixir/lib/node.ex, lib/elixir/lib/port.ex, lib/elixir/lib/process.ex, lib/elixir/lib/regex.ex, lib/elixir/lib/string.ex, lib/elixir/lib/system.ex, lib/mix/lib/mix/tasks/compile.erlang.ex, lib/mix/lib/mix/tasks/compile.leex.ex, lib/mix/lib/mix/tasks/compile.yecc.ex
This commits covers 100% of all links in the documentation,
using a words to describe what the page is about.
It users the `:module.function/arity` format for erlang functions that
link to the earlang docs.
I also changed some of the sentnces using the link from
- See [:erlang.function/2](http://...) for a list of available options.
to
- For a list of available options, see [:erlang.function/2](http://...)
The reasoning behind is that I think it's better to have an link at the end of the sentence
and not in the middle, so the reades doesn't need to finish the sentence to know what is it about and go back
and find the link. This way all the information is given before the link, so the users stops reading and can
click directly.
=> Add text to all links

lib/elixir/lib/macro.ex, lib/mix/lib/mix/tasks/deps.ex, lib/mix/lib/mix/utils.ex
Corrects a few more cases that were not caught by the previous PR
https://github.com/elixir-lang/elixir/pull/3682
Command:
ignore_words="a|an|the|in|exception|helper|callback|front-end|same|when|where|what|functionality|elixir|erlang|eex|iex|logger|environment|module|similar|\w+-like|opposite|boolean|current|information|basic|public|if|unless|otherwise|regular|internal|convenience|given|welcome to|shortcut to|writable|user|system|low-level|pipe operator|supervisor|administrator"
ag "(@(module|short)?doc)\s+(~[Ss])?([\"']{3})(\r|\n|.)\s*+((?!((?i)${ignore_words}(?-i)))[\w'-]+)(?<!(s))(?<!(ed))(?<!(ity))(?<!(ally))(?<!(ily))(?<!(ely))(?=[\s\r\n,:.])"
=> Correct descriptions in docs to use Present Continuous (2)

CHANGELOG.md, CONTRIBUTING.md, README.md, bin/elixir, bin/elixirc.bat, bin/iex, lib/elixir/lib/kernel/cli.ex, lib/elixir/lib/system.ex, lib/elixir/test/elixir/file_test.exs, lib/ex_unit/lib/ex_unit/doc_test.ex, lib/iex/lib/iex.ex, lib/iex/lib/iex/cli.ex, lib/iex/lib/iex/helpers.ex, lib/logger/lib/logger.ex, lib/mix/lib/mix/dep.ex, lib/mix/lib/mix/tasks/app.start.ex, lib/mix/lib/mix/tasks/compile.elixir.ex, lib/mix/lib/mix/tasks/escript.build.ex, lib/mix/lib/mix/tasks/loadpaths.ex, lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/tasks/deps_test.exs
It includes Erlang, Elixir, ExUnit, ExDoc, Logger, IEx, elixirc
It leaves Mix for a different PR.
Command to spot these words:
ag -s '(?<!(\`))(?<!(\.))(?<!(/))(?<!(:))(?<!(_))(erlang|elixir|eex|iex|ex_unit|ex_doc|logger|elixirc)(?!(:))(?!(\?))(?!(_))(?!(-))(?!(\.))(?!(\`))(?!(/))(?!(>))' \
--ignore "*.erl" --ignore "*.yrl" --ignore "*.src"
=> Use Title Case and backticks for Erlang and Elixir applications

lib/elixir/lib/inspect/algebra.ex
This is because in the modules summary, [0] won't be intepreted as a link,
original reported: https://github.com/elixir-lang/ex_doc/issues/347
=> Inspect.Algebra: Replace numbered link in summary with actual link

lib/mix/lib/mix/cli.ex, lib/mix/test/mix/cli_test.exs
This should be a fix for #3715, but I have a feeling that building the exception with `Mix.NoTaskError.exception/2` is a hack at best. If I do `Mix.raise Mix.NoTaskError, task: task`, however, the error message turns out to be
```
** (Mix.NoTaskError) ...
```
instead of
```
** (Mix) ...
```
which is what something like `mix non_existing_task` raises.
=> Raise right away for Mix tasks with slashes

lib/mix/lib/mix/task.ex
You have to write a `@moduledoc` in order to show some documentation when users do `mix help my_task`.
=> Mention how to write docs for public Mix tasks

lib/elixir/lib/float.ex, lib/elixir/test/elixir/float_test.exs
New version can parse "+digit" like "+1.0, and supports E as exponent markter as well as e. + after the exponent marker is legitimate too.
So, Float.parse("+1.0E+2x") returns {100.0, "x"} now.
=> made Float.parse() support complete scientific notation

lib/elixir/lib/process.ex, lib/elixir/test/elixir/process_test.exs
I was working on adding `regs()` helper to IEx and realised passing multiple items to `Process.info/2` wasn't available in Elixir.
There might be a good reason why it's not here in the first place but I figured it would be fairly quick to add so I might as well do it.
I'm not sure the typespec is correct, do I need to define a special type for `{atom, term}` and then use it in place of `{atom | term} | [{atom, term}]` ?
=> Allow list of spec in Process.info/2

lib/mix/lib/mix/dep.ex, lib/mix/test/mix/tasks/deps.git_test.exs, lib/mix/test/mix/tasks/deps_test.exs
Fixes additional issue found in https://github.com/elixir-lang/elixir/issues/3038#issuecomment-139882118
=> Mix.Dep: show instructions on :nolock and :lockoutdated

lib/mix/lib/mix.ex, lib/mix/lib/mix/shell/process.ex
I had some trouble with these docs, especially `Mix.Shell.Process`, and had to reach for the source code. I tried making docs clearer and more verbose :) Let me know if it's all good!
=> Polish docs for Mix.shell and Mix.Shell.Process

lib/elixir/lib/regex.ex, lib/elixir/lib/string.ex
While the docs do in fact explain that you can use \\g{n}, there is no examples using it. If you are like me, who starts off with the examples, this might easily be missed, so i added a example in Regex.replace/4, and modified one in String.replace/4. :smiley: 
Hopefully this is useful.
=> Doc: add examples using alternate capture/replace syntax, in replace/4

lib/elixir/lib/module.ex
The link :erlang.module_info/0 doens't have an entry in the erlang docs.
And I found the correct link to the reference manual, (the previous one was removed bc it
was outdated)
=> Module.__info__ : correct links

lib/elixir/lib/string.ex
As they were rarely used in the String module.
=> String: Rename args "str" to "string"

lib/elixir/lib/code.ex
I was getting a really long cyptic message showing the whole list of docs, but for a private function,
```
** (FunctionClauseError) no function clause matching in Code.do_lookup_docs/2
(elixir) lib/code.ex:634: Code.do_lookup_docs([docs: [{{:%, 2}, 105, :defmacro, [{:struct, [], nil}, {:map, [], nil}], "Creates a struct.\n\nA struct is a tagged map that allows developers to provide\ndefault values for keys, tags to be used in polymorphic\ndispatches and compile time assertions.\n\nTo define a 
```
It also add :all as the default value for kind
=> Code.get_docs/2: check for valid kinds in public function + set :all as default value for kind

lib/iex/lib/iex/helpers.ex
Because this is asked in the mailing list every other week,
I have decided to take a stab at it.
I went with the more conservative approach of always restarting
the application so users don't see errors from their processes.
There are a bunch of disclaimers to consider which have been
documented. For this reason, the helper has been marked as
experimental so we see how often folks will run into corner cases.
@ericmj, @fishcakez and @alco: careful review and feedback is
appreciated. I was also torn between calling it restart and recompile
but went with the latter as the need for restarting is a side-effect
of compilation.
Thoughts?
=> Add Mix recompilation from IEx

lib/elixir/lib/dict.ex
Since `Dict.into_list(Enum.into(list, dict_impl.new)) == list`, I used Dict.put to build the dict.
=> Add example to the to_list function

lib/elixir/lib/io/ansi.ex
My use case: printing a progress bar type thing where sometimes, the just-printed line is shorter than the previous one. Then you first need to clear out the line, or the old line shows through.
Worked around this with `"\e[2K"` but it would be nice to have this built in.
http://ascii-table.com/ansi-escape-sequences-vt-100.php
=> Add IO.ANSI.clear_line

lib/ex_unit/lib/ex_unit/assertions.ex
This patch documents the fact that assert_raise()
can also accept a Regex as the expected message.
=> assert_raise: document that message can be regex

lib/elixir/src/elixir_exp_clauses.erl, lib/elixir/test/elixir/kernel/expansion_test.exs
There are good showcases for it:
```elixir
defmodule Qwe do
def main(val) do
try do
1 / val
rescue
ArgumentError ->
24
rescue
ArithmeticError ->
42
after
IO.puts "1"
after
IO.puts "2"
end
end
end
defmodule Asd do
def main() do
receive do
any -> any
after 50 ->
24
after 0 ->
42
end
end
end
```
Prior this patch duplicated clauses are simply ignored.
There is no practical reason to support this cases and thus `CompileError` will be raised.
=> Raise `CompileError` in case of duplicated clauses given for `try` and `receive`

lib/elixir/lib/kernel.ex, lib/elixir/src/elixir_exp.erl, lib/elixir/src/elixir_parser.yrl, lib/elixir/test/elixir/kernel/alias_test.exs, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/kernel/import_test.exs, lib/elixir/test/elixir/kernel_test.exs
Closes #3646.
```elixir
defmodule MultiAlias1 do
alias List.{Chars}
end
```
multiline:
```elixir
defmodule MultiAlias2 do
alias Mix.{
CLI,
Shell.IO
}
end
```
just random place:
```elixir
[List.{Chars}, 1]
** (UndefinedFunctionError) undefined function: List.{}/1
(elixir) List.{}(Chars)
```
invalid identifier:
```elixir
defmodule MultiAlias1 do
alias List.{Chars, 42}
end
** (SyntaxError) iex:2: syntax error before: '}'
```
There are a couple of open questions:
* do we need to support trailing comma, e.g.: `macro List.{Chars,}`
* do we need to support blank import (alias, etc.), e.g.: `macro List.{}`
@josevalim, I would like any feedback on it.
=> Introduce support for Mod.{A, B, C} on imports, alias, require and use

lib/elixir/lib/kernel/special_forms.ex
```
iex(7)> map = %{:a => 1, 2 => :b}
%{2 => :b, :a => 1}
iex(8)> %{map | :c => 3}
** (KeyError) key :c not found in: %{2 => :b, :a => 1}
```
=> Update a map for non existent key will raise a KeyError, not ArgumentError

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
this removes the spaces between the ranges and the periods
before:
iex> Macro.to_string(quote do: 1 .. 2 ) 
"1 .. 2"
now:
iex> Macro.to_string(quote do: 1 .. 2 ) 
"1..2"
consistent with Inspect
iex> inspect(1..2)   
"1..2"
=> Fix Macro.to_string/2 to print ranges

README.md
This just tripped me up.  If you follow the instructions above for building elixir itself, you're already *in* the elixir directory, so ex_doc gets cloned inside it, which arguably _is_ what "containing folder" means... but then the paths don't work.
Looks like ex_doc needs to be alongside / in a sibling folder / to have the same parent, for it to work.
Also mention where to look for the results.
=> Clarify instructions for building the docs

lib/elixir/lib/kernel.ex, lib/elixir/lib/range.ex, lib/elixir/test/elixir/range_test.exs
- checks for lists when defining range
- replace (left .. right) with (first .. last) in error messages
to use the same terminology used in the function definition
- add guards to Range.new/2
- add specs to Range.range?/1
- test added to check for lists in range.
=> Fix Range validation

lib/elixir/lib/application.ex
I was confused by this section. Mix does have a config.exs file and wondered and so i believe this paragraph is outdated documentation.
=> Configuration file now supported

lib/elixir/lib/gen_event.ex
I think as the documentation is generated from the type spec that this is the only reference that needs removing
=> removed obsolete type option from the GenEvent handler type

lib/elixir/lib/enum.ex
- Updates the terminology: what it was refereed as `collection` is now `enumerable` and `collectable`
- text wrap to 72 chars
- backticks added to `enumerable` and other variables.
- specs fixed
- Summaries improved
- try to avoid the use of what it returns in the summary. 
- documentation for several functions corrected and improved, as well as examples.
- some variables in functions renamed.
- I have changed the use of `value` when it actually refered to elements in the Enumerable to `element`, but i had kept it when it was used for tuples, refering to `key - value`, even though value could be an enumerable.
=> Enum: several fixes

lib/elixir/lib/enum.ex
this is the second part of changes introduced in commit ced1095e177c71b4022c1dc1cd209673b2f872d0
this one does:
- rename collection with enumerable.
- line wrapping so the whole file (with the exceptions of the docs examples) fit in 72 chars.
------
second part of https://github.com/elixir-lang/elixir/pull/3792
which I didn't include originally to reduce the size of the commit..
=> Enum: corrections in  private functions

lib/elixir/lib/enum.ex
Disclaimer: I have no idea what I'm doing when it comes to Elixir.
But! Today I ran `Enum.shuffle` without first running `:random.seed` and it shuffled an array correctly a couple of times, _not_ returning the same value each time.
```
iex(1)> list = [1,2,3,4,5]
[1, 2, 3, 4, 5]
iex(2)> Enum.shuffle(list)
[3, 2, 4, 1, 5]
iex(3)> Enum.shuffle(list)
[2, 3, 1, 5, 4]
iex(4)> Enum.shuffle(list)
[3, 5, 2, 4, 1]
```
So... I don't think we need to run `:random.seed()` here? I'm quite happy to be proven wrong here and learn something from the experience!
=> Add demonstration for Enum.shuffle's randomness

lib/elixir/lib/enum.ex
When writing an article about lists I ventured into implementing couple of the core list functions myself. I was surprised when I discovered that the current implementation of `Enum.map/2` is not optimal.
I came up with 3 options:
* using for comprehensions (currently used)
* using explicit recursion with accumulator
* using simple consing
The third option seems to be the fastest. That's also the one that is used by `:lists.map/2`
Tested implementations:
```elixir
def map_cons([head | tail], fun), do: [fun.(head) | map_cons(tail, fun)]
def map_cons([], _fun), do: []
def map_recurse(list, fun, acc \\ [])
def map_recurse([head | tail], fun, acc), do: map_recurse(tail, fun, [fun.(head) | acc])
def map_recurse([], _fun, acc), do: :lists.reverse(acc)
def map_for(list, fun), do: for i <- list, …
```
=> Optimize Enum.map/2 for lists

lib/elixir/lib/keyword.ex
The timings for 200 elements enumerable:
```
new:      100000   73.76 µs/op
old:       10000   1085.19 µs/op
```
Apparently, [`:lists.foldr`](https://github.com/elixir-lang/elixir/pull/3218#discussion_r27350819) didn't go well for us last time, that's why `foldl` was used at first place and this time.
=> Optimize `Keyword.new/2` function

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel_test.exs
I was stuck with an unhelpful error this morning. It was unhelpful because I was passing a variable that clearly referred to an atom. I realise now that this is due to it working at compile time but I only realised because the error message for require was much more helpful
**use error**
> (ArgumentError) invalid arguments for use, expected an atom or alias as argument
**require error**
(CompileError) meta.exs:2: invalid argument for require, expected a compile time atom or alias, got: 42
This pull request makes the use error also ask for a compile time atom, instead of just an atom.
=> Informative error message when passing a non atom value to use

lib/elixir/lib/supervisor.ex
The first three commits are just me reverting and resyncing to upstream master.  The fourth is the single letter change to the Supervisor doc.
=> Fixed typo/grammar in Supervisor @doc

lib/elixir/lib/protocol.ex, lib/elixir/lib/uri.ex, lib/elixir/test/elixir/stream_test.exs
Disclosure: working on a comprehensive style guide.
=> Omit `else` option in `if` and `unless` clauses if it returns `nil`

lib/iex/lib/iex.ex, lib/iex/lib/iex/config.ex
Would be nice to be able to change the column width in the `.iex.exs` file to allow for custom width output of documentation. This PR should allow that customization while still falling back to `:io.columns` when the terminal window is smaller.
=> Add IEx width option for larger terminal screens.

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
My proposal is the following:
```elixir
Macro.traverse(ast, accumulator, pre_function, post_function)
```
The specification almost is same as `Macro.prewalk/3` and `Macro.postwalk/3`, difference is that `Macro.traverse` is received both pre/post-order functions as arguments.
The third argument `pre_function` specification is same as `Macro.prewalk/3`'s third argument.
The forth argument `post_function` specification is same as `Macro.postwalk/3`'s third argument.
```iex
iex(1)> Macro.traverse(quote(do: :foo), 0,
...(1)>   fn (ast, acc) -> IO.puts "#{acc} pre"; IO.inspect ast; {ast, acc + 1} end,
...(1)>   fn (ast, acc) -> IO.puts "#{acc} post"; IO.inspect ast; {ast, acc - 1} end)
0 pre
:foo
1 post
:foo
{:foo, 0}
```
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic …
=> Add `Macro.traverse/4` pre/post-order traversal at the same time

README.md
most IRC clients don't seem to support irc://, obviously not the command-line ones. additionally, GitHub doesn't consider irc:// a hyperlink so that's less useful but it does hyperlink this (and we're on freenode)
=> change irc:// URI to freenode's webchat

lib/elixir/lib/kernel/typespec.ex
Updates the `Kernel.Typespec` moduledoc to include `as_boolean/1` in the built-ins list.
Not 100% sure the definition is correct, if it is, then this closes #3788.
=> List `as_boolean/1` under `Kernel.Typespec` built-ins.

lib/elixir/lib/module.ex
Most of these docs are from the 1.0 Behaviour module docs, but
those were seemingly lost at some point during the switch to
@callback. I'm not sure whether it is better to put them on
@behaviour or @callback, but I placed them on @behaviour. I'd
rather see a "Behaviour" page that has this information, not
just something randomly stuck in Module or Kernel.Typespec.
If it should be its own page, can you show me how to add new
pages to the Elixir documentation?
=> Transplant Behaviour module docs to @behaviour

lib/elixir/lib/kernel.ex, lib/iex/test/iex/helpers_test.exs
Following the discussions on
https://groups.google.com/forum/?fromgroups=#!topic/elixir-lang-core/bP_cJFFls84
This PR introduces a default `@doc` for delegated methods
```elixir
defmodule Delegator do
defdelegate func1, to: Delegated
@doc "Delegator func2 doc"
defdelegate func2, to: Delegated
end
defmodule Delegated do
def func1, do: 1
def func2, do: 2
end
```
If you don't define docs in the delegator, you get a pointer to the implementation
```elixir
iex> h Delegator.func1
See Delegated.func1/0
```
If you define docs, you get that
```elixir
iex> h Delegator.func2
Delegator func2 doc
```
Thanks @josevalim and @mgwidmann for the pointers, and the amazing community :+1:
=> Add default docs for delegate methods

lib/iex/lib/iex/introspection.ex, lib/iex/test/iex/helpers_test.exs
This is for issue #3830 and a first attempt at displaying the type documentation with the `t` helper. It currently works for `t/1` and prints the module name after each type so I'm not sure if that's desired.
Looking for feedback on whether the direction I'm headed is correct. Thanks!
=> Display docs for types with t/1

lib/elixir/lib/float.ex, lib/elixir/test/elixir/float_test.exs
This PR clarifies the documentation for `Float.parse/1` and adds test assertions to demonstrate the limits enforced by erlang/IEEE 754-1985 double precision floats. See #3862 for more context. /cc @josevalim
=> Document limits of `Float.parse/1`.

lib/elixir/lib/kernel.ex, lib/elixir/lib/module.ex
Attributes such as `@doc` and `@moduledoc` should emit warnings when they
are redefined. For example:
```elixir
@doc "first"
@doc "second"
```
This should emit a warning to the user, because the doc tag will be
overwritten with the value “second”.
This implementation throws a lot of false positives during Elixir’s
bootstrap compile phase. I’ve had trouble debugging it. I think it may
be happening because `@attributes` are treated differently during the
bootstrap phase. Any help would be appreciated.
See #3707 for more details.
=> [#3707] Warn when @attributes are redefined

lib/iex/lib/iex/helpers.ex, lib/iex/test/iex/helpers_test.exs
This patch implements two helper commands 
m - lists all loaded modules and the file path to their object code. 
m/1 - Lists some of the available information about a module. For example: 
iex(2)> m Atom
:module
Atom
:object_file
bin/../lib/elixir/ebin/Elixir.Atom.beam
:source
lib/elixir/lib/atom.ex
:version
[297983237527422559469627991153554784472]
:compile_time
2015-8-31 1:48:12
:compile_options
[:debug_info]
I'm pretty sure that the atoms as labels isn't for everyone's taste, so the code can be easily changed
to better names for those labels. Just let me know.
=> Iex m command

lib/elixir/lib/list.ex, lib/elixir/test/elixir/list_test.exs
Replaces the confusing ":unicode.characters_to_binary([a: 1])" error you would get when interpolating a keyword list. Developers used to Ruby may expect this to just work.
As discussed here: https://groups.google.com/forum/#!topic/elixir-lang-core/ZmxsVo4JO5E
=> More helpful error for keyword list to_string

lib/elixir/lib/process.ex
Because copying the entire example would be silly.
=> Add link to monitor/2 example

lib/elixir/lib/kernel/special_forms.ex
The current example is fine, especially with an understanding of the
matching that is happening. However, to make the example more explicit, the
name of the unmatched pair should be different.
=> Add clarification to comprehension match example

lib/elixir/lib/kernel/special_forms.ex
The code example in section `Hygiene in imports` wouldn't compile, because `size/1` function was removed from `Kernel`. So I updated `Hygiene` with `length/1` defined in `Kennel` for lists.
The code example in `Lazy` can produce a correct result, but since `size/1` function is not available in `Kennel`, the `import Kernel, except: [size: 1]` statement would be redundant. So I updated `Lazy` with `length/1` function as well. Luckily since `length/1` is also define in `String` for strings,  this example still demonstrates the same behavior.
=> Fix code example in the document for quote macro

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs, lib/mix/lib/mix/utils.ex, lib/mix/test/mix/utils_test.exs
Move underscore/1 and camelize/1 from the Mix.Utils module into the Macro module. The Mix.Utils functions have been noted for deprecation and call the Macro functions.
=> Include underscore/1 & camelize/1 in the Macro module

lib/elixir/lib/kernel/special_forms.ex
Uses a string key instead of an atom key in order to force the iex
output to show the list of tuples rather than a keyword list.
The current documentation example shows an output that is equivalent to the actual output of iex, but is not the literal output. That is, if you run: `quote do: %{:a => :b, c: :d}` in iex, the literal output is `{:%{}, [], [a: :b, c: :d]}`. The keyword list is the same as `[{:a, :b}, {:c, :d}]` in meaning but the output looks different.
This change uses a string as the key for the first item in the map, which will output a list of tuples rather than a keyword list.
=> Fix innacurate iex output

lib/elixir/src/elixir_aliases.erl, lib/elixir/test/elixir/kernel/errors_test.exs
Issue: https://github.com/elixir-lang/elixir/issues/3881
I think there are two slightly related cases, that may share the same explanation. I tried to make it as clear as possible with wording, but if you do have better idea please let me know and I can amend.
=> improve error message on requiring module from the context it was defined in

lib/mix/lib/mix/task.ex
Corrected:
* showed => shown
* Multiline backtick rendering issues (see screenshot below)
=> Mix.Task moduledoc update: correction

lib/elixir/src/elixir_aliases.erl, lib/elixir/test/elixir/kernel/errors_test.exs
Minor grammar fix for an error message in compile-time.
=> Grammar fix for error message returned by :elixir_aliases.format_error/2

lib/elixir/lib/supervisor/spec.ex
The reason I think this change is needed is that I'm not familiar with Erlang/OTP, so I was confused about the word `terminated` in `shutdown`. I wondered if it's termination before restart or just stop(will not restart). I looked up in [Erlang's doc](http://www.erlang.org/doc/man/supervisor.html), it says `restart defines when a terminated child process is to be restarted.`, which is more clear.
=> improve doc for restart of supervisor spec

lib/mix/lib/mix/scm/git.ex, lib/mix/test/mix/scm/git_test.exs
https://github.com/elixir-lang/elixir/issues/3885 is the relevant issue. This commit warns user about invalid git options, but does not break existing apps for now. Added todo that this will need to be changed at 2.0 to raise.
=> Validate git options and warn on conflicting ref, branch or tags

lib/elixir/lib/float.ex
The `floor` example was less helpful than it could be since it showed behaviour that was no different from what `round` would do.
Since I "maxed out" the `floor` example, I also "min'd out" the `ceil` example for good measure.
=> Clarify Float.ceil/floor handling of decimals

lib/mix/lib/mix/dep/umbrella.ex
Previously, when using an umbrella app, if a directory was empty when
running a mix task the following error was displayed:
> ** (Mix) Could not find a Mix.Project, please ensure a mix.exs file
> is available"
Since git does not keep directories, it is common to see this issue when
switching branches on an umbrella application where some branches have a
particular app inside `apps` and other branches don't.
This commit checks for the presence of `mix.exs` and uses directories
containing the file as an app in the umbrella application
Please note a `.gitkeep` file is used to allow for an empty directory in the fixtures.
=> fix(Mix.Dep.Umbrella): prevent error when app is missing mix.exs

lib/elixir/lib/gen_event.ex
Properly documented the possibility of adding an handler with an
unique id attached when multiple instances of the same module must
be attached.
Solve issue #3760
=> Documentation improvement to GenEvent

lib/elixir/lib/stream.ex, lib/elixir/test/elixir/inspect/algebra_test.exs, lib/elixir/test/elixir/path_test.exs, lib/ex_unit/lib/ex_unit/case.ex, lib/iex/lib/iex/evaluator.ex, lib/mix/lib/mix/utils.ex
I have removed |>  at the end of the lines,
this only happened twice and one is an example, and I think it's inconsistent.
also code has been simplified using |>, avoiding creating unnecessary variables.
the last fix deals with some formatting issues in Path test: space missing before == , and lines over 100 chars
=> Pipe operator simplication

lib/mix/lib/mix/cli.ex, lib/mix/lib/mix/shell/quiet.ex, lib/mix/test/mix/cli_test.exs, lib/mix/test/mix/shell/quiet_test.exs
Mix.Shell.Quiet is like Mix.Shell.IO, but it prints much less information out. Useful when the output is not important.
Solves #3167.
=> Implemented Mix.Shell.Quiet

lib/logger/lib/logger.ex, lib/logger/test/logger/backends/console_test.exs
In [this StackOverflow question](https://stackoverflow.com/questions/33540776/how-to-get-line-numbers-in-console-outputs-in-elixir), José said it would be possible to add the current file to the logger format, but not all keys from `__CALLER__` are available.
I added the `:file` key since I think it is a useful addition. I also added a list of available keys to the docs, because I was missing them when I researched. Let me know what you think!
=> Add file to logger metadata

lib/elixir/lib/exception.ex, lib/elixir/src/elixir_parser.yrl, lib/elixir/test/elixir/exception_test.exs, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/kernel/expansion_test.exs, lib/elixir/test/elixir/kernel/quote_test.exs, lib/elixir/test/elixir/process_test.exs, lib/elixir/test/elixir/string/chars_test.exs, lib/elixir/test/erlang/function_test.erl, lib/ex_unit/examples/one_of_each.exs, lib/ex_unit/test/ex_unit/assertions_test.exs, lib/ex_unit/test/ex_unit/capture_io_test.exs, lib/ex_unit/test/ex_unit/capture_log_test.exs, lib/iex/test/iex/server_test.exs
Alright @josevalim, here's the new PR (with the changed error message as well). Just a question: should we raise instead of warning? I chose to raise because there are no warnings in the parser and I wasn't sure about adding the first but I can change it if you want.
=> Throw an error for -> with an empty right-hand side - take 2

lib/elixir/lib/io/ansi.ex, lib/elixir/test/elixir/io/ansi_test.exs
https://en.wikipedia.org/wiki/ANSI_escape_code#graphics
=> Add ANSI escape sequences for extended colors

lib/elixir/lib/kernel/cli.ex, lib/elixir/lib/system.ex, lib/elixir/test/elixir/system_test.exs
With erlang version, elixir version, elixir revision short hash.
Also added elixir revision short hash to System.build_info().
```
$ ./bin/elixir --version        
Erlang/OTP 18 [erts-7.1] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.2.0-dev (6b14048)
```
Resolves #3947
=> Added ./bin/elixir --info option #3947

lib/elixir/lib/option_parser.ex
Fixed the docs of the OptionParser module. 
In the first line was written, the OptionParser [...] parse command line arguments, which is a imprecise term. More precise is, the OptionParser [...] parse command line options.
=> The OptionParser parses options, not argumemnts

lib/iex/lib/iex/evaluator.ex, lib/iex/lib/iex/server.ex
* Splits `IEx.State` into `IEx.State` (which contains `cache`, `counter`, and `prefix`)  and `IEx.Evaluator.State` (which contains `binding`, `scope`, and `env`).
* `IEx.State` continues to be stored in the server and passed to the evaluator
* `IEx.Evaluator.State` is stored in the evaluator to enhance performance when large values are stored
* Peeking at the environment is retrieved via message-passing from the evaluator, rather than simply returned from the server.
In my testing I noticed that `IEx.Server.current_env/0` didn't work with the new code, but it also seemed not to work without this patch, as well. Not sure what the intended use of that function is. Other than that, everything seems to work as expected and all iex tests pass.
=> Fix #3914: split IEx server/evaluator state to prevent unnecessary copying

lib/elixir/lib/io/ansi/docs.ex, lib/elixir/test/elixir/io/ansi/docs_test.exs
I noticed there's a bug when escaping underlines in urls in docs. All underlines in the whole line would be escaped, including valid markdown \_italic_ outside the url.
```
iex> IO.ANSI.Docs.print "_click_ http://o_O.example.com" _bait_
_click_ http://o_O.example.com _bait_
:ok
```
=> Don't escape underlines outside url in docs.

lib/elixir/lib/kernel/utils.ex, lib/elixir/test/elixir/kernel_test.exs
Right now, using default args (`\\`) with `defdelegate` results in an error that looks like this:
** (CompileError) iex:2: function '\\\\'/2 undefined
(stdlib) lists.erl:1337: :lists.foreach/2
(stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
(iex) lib/iex/evaluator.ex:117: IEx.Evaluator.handle_eval/5
The error is not very clear. I added some code that raises clearly when default arguments are used with `defdelegate`. Ideally, `\\` should be supported in `defdelegate`? If it should I can give it a shot later this week, but this seems like a good fix in the meantime.
=> Default args in defdelegate

lib/logger/lib/logger/backends/console.ex
This PR changes the `Logger.Backends.Console` private function `take_metadata`, which is a `Keyword.take` that keeps the same order as the keys passed in the args…
Instead of `reduce + reverse`, thought about using `List.foldr` instead. Seems legit?
[Tried some basic measure of the two approaches in this gist](https://gist.github.com/rodrigues/007aa9ff10a12bca4642). It's my first `profile.fprof` hehe… but if I'm not nuts, it reads easier and runs on ~70% of the original time 🤓 Didn't try many scenarios though.
=> Use List.foldr in Console metadata handling

lib/iex/lib/iex.ex
Showing place in code where `IEx.pry` was invoked
After debugging some code, i felt that it would be greate to see where `IEx.pry` was invoked like ruby pry doing.
=> Added verbose pry functionality

lib/elixir/lib/process.ex
This is mentioned in the Erlang docs for `put/2` but not in the Elixir ones.
=> Enhance the docs for Process.put/2

lib/mix/lib/mix/utils.ex, lib/mix/test/mix/utils_test.exs
This PR ensures that calls to `:httpc.request` using the `:mix` profile supply proxy authentication if they can be read from environment variables.
My use case is deploying elixir apps to an internal deployment of Cloud Foundry behind a firewall, limiting external connections to proxies. Hopefully others will find this useful!
=> Support for proxy auth with mix calls to httpc

lib/elixir/lib/io/ansi/docs.ex, lib/elixir/test/elixir/io/ansi/docs_test.exs
Now each reference link labels use one line between each other in IEx. Fixes #3960
=> One reference link label per line

lib/ex_unit/lib/ex_unit/doc_test.ex, lib/ex_unit/test/ex_unit/doc_test_test.exs
=> Print line number when indentation level mismatch in doctest

lib/elixir/lib/io.ex
This adds information to the `IO` docs about devices maintaining the position, and a way to change it for files (e.g. rewind):
```
IO devices maintain their position, that means subsequent calls to any
reading or writing functions will strart from the place when the device
was last accessed. Position of files can be changed using the
`:file.position/2` function.
```
=> Explain IO devices maintain position

lib/iex/lib/iex/autocomplete.ex, lib/iex/test/iex/autocomplete_test.exs
Previously, inputs like 'Enum:' would trigger Erlang module expansion.
=> Only expand Erlang modules when ':' is a prefix.

lib/iex/lib/iex/helpers.ex
This would previously print the 'pwd' string followed by the command's `:ok`
result. This change suppresses the `:ok:` in the same way as similar helpers.
=> Don't print the result of the 'pwd' helper.

lib/mix/lib/mix/tasks/compile.ex
See 7963398aaf448f7113b94ecd27d0fc6604d83fd0 for background.
=> Reword confusing `build_path` documentation.

lib/elixir/lib/file/stat.ex
`gid` - The entry was misleading as it incorrectly implied that the
`gid` indicates the user's group, whereas the `gid` can potentially be
for any group, even one that the user-owner doesn't belong to.
=> Improve the docs for File.Stat

lib/elixir/lib/system.ex, lib/elixir/src/elixir_rewrite.erl, lib/elixir/test/elixir/system_test.exs
Implements #4018.
The implementation is pretty straightforward, I'm just not sure about the docs: should they be more specific? Should they just point to the docs of the functions in the `:erlang` module?
(also, is `:erlang.time_unit` ok in the `@spec` or should I replicate the type in the `System` module?)
=> Add monotonic_time, system_time and unique_integer to System

lib/mix/lib/mix/tasks/local.hex.ex, lib/mix/lib/mix/tasks/local.rebar.ex
This PR tries to fix the issue #4020 
Now it's possible to use the `--mirror` option for `mix local.hex` and `mix local.rebar` tasks.
Please let me know what do you think.
/cc @ericmj
=> Add --mirror option to mix local.{rebar,hex} tasks

lib/elixir/lib/option_parser.ex
* make the return value clearer by presenting it as a list,
* introduce `:switches` before `:strict`,
* remove the documented distinction between `:undefined` and `:invalid`
as it seems to be an implementation detail,
* indicate how to use `:keep` with non-string types.
=> Reword OptionParser moduledoc

lib/elixir/lib/option_parser.ex, lib/elixir/test/elixir/option_parser_test.exs
* supplying :switch together with :strict raises an error.
* closes #4035.
=> Raise error for incompatible OptionParser options

lib/elixir/lib/enum.ex, lib/elixir/lib/stream.ex, lib/elixir/test/elixir/enum_test.exs, lib/elixir/test/elixir/stream_test.exs
=> Implement Enum.with_index/2

lib/elixir/lib/map.ex
Maybe `[key]` should be `Enum.t` since that is what would actually be accepted?
=> Map.take/2, Map.drop/2, Map.split/2 missing spec

lib/elixir/lib/path.ex, lib/elixir/test/elixir/path_test.exs
This patch handles cases such as
```elixir
Path.expand("/foo/../..")
```
which currently fail as described in #4050.
I also added a test for this particular case.
=> Fix edge case in Path.expand. Fix #4050.

lib/mix/lib/mix/project.ex, lib/mix/test/mix/project_test.exs
I added `@spec`s to all the public functions in `Mix.Project`; I did this because I was confused about how `Mix.Project.in_project/3-4` works and I had to read the source to understand it (specifically, what the `fun` argument takes as the only argument). I think specs can make things clearer overall - that is, if there was no particular reason not to have them here :).
Also, I enhanced the docs for `Mix.Project.in_project/3-4` for the reasons described above and added a test for this same function to test that the result of the function is indeed the result of the invocation of the argument `fun`.
Let me know if I can do anything else!
=> Specs for functions in Mix.Project and a couple of docs polishings

lib/mix/lib/mix/generator.ex
I added `@spec`s to the functions in `Mix.Generator` and examples to the docs for those functions.
=> Add specs and enhance docs for Mix.Generator

lib/elixir/lib/option_parser.ex, lib/elixir/src/elixir_import.erl, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/option_parser_test.exs, lib/ex_unit/lib/ex_unit/doc_test.ex
Currently, `import` silently ignores `:except` option if `:only` as a keyword list is given:
```elixir
iex> import String, only: [starts_with?: 2], except: [starts_with?: 2]
nil
iex> starts_with?("a", "a")
true
```
Though `only: :functions` and `only: :macros` with `:except` are still valid.
=> Make import with conflicting options to raise

lib/elixir/lib/string.ex
Looks like this uses graphemes, not codepoints: https://github.com/elixir-lang/elixir/compare/master...henrik:patch-6#diff-22d92528e5319c6e47e28d62cbff5be7R1347
``` elixir
iex> string = "\u0065\u0301"
"é"
iex> String.codepoints(string)
["e", "́"]
iex> String.slice(string, 0, 1)
"é"
```
=> String.slice docs: codepoints -> graphemes

lib/elixir/lib/string.ex
``` elixir
iex> string = "\u0065\u0301"
"é"
iex> String.codepoints(string)
["e", "́"]
iex> String.split(string, "", trim: true)
["é"]
```
=> String.split docs: codepoints -> graphemes

lib/elixir/lib/string.ex
Looked into this and found the examples less clear than they could be about this distinction.
=> Clarify codepoint/grapheme in String docs

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
This fixes the `Access.get` case in `Macro.to_string` to put parenthesis when the left hand side operand is an application.
This fixes #4065.
It does add unneeded parentheses for cases like
```elixir
Macro.to_string(quote do: Dict.put(%{}, "foo", "bar")["foo"])
```
If this is an issue, I can work on it.
=> Fix bug in Macro.to_string. Fix #4065.

lib/elixir/lib/string.ex
Currently, if you look at the docs of both functions, it's hard to tell what the difference is.
This should make it a bit better.
I'm not sure if this is the best way of linking to the module docs.
Another thing I considered but wasn't sure about (mostly because getting it right without ugly `\u…` values is a little fiddly): we could add the same example input, with different output, to the docs of both.
=> String docs: link codepoints/graphemes to details

lib/elixir/lib/system.ex, lib/elixir/test/elixir/system_test.exs
Previously only strings were accepted as valid env keys and values.
However, because the `env` option is eventually passed to
`:erlang.open_port`, `false` values, which remove existing environment
variables, should be allowed.
From the docs for [`erlang:open_port/2`](http://www.erlang.org/doc/man/erlang.html#open_port-2):
{env, Env}
This is only valid for {spawn, Command} and {spawn_executable,
FileName}. The environment of the started process is extended using the
environment specifications in Env.
Env should be a list of tuples {Name, Val}, where Name is the name of an
environment variable, and Val is the value it is to have in the spawned
port process. Both Name and Val must be strings. The one exception is
Val being the atom false (in analogy with os:getenv/1), which removes
the …
=> Allow `false` value in env passed to `System.cmd/3`

lib/elixir/lib/access.ex, lib/elixir/test/elixir/access_test.exs
=> Raise when Access syntax used on non-keywords

bin/mix.bat
On Unix-like systems, the mix command is implemented as an elixir script that runs 
```
Mix.start
Mix.CLI.main
```
On Windows mix.bat it runs something like
```
elixir -e Mix.start -e Mix.CLI.main
```
that is a bit different.
On both systems, if you run 
```
elixir -e Mix.start -e Mix.CLI.main --version
```
you get
```
Elixir x.y.z
```
instead of
```
Mix x.y.z
```
=> mix.bat changed to emulate mix script on Unix-like systems. Solves #4075

lib/elixir/lib/access.ex, lib/elixir/lib/kernel.ex, lib/elixir/src/elixir_exp.erl, lib/elixir/src/elixir_rewrite.erl, lib/elixir/test/elixir/access_test.exs, lib/elixir/test/elixir/kernel/errors_test.exs
=> Make Access syntax fail to compile for unsupported values

lib/elixir/lib/kernel/special_forms.ex
The example prints "Got 25", not just "25"
=> Fix example in `quote`

lib/mix/lib/mix/tasks/deps.clean.ex, lib/mix/test/mix/tasks/deps_test.exs
I added a `--build` flag to the `mix deps.clean` task, as discussed in #4088.
=> Add --build flag to deps.clean mix task. Close #4088.

lib/elixir/lib/exception.ex, lib/elixir/test/elixir/list_test.exs
previously assumed the head of the returned iolist would be an integer. This has been fixed with more recursion
fishcakez was right
=> Fix issue #4081 UnicodeConversionError would generate invalid strings

lib/mix/lib/mix/tasks/deps.clean.ex
I just realized that I had not added the `--build` option to the `mix deps.clean` task  docs in #4089.
Sorry for that.
=> Add deps.clean --build documentation.

lib/elixir/lib/enum.ex
When I first wrote the docs, I didn't know I had to include the `Kernel.` to make the automatic linking work.  I double checked after reading the documentation guide for Elixir 1.2 and noticed that the
`<=/2` wasn't linking.
=> Fix link to Kernel.<=/2 in Enum.sort_by/3 @doc

bin/iex.bat
Allow the user to set an environment variable on Windows so --werl can be the default:
```bat
C:\Users\user>set ELIXIR_IEX_FLAGS=
C:\Users\user>iex
Eshell V7.2.1  (abort with ^G)
Interactive Elixir (1.2.0-rc.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Terminate batch job (Y/N)? y
C:\Users\user>set ELIXIR_IEX_FLAGS=--werl
C:\Users\user>iex
C:\Users\user>REM IEx window opens instead.
```
=> Add environment variable to iex.bat so user can default to --werl.

lib/elixir/src/elixir_module.erl
Verify the spec's correctness with `mix dialyze --specdiffs` in a dummy
mix project.
Closes #4113.
=> Update the spec for the generated __info__/1 function to please Dialyzer

lib/elixir/lib/module.ex
I fixed this by change 6 spaces indent to 4. Otherwise the doc will be like
```elixir
defmodule M do
@compile {:inline, myfun: 1}
def myfun(arg) do
to_string(arg)
end
end
```
instead of 
```elixir
defmodule M do
@compile {:inline, myfun: 1}
def myfun(arg) do
to_string(arg)
end
end
```
=> fix the indent of moduledoc in Module

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
This fixes `Macro.to_string` bit containers clause for cases like mentioned in #4116 
where the expression inside `<< >>` does not start by `<<` but ends by `>>`.
```
ast = quote do: for <<a::4 <- <<1, 2>> >>, do: a
```
=> Fix bug in Macro.to_string. Fix #4116.

lib/elixir/lib/module.ex
If I understand the code correctly a warning will be thrown if you use the `@` macro, but probably that information should go in the macro's docstring?
=> documenting the default return value for `Module.get_attribute/2`

lib/elixir/test/elixir/gen_event_test.exs
The added calls make sure the generated log message is sent before
the :console backend is readded.
This was pretty much me channeling @fishcakez's knowledge into code :)
=> Fix a race condition in gen_event_test.exs. Fix #4131

lib/mix/lib/mix/tasks/compile.leex.ex, lib/mix/lib/mix/tasks/compile.yecc.ex
This PR should close #4111. Some options passed to `:yecc`/`:leex` in the corresponding compilers are overridden so that the return value of `:yecc.file/2` and `:leex.file/2` is predeterminable.
=> Override some yecc/leex compiler opts in order to avoid errors

lib/elixir/src/elixir_tokenizer.erl
I found this while compiling elixir master:
```
src/elixir_tokenizer.erl:478: Warning: function escape_char/1 is unused
```
=> Remove unused `escape_char/1` function

lib/mix/lib/mix/tasks/new.ex
The `mix new` task generates README.md with code markdown that isn't highlighted by github. 
I've specified elixir syntax highlighting in README.md template for the `mix new` task.
=> Specify syntax highlighting for README.md template in mix

Makefile, lib/elixir/pages/Naming Conventions.md
Discussed with @josevalim on Twitter if it could make sense to have a doc page making implicit naming conventions explicit and easy to discover.
I'm making a PR during early stages (before I start fleshing out and polishing text) to get feedback.
Some things I'm not sure about:
* Does "Naming Conventions" make sense as the name for this document? It's all function naming 
currently, but "Function Naming Conventions" is overlong and overspecific, I feel. If we would ever want to write about any other naming conventions (modules or something), we could make subsections.
* Should I add a third explicit `-e` to the Makefile like I did? It doesn't seem to accept globs, but maybe one could either write some fancier bash code to turn a glob into `-e` arguments, or make ex_doc handle globs.
=> Naming Conventions doc page

lib/elixir/pages/Naming Conventions.md
My own typos :) Checked the rendered HTML and noticed these weren't linkified.
=> Naming Conventions doc: function name typos

lib/elixir/lib/enum.ex
Copied this text from `Enum.fetch/2` and changed the word "fetches" to "finds".
=> Enum.at docs: mention negative indexing

lib/elixir/pages/Naming Conventions.md
Using all capitals is recommended only when you have an acronym
like HTTP, IO, SCM, etc. For an abbreviation like "Misc" or "Utils"
all caps should not be used.
I noticed this when #4137.
/cc @henrik
=> abbreviations -> acronyms

lib/mix/lib/mix/exceptions.ex, lib/mix/test/mix/task_test.exs, lib/mix/test/test_helper.exs
Previously, you could get the incredibly confusing error:
> The task "acronym.http" could not be found. Did you mean "acronym.http"?
This happened when you named your module `Mix.Tasks.Acronym.HTTP` rather
than `Mix.Tasks.Acronym.Http` as expected. Since we can detect this
situation, it's helpful to give the user a clear explanation of the
problem.
(For context: this is a follow up to a [conversation I had with José earlier today](https://github.com/elixir-lang/elixir/pull/4137/files#r48686720)).
=> Improve error message for when the named mix task cannot be found.

lib/iex/lib/iex/info.ex
Because this (the current output) looks a little odd:
Compile time
2016-1-2 23:28:9
Didn't add any tests because the time wasn't mentioned in the existing tests. Seemed a trivial-enough change.
=> Zeropad compile time in i/1

lib/elixir/lib/bitwise.ex
Broken markdown formatting. The code example didn't render as a code block. Added a single newline to make a new paragraph, fixes it.
See:
https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/bitwise.ex#L19
http://elixir-lang.org/docs/v1.2/elixir/Bitwise.html
=> Fix markdown formatting of a code example in Bitwise module documentation

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/map_test.exs
Previously `defstruct` could be called multiple times. This could be
particularly confusing is `defstruct` is called by an external library
such as the Ecto `schema` macro.
Calling `defstruct` when the `@struct` module attribute already exists
will now cause a `CompileError`
This closes #4155
=> feat(Kernel): raise when defstruct is called more than once

lib/elixir/lib/kernel.ex
=> Fix typo in `Kernel.use/2` moduledoc

lib/elixir/lib/kernel.ex
Maps coming from decoded JSON or other untrusted sources usually have string keys. Attempting to convert a map with string keys into a struct will always result in the default struct, as structs are always defined with atoms so the keys are all ignored.
=> Document that non-atom keys are ignored by struct

lib/elixir/lib/supervisor.ex
I realized I wasn't sure what was passed to the `init` callback after calling `Supervisor.start_link/3`.
This hopefully makes it more clear.
Also, I improved formatting by breaking lines at 80 chars. Hope that's OK.
=> [doc] Clarify what's passed to `init`

lib/mix/lib/mix/tasks/new.ex
In the README file, the app name looks much better if it's `highlighted as code`.
=> Highlight the app name in README

lib/ex_unit/lib/ex_unit/case.ex
Default timeout is 60000 milliseconds.
```elixir
ExUnit.start
defmodule TimeoutTest do
use ExUnit.Case, async: true
test "timeout" do; :timer.sleep 100_000 end
end
```
```bash
$ elixir /tmp/timeout_test.exs
1) test timeout (TimeoutTest)
/tmp/timeout_test.exs:6
** (ExUnit.TimeoutError) test timed out after 60000ms. You can change the timeout:
1. per test by setting "@tag timeout: x"
2. per case by setting "@moduletag timeout: x"
3. globally via "ExUnit.start(timeout: x)" configuration
4. or set it to infinity per run by calling "mix test --trace"
(useful when using IEx.pry)
Timeouts are given as integers in milliseconds.
stacktrace:
(stdlib) timer.erl:153: :timer.sleep/1
/tmp/timeout_test.exs:6
(ex_unit) lib/ex_unit/runner.ex:293: ExUnit.Runner.exec_test/1
(stdlib) timer.erl:166: …
```
=> Fix the description of the timeout

lib/iex/lib/iex/helpers.ex
If in `iex`(elixir `1.2.0`) we list the available helpers by executing `h()`, we get the following list:
As shown in the picture, there are two identical items in the list.
This PR removes the second duplication, that happens to be the last item, not following the alphabetic sorting.
=> Remove duplicate line in module IEx.Helpers doc

lib/iex/lib/iex/autocomplete.ex, lib/iex/test/iex/autocomplete_test.exs
I made a small improvement in Iex `expand` to handle cases where an expression starts with `&`.
For example
```elixir
Enum.map ~w(foo bar baz), &Str
```
did not yield any completion when pressing tab.
With this fix, it ignores the `&` to yield usual completions.
=> Improve iex expand to handle '&'.

lib/iex/test/iex/config_test.exs
`config_test` fails if my terminal is less than 80 chars wide.
```
$ make test_iex
==> elixir (compile)
==> iex (exunit)
1) test configuration sets a default for width (IEx.ConfigTest)
test/iex/config_test.exs:6
Assertion with == failed
code: IEx.Config.configuration()[:width] == 80
lhs:  61
rhs:  80
stacktrace:
test/iex/config_test.exs:7
....................................................................................................
Finished in 1.4 seconds (0.5s on load, 0.8s on tests)
101 tests, 1 failure
Randomized with seed 298890
Makefile:95: recipe for target 'test_iex' failed
make: *** [test_iex] Error 1
```
While it is not really a big issue, simply checking for an integer should be enough here and avoid to depend on the terminal being more than 80 chars.
=> Avoid config_test to depend on terminal size

lib/mix/lib/mix/config.ex
*   The example code is using the old name of
`Application.fetch!/2`, change to the new, more clear name:
`Application.fetch_env!/2`.
=> Update example code to use correct method name

lib/ex_unit/lib/ex_unit.ex
The new payload returned by the ExUnit.Runner module for the failed state does not match its type specification declared in ExUnit module since Elixir 1.2.0.
https://github.com/elixir-lang/elixir/blob/v1.2.0/lib/ex_unit/lib/ex_unit/runner.ex#L353
This fix change the type definition to support multiple errors.
=> Correct the type definition of ExUnit.state for the failed state

lib/elixir/lib/kernel/special_forms.ex
Hello.
I've noticed wrong formatting in the docs.
=> Fix a typo in `for/1` docs

lib/elixir/lib/record.ex
Hi,
I like to read the docs through the source code and the markup helps to identify what is code and what is text. I noticed that in `ArgumentError` wasn't formatted like all other places over the doc.
=> Update doc to use the correct format

lib/ex_unit/lib/ex_unit/assertions.ex, lib/ex_unit/test/ex_unit/assertions_test.exs
I reused the logic used in `assert_received` to show the pinned variables when using the match operator and `match?`.
=> Update exunit match operator and match? to show pinned variables.

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
Fixes the following problem (reproduced in 1.2.0 and at head)
```
iex(1)> ast = quote do: :erlang.max(<<>>, [])
{{:., [], [:erlang, :max]}, [], [{:<<>>, [], []}, []]}
iex(2)> Macro.to_string(ast)
:erlang.atom_to_binary({:., [], [:erlang, :max]}, :utf8)
(elixir) lib/macro.ex:696: Macro.sigil_call/2
(elixir) lib/macro.ex:600: Macro.to_string/2
```
=> Fix a crash in Macro.to_string if a tree looks like a sigil but the function is not an atom

lib/elixir/lib/kernel.ex, lib/elixir/lib/kernel/utils.ex, lib/elixir/test/elixir/kernel_test.exs
As discussed in #4196, I added the possibility to pass optional parameters to `defdelegate`.
It works by generating all the possible heads for the function, and passing the optional arguments to the delegated function in the body.
```elixir
defdelegate fun(arg1, arg2 \\ []), to: Mod
def fun(arg1), do: Mod.fun(arg1, [])
def fun(arg1, arg2), do: Mod.fun(arg1, arg2)
```
=> Add defdelegate optional parameters. Close #4196.

lib/elixir/lib/kernel.ex
As discussed in #4199, I added a deprecation warning for `defdelegate` with lists and `append_first` option.
Would it be better to remove the examples from the doc, or should they stay until these features are actually removed?
/cc @josevalim @lexmag
=> Add deprecation for defdelegate list arguments and append_first option

lib/elixir/lib/enum.ex
> The given function must return false if the first argument is smaller than second one.
could be misunderstood as "the function should return false if the _literal_ value of first argument is smaller than the second". This is resolved with the examples, but it would be more eloquent just to explain it in the function description.
=> Remove minor ambiguity in Enum.sort/2 doc

lib/elixir/lib/base.ex
Clean up base64 doc, probably left from previous docstring. Alphabets are presented in module doc.
=> Update base.ex doc

lib/elixir/lib/stream.ex
@doc change: there is no Stream.transform/2 and Stream.transform/4's
initial accumulated value is also computed lazily so the doc in
Stream.resource/3 must be referring to Stream.transform/3.
@spec change: I tried the example in Stream.resource/3 to use `nil`
instead of `{:halt, acc}`, as currently specified by the spec, and got:
** (CaseClauseError) no case clause matching: nil
(elixir) lib/stream.ex:1099: Stream.do_resource/5
(elixir) lib/enum.ex:1486: Enum.reduce/3
(elixir) lib/enum.ex:2248: Enum.to_list/1
Besides, the doc and spec don't match (and the doc seems to be correct,
so I changed the spec).
=> Stream.resource/3 @doc and @spec change

lib/elixir/lib/exception.ex, lib/elixir/lib/file.ex, lib/elixir/test/elixir/file_test.exs
Technically it is possible to pass an io_device to File.copy/3 as either the source, destination, or both. However, all input was being converted to a string, which fails for any non-binary data and prevents `:file.copy` from being reached.
This updates the typespec and conditionally converts chardata to a string.
=> Support passing io_device to File.copy/3

lib/elixir/lib/kernel/special_forms.ex
The old wording -- "the current directory" -- made me think it returned
your current working directory, but it's really the directory of the
current file.
=> Make `__DIR__` docs more accurate.

lib/elixir/lib/base.ex, lib/elixir/test/elixir/base_test.exs
As discussed in #4186, I added `ignore: :whitespace` option to `Base.decode64` and `Base.url_decode64`.
=> Add option to ignore whitespace to base64 decoding. Close #4186.

lib/mix/lib/mix/cli.ex, lib/mix/lib/mix/task.ex, lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/cli_test.exs, lib/mix/test/mix/task_test.exs
If one develops a custom task, she might want it to run by default in particular environment, for example, `:prod`. 
She can do it by specifying `preferred_cli_env` in client mix file, but it means that every client should do it. OTOH, `preferred_cli_env` seems to be as natural attribute of the task, as `recursive`, or `shortdoc`. 
As a side effect, it would make `test` task less special (it would simply declare `:test` as a preferred environment).
=> add `preferred_cli_env` attribute to task definition

lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/test/ex_unit/case_test.exs
See #4232 
ExUnit.Case can register test attributes which are
accumulated per test run and injected into the `context.private` under the
attribute name:
```elixir
defmodule MyTest do
ExUnit.Case.register_attribute __MODULE__, :foo
@foo hello: "world"
test "can access @foo via `context`", context do
assert context.private.foo.hello == "world"
end
end
```
=> Add test attributes

lib/elixir/lib/gen_server.ex, lib/elixir/test/elixir/gen_server_test.exs
This unifies the behavior of `GenServer.cast/2` to always
return :ok and never raise an `ArgumentError`, regardless
of how it is called.
Previously an `ArgumentError` would be be raised only when
called with a nonexistant local process name. In all other cases
which are calling using `:global`, `:via` or `{name, node}`
it would previously always return `:ok`.
The new behavior is now constistant with `:gen_server.cast/2`.
This reverts the change partially introduced in 0d4af57abead1c4dfdc2f71fe198ae539f6eceab.
See #4251 for the full discussion.
=> Make GenServer.cast/2 always return :ok. Closes #4251

lib/elixir/lib/io.ex
Found a spelling mistake - 
`shorcuts` > `shortcuts`
=> Fix typo in Elixir docs

lib/elixir/lib/path.ex, lib/elixir/test/elixir/path_test.exs
=> Fix bug in Path.join. Fix #4252.

lib/mix/lib/mix/tasks/app.tree.ex, lib/mix/test/mix/tasks/app.tree_test.exs
Task to show dependency tree of an application.
=> Add task app.tree

lib/mix/test/mix/tasks/deps.tree_test.exs
I got
```
mix.exs:2: warning: redefining module GitRepo.Mixfile (current version defined in memory)
```
when running the tests in master.
I used [@lexmag trick](https://github.com/elixir-lang/elixir/issues/3911#issuecomment-167453067) to find the culprit.
=> Fix warning in mix test.

lib/elixir/lib/kernel/special_forms.ex
The docs for `case` said to
> add a final clause, equal to `_`
as if only `_` would work; the docs now make it clearer that any catch-all clause is fine. Similar changes were made to the docs for `cond`.
(the previous phrasing was introduced in #4285, /cc @eksperimental who submitted that PR)
=> Fix wording in the docs for case and cond

lib/ex_unit/lib/ex_unit/runner.ex, lib/ex_unit/test/ex_unit_test.exs
It seem that the "case" tag doesn't work.
http://elixir-lang.org/docs/v1.2/ex_unit/ExUnit.Case.html:
> The following tags are set automatically by ExUnit and are therefore reserved:
>
> * :case - the test case module
For example, the following test:
```elixir
ExUnit.start
ExUnit.configure [exclude: :case]
defmodule SampleTest do
test "this is sample" do; :ok end
end
```
expected (skip all cases)
```
$ elixir sample_test.exs
Excluding tags: [:case]
Finished in 0.08 seconds (0.08s on load, 0.00s on tests)
1 test, 0 failures, 1 skipped
```
actual
```
$ elixir sample_test.exs
Excluding tags: [:case]
.
Finished in 0.07 seconds (0.07s on load, 0.00s on tests)
1 test, 0 failures
```
=> Fix "case" tag filtering doesn't work

lib/elixir/lib/map.ex
Based on the discussion here: https://github.com/erlang/otp/pull/959 it was determined that building a list and then using :maps.from_list had superior performance characteristics, and would also generate less garbage
=> Improve Map.take/2

lib/elixir/lib/inspect.ex, lib/elixir/lib/inspect/algebra.ex, lib/elixir/test/elixir/inspect_test.exs
Allow inspecting binaries as :hex or :octal.
Examples:
```
iex> inspect("abc")
"\"abc\""
iex> inspect("abc", binaries: :as_binary)
"<<97, 98, 99>>"
iex> inspect("abc", binaries: :as_binary, base: :hex)
"<<0x61, 0x62, 0x63>>"
iex> inspect("abc", base: :hex)
"<<0x61, 0x62, 0x63>>"
iex> inspect("abc", base: :octal)
"<<0o141, 0o142, 0o143>>"
iex> inspect(<< 10, 11, 12::4 >>, base: :hex)
"<<0xA, 0xB, 0xC::size(4)>>"
```
=> Support :base option when inspecting binaries

lib/ex_unit/lib/ex_unit.ex
This is a reminder from https://github.com/elixir-lang/elixir/blob/v1.2.2/lib/ex_unit/lib/ex_unit/case.ex#L162:L163
I was a bit on a fence if I should submit this PR or not because it's a repetition. However, it would have saved me some time because I happened to read that doc first and got confused why just running  `mix test --include focus` was running all tests for me.
=> ExUnit: Add note in docs about `:include` ignored without `:exclude`

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
This only applies when taking a single count, but drastically improves the performance of large ranges, such as `Enum.random(1..1_000_000)`, which is a common use-case.
=> Optimize Enum.random for ranges

lib/elixir/lib/gen_event.ex
Also removed dead link to Getting Started guide.
=> Fixed typos in GenEvent docs.

lib/elixir/lib/base.ex, lib/elixir/test/elixir/base_test.exs
Add option to omit padding to `encode64`, `url_encode64`, `encode32`, `hex_encode32`
Add option to ignore padding to `decode64(!)`, `url_decode64(!)`, `decode32(!)`, `hex_decode32(!)`
Closes #4316
=> Add option to omit / ignore padding

lib/iex/lib/iex/helpers.ex
noticed a small typo in this documentation - "lookup" is a noun, so it should be "look up"
=> fix typo in def v(n \ -1) documentation

lib/elixir/lib/macro.ex
Previously the fact that only lower case sigils was only documented in
the getting started guide.
=> docs(Macro): clarify difference between sigils

lib/elixir/lib/string.ex
`String.slice/2` works with graphemes, not codepoints. `String.slice/3` already documents it correctly.
=> Fix String.slice/2 doc

lib/elixir/lib/version.ex, lib/elixir/test/elixir/version_test.exs
When `allow_pre: false` is set the `~>` operator will not match a pre-release version unless the operand is a pre-release version. The default is to allow always allow pre-releases but note that in Hex `:allow_pre` is set to `false.` See the table below for examples.
=> Add :allow_pre option to Version.match?

lib/elixir/lib/kernel.ex
I just added a couple lines that mention protocol derivation and redirect to the documentation for `defstruct/1` for more information.
=> Mention protocol derivation in `defprotocol/2` docs

lib/elixir/lib/kernel/special_forms.ex
I used existing examples so that we don't add too much complexity and unnecessary volume to the documentation.
I think we can polish the docs for `with` a little bit further, but I'd rather do it in another PR :).
=> Update the docs for "for" and "with" to showcase guards

lib/elixir/lib/kernel/special_forms.ex
Looks like the moduledoc flag was disabled in Kernel.Typespec Module [1]
and a page was created instead
[1] f1d4d5b034bd47d6488b808766f25a3f6fd82683
=> Update reference to Kernel.Typespec

lib/elixir/lib/regex.ex, lib/elixir/test/elixir/regex_test.exs
Hi,
I came across the #4220 while messing with Regex stuff in a custom inflector and decided to go ahead a fix because I was enjoying elixir so much.
Anyway after looking and testing, it seems to be a matter of the closing brackets not being in the compiled escape pattern.
If you'd like me to change anything or write more tests, I'd be happy to do so.
=> add escape for closing brackets

lib/elixir/src/elixir_interpolation.erl, lib/elixir/test/elixir/kernel/sigils_test.exs
As discussed in #4209, the behavior of `~S` (and `~R`) is currently inconsistent.
```elxir
~S"foo\bar" # => "foo\\bar"
~S"foo\
bar" # => "foobar"
```
This fixes the behavior to avoid escaping newlines where it should not, so that the above becomes:
```elxir
~S"foo\bar" # => "foo\\bar"
~S"foo\
bar" # => "foo\\\nbar"
```
=> Do not escape new line when interpolation is disabled. Fix #4209.

lib/elixir/lib/kernel/lexical_tracker.ex, lib/elixir/src/elixir_dispatch.erl, lib/elixir/src/elixir_import.erl, lib/elixir/src/elixir_lexical.erl, lib/elixir/test/elixir/kernel/lexical_tracker_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs, lib/mix/lib/mix/dep/fetcher.ex, lib/mix/lib/mix/tasks/deps.compile.ex, lib/mix/lib/mix/tasks/new.ex
Discussed briefly on: https://groups.google.com/forum/#!topic/elixir-lang-core/YFg07iq4l4Y but also spoken about some implementation details with @josevalim.
I'd appreciate feedback if this is going into the right direction, will be useful enough, and could be considered for merging after it's finished up.
Say, there's following file:
```elixir
import String, only: [upcase: 1, downcase: 1]
import Enum
IO.puts upcase("Hello")
```
Before this patch:
After this patch:
=> Track {module, function, arity} imports and warn on unused ones

lib/mix/lib/mix/dep.ex
I am fairly sure the code I removed in this PR is dead code; it did something before 2c5c53834f7adb0cf9526003450981545ef61766, but it can't do anything right now (since data is immutable in Elixir :smiley_cat:). Tests confirm this as they all pass without the removed code, this helps my confidence here :).
=> Remove some dead code in Mix.Dep

lib/elixir/lib/integer.ex
Integer.parse/1 followed this pattern:
```elixir
defp do_parse(<<char, rest :: binary>>, ...) do
...
{..., <<char, rest :: binary>>}
end
```
This causes a new binary to be created instead of `rest` just being a sub-binary. I tested this with a memory leak I was experiencing in Redix and this seems to fix it. I also did a slightly more scientific experiment with refc binaries:
```elixir
input = "42" <> String.duplicate("a", 10_000)
:erlang.process_info(self(), :binary)
#=> {:binary, [{..., 10002, ...}, ...]}
{int, bin} = Integer.parse(input)
:erlang.process_info(self(), :binary)
#=> {:binary, [{..., 10002, ...}, {..., 10000, ...}, ...]}
```
Still, unrelated from the memory leak, I think the change in the PR is good style anyways :) What do you think?
=> Fix a possible binary leak in Integer.parse/1

lib/ex_unit/lib/ex_unit/callbacks.ex
Left-over from previous versions
=> Remove mention to dict in `ExUnit.Callbacks example`

lib/ex_unit/lib/ex_unit/case.ex
We're spelling it "behaviour" everywhere else (even in the non-OTP context), let's just be consistent across the board
=> Spell behaviour consistently

lib/elixir/lib/process.ex
-Added backticks appropriately in docs for Process.exit
-Mentioned default behaviour for Process.get
=> Improved docs for Process

lib/elixir/lib/uri.ex
Currently, the doc block states that "keys and values are URL encoded as per `encode/2`" when they are actually encoded using `encode_www_form/1`.
I made this clarification and also added an example to demonstrate that the resulting params' spaces are replaced with `+` instead of `%20`, as would be the case with `encode/2`.
=> Minor correction to URI.encode_query/1's doc block

lib/elixir/pages/Typespecs.md
See a similar note in the [Erlang reference
manual](http://erlang.org/doc/reference_manual/typespec.html#id77939)
and [Björn-Egil's answer on the erlang-questions mailing
list](http://erlang.org/pipermail/erlang-questions/2016-March/088139.html)
=> Added a note about dialyzer not using map pair type information

lib/elixir/lib/enum.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/kernel/special_forms.ex, lib/elixir/lib/keyword.ex, lib/elixir/lib/macro.ex, lib/elixir/lib/macro/env.ex, lib/elixir/lib/map.ex, lib/elixir/lib/uri.ex
- "n-item" terminology was replaced by "n-element"
- replaced "two-elements" with "two-element" when used as an adjetive
- replaced numbers with words (as in 1-element)
=> Correct n-element terminology in tuples

lib/elixir/lib/string.ex
Just clarifying that multiple sequential whitespace is treated as a single whitespace.  The existing docs say that leading/trailing whitespace is ignored, but IMHO that was ambiguous for whitespace in the middle of the string.
=> String.split/1 docs - clarify treat multiple whitespace as single

lib/ex_unit/lib/ex_unit.ex
I mentioned that tests within a test case are run serially even with async:true.  This confused me tremendously until I found the comment by @ericmj on this thread: https://github.com/elixir-lang/elixir/issues/3580
=> Clarify ExUnit async docs

lib/elixir/lib/calendar.ex, lib/elixir/lib/calendar/iso.ex
Hello everyone,
This pull request is a proposal for unifying Calendar types in the Elixir ecosystem. Today we have a mixture of different libraries, each defining their own types, which makes interoperability between them really complicated.
Currently, the defined structures do not have any function attached to them, but we expect some basic functionality like ISO8601 parsing and formatting as well as conversion to/from Erlang tuples to be added before Elixir v1.3 is released.
This pull request is not a replacement for the existing date/time libraries. We will still rely on the ecosystem for handling date formatting, date parsing, intervals, periods, time zones and so on. 
Huge thanks to @lau and @bitwalker for the discussion that lead to this proposal.
**Q: Will Elixir support multiple …
=> Introduce calendar types

lib/iex/lib/iex/helpers.ex, lib/iex/test/iex/helpers_test.exs, lib/iex/test/test_helper.exs
Erlang's `c` module is a jumbled sock-drawer of commonly used commands. Inside it is a powerful (but obscure) feature `c:nl(modulename)` that will deploy the object code for a locally compiled module to all connected nodes. This makes deploying code to a newly connected cluster simple, and allows easy redeployment of updated/recompiled code. The Erlang implementation of `c:nil` ([doc](http://erlang.org/doc/man/c.html#nl-1)) glues together `code:ensure_loaded` ([doc](http://erlang.org/doc/man/code.html#ensure_loaded-1)) and `rpc:eval_everywhere` ([doc](http://erlang.org/doc/man/rpc.html#eval_everywhere-4)). 
This pull request give the functionality of `nl` a better home: `Node.load_module`
=> Adds nl to IEx.Helpers

lib/elixir/lib/string.ex, lib/elixir/test/elixir/string_test.exs, lib/elixir/unicode/WhiteSpace.txt, lib/elixir/unicode/unicode.ex
We have been using BiDi character types to determine which unicode characters to consider as whitespace (looking at `B`, `S` and `WS`). By some reason the character set of BiDi whitespace is different than the set for the unicode `White_Space` property. This difference causes surprise in users since the docs for `String.strip/1` and `String.split/1` refer to "unicode whitespace" (the main concern expressed so far is the exclusion of the no-break space `0x0020` from the BiDi set, see #4300).
This PR swaps the use of BiDi character types by the use of the `White_Space` property by adding a subset of a new Unicode table (`PropList.txt`) and a parser for it. This makes the implementation better match the documentation.
Additionally, the no-break characters are excluded from `split` (since …
=> Update definition of Unicode Whitespace

lib/mix/lib/mix/task.ex, lib/mix/test/mix/task_test.exs
This function re-enables the given task and then runs it. Should close #4393.
=> Add Mix.Task.rerun/1,2

bin/elixir, bin/elixir.bat, lib/elixir/lib/kernel/cli.ex
This PR should address #4355.
I added the following command-line arguments to the `elixir` binary:
* `--logger-otp true|false` - to configure the `:handle_otp_reports`
of the `:logger` application
* `--logger-sasl true|false` - to configure the `:handle_sasl_reports`
of the `:logger` application
Not sure this is the best way, consider this as an attempt :). Let me know if I can do anything else!
=> Add --logger-otp and --logger-sasl to the command-line args

lib/elixir/lib/application.ex, lib/elixir/test/elixir/application_test.exs
As Path.join is able to accept a list as argument, it seems logical that Application.app_dir should be able to do so as well.
=> Make Application.app_dir/2 accept a list as path argument.

lib/elixir/lib/kernel.ex
I feel like it's relatively common to see newer elixir users do
```
list ++ [item]
```
inside of a loop, and feel like we should mention the potential pitfalls and alternatives.
The erlang docs have a similarly worded warning for `--`, and it deserves inclusion in our stdlib as well.
=> Add notes about the complexity of ++ and --

lib/elixir/lib/kernel/typespec.ex, lib/elixir/pages/Typespecs.md, lib/elixir/src/elixir.erl, lib/elixir/test/elixir/kernel/typespec_test.exs
I find the `keyword/0` and `keyword/1` types discussed in #3679 pretty convenient, so I took a shot at a PR that implements them. Not sure this is the correct way to solve that though, so any feedback is more than welcome :smiley_cat:
=> Add the keyword/0 and keyword/1 built-in types

lib/iex/lib/iex/helpers.ex
Replaced "em dash" symbol with ordinary "-", because "em dash" symbol is represented as "тАФ" in Windows terminal. That should also be better for overall consistency.
=> Fix doc string for h() fn in iex

lib/elixir/lib/version.ex, lib/elixir/test/elixir/version_test.exs
Should close #4407.
According to the SEMVER spec (http://semver.org/#spec-item-10):
> Build metadata MAY be denoted by appending a plus sign and a series
> of dot separated identifiers [...].
The dot was not previously allowed, with this commit it is.
=> Allow dots in the metadata info in Version.parse/1

lib/elixir/lib/inspect.ex
The previous code was erroring out:
```elixir
iex(1)> Inspect.MapSet.inspect(MapSet.new, Inspect.Opts.new)
** (UndefinedFunctionError) undefined function Inspect.Opts.new/0
(elixir) Inspect.Opts.new()
```
Now it works:
```elixir
iex(1)> Inspect.MapSet.inspect(MapSet.new, %Inspect.Opts{})
{:doc_cons, "#MapSet<", {:doc_cons, "[]", ">"}}
```
=> Remove reference to old `Inspect.Opts.new`

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
As described in the [mailing list topic](https://groups.google.com/forum/#!topic/elixir-lang-core/iIDFkQUiXIs), I've wanted to create a faster implementation of *Enum.sum* that is used for Ranges instead. This implementation runs in **O(1)** instead of **O(n)**, which is why I think it was worth the change.
As this is my first contribution to the Elixir project, I fully expect that I might have missed some important part of the guidelines. In that case, please tell me and I will happily improve my coding efforts.
=> Added faster implementation of Enum.sum that works on Ranges. 

lib/elixir/lib/kernel.ex, lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
The following question has been asked in Slack.
> pdilyard [12:08 PM] 
> why does this work:
> ```
> iex> 2 |> + 2
> 4
> ```
> but this doesn’t?
> ```
> iex> 2 |> * 2
> ** (SyntaxError) iex:2: syntax error before: '*'
https://elixir-lang.slack.com/archives/general/p1458184122001480
I believe this is an edge case with operators that work as both unary and binary,
but it should fail.
I therefore modified `Macro.pipe` to fail when the operator is unary.
=> Fix edge case when piping in unary operators.

lib/elixir/lib/map.ex, lib/elixir/lib/map_set.ex, lib/elixir/test/elixir/map_test.exs
Hey folks!
Based upon discoveries made during my little foray into map performance characteristics a few weeks ago I thought I'd give `MapSet` a work over. I was also very curious about the circumstances under which `MapSet` out performs `:lists.subtract` 
Warning: Be careful when benchmarking `--` or `:lists.subtract`. The compiler (I think it's the compiler) does some crazy optimizations when operating on list literals. Always create a module / function like `MyList.subtract/2` and call that instead, otherwise the result will be pre-computed at compile time.
Many of the current functions use `:maps.fold`. Under the covers `:maps.fold` calls `:maps.to_list` first, and then `:lists.foldl`. In many cases `:maps.fold` uses `Map.put` to accumulate desired results in a new map.
This gives us …
=> MapSet Optimizations

lib/elixir/lib/version.ex, lib/elixir/test/elixir/version_test.exs
I was recently working with versions a bit, and `Version.parse!` would be really handy in iex and tests. For now, I'm manually pattern matching in iex, and have a `version!` helper function in tests.
=> Add `Version.parse!/1`

lib/elixir/lib/kernel.ex, lib/elixir/lib/module.ex, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/kernel_test.exs, lib/elixir/test/elixir/module_test.exs
At (@) syntax works with doc value, Module functions with actual representation.
Closes #4418.
=> Make @doc, @doc(value) and get_attribute/2, put_attribute/3 consistent

lib/elixir/lib/integer.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/range.ex, lib/ex_unit/lib/ex_unit/filters.ex, lib/mix/lib/mix.ex, lib/mix/lib/mix/scm/path.ex
- Function checkout/1 has no local return
- Function raise/1 only terminates with explicit exception
- lib/ex_unit/filters.ex:83: The specification for 'Elixir.ExUnit.Filters':eval/4 states that the function might also return {'error',atom()} but the inferred return is 'ok' | {'error',binary()}
- lib/range.ex:73: Overloaded contract for 'Elixir.Range':'range?'/1 has overlapping domains; such contracts are currently unsupported and are simply ignored
- lib/integer.ex:61: Type specification 'Elixir.Integer':digits(non_neg_integer(),pos_integer()) -> [non_neg_integer()] is a supertype of the success typing: 'Elixir.Integer':digits(non_neg_integer(),pos_integer()) -> [non_neg_integer(),...]
=> Spelling & Resolve dialyzer warnings:  no local return and only terminates with explicit exception

lib/elixir/lib/keyword.ex, lib/mix/lib/mix.ex
- lib/keyword.ex:74: Type specification 'Elixir.Keyword':new() -> t() is a supertype of the success typing: 'Elixir.Keyword':new() -> []
- lib/mix.ex:285: Function raise/2 only terminates with explicit exception
=> Fix Mix and Keyword Dialyzer warnings

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
Right now, this funny thing happens:
```elixir
iex> Macro |> Env
Macro.Env
```
This happens because `|>/2` calls `Macro.pipe/3` under the hood, and `Macro.pipe/3` inserts the left-hand side at the beginning of the list of arguments in the AST for the function call on the right-hand
side. Aliases, however, look exactly like a call to the` __aliases__` function:
```elixir
iex> quote do: Macro.Env
{:__aliases__, [alias: false], [:Macro, :Env]}
```
and that's why `Macro |> Env` becomes `Macro.Env`. With this commit, we explicitly take care of `:__aliases__` in a `Macro.pipe/3` call, so that we can error out in such cases:
```elixir
iex> Macro |> Env
** (ArgumentError) cannot pipe Macro into Env, ...
```
Let me know what you think and most of all, if you can think of any other corner cases …
=> Error out when passing :__aliases__ to Macro.pipe/3

lib/elixir/lib/io.ex
Just tacked on some parens to make it consistent with the other defaults that use group_leader()
=> Use parens consistently in some function calls in the IO module

lib/logger/lib/logger.ex, lib/logger/test/logger_test.exs
Right now, code like this:
```elixir
defmodule MyMod do
require Logger
def my_fun(arg) do
Logger.debug(arg)
:ok
end
end
```
will generate an unused variable warning for the `arg` variable in `my_fun/1` if the log level is higher than `:debug`, as discussed in #4417.This happens because in such cases, we completely remove the AST of the Logger call, so the `arg` variable is effectively never used. This may seem magical to the user.
With this PR, a `Logger` call which would have been removed from the AST before now generates a series of `_ = x` expressions, one for each variable passed to the `Logger` macro.
This will still not take care of private functions and unused imports (which will still warn if used in a `Logger` macro), but it's a step forward :). Let me know how it looks and if I …
=> Suppress unused var warnings when removing Logger macros from the AST

lib/logger/lib/logger.ex, lib/logger/lib/logger/utils.ex, lib/logger/test/logger/utils_test.exs
I added the possibility to pass `:infinity` to `Logger.Utils.truncate` to disable truncating logs.
My use case is the following:
* I execute an external command (with a pretty long input)
* When it fails, I log the output into a file to know what happened
The error is normally at the end of the log, which makes it useless when truncated.
I can pass a very large value to `truncate` for this logger, but I thought that being
able to simply disable truncating would be a nicer way to do it.
As the change is quite minimal, I opened a PR directly, but let me know if you would rather
want me to post to the ML.
=> Allow to pass :infinity to Logger.Utils.truncate.

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
This PR should solve #4435. Right now, this nasty error pops out:
```elixir
iex> :foo |> (fn x -> x end)
** (CompileError) iex:1: expected -> clauses in fn
```
This happens because of what we do in `Macro.pipe/3`, which is: we take the AST of a function call as the second argument and insert the first argument in the list of arguments for the function call, at the position specified by the third argument. The AST for a `fn` looks exactly like the AST of a function call (to the `:fn` function):
```elixir
iex> quote do: fn :ok -> :ok; :err -> :err end
{:fn, [], [{:->, [], [[:ok], :ok]}, {:->, [], [[:error], :error]}]}
```
It's easy to see that the "arguments" to `:fn` are the `->` clauses in the function. This means that doing `:foo |> (fn x -> x end)` basically adds another clause to the …
=> Handle non-called anonymous functions in Macro.pipe/3

lib/mix/lib/mix/tasks/compile.erlang.ex, lib/mix/test/mix/tasks/compile.erlang_test.exs
The issue is described [here](https://groups.google.com/forum/#!topic/elixir-lang-talk/2qvsQ9A2-6g)
tl;dr of it is that a situation can happen that a mix task works with an older version of the module written in Erlang. This can occur if some previous task, (e.g. Phoenix compiler) loaded the module before the Erlang compiler recompiled the code. The agreed solution is to make the Erlang compiler purge the module if it is about to be compiled.
=> purge erlang modules on recompilation

lib/elixir/src/elixir_translator.erl, lib/elixir/test/elixir/kernel/errors_test.exs
Right now, when we call a local function inside a match the error message only shows the function name and its arity (`foo/1`). With this commit, we show the full call (`foo(:bar)`) so that it should be easier to locate the error.
This was discussed in #4411. I'm not sure if we should make this change (and show the whole call) for remote functions (and/or for function calls inside guards). Wdyt?
=> Show the full call when calling a function inside a match

lib/elixir/lib/exception.ex, lib/elixir/test/elixir/exception_test.exs
Before, this would not work: `raise ArithmeticError, "I don't like it when you do complicated math"`
This Pull-Request changes that. ArithmeticError, Enum.OutOfBoundsError and Enum.EmptyError can now be raised with a custom message, if desired.
Tests to check if this behaviour is indeed allowed has also been added.
Also see [this topic on the elixir-lang-talk mailing list](https://groups.google.com/forum/#!topic/elixir-lang-talk/KuoqZyNIql4)
=> Allows ArithmeticError, Enum.OutOfBoundsError and Enum.EmptyError to be raised with a custom message.

lib/elixir/lib/option_parser.ex, lib/elixir/test/elixir/option_parser_test.exs
This pull request changes the way OptionParser handles negative numbers, so that it can parse them as arguments or option values:
```
iex(1)> OptionParser.parse(["-43"])
old version: {[], [], [{"-43", nil}]}
new version: {[], ["-43"], []}
```
and
```
iex(2)> OptionParser.parse(["-f", "-43"], strict: [flag: :integer], aliases: [f: :flag])
old version: {[], [], [{"-f", nil}, {"-43", nil}]}
new version: {[flag: -43], [], []}
```
The new version assumes that any input consisting of a dash followed by a string completely parseable as a float (i.e., no remainder at the end) is a negative number, not an option flag.
=> Allow OptionParser to parse negative numbers

lib/elixir/src/elixir_errors.erl, lib/elixir/src/elixir_parser.yrl, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/erlang/string_test.erl, lib/elixir/test/erlang/tokenizer_test.erl
This PR hopes to solve #4419.
Before this PR, we handled char literals (like `?a`) in the tokenizer, turning a literal like `?a` into the token `{:number, _, 97}` (thus indistinguishable from the literal `97` at the parsing stage). This led to error messages with the integer for the character instead of the character literal, e.g.:
```elixir
iex> :ok ?a
** (SyntaxError) iex:11: syntax error before: 97
```
With this PR, we now turn `?a` into the token `{:char, _, 97}` (which is the same token used by Erlang for Erlang char literals like `$a`); since it's the same token as in Erlang, the parser will now output the char literal as an Erlang char (`?a` would be printed as `$a`). We hijack the error message in `elixir_errors.erl` to end up with the correct message:
```elixir
iex> :ok ?a
** …
```
=> Handle chars literals in the parser for better syntax errors

lib/elixir/lib/system.ex, lib/elixir/src/elixir_rewrite.erl, lib/elixir/test/elixir/system_test.exs
Implementation of #4454. 
I did the rest of the `System.*time` a while back so I figured I would implement these as well :smile:.
@josevalim I didn't touch the docs on time; what do you think should be improved? We already link to http://erlang.org/doc/apps/erts/time_correction.html (in all the `System.*time` functions), which as a lot of info around this stuff.
=> Add System.os_time/0,1 and update time-related docs in System

lib/elixir/lib/macro.ex
I saw this warning when compiling some code and was not sure what to do about it. This message suggests a solution.
=> More helpful deprecation warning for piping into unary operator.

lib/elixir/lib/string.ex, lib/elixir/test/elixir/string_test.exs, lib/ex_unit/examples/difference.exs, lib/ex_unit/lib/ex_unit/cli_formatter.ex, lib/ex_unit/lib/ex_unit/formatter.ex, lib/ex_unit/test/ex_unit/formatter_test.exs
=> Add difference highlighting to ExUnit

lib/elixir/lib/system.ex
Adds some more information about arguments provided to System.cmd (mostly being explicit that these are not going through the shell).
=> Expanded docs for System.cmd

lib/mix/lib/mix/dep/lock.ex, lib/mix/test/mix/dep/lock_test.exs
As [proposed in the ML](https://groups.google.com/forum/#!topic/elixir-lang-core/ORl4QArbaxI), I added a user friendly message when `mix.lock` contains conflicts.
=> Add a user friendly error for merge conflicts on mix.lock.

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
Lastest changes introduced in Enum.sum in #4414 changed the type of the return value
(from integer to float) when argument was a range. This commit fixes this.
Adds a spec when dealing with Range.t
It simplifies the function by making it more recursive,
and also deals with ranges where first and last are equal
Tests added
/cc @Qqwy
=> Fix and improve Enum.sum/1 for ranges

lib/elixir/lib/gen_server.ex
* Add missing 'in' to `handle_call`
* Remove extra `reply` from tuple in `handle_cast`
=> Fix typos in GenServer docs

lib/ex_unit/examples/difference.exs, lib/ex_unit/lib/ex_unit/formatter.ex, lib/ex_unit/test/ex_unit/formatter_test.exs
Make it recursive and element-aware, it also should be faster than difference for their `inspect`ed representation (especially when difference is big).
=> Enhance difference highlighting for lists

lib/elixir/src/elixir_translator.erl, lib/elixir/src/elixir_try.erl, lib/elixir/src/elixir_with.erl, lib/elixir/test/elixir/map_test.exs
Hi,
This is another try to fix #4428.
I used @josevalim instructions from #4468, and changed scope `extra` to `nil` before
translating `with`, `try`, `catch`, `rescue`, `case` and `for`.
Please let me know if I forgot something.
Also, I am not sure if we should allow
```elixir
%{(a = 1) => 1}
```
so I left it as is. It seems a bit creepy and the scope is kind of ambiguous
but I am not sure it should raise a `CompilerError` either. What do you think?
=> Allow generated variables in map keys. Fix #4428

lib/elixir/lib/gen_server.ex, lib/elixir/test/elixir/gen_server_test.exs
Now the error message is also raised when you call a global name registered to yourself.
=> Raise error message if you try to GenServer.call/3 yourself globally

lib/ex_unit/examples/difference.exs, lib/ex_unit/lib/ex_unit/formatter.ex, lib/ex_unit/test/ex_unit/formatter_test.exs
Make it recursive and element-aware, it also should be faster than difference for their inspected representation (especially when difference is big).
=> Enhance difference highlighting for tuples

lib/elixir/lib/map_set.ex
The second argument of `delete/2` function of `MapSet` should be `value` instead of `term`. This doesn't affect the compiled code, but it makes the documentation for the `delete/2` function a bit confusing.
=> Updated documentation for delete/2 of MapSet

lib/iex/lib/iex.ex
It seems like the "IEx cannot pry the shell itself" limitation was
removed 3 years ago in 0b624ff but this code wasn't removed.
Found this thanks to Dialyzer and https://github.com/fishcakez/dialyze.
The error printed by Dialyzer was:
> lib/iex.ex:443: The pattern {'error', 'self'} can never match the type 'ok' | {'error','no_iex' | 'refused'}
=> fix(IEx.pry/1): remove unreachable code

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
This should fix the `Macro.to_string` behavior seen in #4524.
=> Fix Macro.to_string keyword blocks in normal function calls

lib/elixir/lib/record.ex
Simple console test:
```
require Record
defmodule Records do Record.defrecord :rec, [k1: 5, k2: 10, k3: "ababa"] end
require Records
Records.rec()
Records.rec(_: :_)
Records.rec(_: :_, k2: 7)
```
If Dict is deprecated an option is to use :proplists.get\_value/3
TODO: 
Add similar behavior on update. 
Add record_info/2.
=> Support for Erlangs #rec{_ = '_' } and for record_info/2

lib/elixir/test/elixir/kernel/sigils_test.exs
As discussed here: 
https://groups.google.com/forum/#!topic/elixir-lang-core/89yO3X-oGsM
=> Add more tests for sigil `~w` interpolation behaviour

lib/eex/test/eex_test.exs, lib/elixir/lib/code.ex, lib/elixir/lib/kernel/special_forms.ex, lib/elixir/src/elixir_errors.erl, lib/elixir/src/elixir_interpolation.erl, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/src/elixir_utils.erl, lib/elixir/test/elixir/enum_test.exs, lib/elixir/test/elixir/file_test.exs, lib/elixir/test/erlang/string_test.erl, lib/elixir/test/erlang/tokenizer_test.erl, lib/ex_unit/lib/ex_unit/doc_test.ex, lib/ex_unit/test/ex_unit/assertions_test.exs, lib/iex/test/iex/helpers_test.exs, lib/iex/test/test_helper.exs, lib/logger/lib/logger/utils.ex, lib/mix/test/mix/rebar_test.exs, lib/mix/test/mix/shell_test.exs
Standardizes the use of comma leaving a white space after it whenever applicable.
Note #1: In the changed lines it also adds a white space surrounding the `|` when there is  more than one element to the left.
Example: before was `[a,b|tail]` now it is: `[a, b | tail]`.
.Note #2: It does not enforce this in quantifiers in regular expressions such as in: `x{1,3}`
=> Formatting: add white space after comma

lib/elixir/lib/kernel.ex
Continuing the idea of #4532, I've added a doctest so we have at least one example of this behaviour in the docs.
=> Add ~w doctest to highlight the behaviour of white space inside interpolation

lib/elixir/pages/Typespecs.md
As far as I can tell, this is not documented anywhere.  Feel free to move or rewrite this as you see fit.
=> Update Typespecs doc page to mention argument/element naming.

lib/elixir/lib/string.ex
This once was `iex> << eacute :: utf8 >> = "é"` but the variable name became out of sync.
=> Adjust a String code example

lib/mix/lib/mix/tasks/escript.build.ex, lib/mix/test/mix/tasks/escript_test.exs
Minor improvement / polish. Not sure this is worth merging in, yet submitting it in case!
I could go down the road and check that `main` is implemented on the target module too, yet I wanted to get my feet wet first.
=> Return explicit error if escript main_module target is undefined

lib/elixir/lib/calendar.ex
The [IANA tz database](https://www.iana.org/time-zones) is the source of the time zone IDs.
Also adds a few examples and changes "timezone" to "time zone", which adds consistency since the field name is `time_zone` and not `timezone`.
=> Change documentation for some Calendar fields.

lib/logger/lib/logger.ex
Converts return value of functions passed into Logger into a string.
Notice how this line doesn't convert `data.()` to a string:
[https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger.ex#L590](https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger.ex#L590)
And this line converts `data` to a string:
[https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger.ex#L594](https://github.com/elixir-lang/elixir/blob/master/lib/logger/lib/logger.ex#L594)
I believe the intent is for data to be converted into a string value.
To replicate the bug:
* checkout branch 23dd2723bd43d3eef0991d3d35eb50a7362796b3
* launch iex
* use the following code block
```
defmodule Handler do
use GenEvent
def handle_event({_,_,{_,message,_,_}}, state) do
IO.puts "the …
```
=> Stringify truncated function data in Logger

lib/elixir/lib/io.ex, lib/elixir/lib/io/stream.ex, lib/elixir/test/elixir/io_test.exs
IO Module:
* Impoves wording in documentation, particularly in the use of :all, :line, count
* Standardizes arg names to be `line_*`.
* Adds function guards to check for integers.
* Unicode is a proper noun, so it should be always capitalized.
* Adds backticks to args suchs as `device`, `item`, `count`.
* When functions are "Unicode unsafe", they are indicated in the first paragraph of docs.
* IO.puts: code simplified removing unnecessary variable.
* Adds \n to example in IO.gets/2
* Adds example in IO.chardata_to_string/1 when dealing with strings
* Renames args in IO.each_stream/2 and IO.each_binstream/2
* Adds tests for IO.getn/2-3 calling functions with different arities
IO.Steam Module:
* Adds a note about side effects when dealing with IO streams.
=> IO: Several improvements

lib/elixir/lib/exception.ex, lib/ex_unit/lib/ex_unit/formatter.ex, lib/ex_unit/test/ex_unit/doc_test_test.exs
=> Fix ExUnit stacktrace formatting when its entry has no location

lib/iex/lib/iex/helpers.ex
I always tend to get a bit surprised when I see `c/2` only in the helpers documentation so I thought this would be useful to have. It's also consistent with other helpers which follow a similar pattern like `v/0` & `v/1`.
=> Add c/1 documentation

lib/mix/lib/mix/tasks/do.ex, lib/mix/test/mix/tasks/do_test.exs
I often forget the space after the comma when using `mix do`,
so I changed the task a little to allow separating tasks only with a comma,
so we can for example write.
```
mix do deps.get,compile, release
```
=> Do not force spaces between arguments in mix do

lib/eex/test/eex_test.exs, lib/elixir/lib/calendar.ex, lib/elixir/lib/kernel/special_forms.ex, lib/elixir/lib/path.ex, lib/elixir/lib/regex.ex, lib/elixir/lib/system.ex, lib/elixir/src/elixir_interpolation.erl, lib/elixir/test/elixir/regex_test.exs, lib/elixir/test/elixir/string_test.exs, lib/elixir/unicode/unicode.ex, lib/logger/lib/logger/utils.ex
- Unicode is a proper noun, so it should be capitalized
- Replace 'charlist' with 'char list' or 'char_list'
- Replace 'char data' with 'chardata'
- Correct use of a/an articles
=> Standardize unicode and friends

CHANGELOG.md, lib/elixir/lib/range.ex, lib/elixir/test/elixir/range_test.exs
- Range.range?/1: Checks for valid ranges
- Range.t typespec: args are integers
Can anybody please confirm that this is the correct definition:
`@type t(first :: integer, last :: integer) :: %Range{first: integer, last: integer}`
=> Range: Enforce integers values

lib/elixir/lib/enum.ex, lib/elixir/lib/stream.ex
I confused myself the other day by accidentally doing:
```elixir
iex(1)> 1..10 |> Enum.chunk(1, [], [])
```
Instead of blowing up this actually produces
```
[[1], [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]]
```
This happens because `[] > 0` is valid in the guard clause.
I add `is_integer` checks to args 2 and 3 in order to make sure that they're actually numbers.
=> Ensure args 2 and 3 to Enum,Stream.chunk/3,4 are integers

lib/elixir/lib/enum.ex
Noticed it while browsing the docs, just a small doc fix :) Seems to be the only reference of `stream` in the Enumerable module save the ones explaining the difference between `Enum` and `Stream` (or using/requiring some `Stream`) stuff.
=> Keep naming it enumerable for documentation consistency in Enumerable module

lib/elixir/lib/enum.ex, lib/elixir/lib/stream.ex
* got me by surprise today as I always thought it'd do the
equivalent of List.flatten/1 so seemed nice to get some
examples
Not quite sure yet about the added doc to Stream.flat_map - as it is described quite differently in Enum.flat_map but that's also probably due to their different nature.
Enum doc:
```
Returns a new enumerable appending the result of invoking `fun` on
each corresponding item of `enumerable`.
The given function must return an enumerable.
```
=> Clarify that flat_map only flattens one level deep

lib/elixir/lib/string.ex, lib/elixir/test/elixir/string_test.exs, lib/elixir/unicode/unicode.ex
This fixes https://github.com/elixir-lang/elixir/issues/4604.  
:information_desk_person: No new tests were added, only reverted the two failing specs from this commit: 107a185209dabad4147a9c5d27a7c44a60004599
=> Fix nfd normalization bug

lib/elixir/lib/file.ex
I have updated the modes, since many were missing. In docs as well as in typespecs
=> [WIP] File.open/2: complete list of modes

lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/test/ex_unit_test.exs
First, it should be noted that the below-described "problem" **is expected** (and tested) by ExUnit.
This pull-request suggests that behavior be changed.
Given a test having duplicate names defined as the following:
```elixir
ExUnit.start
defmodule TestWithSameNames do
test "foo" do
assert true == true
end
test "foo" do
assert true == true
end
end
```
The second test is not run and the warning that is output is not very helpful to the untrained eye.
```
$ elixir example.exs
example.exs:10: warning: this clause cannot match because a previous clause at line 6 always matches
.
1 test, 0 failures
```
In order to understand the warning, the user must know that ExUnit defines functions based on the test names.
This is an implementation detail that the user shouldn't have to …
=> Friendly error message for duplicate ExUnit test names

lib/elixir/lib/kernel/parallel_compiler.ex, lib/mix/lib/mix/compilers/elixir.ex
I added the `:each_waiting` and `:waiting_timeout` options to `Kernel.ParallelCompiler.files/2`. These option control what to do when a file it's taking longer than `:waiting_timeout` to compile: in such cases, the `:each_waiting` function is called with that file as its argument.
I also updated the Elixir compiler so that it now prints 
> Compiling lib/foo.ex (it's taking longer than 5 seconds)
during compilation. This is a step towards fixing #4585. I still haven't suppressed the "Compiled lib/foo.ex" messages as I think it's better to do one thing at a time (there are also a lot of tests to update if we suppress that).
The diff is pretty big because `Kernel.ParallelCompiler.spawn_compilers/8` has a lot of clauses and I had to update all of them (and I managed to raise the record of …
=> Add an :each_waiting option to Kernel.ParallelCompiler

lib/elixir/lib/kernel/cli.ex, lib/elixir/lib/kernel/parallel_compiler.ex, lib/mix/lib/mix/compilers/elixir.ex
I renamed those to `:each_long_compilation` and `:long_compilation_threshold`.
Tests are failing because we didn't update them when disabling the "Compiled lib/foo.ex" messages. A PR is coming for that :)
=> Rename :each_timeout and :timeout compiler options

lib/elixir/src/elixir_translator.erl, lib/iex/test/iex/helpers_test.exs
Implements changes suggested by @josevalim at #4596.
```elixir
iex> import String
String
```
```elixir
iex> require String
String
```
```elixir
iex> alias String
String
```
```elixir
iex> alias String, as: Foo
String
iex> alias Foo, as: Bar
String
```
```elixir
iex> alias String.{Break, Casing, Chars}
[String.Break, String.Casing, String.Chars]
```
Little updates to section 13 of the [Getting Started](https://github.com/elixir-lang/elixir-lang.github.com/blob/master/getting-started/alias-require-and-import.markdown) may be required, so I will take care of it upon merge.
This is my very first PR to this project, but I am really eager to keep contributing.
We are using Elixir extensively at [Stampery](https://github.com/stampery), so we will try to give back as much as possible to this …
=> Make lexicals (alias, import and require) return the given module(s) instead of nil

lib/elixir/lib/kernel/parallel_compiler.ex, lib/mix/lib/mix/compilers/elixir.ex, lib/mix/lib/mix/tasks/compile.elixir.ex
This option changes the value of the `:long_compilation_threshold` option in `Kernel.ParallelCompiler.files/2`.
=> Add a --long-compilation-threshold option to "mix compile"

lib/elixir/lib/exception.ex, lib/elixir/lib/io.ex, lib/elixir/src/elixir_errors.erl, lib/elixir/src/elixir_parser.yrl, lib/elixir/test/elixir/io_test.exs
What if we use colon as warning prefix separator and 1 indentation level for stacktrace (we don't have exception banner anyway) as it looks too wide right now?
__Before__:
__After__:
=> Improve warning output

lib/elixir/lib/enum.ex
The sentence seemed a bit strange, wanted to make it more understandable.
Also wanted to convey that the "compared equal" part only applies/matters to the smallest/biggest element.
Still not sure, if this is really good. Might want to check with a native speaker, to me it read a bit strange so tried to improve upon it.
Also included a second commit, adding the inline doc `iex` for min/max/min_max_by to show the mentioned behavior that the first biggest/smallest element is returned.
2 commits so if wanted only one of them could be taken. Also happy to squash or let github squash it.
=> Enum documentation: Reformulate the returned element for min/max/max_by 

lib/elixir/pages/Writing Documentation.md
Some minor stuff I saw in passing.
GitHub does not highlight the change in the second chunk: "modules and function names" becomes "module and function names".
=> Minor fixes in "Writing Documentation" [ci skip]

lib/ex_unit/lib/ex_unit.ex, lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/lib/ex_unit/cli_formatter.ex, lib/ex_unit/test/ex_unit_test.exs, lib/iex/test/iex/helpers_test.exs
As per #4159:
* Adds `:type` field that defaults to `:test` to `ExUnit.Test` struct
* Adds `ExUnit.plural_rule/{1,2}` and tests
* Group `ExUnit.Test` completions by `:type` for display in
`ExUnit.CLIFormatter`
This PR also includes a separate commit that implements what might be a good interface for setting the type of a test (based on a new tag `:type` for tests), and tests for the `ExUnit.CLIFormatter` display for tests with a non-`:test` `:type`.
If that interface doesn't work for us for whatever reason, I can back that out and whenever we do come up with an appropriate interface it can be added to the initial commit with updated tests that use the final interface.
=> Test noun customization

lib/elixir/pages/Writing Documentation.md
This PR proposes a revision of the "Privacy" section in "Writing Documentation".
The current "Privacy" section starts saying things about private functions, that they cannot be documented, etc., and then starts explaining a few techniques.
But I think that's not really the point of this section. This section is really about hiding documentation for modules and public functions that do not belong to the public interface for end users.
This proposal then splits this in two sections: The first one is similar to the original and introduces the common use case for hiding documentation which is having two levels of (technically) public interface.
Then a new section explains how private functions are conventionally documented in Elixir.
=> Rewords the section about hiding docs in "Writing Documentation"

bin/elixir.bat, bin/elixirc.bat, bin/iex.bat
Add help information to iex.bat.
Support '/?' command line switch to show help also in elixir.bat and elixirc.bat - under windows '/?' is widely-used.
=> Windows: batch file improvements

lib/elixir/lib/kernel/lexical_tracker.ex
Resolves #4645.
Pretty straightforward, replaces the ets table (which was not used from more than one process) with two maps. Also changes the state of `Kernel.LexicalTracker` to a map to support future expansion.
=> Replace ets table in Kernel.LexicalTracker with a map

lib/ex_unit/lib/ex_unit/callbacks.ex, lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/test/ex_unit_test.exs
The `async` config is meant to be set only by the time `ExUnit.Case` is used. With these changes we make sure a proper error will be raised if we eventually try to override it, either at the setup step, for the whole case as a `moduletag`, or as a regular test tag.
=> Disable overriding the async tag

lib/elixir/lib/kernel/lexical_tracker.ex
We no longer store state in ETS so the paragraph is outdated and I simply removed it.
Alternatively, this paragraph could read e.g.:
> The implementation simply stores dispatch information in GenServer with two maps: one for directives and one for references.
This information is being used during compilation.
(as far as I know LexicalTracker is being used during compilation not sure to what part of build process "once compilation is done" was referring to (pardon my ignorance) :-))
=> Update docs for LexicalTracker

lib/elixir/lib/uri.ex, lib/elixir/test/elixir/uri_test.exs
Merge a relative path/URI to a base URI as per RFC3986 §5.2
Examples:
iex> URI.merge("http://example.com/foo", "/bar") |> to_string
"http://example.com/bar"
iex> URI.parse("http://example.com/foo") |> URI.merge("bar") |> to_string
"http://example.com/bar"
…and more
=> URI.merge/2

lib/elixir/lib/uri.ex
I added parens to a bunch of parens-less `to_string/1` calls that will warn in Elixir v1.4.
=> Polish docs for URI.merge/2 and fix a bunch of future warnings

lib/elixir/lib/option_parser.ex, lib/elixir/test/elixir/option_parser_test.exs
this is a follow-up to what was discussed:
https://groups.google.com/d/msg/elixir-lang-core/HNTvvzY8VCk/x1861JwwBgAJ
I want a strong option parser like the [Python ArgumentParser]
(https://docs.python.org/2/library/argparse.html);
however, to support `-vn` means same as `-v -n` is harder than I
thought, that will be in another PR.
=> improve option_parser.ex to support counter

lib/elixir/lib/kernel/typespec.ex, lib/elixir/pages/Typespecs.md, lib/elixir/test/elixir/kernel/typespec_test.exs
* Removes <<_::size*unit>>
* Adds <<_::size, _::_*unit>>
Closes #4669.
=> Fix binary typespecs

lib/elixir/lib/kernel/typespec.ex, lib/elixir/lib/system.ex, lib/elixir/pages/Typespecs.md, lib/elixir/test/elixir/kernel/typespec_test.exs, lib/mix/lib/mix/project.ex
* %{required(foo) => bar} and %{optional(foo) => bar} forms are added
* %{foo => bar} is deprecated in favor of the above forms
* %{...} is added to mean any map
* %{} now means empty map
=> Add support for OTP 19 map typespecs

lib/elixir/lib/kernel/lexical_tracker.ex, lib/elixir/src/elixir_dispatch.erl, lib/elixir/src/elixir_fn.erl, lib/elixir/src/elixir_lexical.erl, lib/elixir/test/elixir/kernel/lexical_tracker_test.exs, lib/mix/lib/mix/tasks/xref.ex, lib/mix/test/mix/tasks/xref_test.exs
Related: #4656.
`mix xref --callers` accepts a `Module`, `Module.function`, or `Module.function/arity`.
Output looks like:
```
file: lib/a.ex
A.a/0:2,3
```
I chose this format because:
* it looks good if you are simply manually using the task
* file paths can have all kinds of weird characters in them (like `:` and `"` and `,`) and this should hopefully simplify parsing for libraries that will rely on the output of this task without having to define any kind of escaping
The task also returns data like:
```elixir
[{"lib/a.ex", [{A, :a, 0, [3, 2]}]}]
```
from `run`, so if you use it from within Elixir itself you don't have to parse anything.
Do we need any additional switches, like maybe `--silent` (for use from Elixir apps that will simply use the return value of `run`)?
I also added some …
=> Add `mix xref --callers M.f/a`

lib/elixir/lib/string.ex
Prior wording of this was awkward. This makes it much clearer that `:infinity` is the default `parts:` option.
=> Small wording fix to String.split/3 documentation

lib/elixir/lib/uri.ex, lib/elixir/test/elixir/uri_test.exs
(related to #4685)
According to the grammar at https://tools.ietf.org/html/rfc3986#appendix-A, a host can have colons in it only if it's a "IPv6" or a "IPvFuture"; in both cases, it's expected to be surrounded by square brackets. This means that when converting a URI to a string in `URI.to_string/1`, we can simply surround a host with square brackets if it contains one or more colons.
Actually, I'm not sure why we're stripping brackets *from the authority* when parsing IPv6 addresses. If given `"http://[2001:db8::]:8080"`, shouldn't the authority be `"[2001:db8::]:8080"`? And actually, shouldn't the host be `"[2001:db8::]"` as well? Give the following productions of the grammar:
```
host          = IP-literal / IPv4address / reg-name
[...]
IP-literal    = "[" ( IPv6address / IPvFuture  ) …
```
=> Use square brackets for IPv6 in URI.to_string/1

lib/elixir/lib/kernel.ex
I think we should avoid calling lists arrays. I looked up the docs for `Kernel.apply` to see if it would accept a tuple, and was surprised to see the word "array" in there.
I did a quick search through the source, and the only other mention of "array" is in the docs for `Logger.Formatter.compile/1`, but it can return either List or Tuple, so I'm less inclined to change it to "a list".
=> Clarify args in docs for `apply`

lib/ex_unit/lib/ex_unit/case.ex
The documentation here a bit confusingly worded to make it sound like with `async: true` each `test` declaration in the case would run asynchronously. I've tried to reword it and make it clear that the flag is set for the test case itself.
Example of confusion: #3580. I found that thread when trying to find the same answer for why six tests with `:timer.sleep(1000)` were running in serial within a single test case.
=> Clarify the use of `async: true`

lib/elixir/lib/enum.ex, lib/elixir/lib/stream.ex, lib/elixir/lib/stream/reducers.ex, lib/elixir/test/elixir/enum_test.exs, lib/elixir/test/elixir/stream_test.exs
While practicing my kata at http://www.codewars.com/kata/how-green-is-my-valley/ and enjoying myself learning Elixir in general, I ended up in a situation where I want to split a sorted enumerable into two: One enumerable consisting of every other element, and the other enumerable the remaining elements. 
Enum.take_every readily solved one case, but there was no opposite version Enum.drop_every. Strange, I thought, drop_while/take_while is there, drop/take is there. I really need an Enum.drop_every!
I think more people than me would find it really handy to have a Enum.drop_every complementing Enum.take_every.
Will this solve my Kata? Nope, they are still on Elixir 1.2.4 😛
=> Implement Enum.drop_every

lib/ex_unit/examples/difference.exs, lib/ex_unit/lib/ex_unit/diff.ex, lib/ex_unit/test/ex_unit/diff_test.exs
Hello! I had a go at showing whitespace in diffs.
This now replaces diff fragments entirely made of spaces with a sequence of the open box character (␣), for legibility.
An alternative to this character could be changing the background colour.
I was unsure how to test this. There doesn't seem to be any for the CliFormatter? I have added an ExUnit example.
Related to #4682
=> Show whitespace in ExUnit diffs

lib/elixir/pages/Typespecs.md
I'm not sure it if should read `| Remotes` or `| Remote` on line #37
=> Correct typespec group names

lib/elixir/lib/gen_server.ex, lib/elixir/test/elixir/module_test.exs
This should finish up the stuff needed to close #4546.
=> Add GenServer.format_status/2 and use GenServer over :gen_server as the behaviour

lib/ex_unit/lib/ex_unit/assertions.ex, lib/ex_unit/lib/ex_unit/cli_formatter.ex, lib/ex_unit/lib/ex_unit/formatter.ex, lib/ex_unit/test/ex_unit/assertions_test.exs
I would like to pad the message better, at the moment it ends up looking like this:
```
iex(2)> assert :a == :b
** (ExUnit.AssertionError) Assertion with == failed
code: :a == :b
lhs:  :a
rhs:  :b
lib/ex_unit/assertions.ex:287: ExUnit.Assertions.assert/2
```
```
iex(2)> spawn_link fn -> assert :a == :b end
** (EXIT from #PID<0.57.0>) an exception was raised:
** (ExUnit.AssertionError) Assertion with == failed
code: :a == :b
lhs:  :a
rhs:  :b
lib/ex_unit/assertions.ex:287: ExUnit.Assertions.assert/2
```
Since we don't have any information about how nested the messages are in Exception.message, adding the appropriate padding seems very difficult, if not impossible. Happy to accept any feedback on how we should format it, given that limitation. I was considering adding an additional newline …
=> Enhance the ExUnit.AssertionError message.

lib/elixir/lib/uri.ex
Only the spec for `URI.query_decoder/1` worries me as it returns a function which is however semantically a stream (and this is what we mention in the documentation), so I chose to return `Stream.t`. Is this ok? Should we update `Stream.t` to include functions?
=> Add specs to the URI module

lib/logger/lib/logger/backends/console.ex
Hi I've been doing some experiments that you can try out and veryify the result:
https://github.com/olafura/test_io
With sending messages directly to user_drv we are able to have less blocking, significantly less cpu time and less memory usage over all.
I'm making these changes to Logger and not IO directly since IO does a lot more than just print things to the console.
It's not faster per se at putting thing on the terminal but that is something that is going to be difficult to make faster according to my tests.
We might want to handle these reply cases:
https://github.com/erlang/otp/blob/maint/lib/stdlib/src/io.erl#L573
I'm currently pushing everything back to self so it won't be blocking
=> Better logger for console with direct access

lib/elixir/lib/calendar.ex
This Pull Request fixes the grammar in the [Calendar documentation](http://elixir-lang.org/docs/master/elixir/Calendar.html), as well as making it more clear what is meant by `number in numbers`.
=> Fix Calendar @moduledoc about date subdivision overspecification.

lib/mix/lib/mix/tasks/profile.fprof.ex, lib/mix/test/mix/tasks/profile.fprof_test.exs
Implements #4723.
Had to modify an existing test that was profiling a file which defined a module, because now that warmup happens by default it was causing a module redefined error during the test suite. Let me know if there is some other way that should have been solved.
/cc @josevalim
=> mix profile.fprof --warmup

lib/elixir/lib/string_io.ex, lib/elixir/test/elixir/string_io_test.exs
StringIO is a unicode device. I wonder how many people rely on this bug? `IO.binwrite/2` says do not use this on a unicode device.
=> Fix default encoding for put_chars in StringIO

lib/logger/lib/logger.ex
=> Fixed typo in Logger reset_metadata documentation

lib/mix/lib/mix/tasks/escript.install.ex
Seems like a missed find/replace from archive.install?
=> Fix reference to "archive" in Mix.Tasks.Escript.Install

lib/elixir/lib/module.ex
Would close #4737.
\cc @josevalim and @lexmag, just wanted to check with you if it's ok to not align the `-`s in the list of reserved attributes (since we're gonna change all of those anyways just to move them to the right).
=> Mention @optional_callbacks in the documentation for Module

lib/elixir/lib/string.ex, lib/elixir/lib/uri.ex, lib/elixir/pages/Typespecs.md, lib/elixir/test/elixir/string_test.exs
Convert hex to use uppercase after "x", ie: 0xffff to 0xFFFF, and \u{0fffe} to \u{0FFFE}
=> User uppercase letter in Hexadecimal values

lib/elixir/lib/system.ex
- Fix erlang.org to always be www.erlang.org
- Convert to link plain URL
=> Standardize links

lib/elixir/lib/calendar.ex
The `T` separator is only relevant for Time and Datetime formats.
=> Remove reference to iso8601 T separator for Date

lib/logger/lib/logger.ex
Use flush/0 instead of GenEvent.which_handlers(:error_logger) in Logger.add_backend/2 and Logger.remove_backend/2
See: https://groups.google.com/forum/#!topic/elixir-lang-talk/TrekCMxEZAE for more info
=> Use flush/0 in Logger instead of GenEvent.which_handlers

lib/elixir/test/elixir/application_test.exs
```
2) test application directory (ApplicationTest)
test/elixir/application_test.exs:53
Assertion with == failed
code: String.downcase(Application.app_dir(:elixir)) == String.downcase(Path.join(root, "bin/../lib/elixir"))
lhs:  "d:/home/docs/dev/git_repos/robi-wan-elixir/lib/elixir"
rhs:  "d:/home/docs/dev/git_repos/robi-wan-elixir/bin/../lib/elixir"
stacktrace:
test/elixir/application_test.exs:55: (test)
```
`Application.app_dir(:elixir)` delivers under Windows (7 Pro 64bit) an absolute path:
```
iex(1)> Application.app_dir(:elixir)
"d:/home/docs/dev/git_repos/robi-wan-elixir/lib/elixir"
```
Under Linux (Ubuntu 16.04 64bit) it delivers a relative path:
```
iex(1)> Application.app_dir(:elixir)
"/home/robi-wan/development/work/robi-wan-elixir/bin/../lib/elixir"
```
`Application.app_dir/1` …
=> ApplicationTest fails under Windows

lib/elixir/lib/calendar.ex
Make microsecond fields for Time, NaiveDateTime, DateTime default to `{0, 0}` which is equivalent to "nil microsecond".
Closes #4769
=> Default microsecond fields for Time, NaiveDateTime, DateTime

lib/elixir/lib/kernel/parallel_compiler.ex
When a module waits a struct, only the module or struct found message
will be sent, not both.
=> Fix parallel compiler to only send found message once

lib/elixir/lib/float.ex, lib/elixir/lib/integer.ex
The documentation for `Float.parse` has a mention of `String.to_float`, this patch adds a similar reference for `Integer.parse` in the function documentation.
=> Add a reference to String.to_integer in the doc

Makefile, lib/elixir/pages/Behaviours.md, lib/elixir/pages/Typespecs.md
@josevalim and I discussed this on IRC. There were three options for where to add this documentation:
1. in the documentation for `Module` - I don't like this because it's hard to find in the documentation and it gets buried with all the rest of the information already present in the docs for `Module`
1. in the "Typespecs" page - I don't like this because behaviours and typespec only have a small-ish intersection (the actually specs for callbacks), but behaviours extend beyond specs IMO
1. as a separate page - I like this, and it's what I went with 😃
=> Add a "Behaviours" page to the documentation

lib/mix/lib/mix/tasks/new.ex, lib/mix/test/mix/tasks/new_test.exs
Triggered from this tweet: https://twitter.com/HugoGiraudel/status/738694810350014464
> This is your friendly reminder that semantic versioning starts at 0.1.0, not 0.0.1. You can’t start with a bug fix.
Also documented in Semantic Versioning's FAQ (http://semver.org/#how-should-i-deal-with-revisions-in-the-0yz-initial-development-phase)
> The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.
=> Use 0.1.0 as default first version in `mix new` task

lib/elixir/lib/calendar.ex
This PR has two commits. One is general fixes of invalid types in the examples (e.g. invalid microsecond fields). The other commit makes it possible to use DateTime.to_unix with any DateTime struct, not just UTC.
=> add DateTime.to_unix/2 can accept non-UTC DateTime structs

lib/mix/lib/mix/tasks/app.tree.ex, lib/mix/lib/mix/tasks/deps.tree.ex, lib/mix/lib/mix/utils.ex, lib/mix/test/mix/tasks/app.tree_test.exs, lib/mix/test/mix/tasks/deps.tree_test.exs
Inspired by @josevalim's ElixirConf.EU keynote.
This is currently a work in progress, but feedback is more than welcome.
/cc @mootpointer
=> Option for `mix app.tree` and `mix deps.tree` to be output as DOT file

CHANGELOG.md
I noticed this difference in behavior while upgrading my application, but did not see it called out in the changelog anywhere so thought I'd add it.
On 1.2, here's how `group_by` behaved:
iex(1)> 1..10 |> Enum.group_by(fn i -> i < 5 end)
%{false: [10, 9, 8, 7, 6, 5], true: [4, 3, 2, 1]}
On 1.3, here's how it behaves:
iex(1)> 1..10 |> Enum.group_by(fn i -> i < 5 end)
%{false: [5, 6, 7, 8, 9, 10], true: [1, 2, 3, 4]}
=> Document change in behavior of `Enum.group_by` ordering.

lib/elixir/lib/map.ex, lib/elixir/test/elixir/map_test.exs
Without this, it was fine to not pass a map as the first argument to `Map.take/2`, `Map.drop/2`, and `Map.split/2` if the second argument was an empty enumerable of keys:
```elixir
iex> Map.take(:foo, [])
%{}
iex> Map.take(:foo, [:bar])
** (BadMapError) expected a map, got: :foo
```
With this commit, we always check for the first argument to be a map:
```elixir
iex> Map.take(:foo, [])
** (BadMapError) expected a map, got: :foo
```
=> Add a is_map/1 guard to Map.take/2, Map.drop/2, and Map.split/2

lib/mix/lib/mix/tasks/deps.compile.ex, lib/mix/test/mix/tasks/deps_test.exs
@josevalim @ericmj  this is a first stab.
~~The test does not pass, but I wanted to check if I am on track.~~
~~The condition `if "--force" in args do` gets hit, but I wonder why the file does not disappear.~~
~~I wonder if I am placing the "tracer-file" in the right place?~~
It should be working now.
To verify that the cleaning happens I add a tracer file and ensure its removed afterwards.
Any feedback/ideas/suggestions welcome ❤️
=> Clean deps when deps.compile is run with --force

lib/mix/lib/mix/tasks/app.tree.ex, lib/mix/lib/mix/tasks/deps.tree.ex, lib/mix/lib/mix/utils.ex
Added an SVG example for converting the generated `.dot` file.
The intention of this is that users don't have to instantly go and hunt
for the docs if they already have graphviz installed.
This should work as is on Windows too, once installed and in the path.
=> More informative message for DOT tree generation

lib/elixir/src/elixir_scope.erl
The unsafe variable warning can be triggered from the following `with`:
state = true
with true  <-state, state = !state,
do: state,
else: (other -> {other, state})
=> Include with when warning about unsafe variables

lib/mix/lib/mix/config.ex, lib/mix/test/fixtures/configs/imports_recursive.exs, lib/mix/test/fixtures/configs/recursive.exs, lib/mix/test/mix/config_test.exs
- Closes [#4757](https://github.com/elixir-lang/elixir/issues/4757)
- Note that signature of `Code.eval_file/1` has been modified to allow
pass-through of options to `Code.eval_string/3`.
=> Check for recursive imports in config files.

lib/elixir/test/elixir/kernel/sigils_test.exs
SigilsTest fails for newline under Windows
```
1) test sigil S (Kernel.SigilsTest)
lib/elixir/test/elixir/kernel/sigils_test.exs:18
Assertion with == failed
code: ~S"foo\\\r\nbar" == "foo\\\nbar"
lhs:  "foo\\\r\nbar"
rhs:  "foo\\\nbar"
stacktrace:
lib/elixir/test/elixir/kernel/sigils_test.exs:32: (test)
```
[Newlines](https://en.wikipedia.org/wiki/Newline).
[Github](https://help.github.com/articles/dealing-with-line-endings/#platform-windows) recommends setting `core.autocrlf true` on Windows for cross-platform projects.
[Git documentation](https://git-scm.com/book/tr/v2/Customizing-Git-Git-Configuration#Formatting-and-Whitespace) also recommends this setting on Windows.
Using this setting let the SigilsTest fail because the sigil contains a newline which is `\r\n` under Windows and not …
=> Fix failing SigilsTest for newline under Windows

lib/elixir/test/elixir/kernel/dialyzer_test.exs
Under Windows (7 Pro, 64 bit) the Kernel.DialyzerTest fails:
```
1) Kernel.DialyzerTest: failure on setup_all callback, tests invalidated
** (ErlangError) erlang error: {:dialyzer_error, 'The HOME environment variable needs to be set so that Dialyzer knows where to find the default PLT'}
stacktrace:
dialyzer.erl:173: :dialyzer.run/1
lib/elixir/test/elixir/kernel/dialyzer_test.exs:21: Kernel.DialyzerTest.__ex_unit_setup_all_0/1
lib/elixir/test/elixir/kernel/dialyzer_test.exs:3: Kernel.DialyzerTest.__ex_unit__/2
```
Actually this is an erlang error: [dialyzer expects the environment variable HOME set](https://github.com/erlang/otp/blob/e1489c448b7486cdcfec6a89fea238d88e6ce2f3/lib/dialyzer/src/dialyzer_plt.erl#L229-L232).
But Windows does not have this environment variable available.
(It has …
=> Fix failing Kernel.DialyzerTest under Windows

lib/mix/lib/mix/tasks/compile.ex
Typo. should be `yecc` instead of `yeec` in the documentation
=> `yecc` instead of `yeec`

lib/elixir/lib/map.ex
In this PR I mostly
* polished docs for the `Map` module (first commit)
* added some `is_function/2` guards to some functions in `Map` (second commit)
* made some errors better in `Map` (e.g., `:erlang.error({:badkey, key})` becomes `raise KeyError, ...` (third commit)
The first commit should be an instamerge, but I was not 100% sure about the other two as they may be considered to break backwards compatibilty (I'm not sure because people shouldn't rely on unspecified behaviours). This is why I split the PR into separate commits, I can nuke them singularly if needed :)
=> Some improvements to the Map module

lib/elixir/src/elixir_def.erl
When reading the code I noticed 3 warnings from erlang:
1. variable `FinalAnn` unsafe in `case`
2. variable `FinalLocation` unsafe in `case`
3. variable `FinalDefaults` unsafe in `case`
Which can be eliminated with pattern matching at the return of the case statement.
=> Simplify code to remove warning: unsafe in 'case'

lib/mix/lib/mix/tasks/app.tree.ex, lib/mix/lib/mix/tasks/deps.tree.ex, lib/mix/lib/mix/tasks/xref.ex, lib/mix/lib/mix/utils.ex, lib/mix/test/mix/tasks/app.tree_test.exs, lib/mix/test/mix/tasks/deps.tree_test.exs, lib/mix/test/mix/tasks/xref_test.exs
Implements #4810.
Maybe it would be nice to also emit whether it's a runtime or compile time dep as edge_info in --format dot? I'm not sure it's worth the extra effort. Thoughts?
/cc @josevalim @michalmuskala
=> mix xref graph

lib/ex_unit/test/ex_unit/describe_test.exs
It was ExUnit.BundleTest, in memory of ancient times when "describe" was called "bundle". 😛
=> Fix the name of the ExUnit.DescribeTest module

lib/elixir/lib/kernel.ex, lib/elixir/lib/map.ex
- The new `Map` module doc added in #4820 called `===`
the match operator but `=` is the match operator.
- I looked at the docs for `===` to see what it is called
and it did not really give it a name. It did, however,
use the confusing expression "returns true if the two
times are match".  "Are match" is not a very clear explanation.
- The [Erlang docs](http://erlang.org/doc/reference_manual/expressions.html#id80318) describe the equivalent `=:=` operator as
"Exactly equal to", so I think "exact equality operator" is a
better name for this.
=> Clarify some confusion regarding the === operator.

lib/mix/lib/mix/tasks/deps.clean.ex, lib/mix/test/mix/tasks/deps_test.exs
I think it could be useful to warn when the user makes a typo like `mix deps.clean pheonix` instead of just printing `* Cleaning pheonix` even if the `File.rm_rf!` did nothing.
I’v decided to just check if the path is a directory instead of checking in the app’s dependencies because a user could want to clean an old dependency not present in the app.
The message could be something else, english is not my first language 😄
=> Add warning for an invalid path on deps.clean task

lib/elixir/src/elixir_with.erl, lib/elixir/test/elixir/kernel/with_test.exs
When upgrading my code to Elixir 1.3, I forgot to use clauses in my `else` when replacing `if/else` by `with/else`,
and got an error message difficult to parse, so I added a clause to get something more readable.
Before: 
```
== Compilation error on file web/models/app.ex ==
** (FunctionClauseError) no function clause matching in :elixir_with.expand_else/2
(elixir) src/elixir_with.erl:58: :elixir_with.expand_else({:changeset, [line: 34]$
nil}, %Macro.Env{aliases: [], context: nil, context_modules: [BuildyPush.App], expor$
_vars: nil, file: "/home/daniel/tmp/push-server/web/models/app.ex", function: {:valid$
te_settings, 1}, functions: [{Ecto.Changeset, [add_error: 3, add_error: 4, apply_chan$
es: 1, assoc_constraint: 2, assoc_constraint: 3, cast: 3, cast: 4, cast_assoc: 2, cas$
_assoc: 3, …
```
=> Improve with/else error message on invalid form

lib/elixir/src/elixir_def_overridable.erl, lib/elixir/src/elixir_translator.erl, lib/elixir/test/elixir/kernel/overridable_test.exs
This is a WIP PR that I'd really like to collect feedback on; it's a possible *partial* fix for #4830 as it fixes `super()` and `defoverridable` for public macros but not private macros.
Is this a good way to approach this? :)
=> Support (exported) macros with defoverridable/super

lib/elixir/lib/enum.ex
When upgrading one of my projects to Elixir v1.3, I found the `Enum.group_by/3` deprecation message to be a bit confusing. It says to `please use a map instead`, but a map is used by default with the new form of `Enum.group_by/3`. The user only needs to remove the map as an argument to the function.
I think this makes it a little more clear what do to. I'm open to any suggestions here.
=> Clarify Enum.group_by/3 deprecation message

lib/iex/lib/iex/introspection.ex, lib/iex/test/iex/helpers_test.exs
As reported in #4859, the `h` helper was not working with `==/2`, or `div/2`
It seems the regression is here since 1.3.0-rc.0.
=> Fix h helper for binary operators, closes #4859

lib/elixir/test/elixir/behaviour_test.exs, lib/elixir/test/elixir/kernel/dialyzer_test.exs, lib/elixir/test/elixir/kernel/raise_test.exs, lib/elixir/test/elixir/protocol_test.exs, lib/elixir/test/elixir/test_helper.exs, lib/iex/lib/iex/introspection.ex, lib/iex/test/iex/helpers_test.exs, lib/iex/test/test_helper.exs
Addresses #4851.
In addition to the original issues from #4851, a test for `IEx` related to the `h` helper and callback functions was failing. I am currently skipping that test, but we can update `h` to use a similar approach to `callbacks_for_beam` in `elixir/test_helper.exs` as a fallback as part of this PR. That way it will continue to work for in memory and disk modules in <19, but it will only work for disk modules in >19.
I've also posted to erlang-questions asking why callbacks are no longer in the attributes, since I cannot find any reference to such a change in the changelog for 19, the github, or the erlang issue tracker. It seems this may be an unexpected change?
/cc @josevalim
=> Skip/fix tests on OTP 19

lib/elixir/lib/module.ex
I guess this could be backported to 1.3.x cuz the docs will look off
=> Add missing backquote in Module docs

lib/elixir/lib/module.ex, lib/elixir/test/elixir/kernel/overridable_test.exs
Part of what discussed in #4830. I'm raising a `RuntimeError` as you can see in the code but I think that a `CompileError` would be more appropriate, however the neighbour code raises a `RuntimeError` for a very similar situation; should I make both `CompileError`s? 
(I will also add a test later for the neighbour error, which apparently has no tests)
=> Raise an error when trying to make private macros overridable

lib/elixir/lib/module.ex, lib/elixir/test/elixir/kernel/overridable_test.exs
I also added a test for this behaviour as there was none. Related to #4856.
=> Raise an ArgumentError when overriding an undefined function

lib/iex/lib/iex/autocomplete.ex, lib/iex/test/iex/autocomplete_test.exs
I find this behavior to be surprising and annoying. I regularly type `h [first few chars of mod name]<tab><enter>` in IEx to read the read the moduledoc of a particular module, and the trailing period gets in the way every time.
Here's a demonstration showing what happens to me regularly when I try to read the `@moduledoc` for a module:
With this change, it avoids this problem:
Now, I know the existing behavior must be intentional (after all, it's been there a long time and was specified by tests) so I'm fully expecting that this may not be merged.  If the elixir-core team feels the existing behavior is best, that's fine.  Figured I'd open the PR and see if @josevalim and the team are open to changing, it, though, since I've found it so consistently annoying.
=> Stop appending a trailing dot when autocompleting modules in IEx.

lib/elixir/lib/gen_server.ex
Prior to this change it is possible to send any two-pair tuple to
`GenServer.reply/2` and it will happily reply with `:ok`.  This
leads to some hard to track-down bugs if you pass it the wrong
data.  With this small check developers may be able to get a bit
more of a heads up to what is going wrong sooner.
For more information on how I came accross this:
https://github.com/benfalk/data_pool/commit/dcf81d1a87a363952715deeed3caa18ec0efccd9
=> Generate error for no pid given to Genserver.reply

lib/elixir/lib/module.ex, lib/elixir/test/elixir/kernel/overridable_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs
We already don't support private macros so not supporting private functions anymore seems reasonable. Less magic!
=> Deprecate support for making private functions overridable

lib/elixir/test/elixir/kernel/overridable_test.exs
It seems like the `import ExUnit.CaptureIO` is not needed in this test file.
This pull request just removes that line.
=> Remove unused import in kernel/overridable_test.exs

Makefile
This makes packaging elixir easier for distributions which have
a more specialized filesystem layout like exherbo.
=> Allow to set BINDIR for binaries and SHARE_PREFIX for manpages

lib/elixir/lib/calendar.ex
Adapting docs of `Date.new`, according to https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/calendar.ex#L343 and https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/calendar.ex#L615
=> Fix documentation for Date.new

lib/ex_unit/lib/ex_unit/assertions.ex, lib/ex_unit/lib/ex_unit/doc_test.ex, lib/ex_unit/test/ex_unit/assertions_test.exs, lib/ex_unit/test/ex_unit/doc_test_test.exs
__Before:__
```
Doctest failed: expected exception Mix.Error with message "mix deps.clean expects dependencies as arguments or a flag indicating which dependencies to clean. The --all option will clean all dependencies while the --unused option cleans unused dependencies" but got Mix.Error with message "`mix deps.clean` expects dependencies as arguments or a flag indicating which dependencies to clean. The '--all' option will clean all dependencies while the '--unused' option cleans unused dependencies"
```
__After:__
```
Doctest failed: wrong message for Mix.Error
expected:
"mix deps.clean expects dependencies as arguments or a flag indicating which dependencies to clean. The --all option will clean all dependencies while the --unused option cleans unused dependencies"
actual:
"`mix …
```
=> Improve doctest failure messages for exception assertions

lib/elixir/lib/kernel/typespec.ex, lib/elixir/test/elixir/kernel/typespec_test.exs
For example, `@for.t` in protocols or similar use cases. This PR closes #4874.
I'm open to feedback on the error message we should give if the module attribute doesn't expand to a module :)
For the record, this was broken in https://github.com/elixir-lang/elixir/commit/a3c429f9b9a476f995b23328430a1dcca55d1799, when we stopped expanding module attributes in `Macro.expand_once/2`.
=> Support module attributes in remote types

lib/mix/lib/mix/tasks/do.ex, lib/mix/test/mix/tasks/do_test.exs
I reverted the `mix do` behavior, this should fix #4861.
Sorry for messing up! :sweat:
=> Revert mix do to enforce space after comma

lib/ex_unit/lib/ex_unit/cli_formatter.ex
since `@moduledoc` is false, I hope we can change this.
Luckily [not many people using this](https://github.com/search?l=elixir&q=%22invalids_counter%22+OR+%22failures_counter%22+OR+%22tests_counter%22&ref=searchresults&type=Code&utf8=%E2%9C%93)
=> Fix adjectives in ExUnit

lib/ex_unit/examples/difference.exs, lib/ex_unit/lib/ex_unit/diff.ex, lib/ex_unit/test/ex_unit/diff_test.exs
With this path we unify script building for keywords and proper lists, which gives better highlighting as well (see on the animation we have __less noisy diff__). Next step is to make improper lists work with this algorithm, thus we unify list handling and remove a lot of code.
=> Enhance difference highlighting for proper lists

lib/elixir/src/elixir_def_overridable.erl
Support for private overridable macros was officially dropped in 3c88c16 we forgot to remove it from some code in `elixir_def_overridable.erl` (which is now harmless but superfluous code).
=> Remove defmacrop support in leftover code in elixir_def_overridable

lib/mix/lib/mix/tasks/profile.fprof.ex, lib/mix/lib/mix/tasks/run.ex, lib/mix/test/mix/tasks/profile.fprof_test.exs, lib/mix/test/mix/tasks/run_test.exs
This is a first step towards implementing https://github.com/elixir-lang/elixir/issues/4920. It splits the `-pr` option in `mix run` and `elixir`/`elixir.bat` into `-p` and `-r`, still having backwards compatibility. I'd love some early feedback. Couple of things to note:
* the code in `Mix.Tasks.Run` that checks if `-pr` is present in the argv and replaces it with `-p -r` is not nice but very temporary as we can drop it as soon as we'll be able to parse `-pr` as `-p -r` in `OptionParser`
* support for explicit `-pr` in `elixir` and `elixir.bat` is necessary I think, given they don't go through `OptionParser`
Wdyt?
=> Deprecate -pr CLI option in favour of --parallel

CHANGELOG.md, lib/elixir/lib/integer.ex, lib/elixir/test/elixir/integer_test.exs
This PR fixes
- fixes a bug in `Integer.undigits/2`
- corrects docs for `Integer.digits/2`, `Integer.undigits/2`
- optimizers `Integer.digits/2`, `Integer.undigits/2`
- improves `Integer.digits/2` by allowing negative digits
This is a backward non-compatible proposal, but I think it is worth mentioning it.
I think it is a bit weird the behaviour of allowing negative digits other than the first one in `Integer.undigits/2`
such as in this example: `Integer.undigits([1, -4, -5])`
what's the use of that?
It's weird that negative integers were allowed in Integer.undigits/2, and  a negative integer was not allowed in `Integer.digits/2`.
If we agree only on allowing the first element in the list to be a negative integer, then we could optimize this function when dealing with HUGE lists and when …
=> Integer.(un)digits/2 improvements

lib/elixir/lib/kernel.ex
=> [ci skip] Fix typespecs for Kernel.pop_in/2

lib/elixir/lib/enum.ex, lib/elixir/lib/stream.ex, lib/elixir/lib/stream/reducers.ex, lib/elixir/test/elixir/stream_test.exs
Closes #4933. Also fixes up a missing newline in the `Enum.uniq_by/2` docs.
/cc @josevalim
=> Add Stream.uniq_by/2 and deprecate Stream.uniq/2

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
Private function Enum.random_index/2 has been replaced with Enum.random_integer/2
and the deterministic examples had to be updated.
=> Optimize Enum.random/1, Enum.take_random/2 for ranges

lib/elixir/lib/list.ex
Fix return type for [List.keymember?/3](http://elixir-lang.org/docs/master/elixir/List.html#keymember?/3). 
Function ends with `?` should return a `boolean` type as described in the [Naming Conventions](http://elixir-lang.org/docs/stable/elixir/naming-conventions.html) page.
> Trailing question mark (foo?)
> 
> Functions that return a boolean are named with a trailing question mark.
> 
> Examples: Keyword.keyword?/1, Mix.debug?/0, String.contains?/2
=> [ci skip] Fix typespecs for List.keymember?/3

lib/elixir/lib/kernel/special_forms.ex, lib/elixir/lib/map.ex
Most of these docs were just a repetition of the docs that are now in the `Map` module, so we can just point to the `Map` module.
=> Polish the docs for the %{} special form

bin/elixir.bat, bin/elixirc.bat, bin/iex.bat, bin/mix.bat
- use lowercase for batch keywords (e.g., `set`, `if`, `not`, `setlocal`, `endlocal`, etc.)
- use two-space indents
- remove extra spaces except where used for alignment
- remove trailing whitespace
- add newline at end of file
- don't use colon after `goto` before label name (e.g., `goto end`, not `goto :end`)
=> Make batch style more consistent

lib/mix/lib/mix/utils.ex
This fixes the corner-case where mix needs to access files that are unreachable from the proxy server.
An example is if you have a git repo on the local network, but still need to use the proxy server to fetch the rest of your dependencies.
=> Add support for NO_PROXY to Mix.Utils.read_path

lib/elixir/src/elixir_import.erl, lib/elixir/test/elixir/kernel/errors_test.exs
Before, when importing private function, the compiler was informing that is doesn't exist.
=> Improve error message when importing non-existent or private function

lib/elixir/test/elixir/io/ansi_test.exs
The tests for out of range inputs for color_background/3 were actually calling color_background/1.  This PR fixes it.
=> Fix color_background/3 exception tests

lib/elixir/lib/stream.ex
The typespecs for [Stream.into/3](http://elixir-lang.org/docs/master/elixir/Stream.html#into/3) is not showing up due to missing typespecs for the last argument.
=> [ci skip] Fix typespecs not showing up for Stream.into/3

lib/elixir/lib/enum.ex
Private function Enum.do_reverse/2 abstracts the code now, and we call it directly from Enum.reduce/1
Avoiding calling Enum.reduce/2 and having unnecessary is_list/1 guard checks.
=> Optimize Enum.reverse/1

lib/elixir/lib/kernel.ex, lib/elixir/src/elixir_utils.erl
Implements what (I think? 😄) was discussed in https://github.com/elixir-lang/elixir/pull/4941. Let me know what you think!
=> Force defmodule to not be tail-call optimized

lib/elixir/lib/keyword.ex
As typespces for
Keyword.split/2
Keyword.take/2
Keyword.drop/2
Keyword.to_list/1
are missing in the latest [doc](http://elixir-lang.org/docs/master/elixir/Keyword.html#split/2) of module `Keyword`.
=> Add typespecs for Keyword.{split/2, take/2, drop/2, to_list/1}

lib/elixir/lib/keyword.ex
Same fix on `Keyword.pop_first/3` as @josevalim did in this [commit](https://github.com/elixir-lang/elixir/commit/0c2f3a4e5c2398954601f96d2d72f89a854e7038#diff-726c8befd520c8fdcebc6de0c11aac4bL658) for `Keyword.pop/3`.
=> Add parenthesis on Keyword doc example to match rest of the code

.travis.yml
With some of the incompatibilities expected from a major version
thought this might be a good idea, and the builds are fast enough
so I think travis won't mind :)
(not sure if this is wanted, I just noted that they were only running against 18, so I thought adding the new major might be a good idea :) )
Tobi
=> Run travis tests against Erlang 19

lib/elixir/lib/io.ex
Now documentation looks like this:
After fix will look like this:
=> Fix tiny bug in documentation

.travis.yml
After my add Erlang 19 PR (#4972) there was discussion about
adding more erlang versions to the test matrix. I'm in favor,
but didn't want too many on my first go. As other people
seem to agree and [as suggested](https://github.com/elixir-lang/elixir/pull/4972#issuecomment-231571052) by @eksperimental this now
tests all supported minor versions (latest patch level)
> I propose to add support for
> 18.0, 18.1, 18.2.1, 18.3, 19.0
=> Run Travis against every supported minor Erlang version

lib/elixir/lib/regex.ex
=> Using ~r{} instread of ~r// to fix syntax highlight on Regex.split/3's doc example

lib/mix/lib/mix/tasks/escript.ex
Correct verb tense, and remove trailing period.
=> Standardize `mix escript` task's shortdoc

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
This function has been highly-optimized, through thorough benchmarking.
There were serious issues when dealing with big lists and maps when an out of
bound or a negative index was given. Eg. fetching an out-of-bound index in a
1,000-element map, was reduced to 0.18% of the original item. Or same case
with a 1,000-element list time was reduced to a 10,5%.
Enumerables are no longer reversed when dealing with negative indexes.
The much cheaper `Enum.count/1` function is used now.
Benchmark .exs file are published here:
https://gist.github.com/eksperimental/dd5d4fec5988ba51f2191e5a754ed710
They have been done with lists and maps of the following configurations: 0, 1,
100, 1K, 100K, 1M elements, and indexes being 0 or positive and negative,
retrieving first, middle, last elements and and …
=> Optimize Enum.fetch/2 for negative and out of bound indexes

lib/elixir/pages/Typespecs.md
That's the way we do it across the project.
=> Typespec.md: spell it "two-element tuple"

lib/elixir/lib/map.ex, lib/elixir/test/elixir/map_test.exs
Current error message is quite unhelpful for new comers
Map.get_and_update(%{a: 1}, :a, fn value -> value end)
** (MatchError) no match of right hand side value: 1
(elixir) lib/map.ex:513: Map.get_and_update/3
This change introduces an improved message:
** (RuntimeError) must return a two-element tuple or :pop, got: 1
(elixir) lib/map.ex:699: Map.get_and_update/3
=> Improve error message on bad return in Map.get_and_update/3

lib/elixir/lib/io/ansi.ex
[_IO.ANSI.inverse_](http://elixir-lang.org/docs/stable/elixir/IO.ANSI.html#inverse/0) (and its synonym, [_IO.ANSI.reverse_](http://elixir-lang.org/docs/stable/elixir/IO.ANSI.html#reverse/0)) for ANSI escape sequence `7` were already implemented, but not the escape sequence that disables their effect (`27`).
=> Add ANSI escape sequence 27 for turning off reverse video

lib/elixir/lib/enum.ex, lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/enum_test.exs, lib/iex/lib/iex/helpers.ex, lib/mix/lib/mix/dep/loader.ex
This PR closes #4996. `Enum.partition/2` has been soft-deprecated and will be deprecated by v1.5.
Before merging this I think it would be worth asking, is `split_with/2` the best name? I can't think of any clearly better alternatives, just want to raise the question before getting this in. Maybe `split_in_two/2` to be superclear? Not sure. 😕
=> Rename Enum.partition/2 to Enum.split_with/2

lib/elixir/lib/gen_event.ex, lib/elixir/test/elixir/gen_event_test.exs
I'm new to Elixir, but I wanted to see if I can help with any issues, so here is my PR for this.
I can change supervisor.ex and gen_server.ex as well if you think the implementation is ok.
Thanks!
Mentioned in #3932
=> Give helpful error message if a string is used to name a GenServer

lib/elixir/lib/uri.ex
I'm patching up Hackney/HTTPoison to support HTTP over Unix Domain Sockets, using the (informal) 'http+unix' URI scheme.
In order to comply with Erlang 19's spec for opening an `inet:local_address()` socket using `gen_tcp` (http://erlang.org/doc/man/inet.html#type-local_address) I want to make sure the port number is set to 0 by default by calling `URI.default_port("http+unix", 0)`. Unfortunately the `URI.default` functions did not foresee this use-case :)
=> Allow 0 as URI scheme default port

lib/elixir/pages/Behaviours.md
It's simply not true that any default implementation will be provided.
Behaviour modules should explicitly check if the function is defined,
and handle that case.
=> Clarify optional callbacks documentation

lib/mix/lib/mix/generator.ex
The generated functions are private, so the examples will throw the error about an undefined function.
=> Fix examples in mix.generator doc

lib/elixir/lib/enum.ex
It all started when an old version of the Enum.sort/2 docs confused me in the way they described the semantics of the sort function in Enum.sort/2.  The new docs are much better, and I think they're clear enough, but fishcakez pointed out that the example uses a non-stable sort function.  We can make it stable with no loss in clarity, so we should do so.
=> Make Enum.sort/2 example use a stable sort function, to avoid confusion

lib/elixir/lib/macro/env.ex
Migrating Erlang/OTP from 18.3 to 19.0, dialyzer (now much smarter than before!) starts to complain about the following perfectly legitimate expression:
```ex
Macro.Env.location(__ENV__)
```
The actual warning I got:
```
lib/foo.ex:3: The call 'Elixir.Macro.Env':location(#{'__struct__':='Elixir.Macro.Env', 'aliases':=[], 'context':='nil', 'context_modules':=['Elixir.Foo',...], 'export_vars':='nil', 'file':=<<_:264>>, 'function':={'f',0}, 'functions':=[{'Elixir.Kernel',[{atom(),0 | 1 | 2 | 3},...]},...], 'lexical_tracker':=_, 'line':=3, 'macro_aliases':=[], 'macros':=[{'Elixir.Kernel',[{atom(),0 | 1 | 2 | 3},...]},...], 'module':='Elixir.Foo', 'requires':=['Elixir.Kernel' | 'Elixir.Kernel.Typespec',...], 'vars':=[]}) breaks the contract (t()) -> 'Elixir.Keyword':t()
```
This is a bit …
=> Remove nonexisting struct field `local` from type of `Macro.Env.t`

lib/elixir/lib/regex.ex, lib/elixir/lib/string.ex
We were being a bit inconsistent with the use of backslashes to escape the backslash in `\N` and `\g{N}`. This commit should fix that. Should close #4975.
=> Fix docs for \N and \g{N} in String.replace/4 and Regex.replace/4

lib/elixir/lib/integer.ex
Looks like parse_digit has a parameter that isn't being used.
=> Remove redundant parameter

lib/elixir/lib/enum.ex
This PR does two optimizations,
First commit adds a clause to check for lists, when dealing with negative indexes
Second commit, revert's a change by @lexmag,
I think lists should be prioritized in Enum over ranges. In addition to this, I'm doing it based on the idea that checking for a range in a guard is more expensive than checking for a list, so it's better to leave it for as late as possible (just before the fallback guard that would deal with any other enumerable).
Benchmarks accompany this PR, between each commit.
https://gist.github.com/eksperimental/3f9c58a5b27fa9ff05abcd1df4678b1a
for the final results before this PR and after.
https://gist.github.com/eksperimental/3f9c58a5b27fa9ff05abcd1df4678b1a#file-enum_fetch_benchmarking_report_new-txt-L1172-L1360
the gain is considerable …
=> Enum fetch more optimizations

lib/elixir/lib/io.ex, lib/elixir/test/elixir/io_test.exs
This option will decorate the output with additional string, so
it's easy to distinguish between different IO.inspect calls.
```elixir
IO.inspect("foo", tag: "bar")
#=> bar: "foo"
```
Closes #5009
=> Add :label option to IO.inspect/2

lib/elixir/lib/record.ex, lib/elixir/test/elixir/record_test.exs
Literal values in records should not be escaped.
This lead to structs (and other non-literals in AST) being returned
as AST, which was unexpected and incorrect.
Before:
```elixir
defmodule Struct do
defstruct foo: nil
end
defmodule Test do
import Record
defrecord :bar, data: %Struct{}
end
iex> require Test
iex> Test.bar(Test.bar())
[data: {:%{}, [], [__struct__: Struct, foo: nil]}]
```
After:
```elixir
iex> require Test
iex> Test.bar(Test.bar())
[data: %Struct{foo: nil}]
```
=> Don't escape record literals on keyword conversion

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
slice/2,3 have been rewritten changing the approach.
Previous approach was based on count (now named "n") number of elements to be fetched,
and slice/2 would call slice/3.
This leads to the problem of having to recalculate the amount of elements in the enumerable
when dealing with negative indexes.
The new aproach uses slice/2 as the main funtion, and deal with start and finish indexes.
When a negative index is needed, we determine the number of elements, and we convert it to indexes.
Benchmarks for the new implemetation can be seen here:
Runing time: https://gist.github.com/eksperimental/e7cda7722d42e43c4c2f69825149c7df#file-enum_slice_benchmarking_report_new-txt-L773
Comparison: https://gist.github.com/eksperimental/e7cda7722d42e43c4c2f69825149c7df#file-enum_slice_benchmarking_report_new …
=> Enum.slice/2 and Enum.slice/3 rewrite

lib/elixir/lib/gen_server.ex, lib/elixir/lib/supervisor.ex, lib/elixir/test/elixir/gen_server_test.exs, lib/elixir/test/elixir/supervisor_test.exs
Hi, this is my second PR related to #3932.
It should add helpful messages for GenServer and Supervisor.
Thanks!
=> Give helpful error message if a string is used to name a GenServer / Supervisor

lib/elixir/lib/enum.ex
Renamed `mapper_fun` to `value_fun` in function head, to match doctest and other function definitions.
Renamed `fun` to `key_fun` in docs, to match function definitions.
See http://elixir-lang.org/docs/stable/elixir/Enum.html#group_by/3
=> Naming inconsistencies in Enum.group_by/3

lib/elixir/lib/string.ex, lib/elixir/test/elixir/string_test.exs
Closes #5019.
These function would end up in infinite recursion if the "match" argument to replace was an empty string. With this commit, we explicitly check for that empty string and possibly raise an `ArgumentError` exception.
=> Fix a bug in String.replace_leading/3 and String.replace_trailing/3

lib/elixir/lib/option_parser.ex, lib/elixir/test/elixir/option_parser_test.exs
This is work towards closing #4920.
Before this PR, `-abc` is processed by `OptionParser` as an alias. With this PR, we deprecate this behaviour: if `-abc` still matches an alias, we warn, otherwise, we split it into `-a -b -c`.
This is a WIP because I don't like this implementation but I can't seem to come up with something better and am a bit stuck :)
The current implementation just rewrites the `argv` by expanding the alias (which I believed was a good and clean way to do things so that we don't have to go too deep), but it duplicates some work such as splitting the option (`split_option/1`) or converting to underscored/atom.
What are your feelings? Sorry I opened this in not quite a good state, but at least we can get the discussion started 😕
=> [WIP] Expand multi-letter aliases in OptionParser

lib/mix/lib/mix/tasks/profile.fprof.ex, lib/mix/lib/mix/tasks/run.ex
Follow up to #5025. We don't need this anymore now (80aec928) that we support splitting of `-abc` into `-a -b -c`.
=> Don't process -pr in a special way in mix run and mix profile.fprof

lib/elixir/lib/enum.ex, lib/elixir/lib/float.ex, lib/elixir/lib/stream.ex, lib/elixir/test/elixir/kernel/typespec_test.exs, lib/elixir/test/elixir/stream_test.exs, lib/mix/lib/mix/tasks/new.ex, lib/mix/lib/mix/utils.ex
Follow up to #5037. I'm keeping the big ones - `HashDict`, `HashSet`, `Dict` - for later :)
Btw, question: would it make sense to **not** use `@doc false` on these deprecated functions, so that they show up in the docs, and mention they're deprecated in the docs themselves? I know they will show up in autocomplete as well and that's bad, but I'm afraid when people look at old code that uses these function and try to find them they will have a hard time 😕 This is what we do with the `Behaviour` module btw, that's why I was wondering :)
=> Deprecate some functions here and there for v1.4

lib/elixir/lib/supervisor.ex
Based on my confusion in #5020, I've updated the sentence above the list containing the child spec in the supervisor example. Hopefully this makes things a little easier to understand.
=> Clarify comment in the supervisor example included in the Supervisor moduledoc

lib/mix/lib/mix/tasks/xref.ex
=> mix xref: loadpaths before compile

lib/elixir/lib/gen_server.ex
Bug introduced in d9cdeeb2f135abcac87a30b35169efe5d3d7e94c
Variable `module` in the case clause shadows argument of the function.
Servers using `:via` simply do crash on start(_link).
In the mentioned commit similar change in supervisor.ex was correct.
=> Fix broken GenServer using :via registry.

lib/elixir/lib/module.ex, lib/elixir/test/elixir/kernel/errors_test.exs
Aimed towards #5049.
`@doc` was being checked by `Module.add_doc/6` but `@moduledoc` and `@typedoc` weren't.
I think it makes sense to perform all these checks as soon as possible (i.e., when setting the proper attribute with `@`) and raise a helpful error message when we can.
Wdyt?
=> Perform some checks on the value of @moduledoc, @typedoc, and @doc

lib/elixir/lib/enum.ex, lib/elixir/lib/stream.ex
- __Correct typespec return value in Enum.take_every/2, Enum.drop_every/2__
All functions where one arg. is not any() will raise FunctionClauseError, and we don't specify it as :: `no_return`
- __Add bodyless function to Stream.take_every/2, Stream.drop_every/2__
=> {Enum, Stream}.{take_every, drop_every}/2 little improvements

lib/elixir/lib/option_parser.ex
warning: the variable "alias" is unsafe as it has been set inside a case/cond/receive/if/&&/||.
Please explicitly return the variable value instead.
...
Unsafe variable found at:
lib/option_parser.ex:350
=> Eliminate "if" warning

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
+ examples added to docs
An increase in speed between 16-40% when treating lists
You can see the benchmarks here: https://gist.github.com/eksperimental/e13e69620e5c5b5bf0da6d978ff4f9de
=> Optimize  Enum.split_with/2 for lists

lib/ex_unit/lib/ex_unit/formatter.ex
The `:test_started` and `:test_finished` events in the `moduledoc` refer to a `test_case` in the prose. In reality, those events receive an `ExUnit.Test` struct.
=> Update :test_started and :test_finished event docs

lib/mix/lib/mix/tasks/deps.unlock.ex, lib/mix/test/mix/tasks/deps_test.exs
I just accidentially realized that it's possible to pass `--unused` to `mix deps.unlock`. This PR aligns the error message with `mix deps.clean`.
=> Expand message for mix deps.unlock

lib/elixir/lib/stream.ex
```
iex> [1,2,3] |> Stream.chunk(0)
** (FunctionClauseError) no function clause matching in Stream.chunk/4
(elixir) lib/stream.ex:160: Stream.chunk([1, 2, 3], 0, 0, nil)
```
Typespecs for parameter `n` in `Stream.chunk/2` should match `n` in `Stream.chunk/4`, which is  `pos_integer`.
=> Fix typespecs for Stream.chunk/2

lib/elixir/src/elixir_map.erl, lib/elixir/test/elixir/fixtures/dialyzer/struct_update.ex, lib/elixir/test/elixir/kernel/dialyzer_test.exs
With changes to OTP 19, dialyzer started emitting warnings for
the struct update syntax where variable could only be that struct.
For example:
def foo(%Foo{} = struct), do: %Foo{struct | bar: :baz}
I'm not 100% sure this is the correct fix. I'm not sure how to test this properly. Do we have some way of testing for dialyzer warnings?
=> Mark struct update syntax as generated

lib/elixir/lib/integer.ex, lib/elixir/test/elixir/integer_test.exs
Right now `Integer.undigits/2` may yield results that are hard to reason about:
```
iex(1)> Integer.undigits([10,10]) 
110
iex(2)> Integer.undigits([1,10]) 
20
```
=> Raise on incorrect digits

lib/mix/lib/mix/compilers/elixir.ex
Per TODO and https://github.com/elixir-lang/elixir/commit/f8e88ebe6014511a4276699c4705f6d0bb8dcc9b#commitcomment-18420581.
`:file.consult` also used in these files, but there are no TODOs there
```
lib/mix/lib/mix/dep/loader.ex
lib/mix/lib/mix/rebar.ex
lib/mix/lib/mix/tasks/compile.app.ex
lib/mix/test/mix/tasks/compile.app_test.exs
```
=> Cleanup lib/mix/lib/mix/compilers/elixir.ex

lib/iex/lib/iex/server.ex
Doing an interrupt (Ctrl-G then "i") while IEx is busy evaluating something currently makes it crash. This PR makes IEx.Server trap the `interrupt` signal and kill the evaluation (same behavior as the Erlang shell). Fixes: https://github.com/elixir-lang/elixir/issues/4991
I tested:
* Interrupt while waiting for input
```elixir
iex(local@Ando)1>
User switch command
--> i
--> c
** (EXIT) interrupted
iex(local@Ando)1>
```
* Interrupt while evaluating
```elixir
iex(local@Ando)1> Process.sleep(10000000)
User switch command
--> i
--> c
** (EXIT) interrupted
iex(local@Ando)1>
```
* Interrupt in etop (original issue)
```elixir
iex(local@Ando)2> :etop.start
========================================================================================
local@Ando …
```
=> Support interrupting IEx evaluation

lib/elixir/lib/supervisor.ex
I thought this extra iex example might be useful in understanding the difference between :one_for_one, where the child is created when the supervisor is created, vs. :simple_one_for_one where the child acts as a template and creating the supervisor in that case does not create any active child processes until start_child is called.
=> Add example difference between :one_for_one and :simple_one_for_one

lib/elixir/lib/enum.ex
positives are slightly easier to understand than negavites.
I find it more in intuitively to describe the second argument this way, because it's easier to understand that it
> determines whether the first precedes
than it is to understand that it
> determines whether the first doesn't follow the second
`true` meaning *yes* and `false` meaning *no* in both cases.
=> use positive in @doc of Enum.sort/2

lib/elixir/lib/kernel/parallel_compiler.ex, lib/elixir/test/elixir/fixtures/parallel_struct/undef.ex, lib/elixir/test/elixir/kernel/parallel_compiler_test.exs
Closes #5053.
If the module we are waiting `on` is in the list of modules we are currently `defining`, simply send `:found` so that the compiler process can produce whatever error it would outside of the parallel compiler.
This fixes the issue described in #5053 and should also improve any other potential future similar issues.
=> Do not wait for self in parallel compiler

lib/elixir/lib/io.ex
As discussed on IRC, I'm opening this PR as a place for further discussion on the issue.
This commit basically reverts the change introduced in: https://github.com/elixir-lang/elixir/commit/249f83e82b4953e6e7807dc1c14726c017cdd987
Using :stdio gives us much better error in case the data is not
printable, and the function signature is more understandable when
accessed with h/1.
As an example of better error message let's look at the error before the change:
```elixir
iex(1)> IO.puts([:io])
(stdlib) :io.put_chars(#PID<0.50.0>, :unicode, [[:io], 10])
```
And after:
```elixir
iex(1)> IO.puts([:io])
(stdlib) :io.put_chars(:standard_io, :unicode, [[:io], 10])
```
Notice the device is a PID when using `group_leader()` and a more …
=> Use :stdio instead of group_leader() as default device

lib/mix/lib/mix/tasks/app.start.ex, lib/mix/lib/mix/tasks/compile.ex, lib/mix/lib/mix/tasks/compile.protocols.ex
Didn't know about this (and apparently several other people who
asked me if I had it enabled as well) so I thought it'd be good
to mention, I like defaults being mentioned in the docs
in general :)
As [by this default configuration](https://github.com/elixir-lang/elixir/blob/843783a890f00fcbd014170cada06a7c1d3aafd4/lib/mix/lib/mix/project.ex#L490-L507). I also think it'd be nice to mention the project default configuration in Mix.Project docs, but that's prone to error. I thought about making `default_config` public, and adding a doc test for it. Sure, annoying to update but that way the docs would stay up to date and people would have an easy reference for the default configuration without digging through the code. I'd be happy to add that in as well if desired :)
Also for …
=> Document that consolidate_protocols is enabled by default

lib/elixir/lib/enum.ex
While yielding the right result, the current example for `drop_while` is misleading and can cause confusion between `drop_while` and `reject`.
=> Change example for drop_while

lib/elixir/lib/kernel/typespec.ex, lib/mix/test/mix/tasks/compile.elixir_test.exs
Fixes #5087.
Also adds some comments to the cases in which a compile time dependency must be added for a typespec (structs, records). Perhaps the documentation should be altered to suggest using a remote type instead of a struct or record macro to avoid this case, if possible.
Also, I am pushing a commit with the added test first, to show that it fails on the current master. I will then immediately push the commit with the actual fix.
=> Do not consider remote typespecs as a compile-time dependency

lib/elixir/lib/exception.ex, lib/mix/lib/mix/tasks/xref.ex, lib/mix/test/mix/tasks/xref_test.exs
Implements part of #5096.
Had to slightly modify the code for `UndefinedFunctionException` to allow non-autoloaded modules to work properly. Looking into module name suggestions now.
=> mix xref provides "did you mean?" for missing functions

lib/ex_unit/lib/ex_unit/doc_test.ex, lib/ex_unit/test/ex_unit/doc_test_test.exs
- DocTest Regex changed to:
- Allow Unicode
- Allow multiline statements.
- Doctest will still match if Inspect output ends with a `\n`.
- Instead of enforcing `#Name<...>` now enforces `#Name<...` (Trailing `>` no longer required) for opaque inspect types.
Fixes #5103. Fixes #5100.
Also contains some very poetic specs. :innocent:
=> Expand DocTest's RegExp to allow Unicode and Multi-line inside opaque inspect types

lib/iex/lib/iex/helpers.ex
All other helper functions/macros like `h` or `b` have examples. So I feelt like there should be examples in the same style for `i` too.
(And I also fixed a typo).
=> Add examples in the docs for the i/1 IEx helper

lib/ex_unit/lib/ex_unit/assertions.ex, lib/ex_unit/test/ex_unit/assertions_test.exs
=> Omit redundant information if both sides in assertion are exactly equal

lib/elixir/lib/string.ex, lib/elixir/test/elixir/string_test.exs
=> Do not re-compile a compiled pattern for String.split/3

lib/elixir/test/elixir/fixtures/dialyzer/remote_call.ex, lib/elixir/test/elixir/kernel/dialyzer_test.exs, lib/elixir/test/elixir/test_helper.exs
I prefer this approach because:
* Supports custom OTP builds where a non-standard version of dialyzer/erts is used
* Easier to handle once bug is fixed
* Only ignores warnings for the bug and doesn't hide other issues that can crop up, e.g. helpful for #5116 (skipping the test hides bugs introduced in that PR at the moment)
* Shows how to hide the warnings if someone wants to
=> Use dialyzer attributes instead of ExUnit exclude tag

lib/elixir/lib/calendar.ex, lib/elixir/test/elixir/calendar_test.exs
Fixes #5124:
- Unix times back to -62167219200000000 microseconds (0 Gregorian seconds) are now supported by `DateTime.from_unix/2`.
- For lower integers, `:error` will be returned instead of `{:ok, datetime}`. The bang-version of the method will raise an ArgumentError in these cases.
- Usage of negative Unix times has been documented.
- A couple of tests were added to ensure that this is indeed the behaviour that is happening.
- `DateTime.to_unix` has similarly been altered to support all DateTimes with `year >= 0`, which matches the new cutoff-point for `DateTime.from_unix`.
- When passing a DateTime with a negative year to `DateTime.from_unix`, a descriptive ArgumentError is raised.
=> Enhancement: negative integer support in `DateTime.from_unix`

lib/elixir/lib/integer.ex, lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/integer_test.exs
Implements `Integer.mod/2` and `Integer.floor_div/2` as simple functions.
Also includes:
- documentation (+doctests)
- typespecs
- tests
- updated documentation and doctests for `Kernel.rem/2` and `Kernel.div/2`
Does not include:
- Crazy guard-safe macros. (See #5112 )
=> Implements `Integer.mod/2` and `Integer.floor_div/2`.

lib/elixir/lib/gen_server.ex
=> Spelling correction in GenServer reply docs

lib/elixir/src/elixir.hrl, lib/elixir/src/elixir_for.erl, lib/elixir/src/elixir_map.erl, lib/elixir/src/elixir_rewrite.erl, lib/elixir/src/elixir_translator.erl, lib/elixir/src/elixir_with.erl, lib/elixir/test/elixir/fixtures/dialyzer/remote_call.ex, lib/elixir/test/elixir/kernel/errors_test.exs
This still needs a proper test, but I'm opening it early, because I expect a lot of discussion around this anyway.
This fixes one major issue - missing file/line info in stacktraces following a dynamic remote dispatch on nullary functions. For example a code like `x.foo` (when x is not an atom or a map) will produce a stacktrace with top function missing the file/line info, since the code in dispatch is all marked with `[{generated, true}, {location, 0}]`. A runnable example can be found here: https://gist.github.com/michalmuskala/44e2af7d90df09e27cc9abba0c75154b
This changes how we add the generated annotation on erlang 19 by keeping the proper line information. This adds the missing stacktrace information.
Unfortunately this means we'll be generating different code on different erlang …
=> Add proper location to generated code on 19

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs, lib/elixir/test/elixir/exception_test.exs
As discussed on the [mailing list](https://groups.google.com/forum/#!topic/elixir-lang-core/goQuIjs00YE).
The new 2nd argument is a function that is called when the enumerable is empty. It defaults to raising `Enum.EmptyError` to preserve existing behavior.
One thing I'm unsure of: should we add `min_by/3`, `max_by/3` and `min_max_by/3` as well?
=> Add `min/2`, `max/2` and `min_max/2` to `Enum`.

lib/elixir/pages/Operators.md
This is a first shot (really unpolished) at https://github.com/elixir-lang/elixir/issues/5129. I like the format and I like the "Final note" section, I'm not sure the rest of the team agrees on putting "advices/recommendations" in a documentation page though.
Also, I'm not sure what @fishcakez meant with "guards" in #5129, so I skipped them for now 😄 
Btw, \cc @ericmj as well who suggested me to add the list of possible operators to define in the docs a long time ago, sorry for the delay Eric! 😃
=> Add a page in the docs about operators

lib/mix/lib/mix/scm/git.ex, lib/mix/test/fixtures/.gitignore, lib/mix/test/mix/scm/git_test.exs, lib/mix/test/mix/tasks/deps.git_test.exs, lib/mix/test/test_helper.exs
This is a start to adding sparse checkout to the GIT SCM.
Sparse checkout can be used for picking a dep from a repo which may contain many deps in sub folders
For example.
The git repository
https://github.com/nerves-project/toolchains
contains many toolchains including 
`nerves_toolchain_armv5tejl_unknown_linux_musleabi`
To use git and single out that subfolder int he repo as the dependency destination we could use sparse
`{:nerves_toolchain_armv5tejl_unknown_linux_musleabi, github: "nerves-project/toolchains", sparse: "nerves_toolchain_armv5tejl_unknown_linux_musleabi"}`
=> add git sparse checkout

lib/elixir/lib/gen_server.ex
Adding hint how to use `Process.send_after` with GenServer.
It could save hours of time for newcomers like me.
=> Add example of sending/handling custom messages to GenServer documentation

lib/elixir/lib/file.ex
Fix a typo in the name of a parameter in the ExDoc comment for `File.stream!/3`
=> Fix a typo in the ExDoc for File.stream!/3

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel_test.exs
Right now, `Kernel.macro_exported?/3` blindly calls `__info__/1` on the given module, but since `__info__/1` is defined by Elixir when compiling modules, this breaks if an Erlang module is passed to `macro_exported?/3`. This commit fixes this behaviour by always returning `false` in `macro_exported?/3` when an Erlang module is given.
This is mildly related to #5156, which is gonna be a bit simpler once we merge this.
\cc @josevalim
=> Don't crash in macro_exported?/3 when dealing with Erlang modules

lib/elixir/lib/list.ex
Fixes typo 'convertion', replacing with 'conversion'.
=> Fix typo in `List`

lib/elixir/lib/macro.ex
The optional function was not documented at all. If we plan on having `Macro.to_string/2` public (which I assume we do since, well, it's public :bowtie:) I think we should document it properly :)
=> Mention the optional function in the docs for Macro.to_string/2

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
Right now, application of anonymous function literals in `Macro.to_string/2` is represented like this:
```elixir
Macro.to_string(quote do: (fn x -> x end).(1))
#=> "fn x -> x end.(1)"
```
While this is valid, I think it's far more common (and personally, much less confusing) to have such calls with the literal `fn` wrapped in parens:
```elixir
(fn x -> x end).(1)
```
This PR makes `Macro.to_string/2` behave like this. Sorry I jumped the mailing list for discussing this, but the feature was quite small to implement and I wanted to try it out first anyways, so I thought a PR would be ok :)
=> Wrap fn calls in parens in Macro.to_string/1,2

lib/elixir/lib/list.ex
As `List.delete([1, 2, 2, 3], 2)` and `List.delete_at([1, 2, 2, 3], 2)` has same result.
I think `List.delete([4, 5, 5, 6], 5)` is a better example to avoid misunderstanding.
=> To avoid confusion with `List.delete_at/2`

lib/mix/lib/mix/tasks/new.ex
This PR adds `.fetch` to the Git ignore directory in case people find themselves editing deps inside the dependency directory. If you edit something in the `deps/` directory, then commit it, future updates will cause the following error:
```
error: The following untracked working tree files would be overwritten by checkout:
.fetch
Please move or remove them before you can switch branches.
```
This is a easy fix to help people avoid shooting themselves in the foot (like I did).
=> Ignore .fetch in project root

lib/elixir/lib/enum.ex, lib/elixir/lib/process.ex, lib/elixir/lib/stream.ex
As discovered in https://github.com/elixir-lang/elixir/pull/5182 some `when`s where misaligned.
I'm not sure if that's the right way to indent all of them, so suggestions are welcome.
\cc @lexmag
=> Align multiline when in specs to the standard

lib/elixir/src/elixir_with.erl
Isolated example:
```elixir
def foo(arg) do
with foo = arg do
foo
else
_ -> :not_ok
end
end
end
```
which translates to:
```elixir
def foo(arg) do
case (foo = arg; {:ok, foo}) do
{:ok, result} -> result
{:error, _} -> :not_ok
end
end
end
```
I have found which part should be marked as `generated` to suppress the "this clause cannot match because of different types/sizes" warning.
However, I think we can make it even better: with this patch that code produces meaningful warning and also we simply dropping else clauses.
Thoughts?
Closes #5164.
=> Produce meaningful warning when with's else clauses have no effect

lib/elixir/lib/kernel/special_forms.ex, lib/ex_unit/lib/ex_unit/assertions.ex
Noticed it was missing in the `refute_receive` docs and also looked and added it to the `receive` docs. It was already specified for `assert_receive`.
Anywhere else that I should check that might benefit from this addition? Feedback on way to introduce this/wording welcome as always :)
=> Specify that the timeout is expressed in milliseconds for increased clarity

lib/iex/lib/iex/helpers.ex
Because:
```
iex(2)> b(Dict)
No callbacks for Dict were found
```
=> Remove `b(Dict)` example

lib/elixir/lib/process.ex, lib/elixir/src/elixir_rewrite.erl, lib/elixir/test/elixir/process_test.exs
For some reason the `/4` version was missing.
=> Introduce Process.send_after/4

lib/iex/lib/iex/info.ex
Addresses the second item of #4617
=> Remove deprecated module compile time information

lib/logger/lib/logger.ex
Logger.metadata\1 recently got the ability to remove a key. Just updating the docs to inform users of this.
=> Update Logger.metadata\1 documentation

lib/elixir/lib/map.ex
Puts the given `value` under `key` in `map`.
The documentation for Map.put/3 refers to the `value` function argument, even though it is actually called `val`. We should rename it to `value` for consistency with other examples.
=> Change argument 'val' to 'value' in Map.put/3

lib/iex/lib/iex/info.ex, lib/iex/test/iex/info_test.exs
For atoms such as `LooksLikeAModule`, we don't show the raw representation (`:"Elixir.LooksLikeAModule"`). With this commit, we do. What does everyone think about this change? :)
=> Improve the i/1 IEx helper for module-like atoms

lib/elixir/lib/kernel.ex
This makes the code slightly uglier but I think the documentation benefits from it. Wdyt? :)
=> Fix the name of the last argument to defmodule/2 and defprotocol/2

lib/mix/lib/mix.ex, lib/mix/lib/mix/project.ex, lib/mix/lib/mix/task.ex, lib/mix/lib/mix/tasks/app.start.ex, lib/mix/lib/mix/tasks/compile.erlang.ex, lib/mix/lib/mix/tasks/compile.ex
The most important change is listing a few options supported by `project/0` in the documentation for the `Mix.Project` module. I've wanted to do this for a while since it's hard to get a grasp of what *can* be returned in `project/0`; this is not a comprehensive list but I hope it can still be helpful and at least point people to the right direction :)
=> Polish the documentation for a bunch of Mix.* modules

lib/mix/lib/mix/tasks/cmd.ex, lib/mix/test/mix/tasks/cmd_test.exs
Allows a list of apps to be passed to mix cmd and limits the execution of the cmd to only apps in the list. Defaults to all if list is empty.
example
`mix cmd --app1 --app2 mix test`
Todo:
Update tests
=> Allow a list of apps to be passed to mix cmd

lib/elixir/src/elixir_bitstring.erl, lib/elixir/src/elixir_interpolation.erl, lib/elixir/src/elixir_translator.erl
Some erlang code were emiting a warning message when some
variables were defined inside the case statement.
=> Fix some `exported from case` from erlang source

lib/elixir/pages/Typespecs.md
As discussed in https://github.com/elixir-ecto/ecto/pull/1689
=> Fix `struct` built-in type documentation

lib/elixir/lib/io/ansi.ex, lib/elixir/test/elixir/io/ansi_test.exs
I added a very basic spec, as well. I didn't see where these values were being tested explicitly, if they are.
If this can be merged, it might be nice to convert some of the warnings (I'm looking at mix, in particular) from `[:red, :bright]`, which is essentially bold light red to `[:light_red]`, which is... light red and seems more appropriate.
I would be more than happy to help with that work, as well, should you wish for it to be done.
=> Add light foreground and background colors to IO.ANSI

lib/mix/lib/mix/config.ex
In the docs for `Mix.Config.config/2` we show that we actually *merge* the configuration. In the example for `Mix.Config.config/3` however this is not as clear (and users could maybe think that config is replaced, not merged). This PR makes the example in `config/3` more similar to `config/2`. :)
=> Polish the example in the docs for Mix.Config.config/3

lib/elixir/lib/enum.ex
Based on
https://hashrocket.com/blog/posts/the-adventures-of-generating-random-numbers-in-erlang-and-elixir
There was no documentation about `Enum.random` accepting ranges and that it will not expand the range so it is safe to pass something like `Enum.random(1..100_000)`. This PR adds this documentation as well as a doctest.
=> Add documentation: `Enum.random` accepting ranges

lib/elixir/pages/Operators.md
As it was discussed with @whatyouhide in #5222, here is a quick attempt to add the missing key information around term ordering in the docs without directly copying the Erlang docs.
Let me know if you have any suggestions and/or comments.
Cheers!
=> Clarify some of the subtleties linked to term ordering in the docs

lib/elixir/pages/Operators.md
The current wording implies that e.g. `3.3` will be converted to `3`, which isn't the case.
=> Fix precision note in "Operators" doc

lib/elixir/lib/supervisor/spec.ex
=> exit(child, :kill) -> Process.exit(child, :kill)

lib/iex/lib/iex/helpers.ex, lib/iex/lib/iex/info.ex, lib/iex/test/iex/helpers_test.exs, lib/iex/test/iex/info_test.exs
With this PR, we show info about the protocols that a given data structure implements and in case that data structure is a module that is also a protocol, we show all the data structures that implement that protocols as well.
Opening this really early to get feedback on the feel of it and especially on how we find the protocols that a given data structure implements. I noticed that, as far as I can tell, using `Protocol.extract_protocols/1` + `Protocol.extract_impls/2` doesn't pick up protocols defined on the fly in the shell, but I may be getting something wrong or we may not care about this :)
Wdyt roughly? Style and implementation details will be refined before merging btw :)
=> Add info about protocols in the i/1 IEx Helpers

lib/mix/lib/mix/project_stack.ex
Fixes typespec for Mix.ProjectStack.project()
[This type is a tuple](https://github.com/elixir-lang/elixir/blob/v1.3.3/lib/mix/lib/mix/project_stack.ex#L8):
```
@typep project :: {module, config, file}
```
[This method returns a map](https://github.com/elixir-lang/elixir/blob/v1.3.3/lib/mix/lib/mix/project_stack.ex#L65):
```
@spec peek() :: project | nil
def peek do
get fn %{stack: stack} ->
case stack do
[h | _] -> take(h)
[] -> nil
end
end
end
```
Easiest would be to clone this project => [ProjectStackTypespec](https://github.com/amorphid/project_stack_typespec)
```
$ git clone git@github.com:amorphid/project_stack_typespec.git
$ cd project_stack_typespec
$ mix deps.get
$ mix dialyzer.plt
$ mix dialyzer
Starting Dialyzer...
...
example.ex:8: The pattern _stack@1 = #{'config':=_config@1, …
```
=> Fix typespec for Mix.ProjectStack.project()

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
It was incorrect when given a literal atom resembling an alias.
Fixes #5268
=> Fix Macro.to_string when printing keywords

lib/ex_unit/lib/ex_unit/capture_log.ex
=> Flush error_logger before capturing

lib/elixir/lib/process.ex
Hey :wave:
This PR improves the error message displayed when call to `Process.register/2` fails for any reason.
Currently the error is:
```
iex(2)> Process.register(self(), :test)
:erlang.register(:test, #PID<0.170.0>)
(elixir) lib/process.ex:414: Process.register/2
```
The new message is as follows:
```
iex(2)> Process.register(self(), :test)
** (ArgumentError) could not register the process #PID<0.81.0> with name :test. Or the process is not alive, or the name is already taken, or the process has already been named
(elixir) lib/process.ex:429: Process.register(#PID<0.81.0>, :test)
```
Detailed conversation about the different error cases can be found in PR #5278 
Thanks,
Ville
=> More helpful error message when Process.register/2 fails

lib/elixir/lib/gen_server.ex
The "(or `start/3`)" bit in the gen_server docs broke both the `)` from
showing up in the HTML, and the `start/3` link from working correctly.
Adding a space "(or `start/3` )" fixes both of those problems.
=> Fixes a silly typo in the docs

lib/elixir/lib/protocol.ex, lib/elixir/test/elixir/fixtures/dialyzer/protocol_opaque.ex, lib/elixir/test/elixir/kernel/dialyzer_test.exs
Prior to this change, calling a protocol function with an opaque type would yield a warning, as Dialyzer concludes that the `impl_for/1` function can't handle opaque arguments, since all clauses would destructure their arguments in some way.
By adding a catch-all clause that does not destructure its argument, Dialyzer no longer draws this conclusion, and the warnings go away.
As noted in the protocol.ex comment, this is technically a hack as it relies on Dialyzer not being smart enough. However, I would not expect it to break soon, if ever.
Of course, there is a non-hacky way of solving this problem, which is to not declare any type that implements a protocol as opaque in the first place. However, I believe the Elixir team will agree that such a restriction is undesirable.
=> Fix Dialyzer warnings on protocol calls with opaque arguments

lib/elixir/lib/enum.ex, lib/elixir/lib/stream.ex, lib/elixir/test/elixir/enum_test.exs, lib/elixir/test/elixir/stream_test.exs
Similar to the corresponding `zip/2` functions, except allows any number of
input enumerables.
Based on a [suggestion by José](https://groups.google.com/d/msg/phoenix-core/2EWFCMYxDBk/KLRWbYOEBQAJ) on the phoenix-core mailing list.
=> Implement Stream.zip/1 and Enum.zip/1

lib/mix/lib/mix/tasks/deps.compile.ex
Using `make` will fails for Erlang projects using `erlang.mk`.
=> Mix: use gmake on FreeBSD instead of make

lib/elixir/lib/task.ex
As discussed on the mailing list:
https://groups.google.com/forum/#!topic/elixir-lang-core/0uaxTaVN-bw
=> Improve `Task.yield/2` docs to suggest `Task.shutdown/1`

lib/ex_unit/lib/ex_unit/filters.ex, lib/ex_unit/test/ex_unit/filters_test.exs
Currently any tests tagged with `@tag :skip` will be skipped even if ExUnit is configured with `[include: :skip]`.
For instance:
```
ExUnit.configure include: :skip
@tag :skip
test "never run" do
raise "oops"
end
```
Produces:
```bash
Including tags: [:skip]
Finished in 0.05 seconds
1 test, 0 failures, 1 skipped
```
This seems confusing. I have changed the behavior in this PR to allow skipped tests to be included. However, if that is not the desired behavior then I would suggest at least emitting a warning instead of erroneously emitting `Including tags: [:skip]`. I'd be happy to make that change. Let me know. Thanks.
P.S. I do have a valid use case for this behavior which lead me to discover the issue. I'd be happy to elaborate if you need more information.
=> ExUnit includes tests when configured with [include: :skip]

lib/elixir/lib/access.ex
The following clearly works:
```elixir
iex(1)> get_in({nil, %{a: :b}}, [Access.elem(1), :a])
:b
```
However code like this fails to dialyze, due to `tuple` not being an allowed alternative in `Access.t`.
=> Add tuple to Access.t

lib/elixir/lib/calendar.ex, lib/elixir/lib/calendar/iso.ex
- Corrects spelling of "ISO 8601", a space must be used, as that's the name of the standard
- It adds a link to standard (pdf file)
- it changes "ISO 8601" to "ISO 8601:2004" where the year was ommited
=> Reword ISO 8601 and add link to standard

lib/elixir/lib/kernel.ex
There is one thing that could be improved, and it is the summary of the function:
> Concatenates two lists.
where right operand does not necessarily need to be a list
=> Kernel.++/2: comment on improper lists being returned

lib/elixir/lib/application.ex, lib/elixir/lib/enum.ex, lib/elixir/lib/exception.ex, lib/elixir/lib/file.ex, lib/elixir/lib/inspect.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/list/chars.ex, lib/elixir/lib/macro.ex, lib/elixir/lib/module.ex, lib/elixir/lib/string/chars.ex, lib/elixir/lib/system.ex, lib/elixir/lib/task.ex, lib/elixir/lib/task/supervisor.ex, lib/elixir/lib/uri.ex, lib/elixir/pages/Naming Conventions.md, lib/elixir/pages/Typespecs.md, lib/ex_unit/lib/ex_unit/callbacks.ex, lib/iex/lib/iex.ex, lib/iex/lib/iex/helpers.ex, lib/mix/lib/mix/tasks/compile.app.ex, lib/mix/lib/mix/tasks/escript.build.ex
- Add missing arities to functions, callbacks and types
- ~~Remove backticks from wildcard function references such as in
"`start*` functions", to use italics instead "_start*_  functions"~~
For posterity, the command used to find out these errors:
```console
$ ag "\`[^ /]+\`\s+(fun|function|callback|type|typespec|helper)"
```
=> Add/correct arities (part 3)

lib/elixir/lib/file.ex
* "It returns" -> "Returns" for consistency with the rest of the file
* Remove extra space in example for `File.stream!`
=> File doc changes

.travis.yml
Browsing the repo just noticed that the latest Erlang minor release was missing and thought it'd be a good idea to add it :)
=> Test against Erlang 19.1

lib/ex_unit/lib/ex_unit/on_exit_handler.ex
Agent is returning `nil` when it should be `[]`.
Before the fix
```console
$ mix test --timeout 0
1) TestTest: failure on setup_all callback, tests invalidated
** (EXIT from #PID<0.122.0>) an exception was raised:
** (Protocol.UndefinedError) protocol Enumerable not implemented for nil
(elixir) lib/enum.ex:1: Enumerable.impl_for!/1
(elixir) lib/enum.ex:116: Enumerable.reduce/3
(elixir) lib/enum.ex:1768: Enum.reverse/2
(ex_unit) lib/ex_unit/on_exit_handler.ex:29: ExUnit.OnExitHandler.run/2
(ex_unit) lib/ex_unit/runner.ex:307: ExUnit.Runner.exec_on_exit/3
(ex_unit) lib/ex_unit/runner.ex:231: ExUnit.Runner.run_test/3
(elixir) lib/enum.ex:645: Enum."-each/2-lists^foreach/1-0-"/2
(elixir) lib/enum.ex:645: Enum.each/2
(ex_unit) lib/ex_unit/runner.ex:162: anonymous fn/4 in …
```
=> Fix ExUnit case when dealing with timeout 0

lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/tasks/test_test.exs
I'm attempting to add ExUnit test integration to the IntelliJ Elixir plugin (https://github.com/KronicDeth/intellij-elixir) and it requires a custom formatter. I was unable to figure out an easy way to run the ExUnit tests from the IDE using a custom formatter without requiring the user to make changes to the project itself, which is not ideal for an IDE plugin.
It seems useful to have the formatter be a CLI option for `mix test`, as it is for Rspec: https://www.relishapp.com/rspec/rspec-core/v/2-4/docs/command-line/format-option .
I added the option `--format`, which can be passed more than once in case the user wants to use multiple formatters (though I'm not sure why one would want to).
I'm still an Elixir amateur, and feedback is very welcome.
=> Add --format option to `mix test` command

lib/ex_unit/lib/ex_unit/callbacks.ex, lib/ex_unit/lib/ex_unit/on_exit_handler.ex
Additionally it unifies the variables `name` and `ref` across functions by calling it `name_or_ref`.
=> ExUnit.OnExitHandler: improve specs and guards

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
As discussed in https://github.com/elixir-lang/elixir/pull/5362#discussion_r85313529
=> Remove space around * in bit syntax in Macro.to_string/2

lib/elixir/lib/kernel/typespec.ex, lib/elixir/pages/Typespecs.md, lib/elixir/test/elixir/kernel/typespec_test.exs
Closes https://github.com/elixir-lang/elixir/issues/5351
Typespecs page:
- Remove literal float
- Replace improper_list/2 with nonempty_improper_list/2
- Add nonempty_maybe_improper_list/2 and nonempty_maybe_improper_list/0
- Reword documentation and comments
- Group and reorder types a bit
- Reword documentation and comments
Tests:
- Add tests for every single type described in Typespecs page
- Also test the AST
=> Improve Typespecs page and test every document type

lib/elixir/lib/version.ex
This patch complements the current docs of `Version.compare/2` by specifying how versions compare when patch or build segments are present.
=> Complements the docs of Version.compare/2

lib/elixir/lib/kernel/special_forms.ex
=> Format improvements in Kernel.SpecialForms.<<>>/2 docs

lib/elixir/lib/map_set.ex, lib/iex/test/iex/helpers_test.exs
I added the `MapSet.t/1` opaque type (so that a set of specific values can be represented) and reworked the specs for the functions in the `MapSet` module to use the new type.
=> Add the MapSet.t/1 type and use it where possible

lib/ex_unit/lib/ex_unit/doc_test.ex, lib/ex_unit/test/ex_unit/doc_test_test.exs
Previously it was having a hard time discerning what to do with them, and included them in the compiled code for the doctest.
[Discussed and vetted](https://groups.google.com/forum/#!msg/elixir-lang-core/EsRK3n7sifo/MtaX0CRaBwAJ) on #elixir-lang-core.
=> Teach ExUnit.DocTest to handle fenced code block closings.

lib/elixir/lib/option_parser.ex, lib/elixir/test/elixir/option_parser_test.exs
Added an opts argument to OptionParser.to_argv. This way a user can point out args of `:count` type.
If guys agree with the approach I could add the appropriate documentation.
=> [WIP] Fixing :count support in OptionParser.to_argv

lib/mix/lib/mix.ex
See https://elixirforum.com/t/task-aliases-in-mix-ex-of-dependencies-ignored/2218
=> Clarification of aliases' non-visibility if defined in dependency

lib/elixir/src/elixir_map.erl, lib/elixir/test/elixir/kernel/errors_test.exs
In reference to https://github.com/elixir-lang/elixir/pull/5379#issuecomment-257079870 and https://github.com/elixir-lang/elixir/issues/5378
=> Use Macro.to_string/1 when printing bad struct keys

lib/elixir/lib/module.ex
Order should be the same when defining the callback as when implementing it
=> Improve Module docs: keep same order in Module's @callback example

lib/elixir/lib/kernel.ex
Just a little typo, `it` → `is` in the phrase
`If the left operand is not a proper list,`...
Thanks for Elixir!
=> Fix typo in Kernel doc

lib/elixir/lib/kernel.ex, lib/elixir/lib/kernel/error_handler.ex, lib/elixir/lib/kernel/lexical_tracker.ex, lib/elixir/lib/kernel/typespec.ex, lib/elixir/lib/kernel/utils.ex, lib/iex/test/iex/helpers_test.exs
Cover the specs and add guards to functions for the Kernel module, and for some submodules,
- lib/elixir/lib/kernel/error_handler.ex
- lib/elixir/lib/kernel/lexical_tracker.ex
- lib/elixir/lib/kernel/typespec.ex
- lib/elixir/lib/kernel/utils.ex
I think for we don't need to do anything
- kernel/special_forms.ex
some submodules have been left untouched
- kernel/parallel_compiler.ex
- kernel/parallel_require.ex
There are a few specs that the compiler cannot understand, marked as:
`# TODO: FIX: following line gives error`
Once this is merged, I will update in a new PR the documentation based on the specs.
Specially the one with `no_return`.
I'm still unsure about the specs for some macros and that needs reviewing.
=> [WIP] Complete specs and guards for Kernel module and some submodules

lib/elixir/lib/file.ex
I mentioned that the second argument can be a function and renamed variables to make that clearer. I also added a spec for when the second argument is a function to `File.open!/2`.
=> Improve the docs for File.open/2 and File.open!/2

lib/elixir/lib/record.ex
Module must be imported, otherwise the `user` macros won't be available.
=> Fix Record.defrecord/3 example

lib/ex_unit/lib/ex_unit/doc_test.ex, lib/ex_unit/test/ex_unit/doc_test_test.exs
Launching iex with:
$ iex --sname foo
The following code will break doctests
```
iex(foo@HOST)1> :foo
:foo
```
and will give a non descriptive error.
That's because "skip_iex_number" never found the ")>" piece, so it
consumes the line all the way to the end until it's empty.
=> Give a meaningful error when doctest has invalid prompt

lib/elixir/lib/enum.ex, lib/elixir/lib/stream.ex, lib/elixir/lib/stream/reducers.ex, lib/elixir/lib/uri.ex, lib/elixir/src/elixir_utils.erl, lib/mix/lib/mix/tasks/profile.fprof.ex
this corrects the very few cases left for functions and vars, but doesn't include a few tests that still keep this.
=> Remove use of underscore before ordinal numbers in functions and vars

lib/elixir/pages/Typespecs.md
These were missing from the docs. I'm not sure if mentioning them all in one line is the right way to do it, or should each be on a separate line.
=> Mention true, false and nil literals in typespecs

lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/erlang/tokenizer_test.erl
The <<<<<<< symbol is used by all major VC systems including [git](https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/), [subversion](https://tortoisesvn.net/docs/nightly/TortoiseSVN_en/tsvn-dug-conflicts.html) and [mercurial](https://www.mercurial-scm.org/wiki/TutorialConflict).
As proposed on the [mailing list](https://groups.google.com/forum/#!msg/elixir-lang-core/NHLXsV1e4uI/eHARgyRdBQAJ)
=> Make tokenizer recognize VC merge conflict marks

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/enum_test.exs, lib/elixir/test/elixir/kernel_test.exs
There's no need for a special handling of the underscore as the pattern,
the case expression is able of optimizing such cases too.
Additionally the right was never evaluated with underscore as the
pattern, which could lead to subtle bugs.
Currently match?(_, foo) will emit a pattern warning since both branches
of the case are exactly the same. This means such expressions had to be
removed from the test suite. They were replaced with the equivalent:
fn _ -> true end
=> Simplify Kernel.match?/2

lib/elixir/lib/calendar.ex
All /0 types don't use parens and all atoms, such as :lt, are wrapped
properly in backtics
Reference: https://github.com/elixir-lang/elixir/commit/35f492b746d0446b28274382ea359ffd1d55c278#commitcomment-19738734
=> Fix consistency in Calendar

lib/elixir/lib/record.ex, lib/elixir/test/elixir/record_test.exs
Each in separate commit:
* Document use of `record/1` with atom argument.
(it was not)
* In `record/1` used with record argument, raise ArgumentError on record size mismatch.
(when a given record matched the record tag, but not the size, FunctionClauseError was raised in private Record.join_keyword/3)
=> Two fixes in `record/1`

lib/elixir/lib/kernel.ex, lib/elixir/lib/kernel/utils.ex
I removed the examples that used deprecated features,
as well as mention which options have been deprecated.
=> Update defdelegate/2 docs to reflect deprecated features

lib/elixir/lib/access.ex, lib/elixir/lib/kernel.ex
Improves docs, specs and guards for Kernel.get_and_update_in/3 and Access.get_and_update/3
=> Improve docs, specs and guards for get_and_update functions

lib/elixir/lib/kernel.ex
Additional some examples changed to not to use "iex>" since
warnings will be emited with inlined functions.
=> Document when some functions raise in Kernel module

lib/elixir/lib/kernel.ex
Hi all,
I've seen recent PRs making a few var names more declarative, and wonder what you think of these.
I was trying to understand `define/4` in `Kernel`, and came across vars `ue` and `uc` which, at least to me, weren't quickly self-evident.
So I wonder if I even interpreted them right, and also if you think this improves things at all.
If so...great.
=> Rename vars in Kernel

lib/elixir/lib/kernel.ex
Hi all,
just a little typo in the doc for `defstruct`.
Thanks!
=> Fix typo in Kernel

lib/elixir/test/elixir/kernel_test.exs
Hi all,
came across this sequence of defs which was neither aligned nor inlined, so to speak.
This PR removes the spaces.
If you prefer to align all do's, I'll be happy to change it to that.
Cheers!
=> Inline do in def sequence for KernelTest

lib/elixir/lib/string.ex
From `insert_replace` to `insert_replaced`.
=> Fix typo on String.replace doc

lib/elixir/lib/inspect.ex, lib/elixir/lib/inspect/algebra.ex, lib/elixir/test/elixir/inspect/algebra_test.exs, lib/elixir/test/elixir/inspect_test.exs, lib/iex/lib/iex/config.ex, lib/iex/test/iex/interaction_test.exs
Hello!
This weekend I took a stab at adding syntax highling to the repl, inspired by a thread on the mailing list a while back. Here's what I have so far- is this along the right lines?
Additionally there are a few problems.
- After these changes the Inspect protocol seems to wrap far too early. I don't understand how `Inspect.Algebra` works, so I wasn't sure how to resolve this.
- There is additional color configuration for IEx. I'm unsure how this should be changed to fit with syntax highlighting.
=> Syntax highlighting of IEx results

lib/elixir/lib/inspect/algebra.ex
- Renamed a few single-letter variables
- Slightly polished some docs
- Added a few guards here and there
I am not very sure about all the guards, for example some functions call `concat/2` directly and `concat/2` checks for `is_doc/1`, so maybe we could skip the check in the caller function. What's your opinion on this?
One more thing: some functions return `Inspect.Algebra.t`, some return `doc_*` (like `doc_cons`). Since those are private types, couldn't we say everything returns `t` (so that we can flexibly change in the future as well) since it's technically true, just a superset of the real return value?
=> Generally improve code readability in Inspect.Algebra

lib/elixir/lib/inspect/algebra.ex, lib/elixir/test/elixir/inspect/algebra_test.exs
The old spec said that the `left`, `right`, and `separator` arguments had to be binaries but they can instead be documents. I missed this in #5446 😛
=> Fix the spec and guards for Inspect.Algebra.surround_many/6

lib/elixir/test/elixir/kernel_test.exs
Hi all,
a double space. Sorry I missed that in my last PR.
Cheers!
=> Remove double space from KernelTest

lib/elixir/test/elixir/kernel_test.exs
Hi all,
in `KernelTest`, found a duplicated assertion, and also a pair of lists that were formatted differently from each other.
Cheers!
=> Remove duplicated assertion and improve formatting

lib/elixir/lib/module.ex
The usage with __ENV__ as the first argument to Module.eval_quoted was found in [Ecto's schema.ex](https://github.com/elixir-ecto/ecto/blob/master/lib/ecto/schema.ex#L392) but that was not reflected in the docs.
I thought I might add an example for that. Is it ok?
=> Add doc example for Module.eval_quoted with __ENV__ as first argument

lib/elixir/lib/kernel/special_forms.ex
Gives an example of aliasing multiple modles on a single line
=> Add Elixir 1.2's multi alias to the docs

lib/elixir/lib/kernel.ex
It raises `ArithmeticError`, not `ArgumentError`.
=> Fix the doc of arithmetic division (`/`)

lib/logger/lib/logger.ex
I would love this for documentation purposes, I am just wondering if users may not be supposed to know what these functions return (since they're just for side effects, most of them). I still think it's nice to have it documented and public though :)
=> Add specs to a few Logger functions

lib/mix/lib/mix/dep/converger.ex, lib/mix/test/mix/dep_test.exs
Only reverse at the end instead of doing multiple reverses that will
mess with the full order of dependencies.
=> Fix converger order

lib/elixir/lib/code.ex, lib/elixir/test/elixir/code_test.exs
\cc @josevalim, related to #5470, since `Code.compiler_options/1` is called down the road it may be worth improving the already existing validation there as well.
=> Validate options in Code.compiler_options/1

lib/mix/lib/mix/tasks/compile.elixir.ex, lib/mix/test/mix/tasks/compile.elixir_test.exs
On the road to #5388.
I'm on the fence on what to do with `:elixirc_options` here, since they're not set and changed here. Not sure where would be the best place to validate those 😕
=> Improve options validation in Mix.Tasks.Compile.Elixir

lib/mix/lib/mix/tasks/compile.app.ex, lib/mix/lib/mix/tasks/deps.ex, lib/mix/lib/mix/tasks/new.ex, lib/mix/test/mix/tasks/app.tree_test.exs, lib/mix/test/mix/tasks/compile.app_test.exs, lib/mix/test/mix/tasks/escript_test.exs
Before merging this, we need to validate two design decisions:
1. The list of applications is built per environment. This means test only dependencies, such as `{:meck, "> 0.0.0", only: :test}`, will be added to the list of applications when compiled for test (**and only for test**). This means `:meck` no longer needs to be started manually.
2. To disable a dependency from being added to the list of applications, we can pass the `runtime: false` to the dependency. Such as `{:mech, "> 0.0.0", only: :test, runtime: false}`. This will disable it from being added to any environment, specially test in this case. Is `:runtime` the best name here?
The reason I decided to go with `1.` is because inflecting the list of dependencies becomes hard otherwise. For example, if we decide to only include …
=> Automatically inflect the list of applications, closes #5249

lib/elixir/lib/enum.ex
After @josevalim [commit](https://github.com/elixir-lang/elixir/commit/a4682f383d104c350df5c9313aec5d8c953abeb2) yesterday I was playing around with this trying to optimize it a bit more.
What I got seems to be around 30% faster testing with a "noop" reduce function like 
```
def noop(_x, acc) do
acc
end
```
Here is also the implementation as a [gist](https://gist.github.com/gustf/84d57a8501234587bd8bf9e97268b7ca) that I used for testing.
Example result I got was
```
iex(30)> :timer.tc(ReduceTest, :reduce_new, [1..10000000, 1, &ReduceTest.noop/2]) 
{331031, 1}
iex(31)> :timer.tc(ReduceTest, :reduce_new, [10000000..1, 1, &ReduceTest.noop/2]) 
{339605, 1}
iex(32)> :timer.tc(ReduceTest, :reduce, [1..10000000, 1, &ReduceTest.noop/2])    
{474536, 1}
iex(33)> :timer.tc(ReduceTest, :reduce, …
```
=> optimized reduce for range

lib/elixir/lib/stream.ex
By warning about its blocking behavior and suggesting the use of `Stream.iterate/2` for generating number sequences.
=> Improve Stream.interval/1 documentation

lib/mix/lib/mix/rebar.ex, lib/mix/lib/mix/tasks/deps.compile.ex, lib/mix/test/fixtures/rebar_dep/rebar.config.script, lib/mix/test/mix/rebar_test.exs
Closes #4913.
REBAR_CONFIG bug fixed in rebar3 https://github.com/erlang/rebar3/pull/1387. On the next rebar3 release we need to update `mix local.rebar`.
=> Disable warnings_as_errors for rebar3 dependencies

lib/elixir/lib/list.ex
Hey all,
another PR of highly questionable usefulness.
Removed a double line-break inside a `@doc`.
Cheers!
=> Remove double line-break in List

lib/elixir/lib/enum.ex
When I was using `Enum.uniq_by` the following example in the docs helped me understand that the first occurrence of each element was preserved.
```elixir
iex> Enum.uniq_by([{1, :x}, {2, :y}, {1, :z}], fn {x, _} -> x end)
[{1, :x}, {2, :y}]
```
However, the correctness of my code depended on this behavior. So I had to double-check with the source to make sure that this was the case.
I we should explicitly say the first occurrence is kept.
Thoughts?
=> Add clarification to Enum.uniq_by

lib/elixir/lib/keyword.ex, lib/elixir/test/elixir/keyword_test.exs
Similar to
https://github.com/elixir-lang/elixir/pull/5466
It makes sure a valid keyword is given as both arguments.
Additionally, it adds tests to make sure Keyword.merge/2 and /3
work exactly the same way.
Related issue:
https://github.com/elixir-lang/elixir/issues/5395
=> Raise when given non-keyword-lists in Keyword.merge/3

lib/iex/lib/iex.ex
It wasn't clear to me from documentation how to print all of the entries in IEx. As it's useful option while debugging, might be useful to have it in IEx documentation as example.
=> Document how to show all the entries in IEx

lib/iex/lib/iex/autocomplete.ex, lib/iex/lib/iex/evaluator.ex, lib/iex/lib/iex/server.ex, lib/iex/mix.exs, lib/iex/test/iex/autocomplete_test.exs
Eventually we may want to take this a step further and support autocompletion of the variable names themselves but I don't have time today to look into that and that would probably be a separate PR.
I noticed that 1.4.0.rc-0 was just released...any chance this could be included in 1.4?  This is a feature I've long wanted and I'd be sad to see it pushed out months :(.
=> Improve IEx autocomplete to support navigating map atom keys

lib/elixir/pages/Writing Documentation.md
- Plain links were not being autolinked
- Links have been updated since GitHub seems to have removed the first one and now old links are
redirecting to different pages
NOTE: I'm not too sure about whether we should include the the second link as it overlaps with the first one
=> Update links for learning Markdown

CHANGELOG.md, lib/mix/lib/mix/tasks/compile.app.ex, lib/mix/test/mix/tasks/compile.app_test.exs
Might this be a clearer name for it?
=> Mix/changelog: Change "Application inflection" to "Application inference"

lib/elixir/lib/tuple.ex
Hi all,
`Tuples are ordered collection` → `Tuples are ordered collections`
Cheers!
=> Fix typo in Tuple moduledoc

lib/iex/lib/iex/autocomplete.ex, lib/iex/lib/iex/evaluator.ex, lib/iex/test/iex/autocomplete_test.exs
=> Improve IEx autocompletion to handle variable names.

lib/elixir/lib/string.ex, lib/elixir/src/elixir_dispatch.erl, lib/elixir/src/elixir_rewrite.erl
First in a set of deprecations to be implemented for 1.5. I'd love to take care of all of them if no one argues against that :)
Also, I am not 100% sure we should keep the implementation in both `elixir_rewrite` as well as `String`, but it seems to be what we do for other rewrites. Suggestions?
=> Hard-deprecate String.*strip/1,2 functions

lib/elixir/lib/gen_event.ex
Should we give people pointers to alternatives to GenEvent or to things like @josevalim's [blog post](http://blog.plataformatec.com.br/2016/11/replacing-genevent-by-a-supervisor-genserver/) in the docs for GenEvent?
=> Soft-deprecate GenEvent

lib/elixir/lib/application.ex, lib/elixir/lib/enum.ex, lib/elixir/lib/gen_server.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/module.ex, lib/elixir/lib/regex.ex, lib/mix/lib/mix/tasks/profile.fprof.ex
command used to find these cases:
$ ag '(?<!\[)`\:[^`]+`\s+module'
=> Add links to Erlang modules

lib/elixir/lib/application.ex
Hi all,
`when an the application` → `when an application`.
Cheers!
=> Remove extra article from Application start callback doc

lib/elixir/lib/application.ex
Hi all,
`from another mode` → `from another node` 
Cheers!
=> Fix typo in Application start callback doc

lib/elixir/test/elixir/system_test.exs
Git since v2.11 no longer defaults to 7-hexdigits for short object
abbreviation.
See https://github.com/git/git/commit/e6c587c733b4634030b353f4024794b08bc86892
=> Fix system_test

lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/kernel/errors_test.exs
<strike>I took a stab at #5527 but I am definitely not sure this is the way to go, would love opinions on this as I'm sure I will learn something out of it :).</strike>
Closes #5527.
Btw, it doesn't work for `fn (...) do ... end`, but it should still be a worthy improvement.
=> Improve syntax error for "fn do ... end"

lib/elixir/lib/application.ex
Hi all,
`automatically__load` → `automatically load`.
Cheers!
Gustavo
=> Remove double space from application doc

lib/mix/lib/mix/tasks/escript.build.ex, lib/mix/test/mix/tasks/escript_test.exs
I wonder, could this veeery simple change be a solution for #5529? 🤔 :)
=> Use :extra_applications instead of :applications in escript.build

lib/elixir/lib/access.ex
Hi all,
`can also be used … to for updating`  → `can also be used …
for updating`
Cheers!
=> Remove redundant preposition from Access doc

lib/iex/lib/iex.ex
The name of the field and documentation are a bit misleading. The width configruation parameter is actually the maximum width. It might makes sense to change the field name to max_width instead of width.
=> Improve IEx width configuration width

lib/elixir/lib/process.ex
`when a processes` -> `when a process`
=> Typo on Process module doc

CHANGELOG.md
I noticed this wasn't listed in the changelog.
=> Mention new IO.inspect/2 :label option in changelog.

lib/elixir/lib/supervisor/spec.ex
Clarify that `:transient` supervisor will not be restarted when reaches `max_restart_intensity` because of `:shutdown` exit reason.
It would be nice to have someone who will proofread changes :).
=> :transient supervisor restart clarification

lib/elixir/lib/agent.ex, lib/elixir/lib/gen_server.ex, lib/elixir/lib/supervisor.ex
It's an important information, that makes the concerned functions much more
useful in contexts where synchronous termination is important, such as cleaning
up related processes in tests.
=> Highlight that :gen.stop/3 is synchronous

lib/mix/lib/mix/tasks/escript.build.ex
I couldn't build the example code without using `use Mix.Project`.
I could build it with using `use Mix.Project`.
```
/Users/niku/sandbox% cat mix.exs
defmodule MyApp.Mixfile do
def project do
[app: :my_app,
version: "0.0.1",
escript: escript()]
end
def escript do
[main_module: MyApp.CLI]
end
end
defmodule MyApp.CLI do
def main(_args) do
IO.puts("Hello from MyApp!")
end
end
/Users/niku/sandbox% mix escript.build
** (Mix) Could not find a Mix.Project, please ensure a mix.exs file is available
```
```
/Users/niku/sandbox% cat mix.exs
defmodule MyApp.Mixfile do
use Mix.Project
def project do
[app: :my_app,
version: "0.0.1",
escript: escript()]
end
def escript do
[main_module: MyApp.CLI]
end
end
defmodule MyApp.CLI do
def main(_args) do
IO.puts("Hello from MyApp!")
end
end …
```
=> Make the example a valid mix project

lib/ex_unit/lib/ex_unit/on_exit_handler.ex, lib/iex/lib/iex/autocomplete.ex, lib/logger/lib/logger/translator.ex, lib/logger/lib/logger/utils.ex, lib/mix/lib/mix/generator.ex, lib/mix/lib/mix/local/installer.ex, lib/mix/lib/mix/tasks/new.ex
Fixing white-space inconsistencies around operators, parentheses and trailing white-space on all projects outside elixir.
=> Fix whitespace inconsistencies outside Elixir lib

lib/elixir/lib/enum.ex
reduce/3 has clauses specialized for various enumerable types, so should be
much faster than the general Enumerable.reduce/3 case, especially that we don't
need additional facilities like terminating the reduction early.
Comparing 3 implementations:
* map based
elements |> Enum.map(&(if check(&1), do: 1, else: 0)) |> Enum.sum
* count/2 based
elements |> Enum.count(&check/1)
* filter based
elements |> Enum.filter(&check/1) |> Enum.count
We get following results before and after the change:
len   | map       | count before | count after | filter
------|-----------|--------------|-------------|------------
10    | 2.1706 μs | 7.0754 μs    | 1.6304 μs   | 1.9765 μs
100   | 19.921 μs | 27.579 μs    | 13.057 μs   | 14.591 μs
1000  | 168.93 μs | 178.93 μs    | 130.76 μs   | 163.43 μs
10000 | …
=> Optimize Enum.count/2

lib/mix/lib/mix/compilers/test.ex, lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/tasks/test_test.exs
This born in a discussion on this issue #5556.
=> Better behavior for the default test task when no tests were found

lib/elixir/lib/task.ex, lib/elixir/lib/task/supervisor.ex
Noticed some errors in the documentation of `Task.async_stream` and friends...
=> Correct documentation referencing System.schedulers_online/1 to System.schedulers_online/0.

lib/elixir/lib/keyword.ex
We do this for maps for example, maybe it's worth doing for keywords as well. Not sure this is the best place since `{:ok, foo: :bar}` is allowed as well, but I think it's a good start anyways :)
=> Talk a bit about keyword syntax in the Keyword module

lib/iex/lib/iex.ex
This is definitely missing in the IEx documentation. Nobody knows for sure how to do this )
I've also noticed the `q` option is missing in the `BREAK` menu. But I can't find the menu definition in the source files.
=> Add explanation how to quit the IEx shell

lib/elixir/lib/system.ex
Hello! I'm wondering why there is already [`System.halt`][1] which is equivalent of Erlang's [`halt`][2] for quick shutdown, but there is no equivalent of Erlang's [`init:stop`][3] for clean and smooth shutdown. I even have not found any notes about `:init.stop` in the Elixir documentation. Is this not needed in Elixir for some reason?
This is sure not so big deal, but I really feel some inconsistency in this place :) I've prepared this PR for the case you feel this logical to have both `halt/1` and `stop/1` in the Elixir module. Thanks for your attention!
[1]: https://hexdocs.pm/elixir/System.html#halt/1
[2]: http://erlang.org/doc/man/erlang.html#halt-0
[3]: http://erlang.org/doc/man/init.html#stop-0
=> Add System.stop/1 over :init.stop like System.halt/1 over :erlang.halt

README.md
I always thought test_elixir was broken as from the directory
structure I'd have expected it to only run the tests in elixir
e.g. the standard library which is what I mostly touch around
here :) However, it always ran almost everything.
A look at the Makefile reveals that this seems intentional but
that there's also test_stdlib, which seems for to point out in
the README imo.
as always, thanks for elixir :green_heart:
=> Clarify how to use test_stdlib instead of test_elixir

lib/elixir/lib/agent.ex, lib/elixir/test/elixir/agent_test.exs
Read the docs and thought it'd be nice to have usage examples
right there so why not make it doc tests :)
It's a bit repetetive as you always need to start the agent and
I figured even for start/start_link it'd be nice to show that
the value now lives there but that might be discussion worthy.
I also started out always calling Agent.stop to stop the agent
(the other agent tests do that) but the GenServer tests don't
seem to shut it down every time so I thought it might be okay
here in favor of less clutter and to have more clarity :)
Happy about feedback!
=> Doctests for basic agent functionality

lib/elixir/lib/file.ex
The documentation for the `File.dir?/1` function didn't explicitly
state that certain shell conventions (like `~`) would not be
automatically expanded in this function, so I'm adding more
clear documentation including examples for how to use this function.
Closes #5565
=> Update docs for `File.dir?/1`

lib/elixir/lib/float.ex, lib/elixir/test/elixir/float_test.exs
Fix for [issue](https://github.com/elixir-lang/elixir/issues/5593).
Zero has sepcial encoding as IEEE754 floating point number with a 0 value for exponent. This encoding requires special handling in current Float.round implementation.
=> Fix ceil function with zero as input

lib/elixir/lib/version.ex
Hi all,
`…the default is to allow always allow…` → `…the default is to always allow…`
Happy new year!
=> Remove redundancy from Version doc

lib/elixir/test/elixir/version_test.exs
Hi all, 
`use___ExUnit.Case, async: true` → `use ExUnit.Case, async: true` with no lines around justifying the multiple space.
Cheers!
=> Remove isolated multiple space from VersionTest

lib/elixir/lib/path.ex, lib/elixir/test/elixir/path_test.exs
Now, `Path.relative("/")` returns `"."` instead of the empty string for unix systems.
I'm afraid that even if it's a simple change, that could a breaking change.
=> Adding "/" special case in unix's Path.relative

lib/elixir/lib/task.ex, lib/elixir/lib/task/supervised.ex, lib/elixir/test/elixir/task_test.exs, lib/logger/test/logger/translator_test.exs
We do so by starting the tasks directly in the monitor
process, which in this case takes care of linking and
therefore we only need to clean up the monitor process
message.
Closes #5554
=> Cleanup exit messages on Task.async_stream

lib/elixir/lib/file/stream.ex, lib/elixir/test/elixir/file_test.exs
Results of initial benchmarks using https://github.com/michalmuskala/file_count_optim
```
-##### With input Huge (1000000 lines) #####
Name                  ips        average  deviation         median
proposed             4.02      248.64 ms     ±3.62%      248.58 ms
recur_count          3.40      294.41 ms     ±4.37%      290.18 ms
read_line            1.22      817.86 ms     ±3.91%      806.50 ms
current              1.08      925.23 ms     ±5.24%      911.27 ms
Comparison:
proposed             4.02
recur_count          3.40 - 1.18x slower
read_line            1.22 - 3.29x slower
current              1.08 - 3.72x slower
-##### With input Medium (10000 lines) #####
Name                  ips        average  deviation         median
proposed           452.59        2.21 ms    ±11.83% …
```
=> Optimize Enumerable.count/1 implementation for File.Stream

lib/elixir/lib/registry.ex
While going through the Registry doc, I found a broken hash link which might be caused by a bug in `ex_doc`. Specifically, when a closing back tick is followed by a close parenthesis, the latter becomes part of the link. Instead of working around the problem, I decided to remove the parentheses altogether to avoid any ambiguity.
=> Fix broken hash link in Registry doc

lib/elixir/lib/regex.ex, lib/elixir/test/elixir/regex_test.exs
We were not escaping the `-` character, commonly found in character
classes, in cases where it is being used on its own. I've added a test
for this new escape behavior, and also implemented the change.
Resolves #5624
=> Add `-` to Regex.escape/1

lib/iex/lib/iex/helpers.ex
Affect from v1.4 to master.
Changed:
- Let IEx.Helper.import_file/2 not to generate doc
- Add description of import_file_if_available/1 to `moduledoc`
I'm really sorry not to align `import_file_if_available/1`,
however, I think it's too hard to read to developer who update this. ;)
Thanks to read and Happy new year, all XD
=> IEx.Helper documention improvement

lib/elixir/lib/uri.ex
Hi all, 
just a paren on the loose inside a comment.
Cheers!
=> Remove dead paren from URI comment

lib/elixir/lib/path.ex, lib/elixir/test/elixir/path_test.exs
Also fix the spec for `Path.join/1` to mention that the input list of paths has to be non-empty, and fix the documentation to mention that this function takes a list of paths (`Path.t`), not strings like it said before.
Closes #5637.
=> Fix Path.join/1 for lists of one element

lib/elixir/lib/map.ex
Fix a typo in the docs for `Map.split`.
=> Fix a typo in Map

lib/iex/lib/iex/autocomplete.ex, lib/iex/lib/iex/helpers.ex, lib/iex/test/iex/helpers_test.exs
=> Adding export helper. Solves #5633

lib/iex/lib/iex/helpers.ex
This PR makes the new `e/1` IEX helper not return `:ok`.
Before:
```
iex(1)> e Elixir.Tuple
append/2        delete_at/2     duplicate/2     insert_at/3     to_list/1       
:ok
```
After:
```
iex(1)> e Elixir.Tuple
append/2        delete_at/2     duplicate/2     insert_at/3     to_list/1       
```
=> Fix e/1 IEx helper to not return :ok

lib/iex/lib/iex/evaluator.ex
Found it while skimming over the IEx code. It's just a comment in a
private function, so you guys decide whether this pollutes git history.
✌️
=> Fix a typo in IEx.Evaluator.prune_stacktrace

lib/elixir/test/elixir/uri_test.exs
Hi all,
`to_stirng` → `to_string` in test name.
Cheers!
=> Fix typo in URITest test name

lib/elixir/lib/map_set.ex
It changes the documentation of [MapSet.new](https://hexdocs.pm/elixir/MapSet.html#new/1) function to show it takes any enumerable and not just a mapset.
It also makes it consistent with Map.new
=> Make MapSet.new doc more descriptive

lib/mix/lib/mix/compilers/elixir.ex
When preparing file lists for compilation, the code groups file paths according the their status: removed, changed_mtime, or new. 
Before this change, the code would traverse the previous list of files and the current list of files inner loop. This leads to inefficient N^2 complexity. This happens twice when makeing a list of removed files and when making a list of new files. Using sets we can reduce the complexity to average N.
According to the benchmarks on my machine (Intel core i7 6700k), with a project that has 10k files, this optimization consistently saves 700-800 ms.
=> Optimize elixir compiler setup for large projects
