elixir-lang/elixir

lib/iex/lib/iex.ex

Hello, the sentence in `IEx.pry/0` documentation seems malformed. I fixed it based on my understanding of its meaning.

Fix typo in IEx.pry/0 documentation

---

lib/elixir/src/elixir_map.erl
lib/elixir/test/elixir/map_test.exs

Fixes [issue 5602](#5602).
Erlang does not accept map_field_exact tag for map used as map keys
since it does not perform any matching on map keys.
For example this fails:
```
$ erl
Erlang/OTP 19 [erts-8.2] [source-a2c5a92] [64-bit] [smp:8:8]
[async-threads:10] [hipe] [kernel-poll:false]
Eshell V8.2  (abort with ^G)
1> #{ #{1 => X} := 3 } = #{ #{1 => 2} => 3 }.
* 1: illegal map key in pattern
```

Fix translation of maps used as map keys

---

lib/elixir/lib/system.ex

Changed "problem" to "program".

Fix wrong word in System.cmd docs

---

lib/elixir/lib/port.ex

In the documentation it states that the port data format is
{port, {:port, data}}
but the examples show it is
{port, {:data, data}}
Fixed this in the documentation.

Fix port message format

---

lib/logger/lib/logger.ex

In a [mailing list conversation](https://groups.google.com/d/msg/elixir-lang-core/LNZNyUGTdno/9PpvJ8htCQAJ) we decided Logger docs should encourage lazily evaluated messages over potentially expensive computations that might not get used. This change aims to do that.

Logger docs: recommend using thunks for expensive computations.

---

lib/mix/lib/mix/shell/io.ex
lib/mix/lib/mix/shell/quiet.ex

This is the actual regex:
https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/shell/io.ex#L68
IMHO, this behaviour to return true on emply line seems surprising. I can imagine someone writing
```IO.yes?("launch_nukes?")```

Fix Mix.Shell.IO.yes? documenation

---

lib/elixir/lib/enum.ex
lib/elixir/lib/stream.ex

Flat_map/2 doesn't contain info about flattening, but flat_map_reduce/2 does. It was not consistent.

comment to Enum.flat_map/2 about flattening

---

lib/elixir/src/elixir_translator.erl
lib/elixir/test/elixir/kernel/errors_test.exs

Only arith BIFs are allowed in matches.
Partial fix for #5666.

Improve error when using non-arith guard BIF in match

---

lib/elixir/lib/macro.ex
lib/elixir/test/elixir/macro_test.exs

The screaming snake case was keeping its original format after being
camelized. As mentioned in issue #5627. This change allows it to behave
like the all lower snake case when camelized.
Amos King @adkron <amos@binarynoggin.com>

Fix Macro.camelize/1 for screaming snake case

---

lib/elixir/lib/macro.ex
lib/elixir/test/elixir/macro_test.exs

We had some unexpected behavior when trying to use `Macro.underscore/1`
for screaming snake case strings. This commit fixes that!
Resolves #5627

Fix Macro.underscore/1 for screaming snake case

---

lib/elixir/lib/calendar.ex

Improve the documentation-level signatures for functions that take
generic argument types (e.g. `map`, `arg`) by adding empty function
heads with more specific argument names (e.g. `date`).
Also, fix references to the nonexistent `Calendar.native_datetime` type;
it's spelled `Calendar.native_date_time`.
And lastly, fix up some of the DateTime typespecs that still referred to
`DateTime.t` when they now expect `Calendar.date_time`.

Documentation signature and typespec improvements

---

lib/elixir/lib/protocol.ex

When running dialyzer with `-Wunderspecs` against code that contains protocol definitions, one will receive warnings about the generated `__protocol__/1` function like below:
```
lib/collectable.ex:1: The specification for 'Elixir.Collectable':'__protocol__'/1 states that the function might also return 'true' but the inferred return is 'Elixir.Collectable' | 'false' | [{'into',1},...]
```
The stated spec generated in the macro, which is technically correct, contains:
```elixir
@spec __protocol__(:consolidated?) :: boolean
```
The macro-generated function returns only `false` before consolidation, and only `true` after consolidation. The [typical solution](http://stackoverflow.com/questions/37668522/how-to-avoid-dialyzer-errors-for-protocols) to avoid this dialyzer warning is to add an …

Fix dialyzer underspec warning with __protocol__/1

---

lib/elixir/lib/kernel.ex

Defining a protocol implementation for binaries is done with `for: BitString`, not `for: Binary`.

Fix `Kernel.defprotocol` documentation bug.

---

lib/elixir/lib/exception.ex
lib/elixir/lib/inspect.ex
lib/elixir/lib/macro.ex
lib/elixir/test/elixir/exception_test.exs
lib/elixir/test/elixir/inspect_test.exs
lib/elixir/test/elixir/kernel/errors_test.exs
lib/elixir/test/elixir/kernel_test.exs
lib/elixir/test/elixir/macro_test.exs

With this commit, we fix the inspection (both in `Macro.to_string/2` as well as `Exception.format_mfa/3`) of function calls with "weird" atoms like:
Foo."Bar"() # was inspected as Foo.Bar()
Foo."..."() # was inspecetd as Foo....()
and many others.
This is a rework of #5606, which was aimed at #5605.
@josevalim: I went with implementing `Inspect.Atom.classify/1`, but tailored the result to function calls specifically (`:callable`, `:non_callable`) as it turns out this is enough to reuse the logic in `Inspect.Atom.inspect/1` as well.

Correctly inspect function calls with weird atoms

---

lib/mix/lib/mix/scm/git.ex
lib/mix/test/mix/tasks/deps.git_test.exs

I traced the cause of #5525 (for me, anyway) to my global git template, which didn't have an `info/` subdirectory; this caused `Mix.SCM.Git.sparse_toggle/1`'s write to a file in `info/` to fail, causing the same three test failures reported in that issue.
The fix just adds a `File.mkdir_p!/` to make sure the directory exists before writing.
I also modified an existing sparse-checkout test (temporarily adding a git template without `info/`) to show the failure when the fix isn't present; I'm happy to rework this test if you don't think it's the right approach (or remove it entirely).

Tolerate missing git repo "info/" when setting sparse configuration (#5525)

---

lib/elixir/lib/map_set.ex

Made the function signatures and docs normalize on `map_set` (not `set` or `mapset`). Most of the documentation in this module used`map_set`, so I made everything use that. However, the documentation code generally uses `set` in the examples, so I could see an argument to have everything say `set` instead. I don't have a strong opinion one way or the other, I just want the docs to be consistent 😄

Minor Docs Fixup - MapSet

---

lib/mix/lib/mix/rebar.ex
lib/mix/test/mix/rebar_test.exs

Currently only {app, “~> 1.0.0”, {pkg, hex_package}} is supported. This
change will also support {app, {pkg, hex_package}}.

Support rebar3 dependency package declaration

---

lib/mix/lib/mix/tasks/local.hex.ex

In automation scripts like `make`, `--force` flag causes reinstallation of Hex
every time `mix` is run (to avoid hanging on prompt), which is unnecessary.
Locating that Hex is installed from make tasks is not a trivial task,
so adding `mix local.hex --if-missing` would be much more convenient.

Add --if-missing flag to local.hex mix task

---

lib/elixir/lib/kernel.ex

The `start` argument for `Kernel.binary_part/3` can be `0`, therefore I think `non_neg_integer` is a more accurate type spec for it than `pos_integer`.

Fix Kernel.binary_part/3 spec

---

lib/elixir/lib/io/ansi.ex

The public `@type` for `IO.ANSI.ansidata` references `IO.ANSI.ansilist` and `IO.ANSI.ansicode`, so dialyzer complains about missing type for them when referencing `IO.ANSI.ansidata`:
```
Unknown types:
'Elixir.IO.ANSI':ansicode/0
```
From https://hexdocs.pm/elixir/IO.ANSI.html#t:ansidata/0 it seems as though the intention was for them to be public, so I made them public. This is not the forum for this, necessarily, but I do not think public types should be able to reference private types. An `@spec` should also not be able to reference a `@typep` for a public function. I believe something should have warned or errored from this usage.

Made IO.ANSI.ansicode and IO.ANSI.ansilist public types.

---

lib/elixir/lib/application.ex
lib/mix/lib/mix/tasks/compile.app.ex

This callback from the `:application` module wasn't originally included in `Application`.  In addition, the mix docs did not include information on how to define start phases or included applications, even though it was possible to define and use them.
I think these additions would be useful as the underlying functionality is already there and works, just without documentation (in Elixir).

Add Application.start_phase/3 callback and associated docs

---

lib/mix/lib/mix/tasks/new.ex
lib/mix/test/mix/tasks/new_test.exs

The following command should fail.
$ mix new invAlid
According to [this function](https://github.com/elixir-lang/elixir/blob/c1acfe9827f12ef58f7f301baad7497472cb4bc9/lib/mix/lib/mix/tasks/new.ex#L160), app names should only include lowercase letters, numbers, and underscore.
This pull request updates the function to enforce "only include lowercase letters, numbers, and underscore".
assert_raise Mix.Error, ~r"only lowercase letters, numbers and underscore", fn ->
Mix.Tasks.New.run ["invAlid"]
end
$ bin/elixir lib/mix/test/mix/tasks/new_test.exs
.......
1) test new with invalid args (Mix.Tasks.NewTest)
lib/mix/test/mix/tasks/new_test.exs:117
Expected exception Mix.Error but nothing was raised
stacktrace:
(elixir) lib/file.ex:1186: File.cd!/2
lib/mix/test/mix/tasks/new_test.exs:118: (test) …

Fix bug that allows upper case letters in app name

---

lib/mix/lib/mix/dep/converger.ex
lib/mix/test/fixtures/deps_cycle/app1/mix.exs
lib/mix/test/fixtures/deps_cycle/app2/mix.exs
lib/mix/test/mix/dep_test.exs

When Hex.RemoteConverger is called with circular dependency it tries to
flatten the graph and ends up in an infinite loop. This can be prevented
by running the topological sort before calling the remote converger.
Solves issue:
https://github.com/elixir-lang/elixir/issues/5487

Fix deps.get infinite loop on depedency cycles

---

lib/elixir/src/elixir_def.erl
lib/elixir/test/elixir/kernel/warning_test.exs

When functions are redefined in a different file, the translation uses
the first definition source location for all subsequent definitions.
This manifests itself as warnings that are ascribed to the wrong file.
Fixes https://github.com/elixir-lang/elixir/issues/5719

Fix redefined function source location

---

lib/elixir/lib/map.ex

Even the example for Map.put_new/3 asserts as true in the tests, the correct output is a map with sorted keys.

Fix map elements order in the example for Map.put_new/3

---

lib/mix/lib/mix/dep/converger.ex
lib/mix/lib/mix/dep/umbrella.ex

`topsort` should be renamed `top_sort` but I took the liberty to renamed it `topological_sort` for clarity

Rename Mix.Dep.Converger.topsort/1 to topological_sort/1

---

lib/logger/lib/logger/translator.ex
lib/logger/test/logger/translator_test.exs

@josevalim I am not sure if this is the best course of action. This will work, but we keep relying on internals a lot (`Inspect.Function.escape_name/1`). Maybe this is fine. An alternative solution, which I am not a fan of though, would be to do
```elixir
defp format_mfa(mod, fun, :undefined) do
Exception.format_mfa(mod, fun, 0) |> String.replace_suffix("/0", "/?")
end
```
Thoughts?

Correctly inspect functions with undef arity in Logger.Translator

---

lib/elixir/lib/kernel.ex

Alternatively, the note could be "Note that only integers can be `in` a range", what do you think ?
Also, thank you very much for the `not in` ❤️

Comment that the "in" operator on ranges succeeds only on integers

---

lib/iex/lib/iex.ex

Calling `respawn/0` as currently suggested in the 
docs raises a warning to remove the ambiguity.

Call respawn/0 using parentheses in the docs

---

lib/elixir/lib/enum.ex

Making clear how Enum.into/3 can be used with maps.

Added example to Enum.into/3

---

lib/iex/lib/iex/info.ex
lib/iex/test/iex/info_test.exs

There's an implementation for Date, Time and NaiveDateTime.
Implementation for DateTime is omitted since it doesn't define the Inspect
protocol.
Closes #5743

Implement IEx.Info protocol for calendar types

---

lib/mix/lib/mix/compilers/elixir.ex

For example, the callback was removed, and opts added, in 85f5269a, but
the function documentation wasn't updated to reflect those changes.

Revise @doc to reflect current compile/5 params

---

lib/elixir/lib/registry.ex

This will allow link on Hex.pm to work properly.

Fixed typo in Registry.start_link arity

---

lib/logger/lib/logger.ex

Resolves https://github.com/elixir-lang/elixir/issues/5754 although it's a closed issue I think calling out the `:format` option is a good idea.
My first elixir PR so I welcome all feedback.

Explain custom console formatters

---

lib/elixir/src/elixir_exp_clauses.erl
lib/elixir/src/elixir_try.erl
lib/elixir/test/elixir/kernel/expansion_test.exs
lib/elixir/test/elixir/kernel/raise_test.exs

We never officially supported this, but "accidentally" supported it because of how we implemented `rescue exception` (without `in`). With this commit, we move this step from expansion to `elixir_try`.

Drop support for "rescue exception in _"

---

lib/elixir/src/elixir_exp.erl
lib/elixir/src/elixir_translator.erl
lib/elixir/test/elixir/kernel/expansion_test.exs

I also had to adjust the check for `_ -> ...` clauses in `cond` because right now, it performs such check after expanding the clauses, but with the change in this commit then the `unbound variable _` error would fire first. With this commit, we check for `_ -> ...` clauses before expanding the clauses, which may not be ideal since the clauses could expand to `_ -> ...` but it's a compromise we're willing to make (after all, this error is just a friendlier error than `unbound variable _`, not a necessary one).

Check for "unbound variable _" in elixir_exp

---

lib/elixir/src/elixir_def.erl
lib/elixir/test/elixir/kernel/errors_test.exs

The code:
def f (x), do: x
was printing the function header definition error because it is parsed
to this:
def f((x), do: x)
So we made an additional description to the compilation error.
This commit fixes #5761

Improving the function header def args compilation error

---

lib/elixir/src/elixir_try.erl
lib/elixir/test/elixir/kernel/errors_test.exs
lib/elixir/test/elixir/kernel/expansion_test.exs

I also added tests for such errors in `Kernel.ExpansionTest`.

Remove some rescue-related errors from elixir_translator

---

lib/elixir/lib/file.ex
lib/elixir/test/elixir/file_test.exs

I have encountered multiple situations where I need to read a link rather than follow it. I think it should be available in Elixir.File rather than having to drop down to Erlang.

Add File.read_link/1 and File.read_link!/1

---

lib/elixir/pages/Guards.md

Explain the difference between multiple guard clauses and boolean expression
guards in case of failing expressions.

Enhance the guard guide

---

lib/elixir/lib/uri.ex
lib/elixir/test/elixir/uri_test.exs

It seems like current implementation miss the case when ref does not have `scheme`, but has `authority`
This PR is for fixing it

Fix bug in URI.merge

---

lib/elixir/test/elixir/kernel/errors_test.exs
lib/elixir/test/elixir/kernel/expansion_test.exs

I also added a few missing tests that cover errors that happen during expansion.

Move many expansion errors tests from errors_test to expansion_test

---

lib/elixir/src/elixir_expand.erl
lib/elixir/test/elixir/kernel/expansion_test.exs

The error for local calls in matches was showing the call, but the one for local calls in guards wasn't.

Make the error for local calls in matches/guards uniform

---

lib/elixir/src/elixir_clauses.erl
lib/elixir/test/elixir/kernel/expansion_test.exs

Before this, we raised one error if we passed a list with some non-clauses in it, and a different error if we passed a non-list.

Unify the error we raise when cond/case/etc don't receive clauses

---

lib/elixir/src/elixir_clauses.erl
lib/elixir/src/elixir_def.erl
lib/elixir/src/elixir_expand.erl
lib/elixir/src/elixir_with.erl
lib/elixir/test/elixir/kernel/errors_test.exs
lib/elixir/test/elixir/kernel/expansion_test.exs

These errors can now be formatted via either `elixir_expand:format_error/1` or
`elixir_clauses:format_error/1`.

Unify formatting of some common expansion errors

---

lib/elixir/lib/list.ex

This is basically just a rename of Erlang's `:lists.prefix/2`.

Add `List.starts_with?/2`

---

lib/elixir/lib/enum.ex

The documentation of `Enumerable.count/1` mentioned that its default implementation makes use of `===`, which is not the case and a bit confusing. The documentation was probably copied and adapted from `Enumerable.member?/2`, whose default implementation _does_ use `===`.

[trivial][docs] The default implementation of `Enumerable.count/1` does not use `===`

---

lib/elixir/lib/task/supervisor.ex
lib/elixir/test/elixir/task/supervisor_test.exs

Fixing issue #5801 by adding argument guard for `Task.Supervisor.start_child/3`.

Add argument guard for Task.Supervisor.start_child/3

---

lib/elixir/lib/calendar.ex
lib/elixir/lib/calendar/iso.ex

ISO 8601:
>  the decimal fraction shall be divided from the integer part by the decimal sign specified in ISO 31-0, i.e. the comma [,] or full stop [.]. Of these, the comma is the preferred sign.
This PR allows parsing ISO 8601 Time, NaiveDateTime, DateTime with commas.

Allow comma as the decimal sign for Time, NaiveDateTime, DateTime per ISO 8601

---

lib/elixir/lib/calendar.ex
lib/elixir/lib/calendar/iso.ex
lib/elixir/test/elixir/calendar_test.exs

This aligns the behavior with NaiveDateTime and prevents exception when
calling DateTime.to_iso8601. It will catch the common case of
interpreting timestamps with the wrong accuracy, i.e. using
DateTime.from_unix(ts) when ts is in microsecond accuracy.

Prevent creation of DateTime above year 10k

---

lib/elixir/lib/code.ex

This PR adds a warning to the `Code.eval_string` docs about the security consequences of evaling untrusted strings.
You might think that this is obvious or unnecessary, but I've been finding serious security bugs caused by running `eval_string` on untrusted input: https://github.com/tonini/alchemist-server/issues/14; https://github.com/msaraiva/atom-elixir/issues/67

Add a security warning to Code.eval_string

---

lib/elixir/lib/float.ex
lib/elixir/test/elixir/float_test.exs

In the case where precision is out of valid range, the default message is FunctionClause error.
With this commit an ArgumentError will be raised when precision is out of valid range.
This change aligns the behavior with Integer.parse, Float.parse that return ArgumentError on invalid input.

Improve Float ceil/round/floor error messages

---

lib/elixir/lib/file.ex

Fix dir? documentation

---

lib/elixir/lib/version.ex

Before this, I got an unhelpful error message:
```
iex> "1.0.0\n1.1.0\n" |> String.split("\n") |> Enum.map(&Version.parse!/1)
** (Version.InvalidVersionError)
```
now it's:
```
** (Version.InvalidVersionError) expected a valid version string, got: ""
```

Update InvalidVersionError & InvalidRequirementError messages

---

CHANGELOG.md
lib/mix/lib/mix/tasks/escript.build.ex
lib/mix/test/mix/tasks/escript_test.exs

This is a PR for #5688.  I went with `:strip_beam` because BEAM can work as a plural/collective noun, but I will change it to `:strip_beams` if you want.

Strip debug information from escripts by default and add option :strip_beam

---

lib/elixir/lib/list.ex
lib/elixir/test/elixir/list_test.exs

As discussed in the mailing list.
The function raises if `prefix` is an improper list.
Please let me know if that's the best way to detect an improper list.
I think it fits well, because we make use of the `length` results to avoid traversing and comparing elements unnecessarily.

Implement own version of List.starts_with?/2

---

Makefile
RELEASE.md
lib/elixir/pages/Deprecations.md

First draft.
I need your input where you see the __"???"__
let me know what you all think

Add Deprecations page

---

lib/elixir/lib/map_set.ex
lib/elixir/test/elixir/map_set_test.exs

I wanted a function to check if an object is a map set, so I added one!
iex(1)> MapSet.new() |> MapSet.map_set?()
true
While adding both ExUnit and DocTest tests, I did bump into an edge case.
iex(9)> maybe_map_set = %{__struct__: MapSet, map: %{a: false}}
#MapSet<[:a]>
iex(10)> maybe_map_set |> MapSet.map_set?
true
iex(11)> %MapSet{} = maybe_map_set
#MapSet<[:a]>
iex(12)> maybe_map_set |> Map.values
[MapSet, %{a: false}]

Add Add MapSet.map_set?/1 function

---

lib/mix/lib/mix/tasks/profile.cprof.ex
lib/mix/test/mix/tasks/profile.cprof_test.exs

As spoken in [the Elixir Core Mailing List](https://groups.google.com/forum/#!topic/elixir-lang-core/LeB8G1_CSQI) here's the proposed `Mix.Tasks.Profile.Cprof` to profile code using Erlang's `:cprof` and its tests. 
The logic was largely reused from `Mix.Tasks.Profile.Fprof`, but the functions are not shared (i.e., there are equal private functions in both tasks). 
I'd like some feedback on the Module parsing from the cmd args to actual atoms (the `parse_func_spec` function mainly). Some of this was done based on suggestions by @whatyouhide on Slack.
Thanks!

Add Mix.Tasks.Profile.Cprof and its tests

---

lib/mix/lib/mix/tasks/deps.compile.ex

Missing "to" in deps.compile task description.

Fix typo in mix deps.compile moduledoc

---

lib/elixir/lib/process.ex

Expands the documentation for `Process.sleep/1` with a sentence on suspended processes, as referenced in #5847.

Update documentation of the Process module

---

lib/mix/lib/mix/project.ex
lib/mix/lib/mix/tasks/compile.ex
lib/mix/lib/mix/tasks/new.ex
lib/mix/test/mix/task_test.exs
lib/mix/test/mix/tasks/app.start_test.exs
lib/mix/test/mix/umbrella_test.exs

Instead of:
```elixir
defmodule HelloWorld.Mixfile do
use Mix.Project
def project do
[app: :hello_world,
version: "0.1.0",
elixir: "~> 1.5-dev",
build_embedded: Mix.env == :prod,
start_permanent: Mix.env == :prod,
deps: deps()]
end
#
def application do
[extra_applications: [:logger]]
end
#
#
#
#
defp deps do
[]
end
end
```
we propose:
```elixir
defmodule HelloWorld.Mixfile do
use Mix.Project
def project do
[
app: :hello_world,
version: "0.1.0",
elixir: "~> 1.5-dev",
start_permanent: Mix.env == :prod,
deps: deps()
]
end
def application do
[
extra_applications: [:logger]
]
end
defp deps do
[
]
end
end
```
The changes are:
* Use new line after `[` and `]` for multi-line constructs for easier manipulation. If accepted, this will be a new rule throughout the Elixir codebase (but please do no …

Propose new styling for generated applications

---

lib/elixir/lib/integer.ex

* Use single binary match context
* Do minimal pattern matches and maths

Optimise integer parsing

---

lib/elixir/lib/enum.ex

`Enum.reduce` will emit the result of the previous function as the accumulator for the next item. This point didn't seem very evident to me when I was looking up the `Enum.reduce` related documentation [here](https://hexdocs.pm/elixir/Enum.html#reduce/2). This PR is an attempt to make this more clearer for anyone who wants to better understand how `Enum.reduce` works through each iteration.
Thanks to @josevalim for the wonderful explanation wrt the usage of `Enum.reduce` as part of [this stackoverflow question](http://stackoverflow.com/questions/29924170/elixir-looping-through-and-adding-to-map). It helped me better understand how `Enum.reduce` actually works.

Add more clarity on how reduce works through each iteration

---

lib/elixir/lib/option_parser.ex

This commit also mark `OptionParser.get_option_key/2` as private,
this function is not documented and it seems that is only used internally.

OptionParser: Reduce number of params in functions

---

lib/elixir/lib/enum.ex

The docs weren't quite correct, the binary convertibility of the
enumerable does not come into play in this function, only the result
of the `mapper` function call on each element of the enumerable.

Minor fixup of Enum.map_join/3 docs.

---

lib/elixir/lib/calendar.ex
lib/elixir/test/elixir/calendar_test.exs

fixes #5864:
-  `NaiveDateTime.to_iso8601/1`  will raise a descriptive ArgumentError when a NaiveDateTimes that follow a non-Calendar.ISO calendar is passed to it.
- A test to ensure that this indeed works as intended.
- (Tests for the happy path where a NDT that has Calendar.ISO are not added, as the doctests of `NaiveDateTime.to_iso8601/1` already cover this).

Ensures NaiveDateTime.to_iso8601/1 raises for non-Calendar.ISO structs.

---

lib/elixir/lib/uri.ex

Fixes missing words removed in https://github.com/elixir-lang/elixir/commit/b191f6bf1f767f93c752370a851f45549a8d6b45

Add missing word in URI module doc

---

lib/elixir/lib/kernel/typespec.ex
lib/elixir/pages/Typespecs.md
lib/elixir/src/elixir.erl
lib/elixir/test/elixir/kernel/typespec_test.exs

I think this is the only built-in type that we've been missing.

Add nonempty_charlist/0 built-in type

---

lib/elixir/lib/string.ex

Clarify the difference between ```String.to_float/1``` and
```Float.parse/1```

Reword String.to_float documentation

---

lib/logger/lib/logger.ex
lib/logger/lib/logger/backends/console.ex
lib/logger/test/logger/backends/console_test.exs

Hi José and friends!
As discussed on [elixir-lang-core](https://groups.google.com/d/msg/elixir-lang-core/CjVhZj0j7kk/m5bqZ3qfAwAJ) this pull-request adds a `:all` option to the `metadata` configuration option for `Logger.Backends.Console`.
In addition I added a test that verifies that you can configure the `format` option with a `{module, :func}` format.
I want to mention that I had some trouble running the tests. Unless I did a forced compile before running the tests I got random failing tests so I ended up running my tests using:
```
MIX_ENV=test mix do compile --force, test -- test/logger/backends/console_test.exs
```
Best regards
Simon Boisen
CTO, Lix Technologies

Add metadata: :all option to Logger.Backends.Console

---

lib/elixir/lib/process.ex

I always forget the shape of the monitor message, and find it extremely frustrating it's not there, when I try to look it up in the docs.

Improve docs of Process.monitor/1

---

lib/elixir/src/elixir_tokenizer.erl
lib/elixir/test/erlang/tokenizer_test.erl

Changes the error message to be
```Elixir
Interactive Elixir (1.5.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 1.0e310
** (SyntaxError) iex:1: float number out of range 1.0e310
```
Instead of 
```Elixir
Interactive Elixir (1.4.2) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> 1.0e310           
:erlang.list_to_float('1.0e310')
(elixir) src/elixir_tokenizer.erl:765: :elixir_tokenizer.tokenize_number/4
(elixir) src/elixir_tokenizer.erl:423: :elixir_tokenizer.tokenize/5
```

Add float overflow error message to Tokenizer

---

lib/elixir/lib/kernel.ex
lib/elixir/lib/kernel/utils.ex

When default arguements (`\\`) are used with `defdelegate/2`, a function is generated for each default argument and each generated function calls the delegate target function with the same arity. For example:
```elixir
defdelegate demonitor(monitor_ref, options \\ []), to: :erlang
```
will be expanded to
```elixir
def demonitor(monitor_ref), do: :erlang.demonitor(monitor_ref)
def demonitor(monitor_ref, options), do: :erlang.demonitor(monitor_ref, options)
```
However, this seems to "break" the expectation that optional arguments set: when a function has optional arguments, all the additional functions with lower arity that are generated by the default arguments only call the function with maximum arity with the default values provided for the optional arguments.
This means that if …

Fix the behaviour of defdelegate/2 with default arguments

---

lib/logger/test/logger/backends/console_test.exs

Prevents compiler warnings when running tests

Underscore unused variables in test suite

---

lib/elixir/lib/map.ex
lib/elixir/test/elixir/map_test.exs

This produces order of magnitude improvement on the best case, where source map is empty.
You can see benchmark [script](https://github.com/tsubery/misc_bench/pull/1) and results on [travis](https://travis-ci.org/tsubery/misc_bench/builds/212359883).

Optimize Map.merge/3 by choosing merge direction

---

lib/ex_unit/lib/ex_unit/callbacks.ex
lib/ex_unit/test/ex_unit/callbacks_test.exs

Closes #5898.
Since 58377cd, `ExUnit.Callbacks.__merge/3` is a recursive function which drops the `:ok` atom from the passed value if the value is an ok-tuple. This caused potential errors raised by `raise_merge_failed!/2` to show only part of the passed value in the error message.
Returning `{:ok, "foo"}` from a setup block produced an error like this:
** (RuntimeError) expected [...] got \"foo\" instead
This patch adds `ExUnit.Callbacks.__merge/4`, which is called by `__merge__/3` with adds the original value as the fourth argument, to be able to display the full value:
** (RuntimeError) expected [...] got {:ok, \"foo\"} instead

Add original values to context merging in ExUnit

---

lib/ex_unit/lib/ex_unit/callbacks.ex
lib/ex_unit/test/ex_unit/callbacks_test.exs

While working on #5901, I found that the wrong value was passed to `ExUnit.Callbacks.raise_merge_reserved!/3`, which caused the current value to be used in the error message instead of the one passed in the context. With a setup block like this:
setup do
{:ok, file: "foo"}
end
The error message uses the current `:file` value (the path to the test file) instead of the passed one ("foo"):
** (RuntimeError) ExUnit callback in MyAppTest is trying to set reserved field :file to "/path/to/test/my_app_test.exs"
This one-character patch uses the passed value instead, resulting in an error message like this:
** (RuntimeError) ExUnit callback in MyAppTest is trying to set reserved field :file to "foo"

Use passed value for raise_merge_reserved!/3

---

lib/elixir/lib/enum.ex
lib/elixir/lib/stream.ex

Because scan/2 and scan/3 examples had similar input and output, readers could mistake
the default value to be 0. The new code clarifies that.
p.s. Why don't we implement scan/2 by taking first the value and calling scan/3?

Clarify starting value in scan/2 documentation

---

lib/elixir/src/elixir_expand.erl
lib/elixir/test/elixir/kernel/expansion_test.exs

This change raises error when invalid keys are give to "for" loops and
prevents silent errors.

Validate options for comprehension

---

lib/elixir/lib/enum.ex

* Avoid do_ names in enum implementation
* Refactor enum list functions to body-recursive where sensible
The reasoning is the same as in #3811 and 99e0d8e

Enum refactoring

---

lib/mix/lib/mix/local/installer.ex
lib/mix/lib/mix/tasks/archive.install.ex
lib/mix/test/mix/tasks/archive_test.exs

This allows to ignore file naming convention and install correctly even if file name is changed.
Solves https://github.com/elixir-lang/elixir/issues/5882

Mix archive.install parse file before installing

---

lib/elixir/lib/agent.ex

`GenServer.stop/3` is available and it calls `:gen.stop/3` anyways, but at least this way we consistently call out to the `GenServer` module :)

Use GenServer.stop/3 instead of :gen.stop/3 in Agent.stop/3

---

lib/elixir/lib/exception.ex
lib/elixir/lib/keyword.ex
lib/elixir/lib/map.ex

Culmination of [this discussion on the Elixir Forum](https://elixirforum.com/t/updating-structs-map-put-vs-foo-oldfoo-new-value-vs-put-in/4246?u=qqwy).
~~This Pull Request adds the following:~~
- `Map.put_new!/3` which raises a `KeyExistsError` if the key that should be inserted already exists.
- `Map.put_existing/3` which only puts a value in the given map if the key already existed.
- `Map.put_existing!/3` which only puts a value in the given map if the key already existed, and raises a `KeyError` if it did not.
- `Keyword.put_new!/3` which raises a `KeyExistsError` if the key that should be inserted already exists.
- `Keyword.put_existing/3` which only puts a value in the given keyword list if the key already existed.
- `Keyword.put_existing!/3` which only puts a value in the given …

{Map, Keyword}.replace/3 and replace!/3

---

lib/elixir/lib/module.ex
lib/elixir/test/elixir/module_test.exs

There are plenty of changes, that's why the [WIP], but it all guards and typespecs are complete for this module.
There is a common argument which is the `{<function/macro atom>, <arity>}` tuple,
and it make me think whether we need to create a new `type` for this.

Complete typespecs and guards for Module module

---

lib/elixir/lib/map.ex

* add missing "Inlined by the compiler." notifications
* internally inline the replace!/3 function delegating to the BIF
* make compiler inline Map.replace!/3 to :maps.update/3

Properly inline map functions

---

lib/elixir/lib/integer.ex
lib/elixir/src/elixir_dispatch.erl
lib/elixir/test/elixir/integer_test.exs

A regression was introduced in 9c0d6a that removed `Integer.to_char_list/2`, while it should have been hard-deprecated (in favour of `.to_charlist/2`) to be eventually removed in 2.0.
** (UndefinedFunctionError) function Integer.to_char_list/2 is undefined or private. Did you mean one of:
* to_char_list/1
This patch adds `Integer.to_char_list/2` back, which calls `Integer.to_charlist/2` and is deprectated in dispatch, so it produces a deprecation warning (instead of an UndefinedFunctionError) when called:
warning: Integer.to_char_list/2 is deprecated, use Integer.to_charlist/2
⚠️ I've added tests for both [`Integer.to_char_list/1`](https://github.com/jeffkreeftmeijer/elixir/blob/e37751ce1230075aae808bcb12dd2f0ac7a22eef/lib/elixir/test/elixir/integer_test.exs#L208-L210) and …

Restore (deprecated) Integer.to_char_list/2

---

lib/elixir/lib/calendar/iso.ex

warning: unused import Integer
lib/calendar/iso.ex:28
Introduced in d017c5ab1222fef2f114f327767c33c9310f7b52
/cc @Qqwy

Remove unused import in Calendar.ISO

---

lib/logger/lib/logger.ex

Just a missing comma in the documentation of `Logger`.

Add missing comma

---

lib/elixir/lib/record.ex

Previously the tag name is the same name as the module the records is defined in,
so it may not be clear.

Be clearer explaining how to create a record with a customized tag

---

lib/mix/lib/mix/tasks/new.ex

Saw the sentence
> You can configure for your application as:
Since I was on it, I believe the connection with the next line naturally flows as a single sentence, because a displayed code snippet is not a paragraph separator necessarily.
Then we can still start with uppercase the third one, reads well because it separates a "my app config" block from "3rd-party config".

Revises grammar in Mix.Config config template [ci skip]

---

lib/ex_unit/lib/ex_unit/assertions.ex

Assertion macro generated a case statement that can have patterns that
cannot match. For example:
```Elixir
test "warning" do
assert a = %{a: 1}[:a]
a #don't complain about unused var
end
```
Would generate the following output
```Bash
warning: this clause cannot match because a previous clause at line 7
always matches
```

Fix warning when asserting a pattern that always match

---

lib/elixir/lib/calendar.ex
lib/elixir/lib/calendar/iso.ex
lib/elixir/lib/integer.ex

- Uses a coherent and more efficient implementation for the difference functions that only converts to `System.time_unit` after the difference has been calculated using rata die / day fractions.
- Fixes a bug in the current implementation of `DateTime.diff`.
Fixes #5920.

Improve {(Naive)DateTime, Date, Time}.diff/2

---

lib/elixir/lib/integer.ex

The description of `Integer.gcd`
> This is the largest positive integer that divides both `int1` and `int2` without leaving a remainder.
does not cover the edge case where both arguments are 0, because 0 divides no integer (and oftentimes 0 is not considered to be a positive number either, but that is a minor nuance).
The examples section does have a call that demonstrates the behaviour, but I guess users will be less surprised if the description is complete explaining the edge case, and explaining why does it return precisely 0.
This is a convention in its mathematical definition, it could return 7 for that matter, but it is convenient/practical to be defined as 0.
You can double-check this rationale in [Wolfram Alpha](https://www.wolframalpha.com/input/?i=gcd(0,0)) for example (click on …

Document the edge case Integer.gcd(0, 0)

---

lib/elixir/lib/integer.ex
lib/elixir/test/elixir/integer_test.exs

The current examples for `Integer.gcd/2` have some redundancy, and the function itself has no test suite.
This patch selects some examples just for illustration purposes:
* There is one with coprime numbers.
* There is one where GCD is not 1.
* There is one with negative numbers.
* A couple involving 0s.
Then, the test suite has more stuff.

Adds a test suite for Integer.gcd/2

---

lib/elixir/lib/gen_server.ex

Minor documentation edits around `GenServer.whereis/1`.

Improve doc for GenServer.whereis/1

---

lib/ex_unit/lib/ex_unit/diff.ex
lib/ex_unit/test/ex_unit/diff_test.exs

All of 
```elixir
assert %{nil => 42} == %{}
assert %{true => 42} == %{}
assert %{false => 42} == %{}
```
resulted in a `MatchError`, instead of proper diffs.

Fix ExUnit.Diff when comparing maps with nil or boolean keys

---

.gitignore

In the beginning of times Elixir used [`leex`](http://erlang.org/doc/man/leex.html), a tokenizer generator that took as input the .xrl file removed in 2f1f1393c9b6055114eee438e5444e010241a37e.
The Erlang scanner was introduced in 2b48933b9320b8a566c2d8aeaea41174d2b1569d.

Removes .gitignore pattern for generated lexer [ci skip]

---

lib/elixir/lib/file.ex

The font used in the rendered docs does not differentiate `0` and `o`
very well. Put the flags in inline code blocks so that they use a
monospace font that's more unambiguous.
Also, add a short sentence stating that the flags are octal.

Make it more clear that file permissions are octal

---

lib/elixir/lib/kernel/special_forms.ex

Title says it all.
I assumed in the first paragraph that invoking an anonymous function is not a "remote call", but I am not 100% sure about the terminology here. If that is incorrect I'll revise :).

Cover calls to anonymous functions in `:.` docs [ci skip]

---

lib/elixir/lib/kernel/special_forms.ex

@whatyouhide I realized there was a second example using `neg`, I believe it makes sense to use `negate` again, for coherence with the previous definition (though technically they are different examples).
What do you think?

Use `negate` instead of `neg` for coherence

---

lib/elixir/lib/record.ex

"atom" could be either the "name" or "tag" of a record.

Rename ambiguous "atom" argument to "tag" in Record module functions

---

lib/elixir/lib/protocol.ex

Easy one.
This function is for structs, when read on itself, `struct` may communicate that better than `other`.

Parameter rename in Protocol.each_struct_clause_for/3

---

lib/mix/lib/mix/cli.ex

PATH is a requirement when running `mix new`

Correct "mix new" command message in Mix.CLI

---

lib/elixir/lib/kernel.ex
lib/elixir/test/elixir/kernel_test.exs

Previously the error message would referer to a private function, as in:
iex> pop_in([1, 2, 3], 3)
** (FunctionClauseError) no function clause matching in Kernel.do_pop_in/2
(elixir) lib/kernel.ex:1979: Kernel.do_pop_in([1, 2, 3], 3)
now it will metion the public_function:
iex> pop_in([1, 2, 3], 3)
** (FunctionClauseError) no function clause matching in Kernel.pop_in/2
(elixir) lib/kernel.ex:1976: Kernel.pop_in([1, 2, 3], 3)

Improve guards in Kernel.pop_in/2

---

.gitignore
Makefile
lib/mix/test/fixtures/.gitignore

This commits creates new clean targets.
It removes all the files in the .gitignore file.
It also deals with situations where `make test` was interrumpted, leaving files that are neither gonna be ignored by .gitignore nor gonna be removed by `make clean`.

Create "clean_residual_files" target in Makefile

---

lib/elixir/lib/file.ex

I unintentionally deleted some symlinks because I assumed `File.regular?` would return `false` for them, but it does not.
This PR mentions documents the behavior with symlinks.

Mention that File.regular? and File.dir? follow symbolic links

---

lib/mix/lib/mix/local/installer.ex

Othewise it outputs
Found existing archive: /home/eksperimental/.mix/archives/hex-0.14.0.
Changing the name of the file.

Remove the trailing period in installer message

---

lib/elixir/test/elixir/kernel_test.exs

It will warn:
> warning: this expression will fail with ArgumentError
Recently introduced in
980a73cc7ff2e5ba522c9d0ac166043f4a97c7c6
f523b485d04624e8d757ff0ae7d97fdd97be5ce9

Avoid warnings in hd/1 and tl/1 tests

---

lib/elixir/lib/protocol.ex
lib/elixir/test/elixir/protocol_test.exs
lib/mix/lib/mix/compilers/elixir.ex

- Changed from @impl to @__implements_protocols_for
- Required because we want to repurpose @impl - see #5734

Change module attribute name that stores internal protocol metadata

---

lib/mix/lib/mix/tasks/archive.install.ex

Checksum checking cannot be performed on archives being installed
from git/github/hex. This change makes a note of that, using the
same wording from [`escript.install.ex`](https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/escript.install.ex#L42)

Update the documentation for `archive.install`

---

lib/elixir/lib/kernel.ex

I tried to make consistent:
* `left` and `right` as argument names for binary operators (`min/2` and `max/2` were using `first` and `second` for example)
* renamed contrived variable names to more readable ones (`attrs` -> `attributes`, `msg` -> `message`)
* `value` as the name of the argument for unary operator
* `term` as the argument for generic one-argument functions

Improve variable naming in Kernel functions

---

lib/elixir/lib/calendar.ex
lib/elixir/lib/calendar/iso.ex

Currently, Elixir supports the `extended` format for iso_8601 conversion. This format is good for human readability, but there is also basic format, which omits separator characters, which is often use for machine-machine messages (for example timestamps in http headers).  Its easy enough to strip out the separators in a handrolled fashion, but it seems like the language should just support `basic` directly in addition to the already supported `extended` format.
[This document](https://support.sas.com/documentation/cdl/en/lrdict/64316/HTML/default/viewer.htm#a003169814.htm) gives a fairly comprehensive overview of the differences b/w extended and basic (essentially adding or omitting ':' in times and '-' in dates). I would also cite the official ISO 8601 documents but these appear to be …

Calendar: add support for ISO8601 basic format

---

bin/elixir

Double-equals is a Bash-specific alias for "=" and it doesn't work everywhere. We use single-equal in the rest of the script anyways.

Use single-equals when comparing variables in bin/elixir

---

CHANGELOG.md

For some reason, Github wasn't rendering one of the `*` as a bullet point.  Deleting and rewriting the spaces seems to have fixed it.

Fix formatting issue in CHANGELOG.md

---

lib/elixir/lib/module.ex
lib/elixir/test/elixir/kernel/errors_test.exs

I think this could be a way to implement this check:
> `{bad_on_load,Term}`: badly formed `on_load` attribute
from https://github.com/elixir-lang/elixir/issues/5800. Thoughts?

Validate the value of the @on_load attribute

---

lib/elixir/lib/kernel.ex

While writing this, I noticed that the use of `def` to declare function heads isn't documented, at least for `Kernel.def/2`. I could address that here or open a separate PR.
Closes #6024.

Document default argument operator (`\\`)

---

lib/elixir/lib/kernel/special_forms.ex

I think from a programmer's perspective, the fact that in order to expand macros the compiler needs to ensure the module is compiled and loaded is not relevant.
The compiler needs the module loaded in memory to have their functions available (a macro is a function prefixed with "MACRO-"), because it may need to call the function early in the expand phase. Note that the module may be loaded in memory when expansion happens:
```elixir
Integer.digits(1) # function
defmodule M do
Integer.is_odd(1) # macro
end
```
by the time `is_odd` has to be expanded, `Elixir.Integer` is already loaded in the VM, and thus the macro available for dispatch. But Elixir errs, because the code does not opt-in. Since Elixir knows the macro exists, it gives you a better error message ("you need to require in order …

Changes focus in require explanation

---

lib/elixir/lib/task.ex
lib/elixir/lib/task/supervised.ex
lib/elixir/test/elixir/task_test.exs

`:on_timeout` can be `:kill_task | :exit`, where `:exit` is the current behaviour.

Support :on_timeout in Task.async_stream and friends

---

lib/elixir/lib/integer.ex

Improves readability by being more concise ~~and avoiding meta-programming~~. It also improves performance beyond the already fast implementation from #5859.
Some numbers from executing [the benchmark](https://github.com/elixir-lang/elixir/pull/5859#issuecomment-285681896) from #5859 on my Macbook Pro (Mac OS 10.12.4, Erlang 19.3):
```
elixir 1.4.2: 8197µs
current master (3e56f6d32): 410µs
this pull-request: 149µs
```
/cc @fishcakez

Integer.parse/2 simpler and faster

---

lib/ex_unit/lib/ex_unit/cli_formatter.ex
lib/ex_unit/lib/ex_unit/runner_stats.ex

Addresses #5967 
- Handle `setup_all` failures as the failure of all test in the case for `RunnerStats` and `CliFormatter` WRT `test_counter` and `failure_counter`

Fix: ExUnit Setup_all fails with 0 exit status (#5967)

---

lib/mix/lib/mix/tasks/escript.build.ex

Some applications can rely on attributes, so silently stripping them
when building escript can be confusing.
If we still want to strip other debug module information by default,
we have to preserve attributes explicitely.

Preserve attributes even if `strip_beam` is enabled

---

lib/elixir/lib/hash_dict.ex
lib/elixir/lib/hash_set.ex

Similar to what was done in 73ae8ed2856f3d324a8f3b044e7d43bce130db4f for `Dict`.

Silence compilation warnings about the deprecation of HashDict/HashSet

---

lib/elixir/lib/map_set.ex

MapSet is internally represented as a map with keys as set's elements and stub values of `true`, like: `%{ :key => true }`.  When MapSet, in it's current format, is written to a DETS file, or serialized using `:erlang.term_to_binary/2`, it's **two times** as big as the smallest possible case! If the stub value is replaced with an empty list, to a format `%{ :key => [] }`, there is a significant space reduction, see: 
```Elixir
iex(1)> ml = for i<- 1..1_000_000, do: {i,[]}, into: %{}; :ok
:ok
iex(2)> mt = for i<- 1..1_000_000, do: {i,true}, into: %{}; :ok
:ok
iex(3)> {:ok, table_ml} = :dets.open_file(:disk_storage_ml, [type: :duplicate_bag]) 
{:ok, :disk_storage_ml}
iex(4)> {:ok, table_mt} = :dets.open_file(:disk_storage_mt, [type: :duplicate_bag])
{:ok, :disk_storage_mt}
iex(5)> size_ml = …
```

Reduce MapSet's space usage in Erlang term format

---

lib/elixir/lib/dict.ex

This warning is emitted in elixir_dispatch anyways, this currently results in
two warnings emitted for the same `use Dict` in `HashDict`.

Remove custom warning on "use Dict"

---

lib/elixir/lib/integer.ex

Separate extracting the sign from the rest of the pass.
This allows drastically limiting the number of generated cases and
reduces the complexity of the code, speeding it up at the same time.

Simplify integer parsing

---

lib/elixir/src/elixir_expand.erl
lib/elixir/test/elixir/kernel/expansion_test.exs

I was working with import/2 in a macro, and it was not easy to see what was wrong. I hope this helps

Show invalid option in error message when invalid options are expanded

---

.gitignore

1) /.release
Removed long time ago in these two commits.
commit 8ced611aee30a30ed6728a9ef32c0d7094f3a262
Author: José Valim <jose.valim@plataformatec.com.br>
Date:   Thu Jan 24 08:05:01 2013 -0700
We no longer have a .release task
commit 85fca3de2ecc36436e655db6afa0acf9bfa51f43
Author: José Valim <jose.valim@plataformatec.com.br>
Date:   Wed Jan 23 13:53:09 2013 -0700
Properly declare .PHONY targets
2) /rel/elixir
Removed in this commit.
commit d44e8bd1f6efc54e664c28fdfc864af37e7e3129
Author: José Valim <jose.valim@plataformatec.com.br>
Date:   Tue Feb 11 10:24:27 2014 +0100
Remove release files
3) /ebin
Previously used with rebar2

Remove unused ignored entries in .gitignore

---

lib/elixir/lib/record.ex
lib/elixir/test/elixir/record_test.exs

Should close https://github.com/elixir-lang/elixir/issues/6060.

Properly escape fields passed to defrecord

---

lib/elixir/lib/gen_event/stream.ex

This suppresses the deprecation warning. Functionality should be equivalent, but please double check :)

Replace GenEvent.remove_handler/3 with :gen_event in GenEvent.Stream

---

lib/ex_unit/test/ex_unit/doc_test_test.exs

It was really confusing that a min function returns a max value
This is a WIP, as I want the approval first to remove the `:skip` tag in "doctest failures" test and correct the test, as it's a pain in the neck to change the line numbers

Improve test for no import options in DocTest tests

---

lib/elixir/src/elixir_errors.erl

It's possible get_stacktrace won't work outside of catch clauses in the future.
Reference: https://github.com/erlang/otp/pull/1449

Clean up usage of get_stracktrace in elixir_errors.erl

---

lib/ex_unit/test/ex_unit/doc_test_test.exs

Additionally be clearer on when the return value is wrong.

Use explicit function names in DocTest tests

---

lib/logger/lib/logger.ex

I added `:pid` to the list of Logger metadata, and was surprised to find that it worked even without doing `Logger.metadata [pid: self(), ...]`, though it isn't mentioned in the docs list of builtins. This adds it to the docs in case it was omitted by mistake.

Documentation: add :pid to list of Logger metadata builtins

---

lib/elixir/pages/Operators.md

Changed "While it's possible to **defined**" to "While it's possible to **define**".

Fix typo in operators docs

---

lib/elixir/lib/version.ex

Rebuilding the `build` part in `Version.parse/1` may not be the absolute best, but we were basically parsing out the build in `Version.Parser.parse_version/1` only to throw it out and not use it anywhere, and then parsing the build again (with a regex) in `Version.parse/1`. This way, we get rid of the regex and simplify the code a bit.

Refactor Version.parse/1 to not use regexes

---

lib/mix/lib/mix/dep.ex
lib/mix/lib/mix/hex.ex
lib/mix/lib/mix/local/installer.ex
lib/mix/lib/mix/tasks/deps.compile.ex
lib/mix/lib/mix/tasks/iex.ex
lib/mix/lib/mix/tasks/local.rebar.ex
lib/mix/lib/mix/tasks/xref.ex
lib/mix/test/mix/tasks/deps.git_test.exs
lib/mix/test/mix/tasks/deps_test.exs
lib/mix/test/mix/tasks/iex_test.exs
lib/mix/test/mix/tasks/xref_test.exs

It tries to avoid the use of different styles such as:
- inline commands sentence with user of double-quotes (ie. Invalid arguments, please run "mix something" for more information)
- inline commands in sentence with use of semi-colon (ie. Invalid arguments, please run: mix something)
Suggested commands go in a new line, indented with 4
white-spaces.
Error messages follow the following format:
```
** (Mix) Invalid arguments given to "mix local.rebar"
Check the proper call syntax with:
mix help local.rebar
```

Standardize messages that suggest to run a command-line command

---

lib/iex/test/iex/helpers_test.exs

Test was broken in this PR: https://github.com/elixir-lang/elixir/pull/6095

Fix test failing introduced in 6a2cfef

---

lib/elixir/lib/task/supervisor.ex

The items in the `enumerable` are prepended to the `args`

items in the enumerable are prepended to the args

---

lib/elixir/src/elixir_map.erl
lib/elixir/test/elixir/kernel/warning_test.exs
lib/elixir/test/elixir/map_test.exs

Until now, `%x{__struct__: y}` would ignore the `:__struct__` part and only use/match on `x`, without warnings. With this commit, a warning is emitted in this case and in the respective case when updating (`%SomeStruct{x | __struct__: y}`).

Warn when a :__struct__ key is used when building/updating structs

---

lib/elixir/lib/string_io.ex
lib/elixir/test/elixir/string_io_test.exs

This pull request currently consists of 3 separate commits:
1. bf28be6243392a5c40367d329fa7ed233e257a2b Adds test coverage to the existing implementation.
2. 2a475a6a8d1e80b1c8790915b0d08a3eb4357429 Fixes #6037, the performance/scalability problem.
3. c7e821394841c3eda7743f37933a60d501675125 Fixes a bug. `IO.binread` should return raw bytes instead of decoding the input as if it were Latin1. See [this comment](https://github.com/elixir-lang/elixir/issues/6037#issuecomment-298233279).
I can split the last item into a separate pull-request if desired.
Using [this benchmark](https://gist.github.com/balexand/629e37f97865ce404f002199c3b406cd), each `IO.read(pid, :line)` call takes:
```
Before: 2557µs when N=5,000 O(N)
After: 14µs O(1)
```
`StringIO.get_until` suffers from the same performance …

StringIO read_line performance and binread bug fix

---

lib/elixir/src/elixir_dispatch.erl
lib/elixir/src/elixir_map.erl
lib/elixir/src/elixir_module.erl
lib/iex/lib/iex/evaluator.ex

If any of the functions catches an error, we'd get a wrong trace

Make sure System.stracktrace is first thing done in the handler

---

lib/ex_unit/lib/ex_unit/capture_log.ex

Without `require Logger`, the following won't compile...
```
defmodule AssertionTest do
import ExUnit.CaptureLog
test "example" do
assert capture_log(fn ->
Logger.error "log msg"
end) =~ "log msg"
end
test "check multiple captures concurrently" do
fun = fn ->
for msg <- ["hello", "hi"] do
assert capture_log(fn -> Logger.error msg end) =~ msg
end
Logger.debug "testing"
end
assert capture_log(fun) =~ "hello"
assert capture_log(fun) =~ "testing"
end
end
```
```
$ mix test
Compiling 1 file (.ex)
== Compilation error on file lib/lsidjflsjdf.ex ==
** (RuntimeError) cannot use ExUnit.Case without starting the ExUnit application, please call ExUnit.start() or explicitly start the :ex_unit app
expanding macro: ExUnit.Case.__using__/1
lib/lsidjflsjdf.ex:2: AssertionTest (module) …
```

Add missing 'require Logger' in ExUnit.CaptureLog doc example

---

lib/eex/lib/eex/engine.ex

Whenever EEx templates are used to pass variables via `assigns` whatever
this data structure is will be passed into `EEx.Engine.fetch_assign` and
then into `Access.fetch`.
So it makes sense to use the same typespec for the both. Otherwise
dialyzer will complain about every instance where keyword lists are
passed into functions like `eval_string`, `function_from_file` and
`function_from_string`.

Streamline typespec of EEx.Engine.fetch_assign! and Access.fetch

---

lib/elixir/lib/string.ex
lib/elixir/test/elixir/string_test.exs

Hi Maintainers,
New to this community, I'm hoping to improve my understanding of Elixir by working on some issues.
This PR should address the issue raised in #6108, but also breaks the usecase for users that rely on `String.valid?` to check for non-characters...

Consider unicode non-characters as valid (#6108)

---

lib/elixir/src/elixir_tokenizer.erl
lib/elixir/test/erlang/tokenizer_test.erl

Before this PR, we would have:
```elixir
iex> ~s\
** (SyntaxError) iex:1: unexpected token: "~" (column 1, codepoint U+007E)
```
After this commit, we have:
```elixir
iex> ~s\
** (SyntaxError) iex:1: invalid sigil delimiter: "\" (column 3, codepoint U+005C)
```
I'm not sure if we should point to some kind of documentation, or if we should list the possible delimiters, input is welcome.
Closes #6132.

Give a proper syntax error when invalid sigil delimiters are used

---

lib/elixir/lib/inspect.ex
lib/elixir/lib/inspect/algebra.ex
lib/elixir/lib/string.ex
lib/elixir/test/elixir/inspect_test.exs
lib/iex/test/iex/autocomplete_test.exs

provide inspect opts printable_limit to avoid performance issues found when inspecting large printable strings
Fixes https://github.com/elixir-lang/elixir/issues/5817

Inspect Opts Printable String Limit

---

CHANGELOG.md

This makes both documents upto date

Update CHANGELOG and Deprecations with v1.5 changes

---

CHANGELOG.md

This was introduced in
https://github.com/elixir-lang/elixir/pull/5804
due to creating a patch via web interface
Fixes same issue as: https://github.com/elixir-lang/elixir/pull/6032

Replace no-break space in CHANGELOG

---

lib/iex/lib/iex/info.ex
lib/iex/test/iex/helpers_test.exs

:"do not show this result in output" is the returned value of functions
that print to screen and do not want to show in screen any returned value.
This commits prints the information about `nil` instead.

Show specific description for dont_display_result atom in i/1 helper

---

lib/elixir/lib/enum.ex

I had difficulty understanding what sort of function should actually be passed to the second parameter of `Enum.uniq_by/2`. I believe that this helps to clarify it.

Enum: clarify uniq_by function parameter

---

lib/mix/lib/mix/tasks/new.ex
lib/mix/test/mix/tasks/new_test.exs

The motivation for this change is that we would want the developers to be either consciously testing or not the code.
This change would push you towards this goal by giving you a red build whenever you changed the code for the first time, leading you to explicitly make the decision of fixing your tests to align with the changes you introduced to the code, or consciously decide to remove them.

Make test created by `mix new` actually test your code

---

lib/elixir/lib/gen_server.ex
lib/elixir/test/elixir/gen_server_test.exs

I think this would improve the message seen when you pass invalid value for name option. I got confused for a moment with this so I thought this would improve readability.
With something like:
```elixir
defmodule A do
use GenServer
end
```
Current behavior:
```elixir
GenServer.start(A, [], name: "hello")
** (ArgumentError) expected :name option to be one of:
* nil
* atom
* {:global, term}
* {:via, module, term}
Got: {"hello", []}
(elixir) lib/gen_server.ex:674: GenServer.do_start/4
```
Behavior with this PR:
```elixir
GenServer.start(A, [], name: "hello")
** (ArgumentError) expected :name option to be one of:
* nil
* atom
* {:global, term}
* {:via, module, term}
Got: "hello"
(elixir) lib/gen_server.ex:681: GenServer.do_start/4
```

Fix value inspect for name option

---

lib/mix/lib/mix/tasks/local.hex.ex

I noticed there was a typo in the docs for `mix local.hex --if-missing` and that the sentence was a little confusing as written, so I tried to clarify it.

Mix.Tasks.Local.Hex: Clarify --if-missing docs

---

bin/iex.bat

Incorporate commit 82b655a from bin/iex into bin/iex.bat
Original comment:
"Do not start oldshell alongside IEx, closes #5730
Prior to this patch, both oldshell and IEx would start,
which would make them compete for the standard io. This
could be deterministically triggered by pasting input
with multiple lines on the terminal.
This commit guarantees the oldshell is no longer started."
Reorder flags to elixir script in iex.bat to match the order of flags in iex.

Do not start oldshell alongside IEx, closes #5730 (on Windows)

---

lib/elixir/lib/calendar/datetime.ex

...showing an easy way to get the Unix epoch.
I thought about adding a function `DateTime.unix_epoch/0` which would just do `DateTime.from_unix!(0)`. But is it really necessary to add another function, when `DateTime.from_unix!(0)` is so simple?
This PR just adds documentation on how to get the unix epoch using the existing `DateTime.from_unix!/0` function.

Add Unix epoch example to DateTime docs 

---

lib/elixir/lib/task.ex

Old docs made it seem that a supervisor was necessary. This is clearer (in my opinion) and closer to the docs on `GenServer` module.

Update Task.start_link/1 docs

---

lib/elixir/lib/kernel.ex
lib/elixir/lib/protocol.ex
lib/elixir/test/elixir/protocol_test.exs

Implements #6178.
Some questions:
- Keep `Protocol.impls/1` and/or document `protocol.__protocol__(:impls)` in the `Kernel.defprotocol/2` docs?
- I used `[module]` for the spec of the return type of `protocol.__protocol__(:impls)` and `Protocol.impls/1`, is this really correct (since the returned impls aren't really necessarily modules, e.g. `Any`)? Should I be returning the generated impl module names instead of the "types"?

Add __protocol__(:impls) to protocols

---

lib/elixir/lib/integer.ex

It is already used in throught the module "integer" and not "int"

Standardize arguments in Integer.gcd/2

---

lib/elixir/pages/Naming Conventions.md

These are macros, not variables.
It sorts them alphabetically.

Rephrase and correct mention to double-underscore macros in Naming Conventions page

---

lib/ex_unit/lib/ex_unit/doc_test.ex
lib/ex_unit/test/ex_unit/doc_test_test.exs

As discussed in the mailing list.
this is a WIP, since I need to update the line numbers in the test, therefore the `@tag :skip`, but first need to be approved

Raise on incomplete doctests that don't finish on a trailing new line

---

lib/iex/lib/iex/introspection.ex
lib/iex/test/iex/helpers_test.exs

closes #6204 
When calling `h/1` on a `callback`
```
iex(1)> h GenServer.init
No documentation for GenServer.init was found
```
```
iex(1)> h GenServer.init
No documentation for function GenServer.init was found, but there is a callback
with the same name.
You can view callback documentations with the b/1 helper.
```
when requesting specific arity
```
iex(1)> h GenServer.init/1
No documentation for function GenServer.init/1 was found, but there is a callback
with the same name.
You can view callback documentations with the b/1 helper.
```
Any feedback is welcome, thanks! :)

Show better error when h/1 is used on callback

---

lib/elixir/lib/uri.ex
lib/elixir/test/elixir/uri_test.exs

Some `remove_dot_segments` calls were missing in `URI.merge/2` with respect to [RFC3986](https://tools.ietf.org/html/rfc3986#section-5.2.2).

Add missing calls of remove_dot_segments to URI.merge/2

---

lib/eex/lib/eex/compiler.ex
lib/eex/test/eex_test.exs

Turn EEx.SyntaxError into a warning to keep backwards compatibility

---

lib/elixir/lib/enum.ex

Nice to see that expressions are shortcutted when the array is empty but then this happens...

Fix typo in Enum doctest

---

lib/elixir/lib/kernel/parallel_compiler.ex
lib/elixir/lib/kernel/parallel_require.ex

The code is now more idiomatic as we send messages
to the parallel compiler/require instead of passing
information through the exit message.
This also allows us to more clearly distinguish between
EXITs and compilation errors.

Do not use exit(msg) in parallel compiler/require

---

lib/elixir/lib/calendar/date.ex
lib/elixir/lib/calendar/date_range.ex
lib/elixir/test/elixir/calendar/date_range_test.exs

closes #6223 
Adds `Date.Range`, implementing the `Enumerable` module so you can `count/1`, `member?/2`, etc.
Usage example:
```elixir
iex> range = Date.range(~D[2000-01-01], ~D[2001-01-1])
#DateRange<~D[2000-01-01], ~D[2001-01-1]>
iex> Enum.member?(range, ~D[2000-02-01])
true
iex> Enum.member?(range, ~D[2002-02-01])
false
```
As suggested in the issue, the `Date.Range` struct holds also `first_rata_die` and `last_rata_die`, which are later used for faster `count/1`, `member?/2` and `reduce/3` implementations.
Would love some feedback on this, thanks! 😃

Add Date.range/2

---

lib/ex_unit/lib/ex_unit/assertions.ex
lib/ex_unit/test/ex_unit/assertions_test.exs

As discussed on the mailing list. I'm open to changing how the error is reported, I wasn't sure of the best way.
Interestingly, this revealed a bug in `ExUnit.MultiError.message/1` implementation. It's fixed in a separate commit.

Make assert_raise fail with broken message/1 implementation

---

lib/elixir/lib/kernel/parallel_compiler.ex
lib/elixir/src/elixir_errors.erl
lib/mix/lib/mix/compilers/elixir.ex
lib/mix/lib/mix/tasks/compile.elixir.ex
lib/mix/test/mix/tasks/compile.elixir_test.exs

While implementing the (hacky and buggy) automatic builds and error/warning reporting in ElixirLS, one issue that made it difficult was that warnings are lost after a successful build.  If a file compiles with warnings, the next time you compile, those warnings are not shown unless you’ve changed the source or something it depends on.
This change stores warnings in the build manifest and adds an `--all-warnings` option on the CLI. When set, it will print out old warnings from non-stale files.

Add --all-warnings option to Elixir compiler

---

lib/elixir/lib/module.ex

It turns out the *link* is auto-generated so I'm not sure how to override the auto-generation. The link, as is, goes to a non-existent page ( try it: https://hexdocs.pm/elixir/Module.html ) so it's not helpful. I've made an obviously bad change here to start the conversation, as soon as I know how to override the auto-linking I'll do that.

Update link to `:erlang.module_info/0`

---

lib/elixir/lib/string.ex
lib/elixir/src/elixir_rewrite.erl
lib/elixir/test/elixir/string_test.exs

Furthermore, also inline duplicate/2 inside the String module, since it's
used there in couple places.

Inline String.duplicate to :binary.copy BIF

---

lib/elixir/src/elixir.hrl
lib/elixir/src/elixir_tokenizer.erl
lib/elixir/test/erlang/tokenizer_test.erl

Adds a `preserve_comments` option to preserve comment tokens. This will be useful for code formatting purposes.
Sample code:
```ruby
def test3() do
if true do
else
end
end
```
Usage:
```
iex(4)> :elixir_tokenizer.tokenize(code, 0, 0, [])
{:ok, 7, 4,
[{:identifier, {0, 0, 3}, :def}, {:paren_identifier, {0, 4, 9}, :test3},
{:"(", {0, 9, 10}}, {:")", {0, 10, 11}}, {:do, {0, 12, 14}},
{:eol, {0, 14, 15}}, {:identifier, {1, 3, 5}, :if}, {true, {1, 6, 10}},
{:do, {1, 11, 13}}, {:eol, {1, 13, 14}},
{:block_identifier, {3, 3, 7}, :else}, {:eol, {3, 7, 8}}, {:end, {5, 3, 6}},
{:eol, {5, 6, 7}}, {:end, {7, 1, 4}}]}
iex(5)> :elixir_tokenizer.tokenize(code, 0, 0, [{:preserve_comments, true}])
{:ok, 7, 4,
[{:identifier, {0, 0, 3}, :def}, {:paren_identifier, {0, 4, 9}, :test3},
{:"(", {0, 9, 10}}, …
```

Add preserve_comments option to tokenizer

---

lib/iex/test/iex/helpers_test.exs

A related test was not updated when improving argument name for Mix.Task.run/1 on https://github.com/elixir-lang/elixir/commit/b18160f7cbc236ed074d5c93875493a14903f3ff.

Fix broken test for Mix.Task run callback

---

lib/elixir/lib/string.ex

* Skip unnecessary matches on the "rest" size
* Don't prepend/append empty strings
The second one is especially important - doing `"" <> str` will force a copy of
the string. Checking, if the string is empty first, allows us to skip this copy.
Using replace functions with empty replacements is rather common - one example
is the String.trim* family of functions, but even in user code it's quite
frequent.
Removing excessive copy means the speedup can be made arbitrarily large
depending on input. The slowdown for cases with non-empty strings couldn't be
reliably measured.

Optimize String.replace_* functions

---

CHANGELOG.md

- Variable name autocompletion was added in #5504.
- Autocompletion of imported `:only` functions was added in #5518.

Mention IEx autocompletion enhancements.

---

lib/ex_unit/lib/ex_unit.ex

Timeouts get disabled in trace mode. I was puzzling over why timeouts weren't working and eventually found relevant code the exunit source that actually disables them.

Add exunit doc about trace mode and test timeouts

---

lib/elixir/src/elixir.erl
lib/elixir/src/elixir_parser.yrl
lib/elixir/test/elixir/code_test.exs

This PR adds a `metadata_in_literals` option to the parser, which wraps literals like `123`, `:one`, `"one"` or `nil` in a `__block__` tuple along with their metadata. This will be very useful for code formatting purposes since it is now possible to attach comments to a literal based on its line number. The option is invoked from `Code.string_to_quoted/2`. 
@josevalim @whatyouhide currently, this is still a WIP. Would like your feedback on my implementation before moving forward. Also, please let me know if there are any literals that I missed.
Sample code:
```elixir
def test3() do
if true do
else
end
1
"one"
:one
end
```
Usage:
```elixir
iex(8)> Code.string_to_quoted(code)
{:ok,
{:def, [line: 1],
[{:test3, [line: 1], []},
[do: {:__block__, [],
[{:if, [line: 2], [true, [do: nil, else: …
```

Add wrap_literals_in_blocks option to parser

---

lib/mix/lib/mix/task.compiler.ex
lib/mix/lib/mix/task.ex
lib/mix/lib/mix/tasks/compile.all.ex
lib/mix/lib/mix/tasks/compile.app.ex
lib/mix/lib/mix/tasks/compile.elixir.ex
lib/mix/lib/mix/tasks/compile.erlang.ex
lib/mix/lib/mix/tasks/compile.leex.ex
lib/mix/lib/mix/tasks/compile.protocols.ex
lib/mix/lib/mix/tasks/compile.xref.ex
lib/mix/lib/mix/tasks/compile.yecc.ex

Though there isn't much immediate benefit to codifying the current behavior, the Mix.Task.Compiler behavior is good to have as documentation for how to implement a compiler. The ultimate goal is to have a callback specification for `run/1` that returns diagnostic information for errors and warnings.
Open questions:
- Should `use Mix.Task.Compiler` include default implementations for `clean/0` and `manifests/0`?
- Should `Mix.Tasks.Compile.All` have implementations for `manifests/0` and `clean/0` that call them for each compiler, or should these be noops?

Create behavior for Mix compiler tasks

---

lib/elixir/src/elixir_erl_pass.erl
lib/elixir/test/erlang/control_test.erl

It wasn't actually working, because of the wrong pattern match the function
never returned true.
---
This hints, it would be nice to have some tests in place, but I have no idea how to actually test it. It doesn't seem like we test other compiler optimisations either.

Fix optimisation from #6240

---

lib/elixir/pages/Writing Documentation.md

this is only a problem on v1.4, master is fine.

Fix links in documentation guideline on v1.4

---

lib/eex/lib/eex/engine.ex
lib/eex/lib/eex/tokenizer.ex
lib/eex/test/eex/tokenizer_test.exs
lib/eex/test/eex_test.exs

Supports markers `"|"` and `"/"` in `EEx.Engine`.
To be used only within custom Engines. By default raise `EEx.SyntaxError` when not implemented.
`"|"` and `"/"` were chosen because thet should confuse the "" marker, as they should not appear at the beginning of any Elixr expression.

Allow markers "/" and "|" to be used in a custom EEx engine

---

lib/elixir/lib/enum.ex
lib/elixir/test/elixir/enum_test.exs

Closes https://github.com/elixir-lang/elixir/issues/6291
---
One thing to note is that even with that impelmentation, you might get an arbitrary binary function (for example `&+/2`) that still won't work - there's just no way to know other than trying to execute. And the execution can throw arbitrary errors since the function can be completely arbitrary.

Raise Protocol.UndefinedError on bad functions in Enumerable implementation

---

lib/elixir/lib/string_io.ex
lib/elixir/test/elixir/string_io_test.exs

This pull-request addresses the following:
1. Adds tests for `StringIO.get_until`. Previously there were no tests for this function.
2. Fixes the same performance/scalability issue that was fixed for `StringIO.read_line` in #6056.
3. Fixes 2 bugs, described below.
Due to the lack of tests and shortage of examples I tried to change the logic of `do_get_until` as little as possible.
I added test coverage to all of the `case` clauses in `do_get_until`. With the exception of the 2 tests listed below, all tests passed before any changes were made to the implementation.
I found `get_until` to be awkward to test. If anyone has feedback on how to improve these tests then please let me know.
This bug is reproduced by the test titled `"get_until with until_eof and \\r\\n"`.
This bug is reproduced …

StringIO.get_until bug fix, performance, and tests

---

lib/elixir/src/elixir.hrl
lib/elixir/src/elixir_errors.erl
lib/elixir/src/elixir_parser.yrl
lib/elixir/src/elixir_tokenizer.erl
lib/elixir/test/elixir/code_test.exs
lib/elixir/test/erlang/tokenizer_test.erl

Currently, we don't have a way to know which sigil terminators are used after the sigils are tokenized. This PR adds an option to detect such terminators by passing an extra `Terminator` element in the sigil token. The parser will detect the presence of the `Terminator` value and insert it into the sigil AST node's metadata appropriately.
Usage:
```elixir
iex(2)> Code.string_to_quoted("~r/foo\\//")
{:ok, {:sigil_r, [line: 1], [{:<<>>, [line: 1], ["foo/"]}, []]}}
iex(3)> Code.string_to_quoted("~r/foo\\//", detect_sigil_terminators: true)
{:ok, {:sigil_r, [terminator: 47, line: 1], [{:<<>>, [line: 1], ["foo/"]}, []]}}
iex(5)> Code.string_to_quoted("~S\"\"\"\nsigil heredoc\n\"\"\"\n", detect_sigil_terminators: true)
{:ok,
{:sigil_S, [terminator: '"""', line: 1],
[{:<<>>, [line: 1], ["sigil …
```

Add terminator info to sigil AST node metadata

---

lib/mix/lib/mix/task.ex
lib/mix/test/mix/task_test.exs

This function is currently returning either `nil` or the alias itself from the
mix file, so it doesn't match with the `boolean` return type indicated by the
documentation.
Thanks!

Fix return type of Mix.Task.alias?/1

---

lib/elixir/pages/Guards.md

Improve grammar and avoid using the same word *fail* for opposing examples.

Improve the failing guards guide

---

lib/elixir/lib/macro/env.ex
lib/elixir/src/elixir.erl
lib/elixir/src/elixir_clauses.erl
lib/elixir/src/elixir_env.erl
lib/elixir/src/elixir_erl_try.erl
lib/elixir/src/elixir_expand.erl
lib/iex/lib/iex.ex
lib/iex/lib/iex/app.ex
lib/iex/lib/iex/autocomplete.ex
lib/iex/lib/iex/config.ex
lib/iex/lib/iex/evaluator.ex
lib/iex/lib/iex/helpers.ex
lib/iex/lib/iex/introspection.ex
lib/iex/lib/iex/pry.ex
lib/iex/lib/iex/server.ex
lib/iex/test/iex/autocomplete_test.exs
lib/iex/test/iex/helpers_test.exs
lib/iex/test/iex/interaction_test.exs
lib/iex/test/iex/pry_test.exs
lib/iex/test/test_helper.exs

The following functions will be added:
The following helpers will be added:
Then we need to add the pry specific documentation.

Add breakpoint support to IEx.pry

---

lib/elixir/lib/calendar/date.ex
lib/elixir/lib/calendar/datetime.ex
lib/elixir/lib/calendar/naive_datetime.ex
lib/elixir/lib/calendar/time.ex

- change `Date.t` to `Calendar.date` (same for other types)
- add `no_return` to function that raise error
- add doctests to `convert/2`

Update docs & typespecs for calendar modules

---

lib/iex/lib/iex.ex

• "The following call" seems to referring to the preceding call.
• Second example is missing function arity
• Documentation states default `stops` value to be 1, but it’s currently 10.

Fix what I believe to be some errors in the `IEx.break!` documentation/definition

---

lib/elixir/lib/enum.ex
lib/elixir/lib/stream.ex
lib/elixir/test/elixir/enum_test.exs
lib/elixir/test/elixir/stream_test.exs

Before this commit, there wasn't a clear check on these two functions accepting only a list of enumerables as its argument. This lead to things like https://github.com/elixir-lang/elixir/pull/6321.
If merged, will invalidate #6321.

Force {Enum,Stream}.zip/1 to take a list of enumerables as argument

---

lib/elixir/lib/agent.ex

Fix typo in Agent @moduledoc

---

lib/elixir/src/elixir_parser.yrl
lib/elixir/test/elixir/code_test.exs

Currently, lists and tuples of size 2 do not have metadata on their own, hence, it is hard to format code where comments/newlines precede the lists/tuples of size 2. This PR wraps them in a block using an option.
```elixir
[1,2,3]
[
1,
2,
3,
]
{:one, :two, :three}
{:ok, :some_value}
```

Wrap lists and tuples of size 2 in blocks

---

lib/elixir/lib/agent.ex

Recent editions to Agent have updated examples to notate `fn state` without parens.
Found and updated a loose one that had the previously used notation.

Remove parens in "fn" calls in the Agent docs

---

lib/elixir/lib/registry.ex
lib/elixir/test/elixir/registry_test.exs

Right now in a duplicate registry using unregister on a key unregisters all key / value pairs. The idea with this function is that it would only unregister particular values that match a given spec.
The primary issue at the moment is that the `true = :ets.delete_object(pid_ets, {self, key, key_ets})` deletes all instances of the key under self, but instead we want N instances of the key where N is the number of key value pairs remaining in the key_ets table.

Registry.unregister_match/2

---

lib/elixir/lib/kernel.ex
lib/elixir/src/elixir_expand.erl
lib/elixir/test/elixir/kernel/alias_test.exs
lib/elixir/test/elixir/kernel/comprehension_test.exs
lib/elixir/test/elixir/kernel_test.exs
lib/elixir/test/erlang/control_test.erl

orelse may lead to better code in many occasions. Since we're comparing
to literals, there's no semantic difference.
This also means, the compiler is able to figure out more "will always match"
checks. For example in a situation like the following a warning will be emitted.
This pull request also fixes such warnings in the test suite.
if true do
IO.puts("true")
end

Use orelse instead of or when expanding in operator

---

lib/mix/lib/mix/tasks/compile.protocols.ex
lib/mix/test/mix/tasks/compile.protocols_test.exs

This PR fixes a bug when recompiling a mix project where a protocol has been converted into a standard module.
1. Create a new mix project (`mix new bug_demo`)
2. Define a protocol and an implementation somewhere:
```elixir
defprotocol Foo do
def bar(arg)
end
defimpl Foo, for: Integer do
def bar(_), do: :ok
end
```
3. Compile (`mix compile`)
4. Remove the protocol (and its implementation) and define a module with the same name:
```elixir
end
```
5. Compile (`mix compile`)
Compile without errors
It shows the following error:
```
Compiling 1 file (.ex)
Generated bug_demo app
** (EXIT from #PID<0.70.0>) an exception was raised:
** (CaseClauseError) no case clause matching: {:error, :not_a_protocol}
(mix) lib/mix/tasks/compile.protocols.ex:125: …
```

Fix protocols diff calculation between compilations

---

lib/elixir/lib/calendar/time.ex

For consistency with Time.compare/2 allow other types that contain time. For instance `DateTime` and `NaiveDateTime`.

Allow more than Time structs in Time.diff

---

lib/elixir/lib/stream.ex
lib/elixir/test/elixir/stream_test.exs

This PR adds `Stream.intersperse/2`. See [here](https://groups.google.com/forum/#!topic/elixir-lang-core/AsBKS2jgP4w) for the original proposal. 
I tried implementing it as José suggested, which is based on `%Stream{}` struct. Unfortunately, that won't work well for this case. Basically, `%Stream{}` is suitable to power stream which generates zero or one element for each input element. In this case, we need to generate two elements, and if this is powered by `%Stream{}`, in some cases (in particular when zipping the stream), we might end up loading most of the input enumerable into memory before it is needed. As a result, in this case `%Stream{}` based intersperse converges into an eager version.
Therefore, I opted for this version, which is slightly different from the one I proposed. …

Add Stream.intersperse/2

---

lib/elixir/lib/kernel.ex
lib/elixir/lib/version.ex

We choose to change Kernel because that's the entry point
of the Elixir documentation (and it is the best entry point
as it contains all imported functions and quick access to
the other modules in the documentation sidebar).

Give a tour of the standard library on Kernel

---

lib/mix/lib/mix/tasks/compile.erlang.ex

I was trying to build ejabberd using Mix but many of the source files contain the following Erlang module attribute.
`-compile([{parse_transform, ejabberd_sql_pt}]).`
These options were not getting matched, and so were not being added to the Erlang module dependency tree resulting in ejabberd_sql_pt not being compiled early enough.

Handle -compile module attribute when specified as a list

---

lib/elixir/src/elixir_parser.yrl
lib/elixir/src/elixir_tokenizer.erl
lib/elixir/test/elixir/code_test.exs
lib/elixir/test/erlang/string_test.erl
lib/elixir/test/erlang/tokenizer_test.erl

@josevalim @whatyouhide still a WIP. Would like your feedback. Tried emitting different tokens `binary`, `octal` and `hex` but it makes the code more complicated and resulted in obscure compilation errors.
With this implementation, there are 14 test cases failing, but they should be quite easy to fix since we just need to insert the 4th `base` element in the `number` token tuple used in the test cases. The only downside is that the 4th element may be obscure to the uninformed reader.
```elixir
iex(1)> Code.string_to_quoted("0xEF", wrap_literals_in_blocks: true)
{:ok, {:__block__, [base: 16, line: 1], [239]}}
iex(3)> Code.string_to_quoted("1234", wrap_literals_in_blocks: true)
{:ok, {:__block__, [base: 10, line: 1], [1234]}}
iex(4)> Code.string_to_quoted("0b10", wrap_literals_in_blocks: …
```

Augment integer literals with representation info

---

lib/elixir/lib/code.ex

Replaced `succeeds loading` with `succeeds in loading`.
I believe that's the established usage in contexts such as this.
Cheers!

Replace `succeeds loading` → `succeeds in loading` in Code module docs

---

lib/elixir/lib/system.ex
lib/elixir/test/elixir/system_test.exs

Currently it's possible to pass a charlist instead of a binary as an
argument, and this shouldn't be possible.
Resolves #6367

Add check for correct types on System.cmd/3

---

lib/elixir/src/elixir_parser.yrl
lib/elixir/src/elixir_tokenizer.erl
lib/elixir/test/elixir/code_test.exs

Sample code:
```
"""
this is a binary
"""
'''
this is a charlist
'''
```
Output from `Code.string_to_quoted/2` with `wrap_literals_in_blocks: true`:
```
{:ok,
{:__block__, [],
[{:__block__, [format: :bin_heredoc, line: 1], ["this is a binary\n"]},
{:__block__, [format: :list_heredoc, line: 5], ['this is a charlist\n']}]}}
```
@josevalim @whatyouhide still a WIP. Would like your buy-in before adding tests. Thanks!

Add heredoc type to heredoc list/binary literals

---

lib/elixir/lib/task/supervised.ex
lib/elixir/test/elixir/task_test.exs

Fixes a regression introduced in 1.5. Relevant [thread on Elixir Forum](https://elixirforum.com/t/task-async-stream-timeout-infinity-and-1-5-0/7205) where it was reported.

support :infinity timeout on Task streams

---

lib/elixir/lib/gen_server.ex
lib/elixir/lib/supervisor.ex
lib/elixir/lib/task.ex

Hi, just a small typo I came across.
`defauts` -> `defaults`

Fix small typo in GenServer,Supervisor,Task doc

---

lib/elixir/lib/system.ex
lib/elixir/test/elixir/system_test.exs

Example:
```
$ elixir -v
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.6.0-dev (9d3753ded) (compiled with OTP 20)
```

Add OTP version to System.build_info/0

---

lib/iex/lib/iex/helpers.ex

IMHO this could be very useful in a number of use-cases, especially when the dev environment differs from the deployment target.

List applications in runtime_info

---

lib/elixir/lib/file.ex

"File.cp_r/3" currently shows up in the File.rm_rf null byte error.

Fix operation passed to assert_no_null_byte

---

lib/elixir/pages/Syntax Reference.md
lib/iex/lib/iex.ex

Found a formatting issue in the Syntax Reference documentation, where charlist does not get a proper section (see https://hexdocs.pm/elixir/syntax-reference.html#strings).
I found that the issue was caused by the preceeding `` `\` `` block. It can be fixed simply by adding a space, so it becomes `` `\ ` ``. I also applied this in the IEx documentation, which suffers from the same problem (see https://hexdocs.pm/iex/IEx.html#module-exiting-the-shell).
This also means warnings like `` lib/iex/lib/iex.ex:269: warning: Closing unclosed backquotes ` at end of input `` no longer appear when generating the documentation.

Fix documentation formatting where ` follows \

---

lib/ex_unit/lib/ex_unit.ex
lib/ex_unit/lib/ex_unit/cli_formatter.ex
lib/ex_unit/mix.exs
lib/ex_unit/test/ex_unit_test.exs
lib/mix/lib/mix/tasks/test.ex

This adds a `--slowest N` CLI flag to `mix test`, which will print timing information for the slowest test times. To ensure that reported times are accurate enabling slow reporting will automatically set the suite in `--trace` mode.
The `slowest` setting defaults to `0`, disabling it for normal test runs. Setting it to any positive integer will report a cumalitve slow test time and display individual timings for each of the slowest tests.
**Notes**
This has been manually tested/inspected against the ex_unit test suite itself as I was developing it. When the suite is ran with `trace: true` it hangs on a timeout test, so I just ran it with slowest enabled and trace disabled. The timings were fairly consistent, even with async testing.
Here is sample output for an async run of the ex_unit …

Add mix test --slowest reporting to ExUnit

---

lib/elixir/lib/map_set.ex

Just a small potential refactor I saw while reading *map_set.ex*.
The dummy value associated to MapSet elements in the underlying map is repeated in a few spots. Also, it could be argued that
```elixir
new_from_list(rest, [{item, @dummy_value} | acc])
```
is more intention-revealing than
```elixir
new_from_list(rest, [{item, []} | acc])
```
Anyway, your call! 😄

Extract MapSet dummy values to a module attribute

---

lib/elixir/lib/supervisor.ex

Some minor docs improvements. The more important of them is a fixing an indentation that made a text paragraph to format as code. The second one is probably a bit opinionated, changing 10000 to 10_000, now it's more readable and inline with the text.

Improve formatting of Supervisor documentation

---

lib/elixir/lib/macro.ex
lib/elixir/test/elixir/macro_test.exs

Calls such as `Foo.{Bar, Baz}` (used in `alias Foo.{Bar, Baz}` for example) were badly formatted by `Macro.to_string/2`. That's fixed in this PR.

Fix Macro.to_string/2 for tuple calls

---

lib/elixir/unicode/unicode.ex

This produces a bit more readable message if not a string is passed into `String.length`, then failing in the `next_grapheme_size` function.

Add is_binary guard to String.length

---

lib/ex_unit/lib/ex_unit/case.ex

Replace `how tests behaves` → `how tests behave`

Fix verbal agreement in ExUnit.Case @moduledoc

---

lib/elixir/lib/uri.ex
lib/elixir/test/elixir/uri_test.exs

Problem: The current implementation removes empty fragments.
```elixir
iex> "http://example.com/test#" |> URI.parse |> to_string
"http://example.com/test"
iex> URI.parse("http://example.com/test#") == URI.parse("http://example.com/test")
true
```
[RFC 3986](https://tools.ietf.org/html/rfc3986#section-6.2.3) clearly says: _"[...] two URIs that differ only by the suffix "#" are considered different [...]_"
This is also serious problem with respect to the most common solution to the [httpRange-14 issue](https://en.wikipedia.org/wiki/HTTPRange-14#Use_of_.23). 
I've stumbled across this problem on several occasions during the development on [RDF.ex](https://github.com/marcelotto/rdf-ex).

Fix URI.parse/1 to preserve empty fragments

---

lib/ex_unit/lib/ex_unit/assertions.ex
lib/ex_unit/test/ex_unit/assertions_test.exs

I agreed with @josevalim's idea of raising an exception here rather
than coercing the negative delta, so I implemented that. As a user, I
would find that coercion to be unexpected behavior, and I personally
felt the value of being explicit here outweighed the convenience of the
coercion. I did, however, put in the exception message a helpful hint
in the case that the user did want the absolute value of that negative
delta instead.
Fixes #6439

Raise exception when passing negative delta to assert_in_delta/4

---

lib/elixir/lib/supervisor.ex

Hi all,
just a little double space there.
Cheers!

Remove double space from Supervisor moduledoc

---

lib/elixir/lib/supervisor.ex

`the recommend value is...` → `the recommended value is...`

Improve wording in Supervisor moduledoc

---

lib/iex/lib/iex/evaluator.ex
lib/iex/lib/iex/helpers.ex
lib/iex/lib/iex/pry.ex

Prints the current stacktrace with `whereami/0` output. See #6390.
```
iex> whereami
Location: lib/Foo.ex:17
15:   def bar do
16:     require IEx
17:     IEx.pry
18:     :blah
19:   end
Stacktrace:
(Foo) lib/foo.ex:15: Foo.bar/0
(Baz) lib/baz.ex:3: Baz.qux/0
```

Add current stacktrace to whereami/0

---

lib/elixir/src/elixir_bitstring.erl
lib/elixir/test/elixir/kernel/errors_test.exs
lib/elixir/test/elixir/kernel/expansion_test.exs

The error was introduced with the changes on 35fae4790440cab90b85a99c04fad8de6b0f1d1a
Resolves #6450

Fix old initialisation for match_vars

---

lib/elixir/lib/supervisor.ex

Hey all,
this one is in a longer phrase, but it removes an `is` near its end.
From
```
In this case the supervisor will only be restarted if its
child specification was defined with the `:restart` option is set to `:permanent`
(the default).
```
to 
```
In this case the supervisor will only be restarted if its
child specification was defined with the `:restart` option set to `:permanent`
(the default).
```
Cheers!

Remove extraneous 'is' from Supervisor moduledoc

---

lib/elixir/lib/supervisor.ex

Hi all,
```when `:restart` is set `:transient`...```
to
```when `:restart` is set to `:transient`...```
Cheers!

Reword Supervisor moduledoc line

---

lib/elixir/lib/enum.ex

Recently someone(@dploop) told me that matching a key is much faster than use `maps:find/2` in erlang. So I did a little benchmark. See:
https://gist.github.com/Kabie/e34db1b4722211d1c27d2becbacce325
The pattern match wins in most cases. Only situations like when map is a large flat map(map size around 20~31) and the key does not exist, pattern match is slower. This is an acceptable trade off IMO.

Tweak performance of `Enumerable.member?/2` for Map

---

lib/elixir/lib/supervisor.ex

Little double space I found while studying the source code for Supervisor.
I did take note of Valim's request to aggregate these tiny commits into one PR whenever possible. I only happened to find one this time around.

Remove double space from Supervisor doc

---

lib/elixir/lib/list.ex
lib/elixir/lib/map.ex

In collections, use `fun` instead of `callback` or `function` for consistency.

Consistently refer to callback functions as fun

---

lib/elixir/lib/calendar/date_range.ex

Why
---
Fields mistakenly referenced nonexistent `Calendar.days` type
How
---
Change `Calendar.days` to `Calendar.iso_days`

Fix Date.Range.t/0

---

lib/elixir/src/elixir_interpolation.erl
lib/elixir/src/elixir_parser.yrl
lib/elixir/src/elixir_tokenizer.erl
lib/elixir/test/erlang/string_test.erl
lib/elixir/test/erlang/tokenizer_test.erl

Right now, tokens are `{Token, Location}` or `{Token, Location, Value}`. This PR changes `Location` from `{Line, StartColumn, EndColumn}` to `{Line, {StartColumn, EndColumn}, Meta}` where `Meta` can be anything. This will be used for things such as storing the format of integers.
For now all `Meta` are `nil` (we can go with any term that means nothing here), we'll fill it up for some tokens later on.

Change the format of tokens

---

lib/elixir/src/elixir_errors.erl
lib/elixir/src/elixir_parser.yrl
lib/elixir/src/elixir_tokenizer.erl
lib/elixir/test/elixir/code_test.exs
lib/elixir/test/elixir/kernel/errors_test.exs
lib/elixir/test/erlang/string_test.erl
lib/elixir/test/erlang/tokenizer_test.erl

This is basically the same as #6492, but reworked after #6495. Integer tokens are now `int`, not `hex`/`binary`/`octal`/`decimal`. Reasons for this change are in #6495.
Note that the `int` token looks like this
```erlang
{int, {Line, {StartColumn, EndColumn}, IntValue}, OriginalRepresentation}
```
so for `0b010` you'd have
```erlang
{int, {_, _, 2}, "0b010"}
```

Merge integer tokens into the "int" token

---

lib/elixir/lib/path.ex
lib/elixir/test/elixir/path_test.exs

This thing caught me and @michalmuskala:
```
iex(1)> Path.join("a/b/c", ["d", "e"])
"a/b/c/de"
iex(2)> Path.join(["a/b/c", "d", "e"]) 
"a/b/c/d/e"
```
I've expected that right or left part would be joined with path separator between elements.
I think we need either join `left` and `right` parts of the path by calling `join/1` recursively (that looks like a breaking change), or clarify behavior in the docs (as I did for now).

Clarify Path.join/2 behavior when dealing with lists

---

lib/elixir/lib/kernel.ex

Fix word in Kernel moduledoc

---

lib/elixir/lib/registry.ex
lib/elixir/test/elixir/registry_test.exs

More info: https://github.com/elixir-lang/elixir/issues/6507

Correct Registry.match/4's typespec of its "pattern" argument

---

lib/ex_unit/lib/ex_unit.ex

Windows does not have microsecond-level timestamps. As such, the seed
generated by :os.timestamp is only in the millisecond range, giving
multiples of 1000 for "random" seeds. This change should give the same
results in *nix systems while giving a wider seed variety on Windows.

Fix random seed generation in ExUnit for Windows systems

---

lib/elixir/lib/io.ex

When I was reading the documentation for this function a couple days
ago, the line "It returns `:ok` if it succeeds." was really confusing
to me. It made me think there was some other error possibility that I
was missing and should handle.
After looking at the Erlang docs for `:io.put_chars/2`, it looks like
there isn't some additional error case. Only then did I even notice the
typespec that says this function always returns `:ok`. So, I think this
line is misleading, and we should remove it.

Update `IO.write/2` docs

---

lib/elixir/lib/calendar.ex
lib/elixir/lib/calendar/date.ex
lib/elixir/lib/calendar/naive_datetime.ex
lib/elixir/lib/file/stream.ex
lib/elixir/lib/gen_server.ex
lib/elixir/lib/inspect/algebra.ex
lib/elixir/lib/io/stream.ex
lib/elixir/lib/kernel.ex
lib/elixir/lib/module/locals_tracker.ex
lib/elixir/lib/supervisor.ex
lib/elixir/lib/supervisor/spec.ex
lib/elixir/lib/task.ex
lib/elixir/test/elixir/registry_test.exs
lib/mix/lib/mix/tasks/test.ex

"amount" is [not grammatical](https://english.stackexchange.com/questions/337989/the-amount-of-vs-the-number-of-etc/337998#337998) when used with count nouns (e.g. days, seconds, bytes, entries, restarts, partitions, cores).

Use "number" instead of "amount" for count nouns

---

lib/elixir/lib/tuple.ex

Fixed some inconsistent spacing in the documentation example for `Tuple.append`.

Add newline spacing around documentation example

---

lib/elixir/lib/calendar.ex
lib/elixir/lib/calendar/date.ex
lib/elixir/lib/calendar/datetime.ex
lib/elixir/lib/enum.ex
lib/elixir/lib/module.ex
lib/elixir/lib/registry.ex
lib/elixir/lib/supervisor.ex
lib/elixir/lib/task/supervised.ex
lib/elixir/src/elixir.erl
lib/elixir/src/elixir_bootstrap.erl
lib/elixir/src/elixir_compiler.erl
lib/elixir/src/elixir_map.erl
lib/elixir/test/elixir/base_test.exs
lib/elixir/test/elixir/kernel/alias_test.exs
lib/elixir/test/elixir/kernel/dialyzer_test.exs
lib/elixir/test/elixir/kernel/import_test.exs
lib/elixir/test/elixir/registry_test.exs
lib/elixir/test/elixir/system_test.exs
lib/ex_unit/lib/ex_unit/callbacks.ex
lib/iex/test/iex/helpers_test.exs
lib/iex/test/iex/pry_test.exs
lib/iex/test/iex/server_test.exs
lib/logger/lib/logger.ex
lib/mix/lib/mix.ex
lib/mix/lib/mix/compilers/test.ex
lib/mix/lib/mix/remote_converger.ex
lib/mix/test/mix/tasks/deps.path_test.exs
lib/mix/test/mix/tasks/loadconfig_test.exs
lib/mix/test/mix/utils_test.exs

Notes:
standardize on "falsy" because there are more instances of that in the code already
"clean up" isn't a noun, "cleanup" is
"run down" isn't a noun
"take over" isn't a noun
A dependant is a person who is dependent on someone else; "dependent" is the adjective; American English uses "dependent" for both which makes things really simple when code has both "dependent on" and "dependent module"

Fix more typos and spelling errors

---

lib/elixir/lib/map_set.ex
lib/elixir/test/elixir/map_set_test.exs

Right now, the `union` function returns a bare map instead of a `MapSet` struct when operating on `MapSet`s with differing versions. This fix wraps the map appropriately.
Although this fixes behaviour at the `MapSet` API level, I'm not sure what level of support there is intended to be for legacy `MapSet`. Some of the functions have potentially unwanted behaviour that results in a hybrid `MapSet` (legacy `MapSet` with `[]` values, or v2 `MapSet` with `true` values) that would fail pattern matching even if both are at the same version.
```
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
Interactive Elixir (1.5.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> old = %{__struct__: MapSet, map: %{a: true, b: true, c: …
```

Return valid MapSet when union-ing a legacy MapSet

---

lib/elixir/lib/task/supervisor.ex

Just noticed this one while attending the OTP workshop @ ElixirConf 2017 🔨

Fix typo in Task.Supervisor

---

lib/logger/lib/logger/error_handler.ex
lib/logger/lib/logger/utils.ex
lib/logger/test/logger/utils_test.exs

Mentioned on #4617.
It made the code a lot easier to read.
I did not write any tests, since `Logger.Utils.inspect` already has some
There is also room for a performance improvement here.
The way `Logger.Utils.inspect` is used now follows the flow:
- scan the format
- handle the inpects
- unscan the format
- then it is used by `Logger.ErrorHandler.translate`, which calls `io_lib:format` that consequently:
- scan the format again
- then finally build it
To optimize, we can call `io_lib:build_text` on the scanned and inspected format
list.
I'll do it soon in this same PR if you could wait a little bit.

Use :io_lib.scan_format/2 on Logger.Utils.inspect/4

---

lib/elixir/lib/calendar/time.ex

It should serve as a "safer" alternative to non-existing `Time.add/3`.
CC @lau

Introduce Time.add/3

---

CHANGELOG.md
lib/elixir/lib/string.ex
lib/elixir/test/elixir/string_test.exs

This patch allows calling `String.replace` with an empty string as the match argument.
When I found out that passing an empty string as a match argument to `replace` throws an `ArgumentError` I was surprised by this unexpected behavior. 
Many languages support this feature which allows supplying match arguments coming from dynamic sources.
For example assume we are processing file names and trying to remove the
extension (*assuming `Path.basename/2` function did not exist*):
**Before** patch:
```elixir
inputs = ["README.md", "package.json", "LICENSE"]
inputs
|> Enum.map(&(String.replace(&1, Path.extname(&1), "")))
```
To fix it we would have to transform the code to something like this:
```elixir
inputs = ["README.md", "package.json", "LICENSE"]
inputs
|> Enum.map(fn (file) ->
ext = …
```

Allow passing empty string as match argument to String.replace/4

---

lib/mix/lib/mix/tasks/local.hex.ex

When Hex is loaded then `should_install?` should be `false`.
Looks like it never worked properly :(

Fix local.hex --if-missing

---

lib/mix/lib/mix/dep/lock.ex
lib/mix/test/mix/dep/lock_test.exs

As suggested by @josevalim in #6574 I've standardised the format  of `mix.lock` so that each line containing a dependency is in the same format.
So instead of this:
```elixir
%{"foo": ...,
"bar": ...}
```
we now use this format:
```elixir
%{
"foo": ...,
"bar": ...,
}
```
This should improve readability, consistency and also make resolving version control conflicts much easier to deal with (manual or automated).
This change should also make possible implementations of #6554 (which may try to directly resolve conflicts in `mix.lock`) easier to implement since each line containing a dependency is in the same format.
Haven't yet found any other code that needs modification in this PR, but would appreciate any insights on what might break as a result of this change.

Format mix.lock with one dep only per line

---

lib/ex_unit/lib/ex_unit/callbacks.ex
lib/ex_unit/lib/ex_unit/case.ex
lib/ex_unit/lib/ex_unit/filters.ex
lib/ex_unit/test/ex_unit/case_test.exs
lib/ex_unit/test/ex_unit/describe_test.exs
lib/ex_unit/test/ex_unit/filters_test.exs
lib/mix/lib/mix/tasks/test.ex

Until now, ExUnit's line filter (such as `mix test path/to/file:123`) only detected a test case starting at the given line number. Running all tests in a describe block was only possible using `mix test --only describe:"String.capitalize/1"`.
This PR adds the possibility to run all tests in a describe block by addressing the line starting it. If `describe "String.capitalize/1"` is at line 123, all tests in it can now be run via `mix test path/to/file:123`.
This filter is shorter and more intuitive as it makes the line filter smarter, and is in line with the behavior of other test runners, such as rspec, as well as what IDEs such as RubyMine expect.
Implementation-wise, I added an automatic tag `@ex_unit_describe_line` that is added to each test's tags as `:describe_line` and then used for …

Detect describe block at given line filter and run all tests in it

---

lib/mix/lib/mix/tasks/profile.eprof.ex
lib/mix/test/mix/tasks/profile.eprof_test.exs

Continuing the work done in https://github.com/elixir-lang/elixir/pull/5834 and discussed in [the Elixir Core Mailing List](https://groups.google.com/forum/#!topic/elixir-lang-core/LeB8G1_CSQI), here is the proposed code for `Mix.Tasks.Profile.Eprof` to profile code using Erlang's `:eprof`.
The logic follows the one done for `Mix.Tasks.Profile.Cprof`, but the functions are not shared following the previous PR.
Some points:
- The output is very similar output from Erlang, I don't know if we want to keep like this or change something.
- `:eprof` offers a `mfa` sorting option, but I didn't implement because it looks confusing when the mfa is transformed to be printed, especially cases like `anonymous fn/0 in :elixir_compiler_7.__FILE__/1`
- Would also be nice a help with the documentation, …

Add Mix.Tasks.Profile.Eprof for profiling using eprof

---

bin/elixir.bat

Erlang parameters (CLI switch '--erl') are used with possible quotes around the argument removed ('%~1').
This causes an error if one arbitrary argument to elixir.bat represents a quoted path with spaces in it:
"[part of path after space] was unexpected at this time."
Enclose the complete expression with quotes to work around this (the quotes are not added to the content).
This behavior is not documented in the [Windows XP Command Line Reference for SET](https://www.microsoft.com/resources/documentation/windows/xp/all/proddocs/en-us/set.mspx)
but there are other places which document the [SET command](https://ss64.com/nt/set.html).
Fix for #6455

Support path with spaces as argument to elixir.bat

---

lib/elixir/lib/module.ex
lib/elixir/test/elixir/kernel/impl_test.exs

`Module.compile_impl/6` was ignoring the default attributes when compiling the impl, now it checks the count of default attributes and adds an impl for each one.
I tried to follow the same idea of [`Module.add_doc/6`](https://github.com/elixir-lang/elixir/blob/144df88caedfae891e12fcd3595c61b64783fd12/lib/elixir/lib/module.ex#L641), that resolves the signature of the function by itself. The count of default attributes follows the same logic as [`:elixir_def.expand_defaults/2`](https://github.com/elixir-lang/elixir/blob/144df88caedfae891e12fcd3595c61b64783fd12/lib/elixir/src/elixir_def.erl#L230)
Fixes #6550

Fix @impl attribute for default arguments

---

lib/elixir/src/elixir_expand.erl

I believe this should resolve #6583. Linking seemed like the more appropriate solution, since there would be a lot of built-in guard functions to list and wouldn't cover macros the user defined.

Add link to docs for guards, when an invalid guard expression is used

---

lib/elixir/lib/task/supervisor.ex
lib/elixir/test/elixir/task/supervisor_test.exs

This PR allows you to pass a 1-arity fun as the `supervisor` argument for the `async_stream` functions, which receives the stream entry and should return a supervisor pid/name, which will then be used as the target supervisor for the task which will process the stream entry.
cc: @josevalim @ericmj

Add support for supervisor fun to Task.Supervisor.async_stream

---

lib/elixir/lib/calendar/iso.ex
lib/elixir/test/elixir/calendar_test.exs

Fixes negative microsecond result when calling `DateTime.from_unix/2` with :microsecond unit and a value which is not a multiple of 1_000_000. 
Before changes:
```
iex(1)> DateTime.from_unix!(-1, :microsecond)
#DateTime<1970-01-01 00:00:00.0000-1Z>
```
After changes:
```
iex(1)> DateTime.from_unix!(-1, :microsecond)
#DateTime<1969-12-31 23:59:59.999999Z>
```
This resolves #6589.

Fix negative microsecond result from DateTime.from_unix/2

---

lib/ex_unit/lib/ex_unit/assertions.ex

This code example used variables `one` and `two` that weren't previously initialized, and don't match the assertion result message.

Fix example for ex_unit assertion

---

lib/eex/lib/eex/compiler.ex
lib/eex/test/eex_test.exs

In EEx if we evaluate a string with a middle expression without a start block we Elixir enters in an infinite loop consuming 100% CPU.
Example:
```elixir
EEx.eval_string ~S{
<% if true %>
foo
<% else %>
bar
<% end %>
}
```
This PR Raises an `EEx.SyntaxError` exception in case there is start expression.
it covers issue #6607 .

Raise on EEx with invalid middle expression

---

lib/elixir/src/elixir_tokenizer.erl
lib/elixir/test/erlang/tokenizer_test.erl

I'm not sure if it was intentional but I felt that something is missing after colon in error message here:
```elixir
Erlang/OTP 20 [erts-9.0.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Interactive Elixir (1.5.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> :aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
** (SyntaxError) iex:1: atom length must be less than system limit:
iex(1)>
```
This change makes invalid atom to be shown after the colon:
```elixir
Erlang/OTP 20 [erts-9.0.5] …
```

Improve error message on oversized atom

---

lib/mix/lib/mix/tasks/profile.eprof.ex

Tests for this Mix task [failed on Windows](https://ci.appveyor.com/project/josevalim/elixir/build/1-master+1142) with `(ArithmeticError) bad argument in arithmetic expression`.
I guess the time precision on Windows is not sufficient enough to measure this small execution times.

Mix.Tasks.Profile.Eprof: Protect against division by zero

---

lib/logger/lib/logger.ex

Typo in Logger module documentation

---

lib/elixir/lib/supervisor.ex

All examples leading up to this snippet have used the module name
`Stack`, this updates the snippet to use the same.

Fix typo/reference in Supervisor @moduledoc (v1.5)

---

lib/elixir/lib/protocol.ex
lib/elixir/test/elixir/protocol_test.exs

Example warning:
'Elixir.Collectable':'__protocol__'('impls') -> {'consolidated',[module()]}
; ('consolidated?') -> 'true'
; ('functions') -> [{'into',1},...]
; ('module') -> 'Elixir.Collectable' is a supertype of the success typing: 'Elixir.Collectable':'__protocol__'('consolidated?' | 'functions' | 'impls' | 'module') -> 'Elixir.Collectable' | 'true' | [{'into',1},...] | {'consolidated',['Elixir.BitString' | 'Elixir.File.Stream' | 'Elixir.HashDict' | 'Elixir.HashSet' | 'Elixir.IO.Stream' | 'Elixir.List' | 'Elixir.Map' | 'Elixir.MapSet',...]}
Note that the mismatch is that `module()` is wider than the actual list of consolidated implementations. Since we have this information when consolidating, we can adjust the type spec to prevent this particular warning.
This pull-request also adds a …

Remove underspecification warning for consolidated protocols

---

lib/elixir/lib/port.ex

The explanation used `echo hello` so it would make sense for the example to use the same.

Update Port ### spawn example

---

lib/elixir/lib/regex.ex

Was unsure with the current wording, and the other options have the default documented too!

Clarify that the :trim option defaults to false

---

lib/elixir/lib/access.ex
lib/elixir/test/elixir/access_test.exs

Implements `Access.find/1` and `Access.filter/1`. Examples and documentation provided in the code (aligned with examples and documentation for `Access.at/1`.

Implement Access.filter/1

---

lib/elixir/lib/process.ex

(I hope this doesn't come across as pretentious or pedantic: that's certainly not my intention. I also realize this comes close to bikeshedding territory, but still hope it can be considered an improvement, however minuscule :p )
Improved the error message: the "or" conjuction isn't used that way in English (as it would be in French, for example).
Didn't find a way to keep the list of possibilities as a separate sentence: couldn't lead with "Either" as it is typically used to differentiate between only 2 options.
Finally, leaving the "Oxford comma" properly indicates that the issues is "one of" the presented possibilities.

Improved error msg for process registration

---

lib/ex_unit/lib/ex_unit/server.ex

This PR is an example of what suggested in #6643. The steps I ran were:
1. Chose a file at random with:
```bash
$ bin/elixir scripts/random_file.exs
Checking lib/ex_unit/lib/ex_unit/server.ex... jackpot!
The file above needs formatting.
Please format it with the command below:
bin/elixir bin/mix format lib/ex_unit/lib/ex_unit/server.ex
Once formatted, check for any faults and submit a pull request.
For more information see: https://github.com/elixir-lang/elixir/issues/6643
Have fun!
```
1. Formatted it with `$ bin/elixir bin/mix format lib/ex_unit/lib/ex_unit/server.ex`
1. Adjusted the result manually to make it look good, exactly like described in #6643.

Run the code formatter on ExUnit.Server

---

lib/mix/lib/mix/tasks/deps.ex

I did made one change in the pattern matching on the anonymous function
in `run/1` for readability after the formatter had been run.

Run the code formatter on Mix.Tasks.Deps

---

lib/mix/test/mix/utils_test.exs

I moved the anonymous functions out of `in_fixture()` calls and a long string message out of `flunk()`

Run the code formatter on Mix.UtilsTest

---

lib/mix/lib/mix/tasks/escript.ex

Ran the formatter as in #6643. Inspected the results, but made no manual changes.
```
bin/elixir scripts/random_file.exs
bin/elixir bin/mix format lib/mix/lib/mix/tasks/escript.ex
bin/elixir lib/mix/test/mix/tasks/escript_test.exs
```

ran formatter

---

lib/mix/test/mix/tasks/compile.protocols_test.exs

Not a real big fan of 2 lined asserts.
```
assert mark_as_old!("_build/dev/lib/sample/consolidated/Elixir.Compile.Protocol.beam") !=
@old
```
but left it that way because I saw it in other PRs too.

run code formatter on mix/tasks/compile.protocols_test.exs

---

lib/elixir/lib/enum.ex

There was some confusion in #6759 over exactly what was ordered by group_by
Hopefully this is useful. Let me know if you'd like any wording changes.

Specify group_by values are ordered but map is not

---

lib/mix/test/mix/tasks/clean_test.exs

This PR follows #6643. The randomizing script chose _lib/mix/test/mix/tasks/clean_test.exs_
It's a tad bit small, but it does the trick.
BTW, as an extra:
``
$ ./bin/elixir -v
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.6.0-dev (48beb79) (compiled with OTP 20)
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.3 LTS
Release:        16.04
Codename:       xenial
$ cat /proc/version
**Linux version 4.4.0-43-Microsoft (Microsoft@Microsoft.com) (gcc version 5.4.0 (GCC) ) #1-Microsoft Wed Dec 31 14:42:53 PST 2014**
``
Elixir runs pretty well(except for file access speed) on Ubuntu 16.10 for Windows 10, aka Windows Subsystem for Linux.

Run the code formatter on Mix.Tasks.CleanTest

---

lib/mix/test/mix/tasks/profile.fprof_test.exs

Run formatter on lib/test/mix/tasks/profile.fprof_test.exs

Run formatter on lib/test/mix/tasks/profile.fprof_test.exs

---

lib/elixir/lib/kernel.ex

I started to implement `defimplm` for multiple types, then I found that `defimpl` already can do this, but the functionality is not documented.

Document defimpl for multiple types

---

lib/mix/test/mix/task_test.exs

Formatted with:
```
$ bin/elixir -v
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.6.0-dev (61b662a29) (compiled with OTP 20)
```

Run the code formatter on Mix.TaskTest

---

lib/iex/lib/iex/pry.ex

Ran the formatter.
I was not sure about two decisions:
* The formatting of [this typespec](https://github.com/elixir-lang/elixir/compare/master...fabrik42:exfmt-pry?expand=1#diff-06592ac682e15e56da15969a44f5358eR154)
* I [extracted this tuple](https://github.com/elixir-lang/elixir/compare/master...fabrik42:exfmt-pry?expand=1#diff-06592ac682e15e56da15969a44f5358eR435) to make the function call a single line, but the tuple is within a macro and basically a constant. Does this still make sense? I named the variable according to the param name of the Erlang function.

Run code formatter on lib/iex/lib/iex/pry.ex

---

lib/elixir/lib/file/stream.ex

Formatted with:
```$ bin/elixir -v
Erlang/OTP 20 [erts-9.0] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false]
Elixir 1.6.0-dev (7b8d5ec) (compiled with OTP 20)```

Run the code formatter on File.Stream

---

lib/mix/test/mix/tasks/test_test.exs

Formatting file `lib/mix/test/mix/tasks/test_test.exs` as per #6643.

Run the code formatter on Mix.Tasks.TestTest

---

lib/mix/test/mix/umbrella_test.exs

Formatting file `lib/mix/test/mix/umbrella_test.exs` as per https://github.com/elixir-lang/elixir/issues/6643.
I originally began updating [Mix.UmbrellaTest](https://github.com/elixir-lang/elixir/blob/master/lib/mix/test/mix/umbrella_test.exs) in https://github.com/elixir-lang/elixir/pull/6740 however I prematurely discarded my fork of the so I needed to create a new PR.
I've closed the previous and I'm currently making updates based on @josevalim's feedback.

Run code formatter on Mix.UmbrellaTest

---

lib/elixir/lib/kernel.ex

Ok, I got the Kernel 😰 If this is totally wrong, please let me know.
One thing that I recognized is that the Kernel contains a lot of very long strings with interpolations, used for warnings, error messages, etc.
It seems that three different kind of ways are used to construct this strings:
* [String concatenation](https://github.com/elixir-lang/elixir/compare/master...fabrik42:exfmt-kernel?expand=1#diff-e06d5ebc2907d951188e88476f85af51R4174)
* [Using binary type](https://github.com/elixir-lang/elixir/compare/master...fabrik42:exfmt-kernel?expand=1#diff-e06d5ebc2907d951188e88476f85af51R3413)
* [New lines in interpolation](https://github.com/elixir-lang/elixir/compare/master...fabrik42:exfmt-kernel?expand=1#diff-e06d5ebc2907d951188e88476f85af51R1714)
Would it make sense to try to …

Run code formatter on lib/elixir/lib/kernel.ex

---

lib/elixir/test/elixir/calendar_test.exs

Formatter worked just dandy, but I added a new line before a few pipes then re-ran it. 
I find #2 easier to read, personally, but if you'd prefer #1 then I'll edit and commit it.

Run the formatter on lib/elixir/test/elixir/calendar_test.exs

---

lib/mix/lib/mix/tasks/format.ex
lib/mix/test/mix/tasks/format_test.exs

I messed up `.formatter.exs` configuration, and mistakenly included my HTML template files in the formatting path. The `mix format` task died suddenly on me without a nice error message, giving me:
```
$ mix format lib/ui/templates/layout/no_user.html.slim
** (SyntaxError) nofile:5: syntax error before: http
(elixir) lib/code.ex:329: Code.format_string!/2
(mix) lib/mix/tasks/format.ex:148: Mix.Tasks.Format.format_file/4
(elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
(mix) lib/mix/tasks/format.ex:78: Mix.Tasks.Format.run/1
(mix) lib/mix/task.ex:317: Mix.Task.run_task/3
(mix) lib/mix/cli.ex:68: Mix.CLI.run_task/2
```
this change updates the above error message with important information, like the file path that the error happened on. I also kept the original syntax error …

Better `mix format` error message when it crashes during formatting file

---

lib/mix/lib/mix/tasks/archive.build.ex

1. Ran formatter with `bin/elixir bin/mix format lib/mix/lib/mix/tasks/archive.build.ex`
2. Concatenated strings to avoid multiline raise, according to rules and discussion [outlined here](https://github.com/elixir-lang/elixir/issues/6643#issuecomment-335744731)
3. Moved out multiline function call to a variable

Run code formatter on Mix.Tasks.Archive.Build

---

lib/ex_unit/lib/ex_unit/callbacks.ex

Code formatted according to #6643.

Format ExUnit.Callbacks

---

lib/elixir/lib/calendar/naive_datetime.ex

Runs code formatter on NaiveDateTime

---

lib/mix/lib/mix/utils.ex

Run code formatter on lib/mix/lib/mix/utils.ex

---

lib/mix/lib/mix/tasks/deps.compile.ex

1. I chose a random file with the command
```
$ bin/elixir scripts/random_file.exs
```
The file selected was `lib/mix/lib/mix/tasks/deps.compile.ex`
2. Then I ran the code formatter with
```
bin/elixir bin/mix format lib/mix/lib/mix/tasks/deps.compile.ex
```
3. Once the changes where reviewed and manual changes made where according to #6643
4. Tests where then ran with
```
make test
```

Run formatter on deps.compile

---

lib/logger/test/logger/translator_test.exs

Formatter moved indentation on a lot of lines to align with
capture_log instead of assert.

Run formatter on lib/logger/test/logger/translator_test.exs.

---

lib/elixir/lib/protocol.ex

Some of the changes in this file are quite extreme. In a few places, the formatter has added a lot of extra newlines which has made the code quite different. In my opinion, it is more readable like this but I can see why somebody might disagree.
Any thoughts?

Run the code formatter on Protocol

---

lib/ex_unit/test/ex_unit/capture_io_test.exs

Run the code formatter on ExUnit.CaptureIOTest

---

lib/eex/test/eex/tokenizer_test.exs

Formatter worked great. 
These sorts of expressions feel a bit awkward, but I can't really think of a better way and it's just a test:

Run code formatter on tokenizer_text.exs

---

README.md

The README suggests users after Elixir build passes to go to the Getting Started guide, but it was pointing to the home page. This PR fixes the link.

Fix README.md incorrect link to Getting Started guide

---

lib/ex_unit/lib/ex_unit/assertions.ex
lib/ex_unit/test/ex_unit/assertions_test.exs

This fixes https://github.com/elixir-lang/elixir/issues/6925
When sigils are expanded via `Macro.expand/2` they aren't expanded into
their non-sigil equivalent.
eg:
```
defmodule MinimalMacro do
defmacro sigil_l({:<<>>, _, [string]}, _), do: Code.string_to_quoted!(string, [])
end
iex> Macro.expand((quote do: {a} = 1), nil)
{:=, [], [{:{}, [], [{:a, [], Elixir}]}, 1]}
iex> Macro.expand((quote do: {~l(a)} = 1), nil)
{:=, [], [{:{}, [], [{:sigil_l, [], [{:<<>>, [], ["a"]}, []]}]}, 1]}
```
The `assert` macro uses `Macro.prewalk` to walk the AST of a given
expression using pattern matching to find variables that should be
used as the left side of the match. Because sigils aren't expanded into
their non-sigil equivalent and `assert` doesn't look for the sigil
pattern they aren't collected as …

Collect sigil variables as part of assert matches

---

lib/mix/lib/mix/tasks/format.ex

With the new `mix format -` there is no need to keep the print flag on
the task nor on the docs.

Remove print option from mix format

---

lib/iex/lib/iex/helpers.ex
lib/iex/lib/iex/info.ex
lib/iex/test/iex/helpers_test.exs
lib/iex/test/iex/info_test.exs

We were returning info from the protocol as lists of `{atom, string}` pairs with atoms being "titles" of info (such as "Reference modules"). This is a bit weird and it definitely becomes annoying with the new code formatter because it formats things like `["Description": ...]` as `[Description: ...]` which looks weird.
This PR turns all atom keys into strings so that now info is a list of `{string, string}` tuples.
I'm sure @fishcakez will be much relieved by this PR :).

Stop using keyword lists in IEx.Info

---

lib/mix/lib/mix/tasks/format.ex
lib/mix/test/mix/tasks/format_test.exs

Improve output message when --check-* is passed to mix format with
stdin. And add tests for --check-formated with stdin.
Before when we ran `$ echo 'foo( )' | mix format  - --check-formatted` the output was
```
** (Mix) mix format failed due to --check-formatted.
The following files were not formatted:
* -
```
Now the output will tell on the bullet list that the formatted error came from stdin
```
** (Mix) mix format failed due to --check-formatted.
The following files were not formatted:
* stdin
```

On mix format checks formatted for stdin

---

lib/elixir/lib/system.ex

This is a trivial fix for an outdated reference.

Updating what seems to be outdated documentation.

---

lib/mix/lib/mix/dep.ex
lib/mix/lib/mix/dep/converger.ex
lib/mix/lib/mix/dep/loader.ex
lib/mix/lib/mix/tasks/deps.compile.ex
lib/mix/test/fixtures/rebar_dep/rebar.config.script
lib/mix/test/mix/dep_test.exs
lib/mix/test/mix/rebar_test.exs

This PR is the implementation of [this proposal](https://groups.google.com/forum/#!topic/elixir-lang-core/Lk08Vt0eRR0), which allows defining per dependency env variables to be used when loading or compiling it.
Example:
```elixir
def deps do
{:exometer, "~> 1.2.1", env_vars: [{"EXOMETER_PACKAGES", "(amqp)"}]}
end
```
Will set the `EXOMETER_PACKAGES` env variable to "(amqp)" which will include the amqp dependencies in the `mix.lock` (see: [exometer-dependency-management](https://github.com/Feuerlabs/exometer#dependency-management)). This is a Rebar specific example, but the PR sets the env vars to all types of supported packages.
All the files have been formatted using the new `mix format` task.
I'll be really happy to get feedback to improve this PR and make all the required changes to …

Implement :env_vars option for %Mix.Dep{}

---

lib/mix/lib/mix/compilers/erlang.ex

`do_compile` should always return 4-element tuple. Looks like a minor mistake in https://github.com/elixir-lang/elixir/pull/6598.
On hexpm we are using custom compiler for protobuf [1] and it broke on
Elixir master:
$ mix compile.all --force
Compiling 4 files (.proto)
** (MatchError) no match of right hand side value: {:ok, [], []}
(mix) lib/mix/compilers/erlang.ex:249: Mix.Compilers.Erlang.combine_results/2
(elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
(mix) lib/mix/compilers/erlang.ex:125: Mix.Compilers.Erlang.compile/5
(mix) lib/mix/task.ex:354: Mix.Task.run_alias/3
(mix) lib/mix/task.ex:278: Mix.Task.run/2
(mix) lib/mix/tasks/compile.all.ex:63: Mix.Tasks.Compile.All.run_compiler/2
(mix) lib/mix/tasks/compile.all.ex:47: Mix.Tasks.Compile.All.do_compile/4
(mix) …

Fix handling deprecated return value for Erlang.compile callback

---

lib/elixir/lib/calendar/date_range.ex
lib/elixir/lib/enum.ex
lib/elixir/lib/file/stream.ex
lib/elixir/lib/gen_event/stream.ex
lib/elixir/lib/hash_dict.ex
lib/elixir/lib/hash_set.ex
lib/elixir/lib/io/stream.ex
lib/elixir/lib/kernel.ex
lib/elixir/lib/map_set.ex
lib/elixir/lib/range.ex
lib/elixir/lib/stream.ex
lib/elixir/test/elixir/calendar/date_range_test.exs
lib/elixir/test/elixir/enum_test.exs

We have reimplemented Enum.at/3, Enum.fetch/2, Enum.fetch!/2,
Enum.random/1, Enum.slice/2, and Enum.slice/3 to be more
efficient by using the new protocol function.
This partially implements #6955. We have decided to not replace
`count/1` by an `aggregate/2` callback because it became clear
we cannot implement `min/1` for date ranges since `Enum.min/1`
does a structural comparison. Given ranges are still the only case
that requires custom aggregations, we have decided to inline those
in Enum until we have more evidence that such callback is necessary.

Add Enumerable.slice/1 and use it in Enum

---

lib/elixir/lib/stream.ex

IMHO, it is a bit confusing to shadow the outer `fun` in the first function passed into `:lists.unfoldl`. Maybe we could change it to `f1` to be consistent to the rest of the module?

Make fun in Stream.do_reduce less confusing

---

lib/elixir/lib/module.ex
lib/elixir/src/elixir_erl_compiler.erl
lib/elixir/test/elixir/kernel/warning_test.exs

This PR is still in development.  I am creating this PR for discussion regarding the behaviour lint checks and their corresponding implementations in the compiler.
Add linting checks during Elixir compilation to detect problems arising from misuses with behaviours, and disable such linting checks in *erl_lint* as mentioned in #5800.
More tests can, and will be added.
Modified the `elixir_erl_compiler.erl` file to silence all behaviour related warnings thrown by *er_lint*.  Some tests are expected to fail for now.
Added a function to check if the behaviour is indeed a behaviour.  This function can differentiate between an module without callbacks, and a non existing module.
Not applicable in Elixir, since multiple `@optional_callbacks` are merged together.
To do in a subsequent pull …

Perform some behaviour lint checks in Elixir

---

lib/mix/lib/mix/tasks/compile.xref.ex
lib/mix/lib/mix/tasks/xref.ex
lib/mix/test/mix/tasks/xref_test.exs

Use the file location available in the manifest to display external sources.
Closes #6629

Handle external files for xref callers and warnings

---

lib/mix/lib/mix/tasks/xref.ex
lib/mix/test/mix/tasks/xref_test.exs

As discussed in #6963, `mix xref` did not incorporate umbrella sub-app names in its output due to `IO.write` being used instead of `Mix.shell.info`. This PR fixes that, and also the tests that were using `capture_io`, which does not work with `Mix.Shell.Process`

Use Mix.shell.info over IO.write in Mix xref

---

lib/elixir/lib/enum.ex

Hi all,
this fixes the position of a backtick in an Enum doc.
Cheers!

Fix backtick position in Enum doc

---

lib/elixir/lib/code/formatter.ex
lib/elixir/test/elixir/code_formatter/calls_test.exs

Calls such as `alias Foo.{Bar}` would be formatted when multiline as
```elixir
alias Foo.{
Bar
}
```
Now they're formatted as
```elixir
alias Foo.{
Bar
}
```

Fix formatting of multiline "foo.{...}" calls

---

lib/elixir/src/elixir_tokenizer.erl
lib/elixir/test/elixir/code_test.exs

Addresses #6974 by always catching the `error:badarg` when `Code.string_to_quoted/2` is called with `existing_atoms_only: true`, returning an error tuple in `Code.string_to_quoted/2` and raising a `SyntaxError` in `Code.string_to_quoted!/2`.

Better handling of non existing atoms

---

lib/elixir/lib/module.ex

Erlang is updating their docs regarding HiPE limitations and I think we need to mention that they also apply on Elixir.
Related changes: https://github.com/erlang/otp/pull/1618/files#diff-a0bf0e1ae6adf3eee9a66899aef70923R77

Mention that HiPE-compiled modules won't call `@on_load` callback

---

lib/elixir/lib/calendar/date.ex
lib/elixir/lib/calendar/datetime.ex
lib/elixir/lib/calendar/naive_datetime.ex
lib/elixir/lib/calendar/time.ex

* Add `Date.from_erl!/2` to match `from_erl/2`
* Add `Time.from_iso8601!/2` to match `from_iso8601/2`
* Add `NaiveDateTime.from_erl!/3` to match `from_erl/3`
* Update `DateTime.compare/2` to actually accept `Calendar.datetime()`
* Improve typespecs
---
Ideas for further improvements:
- Loosen up functions from taking `t` to taking `Calendar.naive_datetime()` (and similar), e.g. `NaiveDateTime.to_date` [1], `NaiveDateTime.to_time`, `NaiveDateTime.add`, `DateTime.to_date` etc
- similar to above for `DateTime.from_naive/2`, `NaiveDateTime.new/2`
I don't have a use case for the things above, but seems to improve consistency with other functions.
[1] https://github.com/wojtekmach/elixir/blob/wm-calendar-improvements/lib/elixir/lib/calendar/naive_datetime.ex#L304

Improve calendar functions consistency and typespecs

---

lib/iex/lib/iex/autocomplete.ex
lib/iex/test/iex/autocomplete_test.exs

Related issue : #6999 
Add type autocompletion in IEx when users tries to get the type information from the `t` helper.
Added a clause to match an expression starting with `'t '` in the REPL and send it to type expansion logic.
`t String.<tab>` will show `codepoint/0    grapheme/0     pattern/0      t/0`.
`t String.gra<tab>` will autocomplete to `t String.grapheme`.
`t Str<tab>` will show `Stream      String      StringIO`.
- `t(String.<tab>)` and all its parenthesized alternatives are not supported.  Is this a use case we want to support ?

Add types autocompletion in IEx

---

lib/elixir/docs.exs
lib/elixir/lib/dynamic_supervisor.ex
lib/elixir/lib/exception.ex
lib/elixir/lib/supervisor.ex
lib/elixir/lib/supervisor/default.ex
lib/elixir/test/elixir/dynamic_supervisor_test.exs
lib/elixir/test/elixir/supervisor_test.exs
lib/ex_unit/lib/ex_unit/event_manager.ex

As outlined in #5267.
As @myronmarston mentioned, we need to figure out how we are going to handle the `start_child/2` arguments. He proposed an API that passes a function but that's very likely a no-go because we don't want to allow the user to run custom code inside the supervisor. Instead, I have been thinking about different start_child functions:
* `start_child(supervisor, arg :: term)` - starts a child with a single argument given to start_link. The argument in the child_spec is ignored.
* `start_child_with_arguments(supervisor, args :: [term])` - starts a child the given arguments in `start_link`. The arguments in the child_spec are retained.
* `start_child_with_keywords(supervisor, keyword())` - starts a child by merging the given keywords with the single keyword argument given in …

Add DynamicSupervisor

---

lib/mix/lib/mix.ex

Just a couple of minor edits.
The changes "mix" -> "Mix" are proposed because "Mix" is used consistently to refer to the project. Alternatively, you could write `mix` (fixed-width font) to mean the command-line program, but I chose "Mix" because it seems to follow the existing style.

Minor edits in mix.ex docs

---

lib/elixir/lib/module.ex
lib/elixir/test/elixir/kernel/impl_test.exs

Remove warnings when some of the clauses of a function with defaults don't implement callbacks reported on #6975

Fix @impl warnings with default arguments

---

lib/ex_unit/lib/ex_unit/diff.ex
lib/ex_unit/test/ex_unit/diff_test.exs

Closes #6930
For this:
```elixir
test "1" do
assert ~N[2017-10-01 09:00:00] == ~N[2017-11-02 09:00:00.0]
end
test "2" do
assert MapSet.new([1]) == MapSet.new([1, 2])
end
test "3" do
assert 1..1 == 1..2
end
test "4" do
assert Stream.filter([1, 2, 3], &(&1)) == Stream.take([1, 2, 3], 2)
end
```
Before:
After:

Use inspect in assertion diff for structs if possible

---

lib/elixir/lib/calendar/datetime.ex

Add missing `the` and make the references to UTC and Standard offsets consistent with the other docs.

Update docs for DateTime.compare/2

---

lib/ex_unit/lib/ex_unit/callbacks.ex
lib/ex_unit/lib/ex_unit/case_template.ex

Phoenix's generated `conn_case.ex` uses both `setup` and `using` extensively, so it would be nice to have a clean and more explicit documentation around these two:
- Rearranged the docs so that it's easier to visually scan for `setup` and tried to make it more clear how to update the context for tests,
- Extended the example for `using` to make it more clear what is happening there.

Improve ExUnit documentation with regards to "setup" and "using"

---

lib/elixir/lib/calendar.ex

`Calendar.truncate/2` clamps the precision to a maximum of 3, which would seem to be more clearly expressed by `min(precision, 3)` than the current case statement.  All tests pass.

Simplify Calendar.truncate/2 precision check

---

lib/elixir/lib/file.ex
lib/elixir/test/elixir/file_test.exs

Currently, the documentation makes it sound like `File.exists?` might return `true` for dangling symlinks, but it actually returns `false`.

Clarify File.exists? behavior for dangling symlinks

---

lib/logger/lib/logger/error_handler.ex

Logger.ErrorHandler which basically forwards received event (changing its shape, but this is irrelevant) should always preserve original group leader (gl). It's Logger's handlers (backends) which can do whatever they want with gl, based on their own strategies.
Similarly, suppressing events based on node difference (node(gl) != node()) is too early, IMO. The event had to travel to the event manager (:error_loger), so one hop to the final manager (Logger) is almost at no cost, as both reside in the same  node. So let the backends to decide.

Preserve group leader in Logger.ErrorHandler notification to Logger

---

lib/elixir/src/elixir_erl_pass.erl
lib/elixir/test/elixir/kernel/warning_test.exs

Warnings for unsafe variable on boolean checks stopped working after #7015 because
variables of the right clause are unbound on the left clause.
Fixes #7044

Translate clauses for boolean check

---

lib/elixir/lib/kernel/special_forms.ex

I wasn't sure about the difference btween `<-` and `=` in `with` statements. Writing this example helped me understand the behaviour.
```elixir
one =
with :foo <- :bar do
:success
end
IO.inspect one, label: "one"
two =
with :foo = :bar do
:success
end
IO.inspect two, label: "two"
```
one will output `:bar` because the match fails, while two is never reached because it throws a `MatchError`.
This PR updates the with docs to make this a bit clearer

Explain bare expression behavior in with docs

---

lib/iex/lib/iex/introspection.ex
lib/iex/test/iex/helpers_test.exs

Let the user know that Erlang documentation is currently not available
Closes #7060

Print out the specs of Erlang functions in `h` helper

---

lib/elixir/lib/kernel/special_forms.ex

I was looking for the multi-clause anonymous function syntax, but couldn't find it when i searched for `fn`. I recall that it is documented somewhere else, but this seems like it would help as well.
Happy to change the example, I had a hard time thinking of a simple multi-clause function that wasn't self-referential. Not trying to write a y-combinator as an example :)
🍍🍍🍍🍍🍍🍍

Document multi clause anonymous functions

---

lib/elixir/lib/kernel.ex
lib/elixir/src/elixir_erl_pass.erl
lib/elixir/src/elixir_expand.erl
lib/elixir/test/elixir/kernel_test.exs

Fixes the issue raised on https://github.com/elixir-lang/elixir/pull/7069#issuecomment-347490983
returning environment from the left side to the next expressions on boolean checks (`and`, `or`)

Move boolean checks optimizations to Kernel

---

lib/elixir/lib/code/identifier.ex
lib/elixir/test/elixir/inspect_test.exs

As per #7084, this PR adds the printing of the UTF-8 BOM on inspected strings. I think this is the right behavior, but if anything needs being revisited I'm happy to talk about it.
Closes #7084

show UTF-8 BOM on inspected strings

---

lib/elixir/lib/dynamic_supervisor.ex

Hi Elixir Team.
I found mistake on the document for dynamic supervisor.
I think it will be correct that uses function `DynamicSupervisor.start_child/2` instead of `DynamicSupervisor.start_link/2`.
And an argument of `count_children` should be `sup` instead of `sup_pid`.
Thanks!

Fix the documentation for Dynamic Supervisor

---

lib/elixir/lib/kernel/special_forms.ex

Uncommon:
https://www.google.com/search?q="helps+us+from+running+into"
Uncommon:
https://www.google.com/search?q="helps+prevent+us+from+running+into"
Common and sounds natural:
https://www.google.com/search?q="prevents+us+from+running+into"

Adjust bind_quoted docs for language.

---

lib/mix/lib/mix/dep/fetcher.ex

Hex's SCM.checkout returns package build tools in the lock, store this
information on the Dep struct so that the loader can pass this
information to SCM.managers/1.
Fixes hexpm/hex#468.

Store lock from SCM on Dep

---

lib/mix/lib/mix/compilers/elixir.ex
lib/mix/test/mix/tasks/compile.elixir_test.exs
lib/mix/test/mix/tasks/compile_test.exs

At the beginning of compilation, initial `:source` records of the files that
needs to be compiled are added to an Agent process. These records are then
updated when the files are compiled and then written to the compile manifest.
The `:size` field in the initial record has a default of 0, and since files
without any code (they only have comments or newlines) are not compiled, this
is never updated with the actual size of the file before the compile manifest
is written to disk.
These files are always seen as stale because their size on disk does not match
the compile manifest.
This is fixed by adding the actual size of the file to the initial record.
Closes #7066

Files with only comments are no longer always stale

---

lib/elixir/lib/node.ex

My guess is they are private because they rely on Erlang code/docs?

State argument on Node should be documented.

---

lib/elixir/lib/base.ex
lib/elixir/lib/code/formatter.ex
lib/elixir/lib/enum.ex
lib/elixir/lib/kernel/parallel_compiler.ex
lib/elixir/test/elixir/code_formatter/operators_test.exs
lib/elixir/test/elixir/kernel/quote_test.exs
lib/elixir/test/elixir/stream_test.exs
lib/elixir/test/elixir/task_test.exs
lib/elixir/unicode/graphemes_test.exs
lib/ex_unit/lib/ex_unit/case.ex
lib/ex_unit/lib/ex_unit/doc_test.ex
lib/iex/lib/iex/introspection.ex
lib/mix/lib/mix/tasks/xref.ex

Closes #7102
Please use the :+1: and :-1: reaction accordingly.

Do not indent right-side of pipelines in the formatter

---

lib/mix/lib/mix/generator.ex

Fix documentation for `Mix.Generator.create_file/3`

---

lib/mix/lib/mix/tasks/format.ex
lib/mix/test/mix/tasks/format_test.exs

~I am not sure yet on how to go about testing this, any suggestions are appreciated :).~ Testing is done.
The names of the options have been just decided by me for now so feedback is welcome.
Closes #6644.

Allow "mix format" to read exported configuration from dependencies

---

lib/elixir/lib/enum.ex

While I was fixing another bug I realized the whole Enum module uses `enumerable` to name enumerables, but a few places used `enum`. This patch names all occurrences consistently.

Name enumerable consistently

---

lib/elixir/lib/enum.ex
lib/elixir/lib/stream/reducers.ex
lib/elixir/test/elixir/enum_test.exs

`Stream.chunk_every/4` was giving odd results when step was greater than
count and the last element of the enumerable was the same as last
chunk's last element.
This patch fixes this issue and adds tests for different scenarios when
`step > count`. It also adds a `doctest` example to reflect this in the
documentation and test it simultaneously.
Fixes #7096

Fix Stream.chunk_every/4 odd results when step > count

---

lib/elixir/test/elixir/protocol_test.exs

`Code.get_docs/1` calls `:code.get_object_code/1` with the module and this returns the old binary
instead the consolidated one as discussed in #7117

Improve protocol consolidation tests for docs

---

lib/elixir/lib/module.ex
lib/elixir/lib/protocol.ex
lib/elixir/src/elixir_erl.erl
lib/elixir/src/elixir_module.erl
lib/elixir/test/elixir/kernel/deprecated_test.exs
lib/elixir/test/elixir/module_test.exs
lib/elixir/test/elixir/protocol_test.exs

Add deprecated to `ExDp` beam chunk and to `Module.__info__(:deprecated)` as discussed on #7104

Introduce @deprecated

---

lib/elixir/lib/string.ex

Hi all,
`as this options specifies` → `as this option specifies`.
Cheers!

Fix typo in String doc

---

lib/mix/lib/mix/tasks/format.ex

The atom `:export_locals_without_parens` doesn't actually appear in source - the option is nested inside `:export`

Fix documentation for dependency format import

---

lib/mix/lib/mix/tasks/xref.ex
lib/mix/test/mix/tasks/xref_test.exs

Check deprecated using `__info__` or `ExDp` chunk if the module is not loaded,
it doesn't check local deprecations #7104

[WIP] Check deprecated calls on task xref warnings

---

lib/elixir/lib/inspect/algebra.ex

**Background**: As I was researching more on the different use cases around which one can use `IO.inspect`, I stumbled across this [SO post](https://stackoverflow.com/questions/29566248/elixir-io-inspect-to-not-trim-a-long-list) where they mentioned that in case one uses some of the options provide as part of `Inspect.opts` in the context `IO.inspect`, there was a missing information in the documentation. 
**The use case that had missing documentation**: If we want  `IO.inspect` to not trim a particular list, there wasn't an explicit way mentioned of how to do so in the documentation but the [code here](https://github.com/elixir-lang/elixir/blob/master/lib/elixir/lib/inspect/algebra.ex#L77-L79) seemed to provide the `:infinity` option for `limit`, `printable_limit` and `width` option used …

Explicitly specify limit 'infinity' as an option as part of the options one can take wrt IO.inspect

---

lib/mix/lib/mix/tasks/format.ex

Based on discussion that was started from `hpopp`'s [comment](https://elixirforum.com/t/elixir-v1-6-0-rc-0-released/11064/26?u=eiji) on Elixir forum.

Make options part more clear

---

lib/elixir/lib/supervisor.ex

The correct type for the `:start` key is `{module(), atom(), [term()]}`, not `{module(), function(), [term()]}`.
See issue #7151.

Fix Supervisor.child_spec() type

---

lib/elixir/src/elixir_erl_pass.erl
lib/elixir/test/elixir/map_test.exs

There was a regression introduced in #6347 where `true` was returned as the value of an expression match instead of the right side of the expression. See #7156 for more info.
Fixes #7156

return right side expression value on struct matching

---

lib/elixir/lib/application.ex

Small tweak in the docs of `Application.stop/1`.
The word _when_ in this description seems a bit ambiguous to me, it may suggest _while_ to the reader.
By using _after_ and _has been_, the reader unambiguously understands that stopping the application is something else that somehow has already happened.
[OTP docs](http://erlang.org/doc/design_principles/applications.html) also use "after":
> `stop/1` is called **after** the application has been stopped and is to do any necessary cleaning up.

s/when/after/ in Application.stop/1 docs [ci skip]

---

lib/elixir/lib/string_io.ex
lib/iex/lib/iex/pry.ex

This way we'll no longer see `init/1` callback in docs:
https://hexdocs.pm/elixir/1.6.0-rc.0/StringIO.html#init/1

Add `@impl true` to StringIO & IEx.Pry

---

CHANGELOG.md

Couldn't find it in the Changelog, maybe I'm a bit daft :) But the feature is there and I love it. Thanks :green_heart:
```
tobi@comfy ~/github/benchee $ mix test
.............................................................................................................................................................................................................................................................................................
Finished in 2.3 seconds
102 doctests, 183 tests, 0 failures
```

Changelog: mix test reports doctests separately now

---

lib/elixir/lib/inspect.ex
lib/elixir/test/elixir/inspect_test.exs

Before:
iex> inspect(-1, base: :hex)
"0x-1"
After:
iex> inspect(-1, base: :hex)
"-0x1"
This change also applies to the octal and binary base options.

Fix inspect for non-decimal negative integers

---

lib/ex_unit/lib/ex_unit/assertions.ex
lib/ex_unit/test/ex_unit/assertions_test.exs

Previously if the two values that we were checking were within a given
delta were equal, they would fail if the expected delta was `0`.

Change `assert_in_delta` better handle a delta of 0

---

lib/ex_unit/lib/ex_unit/assertions.ex

In a previous commit I changed the behavior of `assert_in_delta`, but I
forgot to document that change so it's clear to users in the future. I
also made it clear that `refute_in_delta` is exclusive, so folks
shouldn't have questions about that anymore.

Add additional documentation for `assert_in_delta` and `refute_in_delta`

---

lib/elixir/docs.exs

Currently the docs have a large group called "Data & Behaviour". The goal of this PR is to extract "Collections" (lists, sets, etc) and "Enumerables" (such as ranges) into their own group. Feedback is welcome!

Introduce a group for collections

---

lib/elixir/pages/Typespecs.md

A [question on StackOverflow](https://stackoverflow.com/questions/48196624/what-is-the-meaning-of-an-elixir-typespec-with-types-in-parenthesis-separated-by/48196807) brought to light that type unions are not called out anywhere in the docs, so here's a small edit to hopefully shed a little more light on them for newcomers :)

Add type union explanation to typespecs

---

lib/elixir/lib/code/formatter.ex

`defrecord/2` and `defrecordp/2` don’t get parentheses when running the code formatter, but their `/3` versions do, so I’ve added `defrecord/3` and `defrecordp/3` to the list of locals without parens.

Don’t add parens for defrecord/3 and defrecordp/3

---

lib/ex_unit/lib/ex_unit/cli_formatter.ex
lib/ex_unit/test/ex_unit/formatter_test.exs
lib/ex_unit/test/ex_unit_test.exs

This adds yellow highlighting for skipped tests in the ExUnit CLI output. This way, when folks have skipped tests that were only intended to be temporary, they will have less of a chance of accidentally thinking they're "all green" and pushing broken code (that would also pass automated CI/CD tests and break production, which I _may_ have done last week 😜 ).
Here's what the new output will look like with skipped tests.

Highlight skipped tests in yellow

---

lib/elixir/lib/code.ex
lib/elixir/src/elixir.erl
lib/elixir/src/elixir_code_server.erl
lib/elixir/test/elixir/code_test.exs
lib/iex/lib/iex/helpers.ex
lib/mix/lib/mix/cli.ex
lib/mix/lib/mix/project.ex
lib/mix/test/mix/tasks/run_test.exs

Currently there is no way to compile a file without leaving
footprints on the system. Plus, the term load_file/2 is very
confusing as loaded is the notation used by modules.
This commit focuses the whole loaded aspect of files exclusively
on require_file/2 (and renames two functions accordingly) and
introduces compile_file/2 which is semantically simpler than
load_file/2.

Replace Code.load_file/2 by Code.compile_file/2

---

lib/elixir/lib/keyword.ex

Following ex_doc's [#821](https://github.com/elixir-lang/ex_doc/pull/821) discussion...
This is the example provided in [`Keyword`](https://hexdocs.pm/elixir/Keyword.html) docs:
```ex
iex> [{:exit_on_close, true}]
[exit_on_close: true]
```
And because below, `elem(0)` is a string, it is not a `Keyword`. So it remains a list of tuples:
```ex
iex> [{"exit_on_close", true}]
[{"exit_on_close", true}]
```
But the code below, which is currently not documented, is actually a valid keyword syntax, and the string key automatically gets converted to an atom:
```ex
iex> ["key": "value"]
[key: "value"]
```
So I thought it would be nice to document this in the docs. :heart:

Add documentation for string keys in Keyword's colon syntax

---

lib/elixir/pages/Guards.md

Updated Guards.md to be more clear in regard to allowed ops in guard clauses.
I found myself doing a double take on the docs today. The sentence about what boolean ops are not allowed can ran together with the allowed ops.

Updated Guards.md to for clairty on boolean ops

---

lib/elixir/lib/macro.ex
lib/elixir/test/elixir/macro_test.exs

Currently modules created with `Macro.to_string` will warn if rescue and catch because of the ordering. As we now get warnings if `catch` is before `rescue` I have changed the order to be more idiomatic.

Reorder keyword blocks in Macro.to_string

---

lib/elixir/lib/tuple.ex

Tuples were not included into the new "Collections & Enumerables" group, but the first paragraph of the `Tuple` documentation says: `Tuples are ordered collections of elements`.
This pull-request edits the documentation to reflect that tuples are composite data types. This should avoid any confusion about why tuples were not included in the "Collections & Enumerables" group.
These changes were previously suggested [here](https://github.com/elixir-lang/elixir/pull/7185#discussion_r160052646).

Update Tuple doc to express it's a composite type

---

lib/elixir/lib/calendar.ex
lib/elixir/lib/calendar/date.ex
lib/elixir/lib/calendar/datetime.ex
lib/elixir/lib/calendar/iso.ex
lib/elixir/lib/calendar/naive_datetime.ex
lib/elixir/lib/calendar/time.ex
lib/elixir/lib/enum.ex
lib/elixir/lib/exception.ex
lib/elixir/lib/file.ex
lib/elixir/lib/integer.ex
lib/elixir/lib/keyword.ex
lib/elixir/lib/list.ex
lib/elixir/lib/macro.ex
lib/elixir/lib/map.ex
lib/elixir/lib/registry.ex
lib/elixir/lib/stream.ex
lib/elixir/lib/supervisor.ex
lib/elixir/lib/system.ex
lib/ex_unit/lib/ex_unit/callbacks.ex
lib/iex/lib/iex.ex
lib/iex/lib/iex/helpers.ex

I saw [here](https://github.com/elixir-lang/elixir/blob/b9591267dc87f79178a9eba435d4765ed745f55b/lib/elixir/lib/code.ex#L43) that `@since` attributes are being added for new behavior in 1.7, and I
thought it might be helpful to go through the recent changelogs and add
those attributes for some newly introduced functions and macros. My
initial thought was to go back and add them through 1.4, but if it's
helpful to go further back then I'd be happy to do that as well.
Or, if you only want to have these attributes starting with 1.7 that's
cool too!

Add @since attributes for behavior introduced in 1.5

---

Makefile

The path for the common options shared between `elixir` and `iex` was not changed when the `man/Makefile` was merged into the top-level `Makefile`.
Here is an screenshot of the change, "before" (left) and "after" (right):
By the way, I installed Elixir v1.6.0 via Homebrew (Mac OS X) and it does not come with the manpages, is that intended?

Set proper path of common options used in manpages

---

lib/elixir/lib/calendar/date.ex
lib/elixir/lib/calendar/datetime.ex
lib/elixir/lib/calendar/naive_datetime.ex
lib/elixir/lib/calendar/time.ex
lib/elixir/lib/enum.ex
lib/elixir/lib/float.ex
lib/elixir/lib/inspect/algebra.ex
lib/elixir/lib/integer.ex
lib/elixir/lib/list.ex
lib/elixir/lib/regex.ex
lib/elixir/lib/registry.ex
lib/elixir/lib/stream.ex
lib/elixir/lib/task.ex
lib/elixir/lib/task/supervisor.ex
lib/iex/lib/iex/helpers.ex
lib/mix/lib/mix/project.ex

This adds the `@since` attribute, documenting what new functions were
added in the 1.4 release.

Add `@since` documentation for 1.4 release

---

lib/elixir/lib/kernel/special_forms.ex

The code snippet in the section "Catching values of any kind" of the documentation of `try` had wrong indentation, because of that the snippet was wrongly formatted.
Before:
After:

Fix example of "Catching values of any kind"

---

lib/elixir/lib/float.ex

While going through and adding the `@since` attributes, I notice that
this function was missing a typespec, so I figured I'd add it.
I went with `{pos_integer, pos_integer} | {neg_integer, pos_integer}`
as the return type instead of `{integer, pos_integer}` to make it clear
that we would never have a numerator of 0.

Add typespec for Float.ratio/1

---

lib/iex/test/iex/helpers_test.exs

If you build your otp version from sources you won't have stdlib path such as `"lib/stdlib-#{vsn}/src/"` but `"lib/stdlib/src/"`. In this case tests on development environment fails.
By using `{:code.lib_dir(:stdlib, :src)}` instead, you can get absolute path to the stdlib library so this solution is transparent for dev/release version.

Change stdlib path to transparent for release/dev version

---

lib/ex_unit/lib/ex_unit.ex
lib/ex_unit/lib/ex_unit/cli_formatter.ex
lib/ex_unit/lib/ex_unit/filters.ex
lib/ex_unit/lib/ex_unit/runner.ex
lib/ex_unit/lib/ex_unit/runner_stats.ex
lib/ex_unit/test/ex_unit/filters_test.exs
lib/ex_unit/test/ex_unit/register_test.exs
lib/ex_unit/test/ex_unit_test.exs

I updated the tests with the new behavior that we're expecting by
excluding tests instead of skipping them. If any of this seems off, let
me know! It makes sense to me, but it's always good to get feedback
before I get too deep in the weeds.

Update tests with new exclude/skipped behavior

---

lib/elixir/lib/file.ex

I noticed a few typespecs were missing for public functions in the
`File` module, so I went ahead and added them.

Add missing typespecs to `File` module

---

lib/elixir/pages/Writing Documentation.md

The previous example wasn't changing the name because `map` was inferred so I was confused about how this feature is supposed to work.

Illustrate specifying function argument names in Writing Documentation docs

---

lib/elixir/lib/calendar/iso.ex

I noticed that some public functions in the Calendar.ISO module
were missing typespecs, documentation and examples of use, so I added
them.

Add missing documentation, examples and specs to Calendar.ISO

---

lib/elixir/lib/io/ansi/docs.ex

I tried to create a type for `options` and to move the documentation
around which options are available up to a typedoc so that was clear
that this is a known type for this module, but it ended up seeming more
complicated than it was worth, so I went with the more general type of
`keyword` instead.
I also did a small optimization of making the default options a module
attribute since that keyword list is a constant, so there's no need to
allocate a new keyword list every time that function is called.

Add missing typespecs and fix error in docs

---

lib/mix/lib/mix/tasks/run.ex

Fix typo in mix documentation

---

lib/iex/lib/iex/introspection.ex
lib/iex/test/iex/helpers_test.exs

This is an attempt of solving #7267.
Output:
```
iex(1) b GenServer
@callback code_change(old_vsn, state :: term(), extra :: term()) ::
{:ok, new_state :: term()}
| {:error, reason :: term()}
| {:down, term()}
when old_vsn: term()
@callback format_status(reason, pdict_and_state :: list()) :: term()
when reason: :normal | :terminate
@callback handle_call(request :: term(), from(), state :: term()) ::
{:reply, reply, new_state}
| {:reply, reply, new_state, timeout() | :hibernate}
| {:noreply, new_state}
| {:noreply, new_state, timeout() | :hibernate}
| {:stop, reason, reply, new_state}
| {:stop, reason, new_state}
when reply: term(), new_state: term(), reason: term()
@callback handle_cast(request :: term(), state :: term()) ::
{:noreply, new_state}
| {:noreply, new_state, timeout() | …
```

Add optional callbacks to IEx.Introspection.b/1 output

---

lib/elixir/src/elixir_expand.erl
lib/elixir/test/elixir/kernel/warning_test.exs

People are frequently confused about results of comparison of structs. This is frequently experienced with calendar structs. This PR tries to catch common erroneous expressions in the compiler and issue warnings at compile-time.

Warn about comparison with calendar structs

---

lib/elixir/lib/application.ex

This PR defines the `prep_stop/1` optional callback for application callback modules. See the [original Erlang/OTP documentation](http://erlang.org/doc/apps/kernel/application.html#Module:prep_stop-1). As of this writing, the application master invokes that callback [here](https://github.com/erlang/otp/blob/1fe1c9a57d365c8203cb1380e4bdfe8f7f6ab8ce/lib/kernel/src/application_master.erl#L377).
In some places, the wording is deliberately a bit vague in identifying applications with application callback modules, to be coherent with the existing style (an application is a broader concept and may not have a callback module associated, you know).
The patch also complements the description of the argument of `stop/1` when `start/2` does not return a state.
The description mentions `kernel` in …

Defines the prep_stop/1 optional callback for applications

---

lib/elixir/lib/port.ex

This is needed to background the processing being run so that control
could move on to the read loop.

Add missing & in port zombie script

---

lib/mix/lib/mix/tasks/compile.erlang.ex

Erlang recognizes both -behaviour and -behavior, but mix was only able to
process one, which made erlang compiler complain about missing behaviour
when source file was using the other one

Teach Mix erlang compiler alternative spelling for -behavior declaration

---

lib/elixir/lib/calendar/date.ex
lib/elixir/lib/calendar/datetime.ex
lib/elixir/lib/calendar/naive_datetime.ex
lib/elixir/lib/calendar/time.ex

* Fastlane structs already in the ISO calendar
* crash with `FunctionClauseError` on bad format. This should actually improve the error message in dev and test given exception blaming. Previously the "bad format" argument error would be also raised when the function was given not a calendar struct (but, for example an erlang style tuple) - very confusing!

Unify *.to_iso8601 functions for calendar types

---

lib/mix/lib/mix/tasks/test.ex

Fix for issue #7294 
`mix test` raise a error if the only option is used and the excluded and total number of tests is equal

Mix test with only option raise a error if no tests matched

---

lib/elixir/lib/dynamic_supervisor.ex

The example makes it appear like the arguments to `def start_child`: `foo, bar, baz` are being ignored by the line `spec = MyWorker`. I *think* this would be the correct way to delegate the module and arguments to `DynamicSupervisor.start_child` in the implied case that MyWorker is using the new child specs. If not, I'd be curious about the preferred approach.

Update doc for DynamicSupervisor.start_child

---

lib/elixir/src/elixir_def.erl
lib/elixir/src/elixir_expand.erl
lib/elixir/test/elixir/kernel/errors_test.exs

I tried using the `contextual_vars` introduced along with `__STACKTRACE__` to give better error messages for `__CALLER__`. I think, I have the consumption part ready, but I can't really understand where I would set it, that the variable is available.
Any tips welcome.

Use contextual vars for __CALLER__

---

lib/elixir/lib/stream.ex

Before this change providing non-number produces harder to understand error "bad argument in arithmetic expression" like this:
```
[1,2,3] |> Stream.drop(nil) |> Enum.to_list
** (ArithmeticError) bad argument in arithmetic expression
(elixir) lib/stream.ex:293: anonymous fn/3 in Stream.drop/2
(elixir) lib/enum.ex:3161: Enumerable.List.reduce/3
(elixir) lib/stream.ex:1433: Enumerable.Stream.do_each/4
(elixir) lib/enum.ex:1823: Enum.reverse/1
(elixir) lib/enum.ex:2581: Enum.to_list/1
```
And floating point numbers give results like this:
```
[1,2,3] |> Stream.drop(1.1) |> Enum.to_list
[3]
```
All other similar functions that I've checked have these guards (i.e. Enum.drop, Stream.take).

is_integer guard for `n` argument in Stream.drop/2

---

lib/elixir/lib/string.ex

The guard clauses of [_String.slice/3_](https://github.com/elixir-lang/elixir/blob/e9dfa50c74488000d2c9de71e926cdd78609b3ac/lib/elixir/lib/string.ex#L1739) exclude negative numbers for the _length_ argument. The function’s spec does not agree, specifying it as `integer` rather than `non_neg_integer`.

Conform the spec for String.slice/3 to its guard clauses

---

lib/ex_unit/lib/ex_unit/manifest.ex
lib/ex_unit/lib/ex_unit/runner_stats.ex
lib/ex_unit/test/ex_unit/manifest_test.exs
lib/ex_unit/test/ex_unit/runner_stats_test.exs
lib/ex_unit/test/test_helper.exs
lib/mix/lib/mix/tasks/test.ex
lib/mix/test/mix/tasks/test_test.exs

This will support filtering tests to just ones that failed the last time they ran.
Background to this is in the [elixir-lang-core discussion](https://groups.google.com/forum/#!topic/elixir-lang-core/_jbuzf4UvA4).

Store the last_run_status of each test in a manifest

---

lib/mix/lib/mix/shell.ex

It was not brought back when Mix.Shell.cmd/3 was "undeprecated" in b2e5b69.
This broke couple projects including test suite of mariaex.

Bring back Mix.Shell.cmd/2

---

lib/elixir/lib/calendar/date.ex
lib/elixir/lib/calendar/datetime.ex
lib/elixir/lib/calendar/iso.ex
lib/elixir/lib/calendar/naive_datetime.ex
lib/elixir/test/elixir/calendar_test.exs

Support negative dates in Calendar

---

lib/ex_unit/lib/ex_unit/callbacks.ex

The change refines and extends the documentation for the ExUnit
callbacks for test setup, `setup` and `setup_all`.
* refer to the introductory Context section in function documentation
* name various ways to define setup code using atom naming unary
function, list of atoms naming unary functions and block.
* clarify that multiple setup callbacks can be used
* reduce two overly similar paragraphs about return values into a
single one

Improve documentation for ExUnit.Callbacks

---

lib/elixir/src/elixir_tokenizer.erl
lib/elixir/test/elixir/kernel/warning_test.exs
lib/elixir/test/erlang/tokenizer_test.erl

First approach at closing #7342. I am not sure the error message is the best. Let me know what you think :)

Prevent operators with many of same char to have same char after them

---

lib/iex/test/iex/helpers_test.exs

Closes #7348.
Some installations delete the Erlang source after installing Erlang. This PR only tests the `open/1` helper on Erlang source files when the Erlang source files are present.
I have checked with @xadhoom and he reported tests pass on this branch.

Only test the open/1 IEx helper on Erlang source if it exists

---

lib/elixir/pages/Syntax Reference.md
lib/elixir/pages/Typespecs.md
lib/elixir/pages/Unicode Syntax.md

I was having fun with Elixir, reading some docs and my IDE alerted me about some typos.
I hope this helps :-)

Fix typos in 'Syntax Reference.md', 'Typespecs.md' and 'Unicode Syntax.md'

---

lib/elixir/lib/macro.ex

Hi all,
`as follow` → `as follows` in Macro docs.
Cheers!

Fix typo in Macro docs

---

bin/elixir

This check was added when Elixir itself was used as a release
but that's not the case anymore.

Remove unecessery releases directory check

---

lib/elixir/lib/port.ex

The `Port.open/2` signature does not match its description in the docs. It also doesn't adhere to Elixir naming conventions.

Fix Port.open/2 signature

---

lib/mix/lib/mix/tasks/run.ex

Some edits I did while reading this file. The main proposed changes are:
* The opening sentence said that applications "start and run". Applications can just be "started", really. The command allows the user to "run" _additional code_ if they wish.
* I found mixing configuration with `System.argv/0` a bit confusing. I believe the docs have to state 
simply that the _command-line arguments_ for the script or expression are available in `System.argv/0`, whatever they are.
* The `-e` example had a `start/0` call. Given that all applications are started by default, didn't find this example very realistic. The patch has a more generic function call instead.

Revises the docs of Mix.Tasks.Run

---

lib/elixir/lib/module.ex
lib/elixir/test/elixir/kernel/typespec_test.exs

@josevalim as discussed in #7363 will close it in favour of this one.

typespec declarations should return :ok like other attributes

---

lib/elixir/lib/dynamic_supervisor.ex
lib/elixir/test/elixir/dynamic_supervisor_test.exs

Fixes #7369 where a DynamicSupervisor using `extra_arguments` crashed when children were restarted.

Fix DynamicSupervisor handling of extra arguments on child restart (fixes #7369)

---

lib/elixir/lib/dynamic_supervisor.ex
lib/logger/test/logger/translator_test.exs

As discussed in #7371, this PR Includes the `extra_arguments` in the error logging when restarting the child of a DynamicSupervisor.

Fix DynamicSupervisor error report when restarting child

---

lib/elixir/lib/gen_server.ex

In GenServer documentation, in the first example description the arity of the start_link does not match the one used in the example

updated "start_link" function arity in the example description

---

lib/elixir/lib/module.ex
lib/elixir/test/elixir/kernel/docs_test.exs

Moving the `init/1` callback before the actual `init/1` function seems to fix the issue at #7382 for this specific case, but we think there's a bigger issue going on here.
We tried to track this down, and we got to the following:
- with the current code on master:
```elixir
Code.get_docs(DynamicSupervisor, :docs) #=> [
...
{{:init, 1}, 449, :def, [{:options, [], nil}], false},
...
]
```
- after changing the order of the functions:
```elixir
Code.get_docs(DynamicSupervisor, :docs) #=> [
...
{{:init, 1}, 452, :def, [{:options, [], nil}], "Receives a set of options that initializes a dynamic supervisor.\n\nThis is typically invoked at the end of the `c:init/1` callback of\nmodule-based supervisors. See the sections \"Module-based supervisors\"\nin the module documentation for more …
```

Fix loading of DynamicSupervisor.init/1 docs

---

lib/iex/lib/iex/helpers.ex
lib/iex/lib/iex/introspection.ex

As noted in #7381, helper methods currently don't take into account required functions. Since you're able to call the functions directly if the module has been required, ideally you should also able to invoke helpers on functions of required modules. This PR addresses this issue.
The following should now work:
```elixir
Erlang/OTP 20 [erts-9.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Interactive Elixir (1.7.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> h take
No documentation for Kernel.take was found
iex(2)> import Enum
Enum
iex(3)> h take
def take(enumerable, amount)
@spec take(t(), integer()) :: list()
Takes the first amount items from the enumerable.
If a negative amount is given, the amount of last values will …
```

pass through __CALLER__ context into IEx.Introspection.decompose

---

lib/ex_unit/lib/ex_unit/case.ex

I was attempting to use a `@moduletag` tag in a test module today, and
I kept getting odd behavior, including this compilation error:
```
== Compilation error in file test/benchee/memory_measure_test.exs ==
** (Protocol.UndefinedError) protocol Enumerable not implemented for :memory_measurement. This protocol is implemented for: Date.Range, File.Stream, Function, GenEvent.Stream, HashDict, HashSet, IO.Stream, List, Map, MapSet, Range, Stream
(elixir) lib/enum.ex:1: Enumerable.impl_for!/1
(elixir) lib/enum.ex:141: Enumerable.reduce/3
(elixir) lib/enum.ex:1919: Enum.reverse/1
(ex_unit) lib/ex_unit/case.ex:534: ExUnit.Case.normalize_tags/1
(ex_unit) lib/ex_unit/case.ex:466: ExUnit.Case.register_test/4
test/benchee/memory_measure_test.exs:11: (module)
(stdlib) erl_eval.erl:670: …
```

Add additional documentation about `@moduletag`s

---

lib/elixir/lib/io/ansi.ex
lib/elixir/test/elixir/io/ansi_test.exs

I added the cursor movement escape codes (from https://www.tldp.org/HOWTO/Bash-Prompt-HOWTO/x361.html) to `IO.ANSI`

Add cursor movement to IO.ANSI

---

lib/elixir/test/elixir/kernel/macros_test.exs
lib/elixir/test/elixir/macro_test.exs

This isn't a really big deal, but it was a little surprising to me that the doctest specification for the Macro module wasn't in the test file for the Macro module. Unless the decision to put it where it is, it might lower friction slightly to move it to the Macro module test file.
Thoughts?

Move `doctest Macro` to Macro module test file

---

lib/elixir/lib/macro.ex

Today I realized I couldn't remember the difference in Macro.escape/2 and Kernel.quote/2. The documented examples weren't quite enough to illustrate the difference as the results are the same from both.
Extend documentation for Macro.escape/2 to illustrate the key difference in it from Kernel.quote/2. Namely: when working on a variable, Macro.escape/2 operates on the _value_.

Extend Macro.escape/2 docs to illustrate difference from quote/2

---

lib/elixir/lib/io/ansi/docs.ex
lib/elixir/test/elixir/io/ansi/docs_test.exs

Before:
```
~>  | Translation
~> 2.0.0 | >= 2.0.0 and < 2.1.0
~> 2.1.2 | >= 2.1.2 and < 2.2.0
~> 2.1.3-dev | >= 2.1.3-dev and < 2.2.0
~> 2.0 | >= 2.0.0 and < 3.0.0
~> 2.1 | >= 2.1.0 and < 3.0.0
```
After:
```
~>           | Translation
~> 2.0.0     | >= 2.0.0 and < 2.1.0
~> 2.1.2     | >= 2.1.2 and < 2.2.0
~> 2.1.3-dev | >= 2.1.3-dev and < 2.2.0
~> 2.0       | >= 2.0.0 and < 3.0.0
~> 2.1       | >= 2.1.0 and < 3.0.0
```

Fix table column alignment with ANSI escapes

---

lib/elixir/lib/calendar.ex
lib/elixir/lib/calendar/date.ex
lib/elixir/lib/calendar/iso.ex
lib/elixir/test/elixir/fixtures/calendar/holocene.exs

Not all calendars have a constant 12 months in
a year.  This function returns the number of
months for a given year. Calendar.ISO will return
12 for all years.

Add calendar callback months_in_year/1

---

lib/mix/lib/mix.ex
lib/mix/lib/mix/project.ex
lib/mix/lib/mix/tasks/compile.ex
lib/mix/test/mix/tasks/compile_test.exs

How it would be called from rebar3:
```
cd deps/my_dep && \
MIX_BUILD_PATH=../../_build/default MIX_ENV=prod mix compile --no-deps-check --no-consolidate-protocol --erl-config mix.config
{my_dep, [{key, value}]}.
Enum.each(Protocol.extract_protocols(paths), fn protocol ->
Enum.each(Protocol.extract_impls(protocol, paths), fn impls ->
:code.purge(protocol)
:code.delete(protocol)
{:ok, beam} = Protocol.consolidate(protocol, impls)
File.write!(Path.join(output, "#{protocol}.beam"), beam)
end)
end)
```

Support compiling from other build tools

---

lib/logger/lib/logger.ex

Today the Logger includes the full path to the source file in the `:file` metadata. With this PR, we use the relative path if the application is available, as that is enough to uniquely identify the path and it helps normalize and reduce the size of the metadata.
For example, before this patch, it would report:
application=interpret_logger_call file=/Users/jose/OSS/interpret_logger_call/lib/interpret_logger_call.ex
and now it reports:
application=interpret_logger_call file=lib/interpret_logger_call.ex

Use relative paths for logger file when application is available

---

lib/elixir/src/elixir_erl.erl
lib/elixir/test/elixir/kernel/typespec_test.exs

Part of https://github.com/elixir-lang/elixir/issues/5800.
@josevalim if we want to keep the shape of the `erl_lint` error (`{behaviour_info, {M, F, A}}`), then I don't think we can give more information than that and so we can't say `@callback` or `@macrocallback` with certainty, that's why I went with `@callback/@macrocallback` in the error message.

Add a "erl_lint" check for behaviour_info/1 plus callback attributes

---

lib/elixir/lib/kernel/parallel_compiler.ex

The `:timed_out` message was not cancelled properly when compilation failed in ParallelCompiler. This meant the timeout message would be delivered even after compilation completed. This could be problematic when invoking compilation programmatically via e.g. `Mix.Task.run("compile", ["--return-errors"])` since it means that the calling process, depending on the implemenation, might crash unexpectedly or get its inbox filled with messages.
The fix simply calls the `cancel_waiting_timer` when a compilation error has ocurred in the same way it is called in other similar cases.
This fixes issue #7428

Properly cancel timeout on compilation error in ParallelCompiler #7428

---

lib/ex_unit/lib/ex_unit/case.ex

Addresses #7423 
The original issue mentions only `@moduletag` but I found it happens with `@tag` as well.

ExUnit raise error for @moduletag and @tag when set before 'use ExUnit.Case'

---

lib/elixir/src/elixir_erl.erl

This is part of https://github.com/elixir-lang/elixir/issues/5800. I implemented the check that checks that a `@spec` attribute is for a function/macro that is actually defined.
@josevalim this implementation might be very naive but it works for simple cases and for the tests that I did. I don't know how this is related to https://github.com/elixir-lang/elixir/blob/7bc0df82fa1c79063ce36d29a2bed90bfb71a7eb/lib/elixir/src/elixir_erl_compiler.erl#L82-L83, I can't see where `{spec_fun_undefined, {M, F, A}}` (with a module, not just `{F, A}`) is used or raised. Let me know how this looks 💟

Implement check for @spec attributes for undefined functions

---

lib/mix/lib/mix/tasks/compile.app.ex

Title says it all!
I have added a few more details than in the [Erlang docs](http://erlang.org/doc/man/app.html). In particular, the termination reason is documented, and the description addresses library applications explictly.
I have seen, by the way, that for library applications `:application.which_applications()` reports them as being started regardless of `:maxT`. That is, library applications with `:maxT` are not actually stopped.

Documents :maxT in compile.app

---

lib/mix/lib/mix/tasks/compile.app.ex

The current description of `:extra_applications` says
> a list of Erlang/Elixir applications that you want started before your application
but from that information the reader is not able to understand how are they different from what you put in `deps/0`, since for example Cowboy is an Erlang application you might want started before your application, so it fits the definition, but it does not go there typically.
The patch is just a proposal (as any patch 😄), because the emphasis depends on what the core team wants to transmit. It tries to reword the description in a way that respects how it technically works today, but I don't really know if custom code paths are a use case intentionally supported, or just an accident of the implementation.
Another option could be that you want to …

Revises the description of :extra_applications

---

lib/mix/lib/mix/tasks/profile.cprof.ex
lib/mix/lib/mix/tasks/profile.eprof.ex
lib/mix/lib/mix/tasks/profile.fprof.ex

I didn't change how options are handled, so they are expected to be strings. Should it be amended, so that they can be passed as actual terms?

Document how to programatically run profiling tasks

---

lib/mix/lib/mix/tasks/format.ex
lib/mix/test/mix/tasks/format_test.exs

Someone recently filed an issue on ElixirLS pointing out that it hasn't kept up with the available options in `.formatter.exs`: https://github.com/JakeBecker/elixir-ls/issues/67 .  I had been loading them from `.formatter.exs` manually, but now that it supports having different config files in subdirectories and importing from dependencies, adding that functionality would increase code duplication more than I would like. I'd also like to have a more future-proof way to do it. The Language Server Protocol has the server respond to the format request with the changed file contents rather than changing the file on-disk, so simply running `mix format` on the file isn't ideal.
I took a quick stab at adding a function that exports the options to be used for a particular file. It doesn't change …

Add function to Mix.Tasks.Format that returns options to be used for a given file

---

lib/mix/lib/mix/utils.ex
lib/mix/test/mix/utils_test.exs

Mix.Utils.stale? will crash if the target list is empty.  This can
easily happen if Path.wildcard() is used to generate it.

Mix.Utils.stale?: Add support for empty target list

---

lib/elixir/lib/registry.ex
lib/elixir/test/elixir/registry_test.exs

Hello everyone,
I'd like to propose a new feature for the `Registry` module. Namely the `count/1` function that returns the number of registered keys in a `Registry`.
It works for both `:unique` and `:duplicate` registries (and the code is the same for both :) )
Do I need to propose this feature in the Mailing List or is if fine to provide it as a PR?
Thanks for making Elixir such a great and approachable language ❤️

Add the ability to count the number of keys in a Registry

---

lib/elixir/lib/string_io.ex

Similar to the way you can pass a function to `File.open` this change allows you to pass a function to `StringIO.open`.  The function will receive the `StringIO` device as a parameter and when the function completes the device will be closed automatically.  The function may be passed in lieu of options to `StringIO.open/2` and a new `StringIO.open/3` function is available should you wish to pass both options and a function.
Examples are included in doc tests.
Please offer feedback or suggestions.  Reviewers should pay particular attention to `@spec` declarations as they are an area of weakness for me.

Pass a function StringIO.open to allow the device to be closed automatically

---

lib/elixir/src/elixir_tokenizer.erl

Small optimization skipping the `handle_terminator` function for commas since they don't require terminators.
I'm not sure if this makes sense, feel free to close it if doesn't.

Optimize tokenizer for commas

---

lib/logger/lib/logger.ex

75% of 500 should be 225 instead of 250 🙂

Fix small math error in error_logger config option

---

lib/elixir/lib/function.ex
lib/elixir/src/elixir_module.erl
lib/elixir/src/elixir_rewrite.erl
lib/elixir/test/elixir/function_test.exs
lib/logger/lib/logger.ex

Reason to add it is capturing functions(#7500) when passing in module name,
function name and arity using variables, because the capture operator
can't handle them.
Done by delegating to `:erlang.make_fun(mod, f, arity)`, also exposed
some erlang functions for getting information for a function and removing
:"Elixir.Function" from the reserved modules.
Added docs for capture/3, info1/ and info/2.
Also added some tests.

Add Function module for introspecting functions.

---

lib/mix/lib/mix/tasks/format.ex

It wasn't immediately obvious to me how the `.formatter.exs` file would look. I probably shouldn't have read the documentation more closely, but I really wanted/expected to see an example. The example I added is from https://hashrocket.com/blog/posts/format-your-elixir-code-now, which seems like a reasonable default.
What do you think?

Add example .formatter.exs for lazy folks

---

lib/elixir/lib/kernel.ex
lib/elixir/src/elixir_rewrite.erl

Saw that it wasn't inlined and asked Jose about it.

Inline `&Kernel.function_exported?/3`

---

lib/elixir/src/elixir_clauses.erl
lib/elixir/test/elixir/kernel/warning_test.exs

Some Elixir users check if the list is not
empty by using the length function. It's not the optimal solution since it has to transverse the whole
list. Now we're warning the users and suggesting them
to use `!= []`.
Apply https://github.com/elixir-lang/elixir/issues/7513 enhancement.

Warn users that uses length to check if list is not empty on guards

---

lib/elixir/pages/Library Guidelines.md

Noticed the "if you a `GenServer`..." fragment when reading the Library Guidelines doc

Fix typo in library guidelines

---

lib/elixir/lib/gen_server.ex
lib/elixir/lib/supervisor.ex

Title says it all :).
Since I was on it, the patch also deletes the paragraph that repeates the default values of `:max_restarts` and `:max_seconds`, and revises the capitalization of the section title "Name registration" to match the existing convention.

Documents the :name option of start_link/2 [ci skip]

---

lib/elixir/src/elixir_tokenizer.erl
lib/elixir/test/erlang/tokenizer_test.erl

This PR fixes cases where `:elixir_tokenizer` does not account for sigil modifiers when determining the column for the next token.
The tokens for
```elixir
~r/foo/ == bar
```
and
```elixir
~r/foo/iu == bar
```
are identical:
```elixir
iex(1)> :elixir_tokenizer.tokenize('~r/foo/ == bar', 1, [])
{:ok,
[
{:sigil, {1, 1, nil}, 114, ["foo"], [], "/"},
{:comp_op, {1, 9, nil}, :==},
{:identifier, {1, 12, nil}, :bar}
]}
iex(2)> :elixir_tokenizer.tokenize('~r/foo/iu == bar', 1, [])
{:ok,
[
{:sigil, {1, 1, nil}, 114, ["foo"], 'iu', "/"},
{:comp_op, {1, 9, nil}, :==},
{:identifier, {1, 12, nil}, :bar}
]}
```
IMHO the column information should have changed after we added the two modifiers:
```elixir
iex(1)> :elixir_tokenizer.tokenize('~r/foo/iu == bar', 1, [])
{:ok,
[
{:sigil, {1, 1, nil}, 114, …
```

Fix column in :elixir_tokenizer for sigils with modifiers

---

lib/logger/lib/logger.ex
lib/logger/test/logger_test.exs

Fix for #7532 
Add missing option `:discard_threshold` and unit test to test the correct implementation of `configure` for valid options

Add missing discard_threshold option to Logger configuration

---

lib/logger/lib/logger.ex
lib/logger/test/logger_test.exs

Addtional fix for #7532. Discussed in #7536. 
After my fix for the option :discard_threshold in PR #7533 another missing option `:translator_inspect_opts` was reported. This option is documented but not configurable with `Logger.configure/1`.
This PR adds makes it configurable with `Logger.configure/1`.

Add missing translator_inspect_opts option to Logger configuration

---

lib/mix/lib/mix/tasks/compile.ex
lib/mix/test/mix/tasks/compile_test.exs

This PR aims to solve the issue #7531, the problem is Mix.Task.run("compile.all", args) returns a empty list when project path is wrong. 
```
def project do
[
app: :apps_path_bug,
apps_path: "this_path_does_not_exist_or_is_empty"
]
end
```

Fix mix compile error when there is a wrong project path.

---

lib/elixir/lib/agent/server.ex
lib/elixir/lib/exception.ex
lib/elixir/lib/inspect.ex
lib/elixir/lib/kernel.ex
lib/elixir/lib/macro.ex
lib/elixir/lib/regex.ex
lib/elixir/lib/task/supervised.ex
lib/elixir/test/elixir/task/supervisor_test.exs
lib/elixir/test/elixir/task_test.exs
lib/iex/lib/iex/info.ex

After having `Function` module might as well make the internal code use it.
* change elixir code to use `Function.fun_info`
* point function type to this module now
Feel free to close this PR if you feel those changes are unnecessary!
Should I change the docs in kernel to reflect that the module is for normal functions too?
More forgotten stuff... :sweat_smile:

Use function module

---

lib/mix/lib/mix/utils.ex

Fix for #7522
Sets the option for `:httpc` to use `:inet6fb4` as `ipfamily` which first tries ipv6 and if that does not works falls back to ipv6.
Testing-Domain with IPv4 only: https://v4-wp123.webpack.hosteurope.de
Testing-Domain with IPv6 only: https://v6-wp123.webpack.hosteurope.de
Function: `Mix.Utils.read_path/1`
Result IPv4 before Fix: `{:remote, "httpc request failed with: {:bad_status_code, 403}"}`
Result IPv6 before Fix: `{:remote, "httpc request failed with: {:failed_connect, [{:to_address, {'v6-wp123.webpack.hosteurope.de', 80}}, {:inet, [:inet], :nxdomain}]}"}`
Result IPv4 after Fix: `{:remote, "httpc request failed with: {:bad_status_code, 403}"}`
Result IPv6 before Fix: `{:remote, "httpc request failed with: {:bad_status_code, 403}"}`

Configure Mix.Utils.read_path to use ipv6 with auto fallback to ipv4 

---

lib/elixir/src/elixir_expand.erl
lib/elixir/test/elixir/kernel/expansion_test.exs

Fix illegal pattern error in Erlang:
```
iex(1)> [1 | 2] ++ [3] = [1, 2, 3]
** (ErlangError) Erlang error: {:illegal_pattern, {:op, 1, :++, {:cons, 0, {:integer, 0, 1}, {:integer, 0, 2}}, {:cons, 0, {:integer, 0, 3}, {nil, 0}}}}
iex(1)> [1] ++ 2 ++ [3] = [1,2]
** (ErlangError) Erlang error: {:illegal_pattern, {:op, 1, :++, {:cons, 0, {:integer, 0, 1}, {nil, 0}}, {:op, 1, :++, {:integer, 0, 2}, {:cons, 0, {:integer, 0, 3}, {nil, 0}}}}}
```

Check if the left argument of the lists concatenation is a proper list

---

lib/mix/lib/mix/project.ex

`Mixfile` was replaced with `MixProject` in https://github.com/elixir-lang/elixir/commit/c6a0edcd32359eca284ff0166d19a6dc979ee954.

Replace Mixfile with MixProject in docs

---

lib/ex_unit/lib/ex_unit/doc_test.ex
lib/ex_unit/test/ex_unit/doc_test_test.exs

This adds diff output to doctests, as [discussed on elixir-core](https://groups.google.com/forum/#!topic/elixir-lang-core/qGMW6lCYo5w). 
I haven't figured out a good way to add more tests for these changes. I have tested the changes manually, and they produce good output on complex data structures like Maps. Output is diffed just like normal in ExUnit tests. Are the existing (updated) tests sufficient, do you think?
I thought of adding a test to `lib/ex_unit/examples/difference.exs`, which exercises highlighting, but since doctests require creating a BEAM file, I wasn't sure this was the best approach. The current file is simple and understandable, and I didn't want to lose that quality.
I also thought to add a case to the doctests suite, but this would only test that left and right …

[WIP] Add diff to doctest

---

lib/elixir/lib/code.ex

Elixir can execute any valid code during compilation.  This can
compromise user machine.  Example of such code:
@foo File.rm_rf(System.get_env("HOME"))
end
Such code would remove whole `$HOME` of current user.
This PR introduces warning similar to the one used in
`Code.eval_string/3` that there is possibility for attacker to run code
via compilation (without evaluation).

Add informations about `Code.compile_string/2` insecurities

---

lib/elixir/lib/supervisor.ex

The documentation for the `:one_for_all` supervisor strategy indicates
> if a child process terminates, all other child processes are terminated
But this is not entirely true. Imagine a supervisor S with a `:one_for_all` strategy. S has 2 children: a `:permanent` process P, and a `:temporary` process T. Killing T will never cause P to get restarted event though that is what seems to be indicated by the documentation (T is a child of S, after all, so P should be terminated given it is an "other child" of the same supervisor).
Hopefully, this commit clarifies that `:temporary` processes are essentially ignored by supervisors with respect to restarting the temporary process or its siblings.

clarify behavior of `:temporary` processes within supervisor strategies

---

lib/elixir/lib/dynamic_supervisor.ex

`DynamicSupervisor.start_child/2` is typespec'ed to return the same type as `Supervisor.start_child/2`, but it can also return `:ignore` and `{:error, :max_children}`
This PR fixes that.

Fix typespec for DynamicSupervisor.on_start_child

---

lib/elixir/lib/dynamic_supervisor.ex
lib/elixir/test/elixir/dynamic_supervisor_test.exs

DynamicSupervisor.init/1 should have %{:ok, sup_flags()} per the @opaque type
Example code:
```elixir
@spec init(atom()) :: {:ok, sup_flags()} | :ignore
def init(arg) do
DynamicSupervisor.init(
strategy: :one_for_one,
extra_arguments: [arg]
)
```
Previous behavior:
```elixir
Starting Dialyzer
dialyzer args: [
check_plt: false,
init_plt: '/Users/starbelly/devel/elixir/soda/_build/dev/dialyxir_erlang-20.3.1_elixir-1.6.4_deps-dev.plt',
files_rec: ['/Users/starbelly/devel/elixir/soda/_build/dev/lib/soda/ebin'],
warnings: [:unknown]
]
done in 0m1.23s
lib/soda_dyn.ex:24: The specification for 'Elixir.Soda.Supervisor':init/1 has an opaque subtype 'Elixir.DynamicSupervisor':sup_flags() which is violated by the success typing (_) -> {'ok',#{'extra_arguments':=_, 'max_children':=_, 'strategy':=_, …
```

Fix typespec for DynamicSupervisor.init/1

---

lib/elixir/lib/string.ex

Removes warning:
```
warning: variable "string" is unused
lib/string.ex:278
```

Ignore unused var in String.ex

---

lib/elixir/lib/kernel.ex
lib/elixir/lib/map.ex
lib/elixir/lib/node.ex
lib/elixir/lib/process.ex
lib/elixir/lib/system.ex
lib/elixir/src/elixir_rewrite.erl

* Sort alphabetically elixir_rewrite.erl
* Mention in the docs every function inlined by the compiler
elixir_rewrite.erl has been audited, function by function:
- All missing "Inlined by the compiler." lines have been added.
- Standardize sentence avoid mentioning the function its inline to (System module).
- "Inline by the compiler." goes always before ##Options or ##Examples
Note: Please do not squash the commits into a single one.

 Mention in the docs every function inlined by the compiler

---

lib/elixir/lib/regex.ex

This addresses issues with precompiled archives on different
endianness, such as: https://github.com/hexpm/hex/issues/469

Include endianness in the regex version

---

lib/elixir/src/elixir.erl

Notice this while reading the parser

Erase elixir_parser_columns from the process dictionary after use

---

lib/elixir/lib/access.ex
lib/elixir/lib/calendar/date.ex
lib/elixir/lib/calendar/time.ex
lib/elixir/lib/file.ex
lib/elixir/lib/gen_server.ex
lib/elixir/lib/kernel.ex
lib/elixir/lib/map.ex
lib/elixir/lib/option_parser.ex
lib/elixir/lib/process.ex
lib/elixir/lib/registry.ex
lib/elixir/lib/string.ex
lib/ex_unit/lib/ex_unit/assertions.ex
lib/ex_unit/lib/ex_unit/case.ex
lib/iex/lib/iex.ex
lib/iex/lib/iex/helpers.ex
lib/mix/lib/mix/task.ex
lib/mix/lib/mix/tasks/app.tree.ex
lib/mix/lib/mix/tasks/deps.get.ex
lib/mix/lib/mix/tasks/deps.update.ex
lib/mix/lib/mix/tasks/local.public_keys.ex
lib/mix/lib/mix/utils.ex

If last line in the docs is idented, leave an emptyline before closing the comment.
Mentioned by @whatyouhide in https://github.com/elixir-lang/elixir/pull/7606#discussion_r184348514
The command/regexp used to find these offending lines is:
ag "\ {4,}[^\n]+\n\s{2}[\"']{3}"

Leave blank line before closing comment if idented

---

lib/mix/lib/mix/tasks/new.ex

I saw this practice in [Plug](https://github.com/elixir-plug/plug/blob/master/.formatter.exs#L25) and I always include it in my `.formatter.exs` files.

Add .formatter.exs to the list of inputs to format

---

ISSUE_TEMPLATE.md
Makefile
README.md
lib/elixir/lib/application.ex
lib/elixir/lib/kernel.ex
lib/elixir/lib/regex.ex
lib/elixir/lib/string.ex
lib/elixir/lib/system.ex
lib/elixir/pages/Compatibility and Deprecations.md
lib/elixir/pages/Syntax Reference.md
lib/elixir/src/elixir.erl
lib/elixir/test/elixir/system_test.exs
lib/iex/lib/iex.ex
lib/iex/lib/iex/helpers.ex
lib/iex/lib/iex/pry.ex
lib/logger/lib/logger.ex
lib/logger/lib/logger/translator.ex
lib/mix/lib/mix/compilers/erlang.ex
lib/mix/lib/mix/tasks/compile.app.ex
lib/mix/lib/mix/tasks/escript.build.ex
lib/mix/lib/mix/tasks/profile.fprof.ex
man/mix.1

This touches only messages directed to the end user,
So comments are (mostly) ignored.
This is important, specially for new commers, who may be confused
by the interchangeably use of Erlang and OTP.
The expressions used consistenly across the documentation are:
- Erlang/OTP version
- Erlang/OTP 20+
- Erlang/OTP release,
- Erlang/OTP documentation
- Erlang process
- Erlang project
- Erlang's error logger
- Erlang log message
- OTP application
- OTP behaviour

Standardize use of Erlang, OTP and Erlang/OTP names

---

lib/elixir/lib/string.ex

The new implementation is 10-70 times faster on the benchmark data.
Full benchmark: https://gist.github.com/michalmuskala/74ebb0456c8cfbfe8e012ce4aae2b6e5

Optimise String.ends_with?/2

---

lib/elixir/lib/keyword.ex

Calling [`Keyword.put/3`](https://github.com/elixir-lang/elixir/blob/e9dfa50c74488000d2c9de71e926cdd78609b3ac/lib/elixir/lib/keyword.ex#L553-L556), [`Keyword.delete/2`](https://github.com/elixir-lang/elixir/blob/e9dfa50c74488000d2c9de71e926cdd78609b3ac/lib/elixir/lib/keyword.ex#L497-L503), and other related functions changes the stacktrace returned from [`:erlang.get_stacktrace/0`](http://erlang.org/doc/man/erlang.html#get_stacktrace-0).
This is due to the throw/catch pattern used in the implementation of these functions.
This pull request helps prevent the following scenario and associated developer confusion:
```elixir
options = []
{exception, options} =
try do
:lists.last([])
catch
class, reason ->
options = Keyword.put(options, :reason, reason)
exception = Exception.normalize(class, …
```

Remove throw/catch pattern for Keyword.delete/2 and friends to prevent stacktrace corruption.

---

lib/elixir/lib/uri.ex

I have warnings that dialyzer could have picked up because when taking values for the map it assumes they can be of any term.

keys and values of decoded query are always binary

---

lib/elixir/lib/string.ex

"the entire string" is more idiomatic than "all the string"

Changes wording.

---

lib/mix/lib/mix/tasks/test.ex

I noticed this while reading though some of the source code, was surprised it wasn't documented, then  realized it was in fact documented, but not in the place I had first looked.

Normalize trace config docs for Mix.Tasks.Test

---

lib/elixir/src/elixir_def.erl
lib/elixir/test/elixir/kernel/warning_test.exs

Relates #7512 
Providing a separate warning for cases where just the function name matches rather than the default warning. 
Added a new unit test to cover the new  case
I left the new arity of the function in the arguments in case we need to use it in the warning to the user

Provide better warnings when grouping multi clause functions

---

lib/elixir/lib/process.ex

This information is provided in the Registry documentation (see https://hexdocs.pm/elixir/Registry.html#module-registrations), but was missing here.

Document Process.monitor/1 behavior for already dead processes

---

lib/elixir/src/elixir_erl_compiler.erl
lib/logger/lib/logger/app.ex
lib/logger/lib/logger/watcher.ex

Those are the minimum fixes which preserve the existing behaviour.
More performant fixes in the logger cases will be applied to master
and the upcoming Elixir v1.7.

Fix logger and stacktrace warnings on OTP 21

---

CHANGELOG.md
lib/eex/test/eex_test.exs
lib/elixir/lib/access.ex
lib/elixir/lib/exception.ex
lib/elixir/lib/kernel.ex
lib/elixir/lib/kernel/special_forms.ex
lib/elixir/lib/system.ex
lib/elixir/src/elixir_dispatch.erl
lib/elixir/src/elixir_erl_for.erl
lib/elixir/src/elixir_erl_try.erl
lib/elixir/src/elixir_rewrite.erl
lib/elixir/test/elixir/code_test.exs
lib/elixir/test/elixir/exception_test.exs
lib/elixir/test/elixir/inspect_test.exs
lib/elixir/test/elixir/kernel/errors_test.exs
lib/elixir/test/elixir/kernel/quote_test.exs
lib/elixir/test/elixir/kernel/raise_test.exs
lib/elixir/test/elixir/kernel/warning_test.exs
lib/ex_unit/lib/ex_unit/capture_log.ex
lib/ex_unit/lib/ex_unit/doc_test.ex
lib/ex_unit/lib/ex_unit/on_exit_handler.ex
lib/ex_unit/lib/ex_unit/runner.ex
lib/ex_unit/test/ex_unit/assertions_test.exs
lib/ex_unit/test/ex_unit/formatter_test.exs
lib/ex_unit/test/ex_unit_test.exs

Erlang/OTP 20 warns if the stacktrace is read outside of a
catch/rescue. This commit mirrors this behaviour by consistently
warning on `System.stacktrace/0` being used outside of a
catch/rescue.
Erlang/OTP 21 warns whenever System.stacktrace/:erlang.get_stacktrace
are used. Therefore we need to promote the usage of `__STACKTRACE__`
and make sure to conditionally compile it according to the OTP version.
This requires changes to the Exception normalization mechanism
so we compute `__STACKTRACE__` only when strictly required.
In future Elixir releases, `System.stacktrace/0` will warn when
used even inside catch/rescue.

Move to __STACKTRACE__ and lazily compute stacktrace

---

lib/elixir/lib/tuple.ex

This fixes the link to the `Kernel.elem/2` function in the Tuple docs.

Fix link to Kernel.elem/2 in docs

---

lib/elixir/lib/kernel/typespec.ex
lib/elixir/test/elixir/typespec_test.exs

The original issue (#7647) was posted in a very specific context, but I
figured that this implementation would both address that issue as well
as provide helpful feedback if someone were to attempt to write types
with variables incorrectly in general, since that was what was being
raised here.
Resolves #7647

Add helpful error message for improperly formatted type definitions

---

lib/elixir/lib/supervisor.ex

The second arg is now `overrides`, not `config`.

Fixed `Supervisor.child_spec/2` param name used in docs

---

lib/ex_unit/lib/ex_unit/diff.ex
lib/ex_unit/test/ex_unit/diff_test.exs

The current implementation of the Myers algorithm for diffing didn't
give very helpful diff information when comparing lists in the ExUnit
formatter. This is a very naieve implementation, and at the moment it
is only for lists, but I can see that we might conceivably want to have
this "missing head" diff show up for strings as well.
For making just this work, I sort of skipped the whole Myers algorithm
and just hand built the diff script since it follows a pretty simple
pattern. If we want to expand this further, though, we might need to
implement the reverse of the Myers algorithm.
Resolves #6768

Add better ExUnit formatting when missing head of list

---

lib/mix/lib/mix/tasks/test.ex

This should reduce need for packages like excoveralls in some use cases
when all what is needed is to have total coverage percentage in any
form available for CI to provide coverage badge.
Reference: https://docs.gitlab.com/ee/user/project/pipelines/settings.html#test-coverage-parsing

Display simple coverage report to console

---

lib/elixir/src/elixir.erl
lib/elixir/src/elixir_parser.yrl

The throws with this pattern are [caught by yecc](https://github.com/erlang/otp/blob/master/lib/parsetools/include/yeccpre.hrl#L67)
and returned as an error. Also renamed throw to error to avoid confusions (matching with function [return_error](https://github.com/erlang/otp/blob/master/lib/parsetools/include/yeccpre.hrl#L51))

Remove unnecessary catch from the parser

---

lib/elixir/lib/access.ex
lib/iex/test/iex/autocomplete_test.exs

It was not being used. In fact, `Access.get/3` was relying on the `c:Access.fetch/2` callback for some reason.

Remove the Access.get/3 callback

---

lib/elixir/lib/string.ex

the existing implementation with binary comprehensions turned out to be
_far_ slower than the other modes.
The current implementation is >= 2.5X faster than the earlier implementation
---
this PR is a consequence of the discussions in #7673
PS: this is my first PR in elixir

Added performant impl for string upcase/downcase `:ascii` mode.

---

lib/elixir/lib/task/supervisor.ex

This PR is nothing but a fix for the documentation of `Task.Supervisor`.
A comment containing an example function call to `Supervisor.start_link/2` is written without any children passed in.

Fix faulty function call in comment

---

lib/elixir/lib/supervisor.ex

Using "supervision strategy" consistently makes the documentation easier to follow, and removing the previous uses of "restart strategy" also avoids confusion with the `:restart` value used in child specifications.

consistently use "supervision strategy" term

---

lib/mix/lib/mix/tasks/format.ex
lib/mix/test/mix/tasks/format_test.exs

Here is the example `.formatter.exs` file given in the documentation of `mix format`:
[
inputs: ["{mix,.formatter}.exs", "{config,lib,test}/**/*.{ex,exs}"]
]
With the previous implementation, the `.formatter.exs` file would not be formatted because internally `Path.wildcard/2` was used without expanding files starting with dot ".":
iex> Path.wildcard("{mix,.formatter}.exs")
["mix.exs"]
iex> Path.wildcard("{mix,.formatter}.exs", match_dot: true)
[".formatter.exs", "mix.exs"]

Match files starting with dot in "mix format"

---

lib/elixir/lib/enum.ex

- One may refer to Kernel functions to find the max and min values in enumerables
with just two elements.

Adds minor reference for Kernel functions Enum doc

---

lib/elixir/lib/code.ex

`some_funtion_without_parens` ... doc needs a C in function

Correct typo

---

lib/iex/test/iex/helpers_test.exs

Closes #7348.
Some installations delete the Erlang source after installing Erlang.
This commit only tests the open/1 helper on Erlang source files when the
Erlang source files are present.

Only test the open/1 IEx helper on Erlang source if it exists (#7350)

---

lib/logger/lib/logger/utils.ex
lib/logger/test/logger/utils_test.exs

I encountered the following while investigating an issue that occurred in dev environment but not in testing (was apparently parsing some really broken data with Sweet_xml)
```elixir
13:29:32.638 module=Logger.Watcher [error] :gen_event handler Logger.ErrorHandler installed at :error_logger
** (exit) an exception was raised:                    
** (ArithmeticError) bad argument in arithmetic expression    
(logger) lib/logger/utils.ex:57: Logger.Utils.truncate_n/2    
(elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
(elixir) lib/enum.ex:1397: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
(logger) lib/logger/utils.ex:141: Logger.Utils.scan_inspect/4
(logger) lib/logger/error_handler.ex:170: Logger.ErrorHandler.translate/6
(logger) lib/logger/error_handler.ex:92: …
```

Avoid calling truncate_n/2 if truncate is :infinity

---

lib/elixir/lib/inspect.ex

Added examples of practical usage to inspect, so that people review the documentation can understand what the inspect protocol is used for.

Added examples of practical usage to inspect

---

lib/elixir/lib/inspect/algebra.ex

The example for `Inspect.Algebra.line/0` isn't indented enough to be recognized as a docstring.

Indent an example all the way

---

lib/elixir/lib/macro.ex
lib/elixir/test/elixir/macro_test.exs

Fixes #7721: 
`1 |> <<1,2,3>>` was valid syntax as it was compiled to
<<1, 1, 2, 3>>. `<<>>` is an operator, the pipe operator (`|>`) prepended an
extra argument. Same goes for situations with interpolation since that leads to
creation of a new string, using `<<>>` and `::`.

raise if piping into bitstring operator <<>>

---

lib/elixir/lib/code/typespec.ex
lib/iex/test/iex/helpers_test.exs

Refs https://github.com/elixir-lang/elixir/issues/7712
When building the `when` clause `Typespec#spec_to_quoted`, we want to ignore var:
```elixir
ignore_vars = Keyword.keys(guards)
vars =
for type_expr <- args ++ [result],
var <- collect_vars(type_expr),
var not in ignore_vars,
uniq: true,
do: {var, {:var, meta, nil}}
```
But `ignore_vars` contains a list of codelists where as `collect_vars` returns an elixir variable:
```elixir
defp collect_vars({:var, _line, var}) do
[erl_to_ex_var(var)]
end
```
As a result, this filter (`var not in ignore_vars,`) doesn't work as intended.
Converting ignore_vars to a list of elixir variables will fix it.
`ignore_vars = Keyword.keys(guards) |> Enum.map(&erl_to_ex_var/1)`
Before:
After:
====
Updates after @michalmuskala 's feedback.
Now the variable …

[Typespec#spec_to_quoted] ignore_vars should be converted to elixir variables

---

lib/elixir/src/elixir_tokenizer.erl
lib/elixir/test/erlang/tokenizer_test.erl

This PR fixes cases where `:elixir_tokenizer` does not account for double quotes in keyword identifiers when determining the column for the next token.
Given the tokens for
```elixir
foo: "bar"
```
and
```elixir
"foo": "bar"
```
the column value of the `"bar"` token is only incremented by +1 for the second example:
```elixir
iex(1)> :elixir_tokenizer.tokenize('foo: "bar"', 1, [])
{:ok,
[{:kw_identifier, {1, 1, nil}, :foo}, {:bin_string, {1, 6, nil}, ["bar"]}]}
iex(2)> :elixir_tokenizer.tokenize('"foo": "bar"', 1, [])
{:ok,
[
{:kw_identifier_unsafe, {1, 1, nil}, ["foo"]},
{:bin_string, {1, 7, nil}, ["bar"]}
]}
```
IMHO the column information should have changed by +2 instead of +1 after we added the two double quotes:
```elixir
iex(1)> :elixir_tokenizer.tokenize('"foo": "bar"', 1, []) …
```

Fix column in :elixir_tokenizer for double quotes in keyword identifiers

---

lib/mix/lib/mix/local/installer.ex
lib/mix/lib/mix/tasks/archive.install.ex
lib/mix/lib/mix/tasks/escript.install.ex
lib/mix/test/mix/local/installer_test.exs

For archives downloaded from Hex, we want to be able to pass in an organization:
mix archive.install hex my_package --organization my_org
Do we want to support `--repo` as well?
PS: did this pairing up with @idlehands, thanks for the help Jeffrey! 💟

Add support for "--organization" in the archive.install task

---

lib/elixir/lib/task/supervisor.ex

This is v1.6 branch version of this PR https://github.com/elixir-lang/elixir/pull/7744
Behind the scenes, this function uses DynamicSupervisor.start_child/4, which can return multiple errors. This gives Task.Supervisor.start_child/4 that return type. This allows dialyzer to not complain when you pass :max_children to the Task.Supervisor and call start_child, which may return {:error, :max_children}.

Fix type spec for Task.Supervisor.start_child/4

---

lib/elixir/pages/Library Guidelines.md

Fix typo in Library Guidelines: paralleiize -> parallelize

---

lib/elixir/src/elixir_erl.erl
lib/elixir/test/elixir/module_test.exs

The phash value changes because clauses for the `__info__` function
are now ordered differently

Refactor __info__ so it generates smaller assembly

---

lib/elixir/lib/kernel/parallel_compiler.ex

Example:
```
Compilation failed because of a deadlock between files.
The following files depended on the following modules:
lib/hexpm/web/controllers/api/repository_controller.ex => Organization
lib/hexpm/repository/sitemaps.ex => Hexpm.Accounts.AuditLog
lib/hexpm/accounts/user.ex => Hexpm.Accounts.AuditLog
lib/hexpm/accounts/users.ex => Hexpm.Accounts.AuditLog
lib/hexpm/repository/releases.ex => Hexpm.Accounts.AuditLog
lib/hexpm/web/controllers/user_controller.ex => Organization
lib/hexpm/accounts/audit_log.ex => Organization
lib/hexpm/repository/owners.ex => Hexpm.Accounts.AuditLog
lib/hexpm/accounts/organizations.ex => Hexpm.Accounts.AuditLog
lib/hexpm/repository/packages.ex => Hexpm.Accounts.AuditLog
lib/hexpm/web/controllers/dashboard/organization_controller.ex => Organization …
```

Add instructions for fixing deadlock errors

---

lib/mix/lib/mix/compilers/erlang.ex

I wanted to make it easier for Elixir developers to try and play with LFE (as I like LFE), so decided to create a mix task for compiling LFE, which gave birth to [mix_lfe](https://github.com/meddle0x53/mix_lfe).
To my surprise, I found an example for exactly that in `Mix.Compilers.Erlang`, while I was looking at Mix's sources which was almost right, but not quite. I used the idea [here](https://github.com/meddle0x53/mix_lfe/blob/6021715d5af181069eb0fd09dcd1787a020ff0de/lib/mix/compilers/lfe.ex#L26) and modified it to work, so decided to fix this example too:
* The `:outdir` fixes a syntax error in the example and is a real option of the `:lfe_comp.file/2`.
* The `:report` option will make it so that compiler errors are shown when the sources are compiled.

Fix the LFE example in Mix.Compilers.Erlang

---

lib/elixir/lib/integer.ex

Fix small grammar error in Integer.parse docs

---

lib/elixir/lib/regex.ex

Hi all,
this fixes 2 typos in the Regex moduledoc.
Cheers!

Fix moduledoc typos in Regex

---

lib/elixir/src/elixir_map.erl
lib/elixir/test/elixir/kernel/errors_test.exs

Partial credit: @tuxified helped me figure this puzzle out.

Include caller information on struct expansion errors, closes #7752

---

lib/logger/lib/logger.ex
lib/logger/test/logger_test.exs

This means that the arguments won't be evaluated if the
message has a lower level than the logger one or if the
logger mode is set to discard.
Closes #7046.

Only evaluate Logger macro arguments when the message will be logged

---

lib/elixir/lib/dynamic_supervisor.ex

It returns `{:error, :max_children}` instead of `{:error, :dynamic}`.

Fix description of max_children option

---

lib/elixir/lib/kernel.ex
lib/elixir/test/elixir/fixtures/dialyzer/boolean_check.ex
lib/elixir/test/erlang/control_test.erl

The optimize_boolean option is very sensitive to the order of
clauses and the optimisation was not happening for and/2 and or/2.
Add regression tests to ensure that won't happen again.
---
This change breaks the dialyzer test for optimised booleans:
```elixir
def and_check_optimized(arg) when is_integer(arg) do
arg < :infinity and arg
end
```
this now emits a warning that the pattern `false` can never match. It's weird because we have already all the clauses marked with `generated`, so I'm not sure why this is emitted. Anyway, the warning is very correct in here, since the `false` branch can never be taken, it's just pretty unreadable to the user - I'm not sure what to do about this.

Restore and/or optimisation

---

lib/elixir/lib/kernel.ex

Minor corrections in the grammar of the documentation of the `Kernel` module:
* enumerate the arguments of the function in `get_in/2` in the same way as in `get_and_update_in/3`. [This new style was applied recently.](https://github.com/elixir-lang/elixir/commit/19105a3bd2437250113776164ddf1209a65da387)
* use back-ticks to enable auto-linking of the `Access` module.
* use "in case of" instead of "in case". ["in case" shouldn't be used to mean "if".](https://dictionary.cambridge.org/grammar/british-grammar/conditionals-and-wishes/in-case-of)
* add missing "the" articles.

Polish documentation of Kernel module

---

lib/iex/lib/iex/helpers.ex

Refs https://github.com/elixir-lang/elixir/issues/7645#issuecomment-386910209
Changes:
- New `runtime_info` topic: `:allocators`
- Human-friendly bytes formatting, the unit is now selected based on the input value

Add :allocators runtime_info topic

---

lib/mix/lib/mix/dep/converger.ex
lib/mix/test/mix/dep_test.exs

- Add test for deps diverged from remote converger (@ericmj)
- Add scm to the deps cache
- Add code comments to help explain reasoning
Fixes: #7685

Update Mix Deps Converger

---

lib/elixir/lib/kernel.ex
lib/elixir/test/elixir/kernel/guard_test.exs

If I got it right, one of the reasons for that change was to get the message:
> invalid expression in guard, **!** is not allowed in guards. To learn more about guards, visit: https://hexdocs.pm/elixir/guards.html  
instead of:
> invalid expression in guard, **case** is not allowed in guards. To learn more about guards, visit: https://hexdocs.pm/elixir/guards.html
This change should make the test suite more robust for future changes or refactors :)
In addition, I've split a couple of strings that were exceeding the maximum line length (98). By the way, should the formatter warn when it cannot keep the code under the desired line length? maybe with a `--strict` flag?

Make test suite for assert_no_guard more robust

---

lib/elixir/lib/kernel.ex

I was reading through the docs, and I can see how `single` here can be misconstrued to mean functions of arity 1. I think that sole makes it clearer as referring to a sole arity instead of a single arity function.

disambiguate def/2 docs regarding anonymous functions

---

lib/elixir/lib/gen_server.ex

Tried to make the docs more clear that manual cleanup is not needed for opened sockets and files.

Updated docs für GenServer.terminate

---

lib/elixir/lib/module.ex

Firstly I commend the use of british spelling.
This commit updates the documentation to improve the href. Currently the link is:
https://hexdocs.pm/elixir/1.6.6/Module.html#module-behaviour-notice-the-british-spelling
With this update the link will be:
https://hexdocs.pm/elixir/1.6.6/Module.html#module-behaviour

Update Module doc - split behaviour link

---

lib/mix/lib/mix.ex
lib/mix/lib/mix/tasks/help.ex
lib/mix/test/mix/tasks/help_test.exs

ref: https://trello.com/c/9DzdXbp4/4-make-mix-help-list-aliases
cc @michalmuskala

Make mix help list aliases

---

lib/mix/lib/mix/local/installer.ex
lib/mix/lib/mix/tasks/archive.uninstall.ex
lib/mix/lib/mix/tasks/escript.uninstall.ex
lib/mix/test/mix/tasks/archive_test.exs
lib/mix/test/mix/tasks/escript_test.exs

Mix archive.install contains a `--force` flag to allow silent installation/upgrades. However, the same is not true for uninstall.
This PR copies the same pattern used in install to add a similar force flag to uninstall.

Add a --force flag to mix archive.uninstall

---

lib/iex/lib/iex/config.ex

Because there is a `min` function in line 18, the `min` function in line 17 is redundant.

IEx config: remove redundant code

---

lib/elixir/lib/code.ex
lib/elixir/lib/kernel.ex
lib/elixir/lib/macro.ex
lib/elixir/src/elixir_interpolation.erl
lib/elixir/src/elixir_tokenizer.erl
lib/elixir/test/elixir/code_test.exs

As discussed in #7270, it would help if we moved up the error logic out of Erlang. So, instead of raising an exception, we'll return an error tuple.
Currently, this will only fix the Hex error use case, so does not completely resolve this issue. But, if this is the route we want to take, I can work on the other usecases.

Move `Code.string_to_quoted` error logic up

---

lib/elixir/lib/code.ex
lib/elixir/lib/protocol.ex
lib/elixir/src/elixir_erl.erl
lib/elixir/test/elixir/kernel/docs_test.exs
lib/elixir/test/elixir/protocol_test.exs
lib/mix/lib/mix/tasks/escript.build.ex

Related to #7198.
As discussed in the referenced issue the following are in scope for this PR:
The following are to be implemented in separate PRs:
* migrate all functionality that uses `Code.get_docs/2` to use `Code.fetch_docs/1`
* remove the old docs chunk and return `nil` from `Code.get_docs/2`
* change how we store docs to be closer to the new docs format
* dependent functionalities (e.g. `@since` and `@deprecated`)

Adopt EEP 48

---

lib/elixir/lib/behaviour.ex
lib/elixir/lib/code.ex
lib/elixir/lib/kernel/typespec.ex
lib/elixir/pages/Writing Documentation.md
lib/elixir/test/elixir/kernel/docs_test.exs
lib/ex_unit/lib/ex_unit/doc_test.ex
lib/iex/lib/iex/autocomplete.ex
lib/iex/lib/iex/info.ex
lib/iex/lib/iex/introspection.ex
lib/iex/test/iex/autocomplete_test.exs
lib/iex/test/iex/helpers_test.exs
lib/mix/lib/mix/task.ex

Migrate to `Code.fetch_docs/1`

---

lib/mix/lib/mix/dep.ex
lib/mix/lib/mix/dep/fetcher.ex
lib/mix/lib/mix/local/installer.ex
lib/mix/lib/mix/project_stack.ex
lib/mix/lib/mix/task.ex
lib/mix/lib/mix/tasks/deps.clean.ex
lib/mix/lib/mix/tasks/deps.compile.ex
lib/mix/lib/mix/tasks/deps.ex
lib/mix/lib/mix/tasks/deps.loadpaths.ex
lib/mix/lib/mix/tasks/deps.tree.ex
lib/mix/lib/mix/tasks/deps.unlock.ex
lib/mix/test/mix/dep_test.exs
lib/mix/test/mix/rebar_test.exs
lib/mix/test/mix/tasks/compile_test.exs
lib/mix/test/mix/tasks/xref_test.exs
lib/mix/test/mix/umbrella_test.exs

This should also provide performance benefits as we
avoid performing resolution for each child project.
Closes #7561

Make sure converged dependencies are fetched on child projects

---

lib/mix/lib/mix/rebar.ex
lib/mix/test/mix/rebar_test.exs

In Rebar 3, simply listing a dependency in the parent overrides
any child dependency, so we mimic this behaviour in Mix.
Closes #7346

Include override true in rebar dependencies

---

lib/logger/lib/logger.ex
lib/logger/test/logger_test.exs

Now that we support a more general `compile_time_purge_matching`,
we can deprecate `compile_time_purge_level`. We chose the name
`:level_lower_than` rather than `:level` for the matching key
since all other matches are exact.

Replace compile_time_purge_level by compile_time_purge_matching

---

lib/elixir/lib/kernel/special_forms.ex

* 4_294_967_295 is still a valid number
* it is not correct to say that :infinity is the same as not using a timeout value,
as this is needed if used the after clause. To what's equivalent is as to not to
use the after clause itself.
* use the formal name "hexadecimal notation" in favor of "hex notation"
[ci skip]

Be precise in documentation about after values in receive/1

---

lib/elixir/pages/Typespecs.md

Mention that `port()` is a "port identifier", in the same vein as
`pid()` is commented as being a "proccess identifier"
[ci skip]

Add comment in typespecs page next to port type

---

lib/elixir/lib/kernel.ex

Use proper names when describing boolean operator args.

---

lib/elixir/lib/gen_server.ex
lib/elixir/lib/supervisor.ex

Since the documented function uses a "module" arg., it was not
clear whether "module" referrer to the argument or to GenServer
[ci skip]

Clarify documentation in GenServer

---

lib/elixir/lib/kernel/special_forms.ex

1. avoid use of single-char variables with not descriptive names ("i")
2. "value" can be thought of a number, so to make it clearer I replace it with "name"

Change arg names in example in receive/1

---

lib/elixir/lib/kernel.ex

Second argument should be named "function_name" and not "fun" as "fun"
is generally used for anonymous functions.

Rename apply/3 second arg.

---

lib/iex/lib/iex/helpers.ex

It make not be 100% clear what "to flush the messages" mean.

Make description of IEx.flush/0 even clearer

---

lib/elixir/lib/gen_event.ex
lib/elixir/lib/gen_server.ex
lib/elixir/lib/kernel.ex
lib/elixir/lib/supervisor.ex
lib/elixir/test/elixir/gen_server_test.exs
lib/elixir/test/elixir/supervisor_test.exs

Message read weird (didn't read natural):
supervisors expect each child to be one of:
* a module
* a {module, arg} tuple
* a child specification as a map with at least the :id and :start fields
* or a tuple with 6 elements generated by Supervisor.Spec (deprecated)
changed to
supervisors expect each child to be one of the following:
* a module
....

Change wording in error giving options

---

lib/mix/lib/mix/tasks/do.ex
lib/mix/lib/mix/tasks/profile.cprof.ex
lib/mix/lib/mix/tasks/profile.eprof.ex
lib/mix/lib/mix/tasks/profile.fprof.ex
lib/mix/lib/mix/tasks/run.ex

Reenable tasks without side-effects, that only run code

---

lib/elixir/lib/calendar/iso.ex

Fix syntax highlighting of Calendar.ISO docs

---

lib/elixir/lib/system.ex

Fixes
```
warning: deprecated time unit: :nanosecond. A time unit should be :second, :millisecond, :microsecond, :nanosecond, or a positive integer
```

Fix time unit depracation messages

---

lib/elixir/lib/protocol.ex
lib/elixir/src/elixir_erl.erl
lib/elixir/test/elixir/fixtures/dialyzer/protocol_opaque.ex
lib/elixir/test/elixir/kernel/dialyzer_test.exs
lib/elixir/test/elixir/protocol_test.exs

This siwtches protocol compilation to happen on the epxnaded Elixir AST
instead of the Erlang AST. This is slightly less complex and opens
possibility for easy "partial" compilation of protocols.
Additionally instead of rewriting specs on consolidation, this marks the
functions that end-up being rewritten with @dialyzer :nowarn_function to
disable overly eager dialyzer warnings.

Compile protocols in elixir syntax

---

lib/elixir/lib/gen_server.ex

The type for `hibernate_after` just from https://github.com/erlang/otp/blob/OTP-20.1.7/lib/stdlib/src/gen_statem.erl#L373.
The doc for `hibernate_after` from http://erlang.org/doc/man/gen_server.html#start_link-3.

update doc for gen server add hibernate_after

---

lib/logger/lib/logger/translator.ex

This prevents Logger application from crashing when supervisors report children progress with fields unknown to Logger.Translator. 
Closes #7889

Ignore unknown child info in Logger.Translator

---

lib/elixir/lib/float.ex

Float ceil/floor 1000 times per benchmark run
**Ceil**
Before changes
```
Name                         ips        average  deviation         median         99th %
ceil/1                    369.95     2703.04 μs     ±9.48%        2615 μs        3897 μs
ceil/2 precision 0        366.37     2729.45 μs     ±8.96%        2674 μs     3743.83 μs
ceil/2 precision 1        350.72     2851.25 μs     ±4.61%        2821 μs     3356.70 μs
```
After changes
```
Name                         ips        average  deviation         median         99th %
ceil/1                  23214.94       43.08 μs    ±17.66%          42 μs          81 μs
ceil/2 precision 0      22786.86       43.88 μs    ±18.15%          42 μs          81 μs
ceil/2 precision 1        364.20     2745.76 μs     ±4.75%        2709 μs …
```

Optimization for Float floor and ceil functions when precision is 0

---

lib/mix/lib/mix/tasks/test.ex

We can't actually specify directory via command line options, need to configure it via mix configuration instead.

Update --cover docs

---

lib/mix/lib/mix/tasks/test.ex

Given `ExUnit.configure` was previously mentioned in these docs, I thought that's where `:test_coverage` is to be put and was surprised that it didn't work.

Clarify how to configure :test_coverage

---

lib/elixir/docs.exs

At the moment `Function` module is in one group (without group?) with Kernel and Kernel.SpecialForms.
I'm not sure if "Basic Types" is correct group, but functions in this module are taking/returning other functions so function looks like kind of type to me.

Add Function module docs to "Basic Types" group

---

lib/elixir/lib/float.ex

I did not notice one more optimization opportunity in previous PR. 
Benchmarks (1000 floats per run)
Before
```
Name                          ips        average  deviation         median         99th %
round/1                    382.08     2617.25 μs     ±3.97%        2590 μs     3031.20 μs
round/2 precision 0        377.92     2646.05 μs     ±4.09%        2621 μs     3064.80 μs
round/2 precision 1        351.24     2847.02 μs     ±6.13%        2804 μs     3648.76 μs
```
After
```
Name                          ips        average  deviation         median         99th %
round/1                  20596.03       48.55 μs    ±18.17%          47 μs          91 μs
round/2 precision 0      20096.23       49.76 μs    ±17.50%          48 μs          91 μs
round/2 precision 1        354.77 …
```

Optimization for Float.round/2 when precision is 0

---

lib/elixir/lib/bitwise.ex
lib/elixir/lib/io/ansi/docs.ex
lib/elixir/lib/kernel.ex
lib/elixir/test/elixir/kernel/docs_test.exs
lib/iex/lib/iex/introspection.ex
lib/iex/test/iex/helpers_test.exs

Related to #7845.
This is a draft implementation after doing some experimentation with various ways of doing this. The current approach introduces the least amount of changes to make it work.
Other approaches:
1. use `:defguard`/`:defguardp` as kind and move the `@doc guard: true` call to `define/4`. `store_definition` would be called with `:defmacro`/`:defmacrop`.
This would have the added benefit of having more precise error messages in the `assert_*` functions.
2. use `:defguard`/`:defguardp`
This would be the most invasive change as there are a lot of places where we do something for `:defmacro`/`:defmacrop` that would have to be extended for guards. However, this would allow us to add `guard: true` to the metadata in `Module.compile_definition_attributes/6` which could in turn allow …

Annotate @doc metadata when something is a guard

---

lib/elixir/lib/kernel.ex

Looking at the documentation, final dots are not included when listing items.

Minor update in Kernel's doc

---

lib/elixir/lib/map.ex

The same sentence is present a few lines above.

Remove duplicated sentence from Map's doc

---

CHANGELOG.md

`mix test --failed` runs all tests that failed the last time they ran,
even if they were not included in the last run of the test suite. This
is important, because it means that you can run individual failed tests
to focus on fixing them without worrying about mix losing track of the
other failed tests.

Changelog: explain `mix test --failed` more accurately.

---

lib/elixir/lib/module.ex

This is one of the things I learnt today in https://github.com/elixir-lang/elixir/pull/7905 :)

Clarify documentation of @compile :inline flag

---

lib/elixir/lib/calendar/datetime.ex
lib/elixir/lib/calendar/naive_datetime.ex
lib/elixir/lib/calendar/time.ex
lib/elixir/lib/kernel.ex
lib/iex/lib/iex/info.ex
lib/iex/test/iex/info_test.exs

There is a mix of "timezone" and "time zone" in the codebase. For what I read, "time zone" is usually more correct.
In addition, there are some variables and types named `time_zone`, so I think the best option is to go with "time zone".

Use "time zone" instead of "timezone" everywhere

---

lib/elixir/lib/string_io.ex

At the moment examples are interpreted as normal text because indentation is too small
https://hexdocs.pm/elixir/1.7.0-rc.0/StringIO.html#open/3
Also, `@doc :since` metadata was missing and I cannot find anything about `StringIO` in v1.7 CHANGELOG. Function was added in #7477

Fixed indentation in StringIO.open/3 examples and added missing @doc :since metadata

---

lib/mix/lib/mix/config.ex
lib/mix/test/fixtures/configs/nested_import.exs
lib/mix/test/mix/config_test.exs

Previously, if a config file uses Mix.Config.eval!/2 then it would fail with the
following error:
> ** (RuntimeError) could not set configuration via Mix.Config. This usually
>  means you are trying to execute a configuration file directly instead of
> using the proper command, such as mix loadconfig
> code: assert Mix.Config.eval!(fixture_path("configs/nested_import.exs")) ==
> stacktrace:
>   (mix) lib/mix/config.ex:71: Mix.Config.raise_improper_use!/0
>   (mix) lib/mix/config.ex:222: Mix.Config.eval!/2
>   lib/mix/test/mix/config_test.exs:110: (test)

Fix nested use of Mix.Config.eval!/2

---

lib/elixir/lib/application.ex

The documentation for Application.get_env is not newcomer friendly and can be considered one of the most important and granular functions to understand in the Elixir programming language. In particular, an inexperienced developer will find it difficult to understand from the documentation what is meant by the 'app', 'environment' and 'environment keys' without bouncing between different sources of information. It's then up to the inexperienced developer to make that (frankly quite difficult) connection. When we try to make elicit the concept of scoping in a Mix configuration file, and how that is laden on `Application.get_env`, and how `Application.get_env` is then used to acquire the various configurations for our application (which are conceptual leaps we need to make in turn), …

Clarify Application.get_env by illustrating a use case

---

lib/elixir/lib/string.ex

This should reduce confusion for newcomers about how function works and
what to use when you need to gracefully handle possible ill-formated
strings.

Add reference to Integer.parse/2 in String.to_integer/1

---

lib/elixir/src/elixir_tokenizer.erl

I’m not a native speaker, but it seems to me the warning on unnecessary quotes sounds strange. Here is a quick fix for that :)

Fix a typo in the unnecessary quotes warning

---

lib/elixir/lib/kernel.ex
lib/elixir/lib/macro.ex
lib/elixir/src/elixir.hrl
lib/elixir/src/elixir_bootstrap.erl
lib/elixir/src/elixir_map.erl
lib/elixir/src/elixir_quote.erl
lib/elixir/test/elixir/macro_test.exs
lib/ex_unit/lib/ex_unit/assertions.ex

We use this option in ExUnit as we are escaping
the code to eventually convert it to a string
representation and therefore the metadata is not
relevant.
Closes #7947.

Allow to prune metadata while escaping

---

lib/elixir/lib/calendar/iso.ex

How it looks like now:
How longest line should looks like after change:

Fixed too wide example for Calendar.ISO.datetime_to_string

---

lib/elixir/lib/calendar/naive_datetime.ex

Rename a variable holding an `NaiveDateTime` in ISO calendar.
It is not a date and it is not in UTC, but rather a `NaiveDateTime`.

Rename variable utc_date.

---

lib/elixir/lib/path.ex

* fixed two example lines that ended with a dot
* made `expand/2` examples more consistent

Path docs improvement

---

lib/elixir/lib/option_parser.ex

This also fixes one `OptionParser.parse/2` example that was too wide for hexdocs.

Make OptionParser docs more formatter-compatible

---

lib/elixir/lib/supervisor/spec.ex

I'm aware that `Supervisor.Spec` is deprecated, but these examples will be visible until v1.9 and that's why I think they should be well-formatted until their time comes.

Make Supervisor.Spec docs examples more formatter-compatible

---

lib/elixir/lib/process.ex

Process.info returns nil if the process is no longer alive, however the @spec for it did not reflect that possible return value .
This causes dialyzer to throw errors if you check for the nil return value.
This pull request updates the @spec for Process.info to allow for the nil return value.
Tests passed. No doc changes necessary as it already said it could return nil.

Update Process.info spec to reflect the possible nil return value

---

lib/elixir/lib/calendar/datetime.ex
lib/elixir/lib/calendar/naive_datetime.ex

This PR builds on the optimizations recently committed to the v1.7 branch: https://github.com/elixir-lang/elixir/commit/04c45b031a8e766969b865015b7ba5c1b4ba04d7. I found it to be cheaper to apply the TZ offset directly to the calendar date than to go through the conversions to and from ISO days. Since TZ offsets are no more than 24 hours, we avoid a lot of the complication of counting leap days over a range of years that's handled by doing calendar math in ISO days. At most, we have to carry over +/- 1 day. I added tests for carrying over month and year boundaries and to and from leap days to verify that the date carrying logic is correct.
Note that `calendar.valid_date?` and `calendar.valid_time?` are handled inside the `Date.new/4` and `Time.new/5` constructors and produce the same …

Optimize ISO-8601 Parsing

---

Makefile

downstream packagers such as FreeBSD support building and shipping binary-style packages with or without manpages enabled, or in different locations, in addition to setting `PREFIX` or `SHARE_PREFIX`
directly.
This simple patch allows them to do so by setting `MAN_PREFIX` and Make will Do The Right Thing.
It should have no impact on users not using this feature, as the default config will fall through to the current value.

build: allow downstream packagers to tweak manpage generation

---

lib/elixir/lib/module.ex
lib/elixir/src/elixir_module.erl
lib/elixir/test/elixir/kernel/errors_test.exs

This is an attempt to implement the check from #5800: `{undefined_on_load,{F,A}}`: function for `on_load` undefined.
These are my first steps with Erlang 🎉 , any feedback is more than appreciated :) 
During the development of this PR, I had some doubts regarding the visibility of the `@on_load` function. According to the [Erlang's documentation](http://erlang.org/doc/reference_manual/code_loading.html#on_load), "It is not necessary to export the function". (I'm currently learning the Elixir internals and what I'm about to say might not make sense, so please be bear with me 😅) I would think that public functions map to exported functions, and private functions to non-exported functions. If that's the case, this should work (as the function does not need to be public/exported):
```elixir …
```

Validate @on_load function in Elixir

---

lib/elixir/lib/module.ex

`definition without a body` in the warning confused me when I upgraded 1.7.0 for my pheonix project.
I found in other documents, it is called `function head` or `header`.
For example:
1. https://github.com/elixir-lang/elixir/blob/691460a6e661f174476c69153776cba2f8a47341/lib/elixir/src/elixir_def.erl#L412-L426
2. https://github.com/elixir-lang/elixir/blob/caa90b563ade4818a4e49b3e20149a44ff0c00c8/lib/elixir/pages/Writing%20Documentation.md#function-arguments
Or else, is it better to add an example in the warning? Like `def foo(a, b)`

Improve compile_doc warning

---

ISSUE_TEMPLATE.md
README.md
RELEASE.md
lib/elixir/pages/Compatibility and Deprecations.md

Promote the new announcements mailing list and how to retrieve
all security releases. Also promote the security disclosure link
more openly.

Talk about the new announcement mailing list

---

lib/elixir/lib/string.ex

Hey all,
this adds an article to `String.pad_leading/3` and `String.pad_trailing/3` `@doc`s:
`…contains non-string element` → `…contains a non-string element`.
Thanks for v1.7, keep rocking, cheers!

Improve wording in String doc

---

lib/elixir/lib/access.ex

The code block was rendering as regular text because it needs one more
space to be considered code.

Fix formatting in docs for access.ex

---

lib/elixir/lib/module.ex

Fixes:
```
==> elixir (compile)
warning: variable "body" is unused
lib/module.ex:1334
```

Fix warning for unused var in Module

---

lib/ex_unit/lib/ex_unit/assertions.ex

The new format was introduced in [this commit](https://github.com/elixir-lang/elixir/commit/81770ad82eb7cab18e8b2f66d4e267d4c8ab9beb#diff-699b0020c6a196231a7d473322f1744d).

Update assertions examples with the new format

---

lib/elixir/lib/registry.ex
lib/elixir/test/elixir/registry_test.exs

When using Registry with `:via` tuples, in some cases it may be desired to associate a value to the process at the same time.  Currently this is not possible, resulting in a value of `nil` unless you call `Registry.update_value` as an additional step after the process has started.
This PR introduces an additional `:via` tuple element for the value to be associated with the process (while retaining the existing behavior, of course):
{:ok, _} = Registry.start_link(keys: :unique, name: Registry.ViaTest)
name = {:via, Registry, {Registry.ViaTest, "agent", :hello}}
{:ok, _} = Agent.start_link(fn -> 0 end, name: name)
Registry.lookup(Registry.ViaTest, "agent")
#=> [{self(), :hello}]
Thoughts?

Registry: Associate value to process using via tuple

---

lib/elixir/lib/registry.ex

Similar to [this commit](https://github.com/elixir-lang/elixir/commit/233341699d303f853cd808567f73df5731e511fa).
I've checked all the codebase, these were the only cases I found.

Remove :since metadata when @doc false

---

lib/elixir/lib/string_io.ex

Caught this while perusing the docs. `string` makes more sense here.

Change name of first argument of StringIO.open/2 to string

---

lib/elixir/lib/string.ex
lib/ex_unit/lib/ex_unit/diff.ex

This extracts a functionality for a function that was previously buried inside `ExUnit.Diff`.

Add String.bag_distance/2

---

lib/elixir/src/elixir_bitstring.erl

Fix error typo in elixir_bitstring.erl

---

lib/elixir/lib/file.ex
lib/elixir/src/elixir_utils.erl

I've hit a situation where I need to call `File.exists?/1` in the inner loop of a bulk text processing application.
The erlang docs for [file:read_file_info/2](http://erlang.org/doc/man/file.html#read_file_info-2) suggest two optimizations that can speed up calls to this function:
> If the option raw is set, the file server is not called and only information about local files is returned. Note that this will break this module's atomicity guarantees as it can race with a concurrent call to write_file_info/1,2
> As file times are stored in POSIX time on most OS, it is faster to query file information with option posix.
I noticed a significant speedup when calling `read_file_info/2` with these options.
I'm not sure what are the implications of "only information about local files is …

Improve performance of File.exists?/1

---

lib/elixir/src/elixir_erl_for.erl

This speeds up comprehensions and remove dialyzer warnings.
Closes #8001

Use list_to_bitstring so we don't have to track binaries

---

lib/ex_unit/lib/ex_unit/assertions.ex
lib/ex_unit/test/ex_unit/assertions_test.exs

Show last message 10 from message mailbox instead of first 10 on tests fails on assert_receive, because usually errors are about the last messages

Show last n messages from mailbox on assert receive fail

---

lib/mix/lib/mix/compilers/elixir.ex
lib/mix/test/mix/tasks/compile.elixir_test.exs
lib/mix/test/mix/umbrella_test.exs

Prior to this commit, a protocol change in a path
dependency would only be reconcolidated if there at
least a runtime change associated to it. This commit
makes it so changes in local deps always triggers
a potential reconsolidation.
Closes #5987

Reconsolidate protocols if stale local deps change

---

lib/mix/lib/mix/dep.ex
lib/mix/test/mix/dep_test.exs

Accordingly mark top level optional dependencies from child deps

---

lib/elixir/src/elixir_expand.erl
lib/elixir/src/elixir_rewrite.erl
lib/elixir/src/elixir_utils.erl
lib/elixir/test/elixir/kernel/expansion_test.exs

Until now, we left rewriting operators in matches to Erlang. This forced
us to inherit Erlang semantics, especially for the ++ operator, that
only allows lists of integers on the left side inside matches. The new
implementation just rewrites this operator regular improper list matching.
Additionally we rewrite matching on -/1 and +/1 operators to number
literals - matching with those operators and variables was never
supported.
Additionally do a bit of housekeeping and refactor code around rewriting
and validating remote calls.

Rewrite match operators in elixir

---

lib/elixir/lib/kernel.ex
lib/elixir/lib/kernel/utils.ex
lib/elixir/lib/macro.ex
lib/elixir/lib/protocol.ex
lib/elixir/src/elixir_quote.erl
lib/elixir/src/elixir_rewrite.erl
lib/elixir/test/elixir/kernel/guard_test.exs
lib/elixir/test/elixir/kernel/lexical_tracker_test.exs
lib/elixir/test/elixir/kernel/quote_test.exs
lib/elixir/test/elixir/kernel_test.exs
lib/elixir/test/elixir/macro_test.exs

Consider the following example:
defmodule NestedQuote do
defmacrop macro(arg) do
quote bind_quoted: [arg: arg] do
quote bind_quoted: [arg: arg], do: String.duplicate(arg, 2)
end
end
defmacro __using__(_) do
quote do
def test do
unquote(macro("foo"))
end
end
end
end
defmodule UseNestedQuote do
use NestedQuote
end
It has two macro expansions, one inside __using__/1 when it invokes
macro/1, and another when used. The issue, however, is that the
`arg` of `String.duplicate(arg, 2)` gets tagged with the context
of `macro/1` but it should be tagged with the context of `__using__`
since it is a quote inside a quote. This patch addresses this.
Closes #7709

Delete counter for vars in nested quotes

---

lib/elixir/lib/system.ex

This is fixed upstream - but reading through the docs for 1.7.1 it caught me out.

Move parentheses in System.cmd() docs

---

lib/elixir/src/elixir_aliases.erl

Removes this warning:
```
Recompile: src/elixir_aliases
src/elixir_aliases.erl:36: Warning: variable 'Counter' is unused
```

Fix unused variable warning

---

lib/elixir/lib/calendar/iso.ex

While building the dictionaries for KronicDeth/intellij-elixir#1169, I spotted this typo.

Fix typo secon -> second

---

lib/iex/test/iex/helpers_test.exs

Due to race conditions, the capturing logic introduced by `ExUnit.CaptureLog.capture_log/2` might not be there when the error messages logged by the Erlang's code server arrived. If that happens, this error message is printed:

Remove error message from IEx test suite

---

lib/elixir/test/elixir/code_formatter/general_test.exs
lib/elixir/test/elixir/fixtures/calendar/holocene.exs
lib/mix/lib/mix/tasks/xref.ex
lib/mix/test/mix/dep_test.exs

* Fix typos in comments
* overriden -> overridden
* Syntatically -> Syntactically
* Propleptic -> Proleptic
* unreacheable -> unreachable

Fix comment typos

---

lib/elixir/lib/access.ex
lib/elixir/lib/application.ex
lib/elixir/lib/calendar/iso.ex
lib/elixir/lib/code.ex
lib/elixir/lib/kernel/special_forms.ex
lib/elixir/lib/list.ex
lib/elixir/lib/tuple.ex
lib/elixir/test/elixir/kernel/deprecated_test.exs
lib/elixir/test/elixir/kernel/guard_test.exs
lib/elixir/test/elixir/kernel/impl_test.exs
lib/ex_unit/lib/ex_unit/callbacks.ex
lib/logger/lib/logger.ex
lib/mix/lib/mix/tasks/cmd.ex
lib/mix/lib/mix/tasks/profile.cprof.ex
lib/mix/lib/mix/tasks/profile.eprof.ex
lib/mix/lib/mix/tasks/profile.fprof.ex
lib/mix/test/mix/dep_test.exs

Added literals spell checking support for IntelliJ Elixir, so found some more typos when compiling the dictionary against elixir-lang/elixir.
* misisng -> missing
* Fix typo in callback reference
* curently -> currently
* overriden -> overridden
* intested on -> interested in
* unecessary -> unnecessary
* resued -> reused
* Additonally -> Additionally
* preferrable -> preferable
* chuncks -> chunks
* non-sensical -> nonsensical
* mutiple -> multiple

Fix typos in literals (strings/charlists)

---

lib/elixir/lib/string.ex

Hi all,
little typo fixed:
`this functions takes` → `this function takes`.
Cheers!

Fix typo in String.to_charlist/1 doc

---

lib/elixir/src/elixir_expand.erl

`elixir_env:mergea(EV, EC)` is always equivalent to `EV` so we can avoid the operation

Small optimization on expand_args/2

---

lib/elixir/src/elixir_bitstring.erl

`elixir_env:mergea(EV, EC)` is always equivalent to `EV` so we can avoid the operation.
Similar to #8069

Small optimization on elixir_bitstring:expand/4

---

lib/elixir/src/elixir_env.erl
lib/mix/test/mix/tasks/compile.elixir_test.exs

Mention that adding a underscore can address it and remove the concept of "leaking vars".

Improve unused variable warnings

---

lib/mix/lib/mix/tasks/test.ex

The list of cli options for `mix test` was alphabetized. This moves `--failed` to the correct place.

Move --failed flag to alphabetize cli options

---

lib/ex_unit/lib/ex_unit.ex
lib/ex_unit/lib/ex_unit/runner.ex
lib/ex_unit/mix.exs
lib/ex_unit/test/ex_unit_test.exs
lib/mix/lib/mix/tasks/test.ex

This is a first take at the `after_suite/1` callback in ExUnit. I've
done basic testing by making this work with an app on my local machine,
but I'm going to think about automated tests tomorrow. I also still
need to document this better, but I wanted to get this up just to make
sure this implementation is along the lines of what y'all are looking
for.
Eventually resolves #8082

First stab at implementation of `after_suite/1` callback

---

lib/ex_unit/lib/ex_unit.ex

There was a `:logs` key that was included in the struct and in the
documentation, but wasn't included in `ExUnit.Test.t()`.

Add missing key to type in `ExUnit.Test`

---

lib/elixir/lib/module.ex

Erlang uses this attribute to export types, but Elixir abstracts it via `@type`, `@typep` and `@opaque`.
Besides, adding `@export_type` to a module does not have any effect; and it's not documented.

Remove check for legacy @export_type attribute

---

lib/elixir/lib/inspect/algebra.ex

To improve readability and usage.

Rename inspect to inspect_opts in Inspect.Algebra

---

lib/mix/lib/mix/dep.ex
lib/mix/lib/mix/tasks/compile.app.ex
lib/mix/lib/mix/tasks/deps.ex
lib/mix/test/mix/dep_test.exs

Since those values are not stored on Hex, we should not
expect them to be available on Mix.Dep.cached. Instead
we traverse the deps in `mix.exs` to lift this information.

Consider :runtime and :app from mix.exs

---

lib/ex_unit/lib/ex_unit.ex
lib/ex_unit/lib/ex_unit/formatter.ex

This includes documentation explicitly allowing the passing of arbitrary
configuration options in `ExUnit.configure/1`, and also tells how to do
runtime configuration of custom formatters by using this arbitrary
configuration.

Update docs for `ExUnit.configure/1` and `ExUnit.Formatter`

---

lib/ex_unit/lib/ex_unit/doc_test.ex
lib/ex_unit/test/ex_unit/doc_test_test.exs

It's a weird case, but I guess that's how it should behave according to the semantics of `:only`.
Raising an `ArgumentError` could be an alternative :)

Do not run doctests with empty :only option

---

lib/logger/lib/logger.ex

`Logger.add_backend/1,2` and `Logger.remove_backend/1,2` are specced to only allow atoms as backends, while `Logger.configure_backend/2` allows backend to be of the more general `backend` type. But both `add_backend` and `remove_backend` work fine with the more generic `backend` type, so the specs should be extended to cover that type.
The specs were introduced with c24a13ebf8, while the spec for `configure_backends` was introduced in aeefd59b15 (with a small fix in b98421fe51).

Fix Logger spec for functions working with backends

---

lib/elixir/lib/file.ex

Hi all,
changed wording in `File.exists?/2` doc from 
`It can be regular file,…` to `It can be a regular file,…`
Cheers!

Fix typo in File doc

---

lib/elixir/lib/kernel/special_forms.ex

This way I hope people will not fall into the trap that no else has different error semantics, as mentioned above in the docs.

Docs: change wording about WithClauseError

---

lib/elixir/lib/exception.ex
lib/elixir/lib/file.ex
lib/elixir/pages/Library Guidelines.md
lib/iex/lib/iex/helpers.ex
lib/mix/lib/mix/public_key.ex
lib/mix/lib/mix/scm.ex
lib/mix/lib/mix/tasks/format.ex
lib/mix/lib/mix/utils.ex
lib/mix/test/mix/dep_test.exs
lib/mix/test/mix/tasks/format_test.exs

Standardize use of this expression.
While both accepted, Google Books Ngram Viewer shows that "file system"
is the prefered one.

Use "file system" instead of "filesystem"

---

lib/elixir/pages/Guards.md

The previous explanation here talked about failing guards, but it wasn't
clear to me that exceptions were the specific kind of failure where
multiple guards are more correct than multiple expressions separated by
`or`.

Clarify that multiple guards are useful for exceptions

---

lib/elixir/lib/enum.ex

* Replace `zip/*` with `zip/1` and `zip/2` to enable linking
* Use relative linking for functions within the same module
cc @eksperimental

Minor tweaks to Enum documentation

---

lib/elixir/pages/Guards.md

Fix typo in Guards.md

---

lib/elixir/lib/enum.ex

Hi all, 
added a missing word:
`…function a truthy value.` → `…function returns a truthy value.`
Cheers!

Fix typo in Enum.filter/2 @doc

---

lib/mix/lib/mix/scm/git.ex
lib/mix/test/mix/tasks/deps_test.exs
lib/mix/test/test_helper.exs

This can cause problems with some user configurations as such flags can
introduce unwanted output/behaviour in some test cases.

Do not use user defined templateDir and hooksDir

---

lib/elixir/lib/path.ex

Related to https://github.com/elixir-lang/elixir/pull/8147
As documented in [`filelib:wildcard/1`](http://erlang.org/doc/man/filelib.html#wildcard-1).

Document Path.wildcard/2 expects / dir separator

---

lib/elixir/lib/version.ex

It used to be used by public function but hasn't been for a while.

Remove Version.matchable/0 type

---

lib/elixir/lib/tuple.ex

Hello! Saw this little bugger when I was reading some tuple docs, thought I'd help out!

Fix small curly typo in tuple docs

---

lib/elixir/lib/task.ex

This isn't stated explicitly, but it is true as far as I can tell and there is already [a test that requires ordered output](https://github.com/elixir-lang/elixir/blob/v1.7.3/lib/elixir/test/elixir/task_test.exs#L315-L325).

Add note to `Task.yield_many` about output ordering

---

lib/elixir/lib/calendar/iso.ex
lib/elixir/test/elixir/calendar/iso_test.exs

👋 
This is a fix for https://github.com/elixir-lang/elixir/issues/8128
tldr; it was a bug with the 1st of January, on negative leap years - converting back from `iso_days` gave us the 32nd of December on the previous year.

Fix for converting from negative iso days on New Year in a leap year

---

lib/elixir/src/elixir_expand.erl
lib/elixir/test/elixir/kernel/expansion_test.exs

When left side is expanded but become invalid, the expansion result in the AST leaking for the user, for example:
```
iex(1)> __ENV__.line.foo
{{:., [line: 1], [1, :foo]}, [line: 1], []}
```
This checks the expanded left to ensure that it's safe

Fix invalid expansion for remote

---

lib/elixir/lib/enum.ex
lib/elixir/lib/kernel.ex
lib/elixir/lib/stream.ex

Additionally, improve documentation of functions.
Add @typedoc to Enum.index/0 and Stream.index/0 types.

Revise use of position in Enum module, and replace it with index

---

lib/elixir/Emakefile

[Erlang's make](http://erlang.org/doc/man/make.html) does not document it, neither the docs nor the codebase of the [Erlang's compiler](http://erlang.org/doc/man/compile.html). The options `basic_validation` and `strong_validation` exist though, but not `strict_validation`.
I cloned the [`Erlang/OTP` repo](https://github.com/erlang/otp) and search for `strict_validation` on the branches `maint-17`, `maint-18`, `maint-19`, and `master`. Nothing was found.
I've also tried looking on Internet, but I couldn't find any documentation nor any article on the matter. However, I did found other Erlang repos containing `strict_validation` 😕 
Removing the flag seems to not have any effect, the codebase compiles and all the tests pass.

Remove invalid flag from Emakefile

---

lib/iex/test/iex/helpers_test.exs

Reduces the chances of #8183. Related to https://github.com/elixir-lang/elixir/pull/8055.
I've investigated a bit more about this issue. If I understood well the code, the Erlang's code server sends the error message (`[error] Can't load module ':lists' that resides in sticky dir`) to the Erlang's `:logger`; the Elixir's `Logger` is added as a handler of the Erlang's `:logger`; and the `ExUnit.CaptureLog` proxy is added as a handler of Elixir's `Logger` when `capture_log/2` is used (and the `:console` backend is removed). 
Thanks to `Logger.flush/0`, we can be sure that all the messages sent to Elixir's `Logger` during the execution of the function are consumed by all the Elixir's `Logger` handlers. However, that function does not have any effect on Erlang's `:logger`, nor `:logger` …

Rearrange assertions to (try to) capture error messages

---

lib/mix/lib/mix/dep.ex
lib/mix/lib/mix/rebar.ex
lib/mix/lib/mix/tasks/format.ex
lib/mix/test/mix/tasks/format_test.exs

- Use "regular expression" instead of the more informal term "regex"
- Use double quotes around commands

Improvements in Mix docs

---

lib/elixir/lib/kernel/typespec.ex
lib/elixir/test/elixir/kernel/errors_test.exs
lib/elixir/test/elixir/kernel/warning_test.exs

Raising a compiler error was correct because invalid typespecs were
generated. Unfortunately it also broke code that compiled and ran
without issues because the issue would only be noticed when running
dialyzer. To avoid breaking working code the error is changed to a
warning instead.

Change invalid typespec error to warning

---

lib/elixir/lib/stream/reducers.ex

Due to the check `acc_count >= limit` inside `chunk_fun`, `acc_count` can only be greater than `count` if `step` is bigger than `count`, there is no need for this check.

Small optimization in `Stream.Reducers.chunk_every/5`

---

lib/elixir/lib/version.ex

Adds a fix for #8205 to 1.7 branch. 
Note that in the master branch the fix is different (typespec has been removed), which means that this commit might cause a conflict between 1.7 branch and the master.

Fix typespec in Version

---

lib/elixir/lib/macro/env.ex

The way it's phrased now doesn't tell what concrete values can `context` contain.

Clear up `Macro.Env.context` description in the documentation
