elixir-lang/elixir

lib/elixir/pages/Typespecs.md
Related to https://github.com/elixir-lang/elixir/issues/5800#issuecomment-418693648
=> Clarify the usage of 'var' keyword in spec guards

lib/ex_unit/lib/ex_unit/filters.ex
=> Improvements in documentation of ExUnit.Filters

lib/elixir/src/elixir_import.erl, lib/elixir/test/elixir/kernel/errors_test.exs
=> Raise errors with duplicated entries on import

lib/mix/lib/mix/tasks/new.ex
Ref: https://github.com/phoenixframework/phoenix/commit/fe57005d201af71427ebd83a9bedf34e089f81ca
=> Improve wording in generated umbrella config.exs

lib/ex_unit/lib/ex_unit.ex, lib/iex/lib/iex.ex, lib/iex/lib/iex/helpers.ex
=> Link to IEx.pry correctly

lib/elixir/src/elixir_erl_try.erl, lib/elixir/test/elixir/fixtures/dialyzer/try.ex, lib/elixir/test/elixir/kernel/dialyzer_test.exs
=> Remove `Guard test tuple_size(...) can never succeed` dialyzer warning on try

lib/elixir/lib/registry.ex
This doc test uses the same name as the doc test for match/4 causing a race condition
Spotted at https://travis-ci.org/elixir-lang/elixir/jobs/429080162
=> Fix registry doc test

lib/elixir/lib/record.ex
Hi all,
a few suggestions of improvements to `Record` docs.
Cheers!
=> Improve Record @docs

lib/elixir/lib/module.ex
=> Improve docs for @impl

lib/elixir/lib/kernel/typespec.ex, lib/elixir/test/elixir/kernel/warning_test.exs
=> Don't raise undefined type errors on invalid type annotations

lib/mix/lib/mix/local/installer.ex, lib/mix/lib/mix/tasks/archive.install.ex
Minor thing spotted while reviewing https://github.com/elixir-lang/elixir/pull/8253
=> Use Git, GitHub, Hex instead of git, github, hex

lib/elixir/lib/kernel/parallel_compiler.ex
This is also related to the flaky test: https://travis-ci.org/elixir-lang/elixir/jobs/437950338
=> Wait for worker termination in parallel compiler

lib/elixir/lib/task/supervised.ex
Related to https://github.com/elixir-lang/elixir/pull/8239
As discussed in https://github.com/elixir-lang/elixir/pull/8259#discussion_r223600811
=> Send and handle kills concurrently in Task.Supervised

lib/elixir/test/elixir/task/supervisor_test.exs
=> Typo in supervisor_test.exs

lib/elixir/lib/kernel/typespec.ex, lib/elixir/lib/protocol.ex, lib/elixir/pages/Typespecs.md, lib/elixir/test/elixir/typespec_test.exs, lib/mix/lib/mix/tasks/xref.ex
Replace "builtin" with "built_in" and "built-in"
=> Standardize use of "built-in" term

lib/elixir/lib/code.ex, lib/elixir/lib/port.ex, lib/elixir/lib/process.ex, lib/ex_unit/lib/ex_unit/doc_test.ex, lib/mix/lib/mix/dep.ex
as opposed to the informal one "For more info"
[ci skip]
=> Use the formal expression "For more information"

lib/mix/lib/mix/tasks/cmd.ex, lib/mix/lib/mix/tasks/xref.ex
=> Document missing auto-reenabled tasks xref and cmd

lib/elixir/lib/kernel/typespec.ex, lib/elixir/lib/module.ex, lib/elixir/src/elixir_module.erl, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/typespec_test.exs
Port of: https://github.com/elixir-lang/elixir/commit/c190f09d5cbb1e79b510ea4332c65a7717aa9eb8
=> Allow typespec attrs to be used as module attrs

lib/elixir/src/elixir_expand.erl, lib/elixir/test/elixir/kernel/errors_test.exs
Addresses #8283.
Let me know what you think!
Thanks
=> Improve error message for invalid quoted expression

lib/elixir/src/elixir_map.erl, lib/elixir/test/elixir/kernel/warning_test.exs
=> Avoid errors with more than one duplicated key

lib/ex_unit/lib/ex_unit/case.ex
As per issue mentioned here: https://github.com/elixir-lang/elixir/issues/8362
I think this updated comment + example will make things clearer for the next viewer :). Let me know of any suggestions!
Thanks
=> Update documented example for ExUnit register_attribute

lib/elixir/src/elixir_bitstring.erl, lib/elixir/test/elixir/kernel/expansion_test.exs
=> Expand operands in size*unit bitstring modifier

lib/mix/test/test_helper.exs
...in Mix test_help.exs, and improve code clarity.
=> Remove code duplication by creating remove_colons/1 private function

CHANGELOG.md
I saw this wasn't included in the changelog and figured folks might want to know it was added.
=> Add missing ExUnit improvement to CHANGELOG [ci-skip]

lib/mix/lib/mix/tasks/compile.app.ex, lib/mix/test/mix/dep_test.exs
=> Consider :only from deps in compile.app

lib/elixir/lib/range.ex
Couple of proposals for the documentation of `Range`.
=> Improve the documentation of Range

CHANGELOG.md
=> Change wording from "change" to "rebind"

CHANGELOG.md, lib/elixir/lib/range.ex, lib/elixir/test/elixir/range_test.exs
Wanted to use `Range.disjoint?/2` for [today's Advent of Code](https://adventofcode.com/2018/day/3), so here's a proposal.
Doctests seem to provide good coverage and didn't implement separate unit tests... is that fine? Otherwise please just tell me and I'll add them.
=> Add `Range.disjoint?/2`

lib/elixir/test/elixir/list_test.exs, lib/iex/lib/iex/autocomplete.ex, lib/iex/lib/iex/config.ex, lib/mix/test/test_helper.exs
=> Replace calls to :lists Erlang module in files outside elixir/lib

lib/elixir/lib/list.ex
=> Elaborate on which characters are considered printable

lib/elixir/lib/record.ex, lib/elixir/test/elixir/record_test.exs
Closes #8059
Additionally some more refactorings of the Record module
---
This needs some more tests before merging
=> Make sure records use the dsetelement optimisation

lib/iex/lib/iex.ex
=> Properly stylize "Windows 10" and "PowerShell"

lib/iex/lib/iex.ex
Let's be politically correcty.
=> Use GNU/Linux instead of plain Linux

lib/elixir/lib/exception.ex, lib/elixir/test/elixir/exception_test.exs, lib/elixir/test/elixir/record_test.exs
This is the first pass on #8513. I would love any feedback you have on this.
=> add hint for behaviours on UndefinedFunctionErrors

lib/elixir/lib/kernel/typespec.ex, lib/elixir/test/elixir/typespec_test.exs
=> Perform {type_syntax, _} checks in Kernel.Typespec 

lib/elixir/pages/Compatibility and Deprecations.md
This is a PR for git branch v1.8
=> Add Supported Erlang/OTP versions for v1.8

lib/eex/lib/eex/tokenizer.ex, lib/eex/test/eex/tokenizer_test.exs, lib/eex/test/eex_test.exs
As further discussed here: https://github.com/elixir-lang/elixir/issues/8590#issuecomment-451407465
=> Improve eex tokenizer further

lib/elixir/lib/system.ex, lib/elixir/test/elixir/system_test.exs
The goal is to make them more accessible for #8595.
=> Add System.restart/0 and System.pid/0

lib/elixir/test/elixir/version_test.exs
- added assertions to exists test  to cover lines 409, 412, and 511
=> Improve coverage of Version.Parser

lib/elixir/lib/gen_server.ex
=> Fix typo in GenServer docs

lib/elixir/lib/module.ex
Original dicussion: https://github.com/elixir-lang/elixir/pull/8580#issuecomment-450598234
* Link to ExDoc in Module module
* Mention Code.fetch_docs/1 in doc related attributes in Module module,
=> Mention Code.fetch_docs/1 in doc related attributes in Module module,

lib/ex_unit/lib/ex_unit/capture_io.ex
=> Minor grammar fix in ExUnit.CaptureIO

CHANGELOG.md
This needs to also be updated in the release notes :)
=> Correct release date of v1.8 in CHANGELOG

lib/elixir/lib/kernel.ex
Updates Kernel.round/1 to describe what happens on half.
=> Update Kernel rounding documentation

lib/elixir/lib/calendar/date.ex, lib/elixir/lib/list.ex
ExDoc is not formatting then as Elixir code
=> Fix indentation in doctests

lib/elixir/lib/kernel/typespec.ex, lib/elixir/lib/module.ex, lib/elixir/lib/protocol.ex, lib/elixir/test/elixir/typespec_test.exs, lib/iex/test/iex/helpers_test.exs
Ref: https://github.com/elixir-lang/ex_doc/issues/942
=> Update Module.spec_to_callback to keep existing specs and copy docs

lib/elixir/lib/list.ex, lib/elixir/pages/Syntax Reference.md, lib/iex/lib/iex/info.ex, lib/iex/test/iex/info_test.exs
Here's a set of three different commits.
Initially I realized the information in the IEx `i` helper was not accurate, trying to fix it let to investigate what was the proper definition of charlist, which let to having to create this newly introuce function List.charlist?/2.
Please don't squash the commit when/if merging
=> Charlist improvements

lib/elixir/lib/system.ex
=> Support SOURCE_DATE_EPOCH for reproducible builds

README.md
Adding a small comment on how to generate the docs in the epub format.
=> Add note about generating epub docs

lib/iex/lib/iex/broker.ex
Attempt to fix #8729
I'm not sure where is right place to add some tests.
=> Fixed IEx.pry crash when IEx (IEx.Broker) isn't running

lib/elixir/lib/kernel/special_forms.ex
Hi all,
just a few typos I seem to have come across.
Cheers!
=> Fix typos in Kernel.SpecialForms doc

lib/elixir/lib/kernel.ex
I was a bit confused by the description of `unless`. I think this is a bit clearer (fewer negations).
=> Improve docs for Kernel.unless

lib/elixir/lib/collectable.ex
Be explicit that we are talking about Collectable.into/1
and Enumerable.reduce/3
=> Reword docs about Collectable.into/1

lib/elixir/lib/dynamic_supervisor.ex
Hi all,
This fixes a small typo in DynamicSupervisor docs.
Cheers!
=> Fixes typo in DynamicSupervisor docs

lib/elixir/lib/kernel/special_forms.ex
Hi all, 
this aims to improve or update a few bits of `Kernel.SpecialForms` docs.
Cheers!
=> Improve Kernel.SpecialForms docs

lib/elixir/lib/uri.ex
This one has been laying around for over 3 years!
=> Improvements to the URI module

lib/elixir/test/elixir/list_test.exs
I noticed that there are missing tests for existing functions in the List module.
=> Adding missing List functions tests

lib/elixir/test/elixir/kernel/overridable_test.exs
These tests cover some edge cases.
=> Improve defoverridable test suite

lib/elixir/lib/module.ex, lib/elixir/test/elixir/kernel/docs_test.exs
=> Raise error when `@doc true`

lib/elixir/lib/kernel.ex, lib/elixir/lib/module/locals_tracker.ex, lib/elixir/src/elixir_def.erl, lib/elixir/src/elixir_dispatch.erl, lib/elixir/src/elixir_expand.erl, lib/elixir/src/elixir_locals.erl, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/module/locals_tracker_test.exs
=> Raise if a macro is invoked before its definition

lib/elixir/lib/inspect.ex
This is an attempt to fix Dialyzer warnings.
Closes #8749
=> Avoid Dialyzer warnings on Inspect

lib/elixir/lib/enum.ex
=> Clarify Enum.all? and Enum.any? for empty lists

lib/elixir/lib/module.ex, lib/elixir/test/elixir/kernel/docs_test.exs
=> Make error msg on invalid @doc more natural and readable

lib/elixir/lib/kernel.ex
@eksperimental had a good suggestion but #8848 was already merged
=> Tiny docs change falsy value

lib/elixir/lib/kernel.ex, lib/elixir/src/elixir_map.erl, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/kernel_test.exs
=> Validate __struct__ key in map returned by __struct__/0,1

lib/logger/lib/logger.ex
I added some information about the precedence of the logger levels.
=> Update documentation of Logger

lib/elixir/lib/system.ex
=> Improve System.build_info/0 spec

lib/elixir/lib/behaviour.ex, lib/elixir/lib/code/formatter.ex, lib/elixir/lib/code/identifier.ex, lib/elixir/lib/code/typespec.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/kernel/typespec.ex, lib/elixir/lib/macro.ex, lib/elixir/test/elixir/inspect_test.exs, lib/elixir/test/elixir/keyword_test.exs, lib/elixir/test/elixir/macro_test.exs, lib/elixir/test/elixir/typespec_test.exs, lib/ex_unit/lib/ex_unit/assertions.ex, lib/iex/lib/iex/introspection.ex
=> Quote :: to avoid ambiguity

lib/elixir/lib/kernel/typespec.ex, lib/elixir/test/elixir/typespec_test.exs
fix issue
https://github.com/elixir-lang/elixir/issues/8888
and add three test case
=> Handle underscore variables (_, _foo) in typespecs

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel_test.exs
=> Raise when retrieving capitalized module attribute

lib/elixir/lib/version.ex
Fix dialyzer warning introduced on #8920
=> Make Version.Requirement opaque

lib/elixir/lib/io.ex
=> Add a section about iodata to the IO docs

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel_test.exs, lib/elixir/test/elixir/macro_test.exs
Bug was introduced in 08829b3709a0b7445b5a33f8d1491a9e735fdf15
=> Fix bug in Kernel.in/2 when right is []

lib/elixir/lib/option_parser.ex
The term "switch" is used exclusively here, "flag" is more common I think. I added some prose in the beginning to try and make this more clear.
Wikipedia has some (hopefully) default language for this: https://en.wikipedia.org/wiki/Command-line_interface#Command-line_option
=> Define what a "switch" is

lib/elixir/lib/code.ex, lib/elixir/lib/code/formatter.ex, lib/elixir/test/elixir/code_formatter/calls_test.exs
=> Support :force_do_end_blocks in formatter

lib/elixir/lib/string.ex
Please let me know if it makes sense :peace_symbol:
=> Be more descriptive in trim functions

lib/elixir/lib/application.ex
Was going through new changes and found this little typo.
=> fix typo OPT -> OTP on elixir application.ex

lib/iex/lib/iex/cli.ex
Thanks to @tsloughter for the feedback.
=> Set ticktime and autohost on IEx --remsh

lib/mix/lib/mix/tasks/release.ex
=> fix typo on techniques section of release mix task

CHANGELOG.md
This change was left behind when the CHANGELOG was updated
=> Add Kernel.in/2 to bug fixes in CHANGELOG.md

lib/logger/lib/logger.ex, lib/logger/lib/logger/config.ex, lib/logger/mix.exs, lib/logger/test/logger/config_test.exs
=> Make sure Logger v1.8 does not get stuck in discard mode

lib/elixir/lib/integer.ex, lib/elixir/test/elixir/integer_test.exs
Please see discussion
https://github.com/elixir-lang/elixir/pull/8777#issuecomment-478996518
/cc @michalmuskala
=> Revert #8777

lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/kernel/errors_test.exs
Address issue #9047 
I am not sure if this PR resolve the issue mentioned. If not, feel free to point me to the right direction. Thanks.
=> Improve heredoc error message

lib/elixir/lib/stream.ex
Before we hadn't added guards to functions in the `Stream` module because the error message for invoking a function with the wrong number of arguments was better than the `FunctionClauseError`. Now that `FunctionClauseError`s are better and display the failed clauses and everything, having guards in `Stream` functions means that we can fail fast in many cases instead of waiting to fail until the stream is realized.
=> Add guards to the Stream module

RELEASE.md, SECURITY.md
GitHub is adding this new feature (still in beta), but I think it is great to have a file dedicated to this
=> Add SECURITY.md (Security Policy)

NOTICE, lib/elixir/lib/float.ex, lib/elixir/lib/string.ex, lib/elixir/lib/version.ex, lib/elixir/pages/Unicode Syntax.md, lib/elixir/test/elixir/string_test.exs, lib/elixir/unicode/properties.ex
The servers are automatically redirecting from http:// to https://
=> Use https instead of http when available

lib/mix/lib/mix/release.ex, lib/mix/test/mix/release_test.exs
=> Handle multiple versions of the same app during releases

lib/elixir/lib/module.ex
Related to https://github.com/elixir-lang/elixir/issues/9084
=> Clarify syntax for custom Module attributes

lib/elixir/lib/module/locals_tracker.ex, lib/elixir/src/elixir_locals.erl, lib/elixir/test/elixir/kernel/errors_test.exs
=> Raise on recursive macros

lib/mix/test/mix/release_test.exs
This test copied almost the entire Erlang installation in order to create the scenario for the test. This process was really slow, to the point that Windows builds in the CI were failing because the copy was taking longer than 60 seconds to complete.
Fortunately, the test do not require all the files. This PR changes the test to strictly copy the files required for the test.
=> Improve performance of release tests

lib/iex/lib/iex/autocomplete.ex, lib/iex/test/iex/autocomplete_test.exs
=> iex: Erlang Module Type Autocomplete

lib/iex/lib/iex/introspection.ex, lib/iex/test/iex/helpers_test.exs
=> IEx: Sort Types in `t` helper

lib/elixir/lib/agent.ex
I thought adding an Example here might be helpful. Let me know what you think!
=> Added Example for Agent.cast/2

lib/elixir/lib/config.ex
A very very minor contribution.
=> Fix typo in Config docs

lib/elixir/lib/system.ex
See http://erlang.org/doc/man/erlang.html#type-time_unit
=> More details about the :native time unit, from the Erlang docs

lib/elixir/lib/agent.ex
Hopefully this example is useful.
😄
=> Example added for Agent.cast/4

lib/elixir/lib/agent.ex
Thought this might be useful too!
I plan to take a look at some of the docs and try to gold plate them but if there's a specific place people want me to focus my efforts on improving docs let me know!
=> Example added for Agent.update/4

lib/elixir/lib/port.ex
Fixes residual issues with 47d017be67e7aaafe7dee2bdfcdbfd9915091e6b
Discussed in issue #9171
=> Improve zombie termination script

lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/test/ex_unit/describe_test.exs
=> Add test for @describetag outside of describe block

lib/mix/lib/mix/project.ex, lib/mix/test/mix/project_test.exs
Fixes #9188.
(@josevalim I think this is what you meant?)
=> MIX_BUILD_PATH specifies the build_path (and has the env added on to it)

lib/elixir/lib/application.ex, lib/logger/lib/logger/app.ex, lib/logger/lib/logger/config.ex
=> Do not emit undefined warnings in old Erlang/OTP versions

lib/elixir/lib/module.ex, lib/elixir/src/elixir_module.erl, lib/elixir/test/elixir/kernel/warning_test.exs, lib/elixir/test/elixir/module_test.exs
Original proposal here: https://groups.google.com/d/msg/elixir-lang-core/4b9-yQ5J9KE/mAputTVBBAAJ
=> Add Module.has_attribute?/2

lib/elixir/lib/module/checker.ex, lib/elixir/test/elixir/module/checker_test.exs
=> Use Code.compiler_options[:no_warn_undefined]

lib/elixir/lib/module.ex, lib/elixir/src/elixir_module.erl
From this discussion
https://github.com/elixir-lang/elixir/pull/9200#discussion_r300868756
=> Change attributes to warn_attributes for clarity

lib/elixir/lib/access.ex
Hey all,
I thought this might be helpful!
💜
=> Example added for Access.get_and_update/3

lib/elixir/lib/function.ex, lib/elixir/test/elixir/function_test.exs
as proposed by Alexey Nikitin (@tank-bohr ?), introduce the identity function as an alternative
to using `&(&1)`. 
edit:
if Alexey wants to create this PR, I'd be happy to delete mine
=> introduce identity function

lib/elixir/lib/range.ex
I thought this would be nice to have!
=> Range.new example

lib/elixir/lib/node.ex
I thought this would be nice to have as well.
=> Node.start example

lib/elixir/lib/file.ex
=> Update @doc of File.open/2

lib/elixir/lib/path.ex, lib/elixir/test/elixir/path_test.exs
PR for [Issue Path.join/2](https://github.com/elixir-lang/elixir/issues/9284)
=> Fix join/2 dot result at path end

lib/elixir/lib/enum.ex
=> Correct guard in Enum slice optimization

lib/elixir/lib/module.ex
=> Fix documentation for ordering in @after_compile

lib/elixir/lib/collectable.ex
- fixing up awkward wording on Collectable protocol documentation
=> fixed awkward wording in the documentation

lib/mix/lib/mix/hex.ex
Closes #9356 
Ref: https://github.com/hexpm/hex/commit/f34518e143a59118589d65494ab4dc5181e782db
=> Bump Hex dependency to v0.19.0

lib/iex/lib/iex/helpers.ex
=> Fix documentation

lib/iex/lib/iex/evaluator.ex, lib/iex/lib/iex/helpers.ex, lib/iex/test/iex/helpers_test.exs
=> Don't allow cycles when loading .iex.exs

lib/elixir/lib/supervisor.ex
Minor documentation improvement
=> fix type details in child spec `:shutdown` documentation

lib/mix/lib/mix/tasks/release.ex
Just saw this while reading up on releases.
=> Minor typo in `mix release` docs

lib/elixir/lib/code.ex, lib/elixir/lib/kernel/parallel_compiler.ex, lib/elixir/lib/module/checker.ex, lib/elixir/lib/module/parallel_checker.ex, lib/elixir/src/elixir_compiler.erl, lib/elixir/src/elixir_module.erl, lib/elixir/test/elixir/code_test.exs, lib/elixir/test/elixir/fixtures/checker_warning.exs
=> Run checker on Code.require_file/1

lib/elixir/lib/macro/env.ex
Related: 69f8c2c77669f0a18f9315ad2c4f68bb7ef3f4f0
=> Macro.Env: Sort fields in documentation and code

lib/ex_unit/lib/ex_unit/case.ex
=> Fix ExUnit.Case.env/0 type

lib/elixir/lib/dynamic_supervisor.ex
I was reading through the docs and thought this bit read weird, so here's a PR that polishes the docs IMHO.
If y'all don't think this is helpful that's okay!
💚
=> DynamicSupervisor Documentation polish

lib/iex/lib/iex.ex, lib/iex/lib/iex/pry.ex
- function is an atom
- breaks/stops are non-negative-integers
=> Fix specs in IE break specs

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
=> Introduce Enum.map_intersperse

lib/iex/lib/iex/cli.ex, lib/logger/lib/logger/app.ex, lib/logger/test/logger_test.exs
This was missing after adding information about changing logger level
=> Translate logger level on startup

lib/logger/lib/logger/app.ex, lib/logger/lib/logger/filter.ex
This uses magical tango of self-deregistering filter.
=> Do not log that logger application is stopping

lib/elixir/lib/kernel.ex
I think this was missed on #9470
=> Add @doc :since to is_struct/1

lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/test/elixir/calendar/naive_datetime_test.exs
=> Add NaiveDateTime.local_now

lib/elixir/lib/application.ex, lib/logger/lib/logger.ex, lib/logger/lib/logger/counter.ex, lib/mix/lib/mix/task.compiler.ex
Brought to you by https://github.com/wojtekmach/app_manifest#usage :-)
=> Add missing doc annotations

lib/elixir/pages/Guards.md
[ci skip]
/cc @josevalim @ericmj @devonestes
=> Guards page: Copyediting the whole page

lib/mix/lib/mix/tasks/format.ex
=> Fix "mix format" docs mention to wrong section

lib/mix/lib/mix/release.ex, lib/mix/test/mix/release_test.exs
=> Only copy the relevant directories from erts

lib/elixir/lib/bitwise.ex
Related 1e4e05ef78b3105065f0a313bd0e1e78b2aa973e
/cc @ericmj
=> Documentation updates in Bitwise module and functions

CHANGELOG.md
I realized just now that this should also have been added to the changelog.
=> Update changelog with capture_io changes [skip ci]

lib/elixir/lib/regex.ex, lib/mix/lib/mix/tasks/release.ex, lib/mix/lib/mix/tasks/release.init.ex, lib/mix/lib/mix/tasks/test.ex
Follows 861cf504f0f838095b36d6eb65a9ce50ce846bdd
=> Use "operating system" instead of OS

README.md
This is missing from ffd8a5fa71765bd16cd5bf61c038a06a3ac5402a
=> Move the references from Travis CI to Cirrus CI

lib/elixir/lib/application.ex, lib/elixir/lib/calendar.ex, lib/elixir/lib/code/formatter.ex, lib/elixir/lib/file.ex, lib/elixir/lib/gen_server.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/macro.ex, lib/elixir/lib/map.ex, lib/elixir/lib/system.ex, lib/elixir/lib/uri.ex, lib/elixir/pages/Naming Conventions.md, lib/elixir/pages/Typespecs.md, lib/elixir/src/elixir_errors.erl, lib/elixir/src/elixir_expand.erl, lib/elixir/src/elixir_parser.yrl, lib/elixir/src/elixir_tokenizer.erl, lib/ex_unit/lib/ex_unit/capture_log.ex, lib/iex/lib/iex/helpers.ex, lib/mix/lib/mix/tasks/compile.erlang.ex, lib/mix/lib/mix/tasks/profile.fprof.ex, lib/mix/lib/mix/tasks/release.ex
=> Replace usage of "e.g."

lib/elixir/lib/uri.ex
Discussion:
https://github.com/elixir-lang/elixir/issues/9588#issuecomment-557803196
=> Use URI.parse/1 instead of building %URI{} manually whenever possible

lib/elixir/lib/uri.ex, lib/elixir/test/elixir/uri_test.exs
=> Raise if a non-absolute path is given with host or authority

README.md, lib/elixir/lib/calendar.ex, lib/elixir/lib/code.ex, lib/elixir/lib/io.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/kernel/special_forms.ex, lib/elixir/lib/macro.ex, lib/elixir/lib/registry.ex, lib/elixir/lib/system.ex, lib/elixir/pages/Compatibility and Deprecations.md, lib/elixir/pages/Library Guidelines.md, lib/elixir/pages/Naming Conventions.md, lib/elixir/pages/Patterns and Guards.md, lib/elixir/pages/Syntax Reference.md, lib/elixir/src/elixir_erl_compiler.erl, lib/elixir/src/elixir_import.erl, lib/elixir/src/elixir_map.erl, lib/iex/lib/iex.ex, lib/logger/lib/logger.ex, lib/mix/lib/mix/dep/converger.ex, lib/mix/lib/mix/tasks/archive.build.ex, lib/mix/lib/mix/tasks/escript.build.ex, lib/mix/lib/mix/tasks/release.ex, lib/mix/lib/mix/tasks/release.init.ex
Related discussion: https://github.com/elixir-lang/elixir/pull/9559
=> Replace usage of "etc."

.cirrus.yml
The auto-cancellation feature has been tested here
https://cirrus-ci.com/github/eksperimental/elixir/v4.0
and it works fine.
=> Abstract common settings in a template in .cirrus.yml

lib/elixir/lib/stream.ex, lib/elixir/test/elixir/stream_test.exs
In the optimized case with a single-element list returned from the
`next_fun`, call the stream function chain in a separate try/catch
block. If it errors out, call the `after_fun` with the new accumulator
returned from `next_fun`.
Previously the `after_fun` was called with the old accumulator in such
case.
=> Close with correct accumulator in Stream.resource/3

.cirrus.yml
=> Support FreeBSD in Cirrus CI

lib/elixir/lib/application.ex
=> Fix spelling mistake in docs

lib/elixir/lib/enum.ex
=> fix_process_when_non_integer_index_passed_in_Enum

lib/elixir/lib/code.ex, lib/elixir/lib/module/checker.ex, lib/elixir/test/elixir/module/checker_test.exs, lib/mix/lib/mix/cli.ex
=> Add option :all to :no_warn_undefined

lib/elixir/lib/module/types.ex, lib/elixir/lib/module/types/pattern.ex, lib/elixir/test/elixir/module/types/pattern_test.exs
=> Allow any type on the RHS of or/2

lib/elixir/lib/module/checker.ex, lib/elixir/lib/module/parallel_checker.ex, lib/elixir/src/elixir_erl.erl, lib/elixir/src/elixir_module.erl, lib/elixir/test/elixir/module/checker_test.exs
=> Do not warn for functions generated by Erlang compiler

lib/eex/lib/eex/compiler.ex, lib/eex/lib/eex/tokenizer.ex, lib/eex/test/eex/tokenizer_test.exs, lib/eex/test/eex_test.exs, lib/elixir/lib/code.ex, lib/elixir/lib/code/formatter.ex, lib/elixir/src/elixir.erl, lib/elixir/src/elixir_compiler.erl, lib/elixir/test/erlang/atom_test.erl, lib/elixir/test/erlang/control_test.erl, lib/elixir/test/erlang/function_test.erl, lib/elixir/test/erlang/match_test.erl, lib/elixir/test/erlang/operators_test.erl, lib/elixir/test/erlang/string_test.erl, lib/elixir/test/erlang/test_helper.erl, lib/iex/lib/iex/evaluator.ex
Additionally we add :column to Code.string_to_quoted*/2
=> Track column information in EEx if enabled

lib/ex_unit/lib/ex_unit/doc_test.ex
=> Fixed-width font for Kernel

lib/mix/lib/mix.ex, lib/mix/lib/mix/shell/io.ex, lib/mix/lib/mix/task.ex
I was frustrated trying to accomplish a few things with custom tasks and the shell, so I added some explanations and examples:
- Details about creating a custom Mix Task
- Examples for how change the current shell
- Example of using some shell commands, e.g. `yes?`
=> Improves docs for tasks and shell

lib/elixir/pages/Library Guidelines.md
=> Update Library Guidelines.md

lib/ex_unit/lib/ex_unit/assertions.ex
There were some confusing errors around this evaluation of the default
timeout at compile time, so now it's been moved to runtime.
Resolves #9744
=> Move evaluation of default timeout in ExUnit to runtime

lib/logger/lib/logger/utils.ex, lib/logger/test/logger/utils_test.exs
=> Fix logger truncate for multi-byte characters

lib/elixir/lib/access.ex
I've refactored a function of Access module based on [this guideline about pattern matching](https://erlang.org/doc/efficiency_guide/functions.html#pattern-matching). 
I'm glad if you review this patch. Thank you.
=> Optimize pattern match of access module's func

lib/ex_unit/lib/ex_unit/callbacks.ex
We lacked information on which process each callback is executed in, which is pretty important information.
=> Improve documentation for ExUnit callbacks

lib/elixir/lib/tuple.ex
=> fix_process_when_non_integer_index_passed_in_tuple_module_function

lib/logger/lib/logger.ex, lib/logger/lib/logger/handler.ex, lib/logger/test/logger_test.exs
=> Expose all logger levels

lib/elixir/lib/kernel/special_forms.ex, lib/elixir/src/elixir_import.erl, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/kernel/import_test.exs
Ref https://groups.google.com/d/msg/elixir-lang-core/QGU3ARQeL7w/AJMEtsYgBQAJ
=> Support `import Mod, only: :sigils`

lib/logger/lib/logger.ex, lib/logger/test/logger_test.exs
This implements it only in code. Documentation is not ready yet.
Ref #9465
=> Add structured logging

lib/logger/lib/logger.ex, lib/logger/test/logger_test.exs
=> Expose functions for setting per-module levels

.cirrus.yml, Makefile, lib/elixir/diff.exs
The new script performs a "BEAM-diff" in case of BEAM files.
Part of #9579
=> Improve 'check_reproducible' script

CHANGELOG.md
I don't need to explain this I guess 😄
=> Fix incorrect spelling

lib/elixir/lib/string.ex
(Possibly the most minor change of all time.)
=> Minor documentation correction

lib/mix/lib/mix/tasks/release.ex
=> Update release.ex documentation

lib/elixir/docs.exs
Ref https://github.com/elixir-lang/ex_doc/pull/1151
=> Update :skip_undefined_reference_warnings_on in docs.exs

lib/elixir/lib/enum.ex
* reference string instead of binary for both functions
* remove outdated reference to list joiner in map_join
=> update Enum.join and map_join docs

lib/elixir/lib/exception.ex, lib/elixir/lib/file.ex, lib/elixir/lib/io.ex, lib/elixir/lib/module/parallel_checker.ex, lib/elixir/lib/regex.ex, lib/elixir/lib/system.ex, lib/elixir/src/elixir_errors.erl
This PR changes mostly type specifications. The only code change is similar to the ones from #9961
=> Fix multiple dialyzer errors in the Elixir application

lib/elixir/lib/io/ansi/docs.ex, lib/elixir/test/elixir/io/ansi/docs_test.exs
=> Fixes deep nested lists inside docs

lib/mix/lib/mix/release.ex
- Update type to reflect that this is a struct
- Add overlays entry to the type
=> Update Mix.Release.t type specification

lib/elixir/lib/calendar/date.ex, lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/lib/calendar/time.ex
Closes https://github.com/elixir-lang/elixir/issues/9831
Added functions:
- Date.from_gregorian_days/2
- Date.to_gregorian_days/1
- NaiveDateTime.from_gregorian_seconds/3
- NaiveDateTime.to_gregorian_seconds/1
- Time.from_seconds_after_midnight/3
- Time.to_seconds_after_midnight/1
=> Add linear representation functions to Calendar types

lib/elixir/lib/task/supervised.ex, lib/logger/test/logger/translator_test.exs
Fixed the issue, now I will figure out how to write the test.
=> fixes issue #10024

bin/elixir.bat, lib/elixir/lib/io/ansi.ex, lib/iex/lib/iex.ex
=> Add ANSI color support for Windows

lib/ex_unit/lib/ex_unit.ex, lib/ex_unit/lib/ex_unit/callbacks.ex
Ref https://github.com/phoenixframework/phoenix_live_view/issues/887
=> Add ExUnit.fetch_test_supervisor/0

lib/elixir/lib/code/typespec.ex, lib/elixir/test/elixir/typespec_test.exs
=> Allow user to define a type named union

lib/mix/lib/mix/tasks/app.start.ex
This PR fixes the read of an app file when it is located inside an archive (.ez) file.
The bug was introduced in `v1.10` line with the introduction of `compile_env` feature.
=> Fix read of app file located in archive .ez file

lib/elixir/pages/patterns-and-guards.md
=> Update patterns-and-guards.md to fix a typo.

lib/elixir/lib/registry.ex
Lost some time to this one. :)
=> Clarify @doc for Registry.unregister_match/4

lib/elixir/lib/calendar/date.ex, lib/elixir/lib/calendar/datetime.ex, lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/lib/calendar/time.ex
Add `new!` to Date/Time/NaiveDateTime/DateTime. This also adds
`new` to DateTime.
Closes https://github.com/elixir-lang/elixir/issues/10063
=> Add new! to Calendar Types

lib/elixir/lib/calendar/datetime.ex
=> Adding gregorian seconds functions to DateTime

.cirrus.yml, lib/elixir/lib/config/provider.ex, lib/mix/lib/mix/tasks/release.ex, lib/mix/lib/mix/tasks/release.init.ex, lib/mix/test/mix/tasks/release_test.exs
=> Change release default mode to interactive

lib/elixir/lib/kernel.ex
=> Use Erlang/OTP "VERSION", instead of OTP "VERSION"

lib/mix/lib/mix/local/installer.ex, lib/mix/lib/mix/tasks/archive.install.ex, lib/mix/lib/mix/tasks/escript.install.ex, lib/mix/test/mix/local/installer_test.exs
=> Add --repo to archive.install and escript.install

README.md
=> Add GitHub Actions CI badge to README

lib/elixir/lib/kernel/cli.ex, lib/elixir/lib/path.ex, lib/elixir/test/elixir/kernel/cli_test.exs
=> Normalize paths before expanding them

lib/mix/lib/mix/local/installer.ex, lib/mix/lib/mix/tasks/archive.install.ex, lib/mix/lib/mix/tasks/escript.install.ex, lib/mix/test/mix/local/installer_test.exs
=> Properly handle --repo and --organization on *.install tasks

lib/elixir/test/elixir/kernel/cli_test.exs, lib/elixir/test/elixir/kernel/dialyzer_test.exs, lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/lib/ex_unit/runner.ex, lib/ex_unit/test/ex_unit/case_test.exs, lib/ex_unit/test/ex_unit/runner_stats_test.exs, lib/iex/test/iex/interaction_test.exs, lib/mix/lib/mix/tasks/new.ex, lib/mix/test/mix/cli_test.exs, lib/mix/test/mix/local_test.exs
https://groups.google.com/u/1/g/elixir-lang-core/c/GfwqeDGqVoA/m/YR-NLrAzBgAJ
As part of this PR, I've also started using the new feature in a few tests.
There is a lot more places where this could be used and I thought about
addressing that in future PRs, but let me know otherwise!
=> Add :tmp_dir tag to ExUnit

lib/elixir/lib/module/types/pattern.ex, lib/elixir/test/elixir/module/types_test.exs
=> is_map_key/2 should add optional keys

lib/mix/lib/mix/release.ex, lib/mix/test/mix/release_test.exs
=> Change erl binary chmod in release to 755

lib/elixir/lib/gen_server.ex
I think it could help to understand better the example
=> Add missing subtract client function in calculator example

CHANGELOG.md
=> Fix minor typo in CHANGELOG

CHANGELOG.md
See how it looks today: https://hexdocs.pm/elixir/master/changelog.html
=> Update syntax highlighting on CHANGELOG.md

lib/elixir/lib/macro.ex, lib/elixir/lib/module.ex
=> [skip CI] Use "bytecode" instead of "byte code"

lib/elixir/lib/supervisor/spec.ex, lib/ex_unit/lib/ex_unit.ex, lib/ex_unit/lib/ex_unit/formatter.ex
This is a first round of commits. The second one will be submitted once this feature https://github.com/elixir-lang/ex_doc/issues/1192 is introduced in ExDoc (which is already implemented by the way)
=> Fix warnings detected by future version of ExDoc

lib/elixir/lib/inspect/algebra.ex, lib/logger/lib/logger/utils.ex
Additionally it rephrases docs.
************************
I made a typo in `:infinity` and it was giving a cryptic error not pointing me to what was wrong. ArithmeticError
=> Update typespecs and enforce with and limit in Inspect.Algebra

lib/elixir/lib/enum.ex, lib/elixir/pages/operators.md
Introduced in: 9a9b1f48bc5a63f364e3c5329ceccea7b67fd3b7 (#9903)
/cc @glv
=> Clarify use of Enum.member?/2 in in/2 operator

lib/elixir/lib/bitwise.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/kernel/special_forms.ex, lib/elixir/pages/operators.md
With this commit every operator in Elixir has been given a name, AFAIK.
=> Improvements to operator functions and page

lib/elixir/lib/keyword.ex
Inspired by c1a538e4a8bee7bc1c5be803534b8e4ee467c086 (#10223)
* Fixes the spec of Keyword.get_and_update!/3 that was missing the :pop return value for the update function
* It removes the concept of the "get" value and replaced it consistently with "current value"
* Renames "initial" argument to "default"
* Uses "existing value" when applicable
=> Make spec clearer for update functions in Keywords

lib/ex_unit/lib/ex_unit.ex
ExDoc doesn't take care of that
=> Sort t:ExUnit.state/0 fields alphabetically

lib/ex_unit/lib/ex_unit/cli_formatter.ex
Sorry, I fogot this change in my previous PR
=> Use Path.relative_to_cwd/1 in file path for slowest test

lib/mix/lib/mix/rebar.ex
Related rebar3 PR which add git_subdir: https://github.com/erlang/rebar3/pull/2239
Hoping to get feedback while I figure out adding tests.
=> support rebar3 resource type git_subdir

lib/logger/lib/logger.ex
Closes #10279
Alternative to #10280
=> Pass code location to :logger.macro_log/4

lib/elixir/lib/kernel.ex
Just thought I would add a small mention to this as it has caused a few headaches to me ahah!
Happy to add more if needed or move it to a different place.
=> Mention right associativity of the `--/2` operator in docs

lib/elixir/diff.exs
Hi all, this fixes a small typo.
Cheers!
=> Fix typo in Diff doc

lib/mix/lib/mix/tasks/test.coverage.ex, lib/mix/test/fixtures/umbrella_test/apps/bar/mix.exs, lib/mix/test/mix/tasks/test_test.exs
I would love to also add a test case for that, but I really did not find a way to insert project options in the test cases.
=> Added ignore module option to coverage report

lib/elixir/lib/collectable.ex
It is not clear what original mean, if the element we extract data or the element we put into.
For clarity I chose to name it the same as the module.
this change make it clear that what needs to be returned is the initial accumulator and not the collectable we are
puting data into.
```diff
-          {original, collector_fun}
+          initial_acc = map_set
+
+          {initial_acc, collector_fun}
```
mention that the MapSet implementation is a simplified version, not the real one.
The implementations in the module have been reformated and some attribute names changed, so it is easier for developers who want to read the source code to understand how protocols are implemented.
=> Improve docs and argument names for Collectable module

lib/elixir/lib/collectable.ex
Sorry, I forgot to include these changes in the previous PR
=> Format missing Collectable implementation

lib/elixir/lib/kernel.ex, lib/elixir/lib/macro.ex, lib/elixir/src/elixir_module.erl, lib/mix/lib/mix/compilers/elixir.ex
Rename `@struct` to `@__struct__`.
Closes #10352
=> Rename struct attribute in defstruct

lib/elixir/test/elixir/kernel/quote_test.exs
Hi all,
this PR removes what seems to be just a duplicated assert.
Cheers!
=> Remove duplicated assert in quote test

lib/elixir/lib/kernel.ex
I thought this would be nice to have.
=> ArgumentError example for binary_part

lib/elixir/test/elixir/module/types/types_test.exs
=> Fix typo in types_test.exs

lib/elixir/lib/list.ex, lib/elixir/test/elixir/list_test.exs
Adds a default field for `List.first/1` and `List.last/1`. Should be pretty simple
=> Add default value for List.first/1 and List.last/1

lib/logger/lib/logger.ex, lib/logger/lib/logger/backends/console.ex
Ref: https://github.com/elixir-lang/ex_doc/pull/1205#issuecomment-657244051
=> Document Logger.Backends.Console

lib/elixir/test/elixir/kernel_test.exs, lib/elixir/test/elixir/map_test.exs
These are leftover tests from a PR that was not merged
=> Add tests to Kernel.struct/2, Map.{replace, replace!}/3

lib/elixir/test/elixir/keyword_test.exs
Same here. Leftovers from a non-merged PR
=> Add tests to Keyword.{replace, replace!}/3

lib/elixir/lib/config.ex
=> Improves the docs of config/runtime.exs and Config.config_env/0

lib/iex/lib/iex/autocomplete.ex, lib/iex/test/iex/autocomplete_test.exs
WIP for this following proposal: https://groups.google.com/forum/?oldui=1#!topic/elixir-lang-core/QcWpEm2a-HA
To try it out just type in some function in your repl and then after the `(` press the tab key. For instance:
> iex(1)> [1, 2, 3] |> Enum.map(**\<TAB>**
> map(enumerable, fun)    
> iex(1)> [1, 2, 3] |> Enum.map(
=> IEX help in place with tab key

lib/elixir/lib/access.ex, lib/mix/lib/mix/tasks/app.config.ex
Brought to you by:
mix archive.install github wojtekmach/app_manifest
asdf shell elixir 1.10.4-otp-23 ; mix app_manifest elixir eex ex_unit iex logger mix > manifest-1.10.4.txt
asdf shell elixir 1.11.1-otp-23 ; mix app_manifest elixir eex ex_unit iex logger mix > manifest-1.11.1.txt
git diff --no-index manifest-1.10.4.txt manifest-1.11.1.txt
:-D
=> Minor docs updates

lib/elixir/lib/config.ex
Add missing config_env/0 & config_target/0
to the list of imports of `import Config`.
But I'm not 100% sure about that...
=> Improve Config docs

lib/ex_unit/lib/ex_unit/callbacks.ex
Hi all,
a couple of tiny things I noticed while studying this module.
Cheers!
=> Two minor doc fixes in ExUnit.Callbacks

lib/elixir/pages/library-guidelines.md
More context: https://elixirforum.com/t/mix-lock-in-libraries-packages/35392
=> Dependency Handling section in Library Guidelines

lib/elixir/lib/string.ex
fix #10505 
Hello :)
Forgetting to add a guard clause to String.trim_leading/2 makes the error message confusing, so fix it
=> add guard clause on functions in string module

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs, lib/iex/test/iex/autocomplete_test.exs
The discussion around it can be found here: https://groups.google.com/g/elixir-lang-core/c/ZJ3yUnVaF0c/m/NBElBo4GBwAJ
=> feat: implement `Enum.count_until/2` and `Enum.count_until/3`

lib/elixir/lib/tuple.ex, lib/elixir/test/elixir/tuple_test.exs
=> Adds Tuple.product/1

lib/elixir/lib/tuple.ex, lib/elixir/test/elixir/tuple_test.exs
=> Adds Tuple.sum/1

lib/elixir/lib/module.ex
A very minimal change to documentation in Module.
=> Fix typo in Module documentation

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
=> Add Enum.product/1

lib/elixir/lib/gen_server.ex
=> Fixed GenServer option typespec

lib/elixir/lib/calendar/datetime.ex
Hello!
As discussed over here https://groups.google.com/g/elixir-lang-core/c/JOGUFUyMm90 this adds the ability to provide an offset to `to_iso8601` to allow formatting a specified offset in the string, without having additional timezone information.
I added this to `NaiveDateTime` in the end to make it clear it has no time zone significance, adding it to `DateTime` is more complicated due to the need to deal with potentially changing timezones or raising when used with a non utc timzone, I thus came to the conclusion that `NaiveDateTime` was a better home for the extended functionality.
As a consequence it can be used to override a `DateTime`s natural timezone which I guess I could avoid with additional pattern matching (and/or an error?) additionally if desired this could be made to have …
=> Add offset to NaiveDateTime.to_iso8601/2 (making it to_iso8601/3).

bin/elixir.bat, lib/elixir/test/elixir/kernel/cli_test.exs
=> Set evaluation to empty string to fix string replace on batch

lib/elixir/lib/kernel.ex, lib/elixir/lib/macro.ex, lib/elixir/test/elixir/kernel_test.exs
=> Adds Kernel.then/2

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel_test.exs
Missing tests and examples, will be adding soon. Does half of #10602
=> Add Kernel.tap/2

lib/elixir/lib/protocol.ex
Related: https://github.com/elixir-lang/elixir/pull/10617
=> Document what exception __protocol__(:impl_for!/1) raises

lib/elixir/lib/string.ex
Reverts elixir-lang/elixir#10635
=> Revert "Update String.printable? character_limit typespec"

lib/iex/lib/iex.ex
Updated to document the new behaviour after it was modified in 6a4b2ec4eeb5de2b4010b5cab1a9b4c78c308e76.
=> Document head of line pipe treatment in IEx

lib/elixir/lib/module/types/unify.ex, lib/elixir/test/elixir/module/types/expr_test.exs, lib/elixir/test/elixir/module/types/unify_test.exs
=> Fix tuple subtype check

lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/test/ex_unit/case_test.exs
=> Improve error message on invalid pattern on test

lib/elixir/lib/module/types/pattern.ex, lib/elixir/test/elixir/module/types/pattern_test.exs
=> Do not require RHS of and operator to be boolean

lib/elixir/lib/enum.ex
As per the [discussion](https://groups.google.com/g/elixir-lang-core/c/8VfA1cc7qsw) in `elixir-core`.
=> Explain why Enum.all?/2 returns true for empty enumerables

lib/elixir/lib/file.ex
=> Add documentation about line break normalization for line based streaming

lib/elixir/lib/uri.ex, lib/elixir/test/elixir/uri_test.exs, lib/ex_unit/lib/ex_unit/runner.ex
This pull request is based on a proposal discussed and accepted here:
https://groups.google.com/g/elixir-lang-core/c/gMqIFBr4OTU
Please note that this is my first contribution to Elixir itself.
=> Add functions for RFC 3986 compliant space encoding and decoding

lib/mix/test/mix/tasks/deps_test.exs, lib/mix/test/test_helper.exs
It was partially solved in 74855f052d6a0d8a015f1956426b0de27e3572c8
=> Fix Git warning

lib/mix/lib/mix/scm/git.ex, lib/mix/test/fixtures/rebar_dep/rebar.config.script, lib/mix/test/mix/local/installer_test.exs, lib/mix/test/mix/rebar_test.exs, lib/mix/test/mix/scm/git_test.exs, lib/mix/test/test_helper.exs
Implements suggestions in https://github.com/elixir-lang/elixir/pull/10707#issuecomment-778421314
=> Remove usage of master and master/slave terminology

lib/elixir/src/elixir_tokenizer.erl
Closes https://github.com/elixir-lang/elixir/issues/10722
=> Fix warning message mentioning quoted atoms may end with ! or ?

lib/elixir/pages/unicode-syntax.md
It addresses https://github.com/elixir-lang/elixir/pull/10723#pullrequestreview-592080497
=> Add clarification in Atoms section in Unicode syntax page

lib/mix/lib/mix.ex, lib/mix/lib/mix/tasks/compile.ex, lib/mix/test/mix_test.exs
=> Add :consolidate_protocols option to Mix.install/2

lib/ex_unit/lib/ex_unit/diff.ex, lib/ex_unit/test/ex_unit/diff_test.exs
This PR tries to address issue https://github.com/elixir-lang/elixir/issues/10808
I am not happy about this solution.
Comments and suggestions about a better approach are welcome!
=> Fix ex_unit exception

lib/elixir/lib/calendar/date.ex, lib/elixir/lib/calendar/date_range.ex, lib/elixir/lib/range.ex, lib/elixir/test/elixir/calendar/date_range_test.exs, lib/elixir/test/elixir/enum_test.exs
I still need to add docs & tests.
=> Add step to Date.Range

lib/iex/lib/iex/helpers.ex
Addresses https://github.com/elixir-lang/elixir/issues/8414
=> Use :erlang.system_info(:ets_count) introduced in OTP 22

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
=> Keeping underscore between digits on Macro.camelize/1

lib/elixir/lib/code/formatter.ex, lib/elixir/lib/code/identifier.ex, lib/elixir/lib/exception.ex, lib/elixir/lib/macro.ex, lib/elixir/test/elixir/code_formatter/literals_test.exs, lib/elixir/test/elixir/kernel/parser_test.exs
Closes https://github.com/elixir-lang/elixir/issues/10857
I think it is good to keep the separate commits, so when we need to revert this change, we can clearly see what to change. Or at least merge the first two
=> Quote range operator

.cirrus.yml
I am upgrading even it is not a stable release yet, to see if test pass
=> Upgrade FreeBSD to 13.0 ALPHA in Cirrus CI

lib/logger/lib/logger.ex, lib/logger/test/logger_test.exs
=> Add functions for application wise log levels

lib/elixir/pages/patterns-and-guards.md
I was trying to find the documentation about that when explaining the functionality to one of our new developers and couldn't find it anywhere.
=> Add Struct Pattern Matching Guide

lib/elixir/lib/string.ex, lib/elixir/unicode/unicode.ex
As described in https://unicode.org/versions/Unicode13.0.0/#Version_Specification
=> Use proper Unicode reference

lib/elixir/lib/collectable.ex
It mentions `step` and link to the various types in Range
=> Document in Collectable docs the new range format

CHANGELOG.md
Not sure what the original intended meaning here was but this is my best guess!
=> Minor wording tweak in CHANGELOG.md

lib/iex/lib/iex/autocomplete.ex, lib/iex/test/iex/autocomplete_test.exs
=> Fix signature expansion when no docs

lib/elixir/lib/code/formatter.ex
This changes the comments in the formatter to be maps instead of tuples, as suggested in the [Expose functions from `Code.Formatter` via the `Code` module](https://groups.google.com/g/elixir-lang-core/c/-8CPorfVTxg) proposal
=> Change formatter comments from tuple to map

lib/elixir/lib/code.ex, lib/elixir/lib/code/formatter.ex
Split from #10988
I created this as a draft because I'm getting an `undef` error when running `make clean test` that I didn't figure out how to solve yet,
=> Add `Code.string_to_quoted_with_comments/2`

lib/elixir/lib/code/normalizer.ex, lib/elixir/test/elixir/code_normalizer/formatted_ast_test.exs
=> Fix ast normalizing issue with keyword lists

lib/mix/lib/mix.ex
=> Mix.install/2: Expand paths for path deps

lib/elixir/lib/option_parser.ex, lib/elixir/test/elixir/option_parser_test.exs
=> OptionParser.parse/2: Validate switch types/modifiers

lib/elixir/lib/code.ex
I got a good chuckle out of this one.  Thank you all for all of your time and hard work!
=> Fix typo in docs for `Code.ensure_loaded!`

lib/mix/lib/mix/tasks/xref.ex, lib/mix/test/mix/tasks/xref_test.exs
As proposed [on elixir-core](https://groups.google.com/g/elixir-lang-core/c/Hmg5y8S3v4E/m/FVK50RWBAQAJ)
Other PR forthcoming...
=> Add `--label compile-connected` option to `mix xref graph`

lib/elixir/lib/io.ex
This resolves #11040.
1. Add @doc since: "1.12.0" to binstream/0 and stream/0
2. Add a comment to binstream/2 and stream/2
Would you please do review?
=> Add `@doc since: "1.12.0"` and comments

lib/mix/lib/mix/tasks/xref.ex, lib/mix/test/mix/tasks/xref_test.exs
As proposed [on elixir-core](https://groups.google.com/g/elixir-lang-core/c/Hmg5y8S3v4E/m/FVK50RWBAQAJ)
Looks like it does not conflict with #11048 🤞
=> Support multiple sinks and sources in `mix xref graph`

lib/elixir/lib/kernel.ex
Add doc examples to: is_atom/1, is_boolean/1, is_function/1
=> Add examples to guards

lib/elixir/lib/record.ex
=> Update record extract documentation

bin/elixir, bin/elixir.bat, lib/mix/lib/mix/tasks/release.ex
=> Provide a mechanism to set a default ERTS_BIN

lib/elixir/lib/list.ex
Mailing list discussion: https://groups.google.com/g/elixir-lang-core/c/toBmfrRUHvw
=> Add List.keyfind!/3

lib/elixir/lib/option_parser.ex, lib/elixir/test/elixir/option_parser_test.exs
Followup to https://github.com/elixir-lang/elixir/pull/11129
See https://github.com/elixir-lang/elixir/pull/11129#discussion_r673897318
=> Handle dashes in option error suggestion

lib/elixir/lib/keyword.ex
Was going to push it on the previous PR, but you're too fast :stuck_out_tongue_closed_eyes:. Wasn't much work, so I just made the changes. It does read better overall I think. :+1:
=> Keyword: change sentences from passive to active voice.

lib/ex_unit/lib/ex_unit/capture_io.ex, lib/ex_unit/lib/ex_unit/capture_log.ex, lib/ex_unit/test/ex_unit/capture_io_test.exs, lib/ex_unit/test/ex_unit/capture_log_test.exs
I added very minimal testing for these, but they are indirectly tested with the existing tests as `capture_log` and `capture_io` rely entirely on them. Let me know if I should add more tests.
=> Add `with_log` and `with_io`

lib/elixir/lib/kernel/utils.ex, lib/elixir/test/elixir/kernel_test.exs
=> Raise with specific erorr message when guards used in defdelegate/2

lib/elixir/src/elixir_env.erl, lib/iex/lib/iex/pry.ex
=> Remove Mix.Env.vars from elixir_env.erl as well

lib/elixir/lib/module/types.ex, lib/elixir/lib/module/types/pattern.ex, lib/elixir/test/elixir/module/types/pattern_test.exs, lib/elixir/test/elixir/module/types/types_test.exs
Closes https://github.com/elixir-lang/elixir/issues/10823.
=> Infer tuple size from is_tuple/1 and add hint

lib/mix/lib/mix/compilers/elixir.ex, lib/mix/test/mix/tasks/compile.elixir_test.exs
=> Make sure .beam files still exist for restored files 

lib/elixir/src/elixir_erl_pass.erl
Follow-up to #11107
See also https://elixirforum.com/t/dialyzer-missing-message-in-otp-24/41977
=> Pass annotation to arguments in more scenarios

lib/iex/lib/iex/server.ex, lib/iex/test/iex/server_test.exs
This is the second attempt to solve the loss of `.iex.exs` loaded code after an `IEx.pry` session.
The `IEx.pry` evaluator gets rid of the previous evaluator options, so to solve this problem we just hold the previous state when a pry session starts, so that it can be passed back when the pry session ends.
=> IEx: Fix .iex.exs load after pry session - Second Approach

lib/elixir/lib/map.ex
=> Do not depend on :maps module internals in Map.{filter, reject, map}

lib/elixir/lib/code/identifier.ex, lib/elixir/lib/integer.ex, lib/elixir/lib/kernel.ex, lib/elixir/pages/operators.md, lib/elixir/src/elixir_parser.yrl, lib/elixir/src/elixir_tokenizer.erl
Same semantics as in Nx.
Question: should the formatter format it as `left ** right` or `left**right`?
/cc @seanmor5 @polvalente @jonatanklosko
=> Add power operator

lib/elixir/lib/version.ex, lib/elixir/test/elixir/version_test.exs
=> Ensure proper precedence of and/or in version requirements

lib/elixir/lib/version.ex
Some other changes in this module allowed dialyzer to detect and point out spec issues
=> Fix Version.Requirement.new/2 spec

lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/erlang/tokenizer_test.erl
=> Allow sigil modifiers to contain digits

lib/elixir/lib/range.ex, lib/elixir/test/elixir/range_test.exs
=> Always show step when range is descending

lib/elixir/pages/patterns-and-guards.md
Updates a reference to a section heading that changed.
=> Correct reference to section of docs

README.md, RELEASE.md
These two have been left out in 38dce7b2cc99cdfd4a5718a8c62816e00251880a
=> Update remaining references to master branch with main

lib/elixir/lib/version.ex, lib/elixir/test/elixir/version_test.exs
Reference: https://github.com/elixir-lang/elixir/pull/9807#pullrequestreview-818567813
/cc @ericmj
=> Improve Version.compile_requirement/1

lib/elixir/lib/float.ex
Makes it clear where to look for if you're looking to use something
other than the algorithm used there.
=> Add note in Float.to_{string/charlist}/1

lib/elixir/lib/calendar.ex
…to show which part of the tuple is the value and which the precision
=> Update microsecond typespec

lib/elixir/lib/kernel/special_forms.ex
The output have changed since 1.13.0-rc.0.
=> Update code example for unquote/1

lib/elixir/lib/code/identifier.ex
Note: I am not 100% sure on the `fun` specs
=> Add guards and specs to Identifier.escape/4

lib/elixir/lib/enum.ex, lib/mix/lib/mix/tasks/format.ex
Brought to you by https://github.com/wojtekmach/app_manifest. :D
=> Add missing `@doc since`

lib/elixir/lib/code/identifier.ex, lib/elixir/lib/code/normalizer.ex, lib/ex_unit/lib/ex_unit/diff.ex
Closes #11444
/cc @michallepicki
=> Fix spec for Code.Identifier.escape/4

lib/elixir/lib/calendar/date.ex
Remove doc repeat iex example for Date.end_of_week
=> Remove doc repeat iex example for Date.end_of_week

lib/elixir/lib/code/normalizer.ex, lib/elixir/test/elixir/code_normalizer/formatted_ast_test.exs, lib/elixir/test/elixir/code_normalizer/quoted_ast_test.exs
=> Fix formatting of lists in module attribues

lib/elixir/lib/string.ex, lib/elixir/test/elixir/string_test.exs
=> return the original string if the list of patterns is empty

lib/elixir/lib/string.ex, lib/elixir/test/elixir/string_test.exs
It covers the case described in https://github.com/elixir-lang/elixir/issues/11485
=> Fix t:String.pattern/0

lib/elixir/pages/typespecs.md
See discussion: https://github.com/elixir-lang/elixir/pull/11520#issuecomment-999901843
=> Remove reference to t:Enum.t/0 in Typespecs page

lib/iex/lib/iex/helpers.ex, lib/iex/test/iex/helpers_test.exs
I frequently define my own helper for this. Thought it might be a useful add for others.
=> Add name lookup to pid/1 helper

lib/mix/lib/mix/tasks/test.coverage.ex
Sorry for the incredibly trivial PR, but I was reading these docs and saw a few mistakes I thought could use fixing 😅
=> Fix a few issues in the mix test.coverage docs

lib/elixir/lib/node.ex, lib/elixir/src/elixir_rewrite.erl
available since OTP 23
Related to https://github.com/elixir-lang/elixir/issues/9603
=> Add Node.spawn_link

.github/workflows/ci.yml, Makefile, lib/elixir/lib/module.ex, lib/elixir/src/elixir_parser.yrl
also: fix Dialyzer CI step name
=> Remove references to HiPe

lib/elixir/lib/path.ex, lib/elixir/test/elixir/path_test.exs
Part of https://github.com/elixir-lang/elixir/issues/9603.
=> Add Path.safe_relative/1 and Path.safe_relative_to/2

lib/elixir/src/elixir_map.erl, lib/elixir/test/elixir/kernel/expansion_test.exs, lib/elixir/test/elixir/module/types/map_test.exs
=> EEP 52: Allow pins inside map keys in matches

lib/elixir/test/elixir/path_test.exs
I accidentally messed it up in #11542 🙃
=> Fix Windows build

lib/elixir/src/elixir_tokenizer.erl
Closes https://github.com/elixir-lang/elixir/issues/11551
=> Add nudge to do expression error

lib/elixir/lib/calendar/date.ex, lib/elixir/lib/calendar/datetime.ex
@benwilson512 comments got 13 likes in a few hours, I thought it was worth updating the documentation to make the information easier to find !
https://elixirforum.com/t/why-is-datetime-module-lacking-min-and-max-functions/45164
=> Update DateTime documentation

lib/elixir/pages/patterns-and-guards.md
...as it is the one used in Core.
=> Use falsy intead of falsey

lib/logger/lib/logger.ex
See discussion:
https://github.com/elixir-lang/elixir/commit/5792c3835fdef6fbf52fc477ef9789f96c0ec68d#commitcomment-62955268
=> Streamline warning message with docs in Logger functions

lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/lib/calendar/time.ex
Following https://github.com/elixir-lang/elixir/pull/11564 and @josevalim 's [comment](https://github.com/elixir-lang/elixir/pull/11564#issuecomment-1011171466), here is a new PR with the same doc improvments adapted to Time and NaiveDateTIme modules.
=> Update doc for Time and NaiveDateTime

lib/elixir/lib/calendar/date.ex, lib/elixir/lib/calendar/date_range.ex, lib/elixir/test/elixir/calendar/date_range_test.exs
=> Change `Date.Range` inspect to use `Date.range`

lib/elixir/lib/version.ex
=> Change `Version` inspect to use expression

lib/elixir/lib/collectable.ex, lib/elixir/lib/map_set.ex, lib/elixir/test/elixir/inspect_test.exs, lib/elixir/test/elixir/map_set_test.exs, lib/ex_unit/test/ex_unit/doc_test_test.exs
=> Change `MapSet` inspect to use expression

lib/elixir/test/elixir/module/locals_tracker_test.exs
=> Only check for unwanted functions

lib/mix/lib/mix/compilers/elixir.ex, lib/mix/test/mix/tasks/compile.elixir_test.exs
=> Fix: warnings-as-errors for compiling with all-warnings

lib/mix/test/mix/rebar_test.exs, lib/mix/test/test_helper.exs
and clean up mix test_helper.exs exclude filters
Part of #11642
=> Skip tests using Rebar2 on Erlang/OTP 25+

lib/eex/lib/eex/compiler.ex, lib/eex/test/eex/tokenizer_test.exs
Closes https://github.com/elixir-lang/elixir/issues/11644
=> Expose EEx comments as tokens in EEx.tokenize/2

lib/ex_unit/lib/ex_unit/doc_test.ex, lib/ex_unit/test/ex_unit/doc_test_test.exs
as proposed in https://groups.google.com/g/elixir-lang-core/c/zlM7pvqCXzE
=> Raise when doctest's only function is undefined

lib/mix/lib/mix/project_stack.ex
Just removing a duplicated comment I found in the codebase.
=> Remove duplicated comment

lib/eex/lib/eex.ex
=> Fix `EEx.tokenize/2` docs

lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/tasks/test_test.exs
=> Fix: dot path for umbrella test

lib/elixir/lib/uri.ex
Small change based on elixir-lang-core discussion on 21/2/2022.
=> Improve documentation on how to manually build URI structs

.github/workflows/ci.yml
=> Add OTP-24.3 to CI

lib/elixir/lib/kernel/special_forms.ex
Closes https://github.com/elixir-lang/elixir/issues/11717
=> Do not mention charlist segments in `<<>>/1` docs

lib/iex/lib/iex.ex
=> Fix typo in IEx module

lib/elixir/lib/module.ex
The feature was added in OTP-18 https://github.com/erlang/otp/commit/25ab719cfaf42d196287fec2171bf3eefb845b62
Latest Elixir supports OTP-22 or newer
=> Do not mention compatibility in @dialyzer attr doc

Makefile
This allows us to generate Epub documents.
DOCS_FORMAT=epub make docs
=> Makefile: allow setting DOCS_FORMAT

lib/elixir/src/elixir.erl, lib/elixir/test/elixir/uri_test.exs
The WebSocket protocol: https://tools.ietf.org/id/draft-ietf-hybi-thewebsocketprotocol-09.html#rfc.section.1.7
=> Add ws and wss port configuration to URIConfig

lib/mix/lib/mix/tasks/escript.build.ex
Add space in between words.
elixir-lang is great language.thank you :-)
=> fix typo in mix escript.build docs

lib/ex_unit/test/ex_unit/case_test.exs
This is an improvement to https://github.com/elixir-lang/elixir/pull/11764
=> ExUnit: Group colliding test names in tests

lib/elixir/lib/exception.ex, lib/elixir/test/elixir/exception_test.exs
Completes the error messages of #11756 
Follow up from https://github.com/elixir-lang/elixir/pull/11756#discussion_r857293994
=> Add error details to ErlangError

lib/elixir/lib/task.ex
Related PR: https://github.com/elixir-lang/elixir/pull/11794
=> Improve docs for Task mfa field

lib/eex/lib/eex.ex
I figure this is going to need some fine tuning, but I wanted to at least start a conversation.
=> Providing documentation for the undocumented "options" argument of EEx.eval_string()

lib/ex_unit/lib/ex_unit/callbacks.ex
I made a pass over the docs for `ExUnit.Callbacks.setup_all/1` and `ExUnit.Callbacks.on_exit/2`. I mostly clarified the behavior of `on_exit/2` when called from `setup_all/1`.
=> Improve docs for setup_all + on_exit

lib/elixir/test/elixir/kernel/warning_test.exs
Related PR: https://github.com/elixir-lang/elixir/pull/11838
=> Add tests for warning on atoms starting with a number

lib/elixir/lib/supervisor.ex
This was the left over from the other PR that can still be merged.
=> Copy-edit Supervisor docs + New types

lib/mix/lib/mix/task.compiler.ex
As documented position 0 means unknown
=> Improve position typespec

lib/elixir/lib/module.ex, lib/elixir/test/elixir/kernel/errors_test.exs
It reads better in English IMO
=> Minor grammar fix

.github/ISSUE_TEMPLATE/issue.yml
As per https://github.com/elixir-lang/elixir/pull/11893#issuecomment-1145345356
=> GitHub Templates: Rename section to Report an issue

lib/elixir/lib/application.ex, lib/elixir/lib/task.ex
It would be preferable this can be reviewed by a native English speaker.
=> Correct use of "who"

CHANGELOG.md, lib/elixir/lib/map_set.ex
Also added it to the CHANGELOG!
=> Add doc since to MapSet.symmetric_difference/2

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
Both of the fixed bug were helpfully pointed out by @wojtekmach in https://github.com/elixir-lang/elixir/pull/11974#issuecomment-1181796832. Thanks!
=> Fix a couple of small bugs in Macro.dbg/3

lib/elixir/lib/io/ansi.ex
Found by [dialyzer](https://github.com/michallepicki/elixir-lang-dialyzer-runs/runs/7312306981?check_suite_focus=true) :)
=> Fix specs in IO.ANSI

lib/mix/lib/mix/release.ex, lib/mix/lib/mix/tasks/release.ex, lib/mix/test/mix/release_test.exs
=> Make sure release mode configuration cascades

lib/elixir/lib/code/fragment.ex, lib/elixir/test/elixir/code_fragment_test.exs
=> Make Code.Fragment functions work across newlines

lib/elixir/lib/code.ex, lib/elixir/lib/code/typespec.ex, lib/elixir/lib/module/parallel_checker.ex, lib/elixir/test/elixir/code_test.exs, lib/elixir/test/elixir/module/types/integration_test.exs, lib/iex/lib/iex/helpers.ex
Close https://github.com/elixir-lang/elixir/issues/12006
=> Case insensitive module resolution

lib/elixir/lib/access.ex, lib/elixir/test/elixir/access_test.exs
This PR only works with the latest Elixir version from master.
=> Introduces Access.slice/1

lib/ex_unit/lib/ex_unit/assertions.ex
Since macro expansion now propagates `generated: true` annotations, maybe we can clean up the workarounds in ExUnit assertions.
Or do we want to keep `case` instead of `nil` to reduce the amount of expansion needed? (in which case we should update the comments)
=> Remove dialyzer workarounds

lib/mix/lib/mix/release.ex, lib/mix/lib/mix/utils.ex
found by [dialyzer](https://github.com/michallepicki/elixir-lang-dialyzer-runs/runs/7531330911?check_suite_focus=true#step%3A7%3A791=) :)
=> Fix passing of File.cp_r! on_conflict option

lib/elixir/lib/string.ex, lib/elixir/pages/typespecs.md
Related to https://github.com/elixir-lang/elixir/issues/10433.
=> Add nonempty_binary/0 and nonempty_bitstring/0

lib/elixir/lib/process.ex, lib/elixir/src/elixir_rewrite.erl, lib/elixir/test/elixir/process_test.exs
See https://github.com/elixir-lang/elixir/issues/10433.
=> Add Process.alias/0,1 and Process.unalias/1

lib/elixir/lib/process.ex
Found by [dialyzer](https://github.com/michallepicki/elixir-lang-dialyzer-runs/runs/7570807166?check_suite_focus=true) :)
=> Fix Process.monitor/2 spec

lib/elixir/lib/io.ex
In a recent project, I ran into this challenge where I needed to collect user inputs from the terminal, and with some trial and error, I came up with the following code and thought maybe it might serve as an example in the docs.
=> Another example for IO.stream

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
=> Fix bug in Enum.slice with step>1

lib/elixir/lib/range.ex, lib/elixir/test/elixir/enum_test.exs
Closes https://github.com/elixir-lang/elixir/issues/12047
=> Fix infinite loop in Enum.take/2

lib/elixir/lib/kernel.ex, lib/elixir/lib/list.ex
Relates to https://github.com/elixir-lang/elixir/issues/12065
Based on https://elixir-lang.org/getting-started/binaries-strings-and-char-lists.html#charlists.
BTW, I was checking the getting started guide, and it might make sense to move the charlists introduction later , maybe in the sigils section?
=> Update charlist documentation

lib/elixir/pages/unicode-syntax.md, lib/elixir/test/elixir/application_test.exs, lib/mix/test/mix/generator_test.exs
some typos on test and documentation
=> fix: some typo on test and docs

lib/elixir/lib/kernel.ex
Some typos/suggestions as I read through
=> Add some minor edits to the struct docs

lib/elixir/lib/code.ex
=> Add more doc to `:debug_info` option

lib/elixir/lib/code/formatter.ex, lib/elixir/test/elixir/code_formatter/containers_test.exs
=> Fix formatter: size*unit shortcut in bitstring

lib/mix/lib/mix.ex, lib/mix/test/mix_test.exs
=> Mix.install accepts atoms as paths

lib/elixir/lib/code.ex
=> Fix tracer on_module docs

CHANGELOG.md, lib/elixir/lib/calendar/date.ex, lib/elixir/lib/calendar/datetime.ex, lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/lib/calendar/time.ex, lib/elixir/test/elixir/calendar/date_test.exs, lib/elixir/test/elixir/calendar/datetime_test.exs, lib/elixir/test/elixir/calendar/naive_datetime_test.exs, lib/elixir/test/elixir/calendar/time_test.exs
As per the [discussion on the mailing list](https://groups.google.com/g/elixir-lang-core/c/W2TeQm5r1H4).
Please let me know if I missed anything.
=> Add before?/2 and after?/2 in Date, Time, DateTime, and NaiveDateTime

lib/iex/lib/iex/info.ex, lib/iex/test/iex/info_test.exs
=> Implement IEx info for DateTime

lib/elixir/lib/kernel/typespec.ex, lib/elixir/test/elixir/typespec_test.exs
=> Fix compiler crash on invalid typespec

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
=> Macro.quoted_literal?/1 supports bitstring literals

lib/mix/lib/mix/project.ex, lib/mix/lib/mix/project_stack.ex, lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/tasks/test_test.exs, lib/mix/test/mix/umbrella_test.exs
=> [ExUnit] fix output when absolute path is given

lib/elixir/lib/code.ex, lib/elixir/lib/kernel/special_forms.ex, lib/elixir/pages/patterns-and-guards.md, lib/elixir/src/elixir.erl, lib/elixir/src/elixir_clauses.erl, lib/elixir/src/elixir_compiler.erl, lib/elixir/src/elixir_env.erl, lib/elixir/test/elixir/kernel/defaults_test.exs, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/kernel/expansion_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs, lib/ex_unit/lib/ex_unit/doc_test.ex, lib/iex/test/iex/helpers_test.exs, lib/iex/test/iex/interaction_test.exs, lib/iex/test/iex/server_test.exs, lib/mix/lib/mix/tasks/compile.elixir.ex, lib/mix/test/mix/tasks/test_test.exs
Replaces https://github.com/elixir-lang/elixir/pull/12272/files
This is still a work in progress, I need to fix the CI but I wanted to first confirm the approach.
=> Add :undefined_variable_as_call compiler option

lib/elixir/lib/exception.ex, lib/elixir/lib/kernel/typespec.ex, lib/elixir/test/elixir/typespec_test.exs
fixes #12277 
Chore to implement and raise the Kernel.TypespecError
=> Implement and raise Kernel typespecerror

lib/elixir/lib/stream.ex
Hi,
I didn't understand the original code sample when I first read, because it was too complicated for a novice. 
I have a hypothesis that `Stream.unfold/2` will be more understandable for such novice by adding more sample code including arithmetic and geometric progression with `Enum.take/2`, so I have just created this PR.
=> Add sample code of Stream.unfold/2

lib/logger/lib/logger/formatter.ex, lib/logger/test/logger/formatter_test.exs
=> Add support for ports in Logger metadata

lib/iex/lib/iex/helpers.ex
This is the "corrected" version of https://github.com/elixir-lang/elixir/pull/12301 but since @nathanl did not respond and I wanted the feature, I figured that I could open a new PR. Feel free to mention him in the commit,
=> Let pid/1 parse a pid's inspection string

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
First draft of having something like this:
=> Format logic expressions in dbg/2

lib/elixir/lib/registry.ex
I also added some docs for this feature.
=> Add type t:Registry.listener_message/0

lib/mix/lib/mix/compilers/application_tracer.ex, lib/mix/lib/mix/compilers/elixir.ex
=> Optimize application tracer

bin/elixir, bin/elixir.bat, bin/iex, bin/iex.bat, lib/elixir/lib/kernel/cli.ex, lib/elixir/lib/system.ex, lib/elixir/src/elixir.erl, lib/elixir/src/elixir_config.erl, lib/iex/lib/iex.ex, lib/iex/lib/iex/cli.ex, lib/mix/lib/mix/tasks/release.ex
This gives us more control to cache paths
and over boot compared to relying on scripts.
=> Move app loading and setting of paths to elixir app

lib/ex_unit/lib/ex_unit/callbacks.ex, lib/ex_unit/test/ex_unit/callbacks_test.exs
This was proposed in the mailing list. Documentation changes would be required if this would be accepted. 
Opening pull request for reference.
=> Accept {module, function} tuples in ExUnit setup

lib/ex_unit/lib/ex_unit/callbacks.ex, lib/ex_unit/test/ex_unit/callbacks_test.exs
Follow up to https://github.com/elixir-lang/elixir/pull/12382.
=> More errors improvements in ExUnit.Callbacks

lib/elixir/lib/system.ex
This is prompted by a discussion in the elixir-lang Slack server: https://elixir-lang.slack.com/archives/C03EPRA3B/p1676667908538029
=> Adds notes about monotonic time not being strictly monotonic

lib/elixir/lib/gen_server.ex, lib/elixir/lib/task.ex, lib/elixir/lib/task/supervisor.ex, lib/elixir/test/elixir/gen_server_test.exs, lib/elixir/test/elixir/task_test.exs
=> Add GenServer.async/2

lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/test/elixir/calendar/naive_datetime_test.exs
=> Fix NaiveDateTime.end_of_day/1 precision

lib/mix/lib/mix/tasks/xref.ex, lib/mix/lib/mix/utils.ex, lib/mix/test/mix/tasks/xref_test.exs
=> Add --output to "mix xref"

lib/mix/lib/mix/tasks/format.ex, lib/mix/test/mix/tasks/format_test.exs
Follow up to https://github.com/elixir-lang/elixir/pull/12529.
=> Validate --no-exit in "mix format"

lib/mix/lib/mix.ex
This is a follow-up on #12411 to prevent others from falling into the same pit.
=> Add note on relation between build and environment

lib/ex_unit/lib/ex_unit.ex, lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/lib/ex_unit/runner.ex, lib/ex_unit/test/ex_unit/case_test.exs
=> Pass module tags to setup_all

.github/workflows/ci.yml, lib/elixir/src/elixir.erl, lib/mix/test/mix/tasks/release_test.exs
I just added it to the CI for now, I wasn't sure what to do with `release.yml` and `repo.hex.pm.yml`.
=> Add OTP 26 to CI

lib/elixir/lib/code.ex, lib/mix/lib/mix.ex
Courtesy of https://github.com/wojtekmach/app_manifest. :)
=> Add missing doc since

lib/elixir/lib/map_set.ex
- fix the references to the function arguments in Docs
=> Fix references

lib/elixir/test/elixir/kernel/warning_test.exs
As a continuation of #12643, this pull requests adds extra assertions based on warning locations to existing tests, so that we can more easily track our changes to warning/error reporting.
=> Refactor warning_tests to assert on warning position

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
Close https://github.com/elixir-lang/elixir/issues/12666
=> Fix slicing MapSet with stepped range

lib/elixir/lib/exception.ex, lib/elixir/lib/module/parallel_checker.ex, lib/elixir/src/elixir_errors.erl, lib/elixir/test/elixir/kernel/diagnostics_test.exs
This pull request updates the formatting of compiler-emitted warnings, you can see some examples of the new visuals on the tests that were added.
=> Improve compiler warnings visuals

lib/ex_unit/lib/ex_unit/doc_test.ex, lib/ex_unit/test/ex_unit/doc_test_test.exs
=> Allow variables to be defined in doctests and used in the expectation

lib/ex_unit/lib/ex_unit.ex, lib/ex_unit/lib/ex_unit/runner.ex, lib/ex_unit/mix.exs, lib/ex_unit/test/ex_unit_test.exs, lib/mix/lib/mix/compilers/test.ex
=> Improve default ExUnit seed algorithm and allow changing via config

lib/elixir/lib/exception.ex
Like #12735, but for more exceptions.
=> Add docs to more stdlib exceptions

lib/elixir/lib/exception.ex
The effort continues. 1.16 is the age of documentation 👿
=> Document almost all remaining stdlib exceptions

lib/elixir/pages/anti-patterns/code-anti-patterns.md, lib/elixir/pages/anti-patterns/design-anti-patterns.md, lib/elixir/pages/anti-patterns/macro-anti-patterns.md, lib/elixir/pages/anti-patterns/process-anti-patterns.md, lib/elixir/pages/anti-patterns/what-anti-patterns.md, lib/elixir/scripts/elixir_docs.exs
This pull request introduces an initial sketch of how anti-patterns/code smells will be documented within Elixir docs. This is based on the work from @lucasvegi here: https://github.com/lucasvegi/Elixir-Code-Smells/tree/main
@lucasvegi, we (more precisely, @whatyouhide and myself) decided to break it into 4 categories: code (low-level + traditional), design, process, and meta-programming. We have also added some new code smells and removed others where we believe are too imprecise). I will drop some comments in the pull request where we need your attention/suggestions.
Once this is merged, pull requests that fill-in the TODOs will be welcome.
=> Initial sketch of anti-patterns

lib/elixir/pages/anti-patterns/design-anti-patterns.md
I only filled in the TODO for "Working with invalid data" to validate the template. Once I receive confirmation, I will gradually continue filling in the others.
=> "Working with invalid data" added (Anti-pattern documentation)

lib/elixir/lib/float.ex
Not sure if it necessary, but having typespecs is better than missing one?
=> Add typespecs for min and max float

lib/elixir/test/elixir/task/supervisor_test.exs
https://github.com/elixir-lang/elixir/pull/12814 made me realize we didn't have a test for `:zip_input_on_exit` in `Task.Supervisor`. Although the implementation is shared within `Task.Supervised`, I figured having tests can't hurt and might help catch regressions.
Adapted [existing tests](https://github.com/elixir-lang/elixir/blob/main/lib/elixir/test/elixir/task_test.exs#L1041-L1056) from `Task`.
=> Add test for :zip_input_on_exit in Task.Supervisor

lib/elixir/lib/code/fragment.ex, lib/elixir/test/elixir/code_fragment_test.exs
Close #12845
This is a proposal and tentative fix, please let me know your thoughts.
=> Code.Fragment handles anonymous function

lib/elixir/lib/macro/env.ex
Close https://github.com/elixir-lang/elixir/issues/12848
=> Update make_custom_env recipe to fix warnings

lib/elixir/lib/kernel/special_forms.ex, lib/elixir/pages/getting-started/try-catch-and-rescue.md, lib/iex/lib/iex.ex
Fix other occurrences similar to https://github.com/elixir-lang/elixir-lang.github.com/issues/1714 in docs and guides.
Will backport the getting started guide too.
=> Update other undefined variable errors in docs

lib/elixir/scripts/windows_installer/installer.nsi, lib/elixir/scripts/windows_installer/update_system_path.erl
=> Fix Windows Installer

lib/elixir/lib/code/formatter.ex, lib/elixir/test/elixir/code_formatter/containers_test.exs
=> Fix formatter for :* in bitstring modifiers

lib/elixir/pages/getting-started/keywords-and-maps.md
Backporting https://github.com/elixir-lang/elixir-lang.github.com/pull/1724
=> Remove duplicate word in guide

lib/elixir/pages/anti-patterns/design-anti-patterns.md
=> Boolean obsession

lib/elixir/lib/macro.ex
=> Add missing spec and test for Macro.path

lib/elixir/lib/kernel/special_forms.ex
=> Update docs on binary syntax modifiers

lib/elixir/lib/file.ex
=> Add example of seeking within a file to File docs

lib/ex_unit/lib/ex_unit/filters.ex, lib/ex_unit/test/ex_unit/filters_test.exs, lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/tasks/test_test.exs
=> Allow mix test multi locations

lib/elixir/lib/exception.ex, lib/elixir/src/elixir.erl, lib/elixir/test/elixir/code_test.exs
Close https://github.com/elixir-lang/elixir/issues/12982
=> Add local_handler to erl_eval

lib/elixir/lib/module/types/behaviour.ex, lib/elixir/test/elixir/kernel/impl_test.exs
Seems I was a bit too fast on https://github.com/elixir-lang/elixir/issues/12841, I missed a place to fix that wasn't covered by tests (known callback suggestions).
=> Fix known callbacks suggestions

lib/elixir/lib/code/formatter.ex
This PR speeds up the formatter's _ interspersing for integers, by about 3x on my machine. Inspired by this [Elixir Forum thread](https://elixirforum.com/t/integer-to-string-with-underscores/59040).
No hard feelings if the existing implementation is preferred. Just thought I'd submit this as it seems to be a small performance improvement.
=> Speed up _ interspersing by using bitstrings

.github/workflows/ci-markdown.yml, .markdownlint.jsonc, README.md
=> Also lint README.md using markdownlint-cli2-action

lib/elixir/lib/path.ex
=> Fix Path.absname/2 spec

lib/elixir/lib/file.ex, lib/elixir/lib/file/stream.ex, lib/elixir/test/elixir/file/stream_test.exs
Adds support for `File.stream!("/path", offset: 10)`.
=> Add offset option to File.stream!

lib/elixir/lib/string.ex, lib/elixir/test/elixir/string_test.exs
Pursuant to: https://groups.google.com/g/elixir-lang-core/c/aFIOplC3f1E/m/uGIMBtVxAQAJ
=> Add `String.replace_invalid/2`

lib/elixir/pages/anti-patterns/code-anti-patterns.md
=> fix minor typo

lib/mix/lib/mix.ex
=> Use Markdown in titles in the Mix docs

lib/elixir/lib/float.ex
=> Update float.ex description of ceil/2 and floor/2

lib/elixir/lib/string.ex
Precedence: https://github.com/elixir-unicode/unicode/issues/10
Significant changes include:
- Tweaking the input matching to reuse the match context
- Replace `replace_invalid_ii_of_iii/2` et al with guards, allowing BEAM to optimize creating the output binary
- Replace `::bits` with `::bytes` per BEAM's byte alignment optimizations (see below)
https://www.erlang.org/blog/more-optimizations/
> When the size of a segment of size 8, 16, 32, or 64 is matched, specialized instructions are used for x86_64. The specialized instructions do everything inline provided that the segment is byte-aligned.
=> Fix `String.replace_invalid/2` perf regressions

lib/elixir/lib/calendar/time.ex, lib/elixir/test/elixir/calendar/time_test.exs
Regression introduced in https://github.com/elixir-lang/elixir/pull/13122
=> Fix Time.add/3 for integer unit

lib/ex_unit/lib/ex_unit.ex, lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/lib/ex_unit/doc_test.ex
=> Add t/0 types to remaining ExUnit exceptions

lib/elixir/pages/anti-patterns/code-anti-patterns.md
=> Fixed a typo in code-anti-patterns.md

lib/ex_unit/lib/ex_unit/filters.ex, lib/ex_unit/test/ex_unit/filters_test.exs, lib/mix/test/mix/tasks/test_test.exs
=> Handle Windows separators on mix test

lib/elixir/pages/anti-patterns/design-anti-patterns.md, lib/elixir/pages/anti-patterns/process-anti-patterns.md, lib/elixir/pages/getting-started/binaries-strings-and-charlists.md, lib/elixir/pages/references/patterns-and-guards.md
Cherry-picked a bunch of commits from `main` to `v1.16`.
=> Backporting doc changes

lib/elixir/lib/kernel.ex
=> Fix typespec for the list concatenation operator

lib/elixir/lib/access.ex
Was going over the docs for `Access` and caught this one up.
=> Fix small typo

lib/ex_unit/lib/ex_unit/filters.ex, lib/ex_unit/test/ex_unit/filters_test.exs
Tentative fix for https://github.com/elixir-lang/elixir/issues/13257
=> Resolve relative paths in exunit filter

lib/elixir/lib/string.ex, lib/elixir/test/elixir/string_test.exs
=> Fix capitalize for single codepoint

lib/elixir/pages/getting-started/debugging.md
=> Improve wording in iex -S mix test --trace doc

README.md
Ref: https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/adding-a-workflow-status-badge#using-the-workflow-file-name.
=> docs: fixes README CI badge

lib/elixir/pages/anti-patterns/code-anti-patterns.md
"configure an anti-pattern" isn't very natural, I think this revision is better.
=> docs: minor simplification of anti-patterns page

lib/elixir/lib/task.ex, lib/elixir/lib/task/supervisor.ex
Addressed separately from https://github.com/elixir-lang/elixir/pull/13289 for easier review, and since these are independent changes.
=> Add @type async_stream_option to Task and Task.Supervisor

lib/elixir/test/elixir/kernel/binary_test.exs
Sorry I merged https://github.com/elixir-lang/elixir/pull/13325 too fast, the suggestion broke the test 🙇
=> Fix <> match test

lib/elixir/lib/kernel.ex
Following this discussion: https://github.com/elixir-lang/elixir/pull/13328#issuecomment-1935844628
=> Rename length -> size in binary_part/3

lib/elixir/lib/file.ex
Close https://github.com/elixir-lang/elixir/issues/13339
=> Fix :trim_doc example in doc

lib/elixir/lib/module/types/descr.ex, lib/elixir/test/elixir/module/types/descr_test.exs
=> Do not include dynamic() and ... if type is indivisible

README.md
This pull request updates grammar and phrasing found in `README.md`.
=> Fixes grammar and phrasing in `README.md`

lib/mix/lib/mix.ex
=> Fix Mix.install_project_dir/0 spec

lib/mix/lib/mix.ex
When the new installation uses `consolidate_protocols: false`, we want to cleanup `_build/dev/lib/mix_install/consolidated`. I think we can just remove the `mix_install` dir altogether before the installation, because it doesn't have any other modules to compile anyway.
=> Remove consolidated when restoring Mix.install/2 dir

lib/mix/test/mix_test.exs
=> Add test for consolidated removal when restoring Mix.install/2

lib/elixir/lib/string.ex, lib/elixir/pages/mix-and-otp/dynamic-supervisor.md
Comment inspired by [this commit](https://github.com/elixir-lang/elixir/commit/dd13c508e8cbf4650d3fe5f142980933d5ba8351#diff-fa333eb231fe218a47ae8d74c7ba07c6a1663953e0c9e4ee1c1ee88308f6a872R158)
=> Update strings typespecs and add comment

lib/elixir/lib/access.ex
This works like Enum.find/2 but for get_in/2 and friends.
=> Add Access.find/1

lib/logger/lib/logger/translator.ex, lib/logger/test/logger/translator_test.exs
Continuing https://github.com/elixir-lang/elixir/pull/13406.
=> Log process label in GenServer and :gen_event crash report

lib/elixir/lib/macro.ex, lib/elixir/lib/macro/env.ex, lib/elixir/src/elixir_dispatch.erl, lib/elixir/test/elixir/macro/env_test.exs
=> Add Macro.Env.expand_import/5 and Macro.Env.expand_require/6

lib/elixir/lib/string.ex
When reading through the docs this case was unclear to me and I had to try out what would happen.
=> [Docs] Clarify the behaviour when splitting a string 

lib/iex/lib/iex/helpers.ex
This PR adds some missing IEx helpers in the documentation.
=> Add some missing IEx helpers in the documentation list

lib/mix/lib/mix/tasks/deps.tree.ex, lib/mix/test/mix/tasks/deps.tree_test.exs
I was about 35-40 `--exclude` flags in before figuring out this is probably useful?
=> Add --umbrella-only to "mix deps.tree"

lib/mix/lib/mix.ex, lib/mix/lib/mix/shell.ex, lib/mix/lib/mix/tasks/cmd.ex, lib/mix/lib/mix/tasks/deps.ex, lib/mix/lib/mix/tasks/deps.tree.ex, lib/mix/lib/mix/tasks/test.ex, lib/mix/lib/mix/tasks/xref.ex
As mentioned by @josevalim. I love the italics as they make the flow nicer IMO.
=> Standardize "since" format for options in docs

lib/iex/lib/iex/pry.ex
This is just a refactor, no change in functionality.
=> Use `IEx.Pry.annotate_quoted/3` in `IEx.Pry.dbg/3`

lib/elixir/lib/calendar/duration.ex, lib/elixir/test/elixir/calendar/date_test.exs, lib/elixir/test/elixir/calendar/datetime_test.exs, lib/elixir/test/elixir/calendar/duration_test.exs, lib/elixir/test/elixir/calendar/naive_datetime_test.exs, lib/elixir/test/elixir/calendar/time_test.exs
Follow-up for https://github.com/elixir-lang/elixir/pull/13385#discussion_r1551447301
FYI @tfiedlerdejanze.
=> Duration.new! returns an ArgumentError on invalid unit

lib/elixir/lib/calendar/datetime.ex
Improve documentation of `calendar/datetime` a bit.
=> Improve docs readability 

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel_test.exs
Some decisions I took which we can totally change:
* Use `:lists` for that lil bit of perf.
* Do one pass on the list to do calculation + validation
* Keep a list of `seen_keys` so that we can raise on keys provided more than once (I think this is a nice touch for avoiding weird behaviors)
Should we also accept `to_timeout(:infinity)`? I don't think it's really useful but hey, who knows.
=> Add `Kernel.to_timeout/1`

CHANGELOG.md
Adding a note about a new option added in https://github.com/elixir-lang/elixir/pull/13128.
=> Update CHANGELOG for 1.17

lib/elixir/src/elixir_erl_pass.erl, lib/elixir/test/elixir/kernel/lexical_tracker_test.exs, lib/elixir/test/erlang/control_test.erl, lib/mix/test/mix/tasks/profile.fprof_test.exs
Draft for https://github.com/elixir-lang/elixir/issues/13475
I'm sharing my WIP to confirm the approach, but the CI is still broken because it breaks the lexical tracker tests:
I'm not sure if this would be an issue yet or if I should just adapt the tests to use non-inlined functions instead.
=> Inline some pure functions

lib/elixir/lib/calendar/date.ex, lib/elixir/lib/calendar/datetime.ex, lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/lib/calendar/time.ex, lib/elixir/src/elixir_erl_pass.erl, lib/elixir/test/erlang/control_test.erl
Close https://github.com/elixir-lang/elixir/issues/13475
=> Inline duration building in shift/2 functions

lib/elixir/lib/kernel.ex, lib/elixir/lib/module/types/descr.ex, lib/elixir/lib/module/types/expr.ex, lib/elixir/lib/module/types/of.ex, lib/elixir/lib/module/types/pattern.ex, lib/elixir/src/elixir_expand.erl, lib/elixir/test/elixir/kernel/warning_test.exs, lib/elixir/test/elixir/module/types/expr_test.exs
=> Perform type checking across comparison operators

lib/elixir/lib/module/types/descr.ex
Not 100% confident with my reverse-engineering, but at least all tests are passing.
I haven't benchmarked it properly, but I'm quite confident it should be faster since we are doing one loop for each approach.
This [simplified example benchmark](https://github.com/sabiwara/elixir_benches/commit/3cb29883ce02e321e52c29b749929f30398fe978) shows a single-pass on an iterator like `:maps.merge_with` is much faster than the `for ++ |> Map.new`.
If my understanding is correct:
- `open - open`: this is a simple `merge_with`, types that are just in one map can be kept as is
- `closed - closed`: this is a simple `intersect_with`, but we should throw if some keys weren't in both
- `open -closed`: we can just loop on open keys, check they are all present in the closed one, and update `closed` as an …
=> Reimplement and optimize intersection of map types

lib/elixir/lib/module/types/descr.ex
I tried to implement my suggestion from [here](https://github.com/elixir-lang/elixir/pull/13512#discussion_r1582637814), according to [this recommendation](https://hexdocs.pm/elixir/main/try-catch-and-rescue.html#throws).
Set aside performance concerns, the logic also feels easier to grasp with familiar boolean operators and functions (but that might be subjective).
=> Refactor boolean logic to use Enum.all?/2 instead of throwing

lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
Same as https://github.com/elixir-lang/elixir/pull/13603 for `unless`.
=> Implement dbg for unless/2 expressions

lib/elixir/lib/macro/env.ex, lib/elixir/src/elixir_import.erl
@lukaszsamson, what do you think about this change?
=> Use `__info__` callback directly

lib/elixir/lib/kernel/parallel_compiler.ex
As discussed in https://github.com/elixir-lang/elixir/pull/13589, this adds an option to change the concurrency of compilation when using `Kernel.ParallelCompiler` and also allows to use sequential compilation by setting it to `1`.
I'm not quite sure how to test this...
=> add max_concurrency to Kernel.ParallelCompiler

lib/elixir/src/elixir_erl_pass.erl, lib/elixir/test/elixir/kernel/with_test.exs
Close https://github.com/elixir-lang/elixir/issues/13665
=> Fix bug when using pinned variable in with else block

lib/elixir/lib/task/supervisor.ex
followup of https://github.com/elixir-lang/elixir/pull/13678
see https://github.com/elixir-lang/elixir/pull/13678#discussion_r1663544260
cc @michallepicki 
cc @josevalim
=> update Task.Supervisor.option type

lib/elixir/lib/io.ex
See #13721 for context.
Please squash when merging :)
=> Add some info about Unix style convention in IO

lib/elixir/src/elixir_clauses.erl, lib/elixir/src/elixir_expand.erl, lib/elixir/test/elixir/kernel/expansion_test.exs
Fixes https://github.com/elixir-lang/elixir/issues/13784
=> Correctly validate number of args for clauses with when in for and catch

lib/elixir/pages/getting-started/module-attributes.md
Thanks for the excellent docs, I am having a great time learning Elixir. Just noticed a small typo :slightly_smiling_face: 
Cheers.
=> Fix missing sentence subject

lib/ex_unit/lib/ex_unit.ex, lib/mix/test/mix/lock_test.exs
Been catching up with what was added to the language recently and came across 2 minor typos. This PR fixes them.
Thanks for all the hard work improving the language!
=> Fix two typos

lib/mix/lib/mix/task.compiler.ex
=> Add note on mix listener messages catch-all

lib/elixir/pages/getting-started/keywords-and-maps.md
Adjust a typo from the new updated docs
=> fix: small typo on new updated docs

lib/elixir/lib/module/types/descr.ex, lib/elixir/lib/module/types/expr.ex, lib/elixir/lib/module/types/of.ex, lib/elixir/lib/module/types/pattern.ex, lib/elixir/test/elixir/module/types/descr_test.exs, lib/elixir/test/elixir/module/types/expr_test.exs
=> Type map and struct updates

lib/mix/lib/mix/tasks/format.ex
=> Fix typo in formatter docs

lib/elixir/lib/map.ex
I tried this syntax to update multiple keys at once and to my happy surprise it worked! I don't think it is mentioned elsewhere in the Elixir docs.
=> Mention map update syntax

lib/iex/lib/iex.ex
The changes were made in da7e04a540d4a05616429af4fcb36287fb88fa1f directly on the v1.18 branch
=> Sync docs improvements around auto_reloading from the v1.18 branch

lib/elixir/src/elixir_erl.erl, lib/elixir/test/elixir/kernel/docs_test.exs
See https://github.com/erlang/otp/pull/8945#issuecomment-2541657253.
=> Make :source_path in docs chunk a charlist

lib/mix/lib/mix/tasks/escript.build.ex, lib/mix/test/mix/tasks/escript_test.exs
Closes #14096.
(Regression from #13730)
=> Fix mix escript.build when protocol consolidation is disabled

.github/workflows/release.yml
Fixes  #14099
Hopefully the last PR on this topic :smile:
=> Fix Release Signing Again

lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/lib/module/types/helpers.ex, lib/elixir/src/elixir_json.erl
=> fix typos.

lib/mix/lib/mix/project.ex
=> Print compilation lock waiting message to stderr

lib/mix/lib/mix/tasks/cmd.ex
Took a little while to find what I was supposed to do instead. Would be nice to just let users know in the deprecation warning. :)
=> Improved help on deprecation warning

lib/elixir/lib/string.ex
#14261 
Update the format consistently for String.chunk/2
=> Update doc for String.chunk/2

lib/elixir/lib/calendar/datetime.ex, lib/elixir/test/elixir/calendar/datetime_test.exs
=> do not truncate microseconds in DateTime.diff/3

.github/workflows/ort/action.yml
=> Fix typo in action.yml

lib/elixir/lib/kernel.ex
https://hexdocs.pm/elixir/1.17.0/Kernel.html#get_in/1
https://hexdocs.pm/elixir/1.16.3/Kernel.html#get_in/1
=> Add @doc since for get_in/1

lib/elixir/pages/getting-started/anonymous-functions.md
Adds words to correct the sentence phrasing.
=> Fix typo in anonymous-functions.md

.github/workflows/ort/action.yml
Fixes https://github.com/elixir-lang/elixir/pull/14266#discussion_r1967366470
Related PR: https://github.com/oss-review-toolkit/ort-ci-github-action/pull/45
=> Update ORT Action

lib/mix/lib/mix/tasks/xref.ex
Include a link to the wikipedia article on strongly connected components, and use the term in the output for clarity.
=> mix xref graph - rework cycles output description

lib/elixir/lib/stream.ex
https://hexdocs.pm/elixir/1.14.0/changelog.html#v1-14-0-2022-08-31
=> Add doc since for Stream.transform/5

lib/mix/lib/mix/compilers/test.ex, lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/tasks/test_test.exs
addresses https://github.com/elixir-lang/elixir/issues/14245
=> Return --exit-status + 1 when warnings as errors and test failures

lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/lib/ex_unit/runner.ex, lib/ex_unit/test/ex_unit/case_test.exs
As proposed in https://groups.google.com/g/elixir-lang-core/c/a_BJBRsJr94
=> Add `test_group` tag to the test context

lib/elixir/test/elixir/enum_test.exs
More like https://github.com/elixir-lang/elixir/pull/14470
=> More test coverage for Enum for non-list inputs

lib/elixir/pages/meta-programming/macros.md
=> Minor fix to the doc of macros section of meta-programming

lib/elixir/lib/file.ex
Added missed examples for `File` module
=> File examples

lib/elixir/lib/file.ex
Came across this one when reading the docs.
=> Fix minior typo in the docs

lib/logger/lib/logger.ex
=> Fix return value in logger filter docs
