elixir-lang/elixir

lib/elixir/lib/stream.ex, lib/elixir/test/elixir/stream_test.exs
`Stream.zip/1` uses empty accumulators to get the next element and this causes an issue
Fixes #8209
=> Raise on empty accumulators only on the first time inside `Stream.cycle/1`

lib/elixir/lib/record.ex, lib/elixir/test/elixir/record_test.exs
An implementation for #8210 , about a better error message for previously defined Records.
The previous error message can be seen in the linked issue.
The new error message is:
```
== Compilation error in file m.ex ==
** (CompileError) m.ex:5: record :r was previously defined
m.ex:5: (module)
(stdlib) erl_eval.erl:677: :erl_eval.do_apply/6
```
Any feedback is appreciated, especially around potentially pulling the `defines?` check and error message into its own function. The check and CompileError logic feels a little long in the `defrecord`/`defrecordp` functions, however, I couldn't figure out how to extract them since its inside macro definitions.
=> Add a check for previously defined records

lib/iex/lib/iex/introspection.ex, lib/iex/test/iex/helpers_test.exs
Closes #8208.
I went with one of many possible solutions. We can be more specific and say for sure that a type is private or is not found, or we can say "undefined or private" which is what we're doing here. I don't have a preference.
=> Fix the t/1 IEx helper for private types

lib/elixir/src/elixir_clauses.erl, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/kernel/expansion_test.exs, lib/elixir/test/elixir/kernel/raise_test.exs, lib/elixir/test/elixir/map_test.exs, lib/elixir/test/erlang/control_test.erl
Closes #8146.
Now using `else` without a `rescue`, `catch`, or `after` in `try` expressions is not allowed anymore.
I started with not allowing `else` by itself but I wonder if it would make sense to also disallow `else` if the only other clause is `after`. `else` is there to handle what happens if nothing is caught/rescued, so it might make sense to disallow `else`/`after` as well. Let me know your thoughts!
=> Forbid using only the "else" clause in "try"

lib/elixir/src/elixir_clauses.erl, lib/elixir/test/elixir/kernel/warning_test.exs
Related to #8219.
The errors could come from `def` as well (this is stored in the `:origin` key in the metadata).
=> Fix error messages for some "try" errors

lib/mix/lib/mix/tasks/format.ex
See #8088 for more information.
This simply rewords some of the help text supplied by `mix help format`.
=> Reword `mix format --check-equivalent` help text

lib/iex/lib/iex.ex
Adding some documentation on pasting multiline expressions into IEx. See [discussion on mailing list](https://groups.google.com/forum/#!topic/elixir-lang-core/4PbUMjjbfPM) for further information.
Best regards
Arno
=> docs: added a section on pasting multiline expressions into iex

lib/elixir/lib/dynamic_supervisor.ex, lib/elixir/lib/gen_server.ex, lib/elixir/lib/supervisor.ex, lib/elixir/test/elixir/dynamic_supervisor_test.exs
I tend to get confused when I read the GenServer docs on how the second argument of `start_link/3` gets transmitted to `init/1`. It's especially confusing in the context of the normal flow of child spec -> start_link -> init.
Here is an example:
`Supervisor.start_child(%{id: 1, start: {Foo, :start_link, [1,2,3]}})`
results in the following being called:
`Foo.start_link(1, 2, 3)`
So far so good. The `args` in `{mod, fun, args}` gets unpacked to multiple arguments in the `start_link` function.
The function header for `GenServer.start_link/3` looks like this: `start_link(module, args, options \\ [])`. Here we also see an `args`, but `args` actually represents a singular argument. This is confusing because it makes it unclear how `args` gets sent to `init/1`. With an argument like `args` I am …
=> Change `args` to `init_arg` in GenServer start_link/3 and init/1

lib/elixir/src/elixir_erl_compiler.erl, lib/elixir/src/elixir_erl_pass.erl, lib/elixir/src/elixir_map.erl, lib/elixir/test/elixir/kernel/warning_test.exs, lib/elixir/test/elixir/map_test.exs, lib/elixir/test/erlang/control_test.erl
Optimizes `:maps.put/3` to a VM operation instead of a remote call, including nested calls to it.
It does the same for `:maps.merge/2` with a simple map on the right side.
Keys that will be overridden are removed from the operation to avoid warnings.
Closes #7353
=>  Optimizes multiple :maps put and merge operations

lib/elixir/lib/io/ansi/docs.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/module.ex, lib/elixir/test/elixir/io/ansi/docs_test.exs, lib/iex/test/iex/helpers_test.exs
Associated issue: https://github.com/elixir-lang/ex_doc/issues/902
=> Link docs for defdelegate functions

lib/elixir/lib/kernel/typespec.ex, lib/elixir/src/elixir_erl_compiler.erl, lib/elixir/test/elixir/kernel/warning_test.exs
Refers to #5800 
Performs the `erl_lint` check `{underspecified_opaque, {TypeName, Arity}}` in Elixir.
After reading the Erlang/OTP codebase, it seems an "underspecified opaque" is an opaque type of arity 0 with a spec of `term` or `any`. [Here is the implementation in the Erlang/OTP codebase](https://github.com/erlang/otp/blob/master/lib/stdlib/src/erl_lint.erl#L2796-L2798) and [the test suite](https://github.com/erlang/otp/blob/master/lib/stdlib/test/erl_lint_SUITE.erl#L2606-L2613).
=> Warn on underspecified opaque types

lib/elixir/lib/task/supervisor.ex, lib/elixir/test/elixir/task/supervisor_test.exs
Related to #7786.
This PR raises when the max number of children for a `Task.Supervisor` is reached when starting a task with `Task.Supervisor.async/2,4` or `Task.Supervisor.async_nolink/2,4`. I am not handling anything related to `async_stream` but this should be a start.
The big diff in tests is related to moving things around in order to be able to use `describe` blocks. I just added one test for `async/2` and one for `async_nolink/2`.
=> Raise an error in Task.Supervisor.async when reaching max_children

lib/elixir/lib/exception.ex, lib/mix/test/mix/tasks/xref_test.exs
I'd like to propose excluding deprecated functions in "did you mean" message.
If a function is deprecated, it's useless to suggest it in the hints, since the compiler would eventually show some warnings if the users go with the deprecated suggestion.
=> Exclude deprecated functions in hints

lib/elixir/src/elixir.erl, lib/elixir/src/elixir_compiler.erl, lib/elixir/src/elixir_erl.erl, lib/elixir/src/elixir_erl_compiler.erl
This speeds up the Elixir compiler from 5-10% as we no
longer do duplicate work on erl_lint and expand_records.
We also avoid the copying of messages by controlling
exactly when the compiler spawns new processes.
=> Bypass erl_lint and spawn compiler processes manually

lib/elixir/lib/range.ex
After a discussion on IRC, there was a consensus that changing this wording would be clearer.
=>  Range documentation: "values" -> "integers"

lib/elixir/lib/task.ex, lib/elixir/lib/task/supervised.ex, lib/elixir/lib/task/supervisor.ex, lib/elixir/test/elixir/task/supervisor_test.exs
=> Raise when reaching max chidren in Task.Supervisor.async_stream

lib/ex_unit/lib/ex_unit.ex, lib/ex_unit/lib/ex_unit/event_manager.ex, lib/ex_unit/lib/ex_unit/on_exit_handler.ex, lib/ex_unit/lib/ex_unit/runner.ex, lib/ex_unit/test/ex_unit_test.exs
This is a preliminary PR in order to implement the --max-failures feature in ExUnit
It only renames arguments, variables, and reorganizes code.
As requested in https://github.com/elixir-lang/elixir/pull/8247#issuecomment-426530597
=> ExUnit: Rename variables and refactor config and loop 

lib/mix/lib/mix/dep.ex, lib/mix/lib/mix/tasks/compile.app.ex, lib/mix/test/mix/dep_test.exs, lib/mix/test/mix/tasks/compile.app_test.exs
Previously when using optional dependencies, they would
not be automatically included by compile.app in extra_applications.
This meant that an optional dependency would not be guaranteed
to be started before the application. Forcing users to handle
this logic in an ad-hoc fashion that is incompatible with
releases.
=> Include optional dependencies in extra_applications

Makefile
`ex_doc` task was using the proper name
==> ex_doc (ex_unit)
=> Use ex_unit and not exunit in Makefile log

lib/ex_unit/test/ex_unit/case_template_test.exs, lib/ex_unit/test/ex_unit/formatter_test.exs
=> Use setup_all instead of "setup all" to refer to the callback

lib/elixir/lib/enum.ex, lib/elixir/lib/exception.ex, lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel/raise_test.exs
Additionally, it corrects the CondClauseError message to:
"no cond clause evaluated to a truthy value"
=> Correct use of truthy and not true

lib/ex_unit/test/ex_unit/assertions_test.exs
It is misleading, as they are meant to be used as true or false.
=> ExUnit: Replace truthy and falsy functions in assertion tests

lib/logger/lib/logger/backend_supervisor.ex
1. Typo `s/shortbut/shortcut`
1. Use third-person singular for the description of `translate_backend`
1. Use backticks to refer to arguments
=> Improve docs of Logger.BackendSupervisor

lib/elixir/lib/task/supervisor.ex
The supervisor() type is defined in the Supervisor module not in the
Task.Supervisor module.
=> Point to the correct module documentation

lib/elixir/src/elixir_env.erl
Closes #8285
This warning has to be removed because all of the forms were unified in v1.7, making case/with/if to behave the same. That leads to undesired warnings in cases such as:
```elixir
a = 1
with {:ok, a} <- my_fun(a) do
:ok
end
```
=> Remove warning related to imperative assignments

lib/elixir/lib/kernel/typespec.ex, lib/elixir/lib/macro/env.ex
As discussed in https://github.com/elixir-lang/elixir/issues/5800#issuecomment-418888952
Redefining the pseudo-type "var" might lead to ambiguous typespecs.
Here is an example:
```elixir
defmodule DefineVarType do
@type my_var :: integer
@type var :: integer
@spec foo(x, x, var) :: boolean when x: var
def foo(x, y, z), do: x + y == z
@spec bar(x, x, my_var) :: boolean when x: my_var
def bar(x, y, z), do: x + y == z
end
```
=> Declare var/0 as built-in type

lib/elixir/lib/kernel/typespec.ex, lib/elixir/lib/module.ex, lib/elixir/src/elixir_module.erl, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/typespec_test.exs
=> Allow @type, @opaque, @typep, @spec, @callback, and @macrocallback to be used as module attributes

lib/elixir/lib/enum.ex
... so the integer in the "if" clause is different than the return value
=> Change Enum.reduce_while/3

lib/ex_unit/test/ex_unit_test.exs
- Use setup_all instead of "setup all".
- Rename tests from "pass" to "fail" as the names were inverted.
=> Touch up max_failures tests in ExUnit

lib/elixir/lib/kernel/parallel_compiler.ex, lib/elixir/lib/supervisor.ex, lib/elixir/src/elixir_erl_try.erl, lib/elixir/src/elixir_quote.erl, lib/elixir/test/elixir/kernel/expansion_test.exs, lib/mix/lib/mix/task.compiler.ex
- Replace "two element tuples" with "two-element tuples" for every number in 1..10
- Replace "2-element tuples" with "two-element tuples" for every number
- "1-based" with "one-based"
- "0-based" with "zero-based"
=> Update use of numbers as adjectives

lib/ex_unit/lib/ex_unit/formatter.ex, lib/ex_unit/test/ex_unit/formatter_test.exs
It is all the module that have been invalidated, not only one.
=> Update failure message in ExUnit setup_all callback

lib/ex_unit/lib/ex_unit/cli_formatter.ex, lib/ex_unit/lib/ex_unit/runner.ex, lib/ex_unit/lib/ex_unit/runner_stats.ex, lib/ex_unit/test/ex_unit_test.exs
There were 2 bugs in the current implementation
1. After the introduction of max-failures, the printing of the number of invalid tests went missing.
2. Invalid and Excluded (pending) tests were counted twice if setup_all failed.
A module with 1 skipped test and 1 excluded and 6 tests in it, it would be reported with a total of 8 tests.
This happened before max-failures was introduced.
A test file is provided including the new tests:
https://gist.github.com/eksperimental/30073f1b190fd2d34c75eadb92a41551
This PR takes the following approach:
1. We determine before running any test which are the tests to be skipped and excluded,
therefore:
A. these tests are always part of the total number of tests in the stats.
B. these tests are not counted as failures or invalid ones if setup_all fails. …
=> Fix 2 bugs in ExUnit.Runner

lib/elixir/lib/version.ex, lib/elixir/test/elixir/version_test.exs
- General improvements to docs
- Minor grammar corrections
- Add doc test examples to Version.match?/3 using :allow_pre option
- List all the operators allowed in requirements.
- Mention that the PATH part of the version can be used as operand with ~>
- Make a clarification that "`~>` will never include pre-release versions of its upper bound,
regardless of the usage of the `allow_pre:` option", and add tests to verify this
- The requirement table has been update:
- It doesn't use the consecutive PATCH number in the example, so `~> 2.1.2` will not use
`2.1.3-dev` but `2.1.6-dev` to make it that the upper bound is within the MINOR part
not the PATCH one
- Remove "-" and replace with "`true` or `false`" as it is not clear what "-" means in that example,
and it could be understood that the …
=> Improvements to the Version module documentation

lib/ex_unit/test/ex_unit_test.exs
... and beginning of line when applicable.
This makes sure we check for the full line,
avoiding unexpected results appearing at the end of the line.
Related discussion:
https://github.com/elixir-lang/elixir/pull/8312#discussion_r226867015
=> Check for line ending in output messages in ex_unit_tests.exs

lib/mix/lib/mix/tasks/test.ex
#7295 made tests raise an error if the option --only was used and it matched no tests, but it isn't mentioned in the documentation and it says `--only tag` and `--include tag --exclude test` are the same when now they are not, as `--include tag --exclude test` doesn't raise on no matches.
=> Document --only and --include --exclude difference

lib/mix/lib/mix/task.compiler.ex
For what I've seen, that's the format the Elixir codebase usually use.
=> Format error message in Mix.Task.Compiler

lib/elixir/lib/calendar/date.ex, lib/elixir/src/elixir_expand.erl, lib/ex_unit/test/ex_unit/failures_manifest_test.exs, lib/ex_unit/test/ex_unit_test.exs, lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/task_test.exs, lib/mix/test/mix/tasks/test_test.exs
To keep consistency in the codebase.
=> Remove backticks from error messages and test desc

lib/ex_unit/lib/ex_unit/filters.ex, lib/ex_unit/test/ex_unit/filters_test.exs
Fixes issues mentioned in #8335, particularly in this discussion:
https://github.com/elixir-lang/elixir/pull/8335#pullrequestreview-168148010
Tests should be first excluded, then included, and then skipped (if any left).
The only exception to the rule is when we explicitely include tests with :skip filter,
to which the :ok value is returned.
Fixes return value of `@spec`
=> Change the precedence in ExUnit.Filters.eval/4

lib/ex_unit/lib/ex_unit/cli_formatter.ex, lib/ex_unit/lib/ex_unit/formatter.ex, lib/ex_unit/test/ex_unit/formatter_test.exs
It was printing this when running: mix test --only foo
```
Including tags: [:foo]
Excluding tags: [:test]
```
which is deceiving beucase the order end up rendering useless the include filter.
Swaps the order then.
Additionally swaps the order in ExUnit.Formatter.format_filters/2 and tests,
while not necessary, maintaining the order is a good thing when it's something related
to precedence.
=> Change order in which filter meesage are printed in  ExUnit.CLIFormatter

lib/mix/lib/mix/project.ex, lib/mix/lib/mix/tasks/test.ex
When running `mix test file_in_one_child_app_but_not_another.exs` an error is logged and an exit/raise happens for every other child app stating `Paths given to 'mix test' did not match any directory/file...`. Since this is a frequent valid use case, this Pull Request changes the message to an `info()` (similar to the `There are no tests to run` message) and doesn't raise or exit when no matching files are found while recursing.
=> Info instead of error on unmatched umbrella tests

lib/elixir/lib/string.ex
doc string for split/3 seems to have been copied from contains?/1, with references left behind to true and false return values
=> Fix copy/paste error in doc string

lib/elixir/lib/calendar.ex
The function signature for Calendar.naive_datetime_to_iso_days does not include the time zone, but the doc string implies it should. The doc string is wrong.
=> Fix misleading doc string

lib/elixir/lib/module.ex
Not a grammar/english expert but it does sound little incorrect to me. Hopefully, I made the correction here.
=> fix minor grammar for docs of Module.register_attribute

lib/elixir/test/elixir/string_test.exs, lib/elixir/unicode/unicode.ex
In Elixir, `String.length("👨‍👩‍👧‍👦")` returns 2.
"👨‍👩‍👧‍👦" consists of 4 emojis joined with 3 ZWJs (ZERO WIDTH JOINER, U+200D). It should be regarded as a single Unicode grapheme cluster, so its length should be 1.
In the module `String.Unicode`, `next_extend_size` handles some combing characters in order to properly separate grapheme clusters. However, it doesn't take account of the cases where more than 2 emojis are joined with ZWJ. This commit will fix that.
=> Fix ZWJ handling in Unicode grapheme clusters

lib/mix/lib/mix/scm/git.ex
The Git SCM doesn't function properly when running under a slave node because the current working directory is pulled from the master instead of the current slave node. This PR updates calls to `System.cmd/3` to set the current working directory.
=> Set the cwd for system calls in the git scm

lib/iex/lib/iex.ex
Hi all, 
this fixes a few assorted apparent typos in `IEx`.
Cheers!
=> Fix typos in IEx module

CHANGELOG.md, lib/elixir/lib/code.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/kernel/special_forms.ex, lib/elixir/pages/Compatibility and Deprecations.md, lib/elixir/pages/Guards.md, lib/elixir/pages/Library Guidelines.md, lib/elixir/pages/Naming Conventions.md, lib/elixir/src/elixir_erl_compiler.erl, lib/elixir/src/elixir_map.erl, lib/mix/lib/mix/dep/converger.ex
Command used to detect these typos:
$ ag -s "\betc[^.]"
=> Use "etc." and not "etc"

lib/iex/lib/iex.ex
This was introduced accidentally in 7f771a4f3d55da1e3d2ac77a3543e220dd31444b
Making the backslash escape the closing backtick,
and ruining the documentation generated by ExDoc.
/cc @gusaiani
=> Fix breaking of documentation introduced in #8373

lib/elixir/lib/io/ansi/docs.ex, lib/elixir/test/elixir/io/ansi/docs_test.exs
=> Ignore escape characters inside markdown backticks

lib/elixir/lib/kernel/typespec.ex, lib/elixir/src/elixir_map.erl, lib/elixir/test/elixir/kernel/parallel_compiler_test.exs, lib/elixir/test/elixir/typespec_test.exs
Prior to this patch, if a module depends on the struct of
another module and that other module depends on the struct
of the first module inside typespecs, it would lead to a
compiler deadlock, which this deadlock would not happen
in "regular code".
This commit also adds a test to ensure @enforce_keys are
not enforced when expanding typespecs.
For now, we are using a compiler private API, but we should
provide a public version for it. This will be discussed below.
=> Resolve circular struct dependencies in typespecs

lib/elixir/lib/kernel.ex
Renamed the first argument to `term` to better describe the argument. Additionally, using `date` as an argument name was confusing for `sigil_T` and `sigil_N`.
=> Update Kernel sigil macro argument name to match others.

lib/elixir/lib/calendar/datetime.ex
Add example in docs for how to use it.
@michalmuskala the example shows how one can pass a `DateTime` and get the same wall time but in a different time zone as you mentioned in another PR.
=> Allow DateTime structs to be passed to DateTime.from_naive in typespecs

lib/eex/test/eex_test.exs, lib/elixir/lib/macro.ex, lib/elixir/test/elixir/macro_test.exs
Follow up of https://github.com/elixir-lang/elixir/issues/8078#issuecomment-412833448
=> Omit parens on calls with only do/end blocks (Macro.to_string)

lib/elixir/lib/calendar/datetime.ex, lib/mix/lib/mix/tasks/archive.install.ex, lib/mix/lib/mix/tasks/escript.install.ex, lib/mix/lib/mix/utils.ex, lib/mix/test/mix/tasks/archive_test.exs, lib/mix/test/mix/tasks/escript_test.exs, lib/mix/test/mix/utils_test.exs
Add a default timeout of 30 seconds and add it as an option.
Test locally using an unroutable local address 10.0.0.0(it timeouts).
Should fix #8252
Edit: I might have to pass in the `HEX_HTTP_TIMEOUT=120` env option from where this is called.
=> Wrap httpc read in a task to timeout

lib/iex/lib/iex.ex, lib/iex/lib/iex/app.ex, lib/iex/lib/iex/autocomplete.ex, lib/iex/lib/iex/broker.ex, lib/iex/lib/iex/evaluator.ex, lib/iex/lib/iex/helpers.ex, lib/iex/lib/iex/pry.ex, lib/iex/lib/iex/server.ex, lib/iex/test/iex/interaction_test.exs, lib/iex/test/iex/server_test.exs, lib/iex/test/test_helper.exs
Since now there may be multiple servers running,
we also introduced IEx.Broker to negociate pry
requests across multiple sessions.
Shell sessions though are tracked separately from
the remaining ones, as we delegate the shell control
to Erlang's user_drv.
Closes #8203.
=> Introduce IEx.Server.run/1

lib/elixir/lib/gen_server.ex
* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.7.4 (compiled with Erlang/OTP 21)
* Operating system: macOS 10.13.6
The [docs of `GenServer.cast/2`][0] currently state: 
> `handle_cast/2` will be called on the server to handle the request. In case the `server` is on a node which is not yet connected to the caller one, the call is going to block until a connection happens. This is different than the behaviour in OTP's `:gen_server` where the message is sent by another process in this case, which could cause messages to other nodes to arrive out of order.
The above documentation is not correct when running on top of Erlang/OTP 21. In Erlang/OTP 21 the C implementation of `erlang:send/3` was changed to implement "truly asynchronous auto-connect", as described in the …
=> Fix GenServer.cast/2 doc

lib/elixir/lib/exception.ex, lib/elixir/test/elixir/kernel/raise_test.exs
Now if the term is a function that couldn't be found because it's
referencing an anonymous function from a previous version of a given
module, it says as much instead of saying it expected a function.
Resolves #8406
=> Improve error message for `BadFunctionError`

lib/logger/lib/logger.ex, lib/logger/test/logger_test.exs
Closes #8389 
Update test to reproduce the issue.
Do not check compile time purge matching in case of direct `Logger.log` call.
=> Fix direct `Logger.log` call in case of compile_time_purge_matching logger option

lib/elixir/lib/code/formatter.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/list.ex, lib/elixir/src/elixir_parser.yrl
Today charlist interpolation is quivalent to calling `String.to_charlist`
on the equivalent string interpolation. It can be more efficient by
leveraging chardata support in the `:unicode` module and encoding as a
list of literal binaries and results of `Kernel.to_string` calls for the
interpolated segments.
The PR also adds a `List.to_charlist` function that accepts a nested list of chardata and returns a flattened charlist.
=> Compile charlist interpolation more efficiently 

lib/elixir/lib/calendar/datetime.ex
Using `inspect` instead of interpolating directly the date time value (like other error messages in this module).
=> Improve error message on DateTime.add/4

lib/mix/lib/mix/tasks/new.ex, lib/mix/test/mix/tasks/new_test.exs
The module name was used in the templates, but the app name was used for
the file names. Now the module name is used for both.
For example:
```bash
mkdir foo
cd foo
mix new . --module Bar
```
...creates a `Bar` module as expected, but the module's filename is `lib/foo.ex`. This, of course, should be `lib/bar.ex` instead. The reason for the wrong filename is that the code currently uses the (inferred) app name when creating the file, which in this case is `foo`.
=> Use --module value when setting up filenames in mix new

lib/elixir/lib/gen_server.ex
Based on Erlang reference [here](http://erlang.org/doc/reference_manual/expressions.html#send):
```
Sending a message to a pid never fails, even if the pid identifies a non-existing process.
```
We do not need try block anymore because there is a `is_pid(to)` guard, which was added from #4876.
Therefore, try block within `GenServer.reply` is unnecessary and [confusing](https://elixirforum.com/t/when-would-send-raise-an-error/18177). We should remove it.
=> Remove unnecessary try block in GenServer.reply

lib/elixir/lib/task.ex
Documentation snippets for supervised `Task`s were misleading -- there is no `Supervisor.start_link/1`. 
This commit fixes it.
=> Update supervised Task docs

lib/elixir/lib/registry.ex
Made a sweep through the docs and found two more misleading snippets.
Similar to https://github.com/elixir-lang/elixir/pull/8422
=> Update Supervisor calls in Registry docs

lib/ex_unit/test/ex_unit/capture_log_test.exs, lib/logger/lib/logger.ex, lib/logger/test/logger/translator_test.exs, lib/logger/test/logger_test.exs
Otherwise it is impossible to dynamically remove them,
which partially defeats the point of adding them dynamically
in the first place.
Therefore this commit moves the whole dynamic backend
management to the user.
Closes #8213
=> No longer persist dynamically added logger backends

lib/mix/lib/mix/tasks/deps.ex
Fix a typo for the `runtime` option documentation of the Mix.Task.Deps module
=> Fix a typo in the Mix.Task.Deps module

lib/elixir/src/elixir_erl.erl, lib/elixir/test/elixir/kernel/docs_test.exs
Handles the special fn case in the signature_to_binary function. As of now I hardcoded the signature of fn, I am not sure this is the intended behavior? 
Fixes #8428
=> add special fn case to signature_to_binary

lib/elixir/src/elixir_fn.erl
Fix a warning that has started to occur because of a recent bug fix in
Erlang/OTP (using `fun M:F/A` could suppress warnings for unused
variables).
=> Eliminate warning for an unused variable

lib/mix/test/test_helper.exs
Backends added or removed dynamically via `Logger.add_backend/2` or `Logger.remove_backend/2` are not persisted. Backends must be removed from the application environment explicitly.
It removes the `[info]` from the output of the tests.
```
==> mix (ex_unit)
Excluding tags: [windows: true]
........................................
11:44:08.368 [info]  Application foo exited: :stopped
11:44:08.368 [info]  Application bar exited: :stopped
..
11:44:08.806 [info]  Application foo exited: :stopped
11:44:08.806 [info]  Application bar exited: :stopped
...
11:44:09.626 [info]  Application foo exited: :stopped
11:44:09.626 [info]  Application bar exited: :stopped
......
11:44:12.480 [info]  Application foo exited: :stopped
11:44:12.480 [info]  Application bar exited: :stopped
......
11:44:14.665 …
```
=> Remove :console backend from the application environment in Mix tests

lib/elixir/lib/dynamic_supervisor.ex
Since we have an Elixir type for `Supervisor.child_spec()` it's better
to link to that instead of the Erlang type docs.
=> Change type to link to Elixir docs [ci-skip]

lib/elixir/lib/enum.ex
This patch explains how does `Enum.reduce_while/3` behave when the enumerable is exhausted.
Since I was on it, the patch removes an article too. The opening sentence was at some point
> Reduces the enumerable until ...
where "enumerable" is a noun, but that changed in 8c5b5bd0fbb3fdac9730259291b44841af7987c1 to
> Reduces the `enumerable` until ...
The first argument is either "the enumerable" or just "`enumerable`".
=> Improve the documentation of Enum.reduce_while/3

lib/elixir/lib/calendar.ex, lib/elixir/lib/calendar/datetime.ex
Instead of requiring a DateTime struct, allow a map containing at least
those fields. In the same way Calendar.naive_datetime is used in
NaiveDateTime (and Calendar.time/Time, Calendar.date/Date).
This way custom types can be used as long as they have the necessary fields required by the DateTime functions.
cc @josevalim
=> Add Calendar.datetime type and allow it in DateTime functions

ISSUE_TEMPLATE.md
It could be useful to link directly to the mailing list in the GitHub issue template.
The same linking as we do in the Elixir website, see https://elixir-lang.org/development.html
=> Update GitHub issue template with mailing list link

lib/elixir/lib/calendar.ex
As discussed in https://github.com/elixir-lang/elixir/commit/edd2c6f780532f6bed4addfd087a06172cc679b1#r31550243
=> Correct return types for c:Calendar.day_of_era/3

lib/elixir/lib/range.ex
Covers degenerate case `a..a`.
=> Cover degenerate case in the description of ranges

lib/iex/lib/iex.ex, lib/iex/lib/iex/pry.ex
Hi all, just two little typos I found while studying Elixir's source.
Cheers!
=> Fix typos in IEx modules' docs

lib/elixir/docs.exs
Ref https://github.com/elixir-lang/ex_doc/pull/930
=> Don't trigger ExDoc warnings on compatibility-and-deprecations page

lib/elixir/lib/string.ex
I believe this recommendation might be good from some chats with @josevalim this week, but I am not 100% sure.
Let me optimistically propose it. This week in AoC I used this function and would have benefited from this remark when reading the documentation of `String.next_codepoint/1`. And if it is not good, I'll learn something.
Regarding the code fences in the examples, I have seen docs don't generally use them, but seemed appropriate in this case. Of course, let me know if you'd prefer a different doctestable example.
=> Add style remark in String.next_codepoint/1

lib/iex/lib/iex/helpers.ex
Before:
```iex
iex(1)> i [1 | 2]
Term
[1 | 2]
Data type
List
Reference modules
List
Implemented protocols
IEx.Info, String.Chars, Enumerable, Inspect, List.Chars, Collectable
```
Now:
```iex
iex(1)> i [1 | 2]
Term
[1 | 2]
Data type
List
Reference modules
List
Implemented protocols
Collectable, Enumerable, IEx.Info, Inspect, List.Chars, String.Chars
```
=> IEx helper "i" lists Implemented Protocols sorted alphabetically

lib/elixir/lib/enum.ex
In the past, we had decided to not use is_function/1 or
is_function/2 in guards in Enum because the underlying
BadFunctionError was clearer than a FunctionClauseError.
However, today this is no longer necessarily true, due
to exception blaming that is capable of diffing the clauses
in a FunctionClauseError.
Furthermore, not checking for the argument can be an issue
on arguments that are rarely invoked, such as the empty
clause default function passed to Enum.min/2 friends, which
makes some mistakes impossible to catch. For example, someone
may write:
Enum.min(non_empty_list, &elem(&1, 1))
The user intent here was actually to call `Enum.min_by/2`,
but without the guard, everything appears to work and the
error can go undetected.
Therefore this commit adds function guards to the min and
max …
=> Check for function arity in guards for aggregates with empty handling

lib/elixir/lib/list.ex, lib/elixir/test/elixir/list_test.exs, lib/iex/lib/iex/info.ex
Related discussion: https://github.com/elixir-lang/elixir/pull/8469#issuecomment-444784727
I had to create a List.improper?/1 in the same fashion of Keyword.keyword? and List.ascii_printable?
Please do not squash these two commits when merging.
=> [WIP] IEx: Special case "i" helper for improper lists

lib/elixir/lib/string.ex, lib/elixir/unicode/unicode.ex
The current wording talks about the "validity of a codepoint", and says that `String.next_codepoint/1` might return an "invalid codepoint" (of which byte length?).
I think this may be confusing, because codepoints are valid by definition. Codepoints are encoded as sequences of bytes that make sense as a unit according to UTF-8. If the sequence of bytes does not make sense, you don't have a codepoint.
Let me propose this rewording, in which we carefully avoid "codepoint" and talk just bytes.
The example is not a doctest because I could not make it pass, it raised `UnicodeConversionError`.
=> Clarify String.next_codepoint/1 re invalid UTF-8

lib/elixir/lib/io.ex, lib/elixir/lib/path.ex
I think it's nicer to link to Elixir types instead of Erlang types where
we can, and these are both places where we definitely can.
=> Remove references to Erlang types

lib/elixir/lib/io/ansi/docs.ex, lib/elixir/test/elixir/io/ansi/docs_test.exs
This is a naive fix of formatting "`http_bar`", but will not fix "`http://elixir.org/foo_bar`".
Closes #8449
=> Stricter link check in IO.ANSI.Docs module

lib/elixir/lib/io/ansi/docs.ex, lib/elixir/test/elixir/io/ansi/docs_test.exs
It follows the same rules as URI.parse/1
Related to #8494
=> IO.ANSI.Docs: Make regex in escape_underlines_in_link/1 handle all schemes

lib/elixir/pages/Operators.md
I don't think this belongs in the Operators documentation.
- It is not a standalone operator, i.e. valid only in map syntax
- List of operators does not include `->`
```
iex(1)> quote do: a => b
** (SyntaxError) iex:1: syntax error before: '=>'
```
=> Remove `=>` operator from documentation

lib/elixir/lib/list.ex, lib/elixir/test/elixir/list_test.exs
- Simplify logic
- Add specs
- Validate specs with guards, raising on non-lists
- Add tests
- Correct documentation about improper lists
- Rename argument `counter` to `limit`
=> Revamp List.ascii_printable?/2

lib/mix/lib/mix/compilers/elixir.ex, lib/mix/lib/mix/utils.ex
OS time must be used when comparing against file system timestamps.
=> use System.os_time

lib/elixir/lib/file.ex
Bug recently introduced in 499446737ea0008bbb1c69a3e2f953fc7e1fedae
=> Fix day in t:File.erlang_time

lib/mix/lib/mix/compilers/erlang.ex, lib/mix/lib/mix/tasks/compile.xref.ex
Follow up on 499446737ea0008bbb1c69a3e2f953fc7e1fedae that already did it for the Elixir compiler.
=> Use System.os_time/1 in the Erlang compiler as well

lib/elixir/lib/task.ex, lib/elixir/lib/task/supervised.ex, lib/elixir/lib/task/supervisor.ex, lib/elixir/test/elixir/task/supervisor_test.exs, lib/elixir/test/elixir/task_test.exs, lib/logger/lib/logger/backends/console.ex, lib/logger/lib/logger/translator.ex, lib/logger/test/logger/translator_test.exs
This allows us to track which process invoked the Task
besides its ancestors in the supervision tree.
Closes #7995
=> Add $callers tracking to Task

lib/iex/lib/iex.ex
As requested at:  https://github.com/elixir-lang/elixir/pull/8508#discussion_r240724685
If someone else could please test to verify, it works here but I don't know if work did anything to the powershell on these computers and I don't have Windows anywhere else to test.
Actually... just downloaded powershell onto linux as well (should this section just be called powershell since PS works on many OS's now?) and tested it there as well, looks good:
```powershell
PS /home/overminddl1/elixir/elixir> $env:ERL_AFLAGS = "-kernel shell_history enabled"
PS /home/overminddl1/elixir/elixir> $env:ERL_AFLAGS                                  
-kernel shell_history enabled
PS /home/overminddl1/elixir/elixir> bash -c 'echo $ERL_AFLAGS'                       
-kernel shell_history enabled
```
=> Add powershell environment to iex documentation

lib/elixir/pages/Operators.md, lib/elixir/src/elixir_parser.yrl
This is part one (of two hopefully), broken into several commits to ease the reviewing
=> Review of Operators (part 1)

lib/elixir/pages/Guards.md, lib/elixir/pages/Operators.md
Now that ExDoc automatically links to functions in
Kernel and Kernel.SpecialForms, when linking to them in custom links,
we can leave out the module name.
=> Simplify custom links when linking to Kernel and SpecialForms

lib/iex/lib/iex/introspection.ex, lib/iex/test/iex/helpers_test.exs
=> Use typespec info in IEx.Helpers.b/1

lib/iex/lib/iex/introspection.ex, lib/iex/test/iex/helpers_test.exs
Macrocallbacks are internally stored prefixing them with "MACRO-". However, that prefix should be removed when presenting the callback information to the user.
Before:
```elixir
@optional_callbacks ["MACRO-foo": 3]
```
After:
```elixir
@optional_callbacks [foo: 3]
```
=> Format optional macrocallbacks in IEx.Helpers.b/1

lib/elixir/lib/macro.ex
Was poking around in the `Macro` module and realized these functions were missing `@spec`s.
=> Add missing typespecs to Macro.underscore/1 and Macro.do_underscore/2

lib/elixir/lib/collectable.ex
In the example, add the type the protocol is implemented for (`MapSet`).
When reading the documentation is not obvious that this code is extracted from the `MapSet` module and therefore the `for: MapSet` is redundant.
=> Minor doc changes in Collectable protocol moduledoc

lib/mix/lib/mix/tasks/new.ex
I think there are pros and cons about trailing commas, but this change is consistent with the formatter.
=> Remove trailing commas in templates

lib/elixir/lib/code.ex, lib/elixir/lib/kernel/typespec.ex, lib/elixir/lib/macro/env.ex, lib/elixir/lib/uri.ex, lib/elixir/pages/Compatibility and Deprecations.md, lib/elixir/test/elixir/kernel/warning_test.exs, lib/ex_unit/lib/ex_unit/failures_manifest.ex
`%{required(foo) => bar}` and `%{optional(foo) => bar}` should be used instead.
=> Deprecate `%{key => value}` in typespecs

lib/mix/lib/mix/dep.ex
As specified by the comment `# TODO: Remove this on v1.8`
=> Remove deprecated Mix.Dep.loaded/1

lib/elixir/lib/kernel.ex
* `__protocol__` doesn't accept `:name`
* Elaborate on atoms that `__protocol__` accepts
* Change code example to doctest and fix it
=> Improve `defprotocol/2` docs

lib/iex/lib/iex/cli.ex, lib/iex/lib/iex/server.ex
Prior to this patch, IEx would just hang, as stdin
was dead. This aligns the behaviour with the `erl`
shell.
=> Halt IEx when it receives EOF from stdin

lib/iex/lib/iex/cli.ex
Fixes #8562: IEx should print a warning when using --remsh with "dumb" terminal
=> #8562 Fix: added IEx warning when using --remsh with 'dumb' terminal

lib/elixir/lib/kernel/typespec.ex, lib/elixir/test/elixir/typespec_test.exs
Closes https://github.com/elixir-lang/elixir/issues/8564
This is my first attempt to contribute code to elixir, so please forgive me if this PR is completely naive.
Besides adding the `is_list/1` guards, I have updated the error message to specify that record specifications must use an atom `literal` as the name, to make it clear that the type `atom` is also not valid.
=> User defined types with the name `record` fail to compile in 1.8.0-rc.0

lib/elixir/lib/exception.ex
It was introduced in https://github.com/elixir-lang/elixir/pull/7803, looks like it was accidentally made public (no docs, no specs)
It shipped in Elixir v1.7 so technically this would be a breaking change. I'm happy to deprecate/doc false it instead.
=> Make KeyError.message/2 private

lib/elixir/lib/system.ex
- Give more detailed spec
- Correct mention to keyword list when it is a map that it returns.
- Compile a list of keys returned and what each one is
- Add example
=> Improve spec and documentation for System.build_info/0

lib/elixir/lib/keyword.ex
Added guards to ensure only lists can be passed to `Keywords.merge/3`.
I thought about adding this change after realizing the `merge/3` method had inconsistent behavior...
```elixir
Keyword.merge([a: 1, b: 2], nil)
Keyword.merge([], nil)
```
What do you think?
=> Added additional guards for Keywords.merge/3.

lib/elixir/lib/enum.ex
It was confusing to say in the summary that:
"Takes the first `amount` items from the `enumerable`."
when it can be from the end as well, depending on the sign of `amount`.
=> Improve documentation for Enum.take/2

lib/ex_unit/lib/ex_unit.ex
Now we're specifying what that integer actually represents -
microseconds!
=> Add documentation about ExUnit.Test.time

lib/elixir/lib/io/ansi.ex
Hi all, and happy New Year.
This adds a missing verb, from `will emitted` to `will be emitted`, in `IO.ANSI.format/2`'s doc.
Cheers!
=> Add verb to IO.ANSI.format/2 doc

bin/elixir, bin/elixir.bat, bin/iex, bin/iex.bat
The rationale is that those options should almost always be given in quotes so by adding the quotes in the documentation we can signal the intent.
=> Suggest quotes in the executables help where appropriate 

lib/elixir/lib/kernel/special_forms.ex, lib/elixir/src/elixir_bitstring.erl, lib/elixir/test/elixir/kernel/expansion_test.exs
Closes #8589 
Binary/bitstring matching allows to dynamically define the `size` of the binary in certain conditions:
* if the `size` variable is defined prior to the pattern match:
iex> size = 8
iex> <<a::size(size), rest::binary>> = "hello"
iex> a
104
* if the `size` variable is matched within the same binary/bitstring match, prior to its use:
iex> <<name_size::size(8), name::binary-size(name_size), _rest::binary>> = <<5, "Frank the Walrus">>
iex> name
"Frank"
Other cases are considered illegal patterns, for example:
{name_size, <<name::binary-size(name_size), _rest::binary>>} = {5, "Frank the Walrus"}
This commit raises a `CompileError: undefined variable ...` for such cases.
=> Error on undefined variables in bitstring segments

lib/elixir/lib/string_io.ex, lib/elixir/test/elixir/string_io_test.exs
Related to #8507 
Non-printable arguments were killing the StringIO process, which was killing the Logger handler associated to it. That was causing some errors when users were running their test suites with `capture_log: true`, because the proxy (logger handler) was not there when `ExUnit.CaptureLog` was trying to remove it.
=> Handle non-printable arguments in StringIO gracefully

lib/elixir/lib/calendar/iso.ex, lib/elixir/test/elixir/calendar/iso_test.exs
As discussed in https://github.com/elixir-lang/elixir/pull/8460/files#r238752220
Provides more information than the previous `MatchError`:
```
** (MatchError) no match of right hand side value: false
```
=> Provide better errors with invalid dates in Calendar.ISO

lib/iex/lib/iex/evaluator.ex, lib/iex/test/iex/interaction_test.exs
Loading .iex.exs with compile or runtime errors currently halts the system. 
This fix intended to print error message, but still run iex with default state.
=> Fix .iex.exs error behaviour #8618

lib/elixir/lib/dynamic_supervisor.ex
I saw this while browsing the DynamicSupervisor code and was reminded of my previous PR #8226
=> Use consistent variable naming in DynamicSupervisor docs

lib/elixir/lib/file.ex
The note was taken from the :file.read_file_info/1 Erlang documentation.
=> Add note to File.stat/2 and File.lstat/2 on optimization

lib/elixir/lib/io/ansi/docs.ex, lib/elixir/test/elixir/io/ansi/docs_test.exs
I've nailed down the bug described in #8629
The case was that `.*?` could be more eager than expected when it is followed by other statement.
=> Fix parsing Markdown links for h function (fix #8629)

lib/iex/lib/iex/introspection.ex
Hi all, 
this removes an extraneous `to` from a `puts_error` message:
`would like to more information` → `would like more information`
(I also considered changing it to `would like to see more information`...if that makes more sense, please let me know.
Cheers!
=> Improve IEx.Introspection.h/1 error message

lib/elixir/pages/Library Guidelines.md
unexpected `end` in Application template
=> typo in documentation: Library Guidelines

lib/elixir/lib/module.ex, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/macro_test.exs, lib/elixir/test/elixir/module_test.exs
It offers alternatives to every possible function that has an equivalent
function for compiled modules.
It shows the mfa of the called function in the error message,
since before it only showed the function name.
=> Improve docs in Module functions and raise errors

lib/elixir/src/elixir_erl_pass.erl
Elixir's `with` is expanded into a series of nested cases. For example, this code:
```elixir
with {:ok, a} <- fun_a(),
{:ok, b} <- fun_b() do
wa = fun_w(a)
wb = fun_w(b)
else
error -> {:c, error}
end
```
would be expanded to something similar to this:
```elixir
case fun_a() do
{:ok, a} ->
case fun_b() do
{:ok, b} ->
wa = fun_w(a)
wb = fun_w(b)
var1 ->
case var1 do
error -> {:c, error}
var2 -> error({with_clause, var2})
end
end
var1 ->
case var1 do
error -> {:c, error}
var2 -> error({with_clause, var2})
end
end
```
The generated code can be optimized for else clauses that only contain a single catch-all clause (a variable that would bind everything). Applying this optimization, the code of the example above would be:
```elixir
case fun_a() do
{:ok, a} ->
case fun_b() do
{:ok, b} ->
wa = …
```
=> Optimize generated code for catch-all else clauses

lib/ex_unit/lib/ex_unit/filters.ex, lib/ex_unit/test/ex_unit/filters_test.exs, lib/mix/lib/mix/tasks/test.ex
As [discussed in the mailing list](https://groups.google.com/d/msg/elixir-lang-core/7yejSvr0RMM/Cfv5JXDnBgAJ), here's a PR that will allow a
shorthand for filtering ExUnit tests by more than one line number at a
time.
For now this doesn't address the question of running single tests in
more than one file since that would be a much larger change. If we do
want to allow that, we can add it later on, but it should be an addition
to the work here, not a replacement.
=> Add ability to filter by more than one line number

lib/mix/lib/mix/project.ex
Typespecs are not shown because the default values have been omitted
Example: https://hexdocs.pm/mix/master/Mix.Project.html#apps_paths/1
=> fixed specs for Mix.Project umbrella?/1 and apps_paths/1

lib/mix/test/mix/tasks/compile.elixir_test.exs, lib/mix/test/mix/tasks/compile.xref_test.exs, lib/mix/test/mix/tasks/format_test.exs, lib/mix/test/mix/tasks/loadconfig_test.exs, lib/mix/test/mix/utils_test.exs
using only 2038 to keep 32-bit UNIX systems happy.
Background:
As part of my work on reproducible builds for openSUSE, I check that software still gives identical build results in the future.
The usual offset is +15 years, because that is how long I expect some software will be used in some places.
=> Make tests pass in 2020

lib/eex/test/eex/smart_engine_test.exs
The existing test was not actually testing anything, as
the default argument to Keyword.get/3, 0, matched one of the
expected values.
=> Ensure we're testing the actual assignment metadata

lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/tasks/test_test.exs
Right now the behavior when trying to use the shorthand for running a
single test for multiple files is confusing. We're now explicitly
disallowing this by raising an error when this happens.
This is how it looks in a shell now:
```
$ ../elixir/bin/elixir ../elixir/bin/mix test test/benchee_test.exs:12 test/benchee/benchmark_test.exs:18
** (Mix) Line numbers can only be used when running a single test file
$ ../elixir/bin/elixir ../elixir/bin/mix test test/benchee_test.exs:12 test/benchee/benchmark_test.exs   
** (Mix) Line numbers can only be used when running a single test file
$ ../elixir/bin/elixir ../elixir/bin/mix test test/benchee_test.exs test/benchee/benchmark_test.exs:18 
** (Mix) Line numbers can only be used when running a single test file
$ ../elixir/bin/elixir …
```
=> Raise error when attempting to run single line tests on multiple files

lib/elixir/lib/calendar/iso.ex
It was missing since 
```elixir
def time_to_string(hour, minute, second, microsecond, format \\ :extended)
```
was split into `time_to_string/4` and `time_to_string/5` without default value in #6331
=> Added missing doc and spec to Calendar.ISO.time_to_string/5

lib/mix/lib/mix/project.ex
It was the only function in this module that did not have spec.
Generally, most functions have typespec, but there are some that do not. Is there any rule when you do not add them?
=> added missing spec for Mix.Project.consolidation_path/1

lib/elixir/lib/calendar/date.ex, lib/elixir/lib/calendar/iso.ex, lib/elixir/lib/calendar/time.ex, lib/elixir/test/elixir/calendar/iso_test.exs
=> Use default args in Calendar.ISO.time_to_string/*

lib/iex/lib/iex/introspection.ex, lib/iex/test/iex/helpers_test.exs
The results were not sorted, when calling:
h Module.function_name
Example:
```
iex)> h :erlang.float_to_binary
:erlang.float_to_binary/2
@spec float_to_binary(float, options) :: binary()
when float: float(),
options: [option],
option:
{:decimals, decimals :: 0..253}
| {:scientific, decimals :: 0..249}
| :compact
Module was compiled without docs. Showing only specs.
:erlang.float_to_binary/1
@spec float_to_binary(float) :: binary() when float: float()
Module was compiled without docs. Showing only specs.
```
Now the results are sorted by arity.
=> IEx h: sort results by arity

lib/mix/lib/mix/tasks/release.ex
You can see it missing here: https://hexdocs.pm/mix/master/Mix.Tasks.Release.html#module-requirements
=> add missing "`" to Mix.Release docs

lib/mix/lib/mix.ex
This change adds function specs to `Mix`.
I'm not completely sure if the specs for `Mix.shell/0` and `Mix.shell/1` are correct; I've used `module` as return type and parameter type respectively given that I'm not sure if it's possible to express the contract between a module and `Mix.Shell` in a more specific way.
=> Add function specs to Mix public interface

lib/elixir/lib/kernel/typespec.ex, lib/elixir/test/elixir/typespec_test.exs
For this module:
defmodule M do
import Record
@type t :: record(:r, foo: atom(), bar: integer())
defrecord :r, [:foo, :bar]
end
`@type t` is defined as the following:
Before this patch:
@type t() :: {:r, atom(), integer()}
After this patch:
@type t() :: {:r, foo :: atom(), bar :: integer()}
This is similar to loading record definition in Erlang shell:
1> rr(file).
[file_descriptor,file_info]
2> rl(file_descriptor).
-record(file_descriptor,{module :: module(),data :: term()}).
ok
=> Include field names in generated type for records

lib/elixir/lib/task.ex
The majority of the text was taken from the release notes:
https://elixir-lang.org/blog/2019/01/14/elixir-v1-8-0-released/
The example at the end is my own.
=> Document the `$callers` tracking that is new in Elixir 1.8

lib/elixir/lib/protocol.ex
Hi!
During troubleshooting an issue in our system (*), I noticed that non-consolidated protocols require one round trip of message exchange between the code server process per invocation.
I'm not sure why it's necessary; couldn't it be a scalability bottleneck?
Simple try-rescue gives me the following performance benefit for sequential execution:
- Before the change
```ex
iex(1)> t = System.system_time(:millisecond); Enum.each(1..10_000_000, &inspect/1); System.system_time(:millisecond) - t
22177
```
- After the change
```ex
iex(1)> t = System.system_time(:millisecond); Enum.each(1..10_000_000, &inspect/1); System.system_time(:millisecond) - t
5247
```
Probably I'm missing some important role of `Code.ensure_compiled?/1` and `function_exported?/3`?
In that case feel free to reject this PR …
=> Optimize performance of dynamic dispatching for non-consolidated protocols

lib/elixir/lib/kernel/special_forms.ex
Hi all,
this fixes two typos in `Kernel.SpecialForms` docs.
Cheers!
=> Fix typos in Kernel.SpecialForm docs

lib/elixir/pages/Typespecs.md
While "false or true" is alphabetically ordered, the most common
way it is used in the English language is "true or false" and this
is the only one reference in Elixir core that we say "false or true".
=> User "true or false" instead of the other way around

man/common, man/elixir.1.in, man/elixirc.1, man/iex.1.in, man/mix.1
I described in `elixir(1)` and `iex(1)` the options which [have recently appeared](https://github.com/elixir-lang/elixir/blob/master/CHANGELOG.md) in the utils.
* `--boot`
* `--boot-var`
* `--erl-config`
* `--pipe-to`
* `--rpc-eval`
* `--vm-args`
Also I added the following options which had been missing for a quite long period of time.
* `-h, --help`
* `-v, --version`
* `--logger-otp-reports`
* `--logger-sasl-reports`
* `--werl`
* `--eval` (the short variant of the option was in the man pages from the very beginning)
=> Add missing arguments to man pages

lib/iex/lib/iex/helpers.ex, lib/iex/test/iex/helpers_test.exs
VM is written in uppercase in other places.
=> Change "vm" to uppercase in IEx.Helpers

lib/elixir/lib/io.ex, lib/elixir/lib/kernel/special_forms.ex, lib/elixir/lib/list.ex, lib/elixir/lib/macro.ex, lib/elixir/lib/string.ex, lib/elixir/lib/task.ex, lib/elixir/pages/Syntax Reference.md, lib/elixir/pages/Unicode Syntax.md, lib/elixir/src/elixir_interpolation.erl, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs, lib/elixir/test/erlang/tokenizer_test.erl, lib/elixir/unicode/unicode.ex, lib/ex_unit/test/ex_unit/doc_test_test.exs, lib/iex/lib/iex/info.ex, lib/iex/test/iex/info_test.exs, lib/logger/lib/logger/formatter.ex, lib/logger/lib/logger/utils.ex, lib/mix/lib/mix/tasks/app.tree.ex, lib/mix/lib/mix/tasks/deps.tree.ex
That's the term it is used in the Unicode standard.
/cc @fertapric
=> Use "code point" instead of "codepoint"

lib/elixir/lib/integer.ex, lib/elixir/test/elixir/integer_test.exs
They are not needed, since they are covered by their /2 version.
=> Remove Integer.to_string/1 and Integer.to_charlist/1

lib/iex/lib/iex/info.ex, lib/iex/test/iex/info_test.exs
Earlier this outputted error messages when loaded module that existed
with different casing, ex.:
iex> i Datetime
Caused errors to be shown. Now this checks if there is module file
defines module with the same name as the provided atom to prevent such
cases.
Close #8780
=> Fix module inspect on case insensitive filesystems

lib/elixir/lib/regex.ex
I am an Elixir mentor on Exercism.io.
Several of my students can't find the documentation for character classes in Regex.
I have added a section copied from the erlang Regex docs to make this easier to find.
=> Added regex documentation for named character classes.

lib/mix/lib/mix/release.ex
Releases can include the Erlang Runtime System (ERTS), copying it by default from the ERTS installation of the machine. If the ERTS files were previously copied, the files are overwritten. However, some package managers install ERTS files without writing permissions, and once those files are copied they cannot be overwritten.
Because of that, a test was failing on my local machine:
```
1) test requires confirmation if release already exists unless forcing (Mix.Tasks.ReleaseTest)
/Users/fertapric/Dropbox/OSS/elixir/lib/mix/test/mix/tasks/release_test.exs:207
** (EXIT from #PID<0.4861.0>) an exception was raised:
** (File.CopyError) could not copy recursively from "/usr/local/Cellar/erlang/21.2.2/lib/erlang/erts-10.2.1" to "/Users/fertapric/Dropbox/OSS/elixir/lib/mix/tmp/Mix.Tasks.ReleaseTes …
```
=> Do not overwrite existent ERTS files in release

lib/elixir/lib/gen_server.ex
I thought it was unclear what would happen if a timeout of `0` were set
but messages were already waiting.
=> Clearer documentation for GenServer timeouts

lib/mix/lib/mix/rebar.ex, lib/mix/test/fixtures/rebar_dep/rebar.config.script, lib/mix/test/mix/rebar_test.exs
This will avoid fetching unnecessary plugins when using rebar3 dependencies.
This should not be back-ported to the `v1.8` branch.
=> Remove project_plugins from dependency rebar.config

lib/elixir/lib/task/supervisor.ex
I should've caught this one earlier 🤦‍♂️ when I submitted a fix for another typo in this same function doc.
=> Improve Task.Supervisor.async_nolink/3 doc

lib/elixir/pages/Guards.md
The current doc first describes in detail the _deprecated_ way to create a custom guard. Only after that's complete is there a small note saying that this isn't recommended, and instead to use `defguard`. This commit changes that order around to lead with the current recommended practice.
=> Guards.md: focus on the new recommended practice.

lib/elixir/lib/calendar/datetime.ex, lib/elixir/test/elixir/calendar/datetime_test.exs
Currently, if you call `DateTime.from_unix!/2` with an integer time unit, it raises a `FunctionClauseError`.
```elixir
iex(1)> DateTime.from_unix!(143_256_036_886_856, 1024)
** (FunctionClauseError) no function clause matching in DateTime.from_unix!/3
The following arguments were given to DateTime.from_unix!/3:
143256036886856
1024
Calendar.ISO
Attempted function clauses (showing 1 out of 1):
def from_unix!(integer, unit, calendar) when is_atom(unit)
(elixir) lib/calendar/datetime.ex:165: DateTime.from_unix!/3
```
However this works fine with `DateTime.from_unix/2`.
``` elixir
iex(2)> DateTime.from_unix(143_256_036_886_856, 1024)
{:ok, #DateTime<6403-03-17 07:05:22.320Z>}
```
Also, when passing a time unit of an invalid type, there are some inconsistencies.
```elixir
iex(4)> …
```
=> Allow integer time units for DateTime.from_unix!/2

lib/elixir/lib/module.ex, lib/elixir/src/elixir_module.erl, lib/elixir/src/elixir_overridable.erl
This is part of an ongoing effort to forbid overriding macros with functions and vice-versa. New checks will require the overridable information to be stored more efficiently.
=> Store overridable information more efficiently

lib/elixir/lib/gen_server.ex
Fixed a few typos in the documentation section of `terminate/2`
=> Fix documentation typos

lib/elixir/lib/keyword.ex, lib/elixir/pages/Syntax Reference.md
As I understand it, "keyword" only refers to the [atom] keys of this data structure, and a "keyword list" refers to the data structure itself. This change makes the documentation consistent.
Arguably changing the module name to `KeywordList` would make sense too, since `Keyword.new` [perhaps unintuitively] creates a keyword list. But I definitely wouldn't argue for a breaking change! 😄 
Feel free to close if my understanding is wrong, and we should be using "keyword" and "keyword list" interchangeably!
=> Update docs to consistently use "keyword list"

lib/elixir/lib/kernel/special_forms.ex
Hi all,
a few more doc improvement suggestions for `Kernel.SpecialForms`.
Cheers!
=> Fix typos in Kernel.SpecialForms

lib/elixir/lib/gen_server.ex
Howdy!
I mentor a lot of folks in Elixir day to day and find myself using this doc with a lot of introductions to GenServers. I recently noticed it stopped working when I would paste directly into the REPL. It looks like these were added in commit b230541fae but before then the only note was commented. In the interest of copy-pasteability for the documentation (especially in IEx) I figured this would be an improvement.
=> Fix uncommented `...` in periodic task GenServer documentation

lib/elixir/lib/kernel.ex, lib/elixir/src/elixir_overridable.erl, lib/elixir/test/elixir/kernel/overridable_test.exs
Overriding a macro as a function (and vice-versa) might produce undesired effects.
For example, it's not clear if the following code should or should not raise:
```elixir
def foo, do: bar()
defmacro bar, do: :ok
defoverridable bar: 0
def bar, do: :ok
end
```
On top of that, `super` does not currently work for such cases.
=> Do not allow to override macros as functions (and vice-versa)

lib/elixir/lib/calendar/datetime.ex, lib/elixir/lib/calendar/iso.ex, lib/elixir/test/elixir/calendar/datetime_test.exs
Before:
DateTime.from_unix!(143_256_036_886_856, 1024).microsecond
{320312, 3}
After:
DateTime.from_unix!(143_256_036_886_856, 1024).microsecond
{320312, 6}
---
Alternatively, should we truncate it to `{320, 3}`?
=> Set DateTime.from_unix precision to microseconds for units not divisible by 10

lib/mix/lib/mix/tasks/test.ex, lib/mix/test/fixtures/umbrella_cover/apps/bar/lib/bar.ex, lib/mix/test/fixtures/umbrella_cover/apps/bar/test/bar_tests.exs, lib/mix/test/mix/cli_test.exs, lib/mix/test/mix/tasks/test_test.exs
The main issue is that Cover no longer considers protocols to
be cover compiled at the end of suite, which was causing protocols
to be taken into account when considering Total but they were not
listed individually. 
By only considering cover compiled modules when computing the results,
it automatically removes protocols and it should also apply for future cases.
The umbrella --cover test was improved to be more assertive and also
list protocols.
Closes #8825
=> Do not consider modules that are no longer cover compiled

lib/elixir/lib/calendar/datetime.ex, lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel_test.exs
Closes #8821
---
~The build failure is addressed in https://github.com/elixir-lang/elixir/pull/8823~
=> Add ~U sigil for UTC date times

lib/elixir/lib/code/formatter.ex, lib/elixir/test/elixir/code_formatter/calls_test.exs
We're not including StreamData (https://github.com/whatyouhide/stream_data) in the standard library anymore. It doesn't make sense that we have StreamData functions in the default locals without parens of the formatter. Instead, we solve the problem on the StreamData side with  https://github.com/whatyouhide/stream_data/pull/124.
=> Remove StreamData-related stuff from the formatter configuration

lib/elixir/lib/macro.ex
I added a bodiless clause so that arguments are clearly named in the documentation. I also added a `is_atom/1` guard to the first function clause so that we consistently check that the context is an atom.
=> Slightly improve Macro.generate_arguments/2

lib/elixir/lib/access.ex, lib/elixir/test/elixir/access_test.exs
Enabling negative index as Enum.at/2 to keep it consistent, as Enum.at/2 returns nil if the index is out of bounds counting from the end.
=> Enable Access.at/1 to handle negative index

lib/elixir/lib/system.ex, lib/elixir/test/elixir/system_test.exs
This PR adds the `System.fetch_env/1` and `System.fetch_env!/1` functions as per the discussion in https://groups.google.com/forum/#!topic/elixir-lang-core/QGxEibK4y7Q.
I chose to keep using the same underlying implementation for `fetch_env/1` as the one for `get_env/1` because the number of lines would have been the same but we would have added one function call.
=> Add System.fetch_env/1 and System.fetch_env!/1

lib/elixir/lib/kernel.ex
In a number of places in the docs (`!/`, `&&/2`, `Enum.all?`) the
concept of a truthy/falsy value is mentioned and briefly explained.
I propose to have single place for that explanation and point to it
from those other places.
I'm not sure if this is the right location though :-)
=> Add docs for truthy/falsy values

lib/elixir/lib/system.ex
* Replaces the recently introduced "defined/undefined" term with the already existing term "set/unset"
* Fixes an Exception type and the message in the System.fetch_env!/1
=> Replace "(un)defined" with "(un)set" in System env related functions

lib/elixir/lib/registry.ex, lib/elixir/test/elixir/registry_test.exs
Currently when omitting a `:name` when starting `Registry` it will be named `nil`. 
Small example:
```elixir
Interactive Elixir (1.9.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> {:ok, _pid} = Registry.start_link(keys: :unique)
{:ok, #PID<0.102.0>}
iex(2)> {:ok, _pid} = Registry.register(nil, :foo, :bar)
{:ok, #PID<0.103.0>}
iex(3)> [{_pid, val}] = Registry.lookup(nil, :foo)
[{#PID<0.100.0>, :bar}]
```
This seems to be because this line defaults `name` to `nil`:
https://github.com/elixir-lang/elixir/blob/3680e8535548cd5f928af52d92ba104eccbd6e50/lib/elixir/lib/registry.ex#L319 
I added `Keyword.has_key?(options, :name)` to the check below the mentioned line to ensure that a name actually was given.
https://github.com/elixir-lang/elixir/blob/3680e8535548cd5f928af52d92ba104e …
=> Ensure :name is given in Registry.start_link/1

lib/elixir/lib/uri.ex, lib/mix/lib/mix/tasks/escript.build.ex
Avoid splitting words that contain a hyphen into two lines,
since a space is added when docs are rendered in IEx and ExDoc.
Command used to detect this bug:
$ ag -- "\w-\n"
=> Avoid hyphen at EOL

lib/elixir/lib/kernel.ex
I personally found the current docs for [function_exported/3](https://hexdocs.pm/elixir/Kernel.html#function_exported?/3) a bit odd. 
```elixir
iex> function_exported?(Enum, :member?, 2)
true
```
Initially I thought the example given with the second parameter was an option. I read it as if the following. "Is there a function in Enum with 2 arity?". I later realised that it was referring to `Enum.member?/2` thanks to @Gazler so I added some more examples that I believe are more memorable functions that aren't close to common option names.
=> More examples for Kernel.function_exported?/3

lib/elixir/src/elixir_map.erl
The `Module` variable in these cases is guaranteed to be a module alias.
Follow up of https://github.com/elixir-lang/elixir/pull/8864#discussion_r263304032
=> Use :elixir_aliases.inspect/1 with module aliases

lib/elixir/lib/macro.ex
Three-element tuples with an atom at the end raise an `ArgumentError` instead of using inspect (fallback):
```elixir
iex(1)> Macro.to_string({1, 2, :hello})
:erlang.atom_to_binary(1, :utf8)
(elixir) lib/macro.ex:621: Macro.to_string/2
iex(1)> Macro.to_string({1, 2, :hello, 1})
"{1, 2, :hello, 1}"
```
=> Add guard to Macro.to_string/2

lib/elixir/src/elixir_map.erl
`__struct__/0,1` is not meant to return an AST. Using `Macro.to_string/1` might lead to incorrect error messages:
```elixir
defmodule MyStruct do
def __struct__, do: {:ok, :one, :two}
def __struct__(_), do: {:ok, :one, :two}
end
iex> %MyStruct{}
** (CompileError) iex:2: expected MyStruct.__struct__/1 to return a map with a :__struct__ key that holds the name of the struct (atom), got: ok
```
Follow up of https://github.com/elixir-lang/elixir/pull/8864#discussion_r263334936 (I thought I was going to find more occurrences 😅)
=> Use inspect/1 with values returned by __struct__/*

lib/elixir/lib/kernel.ex
I got caught off-guard by the existing documentation, so I just wanted to submit a quick fix for it. Would be happy to switch to ```Returns the smallest integer greater than or equal to `number`.``` if that sounds better!
=> Fix small typo for ceil behavior docs

lib/elixir/lib/inspect.ex, lib/elixir/test/elixir/inspect_test.exs
This is an attempt to fix #8860
=> Ensure inspect returns valid ~r// expressions

lib/eex/test/eex_test.exs, lib/elixir/lib/enum.ex, lib/elixir/lib/gen_server.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/kernel/special_forms.ex, lib/elixir/lib/map.ex, lib/elixir/lib/map_set.ex, lib/elixir/lib/option_parser.ex, lib/elixir/lib/stream.ex, lib/elixir/lib/task.ex, lib/elixir/lib/task/supervisor.ex, lib/elixir/pages/Syntax Reference.md, lib/elixir/test/elixir/enum_test.exs, lib/elixir/test/elixir/gen_server_test.exs, lib/elixir/test/elixir/stream_test.exs, lib/iex/test/iex/helpers_test.exs
Related to f451f9f63d6854eef0e828be08dd69786b6fd86d
=> Replace use of "item(s)" with "element(s)" in Enum module

lib/elixir/lib/kernel/typespec.ex, lib/elixir/test/elixir/kernel/warning_test.exs
#8891 showed that underscored variables in type specifications are treated differently: the `singleton_typevar` error was not raised with underscored variables. 
The meaning of underscored variables in type specifications seems to be the same as regular underscored variables: values that are not meant to be used. The `singleton_typevar` could be seen as the type equivalent of the "unused variable" warning. Because of that, I think a warning should be emitted if an underscored type variables is used more than once.
=> Warn if underscored type variable is used more than once

lib/elixir/lib/system.ex, lib/elixir/test/elixir/system_test.exs
Similarly to Erlang `os:getenv/2` this allow to return a default value in `System.get_env` when the environment variable is undefined.
=> Add support for a default value in System.get_env/1

lib/mix/lib/mix/compilers/erlang.ex, lib/mix/test/mix/tasks/compile.yecc_test.exs
The `Mix.Task.Compiler.Diagnostic` spec allows position to be `nil`, but the yecc compiler was sometimes setting it to `:none` which violates the spec.
=> Ensure Erlang-based Mix compilers (erlang, leex, yecc) set valid position on diagnostics

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel_test.exs
I felt that the option to use `update_in/2`/`put_in/2` & `get_and_update_in/2` with structs wasn't really prominent in the docs while I believe it's very important and a great feature.
Tried to highlight it a bit more in all of these that it also works.
Happy for feedback about wording, example change or what not.
I wanted to add doc tests but my doctests always ended up telling me `Foooo.__struct__/1 is undefined, cannot expand struct Foooo` (double checked module/struct definition and usage of course)
so I felt just adding them to the tests was best.
Thanks for all your work :clap:
=> Struct updating docs

lib/elixir/src/elixir_bitstring.erl, lib/elixir/test/elixir/kernel/expansion_test.exs
During the bitstring expansion, guard checks were avoided due to a special case for inlining binaries during interpolation. These changes ensure guards are checked.
Related to #8867
=> Ensure guard checks when expanding string interpolations

lib/elixir/lib/kernel.ex
It uses the &expand/1 function, instead of relying on Macro.expand/2
=> Simplify Kernel.in/2

lib/elixir/lib/list.ex, lib/elixir/test/elixir/list_test.exs
* Make List.to_string/1 error msg non-ambiguous and corrects it mentioning empty lists are valid
* Add elements allowed in List.to_string/1 to @doc
* add tests for empty lists
=> List.to_string/1 improve error message and docs

lib/elixir/lib/code/typespec.ex
Based on [Elixir AST doc](https://github.com/elixir-lang/elixir/blob/3f661b0166f31ef5d1fe8d45d4bc114984c3b434/lib/elixir/pages/Syntax%20Reference.md#the-elixir-ast), the second element of Elixir variable AST tuple should be a keyword list as meta data. For example, `quote do: x` would be evaluated to `{:x, [], Elixir}`.
When `Code.Typespec.typespec_to_quoted` converts specs or types from erlang abstract format to Elixir quoted ast, it should convert `line` (integer) to `[line: line]` (keyword list) for variable.
Related historical commit: https://github.com/elixir-lang/elixir/commit/89cbe93bba82fb0262e9ee66bc7c8fdd07751bdc#diff-6de4b356bc9d4e3d07f1e5731fbe7d23L453 (might just missed this one)
=> Fix Code.Typespec.typespec_to_quoted conversion for variable

lib/elixir/lib/version.ex
The `Version.Requirement` struct is mentioned in several places of the `Version` documentation, used as an argument of `Version.compile_requirement/1` and `Version.match?/3`, and returned as a result of `Version.parse_requirement/1` and `Version.parse_requirement!/1`.
In addition, ExDoc is currently linking to modules even if they are marked with `@moduledoc false` (that issue is being tracked in https://github.com/elixir-lang/ex_doc/issues/951), and produces "PAGE NOT FOUND" when clicking on the [`Version.Requirement` links.](https://hexdocs.pm/elixir/Version.html#parse_requirement/1)
=> Make Version.Requirement public

lib/elixir/lib/kernel.ex, lib/elixir/src/elixir_map.erl, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/map_test.exs
This change fixes inconsistencies when building structs: if the struct was built using the map syntax the `:__struct__` key was overridden by the given module name; however, if the struct was built using `struct/1,2` the `:__struct__` key was kept.
For example:
```elixir
defmodule X do
defstruct [:x]
end
defmodule Y do
defdelegate __struct__, to: X
defdelegate __struct__(args), to: X
end
iex> %Y{}
%Y{x: nil}
iex> struct(Y)
%X{x: nil}
```
Closes #8800
=> Ensure the struct name matches the given module

lib/elixir/lib/keyword.ex
The description from `Keyword.pop/3` mentioned that it will return
**all** the values associated with `key` in the keyword list, but this
wasn't happening, at least when you have duplicate keys in the keyword
list `Keyword.pop/3` was returning just the first match, even one of
examples showed that behavior.
This is my attempt to fix that situation based on my understanding from
the initial description from `Keyword.pop/3`:
> Returns and removes all values associated with key in the keyword list.
>
> All duplicated keys are removed. See pop_first/3 for removing only the first
entry.
=> `Keyword.pop/3` must return all values associated with key

lib/mix/lib/mix/tasks/new.ex, lib/mix/lib/mix/tasks/profile.cprof.ex, lib/mix/lib/mix/tasks/profile.eprof.ex, lib/mix/lib/mix/tasks/profile.fprof.ex, lib/mix/lib/mix/tasks/run.ex, lib/mix/test/mix/tasks/run_test.exs
The fact we explicitly told developers to configure their
application in the config file and access it with
`Application.get_env/2`, probably led many to rely on
the application environment when better options are
available.
Furthermore, `mix new` is mostly used for libraries,
where config is even less important, as configuration
from libraries is not transitive.
Developers that need the config, can simply add it back
by calling:
echo "use Mix.Config" > config/config.exs
This commit removes config for new apps and deprecate
the `--config` flag, which cannot perform deep merges.
Note we do keep the config for umbrellas, as umbrellas
are about applications and not libraries (plus we need
the umbrella children to share and point to an existing
config).
Closes #8815.
Closes #8811.
=> No longer generate config for mix new

lib/mix/lib/mix/cli.ex, lib/mix/lib/mix/utils.ex, lib/mix/test/mix/utils_test.exs, lib/mix/test/test_helper.exs
Implementation of #8818 
The documentation is not as good as I'd expect. Since I'm not a native speaker some help would be appreciated.
=> mix: follow XDG base dir specification

lib/elixir/lib/protocol.ex
- Sample was not a defined Protocol in this example
- run this example in an iex session would cause `ArgumentError`
** (ArgumentError) Sample is not available
This PR also made some small changes to make the example more consistent and intuitive IMO.
A question: do we need to turn this example into a doctest? If so, I can also do that.
=> Fix doc example for Protocol.derive/3

lib/elixir/lib/enum.ex
There was nothing in the Enum.slice/3 documentation indicating that start_index can be a negative number, so I updated the documentation to mention that fact, using similar language to the Enum.at/2 documentation. I also added an iex example to the docs as well.
=> Added documentation to slice/3 indicating that start_index can be negative

lib/ex_unit/lib/ex_unit/assertions.ex
The documentation for `assert/2` suggests that it behaves differently than `assert/1`, which is not the case.
=> Fix the documentation for ExUnit.Assertions.assert/2

lib/elixir/lib/code.ex, lib/elixir/src/elixir.hrl, lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/code_test.exs
This PR introduces the `static_atom_encoder` option to `Code.string_to_quoted/2`, as described in [this elixir-lang-core thread](https://groups.google.com/forum/#!topic/elixir-lang-core/1A0kOswSB7U).
I think it is ready for review; code, docs and 2 added tests.
=> Implement static_atom_encoder option

lib/mix/lib/mix/tasks/compile.elixir.ex
The documentation listed three options that `elixirc_options` supported, but the
code supports all the available options. I replaced the three options listed in
the docs with a sentence saying all the command line options are supported by
`elixirc_options`.
=> Clarify that `elixirc_options` in supports all the command line options

lib/elixir/lib/gen_server.ex
As we can see [here](http://erlang.org/doc/man/gen_server.html#Module:code_change-3),
the function returns `{:ok, new_state} | {:error, reason}` while the
old version can either be old version or `{:down, current version}`
=> Fix @spec for `GenServer.code_change/3`

lib/elixir/src/elixir_expand.erl, lib/elixir/test/elixir/kernel/overridable_test.exs
Closes #8610 
The previous implementation was generating an unnecessary intermediate function when using `&super/arity`.
In addition, capture expressions using `super` with sequential value placeholders (`&n`) were not optimized like other functions. For example, the capture expression `&foo(&1, &2, &3)` is optimized to `&foo/3` because the value placeholders (`&n`) are sequential `&1, &2, &3`.
=> Optimize &super/arity and &super(&1)

lib/elixir/lib/kernel/special_forms.ex
The documentation of `Kernel.SpecialForms.&/1` is updated with a reference to `Function.capture/3`.
Fixes #8961.
=> Updates documentation of capture operator with reference to Function.capture/3

lib/elixir/lib/registry.ex, lib/elixir/test/elixir/registry_test.exs
I've implemented a bare minimum of the feature discussed in the [mailing list](https://groups.google.com/forum/m/#!topic/elixir-lang-core/FyRAyqJZIPs). I didn't focus too much on the tests or documentation since it's still being discussed.
As for a `match` version, I'm unsure of how to handle the match specs. The format of the data that you'd want to match on is, in the table, `{key, {pid, value}}` which we might not want to leak to the outside. In the case of `count_match` it's simpler, it only allows matching on the value and the provided match spec is wrapped to match the table.
Because of the uncertainty around the shape of the match specs I skipped remapping the data from `{key, {pid, value}}`, but a "flat" tuple like `{key, pid, value}` is probably preferable.
I'd like to try out a …
=> Add Registry.to_list/1

lib/logger/lib/logger/config.ex
=> Use :persistent_term for Logger config

lib/mix/lib/mix/tasks/release.ex, lib/mix/lib/mix/tasks/release.init.ex, lib/mix/test/mix/tasks/release.init_test.exs, lib/mix/test/mix/tasks/release_test.exs
Today, the place for setting environment variables in a release
is inside bin/start. The issue with this approach is that, if you
set something like RELEASE_NODE or RELEASE_COOKIE inside
bin/start, and then you run a command such as  `bin/release remote`,
we won't be able to connect to the running node.
This is addressed by introducing `release/RELEASE_VSN/env`
that will be invoked early in the release process. The goal of
this script is to set up environment variables.
This has the advantage of those variables being set per version,
instead of being shared across all releases, which gives us more
independence between versions.
By doing this change, we effectively remove the need for bin/start.
It is important to note that hot code swapping requires bin/start,
but those performing hot …
=> Replace bin/start by release/RELEASE_VSN/env

lib/elixir/lib/keyword.ex
I added a few guards to some functions in the `Keyword` module. Most functions have the `is_atom/1` guard for key-based operations, so I added that to a few functions that didn't have it. The `split`/`take`/`drop` functions were missing a `is_list/1` guard for the second argument so I added that as well. We had guards in most of the functions in this module so I think it makes sense to add them to the missing functions.
=> Add missing guards to functions in Keyword

lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/erlang/tokenizer_test.erl
`handle_dot` already gets the column of `(` from `strip_dot_space`.
=> Fix columns in tokenize of dot_call_op

lib/mix/lib/mix/tasks/release.init.ex
This guarantees that custom hostnames and similar
propagate properly.
Thanks @tsloughter for the tip.
=> Use $RELEASE_NODE as the base for --remsh/--rpc

lib/elixir/lib/map.ex, lib/elixir/test/elixir/map_test.exs
`Keyword.{take|drop|split}` don't offer support for an `Enumerable` of keys to take/drop/split based on. However, the `Map` counterparts do. With this PR, we hard-deprecate support for `Enumerable`s of keys in `Map.{take|drop|split}`. Only lists of keys are allowed.
=> Deprecate Enumerable keys in Map.{take|drop|split}

lib/elixir/lib/config/provider.ex
* Fixes an issue with the code example for `Config.Provider`.
* Fixes typos and improves the phrasing of the documentation text.
=> Improve documentation and example for Config.Provider

CHANGELOG.md
Read the recent blog post on the new stuff in 1.9 and noticed `Registry.select/2` was missing. If this was on purpose please just close the PR 🙂
=> Add Registry.select/2 to changelog

lib/mix/lib/mix/tasks/release.ex
Noticed some typos in the new release documentation, plus a link that wasn't formatted as one.
Really good documentation! I especially liked the part about "Why releases", since it's such a common question.
=> Fix some typos in Mix.Tasks.Release

lib/mix/lib/mix/tasks/release.ex
I'm a bit torn with this one. One one hand, I don't want to set the precedent of `style` changes. On the other, the first thing I thought when reading the docs [here](https://hexdocs.pm/mix/master/Mix.Tasks.Release.html) was that there was some type of emphasis missing.
I think the `LD_LIBRARY_PATH ` change was indeed a typo (since there are other instances of it using ``) but I'm torn about the other changes I made.
Anyways, here are some changes, if you'd like, please use them! It not, no hard feelings. ❤️ 💜 
(If you'd like any changes, please let me know and I'll make them)
=> Update docs to make them easier to read in html format.

lib/elixir/lib/code/formatter.ex
Closes https://github.com/elixir-lang/elixir/issues/9006
I'm not sure if this needs any additional test coverage. I couldn't find anything specific for the current list of Kernel macros.
=> Add defmodule/2 to default locals_without_parens list

lib/elixir/lib/code.ex, lib/elixir/lib/gen_event.ex, lib/elixir/lib/io.ex, lib/elixir/lib/kernel/error_handler.ex, lib/elixir/lib/kernel/parallel_compiler.ex, lib/elixir/lib/kernel/utils.ex, lib/elixir/src/elixir_aliases.erl, lib/elixir/src/elixir_bitstring.erl, lib/elixir/src/elixir_clauses.erl, lib/elixir/src/elixir_compiler.erl, lib/elixir/src/elixir_def.erl, lib/elixir/src/elixir_dispatch.erl, lib/elixir/src/elixir_env.erl, lib/elixir/src/elixir_errors.erl, lib/elixir/src/elixir_expand.erl, lib/elixir/src/elixir_fn.erl, lib/elixir/src/elixir_import.erl, lib/elixir/src/elixir_map.erl, lib/elixir/src/elixir_overridable.erl, lib/elixir/test/elixir/kernel/parallel_compiler_test.exs, lib/mix/lib/mix/compilers/elixir.ex, lib/mix/test/mix/tasks/compile.elixir_test.exs
This makes it so we also include the `function/arity` in the
warnings stacktraces and makes the compiler more deterministic.
=> Unify error handling and compiler deadlock checking

lib/elixir/lib/path.ex
Found this out while debugging, thought it would be nice to mention this in the docs.
=> Add example for Path.dirname/1

lib/elixir/lib/inspect/algebra.ex, lib/elixir/test/elixir/inspect_test.exs
Another stab at making inspecting more configurable. It differs from #8979 in that, instead of introducing global state, we add it as just another option which needs to be passed explicitly. Thus, the users will likely define their own `MyApp.inspect_opts()` and/or `MyApp.io_inspect()` wrappers to avoid repetition.
Let's see some use cases. First we configure IEx to use our custom function:
```elixir
iex> IEx.configure(inspect: [inspect_fun: &Pretty.inspect/2])
:ok
```
1. Pretty-printing integers (#4916)
```elixir
iex> :math.pow(2, 32) |> trunc()
4_294_967_296
```
2. Inspect tuples as records (#8534)
```elixir
iex> {:foo, :bar}
{:foo, :bar}
iex> {:person, "Alice", 30}
#person(name: "Alice", age: 30)
```
3. Overwrite struct's Inspect implementation
```elixir
iex> …
```
=> Add inspect_fun to Inspect.Opts

lib/mix/lib/mix/project.ex
I came across this incorrect word in the documentation.  It slowed me down enough that I thought it worth fixing.
I am happy to have this combined or rewritten with other small documentation fixes if this sort of pull request is discouraged.
=> Update documentation for less confusing read

lib/elixir/lib/kernel/special_forms.ex, lib/elixir/pages/Writing Documentation.md, lib/mix/lib/mix/tasks/release.ex, lib/mix/test/mix/cli_test.exs, lib/mix/test/mix/tasks/escript_test.exs, lib/mix/test/mix/tasks/run_test.exs
There were instances of `IO.puts/1` calls without parens throughout the whole codebase (in docs, code, tests). I removed most of them where it made sense to do so, so that users will find documentation and other things consistent with how the formatter behaves.
=> Use parens in IO.puts/1 calls around the codebase

lib/logger/lib/logger/translator.ex, lib/logger/test/logger/translator_test.exs
Background on this is that a user of the `sentry` library was seeing a difference in behaviour of reported process crashes when running an application as a Distillery release vs. `iex -S mix` (https://github.com/getsentry/sentry-elixir/issues/337)
Sentry implements a Logger backend, but wasn't receiving events with `:crash_reason` metadata for the process crash running a Distillery release.  After some digging and reaching some of the limits of my current understanding, it appears that Erlang prints a different message format with erts, as seen here?
https://github.com/erlang/otp/blob/master/erts/emulator/beam/beam_emu.c#L1591-L1594
```c
int alive = erts_is_alive;
erts_dsprintf_buf_t *dsbufp = erts_create_logger_dsbuf();
erts_dsprintf(dsbufp, "Error in process ~p ");
if (alive) …
```
=> Translate process crash on node

lib/ex_unit/lib/ex_unit/assertions.ex, lib/ex_unit/lib/ex_unit/doc_test.ex, lib/ex_unit/lib/ex_unit/formatter.ex, lib/ex_unit/test/ex_unit/doc_test_test.exs
Modify docs test to show the actual doctest code according to #8889. 
I am not sure this is the way best way to do it, maybe it is a bit overkill to pass the the formatted doctest code around like this. An other solution would simply be to append iex> to the lines in expr. Let me know what you think?
=> Display the actual doctest code when doctset fails

lib/mix/lib/mix/local/installer.ex
Added logic to search for `archive-name-*` if `archive-name` is not found when running `mix archive.uninstall archive-name`.
For example, `mix archive.uninstall ironman` will find `ironman-0.4.2` archive.
Still checks for exact match first, so only modifies cases where legacy would report "no archives found".
=> Improved archive.uninstall to find any version of specified file

lib/elixir/lib/kernel/cli.ex, lib/elixir/test/elixir/kernel/cli_test.exs, lib/mix/lib/mix/tasks/release.ex, lib/mix/lib/mix/tasks/release.init.ex, lib/mix/test/mix/tasks/release_test.exs
We default to --sname which provides safer security defaults.
/cc @tsloughter @wojtekmach
=> Allow developers to choose between sname and name in releases

lib/elixir/src/elixir_module.erl, lib/elixir/test/elixir/kernel_test.exs
Follow up on #9030
```elixir
defmodule true do end
** (CompileError) iex:1: invalid module name: true
(stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
(iex) lib/iex/evaluator.ex:257: IEx.Evaluator.handle_eval/5
(iex) lib/iex/evaluator.ex:237: IEx.Evaluator.do_eval/3
(iex) lib/iex/evaluator.ex:215: IEx.Evaluator.eval/3
(iex) lib/iex/evaluator.ex:103: IEx.Evaluator.loop/1
(iex) lib/iex/evaluator.ex:27: IEx.Evaluator.init/4
```
=> Do not allow defmodule with special atoms

lib/elixir/lib/kernel.ex, lib/elixir/lib/module.ex, lib/elixir/test/elixir/module_test.exs
This PR permits to provide a default value as the third argument to `Module.get_attribute`.
=> Support default value when reading inexistent module attribute

lib/mix/lib/mix/release.ex
If `include_erts` is a path instead of a boolean, the erts lib dir should be based from this location instead of `:code.lib_dir()`. This is useful when trying to include cross compiled lib apps.
=> Base erts lib dir off erts source path

lib/mix/lib/mix/release.ex
systools requires the paths to be declared inorder to find apps that are coming from a different location than the release. This fixes issues when trying to inclide erts and erlang libs that are not part of the host system.
=> Include erts lib dir and paths for release script

lib/mix/lib/mix/release.ex
When calling load app, we should attempt to load it from the otp_root before consulting `:code.lib_dir`. This fixes issues when specifying `include_erts` as a path to a cross compiled version of erlang.
=> Try loading app from otp_root before :code.lib_dir

lib/mix/lib/mix/tasks/release.ex, lib/mix/lib/mix/tasks/release.init.ex, lib/mix/test/fixtures/release_test/lib/release_test.ex, lib/mix/test/mix/tasks/release_test.exs
This speeds up boot time and decreases memory use.
=> Start the VM in interactive mode for rpc/eval/remote

lib/eex/lib/eex/tokenizer.ex
Spec for t:token/0 was missing on element in the tuple
this created a series of Dialyzer errors when running `make dialyze`
`/elixir/lib/eex/lib/eex/compiler.ex:44: The pattern <[{'expr', _line@1, _mark@1, _chars@1, _} | _rest@1], _buffer@1, _scope@1, _state@1> can never match the type <[{'text',binary() | maybe_improper_list(any(),binary() | [])} | {'end_expr',non_neg_integer(),[any()],binary() | maybe_improper_list(any(),binary() | [])} | {'expr',non_neg_integer(),[any()],binary() | maybe_improper_list(any(),binary() | [])} | {'middle_expr',non_neg_integer(),[any()],binary() | maybe_improper_list(any(),binary() | [])} | {'start_expr',non_neg_integer(),[any()],binary() | maybe_improper_list(any(),binary() | [])}],_,[],#{'engine':=_, 'file':=_, 'line':=non_neg_integer(), 'quoted':=[], …
=> Fix specs in EEx.Tokenizer

lib/elixir/lib/regex.ex, lib/elixir/src/elixir.app.src, lib/elixir/src/elixir.erl, lib/elixir/test/elixir/regex_test.exs, lib/mix/lib/mix/tasks/escript.build.ex
Related to discussion: https://groups.google.com/forum/#!topic/elixir-lang-core/CgFdxIONvGg
Regexes are precompiled to binary values during code compilation.
These binary values may be incompatible between different PCRE versions
and OS endianness. This makes code less portable to achieve slight
performance improvement.
PCRE version and endianness are parts of Regex structure and may be
checked in runtime.
This PR adds this check and makes regex execution fall back to binary
matching if versions are incompatible.
This slightly reduces performance (around 5% for simple regexes) for
compatible versions because there is an additional version read.
Also for incompatible versions it's as fast as binary matching.
I'm not sure if there should be additional options to not check for version, …
=> Make regexes fall back to binary matching on incompatible runtime version

lib/mix/lib/mix/tasks/format.ex, lib/mix/test/mix/tasks/format_test.exs
Running `echo 'defmodule <%= module %>.Bar do end' | mix format -` produces the following results:
```
** (FunctionClauseError) no function clause matching in IO.chardata_to_string/1
The following arguments were given to IO.chardata_to_string/1:
:stdin
Attempted function clauses (showing 2 out of 2):
def chardata_to_string(string) when is_binary(string)
def chardata_to_string(list) when is_list(list)
(elixir) lib/io.ex:461: IO.chardata_to_string/1
(elixir) lib/path.ex:312: Path.relative_to/2
(mix) lib/mix/tasks/format.ex:450: Mix.Tasks.Format.check!/1
(mix) lib/mix/task.ex:316: Mix.Task.run_task/3
(mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2
```
It is hiding actual errors. The following error should be output.
```
** (SyntaxError) stdin:1: syntax error before: '='
stacktrace:
(elixir) …
```
=> Fix hiding mix format errors with stdin

lib/elixir/lib/io/ansi/docs.ex, lib/elixir/lib/uri.ex, lib/ex_unit/lib/ex_unit/doc_test.ex, lib/logger/lib/logger/formatter.ex, lib/mix/lib/mix/release.ex, lib/mix/lib/mix/tasks/new.ex
Related #9040 
Regexes used to be precompiled to binary values during code compilation. These binary values may be incompatible with different operating systems and OTP releases. That's why an explicit `Regex.recompile/1` or `Regex.recompile!/1` was required.
Regexes now fallback to binary matching if the precompiled binary is not compatible with the runtime version.
=> Do not explicitly recompile regexes, fallback to binary matching

lib/elixir/lib/application.ex
We were getting the "Type specification ... is a supertype of the success typing" error
/elixir/lib/elixir/lib/application.ex:367: Type specification 'Elixir.Application':spec(app()) -> [{key(),value()}] | 'nil' is a supertype of the success typing: 'Elixir.Application':spec(atom()) -> 'nil' | [{'applications' | 'description' | 'env' | 'id' | 'included_applications' | 'maxP' | 'maxT' | 'mod' | 'modules' | 'registered' | 'start_phases' | 'vsn',_}]
/elixir/lib/elixir/lib/application.ex:382: Type specification 'Elixir.Application':spec(app(),key()) -> value() | 'nil' is a supertype of the success typing: 'Elixir.Application':spec(atom(),'applications' | 'description' | 'id' | 'included_applications' | 'maxP' | 'maxT' | 'mod' | 'modules' | 'registered' | 'start_phases' | 'vsn') -> any()
=> Remove Dialyzer errors in Application module

lib/elixir/lib/dynamic_supervisor.ex
Fixes #9075, by changing the in module documentation about 'module-based supervisors' `The @doc ...` to `A @doc ...`.
=> Improves module documentation of DynamicSupervisor

lib/elixir/lib/gen_server.ex
Fixes #9081 by improving documentation of GenServer.server() type, as well as mentioning its possible values in the documentation of `GenServer.cast`.
=> Fixes #9081 by improving documentation of GenServer.server() type.

lib/elixir/lib/gen_server.ex
`{:via, module, term}` is covered by the type `name`
Related: https://github.com/elixir-lang/elixir/pull/9082
=> Remove duplicated typespec on t:GenServer.server/0

lib/elixir/src/elixir_expand.erl
Fixed a small grammatical mistake in this error message.
Before:
> the function "case" cannot handle clauses with the -> operator because it is not macro. Please make sure you are invoking the proper name and that it is a macro
After:
> the function "case" cannot handle clauses with the -> operator because it is not **a** macro. Please make sure you are invoking the proper name and that it is a macro
=> Add 'a' to {invalid_clauses, Name} error

lib/elixir/lib/inspect/algebra.ex, lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/inspect_test.exs
It’s easier to explain with code.
When `Inspect.inspect/2` is used with the nested structure, it sometimes makes sense to pass some custom additional options through the call stack. That might be a custom setting, meaningful for the inspected type only. For example, the level of nesting in the snippet in the test below.
I would propose the ability to pass any option to `Inspect.inspect/2` so that if it’s not a known default option, it’s being put in the newly introduced `custom_bag` struct field. It might play the role of the “accumulator,” so that all the nested objects of the same type (all objects aware of this particular option) might get it, and update in the nesting calls to `inspect/2`.
The test below should shed more light on how it might be used.
=> Inspect.Opts.custom_options

lib/elixir/lib/string.ex, lib/elixir/test/elixir/string_test.exs
We also deprecate the :insert_replaced option since the
anonymous functions is strictly superior.
Closes #9023.
=> Support unary functions in String.replace/4

lib/elixir/src/elixir_erl.erl, lib/elixir/src/elixir_module.erl, lib/mix/test/mix/tasks/compile.protocols_test.exs
Prior to this patch, we would always compute the relative
path to the current working directory (CWD), but this meant
consolidated protocols would always get a full path since
they are always outside of their current working directory.
We address this by also storing the relative path in the
definition.
Closes #9095
=> Store relative file in module definition

README.md, lib/elixir/pages/Library Guidelines.md
https://spdx.org/licenses/Apache-2.0.html
- Full name: Apache License 2.0
- Short identifier: Apache-2.0
=> Use SPDX full name of Apache License 2.0

lib/mix/lib/mix/tasks/release.ex
I think most projects will end up with some kind of `MyApp.ReleaseTasks` module so I think we could mention it in the docs.
=> Mention custom scripts in mix release "One-off commands" docs

lib/elixir/test/elixir/stream_test.exs
The test `"timer/1"` has been failing intermittently in the CI builds https://cirrus-ci.com/task/4511441067966464. I thought using `:timer.tc/1` to measure time differences would be better than `:timer.now_diff/2`
=> Use :timer.tc/1 to measure time diff in tests

lib/elixir/lib/enum.ex
I found the order of the examples a bit confusing, because on other examples it starts with the 'success' examples first. The default 0 example in the middle had me looking a few times before I understood what the result should be.
=> Update Enum.find/2 documentation

lib/mix/lib/mix/cli.ex, lib/mix/lib/mix/project.ex, lib/mix/test/mix/cli_test.exs
This PR addresses a common issue with running mix tasks, primarily `mix test` when `MIX_TARGET` is set to a value other than `:host`. This is why the behavior mimics that of `preferred_cli_env` with the exception that this will not be able to be overridden by setting `MIX_TARGET`. I feel that this behavior is okay because `mix` is a tool that is _always_ running on your `:host`. Therefore, you should be able to specify, in the task module or project config which target the tasks should run under, no matter what the target. If this behavior needs to be overridden, it could be done by setting `preferred_cli_target` in the `Mix.Project.config`.
The common pain is that `MIX_TARGET` is typically something that you `export` which then makes running `mix test` painful because it attempts to load …
=> Add preferred_cli_target

lib/mix/lib/mix/tasks/deps.compile.ex
@ferd breaks down the issue here https://github.com/erlang/rebar3/issues/2102#issuecomment-500081989
But basically we need to use `--paths=` to get around an issue with how we use subscommands and getopt that can't at this time be fixed on the rebar3 side.
=> --paths= in rebar3 bare compile fixes subcommand splitting on comma bug

lib/iex/lib/iex/autocomplete.ex
Ref: https://github.com/elixir-lang/elixir/pull/9110#issuecomment-498299548
> There's one thing somewhat related to this PR which is how we handle typeps, currently we display them in the list:
>
>     iex(2)> t :filelib
>     @typep filename() :: :file.name()
> but if we want to show just that type, it errors given its private:
>
>     iex(3)> t :filelib.filename
>     No type information for :filelib.filename was found or :filelib.filename is private
Btw, according to https://github.com/elixir-lang/elixir/issues/2612 we still want to list typeps, in this PR we'll just not autocomplete them.
=> iex: Do not autocomplete private types

lib/mix/lib/mix/tasks/release.init.ex
Concerning generated `bin/xxx.bat` from `mix release`.
Otherwise I got a file called `nil` within my directory, after starting a release.
In my case with the contents of `1 file(s) copied.`
I think there aren't any tests regarding this change, but I'm not 100% sure.
Please review, as this is my very first contribution.
=> Fix redirection to null on windows

lib/mix/lib/mix/tasks/release.ex, lib/mix/lib/mix/tasks/release.init.ex
Elixir releases offer a mechanism for generating custom boot scripts in addition to `start` and `start_clean`. This is done by adding a key value pair to the `boot_scripts` map in the `Mix.Release` struct. The generated executables currently do not offer a means for using this boot script. This PR adds the environment variables `RELEASE_BOOT_SCRIPT` and `RELEASE_BOOT_SCRIPT_CLEAN` providing overrides for `start` and `start_clean`.
=> Add RELEASE_BOOT_SCRIPT and RELEASE_BOOT_SCRIPT_CLEAN

lib/elixir/lib/calendar.ex, lib/elixir/lib/calendar/date.ex, lib/elixir/lib/calendar/datetime.ex, lib/elixir/lib/calendar/iso.ex, lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/lib/calendar/time.ex, lib/elixir/test/elixir/calendar/date_test.exs, lib/elixir/test/elixir/calendar/datetime_test.exs, lib/elixir/test/elixir/calendar/fakes.exs, lib/elixir/test/elixir/calendar/holocene.exs, lib/elixir/test/elixir/calendar/naive_datetime_test.exs, lib/elixir/test/elixir/calendar/time_test.exs
PR based upon the conversation at https://elixirforum.com/t/how-to-support-multiple-week-calendars-in-elixir/18783/10
Date, Time, DateTime and NaiveDateTime implement the
`Inspect` protocol with a specific implementation
for `Calendar.ISO`.
This commit introduces a required callback, `inspect/2`
required in all modules implementing the `Calendar` 
behaviour.
Calendars implementing `inspect/2` must ensure
the implementation caters for `Date`, `Time`, `DateTime` and
`NaiveDateTime` structs.
=> Add inspect/2 callback for Calendar

lib/mix/lib/mix/tasks/release.init.ex
When reading the file, it's not clear why uncommenting `RELEASE_NODE` fails and it fails with a message that is not easy to act on (`Can't set short node name!\nPlease check your configuration`).
=> Improve a comment in env.sh.eex for releases

lib/mix/lib/mix/tasks/release.init.ex
@josevalim this needs to be back-ported to v1.9 too
=> Fix bad naming on release script for Windows

lib/elixir/lib/keyword.ex
Use `short hand` instead of `short-hand` to be consistent
=> Update keyword.ex docs

lib/elixir/docs.exs
As of now, it was floating around at the same level as Kernel and Kernel.SpecialForms
=> Place Version.Requirement module under Basic Types in docs.exs

bin/elixir, bin/elixirc, bin/iex
This PR proposes using heredocs for the usage docs of the top-level executables.
Benefits I see:
* No need to escape double quotes within the literal.
* The rightmost column with descriptions is now vertically aligned in the source code, matching easily what the user will get printed.
* The end of the literal is obvious.
* The redirection to standard error is visible upfront.
AFAIK this is portable across different Unix shells, including `sh`.
=> Use heredocs for top-level executables' usage docs

lib/elixir/lib/protocol.ex
The main point of this patch is revising the documentation of impl_for/1, because it only mentions structures.
There are small tweaks too since I was on it: some double spaces, use italics for a defined term, be a bit more precise about debug info removal after protocol consolidation, etc.
=> Tweaks to the docs of protocols

lib/elixir/lib/macro/env.ex
This PR addresses the cause of dialyzer warnings because of the `macro_aliases` field of `Macro.Env` struct.
=> Fix typespec of Macro.Env.t

lib/mix/lib/mix/release.ex, lib/mix/test/mix/release_test.exs
The docs say:
> If mix release, without a name, is invoked and there are multiple names, an error will be raised unless you set default_release: NAME at the root of your project configuration.
But it turns out that the value is not actually used.
```sh
$ mix new bug
* creating README.md
* creating .formatter.exs
* creating .gitignore
* creating mix.exs
* creating lib
* creating lib/bug.ex
* creating test
* creating test/test_helper.exs
* creating test/bug_test.exs
Your Mix project was created successfully.
You can use "mix" to compile it, test it, and more:
cd bug
mix test
Run "mix help" for more commands.
$ cd bug 
$ nano mix.exs
$ cat mix.exs 
defmodule Bug.MixProject do
use Mix.Project
def project do
[
app: :bug,
version: "0.1.0",
elixir: "~> 1.9",
start_permanent: Mix.env() == :prod, …
```
=> Use default_release option when name is not given to mix release

lib/elixir/lib/string.ex
When calling `String.split` with options `parts` and/or `trim` explicitly
set to default values, different code path was taken in comparison to when
no options were given. The alternate code path has some performance
penalties as shown below, so it's better that the
"simple" case is handled always the same way.
```
iex(1)> lines = for _ <- 1..1_000_000, do: "a,b"
iex(2)> :timer.tc(fn -> Enum.each(lines, &String.split(&1, ",")) end)
{2254104, :ok}
iex(3)> :timer.tc(fn -> Enum.each(lines, &String.split(&1, ",", trim: false)) end)
{61426180, :ok}
```
=> Unify code path in String.split

lib/ex_unit/lib/ex_unit/case.ex
I assume it's an oversight that `@describetag` wasn't being checked here?
=> Raise for @describetag defined before use ExUnit.Case

lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/test/ex_unit/case_test.exs
This adds `ExUnit.Case.register_describe_attribute/3` and `ExUnit.Case.register_module_attribute/3`.
This was initially discussed in this thread: https://groups.google.com/forum/#!topic/elixir-lang-core/WcLghqAmBE4
=> Add describe and module attributes

lib/mix/lib/mix/tasks/deps.unlock.ex, lib/mix/test/mix/tasks/deps_test.exs
Analogous to `mix format --check-formatted`, errors if there is any unused dependencies when running `mix deps.unlock --check-unused`. 
Apologies if there is supposed to be some pre discussion before opening this, but it seemed simple enough and fitting with other existing `mix` flags. 
As an aside, it seems like the `--filter` flag is undocumented.
=> Add mix deps.unlock --check-unused flag

lib/elixir/lib/integer.ex
Matching with `is_binary/1` once is a slight performance gain, only noticable on long numbers. It also makes the `FunctionClauseError` more clear (which is for most users and newcomers the bigger benefit I think).
`is_binary`:
```elixir
iex> Integer.parse <<0::size(1)>>
** (FunctionClauseError) no function clause matching in Integer.parse/2    
The following arguments were given to Integer.parse/2:
<<0::size(1)>>
10
Attempted function clauses (showing 2 out of 2):
def parse(_binary, base) when not(is_integer(base) and (base >= 2 and base <= 36))
def parse(binary, base) when is_binary(binary)
(elixir) lib/integer.ex:237: Integer.parse/2
```
`::binary`:
```elixir
iex> Integer.parse <<0::size(1)>>
** (FunctionClauseError) no function clause matching in Integer.count_digits/2    
The …
```
=> Optimize binary pattern matching in Integer.parse

lib/elixir/lib/module/parallel_checker.ex
`{{:__info__, 1}, :def}` is always stored in the ETS entry `:all_exports`.
=> Remove duplicated entry in Module.ParallelChecker.all_exports()

lib/elixir/lib/code/formatter.ex, lib/elixir/test/elixir/code_formatter/calls_test.exs
This is intended to fix #9204.
Since I haven't contributed to the formatter before and I am not completely satisfied with this solution, I marked this as WIP. The PR does solve the problem by not removing the parens before the `do` block when being called from the `remote_to_algebra` clause that matches calls as described in the issue. **However**, I am not entirely sure how long `state` is carried around and if just adding a flag to it (that is not reset) has any unintended side effects.  (Tests are passing, but still)
Is there a more idiomatic way of passing a "flag" for this special case to `call_args_to_algebra` without modifying the state?
=> Fix formatter removing nested parens on function with generated name

lib/elixir/lib/kernel/special_forms.ex
To avoid `warning: variable "rest" is unused`
=> Minor improvements in the documentation for <<>>/1

lib/elixir/lib/kernel.ex
- Haskell: `id`
- Clojure: `identity`
- Ruby: `&:itself`
- Elixir: `&(&1)`
Elixir shouldn't look like Perl
=> Adds &Kernel.identity/1

lib/elixir/lib/regex.ex, lib/elixir/test/elixir/regex_test.exs
As discussed in #9219, this PR keeps the current behaviour, but documents it. :)
=> Regex.split/3 documentation and tests for :include_captures and :parts

lib/mix/lib/mix/tasks/test.ex
=> Update description of formatter in Mix.Tasks.Test moduledoc

lib/elixir/lib/agent.ex, lib/elixir/lib/dynamic_supervisor.ex, lib/elixir/lib/gen_server.ex, lib/elixir/lib/kernel.ex, lib/elixir/lib/supervisor.ex, lib/elixir/lib/task.ex
I did a review of where `Module.get_attribute/2` was used in the code base, where `Module.has_attribute?/2` makes more sense and yields more correct behavior.
=> Use Module.has_attribute?/2

lib/ex_unit/lib/ex_unit/case.ex
This changes ExUnit.Case to use `Module.has_attribute?/2` in the cases where it makes sense.
=> Use Module.has_attribute?/2 in ExUnit.Case

lib/elixir/lib/tuple.ex
Since Elixir data structures are immutable, emphasize that creating a new tuple is required. Also add a `result` binding to make it more clear that the last line is being used as a result for later.
This is based on a conversation on the forum: https://elixirforum.com/t/tuple-documentation-is-confusing-for-me/23993/3
=> Increase understandability of the tuple documentation

Makefile
The current version is not compatible because of the path separators. It fails with the error:
'bin' is not recognized as an internal or external command,
operable program or batch file.
I tested those changes in Cirrus CI and it worked. [Here](https://cirrus-ci.com/task/6207090706612224) is an example of the formatter failing after intentionally introducing an unformatted code; and [another example](https://cirrus-ci.com/task/5038407389020160) with the formatter passing.
=> Make 'make test_formatter' compatible with Windows

lib/elixir/lib/registry.ex
I noticed that `child_spec/1` was missing a typespec, and "opts" seemed a little mysterious. This PR adds the missing typespec for `child_spec/1` and also cleans up the typespec for `start_link/1` (I'm not sure why that `when` was there, but it looks incorrect).
=> Improve typespecs for Registry.start_link/1 and Registry.child_spec/1.

lib/elixir/lib/application.ex
Update docs on `Elixir.Application` to recommend building releases with `mix release` instead of distillery.
=> Replace distillery reference with `mix release`

lib/mix/lib/mix/tasks/escript.build.ex, lib/mix/test/mix/tasks/escript_test.exs
In [`Mix.Tasks.Release`](https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/release.ex#L371) this option is referred to as `:strip_beams`. And even in [this modules doc](https://github.com/elixir-lang/elixir/blob/master/lib/mix/lib/mix/tasks/escript.build.ex#L34) it is referenced to look at `:strip_beams` option. However, the implementation here only uses the singular `:strip_beam` (and is the only place to do so).
This actually caused a bit of confusion in https://github.com/nerves-project/nerves/pull/443.
So this just simply changes that option and updates the doc to match how it is used elsewhere.
=> Rename Mix.Tasks.Escript.Build option to `:strip_beams`

lib/elixir/lib/calendar/datetime.ex
Added an example of how to use `Tzdata` to the `DateTime` docs.
This was requested in #9148.
I hope replacing the `CustomTimeZoneDatabase` with `Tzdata.TimeZoneDatabase` isn't too much - I think it's still obvious what to do if you want to use an alternative database.
I think the comment about adding the dependency is necessary, because if you just configure the module name without actually adding the dependency, you won't get any errors until you try to use the calendar, and then it's not obvious what the problem is.
I also opened https://github.com/lau/tzdata/pull/85 to flesh out the Tzdata's HexDocs a bit, which I though would be helpful for people that get linked there from here.
=> Add Tzdata example to DateTime docs

lib/elixir/lib/keyword.ex, lib/elixir/lib/map.ex
These function behave like their non-bang counterparts except that they raise when the key is not present. This can be useful for option handling in order to extract an option and raise at the same time if it's not there. Note that this is mostly useful when not having the key there is an unrecoverable error (for example, because you already validated options): if you want to return a nice error to the user, `pop_lazy/3` with a `raise` in the third-argument function might be a better idea.
=> Add Keyword.pop!/2 and Map.pop!/2

lib/elixir/lib/config.ex
The current method to get wildcard paths is misleading, as it only works when you start your project from the project root. If someone is in an umbrella project and start a child app, the lookup method won't get any configs, and the result maybe quite confusing.
This PR changed the example to make the example code works completely equivalent with the `Mix.Config` example.
=> Make the wildcard example equivalent with `Mix.Config` in an umbrella project

lib/mix/test/mix/tasks/release_test.exs
Addresses #9167.
The port was closed before calling `System.cmd(script, ["pid"])`, resulting in `--rpc-eval : RPC failed with reason :nodedown` errors.
As mentioned in the issue thread, I am not completely sure why the tests pass on [certain platforms](https://cloud.drone.io/alpinelinux/aports/7875/), while they seemingly shouldn't.
=> Fix release pid RPC tests

lib/elixir/lib/string_io.ex, lib/elixir/test/elixir/string_io_test.exs, lib/ex_unit/lib/ex_unit/capture_io.ex, lib/ex_unit/test/ex_unit/capture_io_test.exs
Before this patch, the encoding was always unicode. This means the
following behaviour:
iex> {:ok, pid} = StringIO.open("")
iex> IO.binwrite(pid, <<127, 128>>)
iex> StringIO.contents(pid)
{"", <<127, 194, 128>>}
One example where this may be problematic is when using
`ExUnit.CaptureIO`, e.g. we're testing that a given function outputs
binary to stdout. Currently, we have a similar issue:
iex> ExUnit.CaptureIO.capture_io(fn -> IO.binwrite(<<127, 128>>) end)
<<127, 194, 128>>
With this patch we can do the following:
iex> ExUnit.CaptureIO.capture_io(fn ->
...>   :ok = :io.setopts(Process.group_leader(), encoding: :latin1)
...>   IO.binwrite(<<127, 128>>)
...> end)
<<127, 128>>
If this is accepted, I'm wondering if it would be useful to set the
encoding on `StringIO.open/2` and/or in …
=> Allow StringIO to set encoding

lib/elixir/lib/access.ex, lib/elixir/test/elixir/access_test.exs
Hey all,
I noticed there's a `key!/1` but that's the only function in this module that supports a bang. I thought maybe `fetch/2` deserved the same love but I totally understand if not!
😄
=> Access.fetch!/2 implemented

lib/elixir/lib/code.ex, lib/elixir/lib/kernel/lexical_tracker.ex, lib/elixir/lib/macro.ex, lib/elixir/lib/macro/env.ex, lib/elixir/lib/module.ex, lib/elixir/lib/module/checker.ex, lib/elixir/src/elixir.erl, lib/elixir/src/elixir_aliases.erl, lib/elixir/src/elixir_compiler.erl, lib/elixir/src/elixir_def.erl, lib/elixir/src/elixir_dispatch.erl, lib/elixir/src/elixir_env.erl, lib/elixir/src/elixir_expand.erl, lib/elixir/src/elixir_import.erl, lib/elixir/src/elixir_lexical.erl, lib/elixir/src/elixir_map.erl, lib/elixir/src/elixir_module.erl, lib/elixir/src/elixir_quote.erl, lib/elixir/test/elixir/code_test.exs, lib/elixir/test/elixir/kernel/lexical_tracker_test.exs, lib/elixir/test/elixir/kernel/parallel_compiler_test.exs, lib/elixir/test/elixir/kernel/tracers_test.exs, lib/elixir/test/elixir/module/checker_test.exs, lib/mix/lib/mix/compilers/elixir.ex, lib/mix/lib/mix/compilers/test.ex, lib/mix/lib/mix/tasks/compile.elixir.ex, lib/mix/test/mix/tasks/compile.elixir_test.exs
This feature allows IDEs and other tools wanting to
perform source code analysis to do so reliably without
a need to reimplement Elixir's compiler expansion and
without relying on Elixir's private APIs.
This commit also adds `:parser_options` to compiler
options, which allows developers to combine both options
to retrieve more accurate information, such as columns.
The lexical tracker has been rewritten to use the tracing
API.
=> Add compiler tracing

lib/eex/lib/eex.ex
When I was searching the eex docs I wasn't able to find any info about "escaping" and didn't realize that the `<%%` form was meant for escaping an eex expression inside of eex.
=> Document escaping in eex more clearly

lib/ex_unit/lib/ex_unit/diff.ex, lib/ex_unit/test/ex_unit/diff_test.exs
It improves the diff for comparisons with ok and error tuples.
The change affects both match and expression contexts.
Closes #9259
=> Compare tuples positionally in Diff

lib/ex_unit/lib/ex_unit/diff.ex
When the elements of the container are too big and rendered in different lines, the separator is missing.
This change fixes that.
References #9259
=> Fix container algebra on diffs

lib/elixir/lib/process.ex
Erlang [deliberately omitted](https://github.com/erlang/otp/blob/51d33208b08a257b59a64a35a953bb44c864f115/erts/preloaded/src/erlang.erl#L2251-L2253) `:monitor_nodes` from `process_flag/2` docs. 
To avoid confusion, `Process.flag/2` docs should omit these flags too .
=> Remove undocumented process flags

lib/elixir/lib/kernel.ex, lib/elixir/pages/Typespecs.md
This PR updates documentation.
- `Kernel.struct/2` doesn't work with multiple structs.
- In the `Typespecs` page, the `t/0` of `Range` doesn't link a proper Range type; instead create `file:///T:/Range.t/0` which is unexpected. And the actual `Range.t/0` is duplicated in the same sentence.
=> Doc) Remove missing link and ambiguous expression

lib/mix/lib/mix/tasks/deps.compile.ex, lib/mix/test/mix/tasks/deps_test.exs
This addresses the problem outlined in
https://github.com/elixir-lang/elixir/issues/7519
`mix deps.compile` can be a good way of caching builds
in a CI environment. Also it's good contain the warnings of the `mix
deps.compile` from the ones of `mix compile`.
=> Allow mix deps.compile to ignore umbrella apps

lib/mix/lib/mix/release.ex, lib/mix/lib/mix/tasks/release.ex, lib/mix/test/mix/release_test.exs
Sometimes it is desireable to lookup the version from another
application to use as the version for a release. This is true in the
case of umbrella applications, where a particular app may be targetted
for a release.
Using `{:from_app, :my_app}` will allow the version returned from
`Application.spec(:my_app, :vsn)` to be used as the version.
=> Allow {:from_app, app_name} as a version for releases

lib/mix/lib/mix/release.ex
Minor inconvenience, from this little [comment](https://github.com/elixir-lang/elixir/commit/b43a6a923e2cbf641421ad10f98b67485bc83548#r34634308).
=> Fix missing backtick in mix.release struct docs

lib/elixir/lib/module.ex, lib/elixir/src/elixir_code_server.erl, lib/elixir/src/elixir_module.erl, lib/elixir/test/elixir/module_test.exs, lib/ex_unit/lib/ex_unit/case.ex
This should be treated mostly as a proposal, but since it’s always easier to explain with code, I’ve created a PR.
Docs for `Module.open?/1` say:
```elixir
@doc """
Checks if a module is open.
A module is "open" if it is currently being defined and its attributes and
functions can be modified.
"""
@spec open?(module) :: boolean
```
The above breaks contract if called from `__after_compile__/2` callback. What leads to the fact all the modifying functions, like `Module.put_attribute/3` are allowed and silently ignored. My concern is `Module.open?/1` should not return `true` from there, and it could have been fixed as proposed below, save for it might break the existing code (as might be seen in `lib/ex_unit/lib/ex_unit/case.ex` below.)
On the other hand, it’d always be a compilation time …
=> Make Module.open?/1 and family to match their docs

lib/elixir/lib/dynamic_supervisor.ex
The type `init_option()` is used in `init/1` and `start_link/1`.
=> Fix function arity in the DynamicSupervisor docs

lib/elixir/lib/regex.ex
this PR is a little update on the `Regex` documentation to inform that the `:all_names` capture option brings the results as a list ordered alphabetically by the `subpattern` names
=> update  capture option doc

lib/elixir/lib/list.ex
Questions on charlists are probably the most common ones of beginners in elixir. I know we have quite a few resources on it, but I don't feel we have a concise common place to link to when trying to help people confused by their first encounter.
https://elixir-lang.org/getting-started/binaries-strings-and-char-lists.html
This is already good, but it deals with charlists from the direction of someone dealing with a string and wanting to deal with a string, while most often beginners are surprised by their lists of numbers getting turned into a string. I think it's good the way it is as part of the getting started guides, but doesn't serve well as point to link surprised people to.
https://github.com/elixir-lang/elixir/wiki/FAQ#4-why-is-my-list-of-integers-printed-as-a-string
This is linked …
=> Improve documentation on charlists

lib/elixir/lib/list/chars.ex, lib/elixir/test/elixir/list/chars_test.exs
Presently, `List.Chars.to_charlist/1` returns `'nil'` when passed `nil`, which feels sort of odd to me. I believe that the canonical character list form of `nil` should be an empty list, similar to how `String.Chars.to_string/1` returns an empty string when passed `nil`.
I added a test around the new behavior, of course, and also around the handling of `true` and `false` since they are also special atoms (though they are handled well by the existing code :smile:).
=> Change List.Chars.to_charlist to return empty list when given nil

lib/mix/lib/mix/release.ex, lib/mix/lib/mix/tasks/release.ex, lib/mix/test/mix/release_test.exs, lib/mix/test/mix/tasks/release_test.exs
Closes #9289
There are a couple of points worth discussing.
@ericmj mentioned using :systools, even if we want to change that, the tests, docs and validations in this PR should still be valid.
Currently the step is simply called `:tar`. Not sure if we want to use a different name, or allow users to build the tar in a different location (something like `{:tar, "some/path/for/myapp.tar.gz"}`
=> Add `:tar` option for releases to create a tarball

lib/elixir/lib/module.ex
As it apparantly was renamed in bb08b415d4852e8f7ae47ebe5421742ce611a6b6
=> Replace `mix xref warnings` with `mix xref deprecated` in Module docs

lib/elixir/lib/protocol.ex, lib/elixir/test/elixir/protocol/consolidation_test.exs
How to reproduce:
This works:
```elixir
iex> path = :code.lib_dir(:elixir, :ebin)
iex> mods = Protocol.extract_impls(Enumerable, [path])
iex> List in mods
true
```
This does not work
```elixir
iex> path = Application.app_dir(:elixir, "ebin")
iex> mods = Protocol.extract_impls(Enumerable, [path])
iex> List in mods
false
```
However the spec says:
```elixir
iex(1)> h Protocol.extract_impls
def extract_impls(protocol, paths)
@spec extract_impls(module(), [charlist() | String.t()]) :: [atom()]
```
And it accepts also a `String.t()`
=> Support binary path in Protocol.extract_impls/2

lib/elixir/lib/module.ex, lib/elixir/pages/Typespecs.md
I was doing some work with behaviours and found the documentation about how to inspect a behaviour a little lacking (resulting in me asking [this SO question](https://stackoverflow.com/questions/57653216/elixir-testing-ensure-a-module-defines-a-callback)), so I've added some information to the Typespec docs, and also linked there from the behaviour section of `Module` docs.
* Add a link from `Module` to the relevant section of the Typespec docs.
* Add an `Inspecting behviours` section to the Typespec docs that
documents how to inspect the behaviours. This information is so far
only available in the deprecated `Behaviour` module or the Erlang docs.
=> Improve behaviour documentation

lib/elixir/lib/enum.ex
**What**
Small update to documentation for `Enum.chunk_while/4`.
**Why**
When using `Enum.chunk_while` for the first time, this portion of the documentation confused me and I ended up returning individual elements in my `chunk_fun` instead of the whole chunk of data.
=> Clarification in documentation for Enum.chunk_while/4

lib/elixir/lib/protocol.ex
This PR documents `__impl__/1` function of protocol module implementations, as discussed [here](https://github.com/sasa1977/boundaries/issues/5#issuecomment-525929855).
=> Documents __impl__/1 of protocol implementation

lib/ex_unit/examples/difference.exs, lib/ex_unit/lib/ex_unit/assertions.ex, lib/ex_unit/lib/ex_unit/diff.ex, lib/ex_unit/lib/ex_unit/formatter.ex, lib/ex_unit/test/ex_unit/assertions_test.exs, lib/ex_unit/test/ex_unit/diff_test.exs
Uses `ExUnit.Diff` to improve `ExUnit.Assertions.assert_receive/1` and `ExUnit.Assertions.assert_received/1`
The formatting slightly changed to accommodate the diffs and it's more similar to the other assertions
Closes #6248
=> Improve assertions on the process mailbox

lib/logger/lib/logger/app.ex, lib/logger/lib/logger/erlang_handler.ex
The Dialyzer was issuing a warining on `logger:add_handler/3` call as
the key `sasl_reports?` should not be in root map but rather within
`config` key of the map.
=> Registration of ErlangHandler spec mismatch

.github/workflows/ci_email.yml
This is the configuration to send an email whenever the Cirrus CI checks fail. The email is delivered to the author and committer of the commit, which should cover the cases of merging PRs, edits from GitHub UI, and so on.
We need to upgrade the Elixir repository to the new GitHub actions:
and configure the secrets `CI_EMAIL_USERNAME` and `CI_EMAIL_PASSWORD` under `Settings > Secrets`.
=> Add GitHub actions workflow to send CI emails

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel/sigils_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs
When creating word lists (e.g., `~w(foo bar baz)`), it is a common mistake to insert trailing commas for some or all parts of the list (e.g., `~w(foo, bar, baz)`).  This PR introduces a warning when such trailing commas are encountered, in macros and regular code:
```
iex> ~w(hello, world)
warning: item "hello," in word list has a trailing comma; was this intentional?
iex:1: (file)
["hello,", "world"]
```
=> Warn on trailing commas in word list

lib/mix/lib/mix/tasks/release.init.ex
As a follow up from #9339, this uses `cat` instead of `cp` to make sure that no peculiar permissions or symlink dereferencing happen with the resulting configuration file, and it is created with default current user permissions.
=> Use cat to create runtime configuration more reliably

lib/elixir/lib/registry.ex
The first commit removes the redundant use of `[]` in the `guards/0` typespec.
~The second commit removes the unnecessary typespec `guard/0`, since we can do away as we do with the `body/0` and the others.~
=> Simplify t:Registry.guards/0

lib/elixir/src/elixir_tokenizer.erl
When comparing characters in `elixir_tokenizer`, replace `==` and `/=`
with the more efficient `=:=` and `=/=` operators.
The `=:=` and `=/=` operators are more efficient because they can
only return `true` if the operands have the same type:
1> $* =:= 42.
true
2> $* =:= 42.0.
false
In contrast, the `==` operator can return `true` when comparing
an integer and a float:
3> $* == 42.0.
true
Using `=:=` and `=/=` also gives the Erlang compiler more opportunites
for optimization. For example, when compiling the `is_sigil` macro,
the compiler can combine all eight comparisons into a single `select_val`
instruction instead of emitting eight separate instructions.
=> Optimize elixir_tokenizer

lib/elixir/lib/module.ex, lib/elixir/test/elixir/module_test.exs
Closes #9351.
I wasn't sure how to update the docs and since we mention elsewhere we
receive quotes arguments I just remove the whole section.
Alternatively, here's my attempt at updating the docs:
> The hook is invoked after the function was stored in the module,
> this means that, for example, `Module.defines?/2` would always
> return `true` when invoked in this hook.
=> Update on_definition with Module.exists?/2 docs & test

lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/test/ex_unit/case_test.exs
=> Allow to reset async for ExUnit.Case by using it again

lib/elixir/lib/code.ex, lib/mix/lib/mix/project.ex, lib/mix/lib/mix/tasks/compile.erlang.ex, lib/mix/test/mix/tasks/compile.erlang_test.exs
That way, if someone sets erlc_options to `[warnings_as_errors: true]`, `:debug_info` would still be on the options. To configure it to not save debug info, one should only add `debug_info: false` to erlc_options
Closes #9184
=> Always adding :debug_info on erlc_options

lib/mix/lib/mix/cli.ex, lib/mix/lib/mix/tasks/app.start.ex, lib/mix/test/mix/cli_test.exs, lib/mix/test/mix/tasks/app.start_test.exs
Part of the configuration of the Logger can be changed dynamically but other part is only used at start. For example, the `:console` backend is implemented with `gen_event`, and its configuration is only read on `init` to build the state.
Logger is first started by Elixir using its default configuration, but the project's configuration is not used fully until the Logger application is restarted. This usually happens when the application is started, but not all Mix tasks do such thing.
This commit ensures that Logger is restarted before calling any Mix task.
=> Ensure project's Logger config is used when running Mix tasks

lib/elixir/lib/calendar/datetime.ex
Single character fix marking `:millisecond` as an atom to match `:second` and `:microsecond`.
=> Fix truncate docs for millisecond precision

lib/elixir/test/elixir/calendar/date_test.exs, lib/elixir/test/elixir/calendar/holocene.exs
This commit updates the test Calendar.Holocene module:
1. to_string/1 removes the "Calendar.Holocene" annotation
in the output string. This is somewhat
problematic because calling `to_string/1` on a date now no
longer emits anything which identifies what calendar it is in.
2. Implements a simple `parse_date/1` function to allow
basic testing of years >= 10_000 and <= -10_000
=> Update Calendar.Holocene to_string/1 and parse_date/1

lib/elixir/lib/code/formatter.ex, lib/elixir/test/elixir/code_formatter/comments_test.exs
Currently,
When defining a struct as following
```elixir
defstruct [
a: 1,
b: 2
]
end
```
It will be formatted to
```elixir
defstruct a: 1,
b: 2
end
```
I think when the first field has some comment, `defstruct` should keep the square brackets.
=> Fix defstruct code formatting

lib/elixir/lib/stream.ex
Was clear that it modifed stream shape.  *However*, we thought changing element return was also possible.
Took a little bit of tinkering, discussion with @tonyvanriet, and finally looking at implementation before we realized the accumulator was discarded.
Am happy to have the PR discarded or language changed.  Just want to prevent the same misunderstanding for future readers of the docs.
=> Make clear Stream.transform is *only* about shape transformation

lib/elixir/lib/calendar.ex, lib/elixir/lib/calendar/date.ex, lib/elixir/lib/calendar/datetime.ex, lib/elixir/lib/calendar/iso.ex, lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/lib/calendar/time.ex, lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/calendar/date_test.exs, lib/elixir/test/elixir/calendar/datetime_test.exs, lib/elixir/test/elixir/calendar/fakes.exs, lib/elixir/test/elixir/calendar/holocene.exs, lib/elixir/test/elixir/calendar/naive_datetime_test.exs, lib/elixir/test/elixir/calendar/time_test.exs
This is the first step in the extended sigils.
It is similar to what @kipcole9 had but I moved the whole `from_iso8601` code to the `Calendar.ISO` module. Also, the idea is that the parsing functions will be counterparts to the `_to_string` functions, so we don't need to have both `_to_string` and `_inspect`. Once we inspect each date, we will automatically inspect them as:
"#{calendar.type_to_string(...)} #{calendar}"
Without special handling for Calendar.ISO (except by hiding the Calendar.ISO part).
I still need to do a couple things to finish this:
Initial feedback is welcome before we move forward, especially on the function names.
/cc @kipcole9 @wojtekmach
=> Add parse_date/parse_naive_datetime/parse_utc_datetime to Calendar behaviour

lib/elixir/lib/kernel/special_forms.ex
In the docs for `case/2`, there's a [section about variable scope](https://hexdocs.pm/elixir/Kernel.SpecialForms.html#case/2-variable-handling) that doesn't seem accurate to me:
> However, variables explicitly bound in the clause "body" are accessible from the outer context:
> ```elixir
> value = 7
>
> case lucky? do
>   false -> value = 13
>   true -> true
> end
>
> value
> #=> 7 or 13
> ```
When attempting the `lucky? = false` case in IEx, `value` in the outer context is `7`, not `13`:
```elixir
Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Interactive Elixir (1.9.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> lucky? = false
false
iex(2)> value = 7
7
iex(3)> case lucky? do
...(3)>   false -> value = 13
...(3)>   true -> true …
```
=> Update docs for Kernel.SpecialForms.case/2

lib/elixir/lib/kernel.ex
During bootstrap, the generated AST for the `defexception` macro does not include import metadata when calling to Kernel functions without using the qualified name. That's not the case when the Kernel is later recompiled.
When compiling the standard library, exceptions like `FunctionClauseError` were generating different ASTs (different metadata) depending on if they were compiled with the bootstrapped Kernel or the later compiled one.
This was spotted during the migration to Cirrus CI, in which the `check_reproducible` check was failing. I managed to create a "BEAM diff" (PR upcoming) that showed these results:
```
94,95c94
<                 {{:., [], [:erlang, :is_list]},
<                  [line: 1063, context: Kernel, import: Kernel],
---
>                 {{:., [], [:erlang, …
```
=> Ensure reproducible builds (boostrapping issue)

lib/elixir/lib/module/types.ex, lib/elixir/lib/module/types/helpers.ex, lib/elixir/lib/module/types/infer.ex, lib/elixir/test/elixir/module/types/infer_test.exs, lib/elixir/test/elixir/module/types_test.exs
This PR does the following changes and improvements to our guard analysis:
* Analyze both type check guard functions, such as `is_list/1`, and failing guard functions, such as `length/1`.
* Split context into stack and context. Unlike the context the stack is never returned.
* Adds missing type guard functions.
* Changes list type to `type(a)` from `cons(a, b)`.
=> Check more guard functions

lib/elixir/lib/enum.ex, lib/elixir/lib/string.ex
ExDoc was giving the following errors:
> lib/elixir/lib/string.ex:250: warning: Closing unclosed backquotes ` at end of input
> lib/elixir/lib/enum.ex:2319: warning: Closing unclosed backquotes ` at end of input
=> Close unclosed backquotes (backticks)

lib/elixir/lib/keyword.ex
ExDoc is giving a warning since it has been deprecated and @doc is set to false.
> warning: documentation references `Keyword.delete/3` but it doesn't exist or it's listed as @doc false (parsing Keyword docs)
[ci skip]
=> Remove reference to Keyword.delete/3

lib/elixir/src/elixir_clauses.erl, lib/elixir/test/elixir/kernel/expansion_test.exs
This fixes an edge case in which the compiler will process an
empty list value (`[]`) as a block with no clauses, which is not
possible.
Here is an example:
with {:ok, value} <- Map.fetch(%{a: 1}, :a) do
value
else
[]
end
With this change, the code above will not compile.
=> Raise when passing an empty list instead of clauses

lib/ex_unit/lib/ex_unit/callbacks.ex
Be explicit and also used a valid typespec (`keywords` is not valid,
but `keyword` is).
=> ExUnit.Callbacks: Be explicit about the shape of a return value

lib/elixir/lib/regex.ex, lib/elixir/lib/registry.ex, lib/mix/lib/mix/generator.ex, lib/mix/lib/mix/tasks/release.ex
* Use imperative verbs in bulleted lists
* Use "does not" instead of "do not" in bulleted lists
Related: 690c2c40c948564f7db5fccfd66246ed78c6fe8d
[ci skip]
=> Standardize use of verbs in bulleted lists

lib/elixir/lib/kernel.ex, lib/elixir/lib/kernel/special_forms.ex
=> Use double-quotes around sections when referring to them

lib/elixir/lib/calendar/iso.ex
The return `year` is always a positive number
Dialyzer was giving this error:
> lib/calendar/iso.ex:672: Type specification 'Elixir.Calendar.ISO':year_of_era(year()) -> {year(),era::0..1} is a supertype of the success typing: 'Elixir.Calendar.ISO':year_of_era
(integer()) -> {pos_integer(), 0 | 1}
=> Fix typespec for Calendar.ISO.year_of_era/1

lib/mix/lib/mix/tasks/test.ex, lib/mix/test/mix/tasks/test_test.exs
This PR implements the functionality described on step #3 here: https://medium.com/@cblavier/how-we-improved-our-elixir-build-speed-by-5x-d45393c6700f
The rationale is: not all tests can run async (think about tests that change the current directory, for example) so having OS based parallelism is a great help. This can also be used to automate CIs. With this PR, you would be able to do:
MIX_TEST_PARTITION=1 mix test --partitions 4
MIX_TEST_PARTITION=2 mix test --partitions 4
MIX_TEST_PARTITION=3 mix test --partitions 4
MIX_TEST_PARTITION=4 mix test --partitions 4
Note the partition itself is given as an environment variable so it can, for example, be used to configure a database and other things in config files.
The current implementation simply partitions files but @wojtekmach suggested …
=> Add basic mix test partitioning

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
Hi! Thank you for great programming language.
add frequencies and frequencies_by.
This is a discussion about this method.
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/elixir-lang-core/hBRKIIy8QKE/2JlhpblqBgAJ
If any points to fix, don't hesitate to say.
=> add  Enum.frequencies and Enum.frequencies_by

lib/elixir/lib/list.ex
I think this is an important detail to include in the documentation because the error when the base it greater than 36 is cryptic.
```
iex(3)> List.to_integer('3FF', 37)
:erlang.list_to_integer('3FF', 37)
```
💚
=> List.to_integer docs include the max value for base

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
Before this PR, sorting dates, decimals, and other structs was
somewhat awkward:
Enum.sort(dates, &(Date.compare(&1, &2) != :lt)) # ascending
Enum.sort(dates, &(Date.compare(&1, &2) != :gt)) # descending
Sorting a user by dates, decimals, and other structs was equally
verbose:
Enum.sort_by(users, &(&1.birthday), &(Date.compare(&1, &2) != :lt)) # ascending
Enum.sort_by(users, &(&1.birthday), &(Date.compare(&1, &2) != :gt)) # descending
Even a general sort in reverse required passing &>=/2 as an argument,
which is not clear in intent:
Enum.sort(list, &>=/2) # descending
This PR addresses this by:
1. Allow `:asc` and `:desc` to be given as sorting functions.
2. Allow a module to be given to sort, which will automatically
compare/2. The module can also be wrapped in a :asc/:desc tuple.
All of …
=> Add asc/desc and compare support to Enum.sort

lib/elixir/lib/enum.ex
Thank you for Elixir.
I updated `frequencies` and `frequency_by` to avoid the function overhead with advice https://github.com/elixir-lang/elixir/pull/9425#discussion_r336789305
Thank you @michalmuskala
=> Update frequencies and frequency_by to avoid the fun overhead

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs, lib/elixir/test/elixir/exception_test.exs
Prior to this PR, there was no convenient way of getting the earliest/latest calendar type nor get the min/max datatype driven by a calendar type.
This PR adds this functionality by allowing a sorter function in `min/max/min_by/max_by` and allowing a sorter function to be automatically derived with a module by using `compare/2`, similar to #9426 
This PR introduces, however, a future deprecation, since the empty callback has been moved one argument ahead. This deprecation will be emitted only in the future (if we choose to do so).
=> Allow a sorting function on min/max/min_by/max_by

lib/elixir/src/elixir_compiler.erl, lib/elixir/src/elixir_lexical.erl, lib/elixir/src/elixir_module.erl, lib/mix/test/mix/tasks/compile.elixir_test.exs
Currently the callbacks on :elixir_compiler are called before the warnings of unused aliases and imports are emitted, causing the messages to not consumed during the compilation. This commit changes `:elixir_lexical.run/2` to `:elixir_lexical.run/3` splitting the callback in two, one during the execution to evaluate the forms and another to be called after all the warnings are emitted.
Fixes #9440
=> Execute callbacks on :elixir_compiler after all warnings are emitted

lib/elixir/lib/io.ex, lib/elixir/lib/string_io.ex, lib/elixir/test/elixir/fixtures/multiline_file.txt, lib/elixir/test/elixir/io_test.exs, lib/ex_unit/test/ex_unit/capture_io_test.exs
Hello, this code:
```elixir
{:ok, file} = File.open("file.txt"), [:charlist])
IO.read(file, :all)
```
would return only first line of  the file. While I was preparing fix for this case, I've encountered another problem. Namely `StringIO` does not comply with `:io.getopts/1` well, as it returns `{:ok. opts}` instead of just `opts`, so I've fixed it too.
I would say these are bugs, but fixing them risks breaking existing code that depends on this behaviour, and I am not sure how you usually handle such changes.
I think this PR fixes both issues I've mentioned above.
=> Fix reading whole file opened as :charlist

lib/elixir/lib/kernel/utils.ex, lib/elixir/test/elixir/kernel/warning_test.exs
Warning is the preferable solution for this, if we raise instead then it
is likely that there are some existing libraries that use duplicate
struct keys that will break.
=> Warn if duplicate key found in struct

lib/ex_unit/lib/ex_unit/capture_io.ex
The information about `:stderr` and `:stdio` being aliases for
`:standard_error` and `:standard_io` wasn't included in this
documentation, so I added that here. I also added some typespecs for
documentation on how users can use these functions since the function
stubs in ExDoc didn't include all of the possible ways to call them.
=> Add additional documentation for ExUnit.CaptureIO

lib/elixir/lib/record.ex, lib/elixir/test/elixir/kernel/warning_test.exs, lib/elixir/test/elixir/record_test.exs
Similar to #9452 :D
Worth noting erlc errors on this too:
```
-record(r, {a, a}).
```
src/m.erl:2: field a already defined in record r
=> Warn if duplicate key is found in record

lib/mix/test/mix/umbrella_test.exs, lib/mix/test/test_helper.exs
A test is failing and it looks like the test assumes that recompilation takes at least 1 second. Because the mtime has a granularity of 1 second. Some times the compared times are equal and fails the test. Example: https://travis-ci.org/elixir-lang/elixir/jobs/606593844#L285
This adds a 1 second delay in the test.
=> Avoid race condition in test

lib/elixir/lib/map_set.ex
This changes the implementation of none_in?/2 (and a few other functions) from `match?` or a pin match to the :erlang.is_map_set/2 BIF. For `disjoint?/2` the result is 1.08x faster, according to benchmarks. Due to the use of `is_map_key` this change only works in Erlang 21.0+.
Benchmark using MapSets with 100 random keys, checking for a worst case match of the 100th key:
```
Operating System: macOS
CPU Information: Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
Number of Available Cores: 4
Available memory: 8 GB
Elixir 1.9.1
Erlang 22.0
Benchmark suite executing with the following configuration:
warmup: 1 s
time: 4 s
memory time: 0 ns
parallel: 1
inputs: none specified
Estimated total run time: 10 s
Benchmarking CustomMapSet...
Benchmarking MapSet...
Name                   ips        average …
```
=> Improve MapSet comparison performance

lib/elixir/lib/dynamic_supervisor.ex, lib/elixir/lib/gen_server.ex, lib/elixir/lib/task/supervised.ex, lib/logger/lib/logger/translator.ex
=> Remove calls to error_logger

lib/elixir/lib/enum.ex
Split was allowing values like 2.0, and higher but throwing on 1.0, 0.0, and -1.0 which was not coherent. Even it does not make any sense to give floating values, it feels weird that it allows some of them and not others.
This fix now allow these values.
=> Update on Enum.split

lib/mix/lib/mix/release.ex, lib/mix/test/mix/release_test.exs
`mix.release` generates undeterministic boot script inside the release. This PR sorts applications list before this script is generated. 
More informations here: https://github.com/nerves-project/shoehorn/issues/30
=> Make release's boot scripts deterministic

lib/elixir/lib/kernel.ex, lib/elixir/lib/kernel/special_forms.ex
Kernel:
- prefix is `Kernel.`, not `Kernel`;
- grammatical corrections and rewording.
Kernel.SpecialFroms:
- mention that the module consist of macros which are automatically imported and can be called
without prefix.
=> Improve module docs in Kernel and Kernel.SpecialForms

lib/logger/lib/logger.ex
Since Elixir only evaluate Logger macro arguments when the message will be logged, we should remove these examples since they might confuse people reading the docs into thinking that they should still wrap their log statements.
=> Remove anonymous function examples

lib/elixir/lib/dynamic_supervisor.ex, lib/elixir/lib/supervisor.ex
- Changes to its specs to reflect deprecated child spec.
- Changes to the code so not it fails with FunctionClauseError if child_spec
doesn't match the spec.
- Documentation fixes.
=> Updates on DynamicSupervisor.start_child/2

lib/elixir/pages/Guards.md
* Clarify distinction of guard expressions and functions and operators.
* Recommend using type-check guard functions.
* Reorder sections such that the "multiple guards" section immediately follows the "errors in guards" section.
=> Make distinction of guard expressions and functions/operators

lib/elixir/lib/module/types/infer.ex, lib/elixir/lib/string.ex
As noun or verbs it is spelled "type check"
[ci skip]
=> Use type-check when it's an adjective

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
Affects: `~> 1.7`, `~> 1.8` and `~> 1.9`
Fixes: #9506
The problem is caused by this commit: 11a0b39ad4a57236c9eb6bf17e5d46cc06621b8b
This means that it has been done when working on `v1.7.0-rc.0` for deprecating `Enum.chunk/4` in favor of `Enum.chunk_every/4`.
=> Fix for default leftover in Enum.chunk/3

lib/mix/lib/mix/tasks/compile.protocols.ex
Allow protocol consolidation to be configurable
with a default timeout value of 30 seconds.
=> Configurable protocol consolidation timeout

lib/elixir/pages/Typespecs.md
fixes: #9522
ping: @ericmj 
Initially added in this commit: f1d4d5b034bd47d6488b808766f25a3f6fd82683
> Good find. It should only be listed in built-in types.
=> Removed struct() from list of Basic Types in Typespecs.md

lib/elixir/lib/kernel/parallel_compiler.ex, lib/mix/lib/mix/compilers/elixir.ex, lib/mix/lib/mix/tasks/compile.elixir.ex
~~I didn't document it because it's only useful for devs working on the group pass. I also made it a variable instead of a flag so you can set it once for all your projects instead of passing the flag to every `mix compile`.~~
=> Add --profile time flag to profile compilation steps

lib/eex/test/eex_test.exs, lib/elixir/test/elixir/code_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs, lib/elixir/test/elixir/protocol/consolidation_test.exs
Capturing a named device other than `:stdio`, such as `:stderr`, happens globally and requires `async: false`.
=> Prevent calling non-async functions in async tests

lib/elixir/test/elixir/test_helper.exs, lib/mix/test/test_helper.exs
Temporary disable those test on Windows since the `epmd` daemon is failing to start in some Windows setups.
This is a temporary fix to not block the migration to Cirrus CI
=> Exclude tests that require epmd on Windows

lib/ex_unit/lib/ex_unit/capture_io.ex, lib/ex_unit/lib/ex_unit/capture_server.ex, lib/ex_unit/test/ex_unit/capture_io_test.exs
I hope @fertapric doesn't mind that I took a swing at this one. I just now saw that he was assigned...
With this change all StringIO stuff for named devices has been moved to the CaptureServer and we start a single StringIO for a given named device. All further captures on that device share the same StringIO, until all captures on that device have finished, at which time the StringIO is closed.
Async output from the device will be mixed in with other output, but we will offset from when a capture is first started to try and avoid too much unintended output being included in the captured output.
One thing that's a little tricky is that with the single StringIO, we only set the encoding once when the StringIO is first spawned. There's definitely some additional documentation or something …
=> Revamp capture_io for named devices to be async

lib/elixir/lib/macro/env.ex, lib/elixir/lib/module/types/helpers.ex, lib/elixir/src/elixir_env.erl, lib/elixir/src/elixir_expand.erl, lib/elixir/src/elixir_module.erl, lib/elixir/test/elixir/kernel/expansion_test.exs, lib/elixir/test/elixir/module/types/infer_test.exs, lib/elixir/test/elixir/module/types/pattern_test.exs
Instead of incrementing the version for each variable individually we increment it globally for all variables. This means we can uniquely identify each variable assignment with only the version.
=> Track variable version globally

lib/elixir/lib/calendar.ex, lib/elixir/lib/calendar/iso.ex
Additionally, it introduces t:Calendar.day_of_era/0.
=> Fix bug in Calendar.ISO.day_of_era/3 typespec

lib/elixir/lib/calendar.ex, lib/elixir/lib/calendar/iso.ex
The reasoning is that the `0..999_999` and `0..6` values only applied
to the Calendar.ISO calendar, and that could be restrictive for other
types of calendars. As discussed in
https://github.com/elixir-lang/elixir/pull/9493#pullrequestreview-312050446
=> Introduce t:Calendar.ISO.microsecond/0 and fix t:Calendar.microsecond/0

lib/elixir/lib/exception.ex, lib/elixir/test/elixir/exception_test.exs
Ended up with @fertapric's suggestion but also appended the `...` as hinted at by @josevalim which ended up making the non visible clause section more obvious.
```
The following arguments were given to Macro.to_string/2:
:invalid
:invalid
Attempted function clauses (showing 10 out of 24):
def to_string(-{var, _, context} = ast-, fun) when -is_atom(var)- and -is_atom(context)-
def to_string(-{:__aliases__, _, refs} = ast-, fun)
def to_string(-{:__block__, _, [expr]} = ast-, fun)
def to_string(-{:__block__, _, _} = ast-, fun)
def to_string(-{:<<>>, _, parts} = ast-, fun)
def to_string(-{:{}, _, args} = ast-, fun)
def to_string(-{:%{}, _, args} = ast-, fun)
def to_string(-{:%, _, [struct_name, map]} = ast-, fun)
def to_string(-{:fn, _, [{:->, _, [_, tuple]}] = arrow} = ast-, fun) when …
```
=> Make the number of attempted function clauses in FunctionClauseError more obvious

lib/mix/lib/mix/tasks/release.ex
Elixir releases behave slightly differently in the package manager Guix, as erlang & elixir will contain references to the Guix store. These will then get copied to the release and the release won't be able to run on the target without having the needed Guix packages installed.
I think this behaviour is fine, considering there already are constraints regarding the matching of host and target, but it would be great to also have this case documented in Elixir.
As a side-note, the user could run a script that replaces the references to the Guix store in the release, but documenting this here would probably just be confusing.
=> Add note about package managers to release docs

lib/mix/lib/mix/tasks/release.init.ex
Using any other name there will cause release to fail - I think it's
good to have that information there - see f.e. #9195.
=> Add comment specyfing possible value of RELEASE_DISTRIBUTION inside env.{sh,bat}.eex

bin/elixir
This is an implementation of [`NO_COLOR`][1] initiative that proposes single environment variable to prevent using colours in terminal. While I do not use that, I think that some people can be interested in such functionality.
[1]: https://no-color.org
=> Add support for NO_COLOR environment variable

lib/mix/lib/mix/tasks/archive.install.ex
This makes the `mix archive.install` help text consistent with the other changes from
commit 4b6b81098628f5f539a91b56357575293ca2bf55 and the `mix escript.install` help text.
Without a PR or any real description to explain this being intentional, the diff seems to imply that this may have been overlooked.
=> Remove the URI example for `mix archive.install` help text

bin/elixir
Before this fix, colors are disabled in my shell, and NO_COLOR variable is unset.
Fixes a bug introduced in 499781d5dd304964981fce093ae7d1ade56d4351 (#9550)
where the variable is checked to be set, when it should be the opposite.
Additionally it removes the use of the "-a" as suggested in the POSIX
especifications
The Open Group Base Specifications Issue 7, 2018 edition
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/test.html
"-a" is becoming obsolete and it may be removed in future versions.
> ...in cases where maximal portability is of concern, replace:
> test expr1 -a expr2
> with:
> test expr1 && test expr2
/cc @hauleth @josevalim @wojtekmach
=> Fix recently introduced bug in NO_COLOR feature

lib/mix/lib/mix/tasks/test.ex
In 6fb8efc6482d5c8526c507b91cd0982d221ec08c I accidentally
changed the title of the section
"OS Processes Partitioning" to
"Operating system process partitioning"
(notice "process" is in singular). Since "partitioning"
is the noun, and the rest are adjective, I think "process"
should be in singular.
This PR changes the reference to the section with the new title.
=> Correct title of section

lib/elixir/src/elixir_clauses.erl, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/kernel/expansion_test.exs, lib/elixir/test/elixir/kernel_test.exs
Avoid use of abbreviations in error messages
=> Use argument instead of arg in error messages

lib/elixir/lib/kernel.ex, lib/iex/test/iex/helpers_test.exs
The concept of "public functions" is used in other parts of the module, but it is never mentioned how these functions are created.
=> Explicitly mention that def and defmacro define public functions/macros

lib/elixir/lib/code.ex, lib/elixir/lib/kernel/parallel_compiler.ex, lib/elixir/test/elixir/kernel/parallel_compiler_test.exs
Some projects like Ecto can use this information to avoid
doing certain verifications, as they may lead to false
positives.
=> Return {:error, :unavalable} for ensure_compiled in a deadlock

lib/elixir/lib/file.ex, lib/elixir/lib/file/stat.ex, lib/elixir/lib/path.ex, lib/elixir/lib/port.ex, lib/elixir/lib/system.ex, lib/mix/lib/mix/local/installer.ex, lib/mix/lib/mix/utils.ex
Use:
- macOS, instead of MacOS X;
- Windows 7, instead of Win7
- Unix, instead of UNIX
- Unix-like operating system or Unix-like system, instead of just Unix
=> Style mention to operating systems

.cirrus.yml
The build button in the README file is red, due to test marked
with "allow_failures: true" not passing.
Adds "skip_notifications: true"
/cc @fertapric @ggcampinho
=> Make Cirrus build button green

lib/elixir/lib/stream.ex
After reading docs about Stream.resource/3 I had a feeling that they should be more hands-on.
So, I added a second example of usage - which should clearly demonstrate how it's working. And it's also a doctest :)
=> Add second example for Stream.resource/3

.cirrus.yml, Makefile
Improvements in .cirrus.yml and increase execution speed
- Make use of $CIRRUS_WORKING_DIR instead of spawning a new process with $(pwd).
- Only run the Elixir formatter, in the latest OTP version, in the same fashion of
CHECK_POSIX_COMPLIANT and CHECK_REPRODUCIBLE.
- TEST_FORMATTED environmetal variable added.
- move fast executing scripts, such as "dialyzer" to the top of the list.
- move "rm -rf .git" and "make compile" to the install script.
- Put each command their own named scripts (i.e., test_formatted_script, dialyzer_script, test_erlang_script, test_elixir_script, check_posix_compliant_script, check_reproducible_script).
- Split in the Windows task, the test_script into install_script and test_script, to mimic the scripts in the test_linux_task.
- Messages added on success or …
=> Improvements in .cirrus.yml and increase execution speed

lib/mix/lib/mix/tasks/release.ex, lib/mix/test/mix/tasks/release_test.exs
Ref #9567 
Now explicitly excludes `erts-x.x` dir and erlang libs when building a tar for a release that has `include_erts: false`.
Otherwise building the tar would fail with `:enoent`.
I'm not sure if this is the correct place to filter out the erlang libs. It feels like they should not be part of `release.applications` at all.
=> Fix release tar when include_erts is false

lib/elixir/lib/uri.ex
According to RFC 3986, section 2.3, add missing unreserved character.
The implementation already includes it.
=> Add missing unreserved character to URI document

lib/elixir/lib/config/provider.ex
It's not necessarily clear where this configuration goes and even though it's explained in the docs for `mix release`, I figured it doesn't hurt to have it here too.
=> Improve documentation for Config.Provider

lib/mix/lib/mix/dep/lock.ex
I think it is confusing and unnecessary to pass `opts` for `Code.string_to_quoted/2` to `Code.eval_quoted/3` as its second argument `binding`.
Removing the argument can save a bit of computation while keeping the intended functionality.
=> remove a confusing arg for Code.eval_quoted/3 in Mix.Dep.Lock

.cirrus.yml
It is warnings, not warning, in warnings_as_errors.
=> Fix ERLC_OPTS in .cirrus.yml

.cirrus.yml
It was accidentally introduced in 0a953d75fb2cbdc6f3d33040aa60738d85512a1f
=> Remove duplicate element in matrix in .cirrus.yml

.cirrus.yml
Add depends_on to Linux Development task in CI.
Initially shared by @fkorotkov
https://github.com/elixir-lang/elixir/pull/9585
Implemented now that Cirrus CI supports the `alias` field.
https://github.com/cirruslabs/cirrus-ci-docs/issues/527
Thank you @fkorotkov
Note: given the current setup, Linux Development doesn't
depend on Windows Stable, due do the latter taking way
longer than the rest. When new stable tasks are added,
they should depend on them, as in the case of the upcoming
FreeBSD task.
=> Deprioritize Linux Development tasks in CI

lib/elixir/test/elixir/registry_test.exs
- `unregistes` 👎 
- `unregisters` 👍
=> Fix typo on test name

lib/elixir/lib/enum.ex, lib/elixir/lib/stream.ex, lib/elixir/test/elixir/enum_test.exs
Replace the deprecated `exsplus` pseudorandom algorithm with `exrop`,
which has been the default algorithm since OTP 20.
Although the `exsplus` still works it has been superceded and therefore
we should not be encouraging users to use it with examples in doctests.
It makes sense to use the new default everywhere rather than change doctests only.
`exsss` is the new default algorithm which was introduced in OTP 22 (see erlang/otp@4a08841). So once OTP 22 is the lowest Erlang version we should switch to it.
> Undocumented (old) algorithms are deprecated but still implemented
> so old code relying on them will produce the same pseudo random sequences as before.
See http://erlang.org/doc/man/rand.html for more detailed documentation.
This post further clarifies the timing of the changes: …
=> Replace exsplus with exrop the OTP 20 default pseudorandom algorithm

lib/ex_unit/lib/ex_unit/assertions.ex, lib/ex_unit/lib/ex_unit/doc_test.ex, lib/ex_unit/test/ex_unit/doc_test_test.exs
This is related to this discussion on the mailing list: https://groups.google.com/forum/m/#!msg/elixir-lang-core/06HZwKG8E8k/KeDneED9AwAJ
This allows devs to now use proper pattern matching assertions in doctests, complete with the nice colored diff in the event of a failure. Here are some screenshots of how these tests look now when they fail (and with color on in the ExUnit config).
This is currently missing documentation, but I'll tack that commit on once folks think this behavior looks good so I know what to document 😉
=> Allow for match assertions in doctests

Makefile, README.md
It runs the formatter from the current elixir code,
and not from the locally or globally installed version.
=> Introduce "format" make target

lib/elixir/lib/io/ansi/docs.ex, lib/elixir/test/elixir/io/ansi/docs_test.exs
When this happend, the last "|" because the content of the second to
last column.
This happened for example with the table in the Base module
...
12 | M | 29 | d | 46 | u | 63    | _
13 | N | 30 | e | 47 | v | |     |
14 | O | 31 | f | 48 | w | (pad) | =
15 | P | 32 | g | 49 | x | |     |
16 | Q | 33 | h | 50 | y | |     |
=> Fix bug when last two columns are empty in IO.ANSI.Docs

lib/mix/lib/mix/dep.ex
Hi!
Status for `:divergedreq` is a 3-tuple.
https://github.com/elixir-lang/elixir/blob/1faf6787092d2822a2f294394aab48c7ed0c3e00/lib/mix/lib/mix/dep/converger.ex#L257
=> make Mix.Dep.diverged?/1 catch :divergedreq

.cirrus.yml
CIRRUS_CLONE_DEPTH is set to 50 (default value in Travis),
to avoid failure when auto-cancellation is enabled,
and a task needs to clone the git repo but a new commit has been added
to that branch. It will fail.
See this for more information
https://github.com/cirruslabs/cirrus-ci-docs/issues/532
More info:
https://stackoverflow.com/a/53857834
You can see a live example here: https://cirrus-ci.com/github/eksperimental/elixir/v6.0
Where the fist commit fails after second one is added. Third and fourth is after this fix.
/cc @fertapric
=> Do not shallow clone Git repo in CI

lib/elixir/pages/Syntax Reference.md
"Over the course of the next section" sounds more natural to me than "over the next section".  "Over the next _________" usually has a temporal expression to fill in the blank, like "over the next 3 days" or "over the summer".  "Throughout the next section" or "In the next section" would also make sense and flow naturally.
I'm also suggesting changing the "next" to "this" because the sentence is inside the section being referred to.  The next section would be the section _after_ "The Elixir AST".
And "many of Elixir syntax constructs" could be changed in a few different ways:
* "many ~of~ Elixir syntax constructs" (remove the "of")
* "many of Elixir's syntax constructs"
* "many of the Elixir syntax constructs"
I felt the first one was clearest in both text and speech. (Having two adjacent …
=> grammar suggestions for syntax reference

lib/ex_unit/lib/ex_unit/assertions.ex
Currently you must import `ExUnit.Assertions` to use it, but now we'll
be able to use it just by requiring it.
Resolves #9624
=> Use fully qualified function calls in macros

lib/elixir/lib/io/ansi/docs.ex, lib/elixir/test/elixir/io/ansi/docs_test.exs
This is supported by GFM (GitHub Flavored Markdown).
=> Allow heading separator in IO.ANSI.Docs to not to have spaces around "|"

lib/elixir/src/elixir_locals.erl, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/kernel/guard_test.exs
Somtimes one undefined function warning can hide others.
For example, in a function call like this:
foo(bar 1, 2)
The user may be expecting it to be called as:
foo(bar(1), 2)
But Elixir compiles it to:
foo(bar(1, 2))
In this case, the warning would be one of "undefined
function foo/1" or "undefined function bar/2", but they
are only "half truths". By showing all undefined function
warnings, we improve errors like above and it allows
users to see all undefined calls at once, when it would
otherwise require them to compile the code multiple times.
=> Print all undefined functions as warnings and then raise

lib/mix/lib/mix/dep/converger.ex, lib/mix/lib/mix/dep/loader.ex
The manager for a child dependency is set based on the following rules:
1. Set in dependency definition
2. From SCM, so that Hex dependencies of a rebar project can be compiled
with mix
3. From the parent dependency, used for rebar dependencies from git
4. Inferred from files in dependency (mix.exs, rebar.config, Makefile)
To reproduce the fixed issue, use the follow dependency definition:
```elixir
[
{:hackney, "~> 1.15.2"},
{:ssl_verify_fun, "~> 1.1.5", manager: :rebar3, override: true}
]
```
=> :manager from dependency definition should override SCM

lib/elixir/lib/uri.ex, lib/elixir/test/elixir/uri_test.exs
Old behavior:
```elixir
to_string(URI.parse("file:///path")) == "file:/path"
```
New behavior:
```elixir
to_string(URI.parse("file:///path")) == "file:///path"
```
=> Preserve slashes in URIs without authority

CHANGELOG.md
This feature was added to Elixir in v1.9.2
=> Remove {:from_app, :app} from 1.10 changelog

lib/iex/lib/iex.ex, lib/iex/lib/iex/config.ex, lib/iex/lib/iex/server.ex, lib/iex/test/iex/interaction_test.exs, lib/iex/test/test_helper.exs
Allow further customization of the IEx prompt.
It also introduces a new placeholder `%w` that is replaced by an empty string (whitespaces) of the same length than the main prompt. This placeholder is useful to write prompts that are copy-paste-able. This is how the default prompt looks like: 
```elixir
iex(1)> try do
...(1)>   :ok
...(1)> rescue
...(1)>   _ -> :error
...(1)> end
```
And this is how it would look like with `%w`:
```elixir
iex(1)> IEx.configure(default_prompt2: "%w")
:ok
iex(2)> try do
:ok
rescue
_ -> :error
end
:ok
```
This idea was inspired by [PostgreSQL's `PROMPT2` ](https://www.postgresql.org/docs/12/app-psql.html#APP-PSQL-PROMPTING), and the `%w` placeholder by an [upcoming feature in PostgreSQL 13](https://git.postgresql.org/gitweb/?p=postgresql.git;a=commitdiff;h=7f3 …
=> Proposal: Allow to configure secondary IEx prompt

lib/elixir/lib/list.ex, lib/elixir/lib/string.ex, lib/logger/lib/logger/formatter.ex
Unicode operates with "code points" and UTF-8 is an encoding which represents "code points" as bytes.
=> Docs: Replace UTF-8 code point with Unicode code point

Makefile
Use Elixir as a learning tool. Use long attributes to lower the barrier so users can
see the meaning of ExDoc command line attributes
Use double-quotes around attribute values in docs target in Makefile.
```
$ make docs
==> ex_doc (elixir)
bin/elixir ../ex_doc/bin/ex_doc "Elixir" "1.10.0-dev" "lib/elixir/ebin" --main "Kernel" --source-url "https://github.com/elixir-lang/elixir" --source-ref "bc4a5bd71be2a72fed02f7580bcbab4fa2625a35"  --output doc/elixir --canonical "https://hexdocs.pm/elixir/master/ " --homepage-url "https://elixir-lang.org/docs.html" --formatter "html" --config "lib/elixir/docs.exs"
==> ex_doc (eex)
bin/elixir ../ex_doc/bin/ex_doc "EEx" "1.10.0-dev" "lib/eex/ebin" --main "EEx" --source-url "https://github.com/elixir-lang/elixir" --source-ref …
```
=> Use long attributes in make docs target + Use double-quotes around attribute values

lib/elixir/lib/string.ex
We seem to use "pattern" to describe the thing that is doing the
matching, and "match" to describe the _found_ object. This is intended
to make this docs more consistent with the language found in the `Regex`
module.
Fixes #9659
=> "matched pattern" -> "match"

lib/elixir/src/elixir_import.erl, lib/elixir/test/elixir/kernel/errors_test.exs
Before:
iex(1)> a = [flatten: 1]; import List, only: a
** (CaseClauseError) no case clause matching: {:only, {:a, [version: 0, line: 1], nil}}
(elixir 1.10.0-dev) src/elixir_import.erl:10: :elixir_import.import/4
After:
iex(1)> a = [flatten: 1]; import List, only: a
** (CompileError) iex:1: invalid :only option for import, expected value to be an atom :functions, :macros, or a list literal, got: a
(elixir 1.10.0-dev) src/elixir_import.erl:22: :elixir_import.import/4
=> Improve error message on import/2

lib/elixir/lib/enum.ex
Optimised `Enum.find_value` docs to show a case that better differentiates it from the alternatives.
=> Update enum.ex docs for find_value

Makefile
One thing I've found myself wanting quite a lot when working on Elixir
is the ability to run single tests, or at least single test files,
easily with `make test_stdlib` or something. With this change this is
now possible - you can run `make test_stdlib TEST_FILES=macro_test.exs`
to just run that file, or `make test_ex_unit TEST_FILES=ex_unit/formatter_test.exs`.
=> Allow running a single test file from make

lib/mix/lib/mix/release.ex, lib/mix/test/mix/release_test.exs
This allows the release skip the creation of unnecessary runtime files during the execution of the clis
=> Set runtime config as false when not rebooting

lib/elixir/lib/config.ex
=> Fixes typo in Config docs

lib/mix/lib/mix/tasks/release.ex
This is actually a question in form of documentation patch 😀.
I was surprised that the docs of the `release` task forbid usage of `import_config/1` with a "MUST NOT" (it said `import_file`, but I guess it means `import_config`).
The `Config` module is unrelated to Mix and looking at the source code of `import_config/1` I see no technical reason it cannot run in releases. So my guess is that the intention of the docs was to rule out common Mix config use cases for `import_config/1` —probably written having the transition from `Mix.Config` in mind—, but perhaps the wording ended up being unnecessarily restrictive ruling out _any_ kind of invocation.
Then, I connected that suspicion with a need to avoid duplication between `config/config.exs` and `config/releases.exs`.
In my project …
=> Rework docs to allow calling `import_config/1` in releases

lib/elixir/lib/io/ansi/docs.ex, lib/elixir/test/elixir/io/ansi/docs_test.exs
This PR introduces markdown quote block handling in `IO.ANSI.Docs`, for blocks such as this:
```markdown
> first line of quote
> second line of __quote__
> third line of `quote`
```
Before this a quote was simply rendered as text which lead to the above quote looking like this:
\> first line of quote > second line of __quote__ > third line of `quote`
An example of this in the Elixir codebase can [be seen in `Access` (link to code)](https://github.com/elixir-lang/elixir/blob/055526057ac9992cc1df87441357c4e56d45235d/lib/elixir/lib/access.ex#L46-L55). Which got rendered like this in `iex`:
Instead of defining a specific quote style (such as `doc_quote`) - which clashes with inline styling of text - this solution instead renders the quote's content in an ASCII-art box. As such the quote from …
=> IO.ANSI.Docs - Properly render quote blocks

lib/elixir/lib/macro.ex, lib/elixir/src/elixir_parser.yrl, lib/elixir/test/elixir/code_test.exs, lib/elixir/test/elixir/macro_test.exs, lib/ex_unit/test/ex_unit/diff_test.exs
This makes it so we're always capturing delimiter metadata for sigils
instead of requiring the `token_metadata` option. This means that we can
now show the correct sigils in ExUnit diffs (and elsewhere) for code
examples.
=> Always capture delimiter metadata for sigils

lib/elixir/lib/enum.ex
Currently, enum join function adds empty strings to the list with reduce.
This fix adds a new condition to handle join with an empty string using Enum.map/2 - which is faster and consumes less memory (i guess 😃)
```elixir
```
Tested with Elixir 1.10.0-dev (ee758f9) (compiled with Erlang/OTP 21)
[Benchmarks script](https://gist.github.com/omohokcoj/0b142cc09eb62eb201e30fd225e1f2b3)
The same optimization could be added to Enum.map_join/3 - but the results were inconsistent:
```elixir
```
Probably because map_intersperse_list/3 recursive function from map_join is faster than Enum.map/2 in some cases (even though Enum.map/2 uses :lists.map for lists which uses body recursion inside as well 🤔).
=> Optimize Enum.join/2 with empty string

lib/elixir/lib/protocol.ex
The docs are on the module nowadays: https://hexdocs.pm/elixir/master/Protocol.html#module-consolidation
=> Point to the proper docs in the consolidation warning

lib/elixir/lib/path.ex, lib/elixir/test/elixir/path_test.exs
absname was incorrectly converting `//host/path` to `/host/path`
Added Windows-only Unit Tests for:
* Path.absname for UNC path (fixed here)
* Path.type for UNC path (was already correct, but not tested)
=> Fixed Path.absname to correctly handle UNC paths on Windows

lib/iex/lib/iex.ex
I'm accustomed to the use of `~` to represent the home directory of the person executing a command in a shell. Since that's apparently not the case when connecting to a node via `remote_console` it seems worth clarifying.
=> Clarify which home directory is referred to by `~` in `~/.iex.exs`.

lib/mix/lib/mix/release.ex
Fixes issue described in #9702 
I have no idea how to write a test for this case, any guidance?
=> Fix mix.release raising error when src is missing in erts_source

lib/elixir/lib/module/types.ex, lib/elixir/test/elixir/code_test.exs, lib/elixir/test/elixir/module/checker_test.exs
A type error may not always cause a clause to fail.
Related to #9700.
=> Improve type check error message

lib/mix/test/mix/tasks/escript_test.exs, lib/mix/test/test_helper.exs
If the machine/user git config is set to sign all commits/tags, these tests fail.
=> Don't GPG sign commits or tags in git tests

lib/ex_unit/lib/ex_unit/filters.ex, lib/ex_unit/test/ex_unit/filters_test.exs
Now if folks give line numbers that are 0 or less, we show a warning and
reject those bad line numbers.
Resolves #9727
=> Reject invalid line numbers in ExUnit filters

lib/ex_unit/lib/ex_unit/filters.ex, lib/ex_unit/test/ex_unit/filters_test.exs
If one call `mix test foo:arg` where `arg` are not natural numbers, we show a warning and reject those bad line numbers.
Extends https://github.com/elixir-lang/elixir/pull/9729 and further resolves #9727
=> Reject (even more) invalid line numbers in ExUnit filters

lib/elixir/src/elixir_parser.yrl, lib/elixir/test/elixir/code_test.exs
We need it there so we can retrieve it like this:
defmacro sigil_E({:<<>>, meta, [expr]}, []) do
options = [
line: __CALLER__.line + 1,
indentation: meta[:indentation] || 0
]
EEx.compile_string(expr, options)
end
=> Fix bug: move :indentation from sigil meta to binary meta

lib/elixir/lib/kernel.ex
I had no idea that the `def` macro supported these "implicit try" structures until Credo warned me about it.  This is related to https://github.com/elixir-lang/elixir/pull/5442
I just wanted a full working example in there.
=> Improves given example and adds "implicit try" for searches

lib/elixir/lib/task.ex, lib/elixir/test/elixir/task_test.exs
Adds a new function `Task.await_many` per [the proposal](https://groups.google.com/forum/#!topic/elixir-lang-core/9QQNIZMzWVE).
I'm still learning my way around the low-level process model, so it's possible I've made mistakes with the process management.
I also ended up doing some data shuffling in the interest of returning an ordered list but keeping a constant access time while constructing it. Maybe there's a better way to handle that, but if so it has escaped me.
=> Add Task.await_many

lib/elixir/lib/gen_event.ex, lib/logger/lib/logger.ex, lib/logger/lib/logger/backends/console.ex
This PR addresses the following:
- fleshes out examples when configuring custom backends
- includes examples of whitelisting metadata fields
- fixes broken link to `Logger.Backends.Console` docs (because it had `@moduledoc false`) : a brief summary was added.
- Corrects a couple small typos
=> Adds links and examples to docs around logging

lib/elixir/src/elixir_map.erl, lib/elixir/test/elixir/kernel/errors_test.exs, lib/elixir/test/elixir/kernel/warning_test.exs
In matches we will error:
%{a: :b, a: :c} = %{a: :b}
In normal expressions we will only warn:
%{a: :b, a: :c}
Closes https://github.com/elixir-lang/elixir/issues/9737.
=> Only error for duplicate map keys in matches

lib/elixir/lib/calendar.ex, lib/elixir/test/elixir/calendar_test.exs
This PR takes the functionality of `NimbleStrftime` and implements it as a function called `strftime` in the `Calendar` module.
closes #9503
=> turn NimbleStrftime into a Calendar function

lib/mix/lib/mix/tasks/release.ex, lib/mix/test/mix/tasks/release_test.exs
the default behaviour when starting a new mix project is to
`include_erts: true`.
if at some point you choose to `include_erts: false`, but have the ERTS
artifact hanging around from previous builds, it gets included in future
builds, therefore rendering `include_erts: false` broken when running on
systems that have built with `include_erts: true` for the same
environment.
`make_tar/1` currently always tries to include the ERTS artifact into
the archive, regardless of our `include_erts` configuration. this fails
in 1.9.4 if no previous artifact is present, and seems to be worked
around in the current implementation by simply ignoring source
directories that don't exist.
this adds a regression test for the behaviour by "simulating" an ERTS
leftover from a previous build.
this also adds …
=> ensure ERTS is not copied into release

CHANGELOG.md
`against` instead of `agaainst`
=> Typo fix in changelog

CHANGELOG.md, lib/ex_unit/lib/ex_unit/doc_test.ex, lib/ex_unit/test/ex_unit/doc_test_test.exs
Now users can pass tags as options to doctests.
=> Allow users to tag doctests with options

lib/elixir/lib/code.ex
The `local_function` event is a tuple with four elements, not five.
=> Fix docs for compiler tracing events

lib/elixir/lib/string.ex
Hexdocs for String.codepoints/1 has 5 examples. 
Fourth and fifth are different but in documentation the look the same. 
String.codepoints("é")
String.codepoints("é")
Unicode chars need to be escaped to distinguish them as intended in the source
String.codepoints("\u00e9")
String.codepoints("\u0065\u0301")
=> Escape Unicode chars in doucmentation for String codepoints/1

lib/elixir/lib/io.ex, lib/elixir/lib/supervisor.ex, lib/elixir/lib/system.ex
I only added it for `Supervisor.start_child/2` but I think this can be useful for almost all cases where we call `IO.warn/2` at runtime. It is also rare that we call `IO.warn/2` with a stacktrace which I also think would be an improvement.
Should I go through the other calls to `IO.warn/2` and do the same change?
=> Add IO.warn_once/3

lib/logger/lib/logger/handler.ex, lib/logger/lib/logger/utils.ex
Instead of generating new timestamp on each log message use existing `time` entry from `:logger.metadata()`.
Ref #9465
=> Use Erlang's logger timestamp

lib/elixir/test/elixir/kernel/parallel_compiler_test.exs, lib/elixir/test/elixir/kernel/tracers_test.exs, lib/elixir/test/elixir/module/types/infer_test.exs, lib/elixir/test/elixir/module/types/pattern_test.exs, lib/elixir/test/elixir/registry_test.exs, lib/elixir/test/elixir/task_test.exs, lib/elixir/test/elixir/typespec_test.exs, lib/ex_unit/lib/ex_unit/assertions.ex, lib/ex_unit/test/ex_unit/assertions_test.exs, lib/logger/test/logger/translator_test.exs, lib/mix/test/mix/release_test.exs, lib/mix/test/mix/tasks/release_test.exs
This needs to be reviewed carefully, in some tests the intention was to
ignore the variable but in some to match against an existing one. I
tried my best to figure out which was which.
There is one thing left which is a false positive for this test:
test "greets the world" do
assert <<len::8, _::size(len)-binary>> = <<3, "foo">>
end
Produces this:
warning: variable "len" is unused (if the variable is not meant to be used, prefix it with an underscore)
test/foo_test.exs:6: FooTest."test greets the world"/1
I wasn't able to fix this so any help appreciated!
=> Fix unused variable warnings

lib/logger/lib/logger/handler.ex, lib/logger/test/logger/handler_test.exs
Earlier it assumed that the return type is the same as in `report_cb/1` which is not true. `report_cb/1` returns format string and data while `report_cb/2` returns already formatted string.
=> Use correct return value from report_cb/2

lib/elixir/lib/version.ex, lib/elixir/test/elixir/version_test.exs
Pattern matching turns out to be faster than using matchspecs.
```elixir
string = "~> 1.2.3 and ~> 1.0"
requirement = Version.parse_requirement!(string)
compiled_requirement = Version.compile_requirement(requirement)
new_requirement = Version.new_requirement(string)
versions =
for major <- 1..10,
minor <- 1..10,
patch <- 1..10,
pre <- [[], ["dev"]],
do: %Version{major: major, minor: minor, patch: patch, pre: pre, build: nil}
Benchee.run(
%{
"old" => fn -> Enum.map(versions, &Version.match?(&1, requirement)) end,
"old & compiled" => fn -> Enum.map(versions, &Version.match?(&1, compiled_requirement)) end,
"new" => fn -> Enum.map(versions, &Version.new_match?(&1, new_requirement)) end
},
time: 10,
memory_time: 2
)
```
```
Operating System: macOS
CPU Information: Intel(R) Core(TM) i7-8850H …
```
=> Optimize Version.match?/2 and Version.compare/2

lib/mix/lib/mix/dep.ex, lib/mix/lib/mix/dep/fetcher.ex
The fix is to mark the dependency for compilation in the Fetcher (by
touching .fetch) so that the Loader wont read the version from the .app
file.
Fixes #9806.
=> Fix divergedreq error when update changes requirement and version

lib/elixir/lib/enum.ex
I was reading the docs for the `Enum` module, and noticed it defines an `acc() :: any()` type alias, which is used in the spec of `reduce/2`, but not in the one for `reduce/3`. I added it so that it's clearer which one of the reducer's arguments is the accumulator in `reduce/3` as well.
=> Use acc type alias in spec of Enum.reduce/3

lib/elixir/lib/system.ex
Unsetting variables using `nil` is different from Erlang's `false`, and this conversion does not appear to be documented anywhere
=> Clarify System.cmd/2 environment handling

lib/elixir/src/elixir_import.erl, lib/elixir/test/elixir/kernel/errors_test.exs
Before this patch we had:
iex> import Kernel, except: :macros
** (CompileError) iex:1: invalid :except option for import, expected value to be an atom :functions, :macros, or a list literal, got: :macros
(elixir 1.11.0-dev) src/elixir_import.erl:84: :elixir_import.calculate/6
(elixir 1.11.0-dev) src/elixir_import.erl:24: :elixir_import.import/4
=> Fix error message for import :except option

.gitattributes
In Git 2.25 there comes native support for Elixir definitions. That will
make `git diff --function-context` work properly. Additionally it makes
diff headers to contain name of enclosing function.
I hope that this will work in GitHub diffs as well.
=> Better Git diffs

lib/elixir/lib/map.ex
I have added a minor clarification in the map documentation with regards to accessing atom keys.
=> Clarification in the map documentation 

lib/elixir/lib/calendar/datetime.ex
The documentation stated that negative numbers down to -62167219200 are
supported, but it actually works down to -377705116800. 
Add doctests to illustrate the upper and lower boundaries.
Resolves #9839
=> Update `DateTime.from_unix` documentation

lib/mix/lib/mix/tasks/release.ex
Proposed doc change for issue #9832 
mix release for Windows 10 has dependency towards "Visual C++ Redistributable Packages for Visual Studio 2013"
Please bare with me since I'm not an experienced  GitHub user and contributor...
=> mix release for Windows 10 has dependency

lib/elixir/test/elixir/file_test.exs
IBM i PASE implements rename in a slightly weird way due to it
wrapping the native syscall. Expect this in the File module's
rename test when expecting an error. Fixes #9858.
This should be the behaviour documented (different from
AIX, which it's emulating, and strange for POSIX):
https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_74/apis/renameun.htm
=> Fix File module rename tests on PASE

lib/elixir/lib/calendar.ex
This improves the error message when we accidentally use the wrong order
of arguments.
Before
iex(1)> Calendar.strftime("%h", Time.utc_now())
** (FunctionClauseError) no function clause matching in Calendar.parse/4
The following arguments were given to Calendar.parse/4:
~T[12:26:18.591978]
"%h"
%{
abbreviated_day_of_week_names: #Function<4.80759775/1 in Calendar.options/1>,
abbreviated_month_names: #Function<3.80759775/1 in Calendar.options/1>,
am_pm_names: #Function<0.80759775/1 in Calendar.options/1>,
day_of_week_names: #Function<2.80759775/1 in Calendar.options/1>,
month_names: #Function<1.80759775/1 in Calendar.options/1>,
preferred_date: "%Y-%m-%d",
preferred_date_invoked: false,
preferred_datetime: "%Y-%m-%d %H:%M:%S",
preferred_datetime_invoked: false,
preferred_time: "%H:%M:%S", …
=> Add guards to Calendar.strftime/3

lib/elixir/lib/code.ex, lib/elixir/test/elixir/code_test.exs
This was the documented behaviour on 1.9 that was broken on v1.10: (version `git` is this branch)
$ cat a.ex
defmodule A, do: nil
$ for v in 1.9.4-otp-22 1.10.2-otp-22 git; do asdf local elixir $v && echo $v; elixir -e 'IO.inspect Code.compile_file("a.ex")'; done
1.9.4-otp-22
[{A, <<70, 79, ...>>}
1.10.2-otp-22
[{A, %{attributes: [], ...}]
git
[{A, <<70, 79, ...>>}
$ for v in 1.9.4-otp-22 1.10.2-otp-22 git; do asdf local elixir $v && echo $v; elixir -e 'IO.inspect Code.require_file("a.ex")'; done
1.9.4-otp-22
[{A, <<70, 79, ...>>}]
1.10.2-otp-22
[{A, %{attributes: [], ...}]
git
[{A, <<70, 79, ...>>}]
$ for v in 1.9.4-otp-22 1.10.2-otp-22 git; do asdf local elixir $v && echo $v; elixir -e 'IO.inspect Code.load_file("a.ex")'; done
1.9.4-otp-22
[{A, <<70, 79, ...>>}]
1.10.2-otp-22
warning: …
=> Return [{mod, bin}] from Code.compile_file/2, require_file/2, load_file/2

lib/elixir/lib/list/chars.ex
I thought the phrase "required to be implemented" was a little bit awkward. Here's an improvement IMHO!
=> Documentation wording improved for List.Chars moduledoc

lib/elixir/lib/supervisor/spec.ex
I thought the wording for this was a little bit awkward as well so I'm offering a little bit of polish!
=> Documentation wording improved for Supervisor.Spec moduledoc

.cirrus.yml
FreeBSD builds are failing because `pkg` refuses to install 
new packages that were built using more recent OS versions. 
The build does not update the packages to avoid that error.
=> Do not update packages on FreeBSD (CI)

lib/elixir/lib/string.ex
just some minor docs updates, specifically:
* unify description of pattern in split/3 and replace/4
* fix function references to correct arity
=> update String.replace/4 and split/3 docs

lib/elixir/lib/version.ex, lib/elixir/test/elixir/version_test.exs
String.Char.to_string/1 was failing due to unexpected`nil` value in `pre` field.
I did not know if tests were necessary or not, but it seems like added line will raise without a fix.
Related to #9885
=> Add default and enforce keys in Version struct

lib/elixir/src/elixir_erl_for.erl
Erlang comprehensions are only used when all generators are binary.
=> Remove list generator clause erlang comprehensions

lib/elixir/lib/io/ansi.ex
Unless you know exactly what ANSI codes are and how they work, the existing documentation page doesn't offer many clues to people who just want to colorize their terminal output.
This PR includes an example demonstrating how to use the functions.
=> Includes an example of how to use ANSI functions to format output

lib/elixir/lib/keyword.ex
This PR fixes a very minor grammatical/flow/typo issue in the `Keyword.ex` module. Honestly, this is an incredibly small change and it could probably be argued whether the change improves sentence flow for most readers. Thoughts?
I'm new to Elixir, but I'm excited and want to contribute any way I can.
=> docs: improves readability and grammatical flow

lib/mix/lib/mix/compilers/application_tracer.ex
OTP app directories contain version numbers and they were included in
the name:
Before:
warning: :ssl.versions/0 defined in application :ssl-9.6 is used by the current application but the current application does not directly depend on :ssl-9.6. To fix this, you must do one of:
1. If :ssl-9.6 is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs
(...)
After:
warning: :ssl.versions/0 defined in application :ssl is used by the current application but the current application does not directly depend on :ssl. To fix this, you must do one of:
1. If :ssl is part of Erlang/Elixir, you must include it under :extra_applications inside "def application" in your mix.exs
(...)
=> Improve app name detection by the application tracer

lib/elixir/lib/enum.ex, lib/elixir/pages/Operators.md
Currently, the [Operators page](https://hexdocs.pm/elixir/1.10.2/operators.html) includes a precedence table, plus information about comparison operators and customization/overriding. It really should have documentation for *all* of the operators, or at least pointers to that documentation (especially since the [Syntax reference page](https://hexdocs.pm/elixir/1.10.2/syntax-reference.html#operators) points you there for a "full reference"). This change fixes that situation.
I'm an Elixir newbie, so I may be wrong about some of the details here. Please point out anything I got wrong!
(Also: I noticed this when I was trying to learn the actual semantics and allowable usage of `in` and `not in`, and it took me a long time to finally find their documentation under Kernel / Guards. So I also …
=> Document operators on the Operators page

lib/elixir/lib/application.ex, lib/elixir/test/elixir/application_test.exs, lib/logger/lib/logger.ex
Typespecs already required an atom key but it was never enforced by
code. We're doing this because we eventually would like to support
passing a _path_ like:
Application.get_env(:myapp, [:key, :foo, :bar])
and this way we will be consistent with recently added
`Application.compile_env/3`.
Another way to solve this issue, not part of this PR, is deprecate
`get_env`, `fetch_env` and `fetch_env!` in favour of a new `env/3` &
`env!/2` or `runtime_env/3` & `runtime_env!/2`.  The downside is we won't
have the `fetch_` (non-raising) function but fwiw we don't have it for
`compile_env` either. (If we deprecate, it should be on a really long
cycle becasue they are so ubiquitous. But if we start printing
deprecation warnings in libraries it's probably for the better. ;-))
=> Deprecate non-atom keys on put_env, get_env, fetch_env*, delete_env

lib/elixir/lib/io/ansi/docs.ex, lib/elixir/test/elixir/io/ansi/docs_test.exs, lib/iex/lib/iex/introspection.ex, lib/iex/test/iex/helpers_test.exs, lib/mix/lib/mix/tasks/help.ex
Erlang/OTP 23 implements EEP 48, which allows us to show Erlang docs directly in IEx:
https://asciinema.org/a/1Kqwwkn0wMl0feePvWQwHe85G
This PR is tracking the development of said feature.
=> Show Erlang docs directly in the shell

lib/elixir/lib/code.ex
I accidentally inputted a string into Code.unrequire_files/1, obviously that failed. 
Somewhere deep in erlang it gave an argument error. This error didn't immediately tell me it was expecting a List instead of a String:
```
(stdlib 3.11.2) maps.erl:293: :maps.without("some_file.exs", %{"/Users/tomhoenderdos/.asdf/installs/elixir/1.10.2/bin/mix" => [], "some_file.exs" => true})
(elixir 1.10.2) src/elixir_code_server.erl:112: :elixir_code_server.handle_cast/2
(stdlib 3.11.2) gen_server.erl:637: :gen_server.try_dispatch/4
(stdlib 3.11.2) gen_server.erl:711: :gen_server.handle_msg/6
(stdlib 3.11.2) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:unrequire_files, "some_file.exs"}}
```
Trying to make it a bit better by adding a …
=> Code.unrequire_files/1: Adding a guard helps preventing wrong input

lib/elixir/lib/supervisor.ex
This is a small fix to a possible error I found in the supervisor docs.
=> Fix supervisor docs

lib/elixir/pages/naming-conventions.md
A typo in naming-conventions.md caused a broken link on hexdocs.pm
=> Fixed typo in naming conventions docs.

lib/elixir/lib/file.ex
I was surprised that `File.cd/1` affects the BEAM globally, instead of just changing the directory for the current process. This adds some documentation regarding this behavior.
=> Document that File.cd/1 affects the BEAM globally

lib/mix/lib/mix/task.compiler.ex
Earlier it failed Dialyzer tests as the example in docs returned value
different from one expected by callback definition.
=> Make spec of `c:run/1` match the documentation

.cirrus.yml
currently [cirrus fails all FreeBSD tests](https://github.com/elixir-lang/elixir/pull/9942/checks?check_run_id=590253510) with this:
```
pkg install -y erlang git gmake
Updating FreeBSD repository catalogue...
Fetching meta.txz: . done
pkg: repository meta /var/db/pkg/FreeBSD.meta has wrong version 2
repository FreeBSD has no meta file, using default settings
Fetching packagesite.txz: .......... done
pkg: repository meta /var/db/pkg/FreeBSD.meta has wrong version 2
pkg: Repository FreeBSD load error: meta cannot be loaded No error: 0
Unable to open created repository FreeBSD
Unable to update repository FreeBSD
Error updating repositories!
Exit status: 3
```
this is because FreeBSD 12.0 is obsolete and the official package mirrors
don't have erlang etc available anymore. We need to move to …
=> build: update to a supported FreeBSD version

lib/elixir/lib/code.ex
There is no `module` in `{:local_function, meta, name, arity}` and `{:local_macro, meta, name, arity}` tuples.
=> Remove refs to module in local_function and local_macro events docs

lib/iex/lib/iex/broker.ex
Since `@name` is assigned IEx.Broker, I figured using the `__MODULE__` alias would make it dynamic
=> use __MODULE__ alias

lib/elixir/lib/module.ex, lib/mix/lib/mix/compilers/elixir.ex, lib/mix/lib/mix/tasks/compile.elixir.ex, lib/mix/test/mix/tasks/compile.elixir_test.exs
This is inspired by `mix compile.phoenix` which turns out wasn't really Phoenix specific :)
https://github.com/phoenixframework/phoenix/blob/v1.4.16/lib/mix/tasks/compile.phoenix.ex
=> Add `__mix_recompile__?/0` callback

lib/elixir/pages/patterns-and-guards.md
The return value in the code example is the opposite of what the code would actually return, making the example misleading.
=> Fix erroneous code snippet in documentation

lib/elixir/src/elixir_compiler.erl, lib/elixir/src/elixir_erl.erl, lib/elixir/src/elixir_erl_pass.erl
- Use erl_anno:new instead of integers for line numbers when generating erlang AST (fixes #9948 )
- Remove unnecessary ?ann macro call
=> Fix dialyzer errors caused by erl_anno:anno type being opaque

lib/mix/lib/mix/tasks/cmd.ex
- `mix cmd echo pwd` would only print literally `"pwd"` for each child app
- `mix cmd pwd` would print each child app's path
=> Fix `mix cmd` examples in its moduledoc

lib/iex/lib/iex.ex
This fixes a few dialyzer errors, e.g. in IEx.Introspection.open/1
or in IEx.Helpers.print_pane/1
=> Update type spec for IEx.color/2 to indicate that it works with iodata

Makefile
This commit fixes many "Unknown function" and "Unknown type" dialyzer errors
visible when generating the dialyzer PLT and when running dialyzer analysis.
Because all "unknown" erros during PLT generation have been fixed, it also
adds an additional -Wunknown flag to PLT generation command, which will
cause it to fail when any of such errors appear again during this step.
Errors fixed during building PLT:
```
Unknown functions:
crypto:block_decrypt/4
crypto:block_encrypt/4
crypto:compute_key/4
crypto:crypto_one_time_aead/7
crypto:ec_curves/0
crypto:exor/2
crypto:generate_key/2
crypto:hash/2
crypto:hmac/3
crypto:mod_pow/3
crypto:private_decrypt/4
crypto:private_encrypt/4
crypto:sign/4
crypto:start/0
crypto:stream_decrypt/2
crypto:stream_encrypt/2
crypto:stream_init/2 …
```
=> Include all relevant OTP apps when building dialyzer PLT

lib/elixir/lib/dynamic_supervisor.ex, lib/elixir/lib/process.ex, lib/elixir/lib/supervisor.ex, lib/elixir/lib/task/supervisor.ex, lib/mix/lib/mix/release.ex
This commit fixes the following errors from dialyzer analysis:
```
Unknown types:
beam_lib:chnk_rsn/0
erlang:message_queue_data/0
supervisor:modules/0
supervisor:restart/0
supervisor:shutdown/0
```
I'm not sure if this is the right way to fix these. In my view, using unexported types is similar to accessing private APIs. Maybe there is no reason for these types not to be exported and this should be fixed upstream by exporting them? Or maybe this is a hint that Elixir is indeed accessing "private" APIs in some of these cases? Or maybe this approach is fine?
=> Inline types not exported from their erlang modules

lib/elixir/lib/calendar.ex
The - padding is already handled at line 526
This was suggested by dialyzer :)
=> Remove redundant pad handling in Calendar.parse_modifiers

lib/mix/lib/mix/tasks/deps.unlock.ex
This could be `:maps.filter(fn ... not in ..., lock)` instead but I don't know if the micro optimization is worth it
=> Call Mix.Dep.Lock.write/1 with a map in Mix.Tasks.Deps.Unlock.run/1

lib/elixir/lib/task.ex
Document that [Task.async_stream/5](https://hexdocs.pm/elixir/Task.html#async_stream/5) accepts `timeout: :infinity` option.
=> Document Task.async_stream/5 infinity timeout

lib/mix/lib/mix/local/installer.ex
The function can also return an {:error, message} tuple when parsing is not successful
=> Fix spec for Mix.Local.Installer.parse_args/2

lib/mix/lib/mix/tasks/escript.build.ex
When no name was provided, project :app name is being used
=> Remove error handling of empty escript name in Mix.Tasks.Escript.Build.escriptize/2

lib/mix/lib/mix/tasks/archive.install.ex
This function call is working when cwd is a binary right now, but it is documented that cwd should be a charlist
=> Call :zip.extract/2 with cwd option as charlist

lib/ex_unit/lib/ex_unit/formatter.ex
The formatter argument is a function so never should be equal to :expr
=> Remove redundant clause in ExUnit.Formatter.format_sides/6

lib/elixir/lib/system.ex
According to erlang documentation, :init.get_argument/1 returns :error when no value is associated with the flag: http://erlang.org/doc/man/init.html
=> Fix handling of empty user home flag in System.user_home/0

lib/mix/lib/mix/project_stack.ex
This function is getting called with :unset in Mix.Tasks.Compile.App.load_compile_env/1
=> Fix spec for Mix.ProjectStack.compile_env/1

lib/elixir/lib/code.ex, lib/elixir/src/elixir_compiler.erl
Before this patch, we could have slightly different
AST while compiling modules in parallel, depending
if modules were recompiled or not. Now we always
recompile Kernel before compiling the whole stdlib.
We used this opportunity to simplify bootstrap by
breaking it two steps. The first step is the minimal
necessary to compile Kernel itself. The second step
contains the whole compiler.
Closes #10000.
=> Recompile Kernel before bootstrapping stdlib

lib/elixir/lib/string.ex, lib/elixir/test/elixir/string_test.exs
`String.titlecase/2` is similar to `String.capitalize/2` but it doesn't downcase the rest of the string.
Closes https://github.com/elixir-lang/elixir/issues/9999
=> Add String.titlecase/2

lib/elixir/lib/config/provider.ex, lib/elixir/test/elixir/config/provider_test.exs, lib/mix/lib/mix/release.ex, lib/mix/test/fixtures/release_test/config/config.exs, lib/mix/test/mix/release_test.exs, lib/mix/test/mix/tasks/release_test.exs
=> Support proper encoding in releases config

lib/mix/lib/mix/config.ex
I have added a line to add a link to the `Config` and `Config.Reader` module inside the Elixir library. I also added the Elixir namespace inside the links, to make it explicit it is in another library, although it will be the standard library. I know that it is not the "normal" style for linking, but it caused some confusion on my end to find out that it moved completely to another library.
=> Improve Mix.Config docs to point to the Elixir library for Config and Config.Reader

lib/elixir/lib/calendar.ex
There is a good question here: https://stackoverflow.com/questions/61566269/utc-offset-in-elixir-return-incorrect-offset-for-time-zones
Both `utc_offset` and `std_offset` are used to get wall time. Some users may look at `utc_offset` and think that this is the total offset from UTC to get wall time even in summer time.
=> Improve documentation for utc_offset and std_offset fields.

lib/mix/lib/mix/release.ex, lib/mix/test/mix/release_test.exs
I made a spike in my job to use the built-in mix releases instead of distillery.
The release was built fine but it broke when I tried to boot it because a different version of cowboy was packed into it.
The fix was rather easy, I just removed the system package, which was mistakenly installed, from our base Docker image.
Finding the problem was not so straightforward for me though. So, I am suggesting in this PR some way to prevent this to happen and have a message early on about the problem. What do you think?
PS. I am not sure how to test such thing.
=> Load app from dependencies path when it is a project dependency

lib/mix/lib/mix/tasks/release.ex, lib/mix/lib/mix/tasks/release.init.ex
I am distributing a package of our app, and to keep it free from
sensitive information, I generate an OS package from the
release tarball, without embedded tokens & passwords.
The cookie, vm.args, and sys.config are provided separately
at runtime, via dev-ops tools.
For `COOKIE` & `vm.args`, this is already possible, but not for
`sys.config`.
I'd like to be able to override `RELEASE_SYS_CONFIG` if
already set, the same as `RELEASE_VM_ARGS` works today.
This PR seems sufficient for UNIX but my windows patch
doesn't handle dynamic `RUNTIME_CONFIG=true`, I'm
not familiar anymore with windows batch scripting, if
somebody could advise that would be great.
=> enable overriding sys.config location via env var

lib/elixir/lib/registry.ex
Per the docs for [Registry.select/2](https://hexdocs.pm/elixir/Registry.html#select/2) you can provide a map for the body part of the spec, currently body is defined as `[atom | tuple]`, I've changed this now to `[term]` to match the erlang match_spec Result used by :ets.select/2
Thinking that perhaps `@type guard` should also be changed to term to match the erlang match_spec as well though?
=> Adjust @type body for Registry to match erlang ets match_spec Result

lib/elixir/lib/enum.ex
This is a proposed refactor of `Enum.with_index/2` with the goal of improving performance so that it is faster and consumes less memory.
I've created a small repository that benchmarks the current implementation with the new one [here](https://github.com/andersonmcook/with_index).
I've included my own benchmarks in the README, but would love if someone could replicate or disprove my results.
- List: The updated function is approximately twice as fast and uses half the memory.
- Map: The updated function is approximately twice as fast and uses half the memory.
- MapSet: The updated function is moderately faster and uses moderately less memory.
- Range: The updated function is moderately faster and uses moderately less memory.
- Stream: The updated function is minimally faster and uses …
=> Improve performance of Enum.with_index/2

lib/mix/test/mix/rebar_test.exs
The PR is going to fix the bug which makes the Mix tests use only rebar3 when they should test Mix with both rebar and rebar3.
How to check that the bug really exists.
* Remove `./lib/mix/test/fixtures/rebar3`.
* Apply the patch (see below), removing the tests related to rebar3.
* Run the tests and `gets and compiles dependencies for Rebar` should fail.
Patch:
```
--- elixir-lang-1.9.1.dfsg.orig/lib/mix/test/mix/rebar_test.exs
+++ elixir-lang-1.9.1.dfsg/lib/mix/test/mix/rebar_test.exs
@@ -33,39 +33,6 @@ defmodule Mix.RebarTest do
end
end
-  defmodule Rebar3AsDep do
-    def project do
-      [
-        app: :rebar_as_dep,
-        version: "0.1.0",
-        deps: [
-          {
-            :rebar_dep,
-            path: MixTest.Case.tmp_path("rebar_dep"),
-            app: false,
- …
```
=> Test not only rebar3

lib/elixir/lib/system.ex
Starting with OTP 23 erlang:get_stacktrace/0 will always return an
empty list. The function will be completely removed in OTP 24 - we
should plan appropriately for that.
=> Add note that System.stacktrace/0 will always return an empty list

lib/mix/lib/mix.ex, lib/mix/lib/mix/utils.ex, lib/mix/test/mix/utils_test.exs
Unfortunately we cannot support XDG out of the box due to backwards compatibility. Today we already allow you to opt-in but it requires setting multiple environment variables. This makes the opt-in API much simpler.
We had lengthy previous discussions on this topic and on backwards compatibility, I am not planning to rehash those points here. [See this comment for a summary](https://github.com/elixir-lang/elixir/pull/9942#discussion_r409569099). For the complete discussion, search for XDG in previous issues and PRs.
If you would like to give feedback in this issue, please let me know which option you prefer:
1. This PR
2. Keep things as is (no changes)
3. Remove XDG support since we can't do it automatically
If the conversation derails, as it has happened in the past, then I will make an …
=> Introduce MIX_XDG

lib/mix/lib/mix/tasks/deps.compile.ex
rebar3 as of 3.13.2 now supports a --output directory option which allows mix going forward to use said option and put build artifacts in _build which should result and less rebuilding of artifacts and/or better caching of artifacts. Details here: https://github.com/erlang/rebar3/pull/2237
In order to make use of said feature we must put a variable in the system's environment that shall hold the desired output path. rebar3 will recognize said environment variable going forward starting at version 3.14 (yet to be released).
- Updated Mix.Tasks.Deps.Compile to put REBAR_BARE_COMPILER_OUTPUT_DIR in system env with the dependency path as the value for use by rebar3.
=> Add support for new rebar3 output dir option

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
This should keep backwards compatibility as it relies on the arity of
the sorter to determine if it is a empty_fallback or a sorter.
=> Allow a sorting function on Enum.min_max_by/3,4

lib/elixir/lib/kernel.ex
I thought it would be helpful to make it clear what the arguments to `update_in/3` should be. In particular that the given function receives the value and is expected to return the new value and not a tuple like `get_and_update_in`.
=> Document data and fun arguments to `update_in/3`

lib/elixir/docs.exs
Rendering it gives us syntax highlighting, auto-linking, sidebar sections, and more. See how v1.10 changelog would be rendered: http://wojtekmach.pl/otp_docs/elixir/elixir/changelog.html
We could duplicate this changelog to mix/, eex/, etc but I opted not to.
=> Add CHANGELOG.md to docs

lib/mix/lib/mix/utils.ex, lib/mix/test/mix/utils_test.exs
unix is not one of the documented options and will get interpreted as linux
=> Pass a valid os option to filename:basedir/3

lib/elixir/lib/kernel/parallel_compiler.ex, lib/mix/test/mix/tasks/compile_test.exs
I've noticed when an exception is raised inside of a macro, the resulting compiler diagnostic has `position: nil`. You can reproduce this issue by invoking the `from` macro from Ecto.Query like so:
```
def list_products do
from(p in Product, order_whoops: p.id) |> Repo.all()
end
```
I tracked it down and found that when I `raise "error"` in a macro, the compiler receives a :file_error with the following arguments:
```
file: “/path/to/lib/b.ex”
kind: :error
reason: %RuntimeError{message: “error”}
stack: [
{A, :custom_macro, 0, [file: ‘expanding macro’]},
{B, :__MODULE__, 0, [file: ‘lib/b.ex’, line: 3]},
...
]
```
There was no function clause for get_line that matched that particular stacktrace. Adding one fixes this issue.
=> Report the correct line number when raising inside of a macro

lib/elixir/lib/string.ex, lib/elixir/test/elixir/string_test.exs
1. Added `:nfkd` and `:nfkc` normalisation forms to `String.normalize/2`
2. Added two doctests which illustrate non-roundtrip behaviour
3. Added warning that these normalisation forms do not round-trip
4. Updated the description with the 2 additional Erlang functions referenced
I did not add any unit tests since that would now seem to be testing Erlang's implementation - let me know if you would like some additional tests added however.
=> Add :nfkd and :nfkc forms to String.normalize/2

lib/elixir/lib/enum.ex
#10033 added a third argument sorter_or_empty_fallback with a default value. To not break compatibility with existing code it also added a function clause that checks third argument's type with a guard and calls Enum.min_max_by/4 with appropriate arguments.
This PR fixes the following dialyzer warnings:
- In user code, e.g. `Enum.min_max_by([1, 2, 3], fn x -> x end, fn -> raise(Enum.EmptyError) end)`:
```
The function call will not succeed.
Enum.min_max_by([1, 2, 3], (_ -> any()), (() -> none()))
will never return since it differs in arguments with
positions 3rd from the success typing arguments:
(any(), (_ -> any()), atom() | (_, _ -> boolean()))
````
- When running dialyzer on Elixir itself:
```
Invalid type specification for function 'Elixir.Enum':min_max_by/3. The success typing is …
```
=> Update Enum.min_max_by/3 spec after #10033

lib/elixir/lib/enum.ex
Followup after #10049
Most importantly, I added specs for function clauses with `(element, element -> boolean) | module()`.
I moved the compatibility clause for `Enum.min_max_by/3` to before documentation with @doc false, just like it is done for other related functions.
I think because of the `@doc false` the specs (both "old" and "new") are not showing up in documentation but I think it's fine (full arity spec is showing up).
I moved the specs a bit. I think this makes it clearer which specs are related to old (possibly deprecated in the future?) function clauses. If it is preferred to keep all specs in one place I can move them back.
=> Correct the specs for Enum aggregate functions

lib/mix/lib/mix/tasks/new.ex, lib/mix/test/mix/tasks/new_test.exs
Whenever I create a new project with `mix new app_name --sup`, https://github.com/akoutmos/doctor validation will fail since the generated `application.ex` file doesn't have correct documentation. Not to say that my personal library should dictate how Elixir core does things....but more so I just noticed that for correctness, the generated `application.ex` file should annotate which functions satisfy the `Application` behaviour.
Thanks in advance for any feedback :)
=> Added @impl to application.ex generated by mix new

lib/mix/lib/mix.ex
Users of Nerves have been using this for some time now, I would consider `Mix.target` necessary and not experimental. 😄
=> Update docs for Mix.target to remove experimental

lib/ex_unit/lib/ex_unit/doc_test.ex, lib/ex_unit/test/ex_unit/doc_test_test.exs
This PR allows generating tests from example codes in `@typedoc` with doctest, related this topic:
https://elixirforum.com/t/doctest-with-typedoc/31772
=> Doctest to generate tests also from @typedoc

lib/elixir/pages/patterns-and-guards.md
While taking a deep-dive in the Elixir and Erlang documentation of guard tests for my upcoming presentation on guards, I found a small couple of inconsistencies that this PR clears up.
Conference Driven Development! :upside_down_face: 
---
This PR improves the 'patterns-and-guards' documentation page to:
- Include `receive` in the list of constructs that accept guards
- Fix in-doc links to the mentioned functions.
=> Improves 'patterns-and-guards' documentation page

lib/elixir/lib/module.ex
In other places in the `Module` documentation this is referenced, but it's a bit hard to find when you're in this section, and this section's documentation on these attribute is a bit limited.
=> Link to Typespec docs from Module documentation

lib/mix/lib/mix/generator.ex
The documentation for `Mix.Generator.copy_file` and `Mix.Generator.copy_template` had examples that do not match their function specs.
Related: should these examples be run as doctests?
=> docs corrections for Mix.Generator.copy_file, Mix.Generator.copy_template

lib/mix/lib/mix/generator.ex
Reverts a bad docs change that removed a necessary argument from the code example for `Mix.Generator.copy_template`.
I took `[project_path: path]` to be the `opts` parameter, but it was actually `assigns`. 😳
=> undo change removing assigns from Mix.Generator.copy_template docs

lib/mix/lib/mix/tasks/deps.unlock.ex, lib/mix/test/mix/tasks/deps_test.exs
Before this patch, we only printed which deps got unlocked when
`--filter` option was used. Now we do it everywhere else, that is
when passing specific apps to unlock and when using `--unused`.
=> Print which deps got unlocked

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel/lexical_tracker_test.exs
The dependency doesn't seem needed in this case.
We go through extra hoops to maintain backwards compatibility,
`opts` does not have to be a compile-time list and :to does not have
to be a literal.
An easy way to see this optimization is:
defmodule A do
defdelegate f(), to: B
end
defmodule B do
def f() do
:ok
end
end
$ touch lib/b.ex && mix compile --verbose
Compiling 1 file (.ex)
Compiled lib/b.ex
vs:
defmodule A do
opts = [to: B]
defdelegate f(), opts
end
defmodule B do
def f() do
:ok
end
end
$ touch lib/b.ex && mix compile --verbose
Compiling 2 files (.ex)
Compiled lib/b.ex
Compiled lib/a.ex
=> Don't add compile-time dependency on defdelegate

lib/elixir/lib/calendar/naive_datetime.ex, lib/elixir/lib/calendar/time.ex
=> Returning microseconds on `NaiveDateTime.to_gregorian_seconds`

lib/elixir/src/elixir_locals.erl, lib/elixir/test/elixir/kernel/warning_test.exs
Refs #10095 
I took the liberty of also rewording the other warnings about arguments with default values, so they all look alike.
=> Rewording the default arguments warnings

.cirrus.yml
The most important change is that since v1.10.3 supports Erlang/OTP 23, it is added to the CI
=> Update .cirrus.yml to latest Erlang/OTP versions and changes from master

lib/elixir/lib/task/supervised.ex, lib/logger/test/logger/translator_test.exs
Discussed with @josevalim a bit, and this is to be able to get callers from Logger metadata
Things I'm not sure on: Whether new test should be written, or if there are other modules (GenServer?) that could also do this.
=> include callers in translated Logger metadata for Task

lib/elixir/lib/system.ex
the documentation fix corrects the use of "from" and the ~plug~ plus suffix.
=> Correct doc, add spec and update TODO comment in System.stacktrace/0

lib/elixir/lib/kernel/special_forms.ex
I happened to stumble across this today.
=> Fixes tiny typo (missing article) in `Kernel.SpecialForms.import` documentation

lib/elixir/test/elixir/inspect/algebra_test.exs
This looks like a copy-paste error. This test is supposed to test the `:reset` implementation, the previous one covers `:cursor` already.
=> Fix bug in Inspect.AlgebraTest

lib/mix/lib/mix/release.ex, lib/mix/lib/mix/tasks/escript.build.ex, lib/mix/test/mix/release_test.exs
This PR attempts to add a bit more granular control over what gets stripped from the BEAM files, when the strip_beams option is set to true in the mix release options.
For now it allows passing a couple of exceptions in a list, namely :docs and :debug_info. The exceptions passed in the options will *not* get stripped from the BEAM files.
For reference: https://github.com/elixir-lang/elixir/issues/10122
Be gentle on me, it's my first one :)
=> Adding support for being more granular when stripping beam files

lib/elixir/pages/patterns-and-guards.md
MD012 Multiple consecutive blank lines.
https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
=> Remove unneeded blank lines from Markdown.

lib/elixir/pages/patterns-and-guards.md
MD009 Trailing spaces
https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
=> Remove trailing spaces from Markdown.

lib/mix/lib/mix/scm/git.ex, lib/mix/test/mix/scm/git_test.exs
Adds reference information (tag, branch, commit hash) to the mix deps task when fetching dependencies from git.
Currently when getting or updating libs from git sources:
```
* Updating open_api_spex (https://github.com/open-api-spex/open_api_spex.git)
* Updating stripity_stripe (https://github.com/code-corps/stripity_stripe.git)
* Updating elixir_utils (git@github.com:DroverLtd/elixir_utils.git)
```
With this PR:
```
* Updating open_api_spex (https://github.com/open-api-spex/open_api_spex.git - origin/master)
* Updating stripity_stripe (https://github.com/code-corps/stripity_stripe.git - origin/master)
* Updating elixir_utils (git@github.com:DroverLtd/elixir_utils.git - 1.2.3)
```
The code can probably be much more optimised, suggestions welcomed :)
=> Show ref information when getting or updating mix dependencies from git sources

lib/elixir/lib/module/types/infer.ex
Avoids building large chains of variable references by always resolving
to the last variable.
Instead of building a chain of references:
var1 -> var2 -> ... -> varN -> type()
We now create a direction reference:
var1 -> varN -> type()
This change vastly improves the speed of checking functions with high
complexity and many variables.
=> Optimize variable unification

lib/mix/lib/mix/scm/git.ex, lib/mix/test/mix/scm/git_test.exs
ok so let's consider I'm doing things ahem, the _wrong_ _way_ and don't have proper ssh keys set up for a private github repository. So instead of doing things the right way I slap something silly into my mix.exs file such as
```elixir
{ :my_repo, git: "https://USERNAME:#{System.get_env("GITHUB_TOKEN")}@github.com/gregors/my_repo.git }
```
Now where would I get such an idea? Maybe reading old things [like this](https://stephenbussey.com/2018/02/05/sourcing-libraries-from-private-github.html)
Now if one were going to do this, you end up seeing logs being displayed such as 
```bash
Getting apex (https://USERNAME:password@github.com/gregors/my_repo.git)
```
That's no good, we don't want our username and password ending up in log files (even if it does end up in our lock file ahem)
I know …
=> redact username/password in mix output log

lib/iex/lib/iex/pry.ex
Fixes the following error inside pry:
(stdlib 3.13) :ets.member(Mix.Compilers.ApplicationTracer, IEx.Helpers)
(mix 1.11.0-dev) lib/mix/compilers/application_tracer.ex:31: Mix.Compilers.ApplicationTracer.trace/2
(elixir 1.11.0-dev) src/elixir_env.erl:36: :elixir_env."-trace/2-lc$^0/1-0-"/3
(elixir 1.11.0-dev) src/elixir_env.erl:36: :elixir_env.trace/2
(elixir 1.11.0-dev) src/elixir_dispatch.erl:161: :elixir_dispatch.do_expand_import/6
(elixir 1.11.0-dev) src/elixir_dispatch.erl:91: :elixir_dispatch.dispatch_import/5
=> Remove tracers before prying

CHANGELOG.md, lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel_test.exs
@josevalim posted [#66](https://elixirforum.com/t/discussion-incorporating-erlang-otp-21-map-guards-in-elixir/14816/66?u=eiji) on forum at `Mar 23, 9:13 AM`:
> (…) is_exception was not implemented but a PR is welcome.
cc @josevalim
=> is_exception/1 guard

lib/elixir/lib/calendar.ex, lib/elixir/lib/calendar/date.ex, lib/elixir/lib/calendar/iso.ex, lib/elixir/test/elixir/calendar/date_test.exs, lib/elixir/test/elixir/calendar/holocene.exs
This augments the Calendar behaviour by adding
a new function, `c:Calendar.day_of_week/4` which
supports a `starting_on` value with defaults and
calendar specific semantics.
=> Add Date.day_of_week/2, beginning_of_week/2, and end_of_week/2

lib/elixir/lib/calendar/time.ex
This enhances time unit aware functions in the `Time` module so that they can operate on `:hour` and `:minute`, along with standard `System.time_unit/0` values. This eliminates the need to convert all values to seconds, which allows more expressive time manipulation.
Along with changes to `Time.add/3` and `Time.diff/3`, this adds a new extended `time_unit` type to `Time`.
=> Add support for :hour and :minute time units

lib/elixir/test/elixir/access_test.exs
These tests actually use `get_and_update_in/3` and `pop_in/2`.
I removed the arities, rather than correcting them, since it seems like unnecessary detail here.
Also, the `get_in` test just above does not mention arity.
=> Remove incorrect arities in test descriptions

lib/ex_unit/lib/ex_unit/failures_manifest.ex
Run `make format` to fix failing build:
(I'm sorry if this is overkill to open a PR for this, I don't have much experience contributing on open source :bow:)
=> Fix ExUnit format

lib/elixir/src/elixir_env.erl, lib/elixir/test/elixir/kernel/warning_test.exs
=> Warn if a variable that looks like a compiler variable is unused

.cirrus.yml, .github/workflows/ci.yml
Here are some benefits of moving to GitHub
Actions:
* The Docker image `fertapric/elixir-ci:*` is no longer needed.
* Build times has been reduced ~50%: current times are ~20 mins, and with GitHub Actions ~10 mins.
* Jobs seem to be scheduled faster: a few seconds compared to minutes.
* Running instances seem more stable: I have not experienced `ExUnit.TimeoutError` errors nor memory allocation issues.
=> Use GitHub Actions for Windows CI

lib/mix/lib/mix.ex, lib/mix/lib/mix/project.ex, lib/mix/test/mix/project_test.exs
The goal is to make it easier to change the path of the `_build` directory.
Mix currently supports `MIX_BUILD_PATH` to customize where the build artifacts are written to. One thing to keep in mind is that `MIX_BUILD_PATH` expects the final path and it's up to the user to use different paths per environment. `MIX_BUILD_PATH` is not equivalent to the `_build` directory, it's equivalent to the `_build/<env>` directory.
Mix also allows to configure the path of the `_build` directory using the `:build_path` configuration of `Mix.Project`, but that is meant to be used by umbrella applications:
> In a non-umbrella context, configuring this has undesirable side-effects (such as skipping some compiler checks) and should be avoided.
https://github.com/elixir-lang/elixir/blob/295f4a705230f297b03d77c7 …
=> Add MIX_BUILD_ROOT to config the "_build" dir

lib/elixir/src/elixir_compiler.erl
If there is a compile error, `Kernel.ParallelCompiler` raises `** (UndefinedFunctionError) function List.Chars.to_charlist/1 is undefined (module List.Chars is not available)`.
Here is an example: https://github.com/fertapric/elixir/runs/875212343
=> Add List.Chars to bootstrap modules

lib/elixir/pages/patterns-and-guards.md
This PR fixes a tiny markdown rendering issue present on the Patterns and Guards -page, under the "Note that the match operator (=) does not support guards:" line.
Currently the docs are rendered with the markdown code block syntax being visible (as seen in both https://hexdocs.pm/elixir/master/patterns-and-guards.html and the source file itself, https://github.com/elixir-lang/elixir/blob/master/lib/elixir/pages/patterns-and-guards.md). 
The small change of whitespace in this PR allows the markdown to be rendered correctly.
Sanity-checked by rebuilding docs with `make docs` locally.
=> Fix markdown code block rendering on Patterns and Guards -page

Makefile
The comments would add space to the CANONICAL variable,
redering the link like
`<link rel="canonical" href="https://hexdocs.pm/elixir/v1.10/ /Kernel.html" />`
=> Fix canonical link in HTML docs

lib/elixir/lib/keyword.ex
Previously it would return something like this:
** (FunctionClauseError) no function clause matching in anonymous fn/1 in Keyword.keys/1
The following arguments were given to anonymous fn/1 in Keyword.keys/1:
{"fetch/2", {:fetch, 2}}
Closes #10010, and it improves 3fd68ef62a90f3b914ed2e881e5d152431f78bbc
=> Raise ArgumentError in Keyword.keys when list is not a keyword list

lib/elixir/lib/enum.ex, lib/elixir/lib/kernel.ex, lib/elixir/pages/operators.md, lib/ex_unit/test/ex_unit/assertions_test.exs
- Use "less-than", "greater-than", and "equal to" operators. This the actual name used by Wikipedia and Unicode.
- Give a name to every opertor in Kernel. Mention it at the beggining of the first paragraph, so it appears in the summary.
- Minor improvements here and there.
=> Improve Operators documentation

lib/elixir/lib/map.ex
Hello.
I was training a new person today and he was very confused on the &(&...) syntax for updating in Map.update.
I have changed the first example to use the full lambda syntax so that it is more clear that the argument should be a regular lambda with an output and that the value is set to the return value of this function.
=> Update Map.update example to use full lambda syntax on first example

lib/elixir/lib/map.ex
* It removes the concept of the "get" value (which should have been "gotten" IMO).
* Renames "initial" argument to "default"
* Makes use of the concept of "current value" which was already present in some functions, and uses this in the examples and the specs consistently
=> Make spec clearer for update functions in Map

lib/mix/lib/mix/tasks/cmd.ex, lib/mix/test/mix/tasks/cmd_test.exs
currently there is a bug when we run `mix cmd --app foo --app bar pwd`, only the first app option will be used.
This PR fix this. This is my first PR to Elixir so please let me know if there is anything I missed. I have ran `make format` and `make test`
=> fix bug of only taking first app option in mix cmd

lib/elixir/lib/path.ex
I think it is appropriate to change the current example so as to avoid any misleading interpretation.
=> Fix ambiguity on Path.expand/1 docs

lib/elixir/lib/dict.ex, lib/elixir/lib/hash_dict.ex
To be consistent with recently introduced changes: #10228, #10223
=> Rename "initial" argument to "default" in Dic and HashDict

lib/ex_unit/lib/ex_unit.ex, lib/ex_unit/lib/ex_unit/case.ex, lib/ex_unit/lib/ex_unit/cli_formatter.ex
- Include file:line to slowest test results.
Additionally it changes the order of the module, so it is consistent with the rest
of the results.
- Print line number while test is being executed.
- Sort struct and spec fields alphabetically.
Related: fbfc8d2fd04c97c7fbfe7e35a482f76b67fbe3a4, #10232
=> Additional changes to ExUnit trace

lib/elixir/lib/code/typespec.ex, lib/elixir/test/elixir/typespec_test.exs
Originally reported in ExDoc.
https://github.com/elixir-lang/ex_doc/issues/1239
Code.Typespec.spec_to_quoted/2 wouldn't know how to deal with a union inside a
map with __struct__ key, such as in:
`@spec foo(%{__struct__: Foo | Bar}) :: any()`
/cc @ericmj @zdcthomas
=> Fix Code.Typespec.spec_to_quoted/2 when union in  %{__struct__:} is used

lib/elixir/lib/access.ex, lib/elixir/test/elixir/access_test.exs
As discussed in https://groups.google.com/d/msgid/elixir-lang-core/3a5d1489-dfa5-4c0c-bcd1-5cb85eac2f3fn%40googlegroups.com.
This exception is a copy-paste of `Enum.OutOfBoundsError`. Makes me wonder if they should be joined into a single unprefixed `OutOfBoundsError` at some point. There is only an unprefixed version of `KeyError`, for example.
=> Add `Access.at!`

lib/logger/lib/logger.ex
I believe the `:info, :info` part was a bit confusing followed by `:warning` therefore skipping `:notice`.
Thank you for reviewing!
=> Make sentence about log levels more clear

lib/mix/lib/mix/tasks/cmd.ex
Noticed this was already backported to 1.10.4, so if that was intentional, let's update the docs :)
(PS. Should I set the base to v1.10?)
=> Fix since doc for mix cmd task

lib/elixir/lib/io/ansi/docs.ex, lib/elixir/test/elixir/io/ansi/docs_test.exs
Small issue when trying to include "|" character inside a table cell in docstring. There already is `String.replace("\\\|", "|")` inside `render_column/2` that I guess is supposed to convert escaped vertical bar back into "|" but `split_into_columns/2` does not check for escapes.
=> Fix not being able to escape "|" inside a table (docstring)

lib/eex/test/eex/tokenizer_test.exs
Recently introduced in afa6d0c17736cac1ad534b056d3c1ce70bb77e63
=> Fix typo in test name

lib/elixir/lib/code.ex
`tokens_to_quoted` got recently updated to include column in addition to line number [here](https://github.com/elixir-lang/elixir/commit/e1e8f9afec953b39e4c850d57e051aae42742d21#diff-eae311b342cce703529f4fd9e82d6c03R357)
Because of this spec for `string_to_quoted` no longer matched the return from `tokens_to_quoted` causing dialyzer errors.
Found by https://github.com/michallepicki/elixir-lang-dialyzer-runs/runs/982880951?check_suite_focus=true
=> Update string_to_quoted spec

lib/elixir/lib/system.ex
System.os_time, System.schedulers, System.schedulers_online were added in 1.3.0, which i know because i tried to use them on an earlier system.
=> adds @since to the System module

lib/elixir/lib/supervisor.ex
Nit picking, but why not?
Alternatives considered:
- The child specification is a map **which contains 2–6** elements.
- The child specification is a map **which contains 2 to 6** elements.
- The child specification is a map **which may contain up to** 6 elements.
- The child specification is a map **containing up to** 6 elements.
=> make Child Specification section of Supervisor documentation a bit more accurate

lib/elixir/lib/string.ex
The `String#myers_difference/2` function was created by df5ac21cb469d7f8b5710fb5615ed378233ce6be on v1.3.0 :)
=> Add since doc to String#myers_difference/2

lib/elixir/lib/kernel/typespec.ex, lib/elixir/test/elixir/typespec_test.exs
This PR updates `Typespec.deftypespec/6` to raise a compilation error when trying to define reserved types such as `required/1` and `optional/1` with `@type`, `@typep` and `@opaque`.
Closes #10263
=> Raise CompileError when trying to define reserved types

lib/elixir/lib/protocol.ex
Just got bitten by this.
I am not sure this is the best place to put it nor the best wording. I do think it deserve a note.
In a protocol, the data structure we are abstracting need to be the first argument in all the protocol functions. Could not find it written in the doc elsewhere
=> Adds note: data structure in first position in Protocol

lib/elixir/lib/kernel.ex
Previously linking to `defprotocol/2` which contains no useful information and links to `Protocol`. Save reader one click.
=> Change link in "Protocols" section in Kernel docs

lib/elixir/lib/registry.ex
Following up on this short discussion: https://groups.google.com/forum/#!topic/elixir-lang-core/t7zzNkQgADA , this PR implements `Registry.delete_meta/2`.
I went for `:ets.delete`, I think it makes sense because `put_meta` uses unique keys even with a `:duplicate` registry.
---
I wasn't sure about adding a `@doc since:` annotation so I left it out for now.
Regarding tests, `put_meta` seems to only have doctests so I did the same here.
=> Add `Registry.delete_meta/2`

lib/logger/lib/logger/handler.ex, lib/logger/test/logger/handler_test.exs
HI,
Elixir integrate new log levels (notice, critical, alert, and emergency) but this information "_is lost for 'compatibility with pre 1.10 backends'_"
In logger/handler.ex there is a 'TODO':
_# TODO: Remove this mapping once we remove old Logger Backends (v2.0)_
So in the meantime is possible to maintain the original level information almost in the metadata inserting an additional key/value `{:erl_level, real_level}` in order to be able to post-process/filter logs by the 'real severity level'.
=> Include Erlang severity level to Logger metadata

lib/elixir/pages/operators.md
Currently how atoms are compared is not described in the Elixir docs, or at least (not where I would expect).
Sentence is copied from the erlang docs:
https://erlang.org/doc/reference_manual/expressions.html#term-comparisons
=> Document atom comparison

lib/elixir/lib/module/types.ex, lib/elixir/lib/module/types/expr.ex, lib/elixir/lib/module/types/helpers.ex, lib/elixir/lib/module/types/pattern.ex, lib/elixir/test/elixir/module/checker_test.exs, lib/elixir/test/elixir/module/types/pattern_test.exs, lib/elixir/test/elixir/module/types_test.exs
Instead of trying to assuming that a certain usage of a type is the correct one, we keep the unification message agnostic and add hints to the message.
Each message may have multiple hints, as they are computed alongside the trace. The traces are also reversed in order to keep the order they are added.
Here is how the new warning for dot access look like:
warning: incompatible types:
map() !~ atom()
in expression:
module.__struct__
where "module" was given the type map() (due to calling var.field) in:
module.__struct__
where "module" was given the type atom() in:
%module{}
HINT: "var.field" (without parentheses) implies "var" is a map() while
"var.fun()" (with parentheses) implies "var" is an atom()
Conflict found at
a.ex:4: A.a/1
And here is the hint for binaries:
warning: incompatible …
=> Introduce a type hint system

lib/elixir/src/elixir_tokenizer.erl, lib/elixir/test/elixir/code_formatter/operators_test.exs, lib/elixir/test/elixir/kernel/quote_test.exs, lib/elixir/test/erlang/tokenizer_test.erl
Closes #10311
I am not 100% sure I'm not introducing any side effect for alternative syntax, but seems to be fixing the issue without failing other tests.
Before/after the change:
```erlang
- [{identifier, {1, 1, nil}, '&'},
+ [{capture_op, {1, 1, nil}, '&'},
```
=> Fix `&//2` parsing issue

lib/mix/lib/mix/tasks/deps.compile.ex
There are basically two implementations of BSD make now, the NetBSD one (also used by FreeBSD, available as 'bmake' on Linux, macOS, etc), and the OpenBSD one.
=> Use 'gmake' instead of 'make' when compiling deps on NetBSD

lib/elixir/pages/patterns-and-guards.md
Many references to operators in this page were already navigable links, but not all. I tried to add them for easy navigation (especially the one saying "See the documentation for ").
=> Improve links in pattern matching page

lib/elixir/lib/map.ex
improves the wording of
> If `key` is present in `map` with value `value`
The problem with this phrase is that it can be interpreted that it will update a field where key and value are both matched.
beside that `value` argument no longer exists
It is a WIP because there are other sentences in the Map module to update once the wording is decided
=> Improve wording in Map module docs

lib/elixir/lib/system.ex
```
$ docker run -it -v $(pwd):/project elixir:1.3.0 bash
root@983045508faf:/# elixir -e "IO.puts System.otp_release"
19
```
```
$ docker run -it -v $(pwd):/project elixir:1.2.6 bash
root@af8db535bb1e:/# elixir -e "IO.puts System.otp_release"
** (UndefinedFunctionError) undefined function System.otp_release/0
(elixir) System.otp_release()
(stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
(stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
(stdlib) erl_eval.erl:404: :erl_eval.expr/5
(elixir) lib/code.ex:168: Code.eval_string/3
```
References:
- https://github.com/elixir-lang/elixir/commit/5533cc466559415f3ecd52424f2fa0371a56e0d4 - v1.3.0
- https://github.com/elixir-lang/elixir/commit/ea119f4c01cc158886ea432c7d7ffdfceefe9685 - v1.4.0 onwards
=> add "since" doc metadata to System.otp_release/0

lib/elixir/lib/registry.ex, lib/elixir/test/elixir/registry_test.exs
This PR fixes a bug which happens if a process started with `name: {:via, Registry, {registry_name, process_name, value}}` crashes during the startup. In this case, instead of the original error, a no function clause exception happens in the Registry module. Minimal example:
```
iex> Registry.start_link(keys: :unique, name: Foo)
iex> Agent.start_link(fn -> raise "foo" end, name: {:via, Registry, {Foo, :name, :value}})
** (EXIT from #PID<0.105.0>) shell process exited with reason: an exception was raised:
** (FunctionClauseError) no function clause matching in Registry.unregister_name/1
(elixir 1.10.2) lib/registry.ex:264: Registry.unregister_name({Foo, :name, :value})
```
=> Fix unregistration crash

lib/elixir/lib/module/types.ex, lib/elixir/lib/module/types/expr.ex, lib/elixir/lib/module/types/infer.ex, lib/elixir/lib/module/types/pattern.ex, lib/elixir/test/elixir/module/types/expr_test.exs, lib/elixir/test/elixir/module/types/infer_test.exs, lib/elixir/test/elixir/module/types/pattern_test.exs, lib/elixir/test/elixir/module/types/types_test.exs
Also document which functions must be changed once
new types are introduced and which functions must
handle them.
Make sure all of these functions comply to the spec
and improve performance for tuples.
=> Document all built-in types internally

lib/elixir/lib/file.ex
Elixir 1.1.0:
```
$ docker run -it hexpm/elixir:1.1.0-erlang-18.3.4-debian-stretch-20200224 bash
root@67c584a6bbed:/# elixir -e 'IO.inspect File.rename("", "")'
{:error, :enoent}
```
Elixir 1.0.5:
```
$ docker run -it hexpm/elixir:1.0.5-erlang-18.3.4-debian-jessie-20200224 bash
root@cb24db2cab8b:/# elixir -e 'IO.inspect File.rename("", "")'
** (UndefinedFunctionError) undefined function: File.rename/2
(elixir) File.rename("", "")
(stdlib) erl_eval.erl:670: :erl_eval.do_apply/6
(stdlib) erl_eval.erl:878: :erl_eval.expr_list/6
(stdlib) erl_eval.erl:404: :erl_eval.expr/5
(elixir) lib/code.ex:131: Code.eval_string/3
```
Reference:
- https://github.com/elixir-lang/elixir/commit/5d7a7ec7f9ad07944c46c1cbaf10efe923dc64c0 - v1.1.0-rc.0 onwards
=> add "since" doc metadata to File.rename/2

lib/elixir/lib/module/types.ex, lib/elixir/lib/module/types/expr.ex, lib/elixir/lib/module/types/helpers.ex, lib/elixir/lib/module/types/of.ex, lib/elixir/lib/module/types/pattern.ex, lib/elixir/lib/module/types/unify.ex, lib/elixir/test/elixir/module/types/map_test.exs
1. Move push_expr_stack to unify and keep helpers typing free
2. Add get_var! when accessing variables so it helps us find
variables that have not been properly processed
3. Properly process all variables found missing on step 2
=> More typing improvements

lib/elixir/lib/list.ex
Recently, I saw a Benchee benchmark between `List.last(list)` and `list |> Enum.reverse() |> hd()` with a list of 10_000 items, and, curiously, the reverse-then-hd was faster. The reverse-then-hd code used more memory than `List.last/1` due to building a new list, but was nearly twice as fast. I was curious if "skipping" some elements could improve the performance of `List.last/1`.
In the code below `list_last_orig/1` is the same implementation as `List.last/1` and `list_last8/1` is the same as `Last.last/1` except the for an additional first function head that pattern matches on and discards the first 8 elements of the list then recurses.
It turns out my idea worked. When the number of elements is 8 or more `list_last8/1` was always faster than `list_last_orig/1`. In about half of the …
=> Improved performance of List.last/1

lib/elixir/lib/task.ex
Per the discussion [here](https://elixirforum.com/t/clarification-on-ordered-for-task-async-stream/34482/2) on the forums, I have updated the docs of `Task.async_stream` to be a little more clear on why you may want to use `ordered: false`. This is my first draft at improving the wording, so if it still seems unclear let me know and I can do a little more editing.
=> Update docs of Task.async_stream to talk more about side effects

lib/elixir/lib/kernel.ex, lib/elixir/src/elixir_utils.erl, lib/elixir/test/elixir/kernel/guard_test.exs
https://github.com/elixir-lang/elixir/issues/10361.
This pull request adds the functionality to raise instead of crashing when trying to use list operators in guard clauses.
```
❯ bin/iex                                                                                                                                                                                                                                                                                                     19:57:43
Erlang/OTP 23 [erts-11.0.2] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe] [dtrace]
Interactive Elixir (1.12.0-dev) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> defmodule Foo do
...(1)>   def check(value) do
...(1)>     case value do
...(1)>       list when list ++ [1] -> …
```
=> Raise instead of crashing on when trying to use list operators in guards

lib/elixir/lib/string.ex
String.capitalize uppercases first letter.
Looks like a copy-paste mistake from the function above it :)
=> Fix copy paste mistake in String.capitalize docs

lib/elixir/lib/gen_server.ex
If we use the function, we don't need the comment explaining that the millis make up for 2 hours.
=> Use timer function instead of manually calculating milliseconds

lib/elixir/lib/file.ex
Addresses issue #10373 https://github.com/elixir-lang/elixir/issues/10373 
- Clarifies args passed to callback in File.cp/3 function
- improves general readability of this function's docs
=> Clarifies args passed to callback in File.cp/3 function; 

lib/elixir/lib/enum.ex
I was getting dialyzer errors when calling `min_by` and `max_by` arity 3.
```
Enum.min_by(matches, & &1.utc_start_time, DateTime)
lib/trailblazer_web/controllers/api/v1/match_controller.ex:56:call
The function call will not succeed.
Enum.max_by(_matches :: [any(), ...], (_ -> any()), DateTime)
breaks the contract
(t(), (element() -> any()), (() -> :empty_result)) :: element() | :empty_result
when empty_result: any()
```
=> Enum.max_by/3 and Enum.min_by/3 dialyzer fixes

lib/iex/lib/iex/server.ex
When the shell is respawned, as a result of `respawn/0`,` continue/0`, or taking a signal, the file given as `--dot-iex` argument is not evaluated. Worse, the default file (`./iex.exs` or `~/.iex.exs`) will be used if present.
The behaviour it is not consistent with normal use (no option and the default file).
=> Take --dot-iex into account after shell respawn

lib/logger/lib/logger/app.ex, lib/logger/test/logger_test.exs
The `config_change` callback is called from `application_controller` process,
which is receiving env updates on `Application.put_env`.
`Logger.configure` does a blocking call to the `Logger` process, which calls
`Application.put_env`
This causes a crash on logger config update.
If logs are synchronous, failing logger will call itself to report a crash and get stuck.
The issue happens in live upgrade with releases and due to high frequency of logs
the Logger switches to the sync mode and gets blocked, blocking all logging processes.
Removed `Logger.config` from config change. It cannot work anyway.
Main purpose of Logger.configure is to put env into the app config and
`config_change` is called when env is already updated.
```
> iex
Erlang/OTP 23 [erts-11.0.1] [source] [64-bit] [smp:12:12] …
```
=> Do not call Logger.configure on config_change callback.

lib/elixir/lib/string.ex, lib/elixir/test/elixir/string_test.exs, lib/elixir/unicode/properties.ex
EDIT: ~This PR fixes a little error in the current unconditional mapping of the "Latin capital letter i with dot above" in SpecialCasing.txt which has an error.~ SpecialCasing.txt is left to its original since its generated by Unicode.
It also adds proper handling of case manipulation of the letter i and its dotless version existing in the Turkish language.
Handling is now done according to the SpecialCasing.txt from here http://www.unicode.org/Public/UCD/latest/ucd/SpecialCasing.txt
=> Add :turkic mode option to String case functions

lib/elixir/lib/string.ex
A variable name `string2` in the docs for `String.equivalent?/2` were enclosed in single quotes instead of backticks, fix it.
=> Fix single quotes to backticks in string.ex

lib/elixir/lib/kernel.ex
> warning: this expression will fail with ArgumentError
>   (for doctest at) lib/kernel.ex:310
It was introduced in  538a9a3 (#10370)
=> Remove compilation warning in doctest in Kernel.binary_part/3

lib/elixir/lib/stream.ex
`:inline_list_funs` → `:inline_list_funcs` as per https://erlang.org/doc/man/compile.html#inlining-of-list-functions.
I believe this is the only instance.
=> Updated Enumerable implementation for Stream

lib/iex/lib/iex.ex, lib/iex/lib/iex/config.ex, lib/iex/lib/iex/evaluator.ex, lib/iex/lib/iex/server.ex
Fixes issue #10390 
Makes the IEx parser configurable through the IEx config so that
you can define your own parser if you wish.
=> Make IEx parser customizable

lib/elixir/lib/module/types/expr.ex
Fixes small mistake detected by dialyzer:
```
lib/module/types/expr.ex:257: The pattern 
{'error', _reason@1} can never match the type 
'error'
lib/module/types/expr.ex:281: The pattern 
{'error', _reason@1} can never match the type 
'error'
```
=> Fix returning errors in Module.Types.Expr.of_expr

lib/elixir/lib/inspect.ex
I think, to avoid confusion of MapSet being a Dict.
=> Rename a variable in Inspect documentation

lib/mix/lib/mix/compilers/application_tracer.ex
It was missing a closing square bracket.
Previously it was saying
3. In case you don't want to add a requirement to :crypto, you may optionally skip this warning by adding [xref: [exclude: :crypto] to your "def project" in mix.exs
Now
3. In case you don't want to add a requirement to :crypto, you may optionally skip this warning by adding [xref: [exclude: :crypto]] to your "def project" in mix.exs
=> Fix warning message in app requirement

lib/elixir/src/elixir_expand.erl, lib/elixir/test/elixir/kernel/warning_test.exs
The original goal[1] was to deprecate the usage of `super` on every `GenServer`
callback, but `child_spec/1` is not a callback, it's a default implementation
that can be re-implemented.
This commit removes the _deprecation warning_ when someone use `super` in
`GenServer.child_spec/1`.
Fixes: #10415
[1] https://github.com/elixir-lang/elixir/commit/c024b0eeb2dc69a759fe5ceeb1c8216d58ae9386#diff-ed0344c13ed25389035f337d94902894R301-R316
=> bugfix(elixir): Do not show warning when `super` is in `GenServer.child_spec/1`

lib/elixir/lib/enum.ex, lib/elixir/lib/stream.ex, lib/elixir/test/elixir/enum_test.exs, lib/elixir/test/elixir/stream_test.exs
This is my first stab at this so comments very welcome. 
Feature Request thread is here: https://groups.google.com/u/1/g/elixir-lang-core/c/mwBRUILsVHA
My basic approach was that the current zip/1 and zip/2 functions can be implemented by zip_with by doing this:
```elixir
zip(enums) do
zip_with(enums, &List.to_tuple/1)
end
```
To implement zip_with/2 the zip_fun you pass to it will get a list of each of the elements from each enumerable we are zipping. This seemed okay, but it differs from what zip/3 does, where each element from the collection being zipped is a different argument to the zipping fun.
I think that's okay but happy to change them to both be consistent with each other.
=> Implements Enum.zip_with and Stream.zip_with

lib/elixir/lib/enum.ex
Wrong spec was detected by Dialyzer:
lib/enum.ex:3248: The call 'Elixir.Enum':zip_with
([any(), ...],
fun((_) -> any())) breaks the contract 
(t(), fun((term(), term()) -> term())) -> [term()]
=> Fix spec for Enum.zip_with/2

lib/logger/lib/logger.ex
The example for using a custom erlang logger handler is invalid, the handler must be enclosed in a tuple.
In version 1.11 it is already fixed for people still using 1.10 the documentation can be misreading.
=> Fix invalid example for using erlang logger handler

lib/ex_unit/lib/ex_unit/callbacks.ex, lib/ex_unit/test/ex_unit/supervised_test.exs
=> Fix stop_supervised/1 for temporary children

lib/mix/lib/mix/tasks/release.init.ex
I keep running into #9835 when testing releases locally. This change fixes it without user intervention.
I considered piping the output of `cd` into `/dev/null`, but it struck me `CDPATH=''` was cleaner. WDYT?
=> Unset CDPATH while finding RELEASE_ROOT

lib/elixir/lib/kernel.ex
The explanation of the functions and the usage example are inconsistent.
They raise a `BadBooleanError` instead of an `ArgumentError`.
=> Fix docs for Kernel#and/2 and Kernel#or/2

lib/elixir/lib/system.ex
1.Remove the additional word 'can'.
2.Add the System.convert_time_unit(1, :second, :native) return value so people have clear idea about  the two units.
=> update function convert_time_unit document

lib/mix/lib/mix/tasks/release.ex
In the case where a mix release's results are owned by a different user than the one booting it, the binaries should be executable by anyone who can also read them.
=> mix release: anyone who can read can execute

lib/elixir/lib/config/reader.ex
I mindlessly copied this line and was wondering why it didn't work :D
=> Fix typo in documentation

lib/elixir/src/elixir_env.erl, lib/elixir/src/elixir_expand.erl, lib/elixir/test/elixir/kernel/warning_test.exs
When rebinding a variable that is not later used, the warning
proposes to use the pin operator.
Fixes #10478
=> Propose Pin Operator with Unused Overridden Variable

lib/mix/lib/mix/tasks/escript.build.ex
This is just small change to the documentation to avoid copy-paste errors due to the single quotes.
Not saying this just happened to me, of course! /s
=> Fix mix escript.build docs

lib/elixir/lib/file.ex
`:compressed` is already passed through and supported here so that gzipped files can be streamed with e.g. `File.stream!("log.gz", [:compressed])`
Adding it to the spec also makes dialyzer happy when actively using it.
=> Add :compressed to stream_modes spec

lib/elixir/lib/enum.ex, lib/elixir/test/elixir/enum_test.exs
Inspired by #10491
/cc @Strech 
```
$ mix run benchmarks/enumerable.exs 
Operating System: Linux
Number of Available Cores: 8
Available memory: 7.56 GB
Elixir 1.11.2
Erlang 23.0.4
Benchmark suite executing with the following configuration:
warmup: 2 s
time: 2 s
memory time: 0 ns
parallel: 1
inputs: list_empty, list_100, list_10_000, map_empty, map_100, map_10_000
Name                                     ips        average  deviation         median         99th %
patched: Enum.Patched.empty?/1      282.41 M        3.54 ns ±51809.11%           0 ns           0 ns
original: Enum.empty?/1             123.23 M        8.11 ns ±48821.41%           0 ns           0 ns
Comparison: 
patched: Enum.Patched.empty?/1      282.41 M
original: Enum.empty?/1             123.23 M - 2.29x slower +4.57 ns …
```
=> Optimize Enumerable.slice/1 for lists and maps

lib/mix/lib/mix.ex, lib/mix/lib/mix/cli.ex, lib/mix/lib/mix/exceptions.ex, lib/mix/test/mix/cli_test.exs, lib/mix/test/test_helper.exs
It is sometimes useful and desirable to have different exit code on
different errors (for example 1 on server error, 2 on connection error,
and so on). This change adds new field to the `Mix.Error` exception -
`code` that will be then used as an exit code value.
=> Allow setting custom exit code on Mix error

lib/elixir/lib/regex.ex
This PR postpones the call to `precompile_replacement/1` until `safe_run` identifies a match
- Background
We had a slow Plug endpoint on production. (p99 ~400ms)
In this endpoint, we'll read a file and then call `Regex.replace` on everyline in this file.
By profiling this endpoint with `fprof`, we found the bottleneck is this `precompile_replacement/1` function inside a `Regex.replace` call. 
Then we added a `Regex.match?` check before calling `Regex.replace`. 
This optimization sped up the replace operation for at most 100ms (which is a ~30KB file with ~1500 lines that contain no matches, i.e. `Regex.replace` would be called 1500 times and all of them are no matches)
We also tried using Erlang's `:re.replace` directly, which yielded a similar result (100ms boost for the worst case). …
=> Speed up Regex.replace/4 when there is no match

lib/mix/lib/mix.ex
`Mix.raise/2` was introduced in https://github.com/elixir-lang/elixir/pull/10463 but by using default arguments, we were not making it at all clear that the `/2` version will only be available from 1.12.0. I'd rather have a couple more lines of code and be perfectly clear here. :)
=> Specify that Mix.raise/2 is available from 1.12+

lib/mix/lib/mix/tasks/deps.ex
This has been a repeated source of confusion and while the feature makes sense there's no note of the fact that this behavior occurs anywhere. Let me know if I should flesh this out a little more.
=> add note about optional mix dependencies not being started

lib/elixir/lib/kernel.ex, lib/elixir/test/elixir/kernel_test.exs
It complemments changes introduced in 30373382ec2183d316f14b6ec6a99225855c6d8d
=> Use one-based generated arguments everywhere

lib/mix/lib/mix/state.ex, lib/mix/test/mix/cli_test.exs
It seems that it's an easy mistake to set `$MIX_TARGET` to be empty
rather than unset it. The intention is to compile the project for the
host and it happens when switching between target and host. While this
seems like it should be easy to catch, it can trip up Nerves users since
Mix targets aren't well used in other contexts.
This commit also protects against `$MIX_ENV` being set to the empty
string for consistency.
Finally, tests were added for verifying that the mix targets gets set
and for the case that this code change addresses.
=> Default the mix target to :host when empty

lib/elixir/lib/enum.ex
It is not part of the Enumerable protocol
=> Hide Enumerable.List.slice/4 function
